### ISSUE TITLE
Travis CI: Old Android NDK

### ISSUE THREAD

**Issue by xsacha** [ruslo/hunter#1000]
Would it be possible to update the Android NDK used by default to something more modern? I feel like the lack of support in r10 is not indicative of the support a package has for Android.

A lot has changed since r10 such as universal headers, deprecation of GCC, proper clang support with proper STL and hence modern compiler support (i.e. c++17), OpenMP.

**Comment by ruslo** [comment]
I need to create minimal Android NDK and use it here:
* https://github.com/ruslo/polly/blob/3e46db7d97bfce5dfe0ca83d0a355c0929c97b39/bin/install-ci-dependencies.py#L126-L139

Default NDK archive is huge and we hit "no space left on device" errors on Travis. Will take a look.

**Comment by headupinclouds** [comment]
I'm looking forward to this too, but I would vote for waiting a little longer until ndk-r17 is released and a few remaining issues are sorted out:

https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md#ndk-r17

**Comment by ruslo** [comment]
Currently r15c and r16 beta 1 available:
* https://developer.android.com/ndk/downloads/index.html

@xsacha Do you think we should use r15c or it worth trying r16 beta?

**Comment by xsacha** [comment]
Probably not R16 since it is still beta.

**Comment by ruslo** [comment]
Toolchain `android-ndk-r15c-api-21-armeabi-v7a-neon-clang-libcxx` can be used in Hunter CI testing. GTest example:
* https://travis-ci.org/ingenue/hunter/builds/271282975

**Comment by xsacha** [comment]
Thanks!!

**Comment by xsacha** [comment]
Just a note that r16b1 (and future versions) don't work on CMake 3.7 - 3.9.1. They require 3.9.2 to work (which isn't available yet).
