### ISSUE TITLE
Add "up-for-grabs" support

### ISSUE THREAD

**Issue by chfast** [ruslo/hunter#1003]
See: http://up-for-grabs.net/#/

- [x] Add <kbd>help wanted</kbd> label.
- [x] Mark some <kbd>new package</kbd> issues with <kbd>help wanted</kbd> label.
- [x] Add Hunter project description to up-for-grabs repo: https://github.com/up-for-grabs/up-for-grabs.net/pull/714.

**Comment by ruslo** [comment]
> Add up-for-grabs label in GitHub

What about "help wanted"? It's more understandable in my opinion.

**Comment by chfast** [comment]
Sure.

**Comment by ruslo** [comment]
Hunter part is ready.
