### ISSUE TITLE
QT compile error

### ISSUE THREAD

**Issue by wheybags** [ruslo/hunter#1012]
```
image/qjpeghandler.cpp: In function ‘bool read_jpeg_image(QImage*, QSize, QRect, QRect, int, Rgb888ToRgb32Converter, j_decompress_ptr, my_error_mgr*)’:
image/qjpeghandler.cpp:384:41: error: invalid conversion from ‘JSAMPROW {aka char*}’ to ‘uchar* {aka unsigned char*}’ [-fpermissive]
                     uchar *in = rows[0] + clip.x() * 3;
                                 ~~~~~~~~^~~~~~~~~~~~~~
image/qjpeghandler.cpp:389:41: error: invalid conversion from ‘JSAMPROW {aka char*}’ to ‘uchar* {aka unsigned char*}’ [-fpermissive]
                     uchar *in = rows[0] + clip.x() * 4;
                                 ~~~~~~~~^~~~~~~~~~~~~~
image/qjpeghandler.cpp:408:50: error: invalid conversion from ‘uchar** {aka unsigned char**}’ to ‘JSAMPARRAY {aka char**}’ [-fpermissive]
                 (void) jpeg_read_scanlines(info, &row, 1);
                                                  ^~~~
In file included from image/qjpeghandler.cpp:64:0:
/home/wheybags/.hunter/_Base/7202b63/2df0ae1/594d1c9/Install/include/jpeglib.h:1056:20: note:   initializing argument 2 of ‘JDIMENSION jpeg_read_scanlines(j_decompress_ptr, JSAMPARRAY, JDIMENSION)’
 EXTERN(JDIMENSION) jpeg_read_scanlines JPP((j_decompress_ptr cinfo,
                    ^~~~~~~~~~~~~~~~~~~
image/qjpeghandler.cpp: In function ‘bool write_jpeg_image(const QImage&, QIODevice*, int, const QString&, bool, bool)’:
image/qjpeghandler.cpp:602:26: error: invalid conversion from ‘uchar* {aka unsigned char*}’ to ‘JSAMPROW {aka char*}’ [-fpermissive]
         row_pointer[0] = new uchar[cinfo.image_width*cinfo.input_components];
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
image/qjpeghandler.cpp:605:39: error: invalid conversion from ‘JSAMPROW {aka char*}’ to ‘uchar* {aka unsigned char*}’ [-fpermissive]
             uchar *row = row_pointer[0];
                          ~~~~~~~~~~~~~^
```
gcc version 6.3.0

**Comment by ruslo** [comment]
I think there are 3 errors here:

1. Seems that JPEG update broke some stuff. See [this change](https://github.com/hunter-packages/jpeg/pull/1) (note that CI is working). Affect OpenCV already: https://github.com/ruslo/hunter/pull/986#issuecomment-326737616 @xsacha +cc

2. If Qt is using JPEG library installed by Hunter then there should be `hunter_add_package(Jpeg)` in scheme

3. Qt is built with own copy of JPEG (see `-qt-libjpeg`) so actually Qt should not use JPEG headers from Hunter (Qt bug?)

**Comment by xsacha** [comment]
I think OpenCV, dlib and Qt allow the option of linking to an existing (i.e. hunter) image library (jpeg/png/gif) or building it from source.

In Qt, the option is -system-libjpeg vs -qt-libjpeg.
In OpenCV, the option is WITH_JPEG without BUILD_JPEG

Building it from source is troublesome as the linker will often complain that there are multiple versions of the same symbol in the situation you have both Hunter and an in-package version of the library.

Should it be enforced to use only Hunter libraries and not have the option of BUILD_JPEG, BUILD_PNG etc (i.e. in-package)?

**Comment by ruslo** [comment]
> In OpenCV, the option is WITH_JPEG without BUILD_JPEG

OpenCV is already hunterized so the only problem is JPEG headers.

> Should it be enforced to use only Hunter libraries and not have the option of BUILD_JPEG, BUILD_PNG etc (i.e. in-package)?

This check can be implemented in OpenCV hunterized fork.

> In Qt, the option is -system-libjpeg vs -qt-libjpeg.

I agree, we should use packages from Hunter. Such changes are quite fragile and require a lot of testing and manual checks. One by one pull requests with minimal change are welcome.

**Comment by ruslo** [comment]
Closing inactive discussion.
