### ISSUE TITLE
[hunter ** INTERNAL **] Unexpected MSVC_VERSION: '1911'

### ISSUE THREAD

**Issue by kwikness** [ruslo/hunter#1014]
Found a similar issue here https://github.com/ruslo/hunter/issues/696 but for a different VS version (VS Community 2017)

Where are all of you guys scoring paid versions of VS? Hook it up. :-P

Build output:
_>cmake ..
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.11.25507.1
-- The CXX compiler identification is MSVC 19.11.25507.1
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe
-- Check for working C compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe
-- Check for working CXX compiler: D:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.11.25503/bin/HostX86/x86/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [hunter] Calculating Config-SHA1
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] HUNTER_ROOT: C:/.hunter
-- [hunter] [ Hunter-ID: 435b09a | Config-ID: 61c532d | Toolchain-ID: 8743852 ]

**[hunter ** INTERNAL **] Unexpected MSVC_VERSION: '1911'**_

**Comment by ruslo** [comment]
https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs

```
Update to latest Hunter URL/SHA1 and check that issue you have hit is not already fixed/reported
```

**Comment by kwikness** [comment]
thanks. updated the version in the project i'm building to v0.19.91 and got past this
