### ISSUE TITLE
jenkins.py --verbose flag is not used

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#1016]
> NeroBurner: the script jenkins.py has a flag --verbose, but this flag is never used. Maybe we could add a flag --cropped or --short-log or --crop-output instead of changing jenkins.py for each project which generates too much output

> ruslo: It will be easier to add VERBOSE=1 environment variable to CI config and read it in jenkins.py.

reference: https://github.com/ingenue/hunter/pull/120#issuecomment-326962928

should we remove the --verbose flag? we also could do both: as default crop output, if argument --verbose or envrionment variable `VERBOSE=1` is set print everythin

**Comment by ruslo** [comment]
> should we remove the --verbose flag?

Yes

> we also could do both: as default crop output, if argument --verbose or envrionment variable VERBOSE=1 is set print everythin

I think `VERBOSE=1` will be enough. It was used only for Travis where we have log size limit. I don't think it make sense to provide similar funtionality on local user's machine.

**Comment by NeroBurner** [comment]
should `VERBOSE=1` or `VERBOSE=0` the default?

**Comment by ruslo** [comment]
`VERBOSE=1` wherever possible, `VERBOSE=0` is quite uninformative.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/commit/7df06527ea9b33f8188edf983709767afb171e7f
https://github.com/ruslo/hunter/commit/fdbc71ae6c4eb1490dbb39c9d5628cc4e9542d3d
