### ISSUE TITLE
Travis CI on Linux is currently broken

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#1021]
Linux images update:
* https://blog.travis-ci.com/2017-08-29-trusty-image-updates

Current issue:
* https://github.com/travis-ci/travis-ci/issues/8363#issuecomment-327909904

Cancelled builds (to restart later):
* https://travis-ci.org/ingenue/hunter/builds/272937751
* https://travis-ci.org/ingenue/hunter/builds/272381382

**Comment by xsacha** [comment]
What is the blocker on this right now?

**Comment by ruslo** [comment]
Mess with the PATH.

**Comment by ruslo** [comment]
Workaround https://github.com/ruslo/hunter/commit/8a950294b6574d8973af4cd1a33f955609f3e5c7
