### ISSUE TITLE
Regression that prevents running Hunter on Android host

### ISSUE THREAD

**Issue by xsacha** [ruslo/hunter#1024]
I just tried building a package on Android that used to work, with the latest version of Hunter and received a python error telling me my system does not support Sem_Open, from this  file:
~/.hunter/_Base/Download/Hunter/0.19.84/9086d4b/Unpacked/scripts/link-all.py

It seems that the multiprocessing.Pool has a hard dependency on sem_open, which is not available on Android and perhaps other platforms.

The solution I found was to use multiprocessing.pool.ThreadPool instead. It uses plain threads instead of spawning new processes.

After resolving that, it tells me that, in the same file, module 'os' has no attribute called 'link'.

**Comment by ruslo** [comment]
Currently `link-all.cmake` script returns error if `link-all.py` failed. It make sense for such cases to return warning and try to use next approach (`/bin/bash`, then `file(COPY ...)`):
* https://github.com/ruslo/hunter/blob/237878f79b8152fce382f33f991c78d11a99f893/scripts/link-all.cmake#L71-L73

Can you try:
```cmake
if(result EQUAL 0)
  return()
endif()
message(WARNING "... link-all.py failed ...")
```
?

**Comment by xsacha** [comment]
I changed os.link to os.symlink and it seems to be working from that (combined with Thread pool).

**Comment by ruslo** [comment]
> I changed os.link to os.symlink

It's kind of different. `os.link` is almost the same as copying, `os.symlink` is not.

**Comment by xsacha** [comment]
Is this only on OSX or is it true of Linux as well? I am using Linux (Android).

**Comment by xsacha** [comment]
Ah ok. Any idea why I wouldn't be able to do this on Android?

**Comment by ruslo** [comment]
> Any idea why I wouldn't be able to do this on Android?

It's not about Android, it's about your host system. Something wrong with installed Python.

**Comment by xsacha** [comment]
My host system is Android (Termux)

**Comment by xsacha** [comment]
Looks like hardlinking has been blocked since Marshmallow.
https://code.google.com/archive/p/android-developer-preview/issues/3150

Is copying the file the only workaround for these situations?

**Comment by ruslo** [comment]
> My host system is Android (Termux)

Oh... okay, I see.

> Is copying the file the only workaround for these situations?

I see no other options.

**Comment by xsacha** [comment]
Bringing this issue back again,
I managed to get this working on Termux by disabling this section of code recommended by you on gitter.im:
https://github.com/ruslo/hunter/blob/master/scripts/link-all.cmake#L48

I would make a pull request, but I'm not sure sure what to check for.

At first I thought:
`if (ANDROID AND NOT CMAKE_CROSSCOMPILING)`
but then.. what if I am cross-compiling? We would have the same issue again and I can't find out the host. CMAKE_SYSTEM_NAME is Linux.

**Comment by ruslo** [comment]
https://gitter.im/ruslo/hunter?at=5b17ecb793dc78791cb76001

**Comment by ruslo** [comment]
@xsacha fixed by https://github.com/ruslo/hunter/pull/1466 ?

**Comment by xsacha** [comment]
Yes, fixed
