### ISSUE TITLE
Boost iostreams build error on Cygwin

### ISSUE THREAD

**Issue by ckaminski** [ruslo/hunter#1025]
Key bits seem to be: ```

/home/Chris Kaminski/.hunter/_Base/4b72d50/392e13c/95c862d/Build/Boost/__iostreams/Source/tools/build/src/build/ac.jam:239: in construct
*** argument error
* rule ac.find-include-path ( properties : header : provided-path ? )
* called with: ( object(property-set)@1918 : zlib.h : /home/Chris Kaminski/.hunter/_Base/4b72d50/392e13c/95c862d/Install/include )
* extra argument Kaminski/.hunter/_Base/4b72d50/392e13c/95c862d/Install/include
/home/Chris Kaminski/.hunter/_Base/4b72d50/392e13c/95c862d/Build/Boost/__iostreams/Source/tools/build/src/build/ac.jam:40:see definition of rule 'ac.find-include-path' being called
/home/Chris Kaminski/.hunter/_Base/4b72d50/392e13c/95c862d/Build/Boost/__iostreams/Source/tools/build/src/build/targets.jam:1353: in class@basic-target.generate
/home/Chris Kaminski/.hunter/_Base/4b72d50/392e13c/95c862d/Build/Boost/__iostreams/Source/tools/build/src/build/targets.jam:774: in generate-really
/home/Chris Kaminski/.hunter/_Base/4b72d50/392e13c/95c862d/Bmake[2]: *** [CMakeFiles/Boost-iostreams.dir/build.make:115: Boost-iostreams-prefix/src/Boost-iostreams-stamp/Boost-iostreams-build] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/Boost-iostreams.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
uild/Boost/__iostreams/Source/tools/build/src/build/targets.jam:746: in class@main-ta 
```

My understanding is that bzip/lzip is off by default on Windows, and adding them with hunter_add_package does not seem to resolve the issue.  

I'm a cmake novice, so it's quite possible I'm not doing something right. 

Error output: 
https://gist.github.com/ckaminski/011b2097b423172632185f28fc52575f
Project:
https://github.com/ckaminski/hunter-cmake-template

**Comment by ruslo** [comment]
```
/home/Chris Kaminski/.hunter/_Base/4b72d50/392e13c/95c862d/Build/Boost/__iostreams/Source/tools/build/src/build/ac.jam:239: in construct
*** argument error
* rule ac.find-include-path ( properties : header : provided-path ? )
* called with: ( object(property-set)@1918 : zlib.h : /home/Chris Kaminski/.hunter/_Base/4b72d50/392e13c/95c862d/Install/include )
* extra argument Kaminski/.hunter/_Base/4b72d50/392e13c/95c862d/Install/include
```
As far as I understand it's a Boost error.

**Comment by ckaminski** [comment]
Having a much better idea with Hunter and Boost now than two weeks ago, I'll be revisiting this on my vacation this weekend and see if it's not just user-error.  :-)

**Comment by ruslo** [comment]
Closing inactive.
