### ISSUE TITLE
 include could not find load file: hunter_status_debug

### ISSUE THREAD

**Issue by ckaminski** [ruslo/hunter#1026]
I see the following error trying to hunter-ize nghttp2_asio, 

```
CMake Error at /home/ckaminski/.hunter/_Base/4b72d50/e1266bb/e726cd5/Install/lib/cmake/Boost/BoostConfig.cmake:5 (include):
  include could not find load file:

    hunter_internal_error
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:245 (find_package)
  CMakeLists.txt:239 (find_package)


CMake Error at /home/ckaminski/.hunter/_Base/4b72d50/e1266bb/e726cd5/Install/lib/cmake/Boost/BoostConfig.cmake:6 (include):
  include could not find load file:

    hunter_status_debug
```

Top of CMakeLists.txt: 
```
cmake_minimum_required(VERSION 3.0)
# XXX using 1.8.90 instead of 1.9.0-DEV

include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.19.80.tar.gz"
    SHA1 "4b72d50fef98189bad4bb098f53bc8893cb46519"
)

project(nghttp2 VERSION 1.25.0)

hunter_add_package(Boost COMPONENTS system thread)
hunter_add_package(libxml2)
hunter_add_package(ZLIB)
```

This near-exact same setup (minus libxml2 and zlib) is working for another project of mine without these errors. 

Any guidance on what I'm doing wrong?  
https://github.com/ckaminski/nghttp2/tree/v1.25.0-hunter 
Building on Ubuntu 16.04.

**Comment by ruslo** [comment]
Looks like some module removing Hunter specific path from CMAKE_MODULE_PATH list. Can you print value of CMAKE_MODULE_PATH before/after each `hunter_add_package` call?

**Comment by ckaminski** [comment]
CMAKE_MODULE_PATH /home/ckaminski/.hunter/_Base/Download/Hunter/0.19.80/4b72d50/Unpacked/cmake/modules;/home/ckaminski/.hunter/_Base/Download/Hunter/0.19.80/4b72d50/Unpacked/cmake/find
CMAKE_MODULE_PATH /home/ckaminski/.hunter/_Base/Download/Hunter/0.19.80/4b72d50/Unpacked/cmake/modules;/home/ckaminski/.hunter/_Base/Download/Hunter/0.19.80/4b72d50/Unpacked/cmake/find
CMAKE_MODULE_PATH /home/ckaminski/.hunter/_Base/Download/Hunter/0.19.80/4b72d50/Unpacked/cmake/modules;/home/ckaminski/.hunter/_Base/Download/Hunter/0.19.80/4b72d50/Unpacked/cmake/find
CMAKE_MODULE_PATH /home/ckaminski/.hunter/_Base/Download/Hunter/0.19.80/4b72d50/Unpacked/cmake/modules;/home/ckaminski/.hunter/_Base/Download/Hunter/0.19.80/4b72d50/Unpacked/cmake/find
CMAKE_MODULE_PATH /home/ckaminski/.hunter/_Base/Download/Hunter/0.19.80/4b72d50/Unpacked/cmake/modules;/home/ckaminski/.hunter/_Base/Download/Hunter/0.19.80/4b72d50/Unpacked/cmake/find


```

message("CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}")
hunter_add_package(Boost COMPONENTS system thread)
message("CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}")
hunter_add_package(libxml2)
message("CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}")
hunter_add_package(ZLIB)
message("CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}")
hunter_add_package(pthread-stubs)
message("CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH}")

```

**Comment by ruslo** [comment]
> set(CMAKE_MODULE_PATH "${CMAKE_MODULE_PATH};${CMAKE_CURRENT_SOURCE_DIR}/cmake" )

Use `list(APPEND ...)`:
* http://cgold.readthedocs.io/en/latest/tutorials/cmake-sources/includes.html#modify-correct

**Comment by ckaminski** [comment]
Thank you, still mostly a cmake newb.
