### ISSUE TITLE
[hunter ** INTERNAL **]  error！

### ISSUE THREAD

**Issue by jackz-jones** [ruslo/hunter#1029]
cmake：v3.8.1
OS：win7 Ultimate
command：cmake -G "Visual Studio 14 2015 Win64" .. 
the first error message：
[hunter ** INTERNAL **] Compilation of C:/.hunter/_Base/Download/Hunter/0.19.97/d4fc452/Unpacked/scripts/ShowPredefined.cpp failed. Result: FALSE

**Comment by ruslo** [comment]
> Compilation of ... failed. Result: FALSE

There should be `OUTPUT BEGIN ... OUTPUT END` message.

Are you able to build [simple project](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs)?

**Comment by jackz-jones** [comment]
yeah！It's successful to build the “Hello World”，and others seem to be ok。the details ：
--- OUTPUT BEGIN ---
Change Dir: E:/cpp-ethereum/build/_3rdParty/Hunter/toolchain/_builds/_test/CMakeFiles/CMakeTmp

here are some VS errors，like that：
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(100): error C2737:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(100): error C2998:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(245): error C2737:
and so on...

--- OUTPUT END ---
[hunter ** INTERNAL **] [Directory:E:/cpp-ethereum/build/_3rdParty/Hunter/toolchain]

**Comment by ruslo** [comment]
> C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xtr1common(100): error C2737:

https://stackoverflow.com/a/43824371/2288008 ?

**Comment by ruslo** [comment]
Closing inactive discussion.
