### ISSUE TITLE
The hash value does not match.

### ISSUE THREAD

**Issue by DubrovinLeo** [ruslo/hunter#1032]
cmake version 3.9.1
msys2
```
curl 7.55.1 (x86_64-w64-mingw32) libcurl/7.55.1 OpenSSL/1.0.2l zlib/1.2.11 libidn2/2.0.4 libssh2/1.8.0 nghttp2/1.23.1 librtmp/2.3
Release-Date: 2017-08-14
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile SSPI Kerberos SPNEGO NTLM SSL libz TLS-SRP HTTP2 HTTPS-proxy Metalink
```

My CMakeLists.txt :
```
cmake_minimum_required(VERSION 3.0)

include("HunterGate.cmake")
HunterGate(
        URL "https://github.com/ruslo/hunter/archive/v0.19.98.tar.gz"
        SHA1 "e9906a08a9778759a7c590fccff0703bca72dceb"
)

project(mychip8)
set(CMAKE_CXX_STANDARD 11)

hunter_add_package(SDL2)
find_package(SDL2 CONFIG REQUIRED)

set(${PROJECT_NAME}_SOURCES
        main.cpp
        )

add_executable(${PROJECT_NAME}
        ${${PROJECT_NAME}_SOURCES}
        )

target_link_libraries(${PROJECT_NAME}
        SDL2::SDL2main
        SDL2::SDL2)
```

Why in the next error hash values is different?

```
-- verifying file...
       file='C:/.hunter/_Base/Download/SDL2/2.0.4-p4/523d8fd/2.0.4-p4.tar.gz'
-- SHA1 hash of
    C:/.hunter/_Base/Download/SDL2/2.0.4-p4/523d8fd/2.0.4-p4.tar.gz
  does not match expected value
    expected: '523d8fd427f707541c7e600ad4c37e0e7bdc3662'
      actual: '589fcb46963b28e9d968646af54add6f4b19890c'
-- Hash mismatch, removing...
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://github.com/hunter-packages/SDL2/archive/2.0.4-p4.tar.gz'
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 3% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 6% complete]
-- [download 7% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 11% complete]
-- [download 12% complete]
-- [download 13% complete]
-- [download 14% complete]
-- [download 15% complete]
-- [download 16% complete]
-- [download 17% complete]
-- [download 18% complete]
-- [download 19% complete]
-- [download 20% complete]
-- [download 21% complete]
-- [download 22% complete]
-- [download 23% complete]
-- [download 24% complete]
-- [download 25% complete]
-- [download 44% complete]
-- [download 55% complete]
-- [download 56% complete]
-- [download 57% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 60% complete]
-- [download 61% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 65% complete]
-- [download 66% complete]
-- [download 67% complete]
-- [download 68% complete]
-- [download 69% complete]
-- [download 70% complete]
-- [download 71% complete]
-- [download 72% complete]
-- [download 74% complete]
-- [download 85% complete]
-- [download 86% complete]
-- [download 87% complete]
-- [download 88% complete]
-- [download 89% complete]
-- [download 90% complete]
-- [download 91% complete]
-- [download 92% complete]
-- [download 93% complete]
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- verifying file...
       file='C:/.hunter/_Base/Download/SDL2/2.0.4-p4/523d8fd/2.0.4-p4.tar.gz'
-- SHA1 hash of
    C:/.hunter/_Base/Download/SDL2/2.0.4-p4/523d8fd/2.0.4-p4.tar.gz
  does not match expected value
    expected: '523d8fd427f707541c7e600ad4c37e0e7bdc3662'
      actual: '589fcb46963b28e9d968646af54add6f4b19890c'
-- Hash mismatch, removing...
CMake Error at Build/SDL2-Release-prefix/src/SDL2-Release-stamp/download-SDL2-Release.cmake:157 (message):
  Each download failed!

    
    


mingw32-make.exe[3]: Leaving directory 'C:/.hunter/_Base/056b4bc/a041ee0/460f10c/Build/SDL2/Build'
mingw32-make.exe[2]: Leaving directory 'C:/.hunter/_Base/056b4bc/a041ee0/460f10c/Build/SDL2/Build'
mingw32-make.exe[1]: Leaving directory 'C:/.hunter/_Base/056b4bc/a041ee0/460f10c/Build/SDL2/Build'
mingw32-make.exe[3]: *** [CMakeFiles\SDL2-Release.dir\build.make:90: SDL2-Release-prefix/src/SDL2-Release-stamp/SDL2-Release-download] Error 1
mingw32-make.exe[2]: *** [CMakeFiles\Makefile2:67: CMakeFiles/SDL2-Release.dir/all] Error 2
mingw32-make.exe[1]: *** [Makefile:83: all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/056b4bc/a041ee0/460f10c/Build/SDL2
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.19.92/056b4bc/Unpacked/cmake/projects/SDL2]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.19.92/056b4bc/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.19.92/056b4bc/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.19.92/056b4bc/Unpacked/cmake/modules/hunter_download.cmake:596 (hunter_fatal_error)
  C:/.hunter/_Base/Download/Hunter/0.19.92/056b4bc/Unpacked/cmake/projects/SDL2/hunter.cmake:55 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.19.92/056b4bc/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:12 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/Lenz0/CLionProjects/mychip8/cmake-build-debug/CMakeFiles/CMakeOutput.log".
mingw32-make.exe: *** [Makefile:175: cmake_check_build_system] Error 1

```

**Comment by ruslo** [comment]
Kind of strange. SDL2 version `2.0.4-p4` checked here with `523d8fd...` hash:
* https://travis-ci.org/ingenue/hunter/jobs/259730486

Pull request:
* https://github.com/ruslo/hunter/pull/923

@wheybags Any chance that you have made release with same tag?

**Comment by DubrovinLeo** [comment]
But this happens not only with SDL. Same error appears when I try to include opencv to my project, but I successful attached glfw and glew.

**Comment by ruslo** [comment]
I've never seen such issues before. Maybe GitHub decided to re-create release archives for some internal reasons?

So summarize currently broken packages:
* OpenCV
  * Release https://github.com/hunter-packages/opencv/releases/tag/v3.3.0-p0
  * Pull request https://github.com/ruslo/hunter/pull/954
  * Travis build example https://travis-ci.org/ingenue/hunter/jobs/266525268
  * From Travis logs: `OpenCV/3.3.0-p0/fc35114` (meaning SHA1 of archive **was** `fc35114...`)
  * **Now** SHA1 of archive is `c6236c9ddf281aac42abe311e9525675005e3b91`
* SDL2
  * Release https://github.com/hunter-packages/SDL2/releases/tag/2.0.4-p4
  * Pull request https://github.com/ruslo/hunter/pull/923
  * Travis build example https://travis-ci.org/ingenue/hunter/jobs/259730486
  * From Travis log: `SDL2/2.0.4-p4/523d8fd` (meaning SHA1 of archive **was** `523d8fd...`)
  * **Now** SHA1 of archive is `589fcb46963b28e9d968646af54add6f4b19890c`

I will contact GitHub team.

**Comment by xsacha** [comment]
Is it possible to compare an old downloaded archive of these packages to a new downloaded archive and find the difference?

Maybe they changed the compression?

**Comment by ruslo** [comment]
> Is it possible to compare an old downloaded archive of these packages to a new downloaded archive and find the difference?

That's what I will try to do now. I will open separate issue for each case.

> Maybe they changed the compression?

For the archive that **already** released? This is huge problem for any kind of package manager, not only for Hunter.

**Comment by ruslo** [comment]
> I will open separate issue for each case

OpenCV: https://github.com/ruslo/hunter/issues/1034

**Comment by ruslo** [comment]
> I will open separate issue for each case

I have no old SDL2 archive on my machine.

@wheybags can you check if you have this archive?

Expected location:
* `~/.hunter/_Base/Download/SDL2/2.0.4-p4/523d8fd/2.0.4-p4.tar.gz`

Expected hash:
* `523d8fd427f707541c7e600ad4c37e0e7bdc3662`

**Comment by ruslo** [comment]
OpenCV will be updated (version, hence hash) here:
* https://github.com/ruslo/hunter/pull/986

SDL2 hash update:
* https://github.com/ruslo/hunter/pull/1038

**Comment by DubrovinLeo** [comment]
```
HunterGate(
        URL "https://github.com/ruslo/hunter/archive/v0.19.99.tar.gz"
        SHA1 "55ca271e9276b9973176e3f5a8c0d0dc25e46a53"
)
```
I use last archive, but it did not help

```
-- verifying file...
       file='C:/.hunter/_Base/Download/SDL2/2.0.4-p4/523d8fd/2.0.4-p4.tar.gz'
-- SHA1 hash of
    C:/.hunter/_Base/Download/SDL2/2.0.4-p4/523d8fd/2.0.4-p4.tar.gz
  does not match expected value
    expected: '523d8fd427f707541c7e600ad4c37e0e7bdc3662'
      actual: '589fcb46963b28e9d968646af54add6f4b19890c'
-- Hash mismatch, removing...
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/hunter-packages/SDL2/archive/2.0.4-p4.tar.gz'
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
...
```

**Comment by ruslo** [comment]
> I use last archive, but it did not help

It's not fixed yet, tests in progress. See links above.

**Comment by ruslo** [comment]
> I will contact GitHub team

Response is: archives are not stable. Nice, the fundamental assumption behind hosting Hunter project on GitHub is broken. Related discussions:
* https://github.com/Homebrew/homebrew-core/issues/18044
* https://github.com/libgit2/libgit2/issues/4343

**Comment by xsacha** [comment]
Do we now need a script that runs through every release ever published and finds the new hash for it?

I just ran in to Protobuf v3.0.0-p1 hash mismatch. New one is: 242443553ca20ab279427330e175a3c33ecbf265

**Comment by ruslo** [comment]
> Do we now need a script that runs through every release ever published and finds the new hash for it?

Feel free to send pull request with script or/and updates. Note that in general script should be CMake-syntax aware, e.g. Boost (likely not hosted on GitHub):
* https://github.com/ruslo/hunter/blob/0dc25c663ea30f597487912e4ed4c68eb78c7385/cmake/projects/Boost/hunter.cmake#L30-L40

Since we need to re-upload stuff please do it in "one package - one pull request" style.

**Comment by ilovezfs** [comment]
In case this is any help at all, these are the checksums we've needed to update for Homebrew so far:
https://github.com/Homebrew/homebrew-core/pull/18048
https://github.com/Homebrew/homebrew-core/pull/18055
https://github.com/Homebrew/homebrew-core/pull/18072
https://github.com/Homebrew/homebrew-science/pull/6317

**Comment by ruslo** [comment]
@ilovezfs Thanks for the info 👍

**Comment by ilovezfs** [comment]
@ruslo You're welcome :)

**Comment by ruslo** [comment]
> Do we now need a script that runs through every release ever published and finds the new hash for it?

Another solution will be to find (or generate?) archives with old hash and upload it to corresponding release. Then use new URL in `hunter.cmake`. This will work smooth for users and we don't have to re-upload binaries.

**Comment by skakri** [comment]
@ruslo Can we expect a new release soon-ish or you'd like to fix all checksums beforehand?

**Comment by ruslo** [comment]
@skakri Currently this issue is linked only to SDL2 and OpenCV. SDL2 is ready but OpenCV will take some time because it includes updating dependencies for new Android NDK r15c toolchain and local uploading from my machine because of Travis timeouts for iOS. So it you're in rush I recommend you not to wait but fix hashes of packages you're interested in your fork, release forked tag and use it.

**Comment by skakri** [comment]
That'll work but is there an option for passing harvested checksums some other way (for example some third party lib that is hosted on service _N_ or even in LAN (local GitLab); some page or API, or another program even, serves hash and Hunter compares those)? This situation somewhat shows that tie-in in one service (which we don't control, like GitHub) can shoot in one's leg.

I'm pretty sure that I'm just overreacting and/or don't understand some of the Hunter concepts. Sorry for off-topic and thank you for your work.

**Comment by ruslo** [comment]
> That'll work but is there an option for passing harvested checksums some other way (for example some third party lib that is hosted on service N or even in LAN (local GitLab); some page or API, or another program even, serves hash and Hunter compares those)? This situation somewhat shows that tie-in in one service (which we don't control, like GitHub) can shoot in one's leg.

Is this related https://github.com/ruslo/hunter/issues/521 ?

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.104
