### ISSUE TITLE
OpenCV archive hash mismatch

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#1034]
Details:
* https://github.com/ruslo/hunter/issues/1032#issuecomment-329116284

I've uploaded old release from my local machine:
* https://github.com/hunter-packages/opencv/releases/download/v3.3.0-p0/v3.3.0-p0-OLD-RELEASE.tar.gz
* `fc351142139be71b366458fa1572ab004c871774`

"New" release:
* https://github.com/hunter-packages/opencv/archive/v3.3.0-p0.tar.gz
* `c6236c9ddf281aac42abe311e9525675005e3b91`

**Comment by ruslo** [comment]
Content of both archives is identical.

**Comment by ruslo** [comment]
They have different sizes:

```
81243476 v3.3.0-p0-OLD-RELEASE.tar.gz
81243538 v3.3.0-p0.tar.gz
```

I can assume it means that difference is not about some magic internal stuff (like timestamp).

@xsacha I think you was correct about compression.

**Comment by gkontsevich** [comment]
I'm unsure if this is related. But I get a has mismatch for older versions of OpenCV

```
-- [download 94% complete]
-- [download 95% complete]
-- [download 96% complete]
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- verifying file...
       file='/home/gk/.hunter/_Base/Download/OpenCV/3.1.0-p3/d1f2356/v3.1.0-p3.tar.gz'
-- SHA1 hash of
    /home/gk/.hunter/_Base/Download/OpenCV/3.1.0-p3/d1f2356/v3.1.0-p3.tar.gz
  does not match expected value
    expected: 'd1f235600e454bcc3ce7d746b6b706e89ed81acc'
      actual: '5bb0fdede69ea004cdfb5b0e1f05915e41579e1e'
-- Hash mismatch, removing...
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://github.com/hunter-packages/opencv/archive/v3.1.0-p3.tar.gz'

```

and


```
-- [download 97% complete]
-- [download 98% complete]
-- [download 99% complete]
-- [download 100% complete]
-- verifying file...
       file='/home/gk/.hunter/_Base/Download/OpenCV/3.1.0-p2/2ad10c4/3.1.0-p2.tar.gz'
-- SHA1 hash of
    /home/gk/.hunter/_Base/Download/OpenCV/3.1.0-p2/2ad10c4/3.1.0-p2.tar.gz
  does not match expected value
    expected: '2ad10c43f8be723b604f1cfccce1f7840b7c39ed'
      actual: '289f2f286554191939976fee1b0791ab69aa89f2'
-- Hash mismatch, removing...
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://github.com/hunter-packages/opencv/archive/3.1.0-p2.tar.gz'
-- [download 0% complete]
```

However version 3.3.1-p1 works fine 

(are the "-pX" suffixes related to the hunterization versions?)

**Comment by ruslo** [comment]
Not all version are updated, seems that hash for `3.1.0-p2` is changed. If you have archive with `2ad10c43f8be723b604f1cfccce1f7840b7c39ed` hash you can upload it somewhere and I will add it to OpenCV release as custom asset (check your `~/.hunter/_Base/Download` directory). Otherwise just send the pull request with new hash.

> are the "-pX" suffixes related to the hunterization versions?

Yes. Since OpenCV has dependencies it should be hunterized.

**Comment by wheybags** [comment]
Should there be a regular CI job (say, run every night?) that downloads all
archives refererenced in hunter and verified their hashes? Because this
seems to have happened a few times now.

**Comment by ruslo** [comment]
> Should there be a regular CI job (say, run every night?) that downloads all archives refererenced in hunter and verified their hashes?

* I don't know how it will look in practice
* Change of SHA1 hash means that cache should be re-uploaded. Upload procedure is not automatic
* Changing SHA1 on regular basis sounds like very strange approach and raise the question of security/stability

> Because this seems to have happened a few times now.

First time for the 4 years of development. But since it was introduced by GitHub it affect some packages and all version of such packages.

**Comment by ruslo** [comment]
https://docs.hunter.sh/en/latest/faq/how-to-fix-hash-mismatch-error.html
