### ISSUE TITLE
double-conversion analyze toolchain failure.

### ISSUE THREAD

**Issue by isaachier** [ruslo/hunter#1037]
Assertion not enable during analyze build. Causes failure due to unchecked constraint.

**Comment by ruslo** [comment]
Can you add simple example?

**Comment by isaachier** [comment]
Yes. See this [diff](https://github.com/isaachier/double-conversion/commit/3c04013193563577bc4e67712e86f607ec6099ba#diff-e08abcccdfee202fef39ff8b406cf507R455). Essentially, the code does this operation:

`static_cast<uint64_t>(1) << (64 - bit_size)`

If `bit_size == 0`, the behavior is undefined. The reason is that a 64 bit unsigned integer can hold a maximum value of `(1 << 64) - 1`, and this would exceed the limit. Therefore, clang analysis fails here. The only way to ensure there is no undefined behavior is as follows:

```
assert(bit_size > 0);
... static_cast<uint64_t>(1) << (64 - bit_size) ...
```

However, during release builds, all assertions are disabled by default, so the clang analysis errors come back.

**Comment by ruslo** [comment]
See no errors:
* https://travis-ci.org/forexample/analyzer-issue-1037/builds/275375260

At least on Linux, waiting for OSX. Feel free to send pull request to reproduce an error.

**Comment by isaachier** [comment]
I am even having trouble reproducing the case from their docs. My guess is that the compiler was able to deduce that there was no problem here for some reason but not in a real library.

**Comment by isaachier** [comment]
@ruslo seems to have found workaround that fixes the issue in github.com/forexample/analyzer-issue-1037. Will try porting to double-conversion project when I have the chance.
