### ISSUE TITLE
Remove command 'project(Hunter)'

### ISSUE THREAD

**Issue by alamaison** [ruslo/hunter#104]
Hunterised projects get `C:\Program Files\Hunter` as the default `CMAKE_INSTALL_PREFIX`, instead of `C:\Program Files\<project name>`.  I only noticed this happening since updating to the latest HunterGate and moving the `HunterGate(...)` call before the call to `project(...)`, but I can be sure if they are related.

**Comment by ruslo** [comment]
Fixed in: https://github.com/ruslo/hunter/releases/tag/v0.9.3
Thanks for report!

**Comment by ruslo** [comment]
So I think it's better to avoid using internal undocumented CMake features :) There is more simplier solution:
* master file only modify `CMAKE_MODULE_PATH` and do `include(hunter_add_package)`
* on first `hunter_add_package` do init hunter-id, config-id, toolchain-id and other preparations

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/releases/tag/v0.11.7

@alamaison Now CMAKE_INSTALL_PREFIX should have correct value

@headupinclouds Now you can use variables like `ANDROID` in `config.cmake`. Also there is no need to use `@` in `if(@ANDROID@)`. It can be just `if(ANDROID)`.

**Comment by alamaison** [comment]
Excellent, thanks :)
