### ISSUE TITLE
Add 'lz4' package

### ISSUE THREAD

**Issue by roalz** [ruslo/hunter#1045]
Original website: http://lz4.github.io/lz4/
Original source repo: https://github.com/lz4/lz4

Strangely, I don't see lz4 included in the supported Hunter libraries, but there is a hunter-packages repo for it: https://github.com/hunter-packages/LZ4

**Comment by ruslo** [comment]
> I don't see lz4 included in the supported Hunter libraries, but there is a hunter-packages repo

I guess from here:
* https://github.com/ruslo/hunter/issues/389#issuecomment-223581774

**Comment by thakkardharmik** [comment]
@ruslo I would like to get involved. Please suggest.

**Comment by ruslo** [comment]
> > I don't see lz4 included in the supported Hunter libraries, but there is a hunter-packages repo

> I guess from here:

@headupinclouds I've moved repository to https://github.com/hunter-packages/LZ4-old. New repository https://github.com/hunter-packages/lz4 forked from official GitHub https://github.com/lz4/lz4.

> I would like to get involved. Please suggest

@thakkardharmik There is no CMake code in original repository. Project structure is trivial so it should be not so hard to add CMakeLists.txt with targets and install. Also there is already work-in-progress variant here: https://github.com/hunter-packages/LZ4-old. I've added you to the `lz4` team (check your email), you have permissions to write directly but for review reasons please open pull request with changes. Follow this guide:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.19.182
