### ISSUE TITLE
Current cache.sha1 creates URL incompatible with Artifactory

### ISSUE THREAD

**Issue by sgara** [ruslo/hunter#1046]
Hi there!
I'm trying to use Artifactory as cache repository for hunter, which looks quite promising. 
I do have one major issue though: to get the right artifact, we need to retrieve data from `{package}/{version}/..../cache.sha1`. This is interpreted by artifactory as "give me the sha1 for the file `{package}/{version}/..../cache` which obviously doesn't exist. So there is no way to upload the file (getting `no such file .../cache`) or to GET it.

I hacked my way through by copying the corresponding `{sha1}.tar.bz2` file to `.../cache` (so it can work theoretically but it would be great to have a more robust solution.

A possible solution would be to rename `cache.sha1` to something else, although it might introduce breaking changes or legacy code to support current structure... Any ideas?

**Comment by ruslo** [comment]
> A possible solution would be to rename cache.sha1 to something else, although it might introduce breaking changes

Kind of. Also where is the guarantee that this name pattern will not produce problems for another kind of cache repository?

> This is interpreted by artifactory as "give me the sha1 for the file {package}/{version}/..../cache which obviously doesn't exist

Have you asked Artifactory developers?

First thing that came to mind is try to add dummy fragment to URL, like `{package}/{version}/.../cache.sha1#dummy`. Will this work or not depends on what stage filename parsed.

**Comment by ruslo** [comment]
Closing inactive discussion.
