### ISSUE TITLE
Can't find freshly-built Expat

### ISSUE THREAD

**Issue by alamaison** [ruslo/hunter#105]
I'm having a problem where a project can't find Expat if it looks for it right after Hunter builds it, but it works fine for other libraries.  For example,
```cmake
hunter_add_package(TIFF)
find_package(TIFF REQUIRED)

hunter_add_package(Expat)
find_package(EXPAT REQUIRED)
```
TIFF will be found fine but EXPAT will not.  This only happens when Hunter has just built Expat: if I reconfigure, EXPAT will be found on the second run; if I start configuring a new build tree from scratch, EXPAT will be found as long as I reuse the same Hunter ID.

I've made a test project that reproduces the error: https://github.com/alamaison/hunter-find-test

When I configure this the first time when the Hunter ID does not already exist, I get:
```
[hunter] Build step successful (dir: C:/Users/Alexander/.hunter/_Base/94f56cb/cbb4458/a44f91b/Build/Expat)
CMake Error at C:/ProgramData/chocolatey/lib/cmake.3.1.3/content/cmake-3.1.3-win32-x86/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find EXPAT (missing: EXPAT_LIBRARY) (found version "2.1.0")
Call Stack (most recent call first):
  C:/ProgramData/chocolatey/lib/cmake.3.1.3/content/cmake-3.1.3-win32-x86/share/cmake-3.1/Modules/FindPackageHandleStandardArgs.cmake:374 (_FPHSA_FAILURE_MESSAGE)
  C:/ProgramData/chocolatey/lib/cmake.3.1.3/content/cmake-3.1.3-win32-x86/share/cmake-3.1/Modules/FindEXPAT.cmake:56 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:22 (find_package)
```
If I reconfigure:
```
[hunter] HUNTER_ROOT: C:/Users/Alexander/.hunter
[hunter] [ Hunter-ID: 94f56cb | Config-ID: cbb4458 | Toolchain-ID: a44f91b ]
[hunter] ZLIB_ROOT: C:/Users/Alexander/.hunter/_Base/94f56cb/cbb4458/a44f91b/Install (ver.: 1.2.8-p2)
[hunter] PNG_ROOT: C:/Users/Alexander/.hunter/_Base/94f56cb/cbb4458/a44f91b/Install (ver.: 1.6.16-patch-4)
[hunter] TIFF_ROOT: C:/Users/Alexander/.hunter/_Base/94f56cb/cbb4458/a44f91b/Install (ver.: 4.0.2-hunter-2)
[hunter] EXPAT_ROOT: C:/Users/Alexander/.hunter/_Base/94f56cb/cbb4458/a44f91b/Install (ver.: 2.1.0)
Found EXPAT: C:/Users/Alexander/.hunter/_Base/94f56cb/cbb4458/a44f91b/Install/lib/expat.lib (found version "2.1.0") 
Configuring done
Generating done
```

Any idea why this would be?  I think it must be to do with CONFIG vs MODULE projects.  PNG and TIFF install a config file.  Expat doesn't (at least not in the correct place).

**Comment by ruslo** [comment]
> I've made a test project that reproduces the error

Hi, Alex. I think it's a bug in CMake. I can reproduce this error with CMake 3.1.2. Version 3.2.1 works fine for me.

Some theory:

* [FindEXPAT](https://github.com/Kitware/CMake/blob/bd6389f7bce6d69a75e6f84245834e19b24cc03f/Modules/FindEXPAT.cmake) from standard CMake's location used
* FindEXPAT calls [find_path](http://www.cmake.org/cmake/help/v3.1/command/find_path.html) for header `expat.h` look-up
* FindEXPAT calls [find_library](http://www.cmake.org/cmake/help/v3.1/command/find_library.html) for library `expat` look-up
* Hunter modify [CMAKE_PREFIX_PATH](http://www.cmake.org/cmake/help/v3.1/variable/CMAKE_PREFIX_PATH.html) in [master](https://github.com/ruslo/hunter/blob/e54d78d123306766ede369532c7c1860ea01a95c/cmake/Hunter#L54) file (same level as HunterGate)
* CMAKE_PREFIX_PATH has highest priority in both `find_path`  and `find_library`

>  I think it must be to do with CONFIG vs MODULE projects. PNG and TIFF install a config file. Expat doesn't

Unfortunately this is not unified yet so you need to use documentation each time you're adding new package:
* PNG use MODULE: https://github.com/ruslo/hunter/wiki/pkg.png
* TIFF use CONFIG: https://github.com/ruslo/hunter/wiki/pkg.tiff
* Expat use MODULE: https://github.com/ruslo/hunter/wiki/pkg.expat

**Comment by ruslo** [comment]
I've added notes to README: https://github.com/ruslo/hunter/tree/develop#notes-about-version-of-cmake
