### ISSUE TITLE
Broken package: Qt + Visual Studio 2017

### ISSUE THREAD

**Issue by chkarl** [ruslo/hunter#1052]
I have issues building Qt with Visual Studio 2017.
This seems related to [#745](https://github.com/ruslo/hunter/issues/745) 
The path to the Qt configure script cannot be found. See below
Building with Visual Studio 2013 works fine.

`C:\svn\tmp>cmake -H. -B_builds2017 -DCMAKE_BUILD_TYPE=Release "-GVisual Studio 15 2017 Win64"
-- [hunter *** DEBUG *** 2017-09-19T08:22:35] HUNTER_ROOT detected by environment variable
-- [hunter *** DEBUG *** 2017-09-19T08:22:35] HUNTER_ROOT: C:/svn/hunter
-- [hunter *** DEBUG *** 2017-09-19T08:22:35] Settings (initialize):
-- [hunter *** DEBUG *** 2017-09-19T08:22:35]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2017-09-19T08:22:35]   Cache init (YES)
-- [hunter *** DEBUG *** 2017-09-19T08:22:35] Multi-configuration generator
-- [hunter *** DEBUG *** 2017-09-19T08:22:35] List of cache servers:
-- [hunter *** DEBUG *** 2017-09-19T08:22:35]   * https://github.com/ingenue/hunter-cache
-- [hunter *** DEBUG *** 2017-09-19T08:22:35] Settings (finalize):
-- [hunter *** DEBUG *** 2017-09-19T08:22:35]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2017-09-19T08:22:35]   Cache init (YES)
-- [hunter *** DEBUG *** 2017-09-19T08:22:35] Variables from HunterGate:
-- [hunter *** DEBUG *** 2017-09-19T08:22:35]   HUNTER_GATE_ROOT: C:/svn/hunter
-- [hunter *** DEBUG *** 2017-09-19T08:22:35]   HUNTER_GATE_VERSION: 0.19.103
-- [hunter *** DEBUG *** 2017-09-19T08:22:35]   HUNTER_GATE_SHA1: 606711b6c3820d3128734416600915d598e3700e
-- [hunter] Calculating Toolchain-SHA1
-- [hunter *** DEBUG *** 2017-09-19T08:22:35] [C:/svn/tmp/_builds2017/_3rdParty/Hunter/toolchain] > "C:/Program Files/CMake/bin/cmake.exe" "-DTOOLCHAIN_INFO_FILE=C:/svn/tmp/_builds2017/_3rdParty/Hunter/toolchain/toolchain.info" "-DHUNTER_SELF=C:/svn/hunter/_Base/Download/Hunter/0.19.103/606711b/Unpacked" "-GVisual Studio 15 2017 Win64" "-HC:/svn/tmp/_builds2017/_3rdParty/Hunter/toolchain" "-BC:/svn/tmp/_builds2017/_3rdParty/Hunter/toolchain/_builds" "-DCMAKE_MAKE_PROGRAM=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional/MSBuild/15.0/Bin/MSBuild.exe" "-DCMAKE_RELEASE_POSTFIX=" "-DCMAKE_DEBUG_POSTFIX=d"
-- The C compiler identification is MSVC 19.11.25507.1
-- The CXX compiler identification is MSVC 19.11.25507.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/svn/tmp/_builds2017/_3rdParty/Hunter/toolchain/_builds
-- [hunter *** DEBUG *** 2017-09-19T08:22:49] Already exists: C:/svn/hunter/_Base/606711b/05e6eb8/toolchain.info
-- [hunter] Calculating Config-SHA1
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Cache data is up-to-date
-- [hunter] HUNTER_ROOT: C:/svn/hunter
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] HUNTER_TOOLCHAIN_ID_PATH: C:/svn/hunter/_Base/606711b/05e6eb8
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] HUNTER_CONFIGURATION_TYPES: Release;Debug
-- [hunter] [ Hunter-ID: 606711b | Toolchain-ID: 05e6eb8 | Config-ID: a663151 ]
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] HUNTER_MSVC_VERSION: 15
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] HUNTER_MSVC_YEAR: 2017
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] HUNTER_MSVC_ARCH: amd64
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Environment 'VS150COMNTOOLS': 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\Tools\'
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] CMAKE_VS_DEVENV_COMMAND: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional/Common7/IDE/devenv.com'
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] vcvarsall.bat file location: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Auxiliary/Build/vcvarsall.bat
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] load: C:/svn/hunter/_Base/Download/Hunter/0.19.103/606711b/Unpacked/cmake/projects/Qt/hunter.cmake
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Qt versions available: [5.5.0;5.5.0-hunter-p0;5.5.0-hunter-p1;5.5.1-hunter-p0;5.5.1-hunter-p1;5.5.1-hunter-p2;5.5.1-cvpixelbuffer-p0;5.5.1-cvpixelbuffer-2-p0;5.5.1-cvpixelbuffer-2-p1;5.5.1-cvpixelbuffer-2-p2;5.5.1-cvpixelbuffer-2-p3;5.5.1-cvpixelbuffer-2-p4;5.5.1-cvpixelbuffer-2-p5;5.5.1-cvpixelbuffer-2-p6;5.5.1-cvpixelbuffer-2-p7;5.5.1-cvpixelbuffer-2-p8;5.5.1-cvpixelbuffer-2-p9;5.6.0-alpha;5.9.1-p0]
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Install to: C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Install
-- [hunter] QT_ROOT: C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Install (ver.: 5.9.1-p0)
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Default arguments:
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] User arguments:
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Locking directory: C:/svn/hunter/_Base/Download/Qt/5.9.1-p0/b1bc254
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Lock done
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Already locked: C:/svn/hunter/_Base/Download/Qt/5.9.1-p0/b1bc254
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Locking directory: C:/svn/hunter/_Base/606711b/05e6eb8/a663151
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Lock done
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Locking directory: C:/svn/hunter/_Base/Cache
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Lock done
-- [hunter *** DEBUG *** 2017-09-19T08:22:50] Downloading file (try #0 of 10):
-- [hunter *** DEBUG *** 2017-09-19T08:22:50]   https://raw.githubusercontent.com/ingenue/hunter-cache/master/05e6eb8/Qt/__qtbase/5.9.1-p0/b1bc254/da39a3e/a49b0e5/b1d5781/basic-deps.DONE
-- [hunter *** DEBUG *** 2017-09-19T08:22:50]   -> C:/svn/hunter/_Base/Cache/meta/05e6eb8/Qt/__qtbase/5.9.1-p0/b1bc254/da39a3e/a49b0e5/b1d5781/basic-deps.DONE
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] File not found
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Downloading file (try #1 of 10):
-- [hunter *** DEBUG *** 2017-09-19T08:22:51]   https://raw.githubusercontent.com/ingenue/hunter-cache/master/05e6eb8/Qt/__qtbase/5.9.1-p0/b1bc254/da39a3e/a49b0e5/b1d5781/basic-deps.DONE
-- [hunter *** DEBUG *** 2017-09-19T08:22:51]   -> C:/svn/hunter/_Base/Cache/meta/05e6eb8/Qt/__qtbase/5.9.1-p0/b1bc254/da39a3e/a49b0e5/b1d5781/basic-deps.DONE
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] File not found
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Cache miss (no basic dependencies info found: C:/svn/hunter/_Base/Cache/meta/05e6eb8/Qt/__qtbase/5.9.1-p0/b1bc254/da39a3e/a49b0e5/b1d5781/basic-deps.DONE)
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Number of logical cores per physical core: 8
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Number of physical cores: 4
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Total number of cores: 32
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] HUNTER_JOBS_NUMBER:
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] HUNTER_JOBS_OPTION: 32
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Add package: Qt
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Component: qtbase
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Download scheme: url_sha1_qt
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Url: https://github.com/hunter-packages/Qt/releases/download/v5.9.1-p0/hunter-5.9.1.7z
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] SHA1: b1bc254e688426316b55115adddd13e4a10115b2
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Configuration types: Release;Debug
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Internal dependencies ID: 10
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] Scheme file used: C:/svn/hunter/_Base/Download/Hunter/0.19.103/606711b/Unpacked/cmake/projects/Qt/schemes/url_sha1_qt.cmake.in
-- [hunter] Building Qt (component: qtbase)
-- [hunter *** DEBUG *** 2017-09-19T08:22:51] [C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase] > "C:/Program Files/CMake/bin/cmake.exe" "-CC:/svn/hunter/_Base/606711b/05e6eb8/a663151/cache.cmake" "-CC:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase/args.cmake" "-HC:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase" "-BC:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase/Build" "-DCMAKE_TOOLCHAIN_FILE=C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase/toolchain.cmake" "-GVisual Studio 15 2017 Win64" "-DCMAKE_MAKE_PROGRAM=C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional/MSBuild/15.0/Bin/MSBuild.exe"
loading initial cache file C:/svn/hunter/_Base/606711b/05e6eb8/a663151/cache.cmake
loading initial cache file C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase/args.cmake
-- The C compiler identification is MSVC 19.11.25507.1
-- The CXX compiler identification is MSVC 19.11.25507.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Professional/VC/Tools/MSVC/14.11.25503/bin/HostX86/x64/cl.exe -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase/Build
-- [hunter *** DEBUG *** 2017-09-19T08:23:01] Configure step successful (dir: C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase)
-- [hunter *** DEBUG *** 2017-09-19T08:23:01] [C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase] > "C:/Program Files/CMake/bin/cmake.exe" "--build" "C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase/Build"
Microsoft (R) Build Engine version 15.3.409.57025 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2017-09-19 08:23:01.
Project "C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" (1) is building "C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\ZERO_CHECK\".
  Creating directory "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake does not need to re-run because C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase/Build/CMakeFiles/generate.stamp is up-to-date.
FinalizeBuildStatus:
  Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\ZERO_CHECK.vcxproj" (default targets).
Project "C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" (1) is building "C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\Qt-qtbase\".
  Creating directory "x64\Debug\Qt-qtbase\Qt-qtbase.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\Qt-qtbase\Qt-qtbase.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ComputeCustomBuildOutput:
  Creating directory "C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\Qt-qtbase-prefix\src\Qt-qtbase-stamp\Debug\".
  Creating directory "C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\CMakeFiles\Debug\".
CustomBuild:
  Building Custom Rule C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase/CMakeLists.txt
  CMake does not need to re-run because C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase/Build/CMakeFiles/generate.stamp is up-to-date.
  Creating directories for 'Qt-qtbase'
  Performing download step for 'Qt-qtbase'
  skip download
  No update step for 'Qt-qtbase'
  No patch step for 'Qt-qtbase'
  Performing configure step for 'Qt-qtbase'
  **********************************************************************
  ** Visual Studio 2017 Developer Command Prompt v15.0.26730.12
  ** Copyright (c) 2017 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x64'

  Building Qt component:
    qtbase

  Dependent components:

  Components to skip:
    qt3d
    qtactiveqt
    qtandroidextras
    qtcanvas3d
    qtcharts
    qtconnectivity
    qtdatavis3d
    qtdeclarative
    qtdoc
    qtdocgallery
    qtenginio
    qtfeedback
    qtgamepad
    qtgraphicaleffects
    qtimageformats
    qtlocation
    qtmacextras
    qtmultimedia
    qtnetworkauth
    qtpim
    qtpurchasing
    qtqa
    qtquick1
    qtquickcontrols
    qtquickcontrols2
    qtremoteobjects
    qtrepotools
    qtscript
    qtscxml
    qtsensors
    qtserialbus
    qtserialport
    qtspeech
    qtsvg
    qtsystems
    qttools
    qttranslations
    qtvirtualkeyboard
    qtwayland
    qtwebchannel
    qtwebengine
    qtwebkit
    qtwebkit-examples
    qtwebsockets
    qtwebview
    qtwinextras
    qtx11extras
    qtxmlpatterns

  Calculating list of files...
  Done
  Clean-up...
  Qt configure command: configure.bat;-confirm-license;-nomake;examples;-nomake;tests;-opensource;-platform;win32-msvc2017;-static;-prefix;C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase/Install;-no-sql-db2;-no-sql-ibase;-no-sql-mysql;-no-sql-oci;-no-sql-odbc;-no-sql-psql;-no-sql-sqlite2;-no-sql-tds;-no-fontconfig;-no-gif;-no-icu;-no-openssl;-qt-freetype;-qt-harfbuzz;-qt-libjpeg;-qt-libpng;-qt-pcre;-qt-zlib;-debug-and-release;-skip;qt3d;-skip;qtactiveqt;-skip;qtandroidextras;-skip;qtcanvas3d;-skip;qtcharts;-skip;qtconnectivity;-skip;qtdatavis3d;-skip;qtdeclarative;-skip;qtdoc;-skip;qtdocgallery;-skip;qtenginio;-skip;qtfeedback;-skip;qtgamepad;-skip;qtgraphicaleffects;-skip;qtimageformats;-skip;qtlocation;-skip;qtmacextras;-skip;qtmultimedia;-skip;qtnetworkauth;-skip;qtpim;-skip;qtpurchasing;-skip;qtqa;-skip;qtquick1;-skip;qtquickcontrols;-skip;qtquickcontrols2;-skip;qtremoteobjects;-skip;qtrepotools;-skip;qtscript;-skip;qtscxml;-skip;qtsensors;-skip;qtserialbus;-skip;qtserialport;-skip;qtspeech;-skip;qtsvg;-skip;qtsystems;-skip;qttools;-skip;qttranslations;-skip;qtvirtualkeyboard;-skip;qtwayland;-skip;qtwebchannel;-skip;qtwebengine;-skip;qtwebkit;-skip;qtwebkit-examples;-skip;qtwebsockets;-skip;qtwebview;-skip;qtwinextras;-skip;qtx11extras;-skip;qtxmlpatterns
  CMake Error at C:/svn/hunter/_Base/606711b/05e6eb8/a663151/QtBuild/10/qt-configure.cmake:366 (message):
    Qt configure failed: The system cannot find the file specified

C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj]
Done Building Project "C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj" (default target) (3) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\svn\hunter\_Base\606711b\05e6eb8\a663151\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:02:16.25

[hunter ** FATAL ERROR **] Build step failed (dir: C:/svn/hunter/_Base/606711b/05e6eb8/a663151/Build/Qt/__qtbase
[hunter ** FATAL ERROR **] [Directory:C:/svn/hunter/_Base/Download/Hunter/0.19.103/606711b/Unpacked/cmake/projects/Qt/qtbase]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/svn/hunter/_Base/Download/Hunter/0.19.103/606711b/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/svn/hunter/_Base/Download/Hunter/0.19.103/606711b/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/svn/hunter/_Base/Download/Hunter/0.19.103/606711b/Unpacked/cmake/modules/hunter_download.cmake:596 (hunter_fatal_error)
  C:/svn/hunter/_Base/Download/Hunter/0.19.103/606711b/Unpacked/cmake/projects/Qt/qtbase/hunter.cmake:134 (hunter_download)
  C:/svn/hunter/_Base/Download/Hunter/0.19.103/606711b/Unpacked/cmake/projects/Qt/hunter.cmake:265 (include)
  C:/svn/hunter/_Base/Download/Hunter/0.19.103/606711b/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:19 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "C:/svn/tmp/_builds2017/CMakeFiles/CMakeOutput.log".

C:\svn\tmp>`

**Comment by cgilles** [comment]
Fully reproducible here too (Win7 + MSVC 2017 community) : 
  -- verifying file...
         file='C:/.hunter/_Base/Download/Qt/5.9.1-p0/b1bc254/hunter-5.9.1.7z'
  -- Downloading... done
  -- extracting...
       src='C:/.hunter/_Base/Download/Qt/5.9.1-p0/b1bc254/hunter-5.9.1.7z'
       dst='C:/.hunter/_Base/e3efd47/3118d98/07cf638/QtBuild/13'
  -- extracting... [tar xfz]
  -- extracting... [analysis]
  -- extracting... [rename]
  -- extracting... [clean up]
  -- extracting... done
  No update step for 'Qt-qtbase'
  No patch step for 'Qt-qtbase'
  Performing configure step for 'Qt-qtbase'
  **********************************************************************
  ** Visual Studio 2017 Developer Command Prompt v15.0.26730.10
  ** Copyright (c) 2017 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x86'

  Building Qt component:
    qtbase

  Dependent components:


  Components to skip:
    qt3d
    qtactiveqt
    qtandroidextras
    qtcanvas3d
    qtcharts
    qtconnectivity
    qtdatavis3d
    qtdeclarative
    qtdoc
    qtdocgallery
    qtenginio
    qtfeedback
    qtgamepad
    qtgraphicaleffects
    qtimageformats
    qtlocation
    qtmacextras
    qtmultimedia
    qtnetworkauth
    qtpim
    qtpurchasing
    qtqa
    qtquick1
    qtquickcontrols
    qtquickcontrols2
    qtremoteobjects
    qtrepotools
    qtscript
    qtscxml
    qtsensors
    qtserialbus
    qtserialport
    qtspeech
    qtsvg
    qtsystems
    qttools
    qttranslations
    qtvirtualkeyboard
    qtwayland
    qtwebchannel
    qtwebengine
    qtwebkit
    qtwebkit-examples
    qtwebsockets
    qtwebview
    qtwinextras
    qtx11extras
    qtxmlpatterns


  Calculating list of files...
  Done
  Qt configure command: configure.bat;-confirm-license;-nomake;examples;-nomake;tests;-opensource;-platform;win32-msvc20
17;-static;-prefix;C:/.hunter/_Base/e3efd47/3118d98/07cf638/Build/Qt/__qtbase/Install;-no-sql-db2;-no-sql-ibase;-no-sql-
mysql;-no-sql-oci;-no-sql-odbc;-no-sql-psql;-no-sql-sqlite2;-no-sql-tds;-no-fontconfig;-no-gif;-no-icu;-no-openssl;-qt-f
reetype;-qt-harfbuzz;-qt-libjpeg;-qt-libpng;-qt-pcre;-qt-zlib;-debug-and-release;-skip;qt3d;-skip;qtactiveqt;-skip;qtand
roidextras;-skip;qtcanvas3d;-skip;qtcharts;-skip;qtconnectivity;-skip;qtdatavis3d;-skip;qtdeclarative;-skip;qtdoc;-skip;
qtdocgallery;-skip;qtenginio;-skip;qtfeedback;-skip;qtgamepad;-skip;qtgraphicaleffects;-skip;qtimageformats;-skip;qtloca
tion;-skip;qtmacextras;-skip;qtmultimedia;-skip;qtnetworkauth;-skip;qtpim;-skip;qtpurchasing;-skip;qtqa;-skip;qtquick1;-
skip;qtquickcontrols;-skip;qtquickcontrols2;-skip;qtremoteobjects;-skip;qtrepotools;-skip;qtscript;-skip;qtscxml;-skip;q
tsensors;-skip;qtserialbus;-skip;qtserialport;-skip;qtspeech;-skip;qtsvg;-skip;qtsystems;-skip;qttools;-skip;qttranslati
ons;-skip;qtvirtualkeyboard;-skip;qtwayland;-skip;qtwebchannel;-skip;qtwebengine;-skip;qtwebkit;-skip;qtwebkit-examples;
-skip;qtwebsockets;-skip;qtwebview;-skip;qtwinextras;-skip;qtx11extras;-skip;qtxmlpatterns
  CMake Error at C:/.hunter/_Base/e3efd47/3118d98/07cf638/QtBuild/13/qt-configure.cmake:368 (message):
    Qt configure failed: Le fichier spécifié est introuvable


C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5
): error MSB6006: Arr?t de "cmd.exe" avec le code 1. [C:\.hunter\_Base\e3efd47\3118d98\07cf638\Build\Qt\__qtbase\Build\Q
t-qtbase.vcxproj]
G?n?ration du projet "C:\.hunter\_Base\e3efd47\3118d98\07cf638\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj" termin?e (cibl
es par d?faut) -- ?CHEC.
G?n?ration du projet "C:\.hunter\_Base\e3efd47\3118d98\07cf638\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" termin?e (cibl
es par d?faut) -- ?CHEC.

?CHEC de la build.

"C:\.hunter\_Base\e3efd47\3118d98\07cf638\Build\Qt\__qtbase\Build\ALL_BUILD.vcxproj" (cible par d?faut) (1) ->
"C:\.hunter\_Base\e3efd47\3118d98\07cf638\Build\Qt\__qtbase\Build\Qt-qtbase.vcxproj" (cible par d?faut) (3) ->
(CustomBuild cible) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171
,5): error MSB6006: Arr?t de "cmd.exe" avec le code 1. [C:\.hunter\_Base\e3efd47\3118d98\07cf638\Build\Qt\__qtbase\Build
\Qt-qtbase.vcxproj]

    0 Avertissement(s)
    1 Erreur(s)

Temps ?coul? 00:32:33.24

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/e3efd47/3118d98/07cf638/Build/Qt/__qtbase
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.19.144/e3efd47/Unpacked/cmake/projects/Qt/qtbas
e]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.19.144/e3efd47/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.19.144/e3efd47/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.19.144/e3efd47/Unpacked/cmake/modules/hunter_download.cmake:609 (hunter_fatal_error
)
  C:/.hunter/_Base/Download/Hunter/0.19.144/e3efd47/Unpacked/cmake/projects/Qt/qtbase/hunter.cmake:134 (hunter_download)

  C:/.hunter/_Base/Download/Hunter/0.19.144/e3efd47/Unpacked/cmake/projects/Qt/hunter.cmake:265 (include)
  C:/.hunter/_Base/Download/Hunter/0.19.144/e3efd47/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:13 (hunter_add_package)


-- Configuring incomplete, errors occurred!

**Comment by Knitschi** [comment]
I have the same problem on a Windows 10 machine. But it works for me on a Windows 7 machine. Also I had it already working on the Windows 10 machine, then I changed something and now it does not work.
On both machines I build with "Visual Studio 15 2017 Win64".

The error says that the qt-configure.cmake file is missing, but the file actually exists. So I am not sure what is going on here.

**Comment by ruslo** [comment]
Probably same problem as with Boost:
* https://github.com/ruslo/hunter/issues/745#issuecomment-316629752

Solution implemented in Boost:
* https://github.com/ruslo/hunter/pull/1145

**Comment by Knitschi** [comment]
Yes it seems to be the same problem. I deleted my `%USERPROFILE%\source` directory and it compiles now. That also explains why it first worked and then did not. However I do not know what created the `\source` directory in the first place.

**Comment by ruslo** [comment]
Closing inactive issue with "Broken package" label, see details:
* https://github.com/ruslo/hunter/wiki/error.external.build.failed
