### ISSUE TITLE
add package glbinding and globjects

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#1054]
I'd like to add the package `globjects` which needs `glbinding`. This issue is for tracking dependencies and initial discussion

Required dependencies:
- [x] globjects https://github.com/cginternals/globjects
  - [x] glbinding https://github.com/cginternals/glbinding
  - [x] glm 

@ruslo could you create repositories for both at `hunter-packages`. I don't know If I need to modify `glbinding` yet, but I suspect I will have to. They do something non-standard with the install directories https://github.com/cginternals/glbinding/blob/c8bd311f2365eb3cecf3dbe2ab6273ae084a4d26/CMakeLists.txt#L136

**Comment by ruslo** [comment]
Done:
* https://github.com/hunter-packages/glbinding
* https://github.com/hunter-packages/globjects

**Comment by NeroBurner** [comment]
merged and released:
- https://github.com/ruslo/hunter/pull/1073#issuecomment-334498025
- https://github.com/ruslo/hunter/pull/1075#issuecomment-334833739
