### ISSUE TITLE
Wiki: error.external.build.failed

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#1059]
On wiki paige: https://github.com/ruslo/hunter/wiki/error.external.build.failed

Dead link for variable `HUNTER_BINARY_DIR` https://github.com/ruslo/hunter/wiki/CMake-Variables-%28User%29#hunter_binary_dir-environment-variable

**Comment by NeroBurner** [comment]
also HUNTER_STATUS_DEBUG=ON has a dead link https://github.com/ruslo/hunter/wiki/CMake-Variables-%28User%29#hunter_status_debug

**Comment by ruslo** [comment]
Fixed. Also wiki is open for editing, you have permissions to add.
