### ISSUE TITLE
UNIX variable unset on first configuration

### ISSUE THREAD

**Issue by alamaison** [ruslo/hunter#107]
Something about using Hunter causes `UNIX` not to be set on Linux on the first configuration of a project.  With [this test code](https://github.com/alamaison/hunter-platform-test/blob/master/hunter-platform-test/CMakeLists.txt) I get the following output:
```
awl03@ubuntu-amd64:~/Projects/hunter-platform-test/bin$ cmake ..
===========Before include(HunterGate)
UNIX
CMAKE_SYSTEM_NAME: 
=========After include(HunterGate)
UNIX
CMAKE_SYSTEM_NAME: 
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [hunter] Calculating Config-SHA1
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] HUNTER_ROOT: /home/awl03/.hunter
-- [hunter] [ Hunter-ID: a0fcbcf | Config-ID: 5dfc1da | Toolchain-ID: 6e3ae24 ]
=========After HunterGate(...)
UNIX
CMAKE_SYSTEM_NAME: Linux
=========After project(...)
CMAKE_SYSTEM_NAME: Linux
-- Configuring done
-- Generating done
-- Build files have been written to: /home/awl03/Projects/hunter-platform-test/bin
```
Note the missing `UNIX` once `project(...)` has been called.  But if I run it a second time without wiping the cache, it works as expected:
```
awl03@ubuntu-amd64:~/Projects/hunter-platform-test/bin$ cmake ..
===========Before include(HunterGate)
UNIX
CMAKE_SYSTEM_NAME: 
=========After include(HunterGate)
UNIX
CMAKE_SYSTEM_NAME: 
-- [hunter] Calculating Config-SHA1
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] HUNTER_ROOT: /home/awl03/.hunter
-- [hunter] [ Hunter-ID: a0fcbcf | Config-ID: 5dfc1da | Toolchain-ID: 6e3ae24 ]
=========After HunterGate(...)
UNIX
CMAKE_SYSTEM_NAME: Linux
=========After project(...)
UNIX
CMAKE_SYSTEM_NAME: Linux
-- Configuring done
-- Generating done
-- Build files have been written to: /home/awl03/Projects/hunter-platform-test/bin
```

If I disable Hunter, it works as expected on the ''first'' run:
```
awl03@ubuntu-amd64:~/Projects/hunter-platform-test/bin$ rm -rf *
awl03@ubuntu-amd64:~/Projects/hunter-platform-test/bin$ cmake -DHUNTER_ENABLED=OFF ..
===========Before include(HunterGate)
UNIX
CMAKE_SYSTEM_NAME: 
=========After include(HunterGate)
UNIX
CMAKE_SYSTEM_NAME: 
=========After HunterGate(...)
UNIX
CMAKE_SYSTEM_NAME: 
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
=========After project(...)
UNIX
CMAKE_SYSTEM_NAME: Linux
-- Configuring done
-- Generating done
-- Build files have been written to: /home/awl03/Projects/hunter-platform-test/bin
```

This is using CMake 3.2.1.

It seems to work fine on Windows:
```
===========Before include(HunterGate)
WIN32
CMAKE_SYSTEM_NAME: 
=========After include(HunterGate)
WIN32
CMAKE_SYSTEM_NAME: 
The C compiler identification is MSVC 14.0.50727
The CXX compiler identification is MSVC 14.0.50727
Check for working C compiler using: Visual Studio 8 2005 Win64
Check for working C compiler using: Visual Studio 8 2005 Win64 -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler using: Visual Studio 8 2005 Win64
Check for working CXX compiler using: Visual Studio 8 2005 Win64 -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
[hunter] Calculating Config-SHA1
[hunter] Calculating Toolchain-SHA1
[hunter] HUNTER_ROOT: C:/Users/Alexander/.hunter
[hunter] [ Hunter-ID: a0fcbcf | Config-ID: cbb4458 | Toolchain-ID: a44f91b ]
=========After HunterGate(...)
WIN32
CMAKE_SYSTEM_NAME: Windows
=========After project(...)
WIN32
CMAKE_SYSTEM_NAME: Windows
Configuring done
Generating done
```

**Comment by ruslo** [comment]
I think it is because of fixing: https://github.com/ruslo/hunter/issues/104 :(

**Comment by alamaison** [comment]
How does that affect it?  By unsetting `CMAKE_SYSTEM_SPECIFIC_INFORMATION_LOADED`?  Wouldn't that just make is re-calculate the target platform and, therefore, set UNIX again on Linux.  And why would that only affect Linux, not Windows?

**Comment by ruslo** [comment]
> By unsetting CMAKE_SYSTEM_SPECIFIC_INFORMATION_LOADED

probably yes

> Wouldn't that just make is re-calculate the target platform and, therefore, set UNIX again on Linux

I was thinking that it will work so

> And why would that only affect Linux, not Windows

Have no idea, may be some other stuff will stop work on Windows.

I will add unit test for both https://github.com/ruslo/hunter/issues/104 and https://github.com/ruslo/hunter/issues/107

**Comment by alamaison** [comment]
I may know why.  Although unsetting `CMAKE_SYSTEM_SPECIFIC_INFORMATION_LOADED` causes the platform to be reloaded, UnixPaths.cmake [has an include guard that prevents it being run a second time](https://github.com/Kitware/CMake/blob/master/Modules/Platform/UnixPaths.cmake#L15).  WindowsPaths.cmake [has a similar guard](https://github.com/Kitware/CMake/blob/master/Modules/Platform/WindowsPaths.cmake), but, as it isn't reponsible for setting `WIN32`, it wasn't affected.  As you say, other stuff might be.

We may need `unset(__UNIX_PATHS_INCLUDED)` and `unset(__WINDOWS_PATHS_INCLUDED)` in the fix to #104. But that's getting hacky.  Why was  unsetting `CMAKE_SYSTEM_SPECIFIC_INFORMATION_LOADED` necessary to fix #104?

**Comment by ruslo** [comment]
> I may know why

cool, thanks for investigating it

>  Why was unsetting CMAKE_SYSTEM_SPECIFIC_INFORMATION_LOADED necessary to fix #104

CMake set default `CMAKE_INSTALL_PREFIX` if it's not defined by user. It happens in [CMakeGenericSystem](https://github.com/ruslo/CMake/blob/9db3116226cb99fcf54e936c833953abcde9b729/Modules/CMakeGenericSystem.cmake#L174) which is loaded by [CMakeSystemSpecificInformation](https://github.com/ruslo/CMake/blob/9db3116226cb99fcf54e936c833953abcde9b729/Modules/CMakeSystemSpecificInformation.cmake#L31), which is loaded in [cmGlobalGenerator.cxx](https://github.com/ruslo/CMake/blob/9db3116226cb99fcf54e936c833953abcde9b729/Source/cmGlobalGenerator.cxx#L476) only if CMAKE_SYSTEM_SPECIFIC_INFORMATION_LOADED is not defined. So to prevent setting CMAKE_INSTALL_PREFIX to "program files/Hunter" I check that CMAKE_INSTALL_PREFIX is not defined and then just clear both CMAKE_INSTALL_PREFIX and CMAKE_SYSTEM_SPECIFIC_INFORMATION_LOADED.

Probably I need to think about not setting 'project(Hunter)' at all to avoid such problems

**Comment by alamaison** [comment]
> Probably I need to think about not setting 'project(Hunter)' at all to avoid such problems

What necessitated the change to using `project(Hunter)`?

**Comment by ruslo** [comment]
> What necessitated the change to using project(Hunter)?

Some variables set by CMake to their normal values in `project` command. Such as MSVC. We need MSVC in master file:
```cmake
if(MSVC)
  include(hunter_setup_msvc_arch)
  include(hunter_setup_msvc_vcvarsall)
  hunter_setup_msvc_arch()
  hunter_setup_msvc_vcvarsall()
endif()
```
may be somewhere else

**Comment by ruslo** [comment]
Reverted version: https://github.com/ruslo/hunter/releases/tag/v0.9.4
Reopened: https://github.com/ruslo/hunter/issues/104

**Comment by ruslo** [comment]
Also new unit-test: https://github.com/ruslo/hunter/blob/develop/tests/issue/107/CMakeLists.txt
