### ISSUE TITLE
Package 'CppNetlib' not working, at least on windows

### ISSUE THREAD

**Issue by smurfy** [ruslo/hunter#1076]
It seems like CppNetlib is to old to still work.

-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:1150 (file):
    file problem creating directory: C:/Program Files/HunterPackages/Download
  Call Stack (most recent call first):
    C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:2517 (_ep_set_directories)
    CMakeLists.txt:3 (ExternalProject_Add)

  CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:1152 (message):
    dir 'C:/Program Files/HunterPackages/Download' does not exist after
    file(MAKE_DIRECTORY)
  Call Stack (most recent call first):
    C:/Program Files/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:2517 (_ep_set_directories)
    CMakeLists.txt:3 (ExternalProject_Add)

  -- Configuring incomplete, errors occurred!
  See also "C:/.hunter/_Base/aafb99b/274849f/1fbe520/Build/CppNetlib/Build/CppNetlib-Release-prefix/src/CppNetlib-Release-build/Hunter-activity/gate/_builds/CMakeFiles/CMakeOutput.log".
  CMake Error at HunterGate.cmake:133 (message):
    Configure download project failed
  Call Stack (most recent call first):
    HunterGate.cmake:173 (hunter_gate_do_download)
    CMakeLists.txt:9 (include)

  -- Configuring incomplete, errors occurred!
  See also "C:/.hunter/_Base/aafb99b/274849f/1fbe520/Build/CppNetlib/Build/CppNetlib-Release-prefix/src/CppNetlib-Release-build/CMakeFiles/CMakeOutput.log".

**Comment by ruslo** [comment]
Closing inactive.
