### ISSUE TITLE
Boost build for VS2017 raises CMP0054 warning

### ISSUE THREAD

**Issue by StuartDAdams** [ruslo/hunter#1077]
Hi, I'm new to hunter but I've got a problem that has me scratching my head. When I use hunter to fetch my boost dependencies for VS2015 builds, they pass without any significant warnings. However, when I do the same but target VS2017, it tries to build boost, at which point cmake raises a CMP0054 warning. This raises a powershell exception that causes the build to fail. The project actually builds fine, but Appveyor processes any exception as a build failure. 

Successful output for VS2015 x64
https://ci.appveyor.com/project/StuartDAdams/tinybox/build/1.0.58/job/pj0066rlabio2i9q

Unsuccessful output of VS2017 x64
https://ci.appveyor.com/project/StuartDAdams/tinybox/build/1.0.58/job/kx8gwpe4gl11e2lh

As I understand it this means I need to update the CMP0054 policy of the offending CMake project, but I'm unsure how that works with an external dependency being fetched and installed by hunter.

Sorry if this is a daft question, my CMake / CI experience is limited. We're doing this for a university project.

Thanks! Really enjoying working with hunter so far.

**Comment by ruslo** [comment]
```
C:/Program Files (x86)/CMake/share/cmake-3.9/Modules/ExternalProject.cmake:1954
```
That's the source of the problem. It's not Hunter - it's CMake.

You can try to disable all logs with:
* [HUNTER_STATUS_PRINT=OFF](https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-status-print)
* [HUNTER_STATUS_DEBUG=OFF](https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-status-debug)

**Comment by StuartDAdams** [comment]
I see! Thank you for responding, very helpful. Appveyor is running quite a new version of CMake in 3.9.1. If I want to see a fix, would my best bet be to submit an issue with Cmake itself? Thanks for the help!

**Comment by ruslo** [comment]
> If I want to see a fix, would my best bet be to submit an issue with Cmake itself?

Yes: https://gitlab.kitware.com/cmake/cmake/issues

**Comment by StuartDAdams** [comment]
Unfortunately suppressing the hunter logs didn't help. I'll submit the issue to cmake and see how it goes. 

https://ci.appveyor.com/project/StuartDAdams/tinybox/build/1.0.60/job/39gc54q3gvi13d4v

Thanks for your help!
