### ISSUE TITLE
How to add Boost compile time defines?

### ISSUE THREAD

**Issue by PyrO70** [ruslo/hunter#1078]
Hi,

I'm using Boost, specifically the MPL and boost::variant, which have a hard contraint on the size of the template parameter list, limited to 20 parameters by default. This can be change via the [BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS](http://www.boost.org/doc/libs/1_65_0/libs/mpl/doc/refmanual/cfg-no-preprocessed-headers.html) and [BOOST_MPL_LIMIT_LIST_SIZE](http://www.boost.org/doc/libs/1_65_0/libs/mpl/doc/refmanual/limit-list-size.html) and a-like defines.

I'm unsure how to do set those defines properly for Boost so that b2 gets the defines and make sure Hunter is notified of the change of configuration. I have looked a bit and think some changes should be done in the Boost scheme and in the BoostConfig.cmake to add the define for compilation and add the defines as a target property, respectively.

The reason why these defines need to be handle within the hunter configuration and can't just be set on a project level is that boost::variant or boost::mpl types are actually different type with different value of the defines, creating link time errors when using a library built with different value of the defines.

```cpp
#define BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS
#define BOOST_MPL_LIMIT_LIST_SIZE 3
using my_list = boost::mpl::vector<int, int, int>; // that compiles
// using my_other_list =boost::mpl::vector<int, int, int, double>; // that wouldn't compile
void foo(my_list);
#undef BOOST_MPL_LIMIT_LIST_SIZE
#define BOOST_MPL_LIMIT_LIST_SIZE 5
using my_list_two = boost::mpl::vector<int, int, int>; // that compiles, supposed to be the same type
foo(my_list_two{}); // link time error, multiple definition
```

Any idea? Maybe I'm missing an existing feature?

**Comment by ruslo** [comment]
> is that boost::variant or boost::mpl types are actually different type with different value of the defines, creating link time errors

As far as [I can see](https://github.com/ruslo/hunter/blob/5d4ca2f7aa235c67f96d6169844490c6a84779aa/cmake/modules/hunter_get_boost_libs.cmake#L52-L82) Boost.mpl and Boost.variant are header-only components. It means that value of `BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS` doesn't affect installed headers/libraries. In this case it will be enough to modify installed `*Config.cmake` files. Take a look at how `BOOST_ALL_DYN_LINK` handled:
* https://github.com/ruslo/hunter/blob/5d4ca2f7aa235c67f96d6169844490c6a84779aa/cmake/templates/BoostConfig.cmake.in#L56-L58
* https://github.com/ruslo/hunter/blob/5d4ca2f7aa235c67f96d6169844490c6a84779aa/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L167-L175

**Comment by PyrO70** [comment]
The problem will remain if any non-header only interface of Boost components uses Boost.mpl or Boost.variant, the types would be compiled within the Boost component. When using Boost with those defines setup, the interface will become incompatible, because it was built with a different set of defines.

Maybe it is not the case and none of the Boost components interfaces uses Boost.mpl or Boost.variant in there interfaces?

I will check out the BoostConfig.cmake.in way in the mean time.

**Comment by ruslo** [comment]
> The problem will remain if any non-header only interface of Boost components uses Boost.mpl or Boost.variant, the types would be compiled within the Boost component

Hm, okay it's true, I missed that. In this case we need to add defines to user's jam file, like:
* https://github.com/ruslo/hunter/blob/5d4ca2f7aa235c67f96d6169844490c6a84779aa/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L177-L187

> Maybe it is not the case and none of the Boost components interfaces uses Boost.mpl or Boost.variant in there interfaces?

Can you take a look?

**Comment by PyrO70** [comment]
Even if there it isn't just now, it might be true in the future. I think it is worth doing the work now, making sure the library are compatible with Boost.boost, whatever API changes might happen in the future for the library components.

Changing the flags for the jam file, using CMAKE_CXX_FLAGS, is this going to be detected as a change of configuration by Hunter? (rebuilding the cache).

The example you're giving is changing the flags for MSVC, does that mean I need multiple condition depending on the compiler spec ? (-D or /D) ? or is it standard to jam? (I'm not really familiar with boost build system).

TODO:
- Add target definition in BoostConfig.cmake.in as an INTERFACE property
- Change jam configuration in url_sha1_boost_library.cmake.in for all SIZE related defines + disable pre compiler header define
  - [BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS](http://www.boost.org/doc/libs/1_65_0/libs/mpl/doc/refmanual/cfg-no-preprocessed-headers.html)
  - [BOOST_MPL_LIMIT_seq_SIZE](http://www.boost.org/doc/libs/1_65_0/libs/mpl/doc/refmanual/variadic-sequence.html)
  - [BOOST_VARIANT_LIMIT_TYPES](http://www.boost.org/doc/libs/1_65_0/doc/html/BOOST_VARIANT_LIMIT_TYPES.html)

I will have a look.

**Comment by ruslo** [comment]
> Changing the flags for the jam file, using CMAKE_CXX_FLAGS, is this going to be detected as a change of configuration by Hunter? (rebuilding the cache).

User should use custom [CMAKE_ARGS](https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-cmake-options) to pass new value => yes, it will affect both cache and install root.

> The example you're giving is changing the flags for MSVC, does that mean I need multiple condition depending on the compiler spec ? (-D or /D) ?

Yes, it will be different flags for different compilers.

> or is it standard to jam?

I don't know jam-file syntax. Have no idea how to pass `-Dxxx=xxx` to it in unified fashion.

**Comment by PyrO70** [comment]
I have managed to make it work with `CMAKE_ARGS`. But, I'm having some issue with `url_sha1_boost_library.cmake.in`. It doesn't get the variable defined in `CMAKE_ARGS` replaced when the file is configured using `hunter_config(Boost VERSION 1.x.y CMAKE_ARGS BOOST_TEMPLATE_PARAMS_SIZE_LIMIT=xx)`. I see `args.cmake` is being populate with the CMake variable but the file is not includes in the scheme.

Do I need to passes some CMAKE_ARGS specifically to the components?

As for jam, it looks like it is possible to give defines to it using `./b2 define=SOME_DEFINE.`. Might be a better way than changing CMAKE_CXX_FLAGS ?

**Comment by ruslo** [comment]
> As for jam, it looks like it is possible to give defines to it using ./b2 define=SOME_DEFINE.. Might be a better way than changing CMAKE_CXX_FLAGS ?

Can't say anything, need to test.

> I see args.cmake is being populate with the CMake variable but the file is not includes in the scheme

Are you sure build is triggered and Boost component was not taken from cache? If it's "stuck" in cache you can update [PACKAGE_INTERNAL_DEPS_ID](https://docs.hunter.sh/en/latest/reference/user-modules/hunter_download.html). Also I recommend you to use `jenkins.py --clear-except-download` script from: https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#testing-locally It will run tests from scratch in isolated directory.

**Comment by PyrO70** [comment]
> Can't say anything, need to test.

I'll test this.

> Are you sure build is triggered and Boost component was not taken from cache? If it's "stuck" in cache you can update PACKAGE_INTERNAL_DEPS_ID.

I run a test from the example directory and erase the _Base directory. It downloads everything and build everything from scratch. Also, I'll will update PACKAGE_INTERNAL_DEPS_ID as I have changed the scheme files, before I make it public. However, I am seeing the changes to the scheme file when it is configured, just the CMAKE_ARGS variable are not being replaced. Will try again with PACKAGE_INTERNAL_DEPS_ID.
