### ISSUE TITLE
Boost filesystem on MacOS does not build

### ISSUE THREAD

**Issue by aadityakalsi** [ruslo/hunter#108]
Hunter gets through the download and the headers install, but when it comes to the filesystem build,
it fails:
```
   "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -no-cpp-precomp -gdwarf-2 -fexceptions  -DBOOST_ALL_NO_LIB=1 -DBOOST_SYSTEM_STATIC_LINK=1 -DNDEBUG  -I"." -c -o "bin.v2/libs/system/build/darwin-4.2.1/release/link-static/threading-multi/error_code.o" "libs/system/src/error_code.cpp"

In file included from libs/system/src/error_code.cpp:18:
In file included from ./boost/system/config.hpp:13:
In file included from ./boost/config.hpp:53:
In file included from ./boost/config/platform/macos.hpp:28:
./boost/config/posix_features.hpp:18:15: fatal error: 'unistd.h' file not found
#     include <unistd.h>
              ^
1 error generated.
...skipped <pbin.v2/libs/system/build/darwin-4.2.1/release/link-static/threading-multi>libboost_system-mt.a(clean) for lack of <pbin.v2/libs/system/build/darwin-4.2.1/release/link-static/threading-multi>error_code.o...
...skipped <pbin.v2/libs/system/build/darwin-4.2.1/release/link-static/threading-multi>libboost_system-mt.a for lack of <pbin.v2/libs/system/build/darwin-4.2.1/release/link-static/threading-multi>error_code.o...
...skipped <pstage/lib>libboost_system-mt.a for lack of <pbin.v2/libs/system/build/darwin-4.2.1/release/link-static/threading-multi>libboost_system-mt.a...
darwin.compile.c++ bin.v2/libs/filesystem/build/darwin-4.2.1/release/link-static/threading-multi/v3/src/windows_file_codecvt.o
```

**Comment by ruslo** [comment]
Do you have a `/usr/include/unistd.h` file?

**Comment by aadityakalsi** [comment]
No. There is no ```/usr/include/unistd.h``` but there is one in the sysroot:

```ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/unistd.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/unistd.h```

**Comment by aadityakalsi** [comment]
Is there a missing ```-isysroot``` flag somewhere?

**Comment by ruslo** [comment]
> Is there a missing -isysroot flag somewhere?

Do you set it in CMakeLists.txt? If C++ flags not set in toolchain they will not be applied to 3rd party projects. This is necessary because user may want to add such stuff as `-Werror` which probably not a good idea to use in 3rd party packages.

**Comment by aadityakalsi** [comment]
It is not set by the CMakeLists.txt I'm using or any other cmake script. However, CMake does figure it out automatically in the regular setup.

[CMake and SYSROOT](http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_OSX_SYSROOT.html)

For some reason it is adding the ```-isysroot <SDKPATH>``` to my CPP files but not to Hunter's build of Boost.

**Comment by ruslo** [comment]
Okay I see.

> For some reason it is adding the -isysroot <SDKPATH> to my CPP files but not to Hunter's build of Boost.

Because boost is not using CMake build. We need to emulate CMake behaviour and add this flag manually.

What Xcode version do you have? I will take a look what we can do here.

**Comment by aadityakalsi** [comment]
I have Xcode 6.2. Let me know if you need any more information for this issue.

**Comment by ruslo** [comment]
Please try this one: https://github.com/ruslo/hunter/releases/tag/v0.9.5

Note that if you set custom CMAKE_OSX_SYSROOT you need to use toolchain. I will add some notes in future, see this bug: https://github.com/ruslo/hunter/issues/32

**Comment by aadityakalsi** [comment]
This did not work. It required a minor modification to your change, and then it passed!

```
-isysroot @CMAKE_OSX_SYSROOT@
```
instead of
```
-isystem @CMAKE_OSX_SYSROOT@
```

**Comment by ruslo** [comment]
> It required a minor modification to your change

Thanks for testing, applied: https://github.com/ruslo/hunter/releases/tag/v0.9.6

I've tested '-isystem' version and it works fine for me, but probably it's because I have '/usr/include/unistd.h'

**Comment by aadityakalsi** [comment]
Thank you for the quick fix. This issue is closed AFAIC.
