### ISSUE TITLE
Add Caffe2

### ISSUE THREAD

**Issue by xsacha** [ruslo/hunter#1081]
I know we already have a(n old) version of Caffe, but how about Caffe2?

https://github.com/caffe2/caffe2

It would need all the similar changes that caffe1 had so we need a hunter-package for it.

**Comment by ruslo** [comment]
> we need a hunter-package for it

https://github.com/hunter-packages/caffe2

**Comment by ruslo** [comment]
Closing, see https://github.com/ruslo/hunter/issues/1713#issue-400590629
