### ISSUE TITLE
Forward CMake arguments to Boost b2 build

### ISSUE THREAD

**Issue by aadityakalsi** [ruslo/hunter#109]
During a build of Boost iostreams:

```
gcc.compile.c++ bin.v2/libs/iostreams/build/gcc-4.8/debug/link-static/threading-multi/bzip2.o
libs/iostreams/src/bzip2.cpp:20:56: fatal error: bzlib.h: No such file or directory
 #include "bzlib.h"  // Julian Seward's "bzip.h" header.
                                                        ^
compilation terminated.

    "/usr/bin/c++"  -ftemplate-depth-128 -O0 -fno-inline -Wall -g -pthread  -DBOOST_ALL_NO_LIB=1 -DBOOST_IOSTREAMS_USE_DEPRECATED  -I"." -c -o "bin.v2/libs/iostreams/build/gcc-4.8/debug/link-static/threading-multi/bzip2.o" "libs/iostreams/src/bzip2.cpp"

...failed gcc.compile.c++ bin.v2/libs/iostreams/build/gcc-4.8/debug/link-static/threading-multi/bzip2.o...
```

Although zlib is available for Boost iostreams, the bz2 filter needs libbz2 for completing the install.

**Comment by aadityakalsi** [comment]
It may also be an option to skip the specific files that are to do with the bz2 filter.

**Comment by aadityakalsi** [comment]
Also, boost iostreams also has an LZMA filter which may require liblzma

**Comment by aadityakalsi** [comment]
According to the Boost Iostreams [install page](http://www.boost.org/doc/libs/1_57_0/libs/iostreams/doc/index.html?path=7), I should be able to get around this by specifying ```NO_BZIP2=1```, but this does not work. I tried specifying this as part of my local config.cmake.

Local cmake/Hunter/config.cmake
```
# Hunter config.cmake
hunter_config(Boost VERSION 1.57.0 CMAKE_ARGS NO_BZIP2=1)
```

Is there another way to specify this?

**Comment by ruslo** [comment]
> I should be able to get around this by specifying NO_BZIP2=1

Where we need to add this one? Is this a compiler flag `-DNO_BZIP2=1`? Or build flag `b2 NO_BZIP2=1`?

> but this does not work

Same reason as with https://github.com/ruslo/hunter/issues/108 - boost is not cmake project, so we need to do everything manually

**Comment by aadityakalsi** [comment]
I got this to work by hacking. Changing the scheme/url_sha1_boost_library.cmake.in

```
    build_opts
    -a
    ${link_opts}
    threading=multi
    ${variants}
    --layout=tagged
    toolset=${toolset_name}
    "--user-config=${boost_user_jam}"
    --with-@HUNTER_PACKAGE_COMPONENT@
)
``` 
to
```
    build_opts
    -a
    ${link_opts}
    threading=multi
    ${variants}
    --layout=tagged
    toolset=${toolset_name}
    "--user-config=${boost_user_jam}"
    --with-@HUNTER_PACKAGE_COMPONENT@
    -s NO_BZIP2=1
)
```

**Comment by aadityakalsi** [comment]
Is it worth considering adding something like ```CMAKE_ARGS``` in ```hunter_config```, but calling it ```BUILD_ARGS``` so that it applies to those 3p projects which do not directly use CMake?

**Comment by ruslo** [comment]
we can also add bzip2: https://github.com/ruslo/hunter/issues/110
my build just use zlib from standard path (?) so everything compiles fine. actually it's a bug :) https://github.com/ruslo/hunter/issues/111

**Comment by ruslo** [comment]
> Is it worth considering adding something like CMAKE_ARGS in hunter_config, but calling it BUILD_ARGS 

I think we need to use our own options, just need to document it here: https://github.com/ruslo/hunter/wiki/pkg.boost

What you think about:
```cmake
hunter_config(Boost VERSION ... CMAKE_ARGS B2_OPTS="NO_BZIP2=1")
```

Though looks quite ugly, and may not work :)

Also flag will be applied to all boost library's b2 build, so probably we must have something like this:
```cmake
hunter_config(Boost VERSION .. CMAKE_ARGS IOSTREAMS_NO_BZIP2=1)
```

**Comment by aadityakalsi** [comment]
:) That's funny because I just cloned Hunter to try to add the same IOSTREAMS_NO_BZIP2=1 check in boost library scheme.

I think that's a good name. I just created a pull request for you

**Comment by ruslo** [comment]
Try this one: https://github.com/ruslo/hunter/releases/tag/v0.9.7
Now NO_BZIP2=1 set by default: https://github.com/ruslo/hunter/blob/c4426af1503972876bf5ae95d54f36bd34280e7d/cmake/projects/Boost/hunter.cmake#L154

User can rewrite this setting locally by custom `config.cmake`. See [documentation](https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-cmake-options)

Also option added to wiki: https://github.com/ruslo/hunter/wiki/pkg.boost

If it will be more options in future I will think about structurizing it. For now it's just a working start.

**Comment by ruslo** [comment]
May be `B2_<component>_<option>=value` goes to `b2 -s <option>=value`?

**Comment by aadityakalsi** [comment]
Yes, thats a good start, but the problem is that I need to know that Boost uses B2.

Currently, I don't and that's a nice abstraction. How about just :
```<component>_<option>=value``` ==> ```b2 -s <option>=<value>```

**Comment by ruslo** [comment]
> How about just

Fine with me. Do you wish to implement it?

**Comment by aadityakalsi** [comment]
Yes. I can do that. Is there a place in the source where the arguments passed to ```CMAKE_ARGS``` are available?

**Comment by ruslo** [comment]
Yes, you can use `HUNTER_Boost_CMAKE_ARGS` variable, just note that it is set using `configure_file` command, so in template scheme it need to have `@`:
```cmake
message("HUNTER_Boost_CMAKE_ARGS: @HUNTER_Boost_CMAKE_ARGS@")
```

Also there are two build schemes for boost, so I guess we need some conversion module with one function with input parameters boost.component + boost.cmake_args and output b2.options

**Comment by aadityakalsi** [comment]
I have the change that works to allow arbitrary ```b2``` arguments given that you specify the boost component before it.

i.e.

```CMAKE_ARGS IOSTREAMS_Foo=Bar``` => ```b2 -s Foo=Bar```

Is there a particular place you wanted this macro? I'm not sure if I create a separate ```.cmake``` file for this, which directory it would be under and how to include it.

**Comment by ruslo** [comment]
> Is there a particular place you wanted this macro? I'm not sure if I create a separate .cmake file for this, which directory it would be under and how to include it.

Yes, it's [cmake/modules](https://github.com/ruslo/hunter/tree/master/cmake/modules). The rule is one function - one `.cmake` file with the same name so you can easily verify that your module used by simple `ctrl+F` (or `*` if you are GVim user like me). Name must be started with `hunter_` because this directory is public (users can use `hunter_add_package`, `hunter_add_package` use some dependencies). Boost build schemes already have command `list(APPEND CMAKE_MODULE_PATH "@HUNTER_SELF@/cmake/modules")` so you just need to add `include(hunter_<your-module-name>)`.

Also this module have no deep dependencies so you can add a unit test if you want. See examples: [issue 24](https://github.com/ruslo/hunter/blob/develop/tests/issue/24/unit/CMakeLists.txt), [issue 107](https://github.com/ruslo/hunter/blob/develop/tests/issue/107/CMakeLists.txt).

**Comment by ruslo** [comment]
> so you can add a unit test if you want

You need to install `build.py` script for it (snippet from Travis CI config):
```
    # install cmake toolchains and script
    - POLLY_VERSION="0.6.2"
    - wget "https://github.com/ruslo/polly/archive/v${POLLY_VERSION}.tar.gz"
    - tar xf "v${POLLY_VERSION}.tar.gz"
    - export PATH="`pwd`/polly-${POLLY_VERSION}/bin:${PATH}"
```

test command: 
```bash
> TOOLCHAIN=default PROJECT_DIR=tests/issue/107 ./jenkins.py --verbose
```
This will pack temporary `hunter.tar.gz` archive, load it using `HunterGate` and call your code (do not forget to init gate submodule `git submodule update --init gate`)

**Comment by aadityakalsi** [comment]
Marking this issue closed.

**Comment by ruslo** [comment]
@aadityakalsi Updated docs: https://github.com/ruslo/hunter/wiki/pkg.boost#cmake-options

**Comment by aadityakalsi** [comment]
This looks great! Thank you for your help and quick turn around to resolve this.. :)
