### ISSUE TITLE
yaml-cpp update from master

### ISSUE THREAD

**Issue by martonka** [ruslo/hunter#1095]
The last release of yaml-cpp is very old and it won't compile with c++17. 
A new release was requested more than a years ago, but nothing were done:
https://github.com/jbeder/yaml-cpp/issues/415

The head of the master branch can be compiled with c++17, and all tests run successfully.
I would like to update the yaml-cpp in hunter from the current master branch head.

**Comment by ruslo** [comment]
Find an appropriate `hunter*` branch and send pull request there https://github.com/hunter-packages/yaml-cpp

**Comment by ruslo** [comment]
Closing inactive discussion.
