### ISSUE TITLE
Add bzip2

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#110]
* http://bzip.org/

Used in boost: https://github.com/ruslo/hunter/issues/109

**Comment by aadityakalsi** [comment]
A nice github repo with bzip2 already CMake'd is [here](https://github.com/mindw/bzip2-cmake-win32)

**Comment by ruslo** [comment]
Great. I see no dependencies so we can add bzip just as is.

**Comment by ruslo** [comment]
Done: https://github.com/ruslo/hunter/wiki/pkg.bzip2

**Comment by headupinclouds** [comment]
-- [hunter] ZLIB_ROOT: /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/a360b08/7d97147/Install (ver.: 1.2.8-p3)
-- [hunter *** DEBUG *** 2015-06-07T23:18:38] Registering dependency:
-- [hunter *** DEBUG *** 2015-06-07T23:18:38]   package: Boost (component: iostreams)
-- [hunter *** DEBUG *** 2015-06-07T23:18:38]   depends on: ZLIB
-- [hunter *** DEBUG *** 2015-06-07T23:18:38] Making: /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/a360b08/7d97147/Build/Boost/__iostreams/Dependencies/ZLIB/__dep
-- [hunter *** DEBUG *** 2015-06-07T23:18:38] Package already installed: ZLIB
-- [hunter *** DEBUG *** 2015-06-07T23:18:38] load: /Users/dhirvonen/devel/hunter/cmake/projects/ZLIB/hunter.cmake ... end
-- [hunter *** DEBUG *** 2015-06-07T23:18:38] load: /Users/dhirvonen/devel/hunter/cmake/projects/BZip2/hunter.cmake

[hunter ** FATAL ERROR **] Broken package:  BZip2 is broken on iOS
[hunter ** FATAL ERROR **] [Directory:/Users/dhirvonen/devel/hunter/cmake/projects/BZip2]

**Comment by aadityakalsi** [comment]
One way to work around this until we get a long term fox is just to add IOSTREAMS_NO_BZIP2=1 in CMAKE_ARGS if on iOS.

Thoughts?

**Comment by headupinclouds** [comment]
Thanks, I found that solution in #109 after posting.  That works for my needs.

**Comment by ruslo** [comment]
> Thanks, I found that solution in #109 after posting

I think wiki is more convenient for this. Just for your information: https://github.com/ruslo/hunter/wiki/pkg.boost
