### ISSUE TITLE
Finaly hunter was mentioned at CppCon :-)

### ISSUE THREAD

**Issue by Knitschi** [ruslo/hunter#1102]
Look at this talk on youtube.

http://www.youtube.com/watch?v=30r_SsOjg2E&t=49m30s

Ruslan, you have to give your own talk about hunter on the next CppCon. The conan boys already had two full talks. ;-)

**Comment by ruslo** [comment]
> https://youtu.be/30r_SsOjg2E?t=49m56s

> `>20 supported packages`

I think one zero is missing here :) I see 267 packages at this moment:
* https://docs.hunter.sh/en/latest/packages/all.html

Not all of them are "real" (there are "mocking system" like [pkg.coregraphics](https://docs.hunter.sh/en/latest/packages/pkg/coregraphics.html) or components like [pkg.opencv-extra](https://docs.hunter.sh/en/latest/packages/pkg/OpenCV-Extra.html) which can't be used without main [pkg.opencv](https://docs.hunter.sh/en/latest/packages/pkg/OpenCV.html)) but still.

**Comment by headupinclouds** [comment]
Thanks for posting the link @Knitschi.  (No pressure @ruslo 😏.)  Does anyone know of other suitable conferences?  I think a public high level narrative like this would be an incredible way of introducing an end-to-end view of Hunter to more C++ devs and (especially) organizations.  It would also be a great opportunity to get some Hunter users communicating face-to-face in the same room.  Perhaps this type of networking could open doors to some forms of corporate sponsorship (so @ruslo can pay rent).  The measurable growing [user base](https://user-images.githubusercontent.com/554720/31845743-3d2d39ea-b5d2-11e7-9d06-07c9441849da.png) is likely to make upstream adoption much more likely, which seems to be an important long term goal.  If one or two highly visible projects adopt optional Hunter CMake mods (OpenCV, etc), I think more will follow.

**Comment by ruslo** [comment]
Closing inactive discussion.
