### ISSUE TITLE
PR template?

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#1105]
@ruslo :  What are your thoughts on PR templates?

https://github.com/blog/2111-issue-and-pull-request-templates

- [] discussion w/ links to text about hunter package cmake/projects/foo/hunter.cmake : match w/ CMakeLists.txt `project( ... VERSION )`
- [] discussion with links to text about default
- [] discussion with links to text about local and CI testing

**Comment by ruslo** [comment]
I was thinking about it but don't know what to put there.

We already have "guidelines for contributing" link:
* http://0.readthedocs.io/en/latest/git.html#read-contributing
* https://github.com/ruslo/hunter/blob/master/.github/CONTRIBUTING.rst

**Comment by ruslo** [comment]
* https://github.com/ruslo/hunter/commit/85a108bcdb548500bff862b3ff72d04a7419bd2c?diff=unified
* https://github.com/ruslo/hunter/commit/03890ae3614dd3485c1a5513839decc7cb1163af?diff=unified
* https://github.com/ingenue/hunter/commit/cc5e999a2e183eea5d1ddc7336252881a068d1c0?diff=unified
