### ISSUE TITLE
Boost.iostreams: use zlib/bzip2 from Hunter

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#111]
Need to use this variables to link Hunterized zlib/bzip2 version instead of system one:

* ZLIB_INCLUDE
* ZLIB_LIBPATH
* BZIP2_INCLUDE
* BZIP2_LIBPATH
* http://www.boost.org/doc/libs/1_57_0/libs/iostreams/doc/index.html?path=7

Related: https://github.com/ruslo/hunter/issues/109

**Comment by aadityakalsi** [comment]
How do we add a dependency between Boost Iostreams and ZLIB within Hunter? Can we call hunter_add_package()?

**Comment by ruslo** [comment]
> Can we call hunter_add_package()?

**Comment by aadityakalsi** [comment]
This fix should also leverage BZIP2 from hunter as part of Boost.Iostreams

**Comment by ruslo** [comment]
> This fix should also leverage BZIP2 from hunter as part of Boost.Iostreams

updated

**Comment by aadityakalsi** [comment]
The default use of IOSTREAMS_NO_BZIP2=1 should be removed here. We also have to account for repeated arguments and be defensive to it. By repeated arguments I refer to ```hunter_config``` default ```CMAKE_ARGS``` added to boost must be overriden if a user specifies the same ```CMAKE_ARGS```.

I am willing to make this change, but I would need our help to resolve this.

**Comment by ruslo** [comment]
> The default use of IOSTREAMS_NO_BZIP2=1 should be removed here

Yep, but only **after** this bug will be closed :)

> I refer to hunter_config default CMAKE_ARGS added to boost must be overriden if a user specifies the same CMAKE_ARGS

This is how it's working now. See documentation: https://github.com/ruslo/hunter/wiki/example.custom.config.id#arguments

**Comment by aadityakalsi** [comment]
I have some of this written. I'm stuck trying to figure out how to get LIBPATH from ZLIB_LIBRARIES. The libraries contain a list of the full paths with configurations, but I simply want the release library's parent directory.

Will I have to parse out the list to extract it by hand? Is there something like this already in hunter?

**Comment by aadityakalsi** [comment]
I have made more progress. I am now stuck at ```hunter_internal_error```

Here is some info:
```
[hunter ** INTERNAL **] Project 'ZLIB' not found
[hunter ** INTERNAL **] [Directory:/home/akalsi/.hunter/_Base/3f4283a/326318e/6e3ae24/Build/Boost/iostreams]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at /home/akalsi/.hunter/_Base/Download/Hunter/0.9.9/3f4283a/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /home/akalsi/.hunter/_Base/Download/Hunter/0.9.9/3f4283a/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  /home/akalsi/.hunter/_Base/Download/Hunter/0.9.9/3f4283a/Unpacked/cmake/modules/hunter_add_package.cmake:28 (hunter_internal_error)
  CMakeLists.txt:242 (hunter_add_package)
```

**Comment by ruslo** [comment]
> I'm stuck trying to figure out how to get LIBPATH from ZLIB_LIBRARIES

ZLIB from Hunter is an imported target so there is no full path in ZLIB_LIBRARIES (see [reason](https://github.com/ruslo/hunter/wiki/usr.adding.new.package#important)):

```cmake
find_package(ZLIB REQUIRED) # compatibility mode
message("ZLIB (libs): ${ZLIB_LIBRARIES}")
```
```
ZLIB (libs): ZLIB::zlib
```

You can get real location by using [INTERFACE_INCLUDE_DIRECTORIES](http://www.cmake.org/cmake/help/v3.2/prop_tgt/INTERFACE_INCLUDE_DIRECTORIES.html) and [IMPORTED_LOCATION](http://www.cmake.org/cmake/help/v3.2/prop_tgt/IMPORTED_LOCATION.html) properties:
```cmake
find_package(ZLIB REQUIRED CONFIG)

get_target_property(zlib_include ZLIB::zlib INTERFACE_INCLUDE_DIRECTORIES)
message("ZLIB (include): ${zlib_include}")

get_target_property(zlib_debug ZLIB::zlib IMPORTED_LOCATION_DEBUG)
message("ZLIB (debug): ${zlib_debug}")

get_target_property(zlib_release ZLIB::zlib IMPORTED_LOCATION_RELEASE)
message("ZLIB (release): ${zlib_release}")
```
```
ZLIB (debug): /.../b5d756e/f453843/Install/lib/libzd.a
ZLIB (release): /.../b5d756e/f453843/Install/lib/libz.a
```
Or when some other [build types](https://github.com/ruslo/hunter/wiki/example.hunter_configuration_types) used:
```cmake
get_target_property(zlib_minsizerel ZLIB::zlib IMPORTED_LOCATION_MINSIZEREL)
message("ZLIB (minsizerel): ${zlib_minsizerel}")

get_target_property(zlib_relwithdebinfo ZLIB::zlib IMPORTED_LOCATION_RELWITHDEBINFO)
message("ZLIB (relwithdebinfo): ${zlib_relwithdebinfo}")
```
```
ZLIB (minsizerel): /.../b5d756e/f453843/Install/lib/libz-MinSizeRel.a
ZLIB (relwithdebinfo): /.../b5d756e/f453843/Install/lib/libz-RelWithDebInfo.a
```

For now we can start with defaults (i.e. Release/Debug only).

**Comment by ruslo** [comment]
> I am now stuck at hunter_internal_error

Heh :) Other assert my be triggered here actually, just made it in branch `bin.cache`: https://github.com/ruslo/hunter/commit/0b63a04a4d0b81c8ccf36f1b3f026efa184c55a6

Well I just forget that we are in template file so some important variables not set (for example there is `@HUNTER_SELF@` but no `${HUNTER_SELF}`). We need to include master file:
```cmake
include("@HUNTER_SELF@/cmake/Hunter")
```

Also I fix some initialization error in branch `develop` please do update or use this [release](https://github.com/ruslo/hunter/releases/tag/v0.9.10).

With all of this changes it works for me.

**Comment by aadityakalsi** [comment]
Actually, now that I think about it, its probably better to pass ZLIB_SOURCE and BZIP2_SOURCE and let Boost build it according to its own make rules. This way if some other CMake package I am building uses ZLIB they get to do it their own way (shared/static etc.) without interfering with Boost.

Is it possible to just get the SOURCES using ```hunter``` and not adding the package?

**Comment by ruslo** [comment]
> its probably better to pass ZLIB_SOURCE and BZIP2_SOURCE and let Boost build it according to its own make rules

In this case we at least will build this library twice (one in Hunter and one in boost). and if boost will use his own way of building we may have a problems. Sources are available only in archive (in `${HUNTER_ROOT}/_Base/Download` directory) since we don't need them after install.

**Comment by aadityakalsi** [comment]
In this case then, this issue is fixed with the given pull request AFAIK.
