### ISSUE TITLE
GTest fails to build when client sets  CMAKE_<config>_POSTFIX variables.

### ISSUE THREAD

**Issue by Knitschi** [ruslo/hunter#1110]
The problem occurs when building with Visual Studio, debug flags and BUILD_SHARED_LIBS=ON.

The code for installing the .pdb files does not respect the value of the CMAKE_<config>_POSTFIX variables, because it uses hardcoded postfixes.

This is affecting my own build, so I will fix it within the next days.

Update:
I just saw that I am using the old version 1.8.0-hunter-p5. I will see if this happens with the newer version too.

Update2:
The problem also occurs with version 1.8.0-hunter-p7.

Btw is it intended that version 1.8.0-hunter-p8 was released, but is not listed in the hunter.cmake file of the package?

**Comment by ruslo** [comment]
> The code for installing the .pdb files does not respect the value of the CMAKE__POSTFIX variables, because it uses hardcoded postfixes.

Since it's not a Hunter issue it's better to open discussion here:
* https://github.com/hunter-packages/googletest

> Btw is it intended that version 1.8.0-hunter-p8 was released, but is not listed in the hunter.cmake file of the package?

I guess nobody opened new pull request with version update :)

**Comment by Knitschi** [comment]
I opened a new issue at the package hunter-packages/googletest#15
