### ISSUE TITLE
GTest package fails on license file copy when using it via `GIT_SUBMODULE`

### ISSUE THREAD

**Issue by Knitschi** [ruslo/hunter#1112]
I think the problem is caused by the lines

````cmake
# hunter.cmake
...
if(HUNTER_GTest_VERSION VERSION_LESS 1.8.0)
  set(_gtest_license "LICENSE")
else()
  set(_gtest_license "googletest/LICENSE")
endif()
...
````

I am not sure how we can check for GIT_SUBMODULE version here and then use the lower path.

Update:
When I remove the conditional and only use the second case, the problem does not occurr. So it seams that the version comparison must be fixed. I will try to do it with a regular expression.

**Comment by ruslo** [comment]
While you're using `GIT_SUBMODULE` the `HUNTER_GTest_VERSION` will be set to SHA1 of commit of submodule. This will not work. You can add this peculiarity to documentation. I guess you can use HUNTER_INSTALL_LICENSE_FILES as a workaround:
* https://docs.hunter.sh/en/latest/user-guides/cmake-user/using-license-files.html

**Comment by ruslo** [comment]
Closing inactive discussion.
