### ISSUE TITLE
Stuck on Boost-system installation with hunter

### ISSUE THREAD

**Issue by zmx01403137** [ruslo/hunter#1113]
While try to use hunter to install Boost, it will always stuck on below:
...
[ 75%] Performing build step for 'Boost-system'

From ps command, can find hunter provide wrong thread number "-j 1568", this cause the build step stuck. In actually, there only have 56 logical CPU cores can be used. Anyone knows how to specify the thread number?
$ ps -ef |grep b2
xxxx   50486 50203  0 21:36 pts/5    00:00:00 /bin/sh -c cd /home/xxxx/.hunter/_Base/906f0fb/265d551/a4caece/Build/Boost/__system/Source && ./b2 -a link=static threading=multi variant=debug,release --layout=tagged toolset=gcc --user-config=/home/xxxx/.hunter/_Base/906f0fb/265d551/a4caece/Build/Boost/__system/Build/boost.user.jam --with-system **-j 1568** --ignore-site-config
xxxx   50488 50486 99 21:36 pts/5    00:02:27 ./b2 -a link=static threading=multi variant=debug,release --layout=tagged toolset=gcc --user-config=/home/xxxx/.hunter/_Base/906f0fb/265d551/a4caece/Build/Boost/__system/Build/boost.user.jam --with-system **-j 1568** --ignore-site-config

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/issues/668
https://github.com/ruslo/hunter/issues/901

**Comment by zmx01403137** [comment]
Thanks ruslo, passing HUNTER_JOBS_NUMBER to cmake is working.

**Comment by ruslo** [comment]
Closing inactive discussion.

**Comment by joelteply** [comment]
Works with HUNTER_JOBS_NUMBER set to something rational, thanks
