### ISSUE TITLE
ABI not detected for CXX compiler

### ISSUE THREAD

**Issue by JonAlvik** [ruslo/hunter#1117]
Configuring protobuf fails with this message:

> -- The C compiler identification is GNU 7.2.0
> -- The CXX compiler identification is GNU 7.2.0
> -- Check for working C compiler: /usr/bin/cc
> -- Check for working C compiler: /usr/bin/cc -- works
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/c++
> -- Check for working CXX compiler: /usr/bin/c++ -- works
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> 
> [hunter ** FATAL ERROR **] ABI not detected for CXX compiler
> [hunter ** FATAL ERROR **] [Directory:/home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf/Source]
> 

I can make a copy of the archive hunter downloaded, extract and compile with no errors or complaints from cmake.

Can reproduce with this CMakeLists.txt:

```
cmake_minimum_required(VERSION 3.0)
include("HunterGate.cmake")
HunterGate(
  URL "https://github.com/ruslo/hunter/archive/v0.19.133.tar.gz"
  SHA1 "510315cd43ebfb92c5459c54aa4f31f0e1c9212d"
  )
project(lol)
hunter_add_package(Protobuf)
```

Using Ubuntu 17.10
gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0
g++ (Ubuntu 7.2.0-8ubuntu3) 7.2.0
cmake version 3.9.1

/Jon

**Comment by ruslo** [comment]
Please add log with `HUNTER_STATUS_DEBUG=ON`:
```
Run build again with HUNTER_STATUS_DEBUG=ON
```
From:
* https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs

**Comment by JonAlvik** [comment]
Sorry, should have read the "reporting-bugs" first.

Here is log until first hunter error:

-- [hunter *** DEBUG *** 2017-10-26T13:40:59] HUNTER_ROOT set using HOME environment variable
-- [hunter *** DEBUG *** 2017-10-26T13:40:59] HUNTER_ROOT: /home/jaa/.hunter
-- [hunter *** DEBUG *** 2017-10-26T13:40:59] Settings (initialize):
-- [hunter *** DEBUG *** 2017-10-26T13:40:59]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2017-10-26T13:40:59]   Cache init (NO)
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [hunter *** DEBUG *** 2017-10-26T13:41:00] Single-configuration generator
-- [hunter *** DEBUG *** 2017-10-26T13:41:00] Using default cache server
-- [hunter *** DEBUG *** 2017-10-26T13:41:00] List of cache servers:
-- [hunter *** DEBUG *** 2017-10-26T13:41:00]   * https://github.com/ingenue/hunter-cache
-- [hunter *** DEBUG *** 2017-10-26T13:41:00] Settings (finalize):
-- [hunter *** DEBUG *** 2017-10-26T13:41:00]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2017-10-26T13:41:00]   Cache init (NO)
-- [hunter *** DEBUG *** 2017-10-26T13:41:00] Variables from HunterGate:
-- [hunter *** DEBUG *** 2017-10-26T13:41:00]   HUNTER_GATE_ROOT: /home/jaa/.hunter
-- [hunter *** DEBUG *** 2017-10-26T13:41:00]   HUNTER_GATE_VERSION: 0.19.133
-- [hunter *** DEBUG *** 2017-10-26T13:41:00]   HUNTER_GATE_SHA1: 510315cd43ebfb92c5459c54aa4f31f0e1c9212d
-- [hunter *** DEBUG *** 2017-10-26T13:41:00] Set CMAKE_DEBUG_POSTFIX to: d
-- [hunter] Calculating Toolchain-SHA1
-- [hunter *** DEBUG *** 2017-10-26T13:41:00] [/home/jaa/sandbox/whatever/build/_3rdParty/Hunter/toolchain] > "/usr/bin/cmake" "-DTOOLCHAIN_INFO_FILE=/home/jaa/sandbox/whatever/build/_3rdParty/Hunter/toolchain/toolchain.info" "-DHUNTER_SELF=/home/jaa/.hunter/_Base/Download/Hunter/0.19.133/510315c/Unpacked" "-GUnix Makefiles" "-H/home/jaa/sandbox/whatever/build/_3rdParty/Hunter/toolchain" "-B/home/jaa/sandbox/whatever/build/_3rdParty/Hunter/toolchain/_builds" "-DCMAKE_MAKE_PROGRAM=/usr/bin/make" "-DCMAKE_RELEASE_POSTFIX=" "-DCMAKE_DEBUG_POSTFIX=d"
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jaa/sandbox/whatever/build/_3rdParty/Hunter/toolchain/_builds
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Already exists: /home/jaa/.hunter/_Base/510315c/8d47408/toolchain.info
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: /home/jaa/.hunter
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] HUNTER_TOOLCHAIN_ID_PATH: /home/jaa/.hunter/_Base/510315c/8d47408
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] HUNTER_CONFIGURATION_TYPES: Release;Debug
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] HUNTER_BUILD_SHARED_LIBS: 
-- [hunter] [ Hunter-ID: 510315c | Toolchain-ID: 8d47408 | Config-ID: ca6439a ]
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] load: /home/jaa/.hunter/_Base/Download/Hunter/0.19.133/510315c/Unpacked/cmake/projects/Protobuf/hunter.cmake
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Protobuf versions available: [3.0.0-p1;3.0.0;3.0.0-beta-2;3.0.0-beta-2-p1;3.1.0;3.3.0]
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Install to: /home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Install
-- [hunter] PROTOBUF_ROOT: /home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Install (ver.: 3.3.0)
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Default arguments: protobuf_BUILD_TESTS=OFF
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] User arguments: 
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Locking directory: /home/jaa/.hunter/_Base/Download/Protobuf/3.3.0/8815a6b
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Lock done
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Already locked: /home/jaa/.hunter/_Base/Download/Protobuf/3.3.0/8815a6b
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Locking directory: /home/jaa/.hunter/_Base/510315c/8d47408/ca6439a
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Lock done
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Add extra CMake args: 'protobuf_BUILD_TESTS' = 'OFF'
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Locking directory: /home/jaa/.hunter/_Base/Cache
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Lock done
-- [hunter *** DEBUG *** 2017-10-26T13:41:01] Downloading file (try #0 of 10):
-- [hunter *** DEBUG *** 2017-10-26T13:41:01]   https://raw.githubusercontent.com/ingenue/hunter-cache/master/8d47408/Protobuf/3.3.0/8815a6b/796c6c1/a49b0e5/da39a3e/basic-deps.DONE
-- [hunter *** DEBUG *** 2017-10-26T13:41:01]   -> /home/jaa/.hunter/_Base/Cache/meta/8d47408/Protobuf/3.3.0/8815a6b/796c6c1/a49b0e5/da39a3e/basic-deps.DONE
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] File not found
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] Downloading file (try #1 of 10):
-- [hunter *** DEBUG *** 2017-10-26T13:41:02]   https://raw.githubusercontent.com/ingenue/hunter-cache/master/8d47408/Protobuf/3.3.0/8815a6b/796c6c1/a49b0e5/da39a3e/basic-deps.DONE
-- [hunter *** DEBUG *** 2017-10-26T13:41:02]   -> /home/jaa/.hunter/_Base/Cache/meta/8d47408/Protobuf/3.3.0/8815a6b/796c6c1/a49b0e5/da39a3e/basic-deps.DONE
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] File not found
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] Cache miss (no basic dependencies info found: /home/jaa/.hunter/_Base/Cache/meta/8d47408/Protobuf/3.3.0/8815a6b/796c6c1/a49b0e5/da39a3e/basic-deps.DONE)
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] Number of logical cores per physical core: 4
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] Number of physical cores: 2
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] Total number of cores: 8
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] HUNTER_JOBS_NUMBER: 
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] HUNTER_JOBS_OPTION: 8
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] Add package: Protobuf
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] Download scheme: url_sha1_cmake
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] Url: https://github.com/hunter-packages/protobuf/archive/v3.3.0-hunter-1.tar.gz
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] SHA1: 8815a6be8188b2d6c8002924e752018b64658748
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] Configuration types: Release;Debug
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] Scheme file used: /home/jaa/.hunter/_Base/Download/Hunter/0.19.133/510315c/Unpacked/cmake/schemes/url_sha1_cmake.cmake.in
-- [hunter] Building Protobuf
-- [hunter *** DEBUG *** 2017-10-26T13:41:02] [/home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf] > "/usr/bin/cmake" "-C/home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/cache.cmake" "-C/home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf/args.cmake" "-H/home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf" "-B/home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf/Build" "-DCMAKE_TOOLCHAIN_FILE=/home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf/toolchain.cmake" "-GUnix Makefiles" "-DCMAKE_MAKE_PROGRAM=/usr/bin/make"
loading initial cache file /home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/cache.cmake
loading initial cache file /home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf/args.cmake
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf/Build
-- [hunter *** DEBUG *** 2017-10-26T13:41:03] Configure step successful (dir: /home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf)
-- [hunter *** DEBUG *** 2017-10-26T13:41:03] [/home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf] > "/usr/bin/cmake" "--build" "/home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf/Build"
Scanning dependencies of target Protobuf-Release
[  6%] Creating directories for 'Protobuf-Release'
[ 12%] Performing download step (download, verify and extract) for 'Protobuf-Release'
-- verifying file...
       file='/home/jaa/.hunter/_Base/Download/Protobuf/3.3.0/8815a6b/v3.3.0-hunter-1.tar.gz'
-- File already exists and hash match (skip download):
  file='/home/jaa/.hunter/_Base/Download/Protobuf/3.3.0/8815a6b/v3.3.0-hunter-1.tar.gz'
  SHA1='8815a6be8188b2d6c8002924e752018b64658748'
-- extracting...
     src='/home/jaa/.hunter/_Base/Download/Protobuf/3.3.0/8815a6b/v3.3.0-hunter-1.tar.gz'
     dst='/home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf/Source'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 18%] No patch step for 'Protobuf-Release'
[ 25%] No update step for 'Protobuf-Release'
[ 31%] Performing configure step for 'Protobuf-Release'
loading initial cache file /home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/cache.cmake
loading initial cache file /home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf/args.cmake
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done

[hunter ** FATAL ERROR **] ABI not detected for CXX compiler
[hunter ** FATAL ERROR **] [Directory:/home/jaa/.hunter/_Base/510315c/8d47408/ca6439a/Build/Protobuf/Source]

**Comment by ruslo** [comment]
Can you try to run this project (no Hunter):
```cmake
cmake_minimum_required(VERSION 3.0)
project(lol)

function(print_var x)
  message("${x}: ${${x}}")
endfunction()

foreach(x C CXX)
  print_var(CMAKE_${x}_COMPILER_ABI)
  print_var(CMAKE_${x}_ABI_COMPILED)
endforeach()
```

Build command:
```
> rm -rf _builds
> cmake -H. -B_builds
```

**Comment by JonAlvik** [comment]
The issue was resolved by deleting the directory ~/.hunter (again, I also did this yesterday with no effect)
protobuf got downloaded and compiled without problems.

**Comment by ruslo** [comment]
> The issue was resolved by deleting the directory ~/.hunter

I don't think that was a real problem. Every time you start build of the package all instructions triggered from scratch (clean source directory, clean build directory, etc.).

**Comment by JonAlvik** [comment]
Here is the output from your suggested cmake project:
Do you want to re-open?

cmake -H. -B_builds
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMAKE_C_COMPILER_ABI: ELF
CMAKE_C_ABI_COMPILED: TRUE
CMAKE_CXX_COMPILER_ABI: ELF
CMAKE_CXX_ABI_COMPILED: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jaa/sandbox/ruslo/_builds

**Comment by ruslo** [comment]
> Here is the output from your suggested cmake projec

It looks good.

> Do you want to re-open?

If you're not experiencing the problem then no need.
