### ISSUE TITLE
suggestion: bundle debug info into static libs on windows

### ISSUE THREAD

**Issue by wheybags** [ruslo/hunter#1118]
so, basically, set CMAKE_STATIC_LINKER_FLAGS to /Z7 by default on windows. This would stop msvc from complaining later when it links with [millions of missing pdb warnings](https://ci.appveyor.com/project/wheybags/freeablo/build/1.0.300#L6875)

**Comment by ruslo** [comment]
I don't think that altering default flags in any way even with the best intentions is a good idea. Can you achieve the same with toolchain?

**Comment by wheybags** [comment]
Alternatively, we could try and install the pdbs too, but I'm not sure how
that could be done without modifying every package.

**Comment by ruslo** [comment]
I don't know what is the best approach here too. Just for your information: https://github.com/ruslo/CGold/issues/8

**Comment by ruslo** [comment]
Closing inactive discussion.
