### ISSUE TITLE
yaml-cpp cannot compile on my macOS

### ISSUE THREAD

**Issue by isaachier** [ruslo/hunter#1120]
Getting errors like this:

```
/Users/isaachier/proj/cmake/hunter/_testing/Hunter/_Base/18f1855/f057cbc/f2ae283/Build/yaml-cpp/Source/include/yaml-cpp/exceptions.h:207:41: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
  BadConversion(const BadConversion&) = default;
                                        ^
```

All started when I updated to newest Hunter (0.19.136).

**Comment by isaachier** [comment]
#1116

**Comment by ruslo** [comment]
Almost all toolchains in CI use C++11. New version breaks `default` toolchain and I've simply removed it. `yaml-cpp` package has no maintainer (https://docs.hunter.sh/en/latest/packages/pkg/yaml-cpp.html) so I did as thought will be easier. If you want to manage tested/accepted toolchains please add yourself as a maintainer of this package.

If you want to use old version just use custom local config:
* https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-package-version

**Comment by isaachier** [comment]
OK I understand now. Thanks.
