### ISSUE TITLE
Add 'OpenAL' package

### ISSUE THREAD

**Issue by NukeBird** [ruslo/hunter#1123]
Hey guys

Why here is no OpenAL or any other libraries for playing sounds/music?

**Comment by wheybags** [comment]
Because you haven't made a package yet :p

**Comment by isaachier** [comment]
I got this one for you @NukeBird ;)

**Comment by NukeBird** [comment]
@isaachier you will help me very much! ^^

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/pull/1128

**Comment by NukeBird** [comment]
@isaachier thank you!

**Comment by isaachier** [comment]
No worries glad to help
