### ISSUE TITLE
How to add new packages locally?

### ISSUE THREAD

**Issue by NukeBird** [ruslo/hunter#1125]
[Creating new packages](https://docs.hunter.sh/en/latest/creating-new/create.html) looks hard for me, but I want to help your project in expanding the package base

Is it possible to practice locally on my computer?

**Comment by ruslo** [comment]
> looks hard for me

Any particular step?

> Is it possible to practice locally on my computer?

Testing locally instructions:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#testing-locally

**Comment by NukeBird** [comment]
My problems:
1. I can't understand how XXXConfig.cmake works and how can I split the package into components (for example, package [SDL2](https://github.com/ruslo/hunter/blob/master/examples/SDL2) has components SDL2::SDL2main and SDL2::SDL2)

2. [Here](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html) I can't understand how work with branches. [Example](https://github.com/hunterbox/hunter_box_1) has only master branch without any pkg.hunter_box_1, upload.hunter_box_1, pr.hunter_box_1

I'm sure that the problem is in me... But I would like to learn how to add packages to help you

**Comment by ruslo** [comment]
> I can't understand how XXXConfig.cmake works

You can find links to documentation and examples here:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#install-xxxconfig-cmake

> how can I split the package into components (for example, package SDL2 has components SDL2::SDL2main and SDL2::SDL2

It's not a components, it's targets.

> Example has only master branch without any pkg.hunter_box_1, upload.hunter_box_1, pr.hunter_box_1

Why do you think that these branches should be part of `hunter_box_1` repository?

If you mean from [this page](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#add-package-to-hunter):

```
Git branches (will be covered in details later):
* pkg.hunter_box_1 branch for testing
* upload.hunter_box_1 branch for uploading
* pr.hunter_box_1 work-in-progress branch for adding/updating package
```

 then it's explicitly said that "will be covered in details **later**".

**Comment by NukeBird** [comment]
@ruslo it is really problematic run local tests on Windows =( 

> $ ./jenkins.py
> /usr/bin/env: ‘python3’: No such file or directory

Also can I add package and USE IT locally? It will help me test the packages a bit

> then it's explicitly said that "will be covered in details later".
Oh I see. Thanks

**Comment by headupinclouds** [comment]
> Also can I add package and USE IT locally? It will help me test the packages a bit

I think there are at least two options to make local package testing easier:
* [GIT_SUBMODULE](https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html?highlight=GIT_SUBMODULE): use`hunter_config(foo GIT_SUBMDULE src/3rdparty/foo)`feature to test packages as a submodule (see: https://github.com/hunter-test-cases/git-submodule-integration-deps)
* specify a local filename path for the package in your hunter fork.  you can use a local hunter via `${HUNTER_ROOT}` and add a package using a filename like this:

`hunter/cmake/projects/OpenCV/hunter.cmake` :
```
hunter_add_version(
    PACKAGE_NAME
    OpenCV
    VERSION
    "3.2.0-p2"
    URL
    "/some/local/path/to/hunter-packages/OpenCV/v3.2.0-p2.tar.gz"
    SHA1
    99219206c4fb9b5b6f60e03112746461baf6c9ab
)
```

**Comment by headupinclouds** [comment]
> it is really problematic run local tests on Windows =(

Can you elaborate?

**Comment by NukeBird** [comment]
>Can you elaborate?
Many unix-like commands from article simply doesn't work

Also script "jenkins.py" trying find out "python3", but there is only "python"

>HUNTER_ROOT specify a local filename path for the package in your hunter fork. you can use a local hunter via ${HUNTER_ROOT} and add a package using a filename like this:

Can I see some examples? 

My project's CMakeLists usually looks like:
```
cmake_minimum_required(VERSION 3.0)

include("cmake/HunterGate.cmake")

if(WIN32)
	set(HUNTER_ROOT "$ENV{HUNTER_ROOT}")
	if(NOT HUNTER_ROOT)
		set(HUNTER_ROOT "${CMAKE_CURRENT_BINARY_DIR}/.hunter")
	endif()
endif()


HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.19.116.tar.gz"
    SHA1 "c872605eee88941a751fb91a028cc5a69c77eac0"
)

#... Now I can work with hunter
```

**Comment by headupinclouds** [comment]
> Also script "jenkins.py" trying find out "python3", but there is only "python"

I'm not a regular Windows user, but `python3` should be a fairly common utility: http://docs.python-guide.org/en/latest/starting/install3/win/

My guess is there is a fairly minimal `cmake` command that should be sufficient for local testing without using the `jenkins.py` test. 

> Can I see some examples?

For the hunter `GIT_SUBMODULE` feature integration (see: https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html?highlight=GIT_SUBMODULE) you can simply add the package as a submodule to a test project and then specify `hunter_config(foo GIT_SUBMDULE src/3rdparty/foo)` in your local config file.  I was searching for links to the docs and realized @ruslo has a test project for this already: https://github.com/hunter-test-cases/git-submodule-integration-deps.   

Note that in this project you need to specify a local config file (to override the hunter default package settings).

https://github.com/hunter-test-cases/git-submodule-integration-deps/blob/517ddfdc13b962781e85881618e0f967039dee96/CMakeLists.txt#L7
```
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.18.58.tar.gz"
    SHA1 "3b39effc5ee1af4ef7487eabb1b0a7a7e10a7b3e"
    LOCAL # i.e., cmake/Hunter/config.cmake
)
```

The `LOCAL` above will tell hunter to look in `cmake/Hunter/config.cmake`:
https://github.com/hunter-test-cases/git-submodule-integration-deps/blob/master/cmake/Hunter/config.cmake
```
hunter_config(ZLIB GIT_SUBMODULE "3rdparty/zlib")
```

In this case the file simply contains a `hunter_config()` statement telling hunter to use the submodule at `3rdparty/zlib` as a hunter package called `ZLIB`.  Under the hood this will use `git-archive` to create a local release for you (URL + SHA1), so you can apply any needed changes directly in the submodule (you will have to commit in the submodule, then update the submodule pointer in your test project as usual).



There are some examples in the comment links https://github.com/ruslo/hunter/issues/1125#issuecomment-340277670.  To use a package as a submodule you can check this example: https://github.com/hunter-test-cases/git-submodule-integration-deps

Add the project
```
cd foo
mkdir src/3rdparty
git submodule add  https://github.com/hunter-packages/zlib
```

**Comment by headupinclouds** [comment]
What are you doing in this block:
```
if(WIN32)
	set(HUNTER_ROOT "$ENV{HUNTER_ROOT}")
	if(NOT HUNTER_ROOT)
		set(HUNTER_ROOT "${CMAKE_CURRENT_BINARY_DIR}/.hunter")
	endif()
endif()
```

If an environment variable `HUNTER_ROOT` exists, then `HunterGate` will look there for a local hunter fork to use for package management.  If it doesn't exist, then the hunter released specified in your `HunterGate` call will be installed in a default location, which will be used instead.

**Comment by headupinclouds** [comment]
If you don't want to use the `GIT_SUBMODULE` option, you can also just create a local release of hunter that contains a package with a local path for the URL.

```
HunterGate(
    URL "/local/path/to/your/own/hunter.tar.gz" # just use tar or maybe git-archive
    SHA1 "c872605eee88941a751fb91a028cc5a69c77eac0" # use openssl sha1 or similar
)
```

And in the local `hunter.tar.gz` you can add the package you need with a local path (as shown above).  In the following `hunter/cmake/projects/OpenCV/hunter.cmake` file we can specify a local path to the package for the `URL` argument.

```
hunter_add_version(
    PACKAGE_NAME
    OpenCV
    VERSION
    "3.2.0-p2"
    URL
    "/some/local/path/to/hunter-packages/OpenCV/v3.2.0-p2.tar.gz" ## use a local path
    SHA1
    99219206c4fb9b5b6f60e03112746461baf6c9ab
)
```

I hope this helps.  This wasn't obvious to me for my first couple of packages, so I ended up with 100 incremental commits before getting each package working.

**Comment by headupinclouds** [comment]
>> The LOCAL above will tell hunter to look in cmake/Hunter/config.cmake:

> Wow! Nice feature! I'll test it soon

That feature is also how you provide a custom package `VERSION` or `CMAKE_ARGS` list.  You may want to update Hunter to get new features, but maintain specific package versions with custom CMake arguments for each build.

The `HunterGate` README has more info.  

https://github.com/hunter-packages/gate

You can also use `FILEPATH` if you want to specify your own config file.

**Comment by headupinclouds** [comment]
> there is a fairly minimal cmake command that should be sufficient for local testing without using the jenkins.py test. [TODO: This might be worth investigating and adding to docs]

As a follow up:

Docs: https://github.com/ruslo/hunter/wiki/dev.hunter.root#jenkinspy

The `jenkins.py` test script expands to the  cmake `Execute command` in the output below.

```
hanuman:hunter dhirvonen$ TOOLCHAIN=default PROJECT_DIR=examples/ZLIB ./jenkins.py
Using POLLY_ROOT: /Users/dhirvonen/devel/ruslo/polly
Testing in: /private/tmp/hunter/_testing
Execute command: [
  `/usr/local/opt/python3/bin/python3.6`
  `/Users/dhirvonen/devel/ruslo/polly/bin/build.py`
  `--clear`
  `--config`
  `Release`
  `--toolchain`
  `default`
  `--home`
  `/private/tmp/hunter/examples/ZLIB`
  `--fwd`
  `CMAKE_POLICY_DEFAULT_CMP0069=NEW`
  `HUNTER_SUPPRESS_LIST_OF_FILES=ON`
  `HUNTER_ROOT=/private/tmp/hunter/_testing/Hunter`
  `TESTING_URL=/private/tmp/hunter/_testing/hunter.tar.gz`
  `TESTING_SHA1=1f93a940c5e42d3ffaa3a52fd1f37463c82e419f`
  `HUNTER_RUN_INSTALL=ON`
  `--verbose`
]
Python version: 3.6
Build dir: /private/tmp/hunter/_testing/_builds/default-Release
Execute command: [
  `which`
  `cmake`
]

[/private/tmp/hunter/_testing]> "which" "cmake"

/usr/local/bin/cmake
Execute command: [
  `cmake`
  `--version`
]

[/private/tmp/hunter/_testing]> "cmake" "--version"

cmake version 3.9.4

CMake suite maintained and supported by Kitware (kitware.com/cmake).
Execute command: [
  `cmake`
  `-H/private/tmp/hunter/examples/ZLIB`
  `-B/private/tmp/hunter/_testing/_builds/default-Release`
  `-DCMAKE_BUILD_TYPE=Release`
  `-DCMAKE_TOOLCHAIN_FILE=/Users/dhirvonen/devel/ruslo/polly/default.cmake`
  `-DCMAKE_VERBOSE_MAKEFILE=ON`
  `-DPOLLY_STATUS_DEBUG=ON`
  `-DHUNTER_STATUS_DEBUG=ON`
  `-DCMAKE_POLICY_DEFAULT_CMP0069=NEW`
  `-DHUNTER_SUPPRESS_LIST_OF_FILES=ON`
  `-DHUNTER_ROOT=/private/tmp/hunter/_testing/Hunter`
  `-DTESTING_URL=/private/tmp/hunter/_testing/hunter.tar.gz`
  `-DTESTING_SHA1=1f93a940c5e42d3ffaa3a52fd1f37463c82e419f`
  `-DHUNTER_RUN_INSTALL=ON`
]
```

**Comment by ruslo** [comment]
> it is really problematic run local tests on Windows

Similar to Linux/OSX with common peculiarities for Windows.
I've added few notes to documentation:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#testing-locally

> /usr/bin/env: ‘python3’: No such file or directory

I guess Python 3 is not installed?

> set(HUNTER_ROOT "$ENV{HUNTER_ROOT}")

Environment variable `HUNTER_ROOT` will be used automatically if set.
There is no need to read it explicitly:
* https://github.com/hunter-packages/gate#effects

> set(HUNTER_ROOT "${CMAKE_CURRENT_BINARY_DIR}/.hunter")

I'm not sure why do you need this at all. If you will use it everywhere then every local project 
will have his own local copy of 3rd parties. You are not getting benefit of been shareable:
* https://docs.hunter.sh/en/latest/overview/shareable.html

Also if you hardcode this variable there is no way to overwrite it.
There is no way to specify custom HUNTER_ROOT without patching the file.

If you want to customize it anyway at least set it to cache:

```cmake
set(HUNTER_ROOT "${CMAKE_CURRENT_BINARY_DIR}/.hunter" CACHE PATH "")
```

See:
* http://cgold.readthedocs.io/en/latest/tutorials/variables/cache.html#use-case

> Default path is C:/.hunter . I don't think that writing to the system drive is a good idea

Set environment variable `HUNTER_ROOT` to whatever you think is more appropriate.

**Comment by ruslo** [comment]
Closing inactive discussion.

**Comment by NukeBird** [comment]
@mchiasson you are welcome ^^

**Comment by mchiasson** [comment]
thank you @NukeBird :+1:

**Comment by jakesyl** [comment]
> > Also can I add package and USE IT locally? It will help me test the packages a bit
> 
> I think there are at least two options to make local package testing easier:
> 
> * [GIT_SUBMODULE](https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html?highlight=GIT_SUBMODULE): use`hunter_config(foo GIT_SUBMDULE src/3rdparty/foo)`feature to test packages as a submodule (see: https://github.com/hunter-test-cases/git-submodule-integration-deps)
> * [HUNTER_ROOT](https://docs.hunter.sh/en/latest/reference/user-variables.html?highlight=HUNTER_ROOT#hunter-root) specify a local filename path for the package in your hunter fork.  you can use a local hunter via `${HUNTER_ROOT}` and add a package using a filename like this:
> 
> `hunter/cmake/projects/OpenCV/hunter.cmake` :
> 
> ```
> hunter_add_version(
>     PACKAGE_NAME
>     OpenCV
>     VERSION
>     "3.2.0-p2"
>     URL
>     "/some/local/path/to/hunter-packages/OpenCV/v3.2.0-p2.tar.gz" ## use a local path
>     SHA1
>     99219206c4fb9b5b6f60e03112746461baf6c9ab
> )
> ```

btw, this should be `GIT_SUBMODULE` not `GIT_SUBMDULE`
