### ISSUE TITLE
add VORBIS

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#1132]
Please create hunter-packages/vorbis

https://github.com/xiph/vorbis (CMake)

**Comment by ruslo** [comment]
Done: https://github.com/hunter-packages/vorbis

**Comment by NukeBird** [comment]
Interesting fact: release archives don't contain any CMakeLists, but CMakeLists exist on repo

I already asked to add it to the release: https://github.com/xiph/vorbis/issues/32
If all goes well, fork will need to be updated
>Done: https://github.com/hunter-packages/vorbis

BTW we can make local release with CMakeLists inside

**Comment by headupinclouds** [comment]
> Interesting fact: release archives don't contain any CMakeLists, but CMakeLists exist on repo

I noticed that in the ogg fork.  I think CMakeLists.txt was added recently (after the last release).  I think the upstream CMakeLists.txt is very close to being usable.  In the case of ogg, I think the package config stuff wasn't being installed with the release so that `find_package()` calls would work on the install tree.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/pull/1455
