### ISSUE TITLE
Project generation fails when -DHUNTER_ENABLED=OFF

### ISSUE THREAD

**Issue by NukeBird** [ruslo/hunter#1139]
I generate project at the begining via
`cmake . -Bbuild`

Then I noticed that calculating SHA1 stuff is slow. So I tried generate project with HUNTER_ENABLED=OFF:
```
$ cmake . -Bbuild -DHUNTER_ENABLED=OFF
CMake Error at test/CMakeLists.txt:13 (message):
  File not found: '


-- Configuring incomplete, errors occurred!
See also "D:/Desktop/SP3D/build/CMakeFiles/CMakeOutput.log".
```

I noticed that main CMakeLists works OK, but error occurs in child's CMakeLists: https://github.com/NukeBird/SP3D/blob/develop/test/CMakeLists.txt

**Comment by NukeBird** [comment]
```
if(NOT EXISTS "${GTest_LICENSES}")
  message(FATAL_ERROR "File not found: '${GTest_LICENSES}")
endif()
```

It just can't find ${GTest_LICENSES} value

**Comment by headupinclouds** [comment]
> It just can't find ${GTest_LICENSES} value

This variable is provided by hunter, so it won't be present if hunter is disabled.

Also, you probably don't want a second `project()` call in your project here:

https://github.com/NukeBird/SP3D/blob/999c3af1e07ecf5b15029ae898e9acc860f80471/test/CMakeLists.txt#L1

**Comment by NukeBird** [comment]
>This variable is provided by hunter, so it won't be present if hunter is disabled.

Possible workaround: wrap it by` if(HUNTER_ENABLED) ... endif()` ?

> Also, you probably don't want a second project() call in your project here:
Oh, you're quite right. Thank you

**Comment by NukeBird** [comment]
>Possible workaround: wrap it byif(HUNTER_ENABLED) ... endif() ?

Anyway why ${GTest_LICENSES} can't be provided by config file?

**Comment by ruslo** [comment]
> Anyway why ${GTest_LICENSES} can't be provided by config file?

When `HUNTER_ENABLED=OFF` Hunter can't do anything about it. Update package for this functionality.
