### ISSUE TITLE
Can build get error 'CMakeFiles/Boost-system.dir/all' failed

### ISSUE THREAD

**Issue by vladimircape** [ruslo/hunter#1144]
Try cmake ..
and get 

> ~/.hunter/_Base/435b09a/cd01ff3/0452b62/Build/Boost/__system/Build# make
> [ 12%] Performing build step for 'Boost-system'
> Invalid value for the '-j' option, valid values are 1 through 256.
> CMakeFiles/Boost-system.dir/build.make:114: recipe for target 'Boost-system-prefix/src/Boost-system-stamp/Boost-system-build' failed
> make[2]: *** [Boost-system-prefix/src/Boost-system-stamp/Boost-system-build] Error 1
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Boost-system.dir/all' failed
> make[1]: *** [CMakeFiles/Boost-system.dir/all] Error 2
> Makefile:83: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by ruslo** [comment]
> This issue still exists

It was not resolved as fixed, issues still opened:
* https://github.com/ruslo/hunter/issues/1113
* https://github.com/ruslo/hunter/issues/668
