### ISSUE TITLE
add fft2d

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#1153]
UPDATE: Initial mirror added here https://github.com/headupinclouds/fft2d

https://github.com/tensorflow/tensorflow/blob/7f84d88d39f236e5c0cea492a2248782e696c972/tensorflow/contrib/cmake/external/fft2d.cmake#L18-L19
```
set(fft2d_URL http://www.kurims.kyoto-u.ac.jp/~ooura/fft.tgz)
set(fft2d_HASH SHA256=52bb637c70b971958ec79c9c8752b1df5ff0218a4db4510e60826e0cb79b5296)
```

I see this source code included in various projects but didn't find a github fork for the project.

**Comment by ruslo** [comment]
https://github.com/hunter-packages/fft2d

**Comment by headupinclouds** [comment]
Thanks.  Updated PR https://github.com/ruslo/hunter/pull/1161

**Comment by headupinclouds** [comment]
Merged.
