### ISSUE TITLE
add/move grpc to hunter-packages

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#1182]
original: https://github.com/grpc/grpc
hunterized: https://github.com/isaachier/grpc

https://github.com/ruslo/hunter/blob/master/cmake/projects/gRPC/hunter.cmake
```
hunter_add_version(
    PACKAGE_NAME gRPC
    VERSION "1.6.6"
    URL "https://github.com/isaachier/grpc/archive/hunter-1.6.6-p6.tar.gz"
    SHA1 "c4abbf4a411f794f4cac2a0ec2311187b6fee31f")
```

**Comment by ruslo** [comment]
Related:
* https://github.com/ruslo/hunter/issues/561
* https://github.com/ruslo/hunter/pull/1109

You want to move to `hunter-packages`?

**Comment by headupinclouds** [comment]
> You want to move to hunter-packages?

Yes, I think centralizing the patched forks in hunter-packages is a good idea .

cc: @isaachier

**Comment by isaachier** [comment]
Good idea. Didn't realize I did that.

**Comment by ruslo** [comment]
Fixed by https://github.com/ruslo/hunter/pull/1183
