### ISSUE TITLE
QT: option to enable or disable static runtime

### ISSUE THREAD

**Issue by Dargun** [ruslo/hunter#1190]
need an option in the url_sh1_qt.cmak.in  to enable or disable static runtime.

**Comment by ruslo** [comment]
> to enable or disable static runtime

Build shared or static libraries?

**Comment by Dargun** [comment]
it's an windows only feature.
Currently qt build is with dynamic runtime /MD.
For shared libs it needs to be foreced to dynamic runtime, 
but for static libs it can be usefull to enable static runtime.

option could be implemented like this.
if(BUILD_SHARED_LIBS)
  list(APPEND configure_opts "-shared")
else()
  list(APPEND configure_opts "-static")
  if("@MSVC@" AND BUILD_STATIC_RUNTIME)
     list(APPEND configure_opts "-static-runtime")
  endif()
endif()

**Comment by ruslo** [comment]
As far as I understand `/MD` and `/MT` are not compatible, meaning either all projects use `/MD` or all projects use `/MT`. Hence it should be set globally. For Hunter it means that this flag should be set in toolchain. E.g. like this:
* https://github.com/ruslo/polly/blob/master/vs-12-2013-mt.cmake
* https://github.com/ruslo/polly/blob/master/flags/vs-mt.cmake

Next, from [this page](https://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx):
* `/MD` defines `_MT` and `_DLL`
* `/MT` defines only `_MT`

You can use [hunter_check_toolchain_definition](https://docs.hunter.sh/en/latest/reference/user-modules/hunter_check_toolchain_definition.html) function to analyze `_DLL` and if it's present (not present?) add `QT_BUILD_STATIC_RUNTIME=YES` to Qt build via `CMAKE_ARGS` in `hunter.cmake`. Then use `QT_BUILD_STATIC_RUNTIME` in build scheme as you suggested.

**Comment by Dargun** [comment]
Thats right, all targets needs to be /MT.
It's not possble to mix.
All my targets compile with /MT but i need to enable it also for qt build.

i tried also this:
**hunter_config(Qt VERSION 5.9.1-p0 CMAKE_ARGS BUILD_SHARED_LIBS=OFF QT_BUILD_STATIC_RUNTIME=YES)**
but this doesn't work.

i think the standard way for qt setup is only to call configure.bat with added option like this **-static-runtime**.

**Comment by ruslo** [comment]
> i tried also this ... QT_BUILD_STATIC_RUNTIME=YES

I haven't said that it's working, I've described the way to introduce the fix :)

**Comment by ruslo** [comment]
Closing inactive discussion.
