### ISSUE TITLE
OpenCV with Qt backend, how can we test it?

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#1193]
Hello Ruslan and others,

Some time ago I contributed changes to OpenCV to enable to Qt backend which is used to create GUI in OpenCV (and really useful for testing and developing with OpenCV).

Now I need to use OpenCV's GUI module and things don't link anymore with the latest hunter version as of today.

I understand there is a problem compiling Qt on Travis, is there any other way we can have tests that depend on Qt running? It is just mildly annoying that I wanted to jump straight into development, but have to fight with the build system once again.

As I side note, I am aware of the gtk backend for OpenCV. Being desperate, I did try to add gtk to hunter locally, but libtiff4 used by hunter does not have the pkgconfig files, so one of the dependencies of gtk (can't remember which), does not find it at  `./configure` time. Also, the gtk backend for OpenCV is poor compared to Qt's, so this would not be an ideal solution.

Without the GUI backend I have to keep writing images to disk and examining them after the program runs, which makes development with OpenCV very slow. If anyone can think of a way we could solve this problem in a scalable way, I will happily implement it.

**Comment by ruslo** [comment]
> I understand there is a problem compiling Qt on Travis

We are hitting timeouts on Travis because it takes a lot of time to compile Qt components. I'm uploading binaries from my local machine. Available toolchains can be found in `pkg.qt` branch:
* https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=pkg.qt

**Comment by pretyman** [comment]
Does that mean that if have another branch in ingenue, it should be enough to test it? Something like pkg.opencv-qt?

**Comment by ruslo** [comment]
> Something like pkg.opencv-qt?

It's better to add new entry to the testing matrix in `pkg.opencv`.

**Comment by pretyman** [comment]
Cool, that can be done, what I don't know how to do is to enable CMAKE_ARGS
to Opencv with WITH_QT=YES through polly command line.

I only know how to do it creating a custom config.cmake for hunter and I
would need a branch for that.

What did you have in mind when you suggested to add it to the test matrix?

**Comment by ruslo** [comment]
> What did you have in mind when you suggested to add it to the test matrix?

Create example `OpenCV-with-Qt` and add local config with `WITH_QT=YES`. See `OpenCV-extra` example:
* https://github.com/ruslo/hunter/blob/2a00835c620870fe8b6a6a2cfdd6af6008fb06c9/examples/OpenCV-extra/CMakeLists.txt#L5
* https://github.com/ruslo/hunter/blob/2a00835c620870fe8b6a6a2cfdd6af6008fb06c9/examples/OpenCV-extra/config.cmake#L1-L9

**Comment by pretyman** [comment]
Understood, thanks

**Comment by headupinclouds** [comment]
[nanogui](https://github.com/wjakob/nanogui) (glfw based) might be a nice lightweight hunter package for this type of work (without the 2 hour QT builds).

**Comment by ruslo** [comment]
Closing inactive discussion.
