### ISSUE TITLE
HUNTER_<name>_VERSION can't be empty with package intsizeof

### ISSUE THREAD

**Issue by dvirtz** [ruslo/hunter#1197]
I'm trying to build examples/intsizeof and get the error 
```
[hunter ** INTERNAL **] HUNTER_<name>_VERSION can't be empty 
[hunter ** INTERNAL **] (intsizeof)
[hunter ** INTERNAL **] (probably `hunter_config(...)` missing in config file)
[hunter ** INTERNAL **] [Directory:C:/Users/Dvir/Documents/GitHub/hunter/cmake/projects/IntSizeof]
```

I've added `variable_watch(HUNTER_intsizeof_VERSION)` command and I get the following output:

```
CMake Debug Log at C:/Users/Dvir/Documents/GitHub/hunter/cmake/modules/hunter_config.cmake:81 (set):
  Variable "HUNTER_intsizeof_VERSION" was accessed using MODIFIED_ACCESS with
  value "2.0.1".
Call Stack (most recent call first):
  C:/Users/Dvir/Documents/GitHub/hunter/cmake/configs/default.cmake(69): (hunter_config)
  C:/Users/Dvir/Documents/GitHub/hunter/cmake/modules/hunter_calculate_config_sha1.cmake(37): (include)
  C:/Users/Dvir/Documents/GitHub/hunter/cmake/modules/hunter_apply_gate_settings.cmake(133): (hunter_calculate_config_sha1)
  C:/Users/Dvir/Documents/GitHub/hunter/cmake/modules/hunter_finalize.cmake(73): (hunter_apply_gate_settings)
  C:/Users/Dvir/Documents/GitHub/hunter/cmake/modules/hunter_add_package.cmake(24): (hunter_finalize)
  CMakeLists.txt(14): (hunter_add_package)


-- [hunter] HUNTER_ROOT: C:/Users/Dvir/Documents/GitHub/hunter
-- [hunter] [ Hunter-ID: xxxxxxx | Toolchain-ID: c4105cf | Config-ID: a70d36d ]
CMake Debug Log at C:/Users/Dvir/Documents/GitHub/hunter/cmake/modules/hunter_add_version.cmake:40 (string):
  Variable "HUNTER_intsizeof_VERSION" was accessed using UNKNOWN_READ_ACCESS
  with value "".
Call Stack (most recent call first):
  C:/Users/Dvir/Documents/GitHub/hunter/cmake/projects/IntSizeof/hunter.cmake(11): (hunter_add_version)
  C:/Users/Dvir/Documents/GitHub/hunter/cmake/modules/hunter_add_package.cmake(53): (include)
  CMakeLists.txt(14): (hunter_add_package)
```

See also [With HUNTER_STATUS_DEBUG=ON](https://gist.github.com/dvirtz/6a85e176bd7accb88542777a25a83029).

I'm using Ninja generator with VS 2017.
Other packages build successfully.
Any idea?

**Comment by dvirtz** [comment]
If I set `HUNTER_intsizeof_VERSION` manually before calling `hunter_add_package` it builds successfully.

**Comment by ruslo** [comment]
> -- [hunter] [ Hunter-ID: xxxxxxx

You're using Git version. I guess you need to update Hunter.

**Comment by dvirtz** [comment]
I'm on head:
```git
git log
commit 933e0986b6da42f72b3f591310cda0b588bc2608
Author: dvirtz <dvirtz@gmail.com>
Date:   Mon Nov 13 22:34:09 2017 +0200

    add mongoose (#1195)
```

**Comment by ruslo** [comment]
I've pushed latest changes to testing branch. Ninja + Visual Studio 2013:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2800/job/lvgln3x8s0b297kr

**Comment by dvirtz** [comment]
I tried on another machine and it works.
Thanks.

**Comment by dvirtz** [comment]
Just for reference, the problem was that the projects/intsizeof folder was named IntSizeof (notice the case change) for some reason.

**Comment by ruslo** [comment]
Oh, I see. Yes it was renamed: https://github.com/ruslo/hunter/commit/b35f39d59d6386e3c735e79836847008066d5331

Was thinking that nobody using it, sorry :) Lower case is recommended because everything looks consistent:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#add-package-to-hunter

**Comment by dvirtz** [comment]
I didn't use it directly but it's a dependency of curl.

**Comment by ruslo** [comment]
How you hit it in this case? CURL is using correct call:
* https://github.com/hunter-packages/curl/blob/4dec0455e57b80f2cf827b89a8ec17ae37190d66/CMakeLists.txt#L493-L495

**Comment by dvirtz** [comment]
As I was using my local fork it took the package from the wrongly named
folder.
