### ISSUE TITLE
OpenSSL + "-m32"

### ISSUE THREAD

**Issue by harsszegi** [ruslo/hunter#1205]
We have a CMAKE_TOOLCHAIN_FILE setting, which sets:

set(CMAKE_C_FLAGS "-m32" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS "-m32" CACHE STRING "" FORCE)
set(CMAKE_LINK_FLAGS "-m32" CACHE STRING "" FORCE)

We are compiling on 64-bit though.
it appears OpenSSL disregards the toolchain settings and gets compiled with native 64 bit (so after all we can't link against the library).

**Comment by ruslo** [comment]
I've tried to run with [gcc-32bit](https://github.com/ruslo/polly/blob/master/gcc-32bit.cmake) toolchain and I see `-m32` passed to OpenSSL build. Build itself failed however. Flags added to OpenSSL build here:
* https://github.com/ruslo/hunter/blob/d06b5030f44ab8c16eee1773cbc5f28d41b1fc3c/cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in#L112-L113

**Comment by harsszegi** [comment]
Awesome :) That was quick, thanks a lot!!!
