### ISSUE TITLE
Asio support? 

### ISSUE THREAD

**Issue by NukeBird** [ruslo/hunter#1210]
I want hunterize rpclib https://github.com/ruslo/hunter/issues/1209
rpclib's dependencies:
-gtest
-gmock
-asio

gtest and gmock already supported by bunter. But what about asio? Is it part of boost package? [Boost's package](https://docs.hunter.sh/en/latest/packages/pkg/Boost.html?highlight=boost) don't have any mention about asio

**Comment by ruslo** [comment]
> don't have any mention about asio

This page is not for detailed description of Boost, only build part. Since ASIO is header only package it should be enough to use `Boost::boost`.

**Comment by NukeBird** [comment]
@ruslo something like Boost::asio will work too?

**Comment by ruslo** [comment]
> something like Boost::asio will work too?

No. It makes no sense to introduce such target because it's header only. Any header-only component can be added by `Boost::boost`.

**Comment by NukeBird** [comment]
Okay, thank you!
