### ISSUE TITLE
Submodule "Version"

### ISSUE THREAD

**Issue by geokon-gh** [ruslo/hunter#1221]
To get familiar with Hunter I'm trying to convert a small template project of mine from using `add_subdirectory` w/ submodules to Hunter. I'm following your helpful guide: https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html

I have OpenCV as a submodule and I'm having some strange output concerning the version. Hunter seems to look for some (commit?) hash which in my case corresponds to tag `3.0.0` and matches it to something that looks like a git tag. However when I look at the OpenCV repo there is for instance only a `3.0.0` tag but no tags with the `-p[x]` suffix - so I'm unsure of what they represent.

```
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.2.0-p1' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.2.0-p0' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.1.0-p3' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.1.0-p2' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.1.0-p1' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.1.0-p0' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p11' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p10' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p9' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p8' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p7' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p6' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p5' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p4' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p3' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p2' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p1' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-p0' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-rc1-p0' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-beta-p2' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '3.0.0-beta' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '2.4.11-p1' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '2.4.11' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Skip '2.4.10' (looking for '72de87ac7f7c8589e034f466255b86e9d7470373')
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] OpenCV versions available: [72de87ac7f7c8589e034f466255b86e9d7470373;3.2.0-p1;3.2.0-p0;3.1.0-p3;3.1.0-p2;3.1.0-p1;3.1.0-p0;3.0.0-p11;3.0.0-p10;3.0.0-p9;3.0.0-p8;3.0.0-p7;3.0.0-p6;3.0.0-p5;3.0.0-p4;3.0.0-p3;3.0.0-p2;3.0.0-p1;3.0.0-p0;3.0.0-rc1-p0;3.0.0-beta-p2;3.0.0-beta;2.4.11-p1;2.4.11;2.4.10]
-- [hunter *** DEBUG *** 2017-11-22T17:08:20] Install to: /home/gk/.hunter/_Base/3b39eff/78a961f/c65f1fb/Install
```

Is this an non-issue?

**Comment by headupinclouds** [comment]
Can you share a pointer to the project or some minimal test case?  It will be harder for people to help with this without a working example to illustrate the problem.

As mentioned in the docs you need to setup your project with a `LOCAL` configuration override.

```
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.18.58.tar.gz"
    SHA1 "3b39effc5ee1af4ef7487eabb1b0a7a7e10a7b3e"
    LOCAL # <----- load cmake/Hunter/config.cmake
)
```

If you add OpenCV as a submodule, you will have to use a *hunterized* branch from the hunter-packages/OpenCV fork .  The upstreams versions won't work as is, since there are a number of dependencies in OpenCV that must be managed by Hunter.

```
mkdir -p src/3rdparty && cd src/3rdparty && git submodule add https://github.com/hunter-packages/OpenCV
```

You would then specify the path to that submodule in your local `cmake/Hunter/config.cmake` configuration file with a single entry

```
hunter_config(OpenCV GIT_SUBMODULE "src/3rdParty/OpenCV")
```

**Comment by ruslo** [comment]
> Is this an non-issue?

I don't see any errors. By the way this message was removed few month ago: https://github.com/ruslo/hunter/commit/a6ce80023b5adb8c3e4ae050b0fbec3fce856b51

**Comment by geokon-gh** [comment]
@ruslo 

Thanks! Looks like I was using an older version. I figured out how to update it and the notification is no longer there.

@headupinclouds 
Hey could you say more about the "hunterizing". Why can't OpenCV manage it's own dependencies? I don't really mind redundant libraries.

I have additional libraries I will want to use (ex: Cinder and LeapSerial) that also have their own dependencies like zlib and stuff... I wouldn't mind if they all have their own version of zlib. I would hope I don't have to maintain "hunterized" forks for all of them. A client I'm helping for has about 10 different dependencies and it'd be pretty messy to manage all of that.

Basically I'm not looking for anything fancy. The `submodule`\`add_subdirectory` method worked for me for the most part. It was like 90% of there...  there were just 2 issues:

*1*
The lack of namespacing in CMake made it so that I have target name collisions between dependent projects (esp. things like `uninstall`)

*2*
One of my dependent projects (LeapSerial) queried the project name/version which would be messed up/lost when used as a subdirectory (it'd only see the parent project name/version).

So I was hoping Hunter would mitigate these issues by configuring/building each dependent target in its own namespace and in effect "exporting" the targets to parent projects.

Reading the documentation it seems that that's sort of what going on.. but there is more work involved?
Thanks for the great software guys. Really appreciate the work! Hope it works for me :)

**Comment by ruslo** [comment]
> could you say more about the "hunterizing"

Docs:
* https://docs.hunter.sh/en/latest/reference/terminology/hunterize.html
* https://docs.hunter.sh/en/latest/creating-new/create/cmake-dependencies.html

> I wouldn't mind if they all have their own version of zlib

Even if you don't, ODR would mind.

> there is more work involved?

Creating/updating package instructions:
* https://docs.hunter.sh/en/latest/creating-new.html

In short:
* If package has no dependencies and generate `*Config.cmake` then it can be used as is (https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#install-xxxconfig-cmake)
* If package has dependencies then all dependencies should be added to Hunter, then package should be "hunterized" (https://docs.hunter.sh/en/latest/creating-new/create/cmake-dependencies.html)
* If packages doesn't use CMake as a build system then custom build scheme should be used. This is the worst scenario since mimicing all features that CMake has is a nontrivial effort in practice

**Comment by geokon-gh** [comment]
Thanks for the links. I'll need to see if this is an acceptable amount of work for my client or if we'll just stick to manual dependency management. How come ODR isn't an issue when I build the libraries by hand and link through find_package? I feel like half my dependencies end up building a copy of zlib and yet nothing seems to blow up

Thanks again for all your help

**Comment by ruslo** [comment]
> I feel like half my dependencies end up building a copy of zlib and yet nothing seems to blow up

It's called "undefined behavior", there is no guarantee that any error will be reported. In your particular case I guess the reason is that zlib API is pretty stable, linker just use symbols from the first zlib it see.

**Comment by geokon-gh** [comment]
I see, well I guess if I had it working through build scripts before, then I should be able to get it working with Hunter without having to make change. Thanks for explaining the issue

**Comment by gkontsevich** [comment]
Thanks again for pointing out ODR to me. I see that some libraries really seem to ignore this issue!

@ruslo 
Going on with the `zlib` example. Say my project uses `zlib` and have a configuration that reads something like `hunter_config(ZLIB VERSION 1.2.8-p3 CMAKE_ARGS ZLIB_BUILD_SHARED=OFF)` in `cmake/Hunter/config.cmake`. And now another dependency (like OpenCV) has it's own zlib with it's own flags/version/configuration. Will Hunter handle the linking so there are 2 zlibs and no ODR issues?

in this page you have a diagram that seems to suggest the more "local" version will simply be ignored
https://docs.hunter.sh/en/latest/creating-new/create/cmake-dependencies.html
(I know that the diagram is for when one project isn't hunterized.. but suppose both are hunterized)

**Comment by ruslo** [comment]
> And now another dependency (like OpenCV) has it's own zlib with it's own flags/version/configuration.

Depends on what you mean by "it's own zlib". If it's own bundled copy then it should be "hunterized" to use Hunter's zlib. OpenCV is already hunterized: https://github.com/hunter-packages/opencv/blob/b6462b93e2f466d66c232786b74bdb40020b25f8/cmake/OpenCVFindLibsGrfmt.cmake#L9 hence both OpenCV and your project will use version that you define in `hunter_config`.

**Comment by geokon-gh** [comment]
(sorry, last answer was posted from my work account!)

When you say "Hunter's ZLIB", can't that be configured to any version of ZLIB that hunter has archived through `hunter_config(ZLIB VERSION [#version_number])`? So unless I'm misunderstanding, two hunterized packages can point to two different versions of ZLIB (each one with a slightly different `hunter_config` internally)

I'm trying to hunterize a library ([LeapSerial](https://github.com/leapmotion/leapserial)) where they've just dropped in some old version of zlib into their repository - so I'm not sure it'll match the version number OpenCV uses nor the version I've been using in the parent project (when I've been building manually with scripts). I'm not clear on how Hunter will handle this setup

Thank you for your help

**Comment by ruslo** [comment]
> can't that be configured to any version of ZLIB that hunter has archived through hunter_config(ZLIB VERSION [#version_number])?

Yes it can.

> two hunterized packages can point to two different versions of ZLIB

Not simultaneously. Again, version choosed only once and forms Config-ID. Local project and all external packages will use same ZLIB version. When you change ZLIB version locally Config-ID regenerated and everything will point to different root directory. External packages inherit version, local `config.cmake` of external package will be ignored since at the moment of external package build Config-ID is ready.

> I'm not clear on how Hunter will handle this setup

Whatever you decide Hunter will handle everything correctly :) If your package is not compatible with default ZLIB version from Hunter then you have to set custom ZLIB version locally. You have to do it for every project that will use `LeapSerial`.

**Comment by geokon-gh** [comment]
Gotcha! Thanks for helping out. That answered my question. Basically the version declared highest up the dependency chain will override everything below it. So if you point to an incompatible version higher up (say in your root project) and a dependency expect some other version, then things may break. That's a reasonable behavior I think. I'll make sure to look out for that then :)

Handling multiple versions would be more handy.. but I don't even know if there are tools for that. You'd have to re-lable everything in the 2 object files for the 2 zlibs to have separate unique names

**Comment by ruslo** [comment]
> Basically the version declared highest up the dependency chain will override everything below it

Yes, but to clarify this chain is not very long - it's just local and external. Local processed only once and all externals inherit everything.

> You'd have to re-lable everything in the 2 object files for the 2 zlibs to have separate unique names

It's tricky and also not very effective. If you will have 2 libraries it will mean that code is doubled in size.

**Comment by geokon-gh** [comment]
I see, so all additional dependencies of externals need to be specific by the root/local. So if OpenCV uses ZLIB, but I don't use it myself directly, I still need to declare it. That's good. Everything is explicit. :relaxed:

As for relabeling, maybe it'd make the code size double for that library, but at least you wouldnt have to patch dependencies :) (but I get why you'd rather not due things that way)

**Comment by ruslo** [comment]
> if OpenCV uses ZLIB, but I don't use it myself directly, I still need to declare it

What? Why? No, I haven't said that. If you don't specify version of dependency Hunter will pick default one. Which is fine in most cases and you should stick to defaults as close as possible in general. This of course introduce some limitations which can be covered by adding more global configs, see https://github.com/ruslo/hunter/issues/1106.
