### ISSUE TITLE
Can't find_package() system GStreamer

### ISSUE THREAD

**Issue by geokon-gh** [ruslo/hunter#1230]
I'm trying an extremely simple setup with just loading one single external library.
I'm mirroring pretty much 1-1 the example provided in the documentation for a dependency in a git-submodule

https://github.com/geokon-gh/cinder-template/tree/hunter-version

The library/dependency in question is Cinder. It in turn depends on GStreamer (and Boost and GLIB). When I manually configure it through cmake (to build separately - not part of larger project) it finds my system's gstreamer without any issues. However when I have Hunter do the configuration it doesn't find GStreamer and crashes during compilation. Since I don't have any other libraries or any other potential GStreamer versions I'd rather just use Cinder as-is and not have to make a hunterized fork

Could Hunter somehow be blocking the Cinder from finding GStreamer? (It's finding GLib and Boost just fine). From my understanding this should go through without a problem - but maybe I'm misunderstanding something

Here is the code where Cinder does the find_package() for GStreamer - there doesn't seem to be anything special going on here.
https://github.com/cinder/Cinder/blob/ff4781385028d40510d89ca2e4e824b51bb3fb7a/proj/cmake/platform_linux.cmake

**Comment by isaachier** [comment]
The usual issue I have experienced is that Hunter packages often rely on a package with a config, whereas other packages will just try to find the library without a config. The code would be `find_package(GStreamer CONFIG REQUIRED)` vs `find_package(GStreamer REQUIRED)`. If you own the package in question, use the `HUNTER_ENABLED` variable to determine which way to find the GStreamer package.

**Comment by isaachier** [comment]
After looking at your project more carefully, I think the main issue is that Cinder is not a Hunter project and you must port that first along with its dependencies in order for Hunter to work.

**Comment by ruslo** [comment]
> it finds my system's gstreamer without any issues

Hunter is not designed to interact with packages installed in system:
* https://docs.hunter.sh/en/latest/faq/interaction-with-other-package-managers.html

System package can be used as a workaround in rare cases for the missing packages, but GStreamer is already in Hunter:
* https://docs.hunter.sh/en/latest/packages/pkg/gstreamer.html

**Comment by ruslo** [comment]
Closing inactive discussion.
