### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by kastus777** [ruslo/hunter#1247]
Afternoon,
Ive got the issue.
Can you please have a look
Thanks

kostya@E470:~/ethminer/build$ sudo cmake --build .
[sudo] password for kostya: 
[  0%] Built target BuildInfo.h
[ 23%] Built target devcore
[ 33%] Built target ethash
[ 46%] Built target hwmon
[ 50%] Building CXX object libethcore/CMakeFiles/ethcore.dir/Miner.cpp.o
In file included from /home/kostya/ethminer/libethcore/Miner.cpp:1:0:
/home/kostya/ethminer/libethcore/Miner.h: In constructor ‘dev::eth::Miner::Miner(const string&, dev::eth::FarmFace&, size_t)’:
/home/kostya/ethminer/libethcore/Miner.h:169:18: error: ‘to_string’ is not a member of ‘std’
   Worker(_name + std::to_string(_index)),
                  ^
/home/kostya/ethminer/libethcore/Miner.h:169:18: note: suggested alternatives:
In file included from /home/kostya/.hunter/_Base/aafb99b/a5f7296/a63b4ed/Install/include/boost/exception_ptr.hpp:9:0,
                 from /home/kostya/.hunter/_Base/aafb99b/a5f7296/a63b4ed/Install/include/boost/exception/all.hpp:25,
                 from /home/kostya/ethminer/libethcore/../libdevcore/Exceptions.h:26,
                 from /home/kostya/ethminer/libethcore/../libdevcore/RLP.h:33,
                 from /home/kostya/ethminer/libethcore/BlockHeader.h:25,
                 from /home/kostya/ethminer/libethcore/EthashAux.h:28,
                 from /home/kostya/ethminer/libethcore/Miner.h:32,
                 from /home/kostya/ethminer/libethcore/Miner.cpp:1:
/home/kostya/.hunter/_Base/aafb99b/a5f7296/a63b4ed/Install/include/boost/exception/detail/exception_ptr.hpp:493:5: note:   ‘boost::to_string’
     to_string( exception_ptr const & p )
     ^
In file included from /home/kostya/.hunter/_Base/aafb99b/a5f7296/a63b4ed/Install/include/boost/exception/to_string_stub.hpp:9:0,
                 from /home/kostya/.hunter/_Base/aafb99b/a5f7296/a63b4ed/Install/include/boost/exception/info.hpp:11,
                 from /home/kostya/.hunter/_Base/aafb99b/a5f7296/a63b4ed/Install/include/boost/exception/diagnostic_information.hpp:11,
                 from /home/kostya/.hunter/_Base/aafb99b/a5f7296/a63b4ed/Install/include/boost/exception/all.hpp:10,
                 from /home/kostya/ethminer/libethcore/../libdevcore/Exceptions.h:26,
                 from /home/kostya/ethminer/libethcore/../libdevcore/RLP.h:33,
                 from /home/kostya/ethminer/libethcore/BlockHeader.h:25,
                 from /home/kostya/ethminer/libethcore/EthashAux.h:28,
                 from /home/kostya/ethminer/libethcore/Miner.h:32,
                 from /home/kostya/ethminer/libethcore/Miner.cpp:1:
/home/kostya/.hunter/_Base/aafb99b/a5f7296/a63b4ed/Install/include/boost/exception/to_string.hpp:73:5: note:   ‘boost::to_string’
     to_string( std::pair<T,U> const & x )
     ^
libethcore/CMakeFiles/ethcore.dir/build.make:110: recipe for target 'libethcore/CMakeFiles/ethcore.dir/Miner.cpp.o' failed
make[2]: *** [libethcore/CMakeFiles/ethcore.dir/Miner.cpp.o] Error 1
CMakeFiles/Makefile2:486: recipe for target 'libethcore/CMakeFiles/ethcore.dir/all' failed
make[1]: *** [libethcore/CMakeFiles/ethcore.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ruslo** [comment]
> /home/kostya/ethminer/libethcore/Miner.h:169:18: error: ‘to_string’ is not a member of ‘std’

What exactly makes you think it's a Hunter issue?

**Comment by kastus777** [comment]
не увидел, my bad(((
sorry)
thanks

**Comment by xsacha** [comment]
1. Probably don't run cmake --build as sudo.
2. Use a toolchain that sets c++11.
3. Can we close this?

**Comment by ruslo** [comment]
> Probably don't run cmake --build as sudo.

Probably it's not a very good idea to run build with sudo but it's really up to user.

> Use a toolchain that sets c++11.

It may not help if `std::to_string` is not implemented in version of standard library.

> Can we close this?

I'm pretty sure Hunter can't do anything here, so yes, closing.
