### ISSUE TITLE
Missing TLS_VERIFY?

### ISSUE THREAD

**Issue by lamefun** [ruslo/hunter#1256]
I see that HTTPS URLs are used everywhere, but `TLS_VERIFY` seems to not be set to `ON` (it's `OFF` by default according to the CMake documentation).

**Comment by ruslo** [comment]
> TLS_VERIFY seems to not be set to ON (it's OFF but default

What a bad default choice. Let me take a look...

**Comment by ruslo** [comment]
Need `TLS_VERIFY` in HunterGate too: https://github.com/hunter-packages/gate/commit/6711a3fac93d9035cf8a31560dfa992d375eaa77

`ExternalProject_Add` and `file(DOWNLOAD ...)` updated: https://github.com/ruslo/hunter/commit/bb6d75efc2e61a38e9da507cc30f1e3cdbfba568

Released: https://github.com/ruslo/hunter/releases/tag/v0.19.197

Also if TLS check will fail ExternalProject_Add will keep spinning retrying download thinking that it's a fixable error.

Nice catch, thanks!
