### ISSUE TITLE
add boost::hana

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#1268]
Please create a hunter-packages/hana fork from https://github.com/boostorg/hana

> Your standard library for metaprogramming http://boostorg.github.io/hana

**Comment by ruslo** [comment]
Hana is a part of Boost package. Meaning if you want to patch it we should use this repo:
* https://github.com/hunter-packages/boost

I need to update code to newer version. Can do it after this merge:
* https://github.com/ruslo/hunter/pull/1265
