### ISSUE TITLE
CppNetlib build

### ISSUE THREAD

**Issue by rolandsz** [ruslo/hunter#1278]
I'm trying to use the [CppNetlib](https://github.com/ruslo/hunter/blob/master/cmake/projects/CppNetlib/hunter.cmake) library in my project and the build fails while generating the OpenSSL documentation. It is a known issue and is already fixed in newer versions of Hunter (https://github.com/ruslo/hunter/blob/master/cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in#L170) but the CppNetlib uses an older package I guess.

Could you please update CppNetlib's Hunter to a newer version?

CMake: cmake version 3.9.1
OS: Ubuntu 17.10
Error log:

> [...]
making all in apps...
making all in test...
making all in tools...
installing man1/CA.pl.1
installing man1/asn1parse.1
installing man1/ca.1
installing man1/ciphers.1
installing man1/cms.1
cms.pod around line 457: Expected text after =item, not a number
cms.pod around line 461: Expected text after =item, not a number
cms.pod around line 465: Expected text after =item, not a number
cms.pod around line 470: Expected text after =item, not a number
cms.pod around line 474: Expected text after =item, not a number
POD document had syntax errors at /usr/bin/pod2man line 71.
Makefile:640: recipe for target 'install_docs' failed
[...]

**Comment by ruslo** [comment]
I've created branch `hunter-0.12.0` basing on latest release:
* https://github.com/hunter-packages/cpp-netlib/tree/hunter-0.12.0

Please send pull request to `hunter-0.12.0` with hunterization commits from branch `hunter-0.10.1`:
* https://github.com/hunter-packages/cpp-netlib/commits/hunter-0.10.1

**Comment by rolandsz** [comment]
There have been many dependency related changes in the project between 0.10.1 and 0.12.0. It is not that trivial to apply hunter-0.10.1 commits.

For example we'll need a hunterized version of the non-boost [asio](https://github.com/chriskohlhoff/asio) header-only library.

As for now I'm using [Beast](https://docs.hunter.sh/en/latest/packages/pkg/Beast.html) in my project instead of cpp-netlib.

**Comment by ruslo** [comment]
> As for now I'm using Beast in my project instead of cpp-netlib.

Beast is a part of Boost now and available in Boost 1.66.

**Comment by ruslo** [comment]
Closing inactive discussion.
