### ISSUE TITLE
Questions about hunter with and compared to other tools

### ISSUE THREAD

**Issue by ahundt** [ruslo/hunter#128]
Cool, I came across hunter and I'm interested in it but I'm not sure if it will work well with another tool I use [cmake-basis](https://github.com/schuhschuh/cmake-basis), which I've contributed to.

Is python necessary to use hunter? I strongly prefer pure CMake build tools. The use of python also concerns me as a dependency since [catkin](https://github.com/ros/catkin) has some similarities but many issues, and it can break the build up into pieces losing some of the integration that comes with CMake. I'm not familiar with your implementation however so you may have good reasons these issues don't come up.

Some people also like to use tools such as ones that allow grid compilation. Is that still possible with hunter or does the us of ExternalProject_Add get in the way?

**Comment by alamaison** [comment]
Hunter is a slot-in solution that automatically fetches and compiles your project's dependencies during your project build process.  It allows you to use whatever combination of platform/ide/toolchain you want, without having to worry whether your dependecies will be ok with that.  Hunter makes them ok with that.

Just download one module, a little boilerplate specifiying which Hunter version you want, and insert one `hunter_add_package` call to match every `find_package` call in your project.  That's it.  Those pacakges you use via `find_package` will be compiled ready for CMake to find when configuring your project.

> Is python necessary to use hunter?

No.  AFAIK, the only package that depends on anything like that is OpenSSL which required Perl to be there.

**Comment by aadityakalsi** [comment]
Building on OSX requires Python 3 from what I remeber.. at least for Boost

**Comment by ruslo** [comment]
> Cool, I came across hunter and I'm interested in it but I'm not sure if it will work well with another tool I use

Let me know if you have any problems. I see no reason why Hunter can conflicts with other CMake modules. Hunter set some `*_ROOT` CMake/environment variables + `CMAKE_PREFIX_PATH` to find packages in custom location. Hunter modify `CMAKE_MODULE_PATH` so you can use `hunter_add_package` module + Hunter set some internal variables that all starts with `HUNTER_*`.

> Is python necessary to use hunter?

No. README explicitly states:
```
no need for Git or Python or anything
```

but some packages require external tools for building

> OpenSSL which required Perl to be there

exactly

> Building on OSX requires Python 3 from what I remeber.. at least for Boost

You mean [this script](https://github.com/ruslo/hunter/blob/master/scripts/fix-boost-dylib-id.py)? It's just for OS X. Well I think I can handle it with CMake easily. I've opened https://github.com/ruslo/hunter/issues/130

> Some people also like to use tools such as ones that allow grid compilation

I think Alex answer this question, let me know if you need more info.

**Comment by ruslo** [comment]
Hope answers help you. Closing.

**Comment by ahundt** [comment]
@ruslo thanks!
