### ISSUE TITLE
add dmlc/rabit

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#1284]
Please create a hunter-packages/rabit fork

original : https://github.com/dmlc/rabit
cmake fork : https://github.com/headupinclouds/rabit 

* added pure CMake in headupinclouds fork (no HunterGate needed)
* required for full/distributed xgboost build
* changes to be submitted upstream after xgboost update

**Comment by ruslo** [comment]
Done: https://github.com/hunter-packages/rabit

**Comment by headupinclouds** [comment]
#1291
