### ISSUE TITLE
GIT_SUBMODULE doesn't take into account recursive submodules

### ISSUE THREAD

**Issue by malirod** [ruslo/hunter#1286]
Recent log4cplus uses submodules (catch, threadpool).
Usage of GIT_SUBMODULE doesn't produce complete archive suitable for further build.

**Comment by ruslo** [comment]
> Usage of GIT_SUBMODULE doesn't produce complete archive suitable for further build.

You will have same problems with archives produced by GitHub. 3rd parties should be [hunterized](https://docs.hunter.sh/en/latest/creating-new/create/cmake-dependencies.html), this will resolve all issues.

**Comment by malirod** [comment]
1. for submodules I can suggest usage of the following script [git-archive-all](https://github.com/Kentzo/git-archive-all) instead of just using `git archive ...` in the submodule root.

2. GitHub indeed produces archives without submodules. But that's the point to use own local submodule. Locally I get all required modules and don't rely on GitHub implementation.
In general 3rd party project manteinter might create full release pack and attach to GitHub release or in some other source. E.g. Log4plus stores full release archives on sourceforge. 

3. Hanterization of 3rd parties this is what I'm trying to avoid if possible. In provided link I see third party with dependencies (which might be installed system-wide) and I can understand why Hanterization is required. But from my perspective, sub-modules are internals of the project and hunterization might not be required.

**Comment by ruslo** [comment]
> for submodules I can suggest usage of the following script git-archive-all instead of just using git archive ... in the submodule root

How it will work with circular dependencies?

> Hanterization of 3rd parties this is what I'm trying to avoid if possible

Hunterization is an essential part of Hunter infrastructure. The only way known to me to avoid it is not to use Hunter :)

> sub-modules are internals of the project and hunterization might not be required

You're mentioning log4plus and submodules are not internal to it. Internal submodules which is not designed to be visible outside might be interesting case though. Packages [OpenCV-extra](https://github.com/ruslo/hunter/blob/master/cmake/projects/OpenCV-Extra/hunter.cmake) and [ClangToolsExtra](https://github.com/ruslo/hunter/blob/master/cmake/projects/ClangToolsExtra/hunter.cmake) come to mind.

**Comment by ruslo** [comment]
Closing inactive discussion.
