### ISSUE TITLE
how to handle unversioned packages?

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#1289]
Should there be a convention for creating releases from packages with no upstream versioning?  I've used YYY.MM.DD as a kind of overloaded semantic versioning scheme which still plays well with regular expressions that expect that.

**Comment by ruslo** [comment]
> a convention for creating releases from packages with no upstream versioning?

What about `v0.0.0-pN` template?

**Comment by headupinclouds** [comment]
That works for me.  In the case of the dmlc/nccl fork, maybe something like: `v0.0.0-dmlc0` to distinguish it from other forks?  (Tensorflow also has a a bundled nccl.)

**Comment by ruslo** [comment]
> v0.0.0-dmlc0 to distinguish it from other forks?

Yes, sounds good.
