### ISSUE TITLE
ccv link error on Linux

### ISSUE THREAD

**Issue by alamaison** [ruslo/hunter#129]
@headupinclouds Can't file an issue on your Hunterised fork of ccv, so filing here.

ccv in Hunter won't like on Linux:
```
/home/ubuntu/workspace/hunter/PROJECT/ccv/TOOLCHAIN/default/_testing/Hunter/_Base/d686e4c/326318e/6e3ae24/Install/lib/libccvd.a(ccv_algebra.c.o): In function `ccv_normalize':
/home/ubuntu/workspace/hunter/PROJECT/ccv/TOOLCHAIN/default/_testing/Hunter/_Base/d686e4c/326318e/6e3ae24/Build/ccv/Source/lib/ccv_algebra.c:72: undefined reference to `sqrt'
```
The reason is that Linux keeps its maths functions in libm.

Here is an example of [how I fixed it for libtiff](https://github.com/alamaison/tiff/commit/2da0d05dc6c0459cf95bbb75d4b4eacf53202600), which needs libm for `pow`.  I've not used Sugar, which you're using for ccv, so I'm not confident to apply the fix to ccv myself.

**Comment by headupinclouds** [comment]
I've applied your fix to my local fork, but am unable to test in my Linux VM right now (some kind of libcurl openssl/https problem during hunter package downloads). 
```
https://github.com/headupinclouds/ccv/commit/c25b2fd1615f5c3477a60f9120a966d1c47efcdd
```
If you can confirm this fix works, I'll push the changes up and update the package.

**Comment by ruslo** [comment]
> some kind of libcurl openssl/https problem during hunter package downloads

What is the error message about?

**Comment by headupinclouds** [comment]
Thanks @alamaison.  I just submitted a pull request for your ccv libm fixes (v0.7-p5).

**Comment by headupinclouds** [comment]
> What is the error message about?

I don't think this has anything to do with hunter.  From a quick search, my guess is that CMake is using a libcurl without openssl (directly or indirectly) for the ExternalProject_Add command.  This is the error I get:

```
cmake version 3.2.2
```
```
> cmake -H. -B_builds
-- [hunter] Initializing Hunter workspace (7103f0ab481523ca93a06c1c55abcd56741d3a97)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.8.13.tar.gz
-- [hunter]   -> /home/dhirvonen/.hunter/_Base/Download/Hunter/0.8.13/7103f0a
CMake Error at Build/Hunter-prefix/src/Hunter-stamp/download-Hunter.cmake:27 (message):
  error: downloading 'https://github.com/ruslo/hunter/archive/v0.8.13.tar.gz'
  failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1

make[2]: *** [Hunter-prefix/src/Hunter-stamp/Hunter-download] Error 1
make[1]: *** [CMakeFiles/Hunter.dir/all] Error 2
make: *** [all] Error 2

[hunter ** INTERNAL **] Build project failed
[hunter ** INTERNAL **] [Directory:/home/dhirvonen/devel/work/ccv]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at cmake/HunterGate.cmake:76 (message):
Call Stack (most recent call first):
  cmake/HunterGate.cmake:86 (hunter_gate_wiki)
  cmake/HunterGate.cmake:312 (hunter_gate_internal_error)
  cmake/HunterGate.cmake:450 (hunter_gate_download)
  CMakeLists.txt:6 (HunterGate)
```

My CMake version is 3.2.2 (compiled from source).

**Comment by ruslo** [comment]
> My CMake version is 3.2.2 (compiled from source)

You need to add `CMAKE_USE_SYSTEM_CURL=YES`. I'm not sure, but I think curl version of cmake is kind of broken or limited.

See https://github.com/ruslo/polly/wiki/Jenkins#other:

```
build.py --install --toolchain default --config Release --verbose --fwd "CMAKE_USE_SYSTEM_CURL=YES"
```

**Comment by ruslo** [comment]
Fixed in branch `develop` or in release: https://github.com/ruslo/hunter/releases/tag/v0.10.1

@headupinclouds Thanks, David!
