### ISSUE TITLE
CURL version update.. maybe?

### ISSUE THREAD

**Issue by geokon-gh** [ruslo/hunter#1307]
The Hunterized CURL package has a 7.51.0-v1 branch listed
https://github.com/hunter-packages/curl/

However it's not one of the available versions in Hunter
https://github.com/ruslo/hunter/blob/master/cmake/projects/CURL/hunter.cmake

Is this just an omission? Or is there a reason for it (maybe WIP)?

Unfortunately the older version doesn't seem to do static builds (see line 1126 `message(WARNING "Static linking is broken!")` ) and I need to bundle my build and statically link everything with "-fPIC", so I don't seem to have a work-around. 

I'm also a bit unclear on if OpenSSL builds with -fPIC or not and how to ensure it's enabled (from previous closed issues.. it seems like it's enabled by default)

Thanks guys

**Comment by ruslo** [comment]
> Is this just an omission? Or is there a reason for it (maybe WIP)?

I don't know. @xsacha Did you made this release: https://github.com/hunter-packages/curl/releases/tag/hunter-7.51.0-v1 ? Anyway, I have pushed branch https://github.com/hunter-packages/curl/tree/hunter-7.57.0 basing on upstream tag 7.57.0. Pull request with hunterization patches from branch https://github.com/hunter-packages/curl/commits/hunter are welcome.

> Unfortunately the older version doesn't seem to do static builds

It's just a warning, static library should works fine.

> I need to bundle my build and statically link everything with "-fPIC"

Define PIC in toolchain, example:
* https://github.com/ruslo/polly/blob/9b305b84c81d391665ba55c9a903a5b2a191fe21/gcc-pic.cmake#L21

**Comment by xsacha** [comment]
I think I never added 7.51 to Hunter for some reason. Something had broken in that update? Not sure. That was a while ago.

**Comment by geokon-gh** [comment]
Hey thanks @ruslo !
The toolchain files worked great and solved all my problems.
I really appreciate the help :)

**Comment by geokon-gh** [comment]
Sorry to reopen this.. but `-fPIC` doesn't seem to propagate to OpenSSL properly (I had it working last week, but for some reason after a clean build I'm having issues again)

In my config.cmake I have 
hunter_config(OpenSSL VERSION 1.0.2m)

I'm feeding in the `gcc-pic.cmake` toolchain from polly like you suggest and when it's built by hunter everything also looks good. I can see fPIC in the CFLAG list and I can see it go to all the objects that then get pulled into libcrypto.a

looking at[ /flags/fpic.cmake 
](https://github.com/ruslo/polly/blob/9b305b84c81d391665ba55c9a903a5b2a191fe21/flags/fpic.cmake) it seems to be doing the right things as well - adding fPIC to CMAKE_C_FLAGS and CMAKE_CXX_FLAG

However when I build my parent project the build fails with:
```
/usr/bin/ld: /home/gk/.hunter/_Base/244a137/d6a31ec/fc8d977/Install/lib/libcrypto.a(bn_gf2m.o): relocation R_X86_64_32 against '.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
```

Have you seen anything like this before?

I also tried to go and rebuild everything without fPIC using gcc-static.cmake, but I get the same error

**Comment by ruslo** [comment]
@geokon-gh Can you show the logs of building OpenSSL? Can you see `-fPIC` there?

**Comment by geokon-gh** [comment]
Well this is embarrassing... I ran out of disk space, so I deleted the build directory and the `~/.hunter ` cache and rebuilt everything from scratch overnight. Now of course all the issues have disappeared so I don't know what was wrong in the cache... :S 
.. sorry about that

I'll reopen this issue if I replicate the problem
Thanks again for all your help @ruslo
