### ISSUE TITLE
SDL2 2.0.4-p2 checksum changed

### ISSUE THREAD

**Issue by mchiasson** [ruslo/hunter#1315]
after nuking my `.hunter` folder, I started getting this strange error:
```
-- verifying file...
       file='/Users/mathieuchiasson/.hunter/_Base/Download/SDL2/2.0.4-p2/dfdcff7/2.0.4-p2.tar.gz'
-- SHA1 hash of
    /Users/mathieuchiasson/.hunter/_Base/Download/SDL2/2.0.4-p2/dfdcff7/2.0.4-p2.tar.gz
  does not match expected value
    expected: 'dfdcff72966c1b597154f21f59bf4d30964e8795'
      actual: '1a52dff915f9bd36689d85dbd98f724d88ae543d'
-- Hash mismatch, removing...
CMake Error at Build/SDL2-Release-prefix/src/SDL2-Release-stamp/download-SDL2-Release.cmake:157 (message):
  Each download failed!
```

and then I realised what was causing it:   My top cmakelists.txt was using `v0.19.34` this:
```
    HunterGate(
        URL "https://github.com/ruslo/hunter/archive/v0.19.34.tar.gz"
        SHA1 "9d0944566336eb6e4e26b4a709e1f17923a9aaa8"
        LOCAL # <----- Use local config.cmake
    )
```
while the subdirectory cmakelists.txt was using `v0.19.26` completely by accident from copy-pasting cmakelists.txt from another project location
```
    HunterGate(
        URL "https://github.com/ruslo/hunter/archive/v0.19.26.tar.gz"
        SHA1 "362b3c2fd8f0f50fc03cec5105be8fd4376ea886"
    )
```
As you can see, it was accidentally using 2 different versions of hunter, and then things started conflicting I guess.  Removing the 2nd `HungerGate` call solved the issue.  

This make me wonder:  Should hunter ignore every subsequent `HunterGate` calls after the first time it was issued?

**Comment by ruslo** [comment]
> As you can see, it was accidentally using 2 different versions of hunter, and then things started conflicting I guess

They should not, everything will be set in first HunterGate call, HunterGate calls from subdirectories will be ignored.

>  Removing the 2nd HungerGate call solved the issue

Sounds strange, should have no effects. Can you post minimal example to reproduce an issue and add logs with `-DHUNTER_STATUS_DEBUG=ON`?

**Comment by mchiasson** [comment]
sure. 

[cmake_hunter_output.txt](https://github.com/ruslo/hunter/files/1647385/cmake_hunter_output.txt)

I ran it after doing this just to be clear:
```
$ rm -rf ~/.hunter/
```
Here's my repo if you want to try on your own : 

http://github.com/mchiasson/GLBrebis

**Comment by ruslo** [comment]
```
> grep Hunter-ID cmake_hunter_output.txt
-- [hunter] [ Hunter-ID: 9d09445 | Config-ID: 111cff8 | Toolchain-ID: e1266bb ]
-- [hunter] [ Hunter-ID: 9d09445 | Config-ID: 111cff8 | Toolchain-ID: e1266bb ]
-- [hunter] [ Hunter-ID: 9d09445 | Config-ID: 111cff8 | Toolchain-ID: e1266bb ]
```

All HunterGate calls use same Hunter-ID meaning it was defined once and then inherited.

**Comment by mchiasson** [comment]
I think I've drawn the wrong conclusion. Something else is going on...

**Comment by mchiasson** [comment]
in the latest hunter/cmake/projects/SDL2/hunter.cmake, I am truly seeing this sha1:
```
hunter_add_version(
        PACKAGE_NAME
        SDL2
        VERSION
        "2.0.4-p2"
        URL
        "https://github.com/hunter-packages/SDL2/archive/2.0.4-p2.tar.gz"
        SHA1
        dfdcff72966c1b597154f21f59bf4d30964e8795
)
```
and when I manually download and check the sha1:
```
$ wget https://github.com/hunter-packages/SDL2/archive/2.0.4-p2.tar.gz
$ openssl sha1 2.0.4-p2.tar.gz 
SHA1(2.0.4-p2.tar.gz)= 1a52dff915f9bd36689d85dbd98f724d88ae543d
```
it's not the right one! :cold_sweat:

**Comment by mchiasson** [comment]
how is this even possible? This used to work, otherwise I would have never pushed it to git.

**Comment by ruslo** [comment]
GitHub changed the algo for generating archives, details here:
* https://github.com/ruslo/hunter/issues/1032

Use latest 2.0.4-* SDL2 release, it's `2.0.4-p8`.

**Comment by mchiasson** [comment]
yup, what I'm seeing in #1032 seems to be exactly what is going on here. Wow... This is really scary that github can change their compression algorithm anytime they want!  Hunter depends on these sha1 to remain stable! :disappointed:

**Comment by mchiasson** [comment]
I'll close this discussion, since it obviously duplicating #1032. Thank you @ruslo for the quick support. You are the best!

**Comment by ruslo** [comment]
> This is really scary that github can change their compression algorithm anytime they want! Hunter depends on these sha1 to remain stable!

It's not very good but not a disaster either. Not all packages was affected and it happenned just once for the 4 years of development period.

**Comment by OvermindDL1** [comment]
Perhaps using github releases instead of github archives would be far more preferable as they are stable?

**Comment by mchiasson** [comment]
I thought a github archive the archive of a github release...

**Comment by OvermindDL1** [comment]
An archive is a 'generated-on-the-fly' snapshot of a specific git commit or tag.  A release is a file that you upload manually (hunter's releases here use releases as at https://github.com/ruslo/hunter/releases and those should always be stable as they are custom files that can be anything you wish).

**Comment by ruslo** [comment]
> hunter's releases here use releases as at https://github.com/ruslo/hunter/releases and those should always be stable as they are custom files that can be anything you wish

Nope they are not stable, it's generated on the fly by GitHub. I guess you mean custom asset uploaded by user, like this one (file with name `v3.2.0-p0.tar.gz`):
* https://github.com/hunter-packages/opencv/releases/tag/v3.2.0-p0

But it means that we have to ask people to upload these files manually.

**Comment by OvermindDL1** [comment]
> Nope they are not stable, it's generated on the fly by GitHub. I guess you mean custom asset uploaded by user, like this one (file with name v3.2.0-p0.tar.gz):

Yes that.  I've only ever put up releases by manually uploading files.  ^.^;
