### ISSUE TITLE
password protected hunter fork

### ISSUE THREAD

**Issue by mchiasson** [ruslo/hunter#1320]
Hi @ruslo 

We are currently investigating, but my employer is very thrilled and excited by the prospect of using hunter as a much better and complete tool for building our customised 3rd party libraries for all the platforms that we need to support. However, all of our 3rdparty library repository forks will most likely need be private due to confidentiality agreement with some of our customers. 

(related to the #426 discussion) After reading https://docs.hunter.sh/en/latest/user-guides/cmake-user/protected-sources.html, it looks _exactly_ like what we need, and should work really well with this github access token ID solution.

However, it doesn't seem that `~/.config/Hunter/passwords.cmake` is used during the `HunterGate()` call if the URL points to our private hunter-mirror repository. Is this possible to do currently?

Thanks!

**Comment by mchiasson** [comment]
Ok, I feel like a complete idiot now, because the code that reads `~/.config/Hunter/passwords.cmake` is inside of hunter, and HunterGate _downloads_ hunter (so it doesn't even have the code yet). Please disregard this issue LOL.

**Comment by ruslo** [comment]
Currently implemented username/password protection for sources only for packages inside Hunter, but not for the HunterGate itself. Need to design and introduce such functionality to HunterGate module separately. Also note that Hunter archive contains only URL/SHA1 of sources, such feature will be useful only for protection of URL/SHA1 **strings** itself and if you want to protect internal code such as custom instructions for non-CMake build schemes.
