### ISSUE TITLE
Protobuf : error LNK 2005, MS Build 2017

### ISSUE THREAD

**Issue by xelavoprak** [ruslo/hunter#1323]
[CMakeLists.txt](https://github.com/ruslo/hunter/files/1664164/CMakeLists.txt)

`cmake.exe -H. -B_build -DHUNTER_STATUS_DEBUG=ON -DHUNTER_CONFIGURATION_TYPES=Release -DCMAKE_TOOLCHAIN_FILE=C:/git/polly/vs-15-2017.cmake -G "Visual Studio 15 2017" -DCMAKE_VERBOSE_MAKEFILE=ON`

[out.txt](https://github.com/ruslo/hunter/files/1664193/out.txt)

hunter_add_package(gRPC)
fail too.

**Comment by ruslo** [comment]
Error in Protobuf build. For the reference "Visual Studio 15 2017" is not regularly tested:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2666

**Comment by xelavoprak** [comment]
2015 work, thx.
Have some table for view, dependence polly(toolchain)?

**Comment by ruslo** [comment]
> Have some table for view, dependence polly(toolchain)?

Not sure I understand. Testing CI table use Polly toolchains under the hood, e.g. entry `vs-12-2013` will be build by `polly.py --toolchain vs-12-2013`. But as for Visual Studio it's the same as just doing `cmake -H. -B_builds -G "Visual Studio 12 2013"`.

**Comment by ruslo** [comment]
Closing inactive issue with "Broken package" label, see details:
* https://github.com/ruslo/hunter/wiki/error.external.build.failed
