### ISSUE TITLE
leveldb on WIN

### ISSUE THREAD

**Issue by xelavoprak** [ruslo/hunter#1324]
can`t build, [https://github.com/hunter-packages/leveldb](url)
not porting to win

**Comment by ruslo** [comment]
Only `MSYS` is working in Windows CI:
* https://github.com/ingenue/hunter/blob/9319378bc0cc6c8c44bbdca6fc3195bb83397fa9/appveyor.yml#L12-L41

**Comment by isaachier** [comment]
LevelDB never has and probably never will support Windows. Anyone claiming to have seen otherwise is usually referring to a forked version used in Bitcoin, but not the official package.

**Comment by ruslo** [comment]
Closing inactive issue with "Broken package" label, see details:
* https://github.com/ruslo/hunter/wiki/error.external.build.failed

**Comment by chfast** [comment]
Leveldb just merged native Windows support.
