### ISSUE TITLE
Is it possible to build different dependencies with different CXX compiler versions?

### ISSUE THREAD

**Issue by trivigy** [ruslo/hunter#1325]
Working on a current project that requires c++-17 but since some of the dependencies do not yet support 17 what I resort to doing manually is compiling those separately using c++-14 and just importing library files. I am new to huntergate and since I just discovered it I cannot figure out how to instruct the different dependencies to be build using different cmake_cxx_compiler settings. Would greatly appreciate some example if possible.

**Comment by ruslo** [comment]
It's not supported, you have to manage installed libraries yourself. Note that mixing different C++ standards in one project can lead to non-trivial errors:
* https://cgold.readthedocs.io/en/latest/tutorials/libraries/symbols/odr-global.html
* https://cgold.readthedocs.io/en/latest/tutorials/toolchain/globals/cxx-standard.html

**Comment by OvermindDL1** [comment]
I'm quite curious about is what libraries are not compiling in C++17 mode but will compile in C++14?  That sounds like those libraries are hard coding some very poor checks (equality instead of greater-than or so) and need fixes...

**Comment by dvirtz** [comment]
C++17 deprecated some features so it's quite possible.

**Comment by OvermindDL1** [comment]
> C++17 deprecated some features so it's quite possible.

Those were generally only either never/rarely-used, ambiguous, or overall poorly designed bits though, which is something that libraries should not have used anyway.  However, that should still not prevent compiling, just cause warnings (unless compiling with warnings as errors of course).  I'm still curious what libraries those as I've not had issues as of yet.  :-)

**Comment by trivigy** [comment]
@OvermindDL1 grpc does not compile on c++-17.

**Comment by trivigy** [comment]
@ruslo Thanks for pointing this out.

**Comment by OvermindDL1** [comment]
> @OvermindDL1 grpc does not compile on c++-17.

Cool, checking, I'm guessing this is it:
https://github.com/grpc/grpc

Wow that repo is a mess...  >.>
Over 800 issues and over 260 pull requests, most are very old interestingly...
But not seeing an issue about C++17, so that means that you should create an issue there with the error you get when trying to compile it in that mode.  :-)

**Comment by xsacha** [comment]
Think it is more worthwhile to fix the issue that stops it building in C++17 rather than having a mixed-use compatibility.

**Comment by ruslo** [comment]
Closing inactive discussion.
