### ISSUE TITLE
build crc32c with polly ios-nocodesign.cmake Error 

### ISSUE THREAD

**Issue by zhang-heng** [ruslo/hunter#1336]
crc32c for ios on mac, I get the following error:

error: unknown target CPU 'armv8-a+crc+crypto'

**Comment by ruslo** [comment]
Toolchain `ios-nocodesign-10-3` seems to work fine:
* https://travis-ci.org/ingenue/hunter/jobs/311198341

**Comment by zhang-heng** [comment]
thank you for your reply. this is my build log
[buildlog.txt](https://github.com/ruslo/hunter/files/1689255/buildlog.txt)

**Comment by ruslo** [comment]
> this is my build log

Error is inside package build, not a Hunter issue. If you know how to fix it please send pull request to https://github.com/hunter-packages/crc32c

**Comment by isaachier** [comment]
The issue is this flag `-march=armv8-a+crc+crypto`. Pretty sure crc32c upstream is trying to use architecture specific instructions your compiler doesn't support.

**Comment by ruslo** [comment]
Closing inactive issue with "Broken package" label, see details:
* https://github.com/ruslo/hunter/wiki/error.external.build.failed
