### ISSUE TITLE
websocketpp build error with openssl 1.1.0 on linux/osx

### ISSUE THREAD

**Issue by ikliashchou** [ruslo/hunter#1347]
https://github.com/zaphoyd/websocketpp/issues/599

it is already [fixed](https://github.com/zaphoyd/websocketpp/commit/16d126ee61dfc901e75abc5573b704c72a8d1f24) in websocketpp develop branch targeting v0.8.

As websocketpp is hunterized package I think we can apply the patch already to build it correctly.
You can check examples/websocketpp - it fails with current Hunter version when build on OS X, for example.

Should I create pull request to https://github.com/hunter-packages/websocketpp?

**Comment by ikliashchou** [comment]
Also related to this I have a question.
Each hunterized package mentions Hunter in CMakeList.txt with specific version.
Tests that are performed in https://github.com/ingenue/hunter/tree/pkg.websocketpp/ branch, for example, will never fail, as they are fixed to specific Hunter version, where they are passing OK.

 Shouldn't this be updated time to time to the latest? Like if some package is updated, all other packages dependent on it should be checked and updated if needed as a rule. What do you think?

**Comment by ruslo** [comment]
> it is already fixed in websocketpp develop branch targeting v0.8.

It's not released yet. I've named branch `hunter-0.7.0-16d126e`:
* https://github.com/hunter-packages/websocketpp/tree/hunter-0.7.0-16d126e

Please send pull request there with cherry-picked hunterization from previous `0.7.0-hunter` branch:
* https://github.com/hunter-packages/websocketpp/tree/0.7.0-hunter

It would be nice if you can refactor it into 3 simple commits "Add HunterGate module", "Use HunterGate module" and "Add hunter_add_package":
* https://docs.hunter.sh/en/latest/creating-new/patch.html

> Each hunterized package mentions Hunter in CMakeList.txt with specific version.

Yes, but if this package will be added as a dependency by `hunter_add_package` or by `add_subdirectory` then HunterGate will inherit settings from parent.

> Tests that are performed in https://github.com/ingenue/hunter/tree/pkg.websocketpp/ branch, for example, will never fail, as they are fixed to specific Hunter version, where they are passing OK

No, URL/SHA1 of Hunter archive created on-the-fly by `jenkins.py` script. From [log](https://travis-ci.org/ingenue/hunter/jobs/128382064):
```
  `-DTESTING_URL=/Users/travis/build/ingenue/hunter/_testing/hunter.tar.gz`
  `-DTESTING_SHA1=a059385dd0e1cec12e5804868c7baad60a33ad2f`
```

**Comment by ikliashchou** [comment]
I see you forked development branch from that commit. I thought we can just apply the patch to 0.7.0?

I looked into "hunterization" commits and it seems to be more complex than just 3 simple commits: the root CMakeLists.txt was completely [changed](https://github.com/hunter-packages/websocketpp/commit/ad84015e087f4c8add06c7fe06e2bcd72dbd0add). 
Do you think it worth to apply this ti the new branch now and then repeat again after 0.8.0 release?

**Comment by ruslo** [comment]
> I thought we can just apply the patch to 0.7.0?

Have used such approach before it's a mess. Better to cherry-pick all hunterization patches on top of upstream.

> I looked into "hunterization" commits and it seems to be more complex than just 3 simple commits: the root CMakeLists.txt was completely changed.

Can't comment on this, as you can see I'm not the one who made this commit.

> Do you think it worth to apply this to the new branch now and then repeat again after 0.8.0 release?

Yes

**Comment by ruslo** [comment]
Closing inactive discussion.
