### ISSUE TITLE
Boost: limit number of concurrent builds

### ISSUE THREAD

**Issue by chfast** [ruslo/hunter#1352]
On systems with high number of CPUs b2 is trying to use all of them and the build takes forever. Cap the number of concurrent builds.

See https://github.com/ethereum-mining/ethminer/issues/548#issuecomment-363371655.

**Comment by OvermindDL1** [comment]
This issue is only on older CMake versions as well?

**Comment by chfast** [comment]
I'm not sure this is CMake issue, unless Hunter is passing this number explicitly to b2. In the lined issue, the number of CPU was valid, but 20.

**Comment by Predelnik** [comment]
Isn't this due to #668?
Should actually be pretty easy to fix.

**Comment by chfast** [comment]
This seems to be different. The user there have 20 CPUs and b2 is building with 20 parallel jobs. The problem is in the b2 itself that hangs with such configuration. The workaround was to build with less number manually, but you cannot control this from Hunter.

**Comment by Predelnik** [comment]
Well quoting the user
> I manually installed boost with
>
> ./b2 -j N
> with N being the number of cpus in my workstation, in my case it’s 20.

Seems like with 20 it worked fine. But just having physical/logical cores to be 10/20 it would start building `-j200` which may cause trouble. I don't know for sure but I don't think that boost would have any trouble building with `-j20` on 20-core system.

**Comment by ruslo** [comment]
> Isn't this due to #668?

I think yes. Logical and physical values should not be multiplied here:
* https://github.com/ruslo/hunter/blob/78f356c878a42a3ace38ad8cf0599426563eebc0/cmake/modules/hunter_jobs_number.cmake#L41

Just physical should be used instead.

**Comment by dkeeney** [comment]
I am trying to install Boost (with system and filesystem) using Hunter and I am getting an error that seems to relate to this thread.  In the Build step for Boost:system it says "Invalid value for the '-j' option."

Running on Windows 7 x64, Intel 6 core processor,   Visual Studio 2017, CMake version 3.11.0-rc3
My top CMakeLists.txt contains:
```
cmake_minimum_required(VERSION 3.0)
include("cmake/HunterGate.cmake")
option(HUNTER_ENABLED "Enable Hunter package manager. If OFF no installs will occur." ON)
option(HUNTER_STATUS_DEBUG "Print a lot of info to help debug cmake scrips." ON)
option(HUNTER_JOBS_NUMBER "Maximum number of parallel threads during build." 6)
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.20.24.tar.gz"
    SHA1 "3e2037a462bcf2ec3440f60298d933e74ffd4df3"
)
project(nupic.core)
hunter_add_package(Boost COMPONENTS system filesystem)
find_package(Boost CONFIG REQUIRED system filesystem)

```
The command that fails is:
```
 'b2' '-a' 'link=static' 'threading=multi' 'variant=debug,release' '--layout
=tagged' 'toolset=msvc' '--user-config=C:/.hunter/_Base/3e2037a/b94518a/cd778ec/
Build/Boost/__system/Build/boost.user.jam' '--with-system' 'linkflags=/machine:x
64' 'address-model=64' '-j' 'ON' '--ignore-site-config'
```
Note the **-j ON** in the command. I know it should be a number (1 - 256).  I tried various values for HUNTER_JOBS_NUMBER .  1, 4, 6,  same error.  A value of 0 resulted in -j OFF.  A value of 1, 4, or 6 resulted in -j ON.

Any suggestions other than doing a manual install of Boost?

**Comment by ruslo** [comment]
> Note the -j ON in the command

@dkeeney That's because you're using `option(HUNTER_JOBS_NUMBER "..." 6)`, `option` is for boolean `ON` or `OFF` values. Effectively it's the same as `OFF` I guess. Try `set(HUNTER_JOBS_NUMBER 6 CACHE STRING "...")`

**Comment by dkeeney** [comment]
Success -- Thank you.

`set(HUNTER_JOBS_NUMBER 6 CACHE STRING "...")` 
did not work... it just passed all of the text on into the command.
```
     'b2' '-a' 'link=static' 'threading=multi' 'variant=debug,release' '--layout
=tagged' 'toolset=msvc' '--user-config=C:/.hunter/_Base/3e2037a/b94518a/cd778ec/
Build/Boost/__system/Build/boost.user.jam' '--with-system' 'linkflags=/machine:x
64' 'address-model=64' '-j' '6' 'CASHE' 'STRING' 'Maximum number of parallel thr
eads during build.' '--ignore-site-config'
```
But this did work:
`set(HUNTER_JOBS_NUMBER 6)`
Thanks

**Comment by dkeeney** [comment]
Oh I misspelled CACHE
anyway, it worked.

**Comment by ruslo** [comment]
Fixed in https://github.com/ruslo/hunter/releases/tag/v0.20.72
