### ISSUE TITLE
Support Android

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#136]
* Test toolchains: https://github.com/ruslo/polly/issues/10
* Update Boost scheme
* Update OpenSSL scheme

@headupinclouds Is it more important than binaries from site https://github.com/ruslo/hunter/issues/75? I just want to set milestone

**Comment by headupinclouds** [comment]
> @headupinclouds Is it more important than binaries from site #75? I just want to set milestone

For my needs, yes.  I need to build some projects for android within the next couple of weeks.  I'll push the initial toolchains to a polly branch as discussed.  I also think this feature will serve a wider audience for comparable effort.

**Comment by ruslo** [comment]
Branch `android`: https://github.com/ruslo/hunter/tree/android

**Comment by ruslo** [comment]
So simple example works. Let's debug some packages:
* [OpenCV](https://github.com/ruslo/hunter/issues/153)
* [Boost](https://github.com/ruslo/hunter/issues/154)
* [OpenSSL](https://github.com/ruslo/hunter/issues/155)
* [cvmatio](https://github.com/ruslo/hunter/issues/156)

@headupinclouds David, as far as I know GPUImage works only for iOS, so there will be no Android version. Do we need any other packages for the first time?

**Comment by headupinclouds** [comment]
This looks like a good initial set.  Eigen would be nice, but that is
header only.

**Comment by ruslo** [comment]
@headupinclouds `Eigen would be nice, but that is header only.` should just work in this case, let's test it anyway: [Android Eigen](https://github.com/ruslo/hunter/issues/157)

**Comment by headupinclouds** [comment]
Eigen is working, as are all the other libs mentioned above (with recent commits).  This can probably be closed.
