### ISSUE TITLE
Configuring OpenSSL for PocoCpp

### ISSUE THREAD

**Issue by ciband** [ruslo/hunter#1367]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. I think I mostly understand, but I am still pretty new to cmake.

* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. Yes

* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. Yes

I am working with the PocoCpp package. It works fine under Windows and Visual Studio 2017 but when I try to use it in a CI build with VSTS it fails. 

It appears it fails on building OpenSSL during the configure phase where it tries to detect its platform. 

Ideally (I think), I would want Poco to use the system installed OpenSSL but either solution will work. 

I am pretty new to this environment so any help or guidance is appreciated. 

Thank you.

**Comment by ruslo** [comment]
> I am pretty new to this environment so any help or guidance is appreciated

Not ignoring `ISSUE_TEMPLATE.md` file will be a good start:
* https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE.md

**Comment by ciband** [comment]
Sorry about that.  My apologies.  I have updated the original posting with template.  I think I did it write.  Thank you.

**Comment by ruslo** [comment]
> I would want Poco to use the system installed OpenSSL but either solution will work

OpenSSL package should be installed by Hunter:
* https://docs.hunter.sh/en/latest/faq/interaction-with-other-package-managers.html

System packages can be used, but only as a workaround for something that currently missing in Hunter.

> I am working with the PocoCpp package. It works fine under Windows and Visual
> Studio 2017 but when I try to use it in a CI build with VSTS it fails.

> It appears it fails on building OpenSSL during the configure phase where it
> tries to detect its platform.

See this part of `ISSUE_TEMPLATE.md`:


```
<!--- Use this part of template if you want to report bug. Remove the rest. -->
<!--- BEGIN -->

...

<!--- END -->
```

* https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE.md

This wiki page is worth reading too:
* https://github.com/ruslo/hunter/wiki/error.external.build.failed

**Comment by ciband** [comment]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. Yes, mostly understand I think
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. Yes
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. Yes
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. Yes
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). Yes
* I'm using latest Hunter URL/SHA1. Yes





* I've created SSCCE GitHub repository to reproduce the issue: https://github.com/<username>/<repo>

I have not created a sample sandbox for VSTS. I can try if we end up needing to.  I'm hoping the build log is enough to go on.


* AppVeyor build reproducing issue: https://ci.appveyor.com/project/<username>/hunter/build/<build-number>
* Travis build reproducing issue: https://travis-ci.org/<username>/hunter/builds/<build-number>
I cannot provide a link to the VSTS build results due to permission issues with VSTS (I think).

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
I have attached the log file to the issue
[CMake -G Visual Studio 15 2017.txt](https://github.com/ruslo/hunter/files/1786164/CMake.-G.Visual.Studio.15.2017.txt)




I've checked that the first error in logs **IS NOT** `external.build.failed`. Yes.  external.build.failed ultimately gets generated but the original error is upstream.


* I'm building on Windows via VSTS CI.
* [I'm using system CMake bundled with VS2017 I assume.
* CMake version:  >= 3.6 per constraints in CMakeLists.txt.  Not exactly sure what version is bundled with VS2017.


* I'm not using toolchain (I think, I didn't do anything explicit)

I'm using next command line on generate step:
```
Tried both of these.  Same result.

cmake "-G Visual Studio 15 2017"
cmake -H. -B_builds "-GVisual Studio 15 2017"
```

**Comment by ciband** [comment]
Just an update to this.  The same cmake files work on AppVeyor.  I'm not sure what the environment differences are between VSTS and AppVeyor or if that is helpful.

**Comment by ruslo** [comment]
> Here is the log until first error reported by Hunter, option HUNTER_STATUS_DEBUG is ON

According to the log it's not true.

> cmake -H. -B_builds "-GVisual Studio 15 2017"

Visual Studio 15 2017 is not part of the OpenSSL testing yet:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.3349

There is a chance that it was not working before.

**Comment by ciband** [comment]
For the time I have abandoned VSTS in my project in favor of AppVeyor and everything works well there, including using Visual Studio 2017 to build.  We can close this issue.  Thank you.
