### ISSUE TITLE
Add "ncnn" package

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#1384]
* I'm interested in package `tencent/ncnn`
* Here is official site of package https://github.com/tencent/ncnn

* This package is using Git: https://github.com/Tencent/ncnn.git

* Official GitHub repository: https://github.com/Tencent/ncnn.git

* Used build system: CMake

* This package has no dependencies

Please add a hunter-packages fork.

**Comment by ruslo** [comment]
> Please add a hunter-packages fork.

Done: https://github.com/hunter-packages/ncnn

Branch `hunter-20180314` created from the latest upstream tag `20180314`.

**Comment by headupinclouds** [comment]
Merged in #1398
