### ISSUE TITLE
dlib example does not compile ("Dlib requires C++11 support")

### ISSUE THREAD

**Issue by rsnitsch** [ruslo/hunter#1386]
The official dlib example does not compile. I get the following error message:
```
/Users/robert/Development/hunter/_Base/xxxxxxx/363bee1/9db0efd/Build/dlib/Source/dlib/dir_nav/../algs.h:17:10: error: "Dlib requires C++11 support.  Give your compiler the -std=c++11 option to enable it."
        #error "Dlib requires C++11 support.  Give your compiler the -std=c++11 option to enable it."
         ^

** BUILD FAILED **
```

I created a fix for this in my hunter fork:
https://github.com/rsnitsch/hunter/commit/4481054bed58d783f7400a79ca35de9c73d9ce99

I assume that the error occurs since this "Add c++11 warning" commit in dlib (it seems this is included since dlib v19.2):
https://github.com/davisking/dlib/commit/8061c31acfba4a5046bcadd83f1ae2c9190c545f#diff-2173b200f9de46817e7d23bbc7a32d62

I am aware that this should rather be fixed in the hunterized dlib package repository. Unfortunately I am not able to do that on my own, because my knowledge about hunter is not yet sufficient.

----

Details below:

* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **[Yes]**
* I'm using latest Hunter URL/SHA1. **[No: I'm using the current hunter repository from Git master branch tagged v0.20.24 with Hash 3161055de76a7d99c401e80bf6b04d6cb5ec2cff]**

* The official dlib example in hunter/examples/dlib does reproduce the issue.

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
* https://pastebin.com/nNSnk9um

I've checked that the first error in logs **IS NOT** `external.build.failed`. **[It is, but I still prefer to report the issue here.]**

* I'm building on OSX 10.13.3 (High Sierra)
* I'm using official CMake release
* CMake version: 3.9.6

* I'm not using toolchain

I'm using next command line on generate step:
```
cmake -H. -B_build -G "Xcode" -DHUNTER_STATUS_DEBUG=ON
```

---

**Comment by ruslo** [comment]
> I get the following error message

The toolchain file is the only way to apply global settings for 3rd party projects, including C++ standard:
* https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html
* https://cgold.readthedocs.io/en/latest/tutorials/toolchain/globals/cxx-standard.html#defaults

> /Users/robert/Development/hunter/_Base/xxxxxxx

`xxxxxxx` means that you're using Git based Hunter version. I don't recommend you to do that, you may hit non-trivial issues:
* https://github.com/ruslo/hunter/wiki/dev.hunter.root#jenkinspy

This is a robust way to test examples:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#testing-locally

> It is, but I still prefer to report the issue here

I highly recommend you to follow guides precisely since you just started. Please assume that if you don't see something explicitly allowed - then it's forbidden.

**Comment by rsnitsch** [comment]
You're right. Thanks for the fast response. In hindsight, it seems obvious.

For reference, the dlib example works for me with the following commands (note that you have to change the path to your polly installation, which I have hardcoded for now for the sake of simplicity):
```
CONFIGURE:
cmake -H. -B_build -G "Xcode" -DCMAKE_TOOLCHAIN_FILE=/Users/robert/Development/polly/xcode.cmake

BUILD:
cmake --build _build/

EXECUTE:
_build/Debug/bayes_net_ex
```
