### ISSUE TITLE
Add "ROS bare-bones" packages

### ISSUE THREAD

**Issue by lsolanka** [ruslo/hunter#1397]
I would like to propose adding ROS bare-bones stack to Hunter: https://github.com/ros

The current idea is to hunterise some of the core packages separately, in order to be able to reproduce the installation from source: http://wiki.ros.org/kinetic/Installation/Source.

Then the users would use, e.g. `hunter_add_package(ros-ros_comm)` inside their CMakeLists.txt to pull the whole hunterised ros bare-bones. That, in turn, would pull all the transitive dependencies.

I have all packages required for the bare-bones installation from source hunterised, so I would like to start a discussion about potentially making these inside the mainstream Hunter, if it is of interest to the wider community.

The main dependencies are:
- Boost
- OpenCV
- Python (during the build both the python interpreter, as well as PythonLibs for C extensions)
- tinyxml2
- log4cxx
- empy
- Poco

A few caveats:
- ROS uses a 'catkin' build system, which is basically CMake based, however the build proceeds in a non-standard way (i.e. they have the concept of a devel space instead of install-and-find-package). Therefore I had to patch the catkin repository quite extensively to support the 'hunter_add_package' directive.
- I did not have time/resources to hunterise some dependencies of log4cxx, such as libapr1, libapr-utils etc. and these have to be linked in as shared libraries, otherwise the logging will only print to stdout.
- Perfect hunterisation is not possible given the complexity of the ROS build system and thus pushing upstream is unlikely
- ROS has many more dependencies required for build than those stated above, which normally have to be resolved using the 'rosdep' tool, so I'm not sure how well the packages will integrate with the Hunter CI here.
- The consequence is that the build might work nicely on Ubuntu, but not on Windows that much. I haven't had any time to test on Windows as I'm not a windows user.

The work was done partly during my working hours in [SeeByte Ltd.](http://www.seebyte.com), so it would be fair to at least acknowledge them in the docs if the packages become part of the community.

TODO list for all the partial packages:
- [x] https://github.com/lsolanka/console_bridge => #1403
- [x] https://github.com/lsolanka/catkin => #1407
- [x] https://github.com/lsolanka/roscpp_core => #1412
- [x] https://github.com/lsolanka/genmsg => #1410
- [x] https://github.com/lsolanka/geneus => #1416 
- [x] https://github.com/lsolanka/gencpp => #1416
- [x] https://github.com/lsolanka/genpy => #1416
- [x] https://github.com/lsolanka/gennodejs => #1416
- [x] https://github.com/lsolanka/genlisp => #1416
- [x] https://github.com/lsolanka/message_generation => #1435
- [x] https://github.com/lsolanka/message_runtime => #1439
- [x] https://github.com/lsolanka/std_msgs => #1450
- [x] https://github.com/lsolanka/tinyxml2 (required by rospack) => #1426
- [x] https://github.com/lsolanka/rospack => #1435
- [x] https://github.com/lsolanka/ros_comm_msgs => #1461
- [x] https://github.com/ros/ros_environment => #1450
- [x] https://github.com/lsolanka/common_msgs => #1461
- [x] https://github.com/lsolanka/ros => #1461
- [ ] https://github.com/ros-hunter/class_loader => see https://github.com/ros-hunter/class_loader/tree/pr.hunter-0.4.1
- [ ] https://github.com/ros/rosconsole ==> patches applied on v1.13.7-p0 in hunter-packages. Version moved to 1.13.10.
- [ ] https://github.com/ros/pluginlib/ ==> patches applied in https://github.com/ros-hunter/pluginlib/tree/pr.hunter-1.12.1
- [ ] https://github.com/lsolanka/ros_comm ==> current WIP on https://github.com/ros-hunter/ros_comm/tree/pr.hunter-1.14.1. Latest version: 1.14.3
- [ ] https://github.com/lsolanka/actionlib ==> current WIP https://github.com/ros-hunter/actionlib/tree/pr.hunter-1.11.13
- [ ] https://github.com/lsolanka/angles ==> https://github.com/ros-hunter/angles/tree/hunterise
- [ ] https://github.com/lsolanka/geometry2 (only tf2 as the full repo requires some more libraries as dependencies) ==> current WIP https://github.com/ros-hunter/geometry2/tree/pr.hunter-0.6.2; latest melodic version: 0.6.5

**Comment by lsolanka** [comment]
I'm happy to provide examples of how to use the current versions of hunterised packages from a user's CMakeLists.txt.

**Comment by ruslo** [comment]
> Currently I have the following packages of ROS Kinetic successfully compiling on Linux using Hunter

@lsolanka Do you want me to create corresponding forks in https://github.com/hunter-packages ?

**Comment by lsolanka** [comment]
> > Currently I have the following packages of ROS Kinetic successfully compiling on Linux using Hunter
> 
> @lsolanka Do you want me to create corresponding forks in https://github.com/hunter-packages ?
Yes, that would be great - assuming I'll be able to push patches to that also in the future (contrib guidelines mention you can add me to the organisation?)

**Comment by ruslo** [comment]
> Yes, that would be great

Okay, I will create forks and create branches `hunter-X.Y.Z` where `X.Y.Z` is the latest upstream release tag.

> assuming I'll be able to push patches to that also in the future (contrib guidelines mention you can add me to the organisation?)

Yes, you will have permissions to write directly however it's better to make a pull request for review reason. 

Basically the rules are here: https://docs.hunter.sh/en/latest/creating-new/patch.html

**Comment by ruslo** [comment]
> Okay, I will create forks and create branches hunter-X.Y.Z where X.Y.Z is the latest upstream release tag.

Done, let me know if I missed anything.

> https://github.com/lsolanka/tinyxml

Active development now is in tinyxml2 project, located here: https://github.com/leethomason/tinyxml2 

Can we use tinyxml2 instead of tinyxml?

**Comment by lsolanka** [comment]
> Yes, you will have permissions to write directly however it's better to make a pull request for review reason.
> 
> Basically the rules are here: [https://docs.hunter.sh/en/latest/creating-new/patch.html](https://docs.hunter.sh/en/latest/creating-new/patch.html)

Yes, of course, not sure why I even said that...pull request is the way.

> > [https://github.com/lsolanka/tinyxml](https://github.com/lsolanka/tinyxml)
> 
> Active development now is in tinyxml2 project, located here: [https://github.com/leethomason/tinyxml2](https://github.com/leethomason/tinyxml2)
> 
> Can we use tinyxml2 instead of tinyxml?

Yes, the latest stable ROS (Lunar) uses tinyxml2 already so we should go with that. Kinetic is a bit older.

I will start preparing the pull request for catkin which is the common dependency of everything.

**Comment by ruslo** [comment]
> Yes, the latest stable ROS (Lunar) uses tinyxml2 already so we should go with that. Kinetic is a bit older.

Looks like they have `*Config.cmake` installation. If package doesn't have dependencies it can be used as is and there is no need to maintain a fork.

**Comment by lsolanka** [comment]
[**@ruslo**](https://github.com/ruslo) commented on [8 Apr 2018, 13:53 GMT+1](https://github.com/ruslo/hunter/issues/1397#issuecomment-379548380 "2018-04-08T12:53:32Z - Replied by Github Reply Comments"):
> Okay, I will create forks and create branches `hunter-X.Y.Z` where `X.Y.Z` is the latest upstream release tag.

https://github.com/hunter-packages/ros_comm has hunter-1.12.13, but I think the latest stable release is 1.13.6.

**Comment by ruslo** [comment]
> but I think the latest stable release is 1.13.6

It was last by date :) Branch `hunter-1.13.6` created:
* https://github.com/hunter-packages/ros_comm/tree/hunter-1.13.6

**Comment by lsolanka** [comment]
[**@ruslo**](https://github.com/ruslo) commented on [9 Apr 2018, 11:58 GMT+1](https://github.com/ruslo/hunter/issues/1397#issuecomment-379713885 "2018-04-09T10:58:35Z - Replied by Github Reply Comments"):
> Looks like they have `*Config.cmake` installation. If package doesn't have dependencies it can be used as is and there is no need to maintain a fork.

[CMakeLists.txt](https://github.com/leethomason/tinyxml2/blob/3cdaf8b15e6f54eb88adda848068384a877d6cca/CMakeLists.txt#L100) seems to have an absolute install include directory for the target:
```CMake
if(DEFINED CMAKE_VERSION AND NOT "${CMAKE_VERSION}" VERSION_LESS "2.8.11")
    target_include_directories(tinyxml2_static PUBLIC 
                          $<BUILD_INTERFACE:${PROJECT_SOURCE_DIR}>
                          $<INSTALL_INTERFACE:${CMAKE_INSTALL_PREFIX}/include>)

if(MSVC)
```
Am I correct to say that it breaks relocatability?

**Comment by ruslo** [comment]
> Am I correct to say that it breaks relocatability?

Yes, it should be just ` $<INSTALL_INTERFACE:include>`

**Comment by lsolanka** [comment]
@ruslo  should we maybe create a fork of TinyXML2 as well?

**Comment by ruslo** [comment]
> > Yes, the latest stable ROS (Lunar) uses tinyxml2 already so we should go with that. Kinetic is a bit older.

> Looks like they have *Config.cmake installation. If package doesn't have dependencies it can be used as is and there is no need to maintain a fork.

@lsolanka Are there any issues with upstream install?

**Comment by lsolanka** [comment]
> @lsolanka Are there any issues with upstream install?

I had to do a small patch to remove the relative paths:
https://github.com/lsolanka/tinyxml2/commit/222f1b43a98ede846728ba6d254359fcf1ae4309
It looks like `CMAKE_INSTALL_LIBDIR` is an absolute path as well, at least on my Ubuntu 16.04. This causes the *Targets.cmake to include some files using absolute paths.

**Comment by ruslo** [comment]
Done: https://github.com/hunter-packages/tinyxml2

**Comment by lsolanka** [comment]
Request to fork https://github.com/ros/ros_environment which is required by the latest versions of `ros' package. Note that we need 1.2.0 which is part of ROS1. 2.0.0 is part of ROS2, which is a whole new story...

There was a new patch release of `ros` so I've also added branch https://github.com/hunter-packages/ros/tree/hunter-1.14.4, but the default branch is still 1.14.3 as I don't have permissions to access 'Settings'.

**Comment by ruslo** [comment]
> Request to fork https://github.com/ros/ros_environment which is required by the latest versions of `ros' package

@lsolanka Done: https://github.com/hunter-packages/ros_environment

**Comment by ruslo** [comment]
> a rosconsole package which was formerly inside ros_comm was moved to a separate repo: https://github.com/ros/rosconsole. We will need this one to be cloned as well.

Done: https://github.com/hunter-packages/rosconsole

**Comment by lsolanka** [comment]
@ruslo, 2 more repos needed to finalize `ros_comm`:

- https://github.com/ros/class_loader (depends on Poco::Foundation, which should be in hunter already?)
- https://github.com/ros/pluginlib/

Didn't have much time to finalize this and only now I started working it out in detail.

Both will require patches.

**Comment by ruslo** [comment]
> 2 more repos needed to finalize ros_comm:

Done:
* https://github.com/hunter-packages/class_loader
* https://github.com/hunter-packages/pluginlib

> which should be in hunter already?

See https://docs.hunter.sh/en/latest/packages/pkg/PocoCpp.html

**Comment by acasadom** [comment]
Hello
   I am starting to play with ROS and using hunter for this seems a very good idea, however there  still are a few repos in the todo lists and I have also seen that  Lukas Solanka's repo differs from hunter and is having a couple of this ROS packages already integrated.

I wonder if this issue is a work in progress or has been just abandon in the way it is..

**Comment by acasadom** [comment]
Hi Lukas,
I am not an expert, neither in ROS neither in cmake. I am just having a big "project" with a lot of 3th-party dependencies and I would like to use hunter to handle this complexity. I am learning cmake, hunter and ROS as I go.

I am thinking in trying to continue your work and see if I can make the "project" work, it has more ROS dependencies , for instance ros_perception, but maybe I can manage to have some time to try this.

are you aware of any "hidden issue in ROS" that could make this approach of using hunter not be usable?

Of course if I am able to make it work I will ask Ruslan to add all the new packages I would need to hunterise..

**Comment by lsolanka** [comment]
The fork of Hunter I have which contains ros_comm should be tested. I think
I've used it in my pet project in lsolanka/a4wd2. I've successfully
compiled everything of melodic up to ros comm, including tf2 and actionlib,
and tested cross compilation to armhf onto raspberry pi using Polly, which
is really cool.

As I mentioned it only needs to be integrated into Hunter's CI and then it
becomes official. That's actually quite a lot of manual work so that's why
I put it on hold...

The only issue that could hit you is that once you switch to Hunter you
need to hunterize all your ros dependencies, which can be quite time
consuming.

Otherwise it would be great if you add a few more packages.

Also, there's absolutely no warranty whatsoever from my side about any
damage to your robot or yourself you make by using these packages from
Hunter ;)

**Comment by lsolanka** [comment]
Sorry, correction, what I have in my personal fork of Hunter: it is not melodic purely, but some sort of hybrid. I think I had an issue with the fact that `ros_comm` in melodic has been split into several smaller repositories (class_loader, pluginlib, etc.) which are dependencies of `ros_comm`. These smaller libraries needed to be hunterised, which I've mostly finished, but they are not in official Hunter CI. That's why the work was put on hold.

**Comment by lsolanka** [comment]
@kgeorgiev93 I have added some links to the issue description, pointing to some of the committed WIP I haven't had time to do. Some packages moved so some rebase might be necessary.

**Comment by pretyman** [comment]
Hi @lsolanka 

Did you consider hijacking `find_package(catkin ...)` and wrap hunter around inside the find script? If so, what was the conclusion?

**Comment by lsolanka** [comment]
> Hi @lsolanka
> 
> Did you consider hijacking `find_package(catkin ...)` and wrap hunter inside the find script? If so, what was the conclusion?

No, not sure actually what you mean exactly by that. Perhaps you could elaborate more about what "hijacking", and "wrap hunter" would mean in this case?

**Comment by kgeorgiev93** [comment]
Hi @ruslo and @lsolanka. I have taken some time to familiarize myself with all the ros packages that have been hunterised already and the ones left to do as per the TODO in this comment https://github.com/ruslo/hunter/issues/1397#issue-312294502.

I then have picked up where @lsolanka had left off in the partially hunterised packages to wrap up the hunterisation. I have also updated most of the already hunterised packages as they have moved versions in upstream.

I will try to summarize what I have done for each package and the way forward:

- console_bridge - applied the already existing changes to latest version 0.4.3
- catkin - applied the already existing changes to latest version  0.7.17
- roscpp_core - applied the already existing changes to latest version 0.6.12
- ros_genmsg - applied the already existing changes to latest version 0.5.12
- ros_geneus - no changes
- ros_gencpp - applied the already existing changes to latest version 0.6.2
- ros_genpy - applied the already existing changes to latest version 0.6.8
- ros_gennodejs - no changes
- ros_genlisp - no changes
- ros_message_generation - no changes
- ros_message_runtime - no changes
- ros_std_msgs - applied the already existing changes to latest version 0.5.12
- rospack - applied the already existing changes to latest version 2.5.3
- ros_common_msgs -applied the already existing changes to latest version 1.12.7
- ros_comm_msgs - no changes
- ros_environment - applied the already existing changes to latest version 1.2.1
- ros - applied the already existing changes to latest version 1.14.6

- class_loader - continued work from @lsolanka on version 0.4.1 - just an update to HunterGate
- rosconsole - applied @lsolanka's changes to latest version 1.13.10
- pluginlib - continued work from @lsolanka on version 1.12.1 - just an update to HunterGate
- ros-comm - applied @lsolanka's changes to latest version 1.14.3 and added small changes
- actionlib - continued work from @lsolanka on version 1.11.13 - just an update to HunterGate
- angles - continued work from @lsolanka on version 1.9.11 - just an update to HunterGate
- tf2 - continued work from @lsolanka and applied his changes to version 0.6.5
- tf - continued work from @lsolanka with small changes on version 1.12.0. As far as I see, this is the only ros package that doesn't yet have a fork in hunter-packages. The upstream is https://github.com/ros/geometry. Only tf has been hunterised as the other packages have more non hunterised dependencies.

I will start creating pull requests for these in the same order. For the packages that have no changes,
I think I should still update their HunterGate to get the latest versions of their dependencies as they get released. 

I have followed the descriptions in https://docs.hunter.sh/en/latest/creating-new/create/cmake.html,
https://docs.hunter.sh/en/latest/creating-new/patch.html and https://docs.hunter.sh/en/latest/creating-new/update.html. My understanding is to first create pull requests for each package to https://github.com/hunter-packages. Then following the guides, either update it in hunter for existing packages or add a new package there. Is that correct, am I missing something? Obviously I will do everything in my own forks and send the pull requests.

Also, I wanted to mention that so far I have done this during my working hours in SeeByte Ltd, so it would be fair to at least acknowledge them in the docs.

**Comment by ruslo** [comment]
> console_bridge - applied the already existing changes to latest version 0.4.3

- https://github.com/hunter-packages/ros_console_bridge/tree/hunter-0.4.3

> catkin - applied the already existing changes to latest version 0.7.17

- https://github.com/hunter-packages/catkin/tree/hunter-0.7.17

> roscpp_core - applied the already existing changes to latest version 0.6.12

- https://github.com/hunter-packages/roscpp_core/tree/hunter-0.6.12

> ros_genmsg - applied the already existing changes to latest version 0.5.12

- https://github.com/hunter-packages/ros_genmsg/tree/hunter-0.5.12

> ros_gencpp - applied the already existing changes to latest version 0.6.2

- https://github.com/hunter-packages/ros_gencpp/tree/hunter-0.6.2

> ros_genpy - applied the already existing changes to latest version 0.6.8

- https://github.com/hunter-packages/ros_genpy/tree/hunter-0.6.8

> ros_std_msgs - applied the already existing changes to latest version 0.5.12

- https://github.com/hunter-packages/ros_std_msgs/tree/hunter-0.5.12

> rospack - applied the already existing changes to latest version 2.5.3

- https://github.com/hunter-packages/rospack/tree/hunter-2.5.3

> ros_common_msgs -applied the already existing changes to latest version 1.12.7

- https://github.com/hunter-packages/ros_common_msgs/tree/hunter-1.12.7

> ros_environment - applied the already existing changes to latest version 1.2.1

- https://github.com/hunter-packages/ros_environment/tree/hunter-1.2.1

> ros - applied the already existing changes to latest version 1.14.6

- https://github.com/hunter-packages/ros/tree/hunter-1.14.6

> class_loader - continued work from @lsolanka on version 0.4.1 - just an update to HunterGate

- https://github.com/hunter-packages/class_loader/tree/hunter-0.4.1

> rosconsole - applied @lsolanka's changes to latest version 1.13.10

That's confusing, are they different?

- https://github.com/ros/console_bridge
- https://github.com/ros/rosconsole_bridge

> pluginlib - continued work from @lsolanka on version 1.12.1 - just an update to HunterGate

- https://github.com/hunter-packages/pluginlib/tree/hunter-1.12.1

> ros-comm - applied @lsolanka's changes to latest version 1.14.3 and added small changes

- https://github.com/hunter-packages/ros_comm/tree/hunter-1.14.3

> actionlib - continued work from @lsolanka on version 1.11.13 - just an update to HunterGate

- https://github.com/hunter-packages/actionlib/tree/hunter-1.11.13

> angles - continued work from @lsolanka on version 1.9.11 - just an update to HunterGate

- https://github.com/hunter-packages/angles/tree/hunter-1.9.11

> tf2 - continued work from @lsolanka and applied his changes to version 0.6.5

- https://github.com/hunter-packages/tf2/tree/hunter-0.6.5

>  As far as I see, this is the only ros package that doesn't yet have a fork in hunter-packages

Created: https://github.com/hunter-packages/ros_geometry

> Also, I wanted to mention that so far I have done this during my working hours in SeeByte Ltd, so it would be fair to at least acknowledge them in the docs.

You can do it similar to:
- https://docs.hunter.sh/en/latest/packages/pkg/catkin.html

> My understanding is to first create pull requests for each package to https://github.com/hunter-packages. Then following the guides, either update it in hunter for existing packages or add a new package there. Is that correct, am I missing something?

Yes, that's the path.

**Comment by kgeorgiev93** [comment]
> > rosconsole - applied @lsolanka's changes to latest version 1.13.10
> 
> That's confusing, are they different?
>
>     * https://github.com/ros/console_bridge
>     * https://github.com/ros/rosconsole_bridge

Yes, these are different packages. There is rosconsole, console_bridge and rosconsole_bridge.

In hunter we have a fork of console_bridge (first package above) https://github.com/hunter-packages/ros_console_bridge,

and a fork of rosconsole - https://github.com/hunter-packages/rosconsole.


> > As far as I see, this is the only ros package that doesn't yet have a fork in hunter-packages
> 
> Created: https://github.com/hunter-packages/ros_geometry
> 
Should this be named tf instead, similar to how the ros package geometry2 was named tf2 in hunter?

**Comment by ruslo** [comment]
> rosconsole - applied @lsolanka's changes to latest version 1.13.10

- https://github.com/hunter-packages/rosconsole/tree/hunter-1.13.10

> Should this be named tf instead, similar to how the ros package geometry2 was named tf2 in hunter?

Renamed: https://github.com/hunter-packages/tf

**Comment by kgeorgiev93** [comment]
@ruslo, I am trying to create a pull request for `ros_comm`, but am unable to set the base repository to `hunter_packages/ros_comm`. Could you check the settings for this repo?

**Comment by ruslo** [comment]
>  I am trying to create a pull request for ros_comm, but am unable to set the base repository to hunter_packages/ros_comm. Could you check the settings for this repo?

Repo is https://github.com/hunter-packages/ros_comm the branch is https://github.com/hunter-packages/ros_comm/tree/hunter-1.14.3

From:

> > ros-comm - applied @lsolanka's changes to latest version 1.14.3 and added small changes

> https://github.com/hunter-packages/ros_comm/tree/hunter-1.14.3

Do we need another release branch?

**Comment by kgeorgiev93** [comment]
> 
> Repo is https://github.com/hunter-packages/ros_comm the branch is https://github.com/hunter-packages/ros_comm/tree/hunter-1.14.3
> 
> From:
> 
> > > ros-comm - applied @lsolanka's changes to latest version 1.14.3 and added small changes
> 
> > https://github.com/hunter-packages/ros_comm/tree/hunter-1.14.3
> 
> Do we need another release branch?

No, that is correct. This is the release branch I am trying to create a pull request for. We don't need another release branch.

I had originally forked this from https://github.com/ros-hunter/ros_comm and I wasn't able to create the pull request and change the base repository to https://github.com/hunter-packages/ros_comm. This is what I meant.

I now have forked it from https://github.com/hunter-packages/ros_comm and am able to create the pull request.

**Comment by kgeorgiev93** [comment]
All ROS barebones packages are now added as per https://github.com/ruslo/hunter/issues/1397#issuecomment-496585970. 

Documentation was also updated in https://github.com/ruslo/hunter/pull/1934.

I think we can close this issue.
