### ISSUE TITLE
Can't build boost on windows 10

### ISSUE THREAD

**Issue by JasonDictos** [ruslo/hunter#1402]
c:\code\dictos>cmake -H. -B_build -G"Visual Studio 15 2017 Win64"
-- cotire 1.7.10 loaded.
-- The C compiler identification is MSVC 19.13.26129.0
-- The CXX compiler identification is MSVC 19.13.26129.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
Hunter boost version: 1.66.0
-- [hunter] HUNTER_ROOT: C:/.hunter
-- [hunter] [ Hunter-ID: 72bd88d | Toolchain-ID: b94518a | Config-ID: 551f163 ]
-- [hunter] BOOST_ROOT: C:/.hunter/_Base/72bd88d/b94518a/551f163/Install (ver.: 1.66.0)
-- [hunter] Building Boost
loading initial cache file C:/.hunter/_Base/72bd88d/b94518a/551f163/cache.cmake
loading initial cache file C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost/args.cmake
-- The C compiler identification is MSVC 19.13.26129.0
-- The CXX compiler identification is MSVC 19.13.26129.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost/Build
Microsoft (R) Build Engine version 15.6.82.30579 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 4/11/2018 4:29:48 PM.
Project "C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\ALL_BUILD.vcxproj" on node 1 (default targets).
Project "C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\ALL_BUILD.vcxproj" (1) is building "C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\ZERO_CHECK.vcxproj" (2) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\ZERO_CHECK\".
  Creating directory "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
CustomBuild:
  Checking Build System
  CMake is re-running because generate.stamp.list is missing.
  -- Configuring done
  -- Generating done
  -- Build files have been written to: C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost/Build
FinalizeBuildStatus:
  Deleting file "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\unsuccessfulbuild".
  Touching "x64\Debug\ZERO_CHECK\ZERO_CHECK.tlog\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\ZERO_CHECK.vcxproj" (default targets).
Project "C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\ALL_BUILD.vcxproj" (1) is building "C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\Boost.vcxproj" (3) on node 1 (default targets).
PrepareForBuild:
  Creating directory "x64\Debug\Boost\".
  Creating directory "x64\Debug\Boost\Boost.tlog\".
InitializeBuildStatus:
  Creating "x64\Debug\Boost\Boost.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ComputeCustomBuildOutput:
  Creating directory "C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\Boost-prefix\src\Boost-stamp\Debug\".
  Creating directory "C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\CMakeFiles\Debug\".
CustomBuild:
  Creating directories for 'Boost'
  Building Custom Rule C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost/CMakeLists.txt
  CMake does not need to re-run because C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost/Build/CMakeFiles/generate.stamp is up-to-date.
  Performing download step (download, verify and extract) for 'Boost'
  -- Boost download command succeeded.  See also C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-download-*.log
  Performing update step for 'Boost'
  No patch step for 'Boost'
  Performing configure step for 'Boost'
  CMake Error at C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-configure-Debug.cmake:16 (message):
    Command failed: 1

     'C:/Program Files/CMake/bin/cmake.exe' '-Dmake=' '-Dconfig=Debug' '-P' 'C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-configure-Debug-impl.cmake'

    See also

      C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-configure-*.log

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\Boost.vcxproj]
Done Building Project "C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\Boost.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\Boost.vcxproj" (default target) (3) ->
(CustomBuild target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\.hunter\_Base\72bd88d\b94518a\551f163\Build\Boost\Build\Boost.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:32.59

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.20.32/72bd88d/Unpacked/cmake/projects/Boost]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.20.32/72bd88d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.20.32/72bd88d/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.20.32/72bd88d/Unpacked/cmake/modules/hunter_download.cmake:660 (hunter_fatal_error)
  C:/.hunter/_Base/Download/Hunter/0.20.32/72bd88d/Unpacked/cmake/projects/Boost/hunter.cmake:304 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.20.32/72bd88d/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:27 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "C:/code/dictos/_build/CMakeFiles/CMakeOutput.log".

c:\code\dictos>gvim C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-configure-*.log

c:\code\dictos>

The log file shows:

'patched_boostrap.bat' is not recognized as an internal or external command,

operable program or batch file.

CMake Error at C:/.hunter/_Base/72bd88d/b94518a/551f163/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-configure-Debug-impl.cmake:19 (message):
  Command failed (1):

   'patched_boostrap.bat'

**Comment by ruslo** [comment]
This issue will be closed because the required template file [ISSUE_TEMPLATE.md][1] was ignored. Please read and fill carefully all parts of this file while submitting a bug report.

Thanks for understanding.

[1]: https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE.md
