### ISSUE TITLE
Add "forest" package

### ISSUE THREAD

**Issue by xorz57** [ruslo/hunter#1404]
* I'm interested in package `<forest>`

* Official GitHub repository: https://github.com/xorz57/forest

* Used build system: [header-only does not require build system]

* This package has no dependencies

**Comment by ruslo** [comment]
> header-only does not require build system

In general it's better to use build system even for header-only libraries:
* library should be tested
* library may have dependencies even if it's header-only itself
* you may want to install `*Config.cmake` files for integration into other projects

Adding CMake installation code to header-only library is a trivial effort:
* https://github.com/ruslo/leathers/blob/4bd0f6c36468c479f6010c45ab4f5f919c11ed49/CMakeLists.txt#L91-L141
