### ISSUE TITLE
Help-me to solve this problem please!

### ISSUE THREAD

**Issue by MarcosSoares10** [ruslo/hunter#1409]
"C:\Program Files\JetBrains\CLion 2018.1.1\bin\cmake\bin\cmake.exe" -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - MinGW Makefiles" C:\Users\Marquinhos\mobagen
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: C:/.hunter
-- [hunter] [ Hunter-ID: 44c5a98 | Toolchain-ID: 4ec64c2 | Config-ID: eb72dfe ]
-- [hunter] CURL_ROOT: C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Install (ver.: 7.49.1-DEV-v9)
-- [hunter] Building CURL
loading initial cache file C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/cache.cmake
loading initial cache file C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/CURL/args.cmake
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/gcc.exe -- works
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/g++.exe -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/CURL/Build
Scanning dependencies of target CURL-Release
[  6%] Creating directories for 'CURL-Release'
[ 12%] Performing download step (download, verify and extract) for 'CURL-Release'
-- verifying file...
       file='C:/.hunter/_Base/Download/CURL/7.49.1-DEV-v9/4d4cb6e/hunter-7.49.1-v9.tar.gz'
-- File already exists and hash match (skip download):
  file='C:/.hunter/_Base/Download/CURL/7.49.1-DEV-v9/4d4cb6e/hunter-7.49.1-v9.tar.gz'
  SHA1='4d4cb6e5faebfceaafa152bb3572c4760f1745cf'
-- extracting...
     src='C:/.hunter/_Base/Download/CURL/7.49.1-DEV-v9/4d4cb6e/hunter-7.49.1-v9.tar.gz'
     dst='C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/CURL/Source'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 18%] No patch step for 'CURL-Release'
[ 25%] No update step for 'CURL-Release'
[ 31%] Performing configure step for 'CURL-Release'
loading initial cache file C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/cache.cmake
loading initial cache file C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/CURL/args.cmake
-- The C compiler identification is GNU 7.3.0
-- Check for working C compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/gcc.exe -- works
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning at CMakeLists.txt:54 (message):
  the curl cmake build system is poorly maintained.  Be aware

-- curl version=[7.49.1-DEV]
CMake Warning at CMakeLists.txt:243 (message):
  Found no *nroff program

-- Looking for getch in ws2_32;
-- Looking for getch in ws2_32; - found
-- Looking for getch in winmm;ws2_32
-- Looking for getch in winmm;ws2_32 - found
-- [hunter] HUNTER_ROOT: C:/.hunter
-- [hunter] [ Hunter-ID: 44c5a98 | Toolchain-ID: 4ec64c2 | Config-ID: eb72dfe ]
-- [hunter] OPENSSL_ROOT: C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Install (ver.: 1.1.0h)
-- [hunter] Building OpenSSL
loading initial cache file C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/cache.cmake
loading initial cache file C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL/args.cmake
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/gcc.exe
-- Check for working C compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/gcc.exe -- works
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/g++.exe
-- Check for working CXX compiler: C:/Users/Marquinhos/Downloads/MinGW/bin/g++.exe -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL/Build
mingw32-make.exe[3]: Entering directory 'C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL/Build'
mingw32-make.exe[4]: Entering directory 'C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL/Build'
mingw32-make.exe[5]: Entering directory 'C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL/Build'
Scanning dependencies of target OpenSSL
mingw32-make.exe[5]: Leaving directory 'C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL/Build'
mingw32-make.exe[5]: Entering directory 'C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL/Build'
[ 12%] Creating directories for 'OpenSSL'
[ 25%] Performing download step (download, verify and extract) for 'OpenSSL'
-- verifying file...
       file='C:/.hunter/_Base/Download/OpenSSL/1.1.0h/2168c88/OpenSSL_1_1_0h.tar.gz'
-- File already exists and hash match (skip download):
  file='C:/.hunter/_Base/Download/OpenSSL/1.1.0h/2168c88/OpenSSL_1_1_0h.tar.gz'
  SHA1='2168c88516556332ebaf7c31791132025a093c2b'
-- extracting...
     src='C:/.hunter/_Base/Download/OpenSSL/1.1.0h/2168c88/OpenSSL_1_1_0h.tar.gz'
     dst='C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL/Source'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[ 37%] No patch step for 'OpenSSL'
[ 50%] No update step for 'OpenSSL'
[ 62%] Performing configure step for 'OpenSSL'
'.' nï¿½o ï¿½ reconhecido como um comando interno
ou externo, um programa operï¿½vel ou um arquivo em lotes.
mingw32-make.exe[5]: *** [CMakeFiles\OpenSSL.dir\build.make:109: OpenSSL-prefix/src/OpenSSL-stamp/OpenSSL-configure] Error 1
mingw32-make.exe[5]: Leaving directory 'C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL/Build'
mingw32-make.exe[4]: *** [CMakeFiles\Makefile2:67: CMakeFiles/OpenSSL.dir/all] Error 2
mingw32-make.exe[4]: Leaving directory 'C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL/Build'
mingw32-make.exe[3]: *** [Makefile:83: all] Error 2
mingw32-make.exe[3]: Leaving directory 'C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL/Build'

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/OpenSSL
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/projects/OpenSSL]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/modules/hunter_download.cmake:660 (hunter_fatal_error)
  C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/projects/OpenSSL/hunter.cmake:380 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:328 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/CMakeFiles/CMakeOutput.log".
mingw32-make.exe[2]: *** [CMakeFiles\CURL-Release.dir\build.make:109: CURL-Release-prefix/src/CURL-Release-stamp/CURL-Release-configure] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:67: CMakeFiles/CURL-Release.dir/all] Error 2
mingw32-make.exe: *** [Makefile:83: all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/44c5a98/4ec64c2/eb72dfe/Build/CURL
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/projects/CURL]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/modules/hunter_download.cmake:660 (hunter_fatal_error)
  C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/projects/CURL/hunter.cmake:81 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.20.42/44c5a98/Unpacked/cmake/modules/hunter_add_package.cmake:53 (include)
  CMakeLists.txt:15 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Marquinhos/mobagen/cmake-build-debug/CMakeFiles/CMakeOutput.log".

[Failed to reload]

**Comment by ruslo** [comment]
This issue will be closed because the required template file [ISSUE_TEMPLATE.md][1] was ignored. Please read and fill carefully all parts of this file while submitting a bug report.

Thanks for understanding.

[1]: https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE.md
