### ISSUE TITLE
Exceptions being disabled for dependencies

### ISSUE THREAD

**Issue by alamaison** [ruslo/hunter#142]
For some reason, in 0.10.1, dependencies are built with C++ exceptions support being turned off.

Reproducible using:
- Windows
- Visual Studio 2005
- Hunter 0.10.1

I don't know if other combinations have the same problem.

For example, a [simple project that depends on TIFF](https://github.com/alamaison/hunter-tiff-test).  The TIFF library contains one file that uses C++, `tif_stream.cxx`.  When building the sample project, you can see that exceptions have been disabled because of the [warnings that appear](http://pastebin.com/ESKKSPKt): 
```C:\Program Files (x86)\Microsoft Visual Studio 8\VC\include\xlocale(326) : w
arning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc```.  Unfortunately, the build succeeds (because Visual Studio thinks this is only worth a warning!) and poisons the cache with an unusable version of libtiff.  However, if you build the TIFF project itself using the latest Hunter (i.e. not as a dependency of another project) all works fine and exceptions are enabled.

I though this was being caused by the ABI failure issue (#121) but I can reproduce it even when ABI detection works.  In fact, it turns out that it doesn't matter on Windows if the ABI detection fails (at least not in the default configuration) because all the values are empty.

**Comment by alamaison** [comment]
Exceptions are also being disabled with Hunter 0.9.10

**Comment by alamaison** [comment]
The problem was introduced in Hunter 0.8.13.  Version 0.8.12 builds the example project correctly without the warnings for `tif_stream.cxx`.  0.8.13 doesn't.

**Comment by alamaison** [comment]
The cause is that `hunter_jobs_number`, introduced in 0.8.13, is destroying `CMAKE_CXX_FLAGS` and `CMAKE_C_FLAGS`.  In 0.8.13, `hunter_jobs_number` inserts the following into `toolchain.cmake` when using MSVC:
```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} /MP" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} /MP" CACHE STRING "" FORCE)
```
Although this looks ok, the result is that `CMakeCache.txt` changes from this (0.8.12):
```
//Flags used by the compiler during all build types.
CMAKE_CXX_FLAGS:STRING= /DWIN32 /D_WINDOWS /W3 /GR /EHsc

//Flags used by the compiler during all build types.
CMAKE_C_FLAGS:STRING= /DWIN32 /D_WINDOWS /W3
```
to this (0.8.13)
```
CMAKE_CXX_FLAGS:STRING= /MP /MP

CMAKE_C_FLAGS:STRING= /MP /MP
```
`/EHsc`, which is required to enable exceptions, is missing, along with other important flags.  Note, also, the lost comments which suggests that setting CMAKE_XXX_FLAGS in this way is not correct.

**Comment by alamaison** [comment]
I'm at a loss.  I tried to fix it by setting `CMAKE_CXX_FLAGS` locally, not in the cache.  But, because the toolchain is processed first, [CMake overrides that](https://github.com/Kitware/CMake/blob/master/Modules/CMakeCXXInformation.cmake#L205) with the contents of `CMAKE_CXX_FLAGS_INIT`.  I tried setting CMAKE_CXX_FLAGS_INIT, but [CMake overrides that too](https://github.com/Kitware/CMake/blob/master/Modules/Platform/Windows-MSVC.cmake#L294).  It seems the toolchain file is just the wrong place to set an option like this.

**Comment by ruslo** [comment]
This is weird, thanks for investigation

**Comment by ruslo** [comment]
TODO: try `/maxcpucount:N`

**Comment by ruslo** [comment]
> try /maxcpucount:N

Fixed: https://github.com/ruslo/hunter/commit/d3c75b28c076b247c02bfe66dcd2cd5873413e54
Related Polly `--jobs` change: https://github.com/ruslo/polly/commit/51670e440f00accbdb394403acd06c0721a805d9

Note that this works only for MSVC >= 12 2013 (at least 9 2008 don't have such option). And only for Visual Studio generators - no NMake support (`/MP` doesn't work for NMake too).
