### ISSUE TITLE
harfbuzz - text shaping library

### ISSUE THREAD

**Issue by jhs67** [ruslo/hunter#1423]
* I'm interested in package `harfbuzz`
* Here is official site of package http://harfbuzz.org/
* This package is using Git: https://github.com/harfbuzz/harfbuzz.git
* Official GitHub repository: https://github.com/harfbuzz/harfbuzz
* Used build system: CMake

* This package has these dependencies:
  * `freetype` (optional, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/freetype.html)
  * `ICU` (optional, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/ICU.html)

The cmake based build system requires some patching to install harfbuzzConfig.cmake and related files and to hunterize the optional dependencies. I've been working on these changes [here](https://github.com/jhs67/harfbuzz), but thought a project under hunter-packages might be better.

**Comment by ruslo** [comment]
> I've been working on these changes here, but thought a project under hunter-packages might be better.

See https://github.com/hunter-packages/harfbuzz

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/pull/1440
