### ISSUE TITLE
latest hunter version doesn't work for android-studio

### ISSUE THREAD

**Issue by dryganets** [ruslo/hunter#1459]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **[Yes]**
* I'm using latest Hunter URL/SHA1. **[Yes]**

* I've created SSCCE GitHub repository to reproduce the issue: https://github.com/dryganets/hunter-android-studio/tree/sergeyd/new-hunter-not-work-with-android-studio

you could check that master with default cmake works.
external-cmake branch works as well (upgrade to 3.11.2 alone).

log:

```
Android API (CMAKE_SYSTEM_VERSION)
Expected: `24`, `21`, `19`, `16`
Got: `1`"
```

Turns out boost resets CMAKE_SYSTEM_VERSION to 1
```
 ~/.hunter
11:49 $ ag CMAKE_SYSTEM_VERSION
_Base/a47baf7/4c741bc/e11a692/Build/Boost/Build/CMakeFiles/3.11.2/CMakeSystem.cmake
10:set(CMAKE_SYSTEM_VERSION "17.5.0")

_Base/a47baf7/99b5517/a69be9e/Build/Boost/__system/Build/CMakeFiles/3.6.0-rc2/CMakeSystem.cmake
10:set(CMAKE_SYSTEM_VERSION "1")

_Base/f91a01c/efc1666/5db38ea/Build/Boost/Build/CMakeFiles/3.11.2/CMakeSystem.cmake
10:set(CMAKE_SYSTEM_VERSION "1")

```

I've checked that the first error in logs **IS NOT** `external.build.failed`. **[Yes]**

* I'm building on [OSX| Android].
* [I'm using system CMake]
* CMake version: 3.11.2

* I'm using unmodified toolchain <toolchain-name> from [Polly](https://github.com/ruslo/polly)

I'm using next command line on generate step:
```
gradlew assembleDebug
```

**Comment by ruslo** [comment]
See this issue for starting with Android Studio:
* https://github.com/ruslo/hunter/issues/618#issuecomment-367532376

And this example for latest updates:
* https://github.com/forexample/android-studio-with-hunter
