### ISSUE TITLE
Boost cross compiling failed

### ISSUE THREAD

**Issue by CHChang810716** [ruslo/hunter#1467]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**

Hi, I'm trying to cross compiling the Boost to ARM target and it failed.

It seems Boost library requires to build the Boost build system and then build the source code, so it needs to identify host compiler and the target system compiler.

The question is how can I specify the host compiler to build Boost build system? 

---

**Comment by CHChang810716** [comment]
Here's the short log: 
```
[ 37%] No patch step for 'Boost'
[ 50%] Performing update step for 'Boost'
[ 62%] Performing configure step for 'Boost'
Dummy patch command
Building Boost.Build engine

Failed to build Boost.Build engine.
Please consult bootstrap.log for further diagnostics.

You can try to obtain a prebuilt binary from

   http://sf.net/project/showfiles.php?group_id=7586&package_id=72941

Also, you can file an issue at http://svn.boost.org
Please attach bootstrap.log in that case.
```

**Comment by ruslo** [comment]
Boost build scheme use `bootstrap.sh` without any arguments:
* https://github.com/ruslo/hunter/blob/90f1c32fbb04a246ff4aba4a66750ab817ac1e2f/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L336

> The question is how can I specify the host compiler to build Boost build system?

I don't know, do you know how to specify it without Hunter?

**Comment by CHChang810716** [comment]
I see.....
The host compiler is automatically detected by bootstrap.sh and then Hunter generate the user jam file to build the source code.

It seems everything works fine on Linux. 
The earlier fail built is from MinGW and maybe I misunderstood the fail reason.
I'll check the log and see what happened.

**Comment by ruslo** [comment]
Closing inactive discussion.
