### ISSUE TITLE
Add glslang

### ISSUE THREAD

**Issue by jhs67** [ruslo/hunter#1472]
* I'm interested in package `glslang`
* Here is official site of package https://github.com/KhronosGroup/glslang
* This package is using Git: https://github.com/KhronosGroup/glslang.git
* Used build system: CMake

* This package has no required dependencies

The cmake based build system will require some patching to install the config.cmake files, so a hunter-packages fork is probably appropriate.

**Comment by ruslo** [comment]
> The cmake based build system will require some patching to install the config.cmake files, so a hunter-packages fork is probably appropriate.

https://github.com/hunter-packages/glslang

**Comment by xsacha** [comment]
Fixed by https://github.com/ruslo/hunter/pull/1475
