### ISSUE TITLE
Tests won't compile anymore

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#1478]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **[nA]**
* I'm using latest Hunter URL/SHA1. **[Yes]**

Since the latest restructure of `hunter_config` and `hunter_default_version` some tests don't compile anymore. Affected tests

- issue/22
- issue/24/unit
- simple
For the three mentioned the following error is output
```
[hunter ** FATAL ERROR **] Unexpected 'hunter_config' usage from:
[hunter ** FATAL ERROR **]  tests/simple/CMakeLists.txt:32
[hunter ** FATAL ERROR **] [Directory:tests/simple]
```

- issue/109/unit
```
[hunter ** INTERNAL **] Unexpected empty string
[hunter ** INTERNAL **] [Directory:tests/issue/109/unit]
```

Why are the regression tests not run anymore? Do they take too much time?

**Comment by ruslo** [comment]
> issue/22
> issue/24/unit
> simple

I've added it to my local TODO list after changing the format of Config-ID.

> Why are the regression tests not run anymore? Do they take too much time?

In most cases those tests are quite useless.

**Comment by NeroBurner** [comment]
fixed the tests:

- https://github.com/ruslo/hunter/pull/1563
- https://github.com/ruslo/hunter/pull/1564
- https://github.com/ruslo/hunter/pull/1565

**Comment by ruslo** [comment]
> fixed the tests

Merged, thanks!

**Comment by NeroBurner** [comment]
you're welcome :)

shall we re-enable the tests or let them rot, as they "are quite useless"?

**Comment by ruslo** [comment]
> shall we re-enable the tests or let them rot, as they "are quite useless"?

I don't see the problem about keeping them, rotting is not a requirement :) I just don't see the point of running them for every pull request. Most of the pull requests are about documentation (that's what is currently tested by CI) or package updates/new packages (tested by `ingenue/ci/pkg.N`).
