### ISSUE TITLE
Add termcolor

### ISSUE THREAD

**Issue by thomassuckow** [ruslo/hunter#1482]
* I'm interested in package `termcolor`
* Here is official site of package https://github.com/ikalnytskyi/termcolor

* This package is using Git: https://github.com/ikalnytskyi/termcolor.git

* Official GitHub repository:  https://github.com/ikalnytskyi/termcolor

* Used build system: Cmake (for tests)

* This package has no dependencies

---

**Comment by norbertwenzel** [comment]
Released in https://github.com/ruslo/hunter/releases/tag/v0.23.39
@ruslo Can be closed.

**Comment by ruslo** [comment]
Fixed by https://github.com/ruslo/hunter/pull/1601 @norbertwenzel Thanks!
