### ISSUE TITLE
How to start for iOS?

### ISSUE THREAD

**Issue by zhouhao27** [ruslo/hunter#1493]
I'm planing to compile a C++ library for iOS. Where to start? Is there any tutorial for this? Thanks.

For example, I want to build this for iOS:

> https://github.com/openalpr/openalpr

**Comment by ruslo** [comment]
The question is mostly about choosing and using iOS toolchain. Closing for https://github.com/ruslo/polly/issues/263

**Comment by zhouhao27** [comment]
@ruslo Thanks for your reply. What's the difference between Polly and Hunter?

**Comment by zhouhao27** [comment]
Sorry, I understand now. It seems the hunger is ready make cmake files for third party libraries. Thanks.

**Comment by ruslo** [comment]
> hunger

Hunter
