### ISSUE TITLE
error at cmake/HunterGate.cmake:83

### ISSUE THREAD

**Issue by stray128** [ruslo/hunter#1504]
Cannot configure the project in the directory Build
`cmake ..`
gives the following error:
-- [cable ] Cable 0.2.3 initialized 
-- [hunter] Initializing Hunter workspace (aa1faccd24f33dd2c368f85a4e9ca2e5d9c249cb) 
-- [hunter] https://github.com/ruslo/hunter/archive/v0.21.16.tar.gz 
-- [hunter] -> C:/.hunter/_Base/Download/Hunter/0.21.16/aa1facc 
The system cannot find the file specified 
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/nologo" 
[hunter ** INTERNAL **] Build project failed 
[hunter ** INTERNAL **] [Directory:C:/Users/Ashwith Basani/cpp-ethereum] 
------------------------------ WIKI ------------------------------- https://github.com/ruslo/hunter/wiki/error.internal 
------------------------------------------------------------------- 
CMake Error at cmake/HunterGate.cmake:83 (message): 
Call Stack (most recent call first):
 cmake/HunterGate.cmake:93 (hunter_gate_wiki) 
cmake/HunterGate.cmake:349 (hunter_gate_internal_error) 
cmake/HunterGate.cmake:513 (hunter_gate_download) 
CMakeLists.txt:43 (HunterGate)

**Comment by ruslo** [comment]
This issue will be closed because the required template file [ISSUE_TEMPLATE.md][1] was ignored. Please read and fill carefully all parts of this file while submitting a bug report.

Thanks for understanding.

[1]: https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE.md
