### ISSUE TITLE
Add "ctti" package

### ISSUE THREAD

**Issue by caseymcc** [ruslo/hunter#1516]
* I'm interested in package `ctti`
* Here is official site of package https://github.com/Manu343726/ctti
* This package is using [Git]: https://github.com/Manu343726/ctti.git
* Official GitHub repository: https://github.com/Manu343726/ctti
* Used build system: [CMake]
* This package has no dependencies

I have the package ready, had to add cmake install to the cmake config. I sent a PR for the changes (and bug fixes) but have not heard anything also the project has not created a release in a long time although there has been development all the way up till now. For the short term I think I would like to set it up on hunter-packages and if they take the PRs and create a release then I will change back to the upstream repo.

**Comment by ruslo** [comment]
> For the short term I think I would like to set it up on hunter-packages and if they take the PRs and create a release then I will change back to the upstream repo

Done: https://github.com/hunter-packages/ctti

**Comment by ruslo** [comment]
https://docs.hunter.sh/en/latest/packages/pkg/ctti.html
