### ISSUE TITLE
Runtime error of Qt5 app on Windows 7

### ISSUE THREAD

**Issue by giraldeau** [ruslo/hunter#1517]
* Building on Windows 7 using MSVC 2015
* Using CMake 3.10.2 from MSYS2

```
cd hunter/examples/qt-core/
cmake -G "Visual Studio 14 2015" .
Debug\helloworld.exe
```

Problem: The qt-core app compiles correcly, but fails at runtime, complaining about missing system DLLs, such as `api-ms-win-core-debug-l1-1-1.dll`. 

I've pinpointed the origin of the problem which is related to linking to `Mincore.lib`. The [Microsoft docs](https://docs.microsoft.com/en-us/windows/desktop/apiindex/windows-8-api-sets) states: 

> Compatibility with Windows 7, Windows Server 2008 R2 and older operating systems: Binaries that link to MinCore.lib or MinCore_Downlevel.lib are not designed to work on Windows 7, Windows Server 2008 R2 or earlier. Binaries that need to run on earlier versions of Windows or Windows Server must not use either MinCore.lib or MinCore_Downlevel.lib.

Replacing the library `Mincore` by `Netapi32` and `Userenv` in `Qt5Core_HunterPlugin.cmake` fixes this issue:

```diff
diff --git a/Qt5Core_HunterPlugin.cmake.orig b/Qt5Core_HunterPlugin.cmake
index ed6f700..1ec9e2f 100644
--- a/Qt5Core_HunterPlugin.cmake.orig
+++ b/Qt5Core_HunterPlugin.cmake
@@ -78,7 +78,12 @@ elseif(MSVC)
 
   # defined: '_GetFileVersionInfoSizeW'
   _qt_cmake_extra_helpers_add_interface(Qt5::Core Version)
-  _qt_cmake_extra_helpers_add_interface(Qt5::Core Mincore)
+
+  # defined: 'NetShareEnum'
+  _qt_cmake_extra_helpers_add_interface(Qt5::Core Netapi32)
+
+  # defined: '__imp__GetUserProfileDirectoryW'
+  _qt_cmake_extra_helpers_add_interface(Qt5::Core Userenv)
 
   # defined: '__imp__timeSetEvent'
   _qt_cmake_extra_helpers_add_interface(Qt5::Core Winmm)
```

More generally, I compiled a small UI project using qmake and this is the list of Windows system libraries it links to: 

```
advapi32.lib
comdlg32.lib
d3d9.lib
dwmapi.lib
dxguid.lib
gdi32.lib
imm32.lib
kernel32.lib
mpr.lib
netapi32.lib
ole32.lib
oleaut32.lib
shell32.lib
shlwapi.lib
user32.lib
userenv.lib
uuid.lib
uxtheme.lib
version.lib
winmm.lib
winspool.lib
ws2_32.lib
```

These libraries are scattered in `.pri` and `qtbase/mkspecs/common/msvc-desktop.conf` files, which is somewhat annoying. I'm a bit worried that if one of these library is missing, then it will fail at link time, but at least there is a simple workarround to [add libraries to the INTERFACE_LINK_LIBRARIES property](https://stackoverflow.com/questions/32010314/qt5-5-how-can-i-include-qts-qtpcre-lib-and-qtharfbuzzng-lib-with-cmake#32016976).

I wanted to submit a PR for the change, but I cannot find the `Qt5Core_HunterPlugin.cmake` sources or template. I don't mind to do it if I know the location of the file. Thanks!

**Comment by ruslo** [comment]
>  I cannot find the Qt5Core_HunterPlugin.cmake sources or template

There is a small package with extra CMake modules for appliying Qt+CMake integration issues. Please check this repo: https://github.com/hunter-packages/QtCMakeExtra

**Comment by ruslo** [comment]
Closing inactive issue with "Broken package" label, see details:
* https://github.com/ruslo/hunter/wiki/error.external.build.failed
