### ISSUE TITLE
Pull changes from CppNetlibUri 1.0.1

### ISSUE THREAD

**Issue by chfast** [ruslo/hunter#1519]
* I'm interested in upgrading  package `CppNetlibUri` to version 1.0.1
* Here is official site of package https://github.com/cpp-netlib/uri

* This package is using [Git]: https://github.com/cpp-netlib/uri

* Official GitHub repository: https://github.com/cpp-netlib/uri

* Used build system: [CMake]

* Hunter support: https://github.com/hunter-packages/uri

* This package has next dependencies:

  * `Boost (required, available in Hunter)

There were small changes and fixes release in upstream CppNetlibUri as 1.0.1. Merging them back to hunterized repo is not easy as CMake scripts are quite different. There is also version collision with 1.0.0-hunter.

**Comment by ruslo** [comment]
Closing inactive issue with "Broken package" label, see details:
* https://docs.hunter.sh/en/latest/reference/errors/error.external.build.failed.html#what-to-do
