### ISSUE TITLE
Is there a way to pass CXXFLAGS to build of 3p libraries?

### ISSUE THREAD

**Issue by aadityakalsi** [ruslo/hunter#152]
I'm in a situation where I want boost libraries (both static and shared version) to be built with ```-fPIC```.

Is there a way to pass this information to Hunter?

**Comment by aadityakalsi** [comment]
Setting CMAKE_CXX_FLAGS before running ```hunter_add_package``` solves this.

**Comment by aadityakalsi** [comment]
That does not actually work. @ruslo Is there something I'm missing?

**Comment by aadityakalsi** [comment]
Trying local ```config.cmake```

**Comment by aadityakalsi** [comment]
That worked!

**Comment by ruslo** [comment]
By design I think you need to set it in toolchain. Toolchain with `-fPIC` and without has different `toolchain-id`

**Comment by aadityakalsi** [comment]
I find that adding it to your local config.cmake works well for me. Each package can be configured as per needs and that goves it a different ```config-id```.

By the way, how do we get different toolvhains with Hunter? Do we have to sync Polly separately and add?

**Comment by ruslo** [comment]
> I find that adding it to your local config.cmake works well for me. Each package can be configured as per needs and that goves it a different config-id

In this case I think it's not a problem. Also see:
* [HUNTER_POSITION_INDEPENDENT_CODE](https://github.com/ruslo/hunter/issues/64)

But in some cases you can break compatibility, e.g. if you set `-stdlib=libc++` to one 3rd party library and `-stdlib=libstdc++` to another. Such flags must be set in toolchain and result different toolchain-id.

Related:
* [Toolchain-id examples](https://github.com/ruslo/hunter/issues/32)

> By the way, how do we get different toolvhains with Hunter? Do we have to sync Polly separately and add?

For now yes. You need to create toolchain yourself. You can do it using Polly or manually by `-DCMAKE_TOOLCHAIN_FILE`. This can be improved in future:
* [Builtin toolchains](https://github.com/ruslo/hunter/issues/150)

**Comment by truedat101** [comment]
> That worked!

@aadityakalsi sorry for the old/late reply on this, but what was your fix in the config.cmake?  I'm sorting through this particular problem on freetype and will revisit later the approach of toolchain files, but just need something to get the build to complete.

**Comment by akalsi87** [comment]
Having a local config.cmake and passing CMAKE_CXX_FLAGS for Unix GCC and Clang.
