### ISSUE TITLE
Boost CMAKE_ARGS user macro no longer work

### ISSUE THREAD

**Issue by PyrO70** [ruslo/hunter#1525]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **Yes**
* I'm using latest Hunter URL/SHA1. **Yes**

I have used the boost configuration functionally as described in [Boost - CMake Options](https://docs.hunter.sh/en/latest/packages/pkg/Boost.html) with **Hunter v0.20.13**. Moving to the lastest **Hunter v0.23.17**, the `CONFIG_MACRO` in the `CMAKE_ARGS` seems to be ignored.

I have managed to reproduced the issue with a newly checked-out Hunter repository using `example/boost/` setting the `TESTING_CONFIG_OPT` to a file containing the example macro from the  [Boost - CMake Options](https://docs.hunter.sh/en/latest/packages/pkg/Boost.html) and checking the created `boost/config/user.hpp` file, which didn't have the additional macros.

I have then checked the generated file from the boost scheme in `append-boost-config-macros.cmake` which is called at update time by the `externalproject_add` command. The `foreach` loop that is supposed to write each macro into `boost/config/user.hpp` is missing its arguments, meaning when the file was configured the variable containing the list of macro is empty.

I have not been able to track down where that variable is created, or when that file is configured by lack of time. 

I have double checked the same steps in a checkout of **Hunter v0.20.13**, to make sure that the steps actually worked and checked the `boost/config/user.hpp`, which indeed properly contains the macros.

* I've created SSCCE reproducing the issue:

```cmake
# example/boost/CMakeLists.txt
# before include(../common.cmake)
set(TESTING_CONFIG_OPT FILEPATH ${CMAKE_CURRENT_LIST_DIR}/config.cmake)
```

```cmake
# example/boost/config.cmake
# this is taken from the Hunter documentation
hunter_config(Boost VERSION ${HUNTER_Boost_VERSION} CMAKE_ARGS
    CONFIG_MACRO=BOOST_REGEX_MATCH_EXTRA;BOOST_MPL_CFG_NO_PREPROCESSED_HEADERS
    CONFIG_MACRO_BOOST_MPL_LIMIT_LIST_SIZE=3
)
```
**_NOTE: There is an error in the documentation where the `hunter_config` call is missing the `VERSION` property just before `${HUNTER_Boost_VERSION}`_**

I've checked that the first error in logs **IS NOT** `external.build.failed`. **Yes**

* I'm building on Linux.
* I'm using official CMake release
* CMake version: **3.11.0**

* I'm using unmodified toolchain **gcc-7-cxx14-pic** from [Polly](https://github.com/ruslo/polly)_, not sure it is relevant for this issue, but that is the one it tried with_

**Comment by ruslo** [comment]
I'm testing a fix. Boost testing may take some time so you can use this temporary archive to check that fix will work for you:
```cmake
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/7aa2edb32825445be6f766ab1e4e10788aafa8cf.zip"
    SHA1 "6e9dae26e66fa5afec0a54d74887130d3f46f939"
)
```

**Comment by PyrO70** [comment]
Perfect, I can see the #define's added to `config/user.hpp`. Thanks.

Do you want me to file a bug for the documentation too? (missing `VERSION`) or you already noted that?

**Comment by ruslo** [comment]
> Do you want me to file a bug for the documentation too? (missing VERSION) or you already noted that?

I have fixed it already: https://docs.hunter.sh/en/latest/packages/pkg/Boost.html#cmake-options

In general I prefer pull request since this one was trivial :)

**Comment by ruslo** [comment]
> I have used the boost configuration functionally as described in Boost -
> CMake Options with Hunter v0.20.13. Moving to the lastest Hunter v0.23.17,
> the CONFIG_MACRO in the CMAKE_ARGS seems to be ignored

I missed this part while doing refactoring in v0.22: https://docs.hunter.sh/en/latest/reference/release-notes/v0/v0.22.html
Boost seems to be the only package that use this feature, usually build scheme check
particular arguments like `if(SOME_OPTION)` and not the list of all arguments.

> I have managed to reproduced the issue with a newly checked-out Hunter
> repository using example/boost/ setting the TESTING_CONFIG_OPT to a file
> containing the example macro

There is an example to test this: https://github.com/ruslo/hunter/tree/master/examples/Boost-custom-args

But it was not added to CI config, now it's part of the testing: https://github.com/ingenue/hunter/commit/5b996e232abed99b14d462adb600f6925f873636#diff-354f30a63fb0907d4ad57269548329e3

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.19

**Comment by PyrO70** [comment]
Thanks you. All good.
