### ISSUE TITLE
OpenBLAS on mobile failed

### ISSUE THREAD

**Issue by tonyrewin** [ruslo/hunter#1536]
iOS build script resetting all env vars, so required by openBLAS TARGET var is missed, steps to reproduce:
```sh
export TARGET=ARMV8
polly.py --toolchain ios-nocodesign --verbose --config Release
..
CMake Error at cmake/system.cmake:17 (message):
  When cross compiling, a TARGET is required.
Call Stack (most recent call first):
  CMakeLists.txt:44 (include)
```

...and Android need to be synced with [this](https://github.com/xianyi/OpenBLAS/wiki/How-to-build-OpenBLAS-for-Android) instruction:
```log
-- Targeting the ARMV8 architecture.
-- GEMM multithread threshold set to 4.
-- The Fortran compiler identification is unknown
CMake Error at cmake/f_check.cmake:24 (enable_language):
  No CMAKE_Fortran_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "FC" or the CMake cache entry CMAKE_Fortran_COMPILER to the full
  path to the compiler, or to the compiler name if it is in the PATH.
Call Stack (most recent call first):
  cmake/prebuild.cmake:84 (include)
  cmake/system.cmake:122 (include)
  CMakeLists.txt:44 (include)
```

**Comment by tonyrewin** [comment]
```cmake
if(ANDROID)
  set(NOFORTRAN 1) # FIXME
  set(ARM_SOFTFP_ABI 1) 
..
```
adding this to [hunter-packages/OpenBLAS/CmakeLists.txt](https://github.com/hunter-packages/OpenBLAS/blob/hunter-0.3.2/CMakeLists.txt) did not take effect... not sure where to apply a fix: to hunter's common logic or to openblas package _hunterizaton_-scrpits script in both of cases (ios and android).

**Comment by ruslo** [comment]
> to openblas package hunterizaton-scrpits

What is it? :)

> not sure where to apply a fix

Current default version of OpenBLAS is upstream without any extra patches:
* https://github.com/ruslo/hunter/blob/305e1831180a1f80128c5f0e9a0e10b8b928342b/cmake/projects/OpenBLAS/hunter.cmake#L14-L23

If you have any fixes of OpenBLAS please send them to https://github.com/xianyi/OpenBLAS

**Comment by xsacha** [comment]
TARGET should be handled internally in the CMake.

Also, NOFORTRAN is the default setting:
https://github.com/ruslo/hunter/blob/master/cmake/projects/OpenBLAS/hunter.cmake#L81

**Comment by xsacha** [comment]
By the way, any package that has a dependency on BLAS should be using the Accelerate framework on iOS rather than OpenBLAS. It seems superior in performance and requires no compilation.

**Comment by ruslo** [comment]
Closing inactive issue with "Broken package" label, see details:
* https://docs.hunter.sh/en/latest/reference/errors/error.external.build.failed.html#what-to-do
