### ISSUE TITLE
different .hunter cache default paths per generator on Windows

### ISSUE THREAD

**Issue by mchiasson** [ruslo/hunter#1537]
Without specifying the hunter cache folder location, if you generate your cmake build location for visual studio, it goes by default into the `C:\Users\<username>\.hunter` folder.  However, if we generate for nmake makefiles, it goes by default into the `C:\.hunter` folder.

**Comment by mchiasson** [comment]
it's pretty minor, but it makes it cumbersome to remember that you need to clean up 2 places when it's time to free some hard disk space after using hunter for many years.

**Comment by ruslo** [comment]
I can't reproduce it, for me it's a `C:\.hunter` (`%SYSTEMDRIVE%\.hunter`) for both generators. Can you add the logs with `HUNTER_STATUS_DEBUG=ON` enabled?

**Comment by ruslo** [comment]
Closing inactive discussion.
