### ISSUE TITLE
Failure with Webkit package

### ISSUE THREAD

**Issue by acabarbaye** [ruslo/hunter#1541]
I am trying to compile my Android native library with JavaScriptCore and hence used the webkit package.
However, I keep getting the following error and cannot figure out why:
```
/usr/bin/make -f CMakeFiles/ICU-Release.dir/build.make CMakeFiles/ICU-Release.dir/build
make[2]: Entering directory '/home/user/.hunter/_Base/cb75cce/7f32107/da2354d/Build/ICU/Build'

make[2]: Entering directory '/home/user/.hunter/_Base/cb75cce/7f32107/da2354d/Build/ICU/Build'

> Task :project:generateJsonModelDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':project:generateJsonModelDebug'.
> Conversion = ']'

```
I run hunter with the debug flag and here are the logs I get: [logsWebkit.txt](https://github.com/ruslo/hunter/files/2362083/logsWebkit.txt). I also use other 3rd party tools such as protocol buffer or boost in my project which are imported correctly and therefore, do not understand what the cause of this problem.

---- 
# Environment:
For the toolchain, I have set up my project following this example: https://docs.hunter.sh/en/latest/faq/android-studio.html
cmake version 3.12.1

## Cpp flags
`cppFlags "-std=c++14 -frtti -fexceptions"`

## Project setup
```
if(ANDROID_STUDIO)
  set(gen_toolchain "${CMAKE_CURRENT_BINARY_DIR}/generated/toolchain.cmake")
  file(TO_CMAKE_PATH "${CMAKE_TOOLCHAIN_FILE}" CMAKE_TOOLCHAIN_FILE_CMAKE_PATH)
  configure_file(
      "${CMAKE_CURRENT_LIST_DIR}/cmake/template/toolchain.cmake.in"
      "${gen_toolchain}"
      @ONLY
  )
  set(CMAKE_TOOLCHAIN_FILE "${gen_toolchain}" CACHE PATH "" FORCE)
endif()

include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.25.tar.gz"
    SHA1 "cb75cce9a3a8d552e70e7118f3203eb4ac05c201"
)
hunter_add_package(WebKit)
find_package(WebKit CONFIG REQUIRED)
```

## Android
> compileSdkVersion 28
> minSdkVersion 21
> targetSdkVersion 28
> versionCode 1
> versionName "1.0"

**Comment by acabarbaye** [comment]
[Full logs](https://github.com/ruslo/hunter/files/2362262/log-webkit.txt)

**Comment by ruslo** [comment]
```
* What went wrong:
Execution failed for task ':project:generateJsonModelDebug'.
> Conversion = ']'
```
Sounds like a Gradle issue, you can report it to https://issuetracker.google.com

> For the toolchain, I have set up my project following this example: https://docs.hunter.sh/en/latest/faq/android-studio.html

As a workaround you can try to run CMake build directly without Gradle, see "you can add return() command right after first hunter_add_package" part.

**Comment by acabarbaye** [comment]
I ran gradle with `return()`

```
hunter_add_package(WebKit)
return() # Early exit
find_package(WebKit CONFIG REQUIRED)
```
But I get exactly the same error i.e. `Entering directory ... ICU ... Failed ... Conversion = ']'`

**Comment by ruslo** [comment]
Try another package, something smaller, e.g.:
```cmake
hunter_add_package(md5)
return() # Early exit
```

**Comment by acabarbaye** [comment]
I tried with the example app:
https://github.com/forexample/android-studio-with-hunter
As is, when running `gradle build` it works fine. 
However, when adding the `Webkit` package it fails with the following error:

```
  [hunter *** DEBUG *** 2018-09-11T16:42:41] Configure step successful (dir: /home/user/.hunter/_Base/2c42191/8b6b412/a859b8f/Build/WebKit)
  [hunter *** DEBUG *** 2018-09-11T16:42:41] [/home/user/.hunter/_Base/2c42191/8b6b412/a859b8f/Build/WebKit] > "/home/user/bin/cmake" "--build" "/home/user/.hunter/_Base/2c42191/8b6b412/a859b8f/Build/WebKit/Build"
  [hunter ** FATAL ERROR **] Build step failed (dir: /home/user/.hunter/_Base/2c42191/8b6b412/a859b8f/Build/WebKit
  [hunter ** FATAL ERROR **] [Directory:/home/user/.hunter/_Base/Download/Hunter/0.23.3/2c42191/Unpacked/cmake/projects/WebKit]
  ------------------------------ WIKI -------------------------------
      https://github.com/ruslo/hunter/wiki/error.external.build.failed
  -------------------------------------------------------------------
  CMake Error at /home/user/.hunter/_Base/Download/Hunter/0.23.3/2c42191/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
  Call Stack (most recent call first):
    /home/user/.hunter/_Base/Download/Hunter/0.23.3/2c42191/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
    /home/user/.hunter/_Base/Download/Hunter/0.23.3/2c42191/Unpacked/cmake/modules/hunter_download.cmake:608 (hunter_fatal_error)
    /home/user/.hunter/_Base/Download/Hunter/0.23.3/2c42191/Unpacked/cmake/projects/WebKit/hunter.cmake:51 (hunter_download)
    /home/user/.hunter/_Base/Download/Hunter/0.23.3/2c42191/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
    CMakeLists.txt:44 (hunter_add_package)


  Configuring incomplete, errors occurred!
  See also "/home/user/android-studio-with-hunter/android-studio/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
```

The return() workaround does not solve the problem. It does not seem to be a problem with gradle or my android environment. Otherwise, I would assume the problem would be the same with md5 package

Below is the CMake file I use

```
# Android NDK r16 support:
# * https://gitlab.kitware.com/cmake/cmake/issues/17253
cmake_minimum_required(VERSION 3.9.2)

# For Android Studio we will force generated toolchain
if(HELLOJNI_ANDROID_STUDIO)
  set(gen_toolchain "${CMAKE_CURRENT_BINARY_DIR}/generated/toolchain.cmake")
  file(TO_CMAKE_PATH "${CMAKE_TOOLCHAIN_FILE}" CMAKE_TOOLCHAIN_FILE_CMAKE_PATH)
  configure_file(
      "${CMAKE_CURRENT_LIST_DIR}/cmake/template/toolchain.cmake.in"
      "${gen_toolchain}"
      @ONLY
  )
  set(CMAKE_TOOLCHAIN_FILE "${gen_toolchain}" CACHE PATH "" FORCE)
endif()

# Example of stepping into external sources.
# USE CAREFULLY, please check documentation:
# * https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-keep-package-sources
option(HUNTER_KEEP_PACKAGE_SOURCES "Keep third party sources" ON)

option(HUNTER_STATUS_DEBUG "Print debug info" ON)

include(cmake/HunterGate.cmake)
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.25.tar.gz"
    SHA1 "cb75cce9a3a8d552e70e7118f3203eb4ac05c201"
)

project(hello-jni)

option(CMAKE_VERBOSE_MAKEFILE "Verbose makefile" ON)

add_library(hello-jni SHARED hello-jni.cpp)

# If CMAKE_DEBUG_POSTFIX is emtpy Hunter will initialize with 'd'.
# We have to explicitly set DEBUG_POSTFIX to simplify library
# load from Java code.
set_target_properties(hello-jni PROPERTIES DEBUG_POSTFIX "")

# https://docs.hunter.sh/en/latest/packages/pkg/md5.html
hunter_add_package(md5)
find_package(md5 CONFIG REQUIRED)
hunter_add_package(WebKit)
return()
find_package(WebKit CONFIG REQUIRED)


target_link_libraries(hello-jni
		      PUBLIC
		      md5::md5
#	              WebKit::JavaScriptCore
#		      WebKit::WTF
 		     )





```

**Comment by ruslo** [comment]
> It does not seem to be a problem with gradle or my android environment.

The error is different, as you can see there is no `> Conversion = ']'` error message.

>  [hunter ** FATAL ERROR **] Build step failed (dir: /home/user/.hunter/_Base/2c42191/8b6b412/a859b8f/Build/WebKit

I do expect more logs on this error, like compiler error messages. There seems to be WebKit build problems.

> Below is the CMake file I use
>     URL "https://github.com/ruslo/hunter/archive/v0.23.25.tar.gz"

> CMake Error at /home/user/.hunter/_Base/Download/Hunter/0.23.3

The versions of Hunter are not the same.

**Comment by acabarbaye** [comment]
Hello @ruslo,

I realised I was not that clear on my last message.
Basically, I wanted to discover if the problem was due to my environment (gradle, cmake, etc.) or if it was a problem with the `Webkit` package. Therefore, I wanted to be sure the problem was not coming from my project and hence, tried to use Hunter with the Android example (https://github.com/forexample/android-studio-with-hunter) in which I tried to add a dependency on `Webkit` package. I then realised that the example was using quite an old version of gradle, android plugin and Hunter and hence, wanted to see if the latest versions would solved the problem. As you rightly noticed, I enclosed in my message the wrong logs and not the one corresponding to my last attempt.
The summary of what happens is as follows:
- when there is only a dependency on `md5`, build goes through successfully
- when the dependency on `webkit` is added, the build fails with attached logs.
[logswebkit.txt](https://github.com/ruslo/hunter/files/2375339/logswebkit.txt)
------------------------------------------------------------

Environment and project setup in use:
[CMakeList.txt](https://github.com/ruslo/hunter/files/2375381/CMakeList.txt)

`
Gradle 4.10
Build time:   2018-08-27 18:35:06 UTC
Revision:     ee3751ed9f2034effc1f0072c2b2ee74b5dce67d

Kotlin DSL:   1.0-rc-3
Kotlin:       1.2.60
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_181 (Azul Systems, Inc. 25.181-b02)
OS:           Linux 4.15.0-34-generic amd64

Android gradle plugin version: 'com.android.tools.build:gradle:3.3.+'
compileSdkVersion 28
minSdkVersion 21
targetSdkVersion 28
versionCode 1
 versionName "1.0"
`

**Comment by ruslo** [comment]
> I then realised that the example was using quite an old version of gradle, android plugin and Hunter

Feel free to send a pull request with updates, everything should work fine.

> when the dependency on webkit is added, the build fails with attached logs.  logswebkit.txt

WebKit build failed

> The error happens much quicker than it used to and the following seems to suggest an issue with the package

You mean `File not found`/`Cache miss` messages? This one is not critical, it means that there is no binaries on server and we have to build package from sources.

The real error is here:
```
[hunter *** DEBUG *** 2018-09-12T14:27:38] [/home/user/.hunter/_Base/224d85d/1275c0c/643d544/Build/WebKit] > "/home/user/bin/cmake" "--build" "/home/user/.hunter/_Base/224d85d/1275c0c/643d544/Build/WebKit/Build"
[hunter ** FATAL ERROR **] Build step failed (dir: /home/user/.hunter/_Base/224d85d/1275c0c/643d544/Build/WebKit
[hunter ** FATAL ERROR **] [Directory:/home/user/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/projects/WebKit]
------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------
```

As I said before it's strange that there is no other logs here, I do expect some compiler output and compiler error messages. Since it's a CMake-based package you can dive even deeper into internals and run this `cmake --build`:

```
> cd /home/user/.hunter/_Base/224d85d/1275c0c/643d544/Build/WebKit
> "/home/user/bin/cmake" "--build" "/home/user/.hunter/_Base/224d85d/1275c0c/643d544/Build/WebKit/Build"
```

**Comment by acabarbaye** [comment]
I run `cmake --build "/home/user/.hunter/_Base/224d85d/1275c0c/643d544/Build/WebKit/Build"`
and this is what I get:
-- [hunter *** DEBUG *** 2018-09-13T15:01:42] Secondary HunterGate (use old settings)
-- [hunter *** DEBUG *** 2018-09-13T15:01:42] Settings (initialize):
-- [hunter *** DEBUG *** 2018-09-13T15:01:42]   HunterGate done (YES)
-- [hunter *** DEBUG *** 2018-09-13T15:01:42]   Cache init (YES)
-- Android: Targeting API '21' with architecture 'arm', ABI 'armeabi-v7a', and processor 'armv7-a'
-- Android: Selected Clang toolchain 'arm-linux-androideabi-clang' with GCC toolchain 'arm-linux-androideabi-4.9'
-- The ASM compiler identification is Clang
-- Found assembler: /home/user/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/user/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /home/user/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/user/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /home/user/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for elf.h
-- Looking for elf.h - found
-- [hunter]
************************* !!! WARNING !!! *************************

You're using experimental feature. This may not work well
and can be removed anytime. It's a workaround for existing
feature request:

https://github.com/ruslo/hunter/issues/495

*******************************************************************
-- [hunter] Building host project: /home/user/.hunter/_Base/224d85d/1275c0c/643d544/Build/ICU/Source/source/data/cmake/host
-- [hunter *** DEBUG *** 2018-09-13T15:01:43] Using default host generator
-- [hunter *** DEBUG *** 2018-09-13T15:01:43] HUNTER_ROOT detected by cmake variable
-- [hunter *** DEBUG *** 2018-09-13T15:01:43] HUNTER_ROOT: /home/user/.hunter
-- [hunter *** DEBUG *** 2018-09-13T15:01:43] Settings (initialize):
-- [hunter *** DEBUG *** 2018-09-13T15:01:43]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2018-09-13T15:01:43]   Cache init (NO)
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
See also "/home/user/.hunter/_Base/224d85d/1275c0c/643d544/Build/ICU/Build/ICU-Release-prefix/src/ICU-Release-build/source/data/_3rdParty/Hunter/host-build-binary-tree/cmake/host/CMakeFiles/CMakeOutput.log".

**Comment by ruslo** [comment]
>  CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles". CMAKE_MAKE_PROGRAM is not set. You probably need to select a different build tool.

What is the result of running `which make`?

**Comment by ruslo** [comment]
> But should not it try to use the tools from the Android toolchain?

In general no since we are building package for host (e.g. x86_64) and not for Android (e.g. armv7). In practice the setting of host generator to target generator may work I guess. Need to think about exotic cases and test them if you want to introduce this feature.

> nothing. It seems that I don't have a make program in the path

Can you try to install it?

**Comment by acabarbaye** [comment]
I installed all the packages needed to build [Android on Ubuntu](https://source.android.com/setup/build/initializing#installing-required-packages-ubuntu-1404) as listed here:
`sudo apt-get install git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev libxml2-utils xsltproc unzip`
The whole build went through.

**Comment by acabarbaye** [comment]
the build goes though and libWTF.a and libJavaScriptCore.a are created. However, I then get problems during linking in my project with symbols not being found due to the following error:
`nm -gC /home/user/.hunter/_Base/224d85d/a9c8684/edaf3f0/Install/lib/libJavaScriptCore.a
nm: /home/user/.hunter/_Base/224d85d/a9c8684/edaf3f0/Install/lib/libJavaScriptCore.a: Malformed archive
`
`nm -gC /home/user/.hunter/_Base/224d85d/a9c8684/edaf3f0/Install/lib/libWTF.a
nm: /home/user/.hunter/_Base/224d85d/a9c8684/edaf3f0/Install/lib/libWTF.a: Malformed archive
`

Md5 module for instance produced valid libraries:
`nm -gC /home/user/.hunter/_Base/224d85d/a9c8684/edaf3f0/Install/lib/libmd5d.a

md5.c.o:
0000000000000000 T md5_append
0000000000000000 T md5_finish
0000000000000000 T md5_init
0000000000000000 T md5_process
                 U memcpy
                 U __stack_chk_fail
`

**Comment by ruslo** [comment]
> However, I then get problems during linking in my project with symbols not being found due to the following error

I'm not an active user of the WebKit so I can't give you any advice, please check build instructions and try to find something suspicious.

Note that in the WebKit example there are no symbols really used:
* https://github.com/ruslo/hunter/blob/v0.23.27/examples/WebKit/boo.cpp#L1-L4

Feel free to update the example to reproduce the error.

**Comment by ruslo** [comment]
Closing inactive discussion.
