### ISSUE TITLE
Cannot upload to artifactory: Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by acabarbaye** [ruslo/hunter#1544]
I followed the documentation for uploading hunter cache to artifactory:
https://docs.hunter.sh/en/latest/user-guides/hunter-user/artifactory-cache-server.html

However, upload fails with this error: ` Peer certificate cannot be authenticated with given CA certificates`.
I am using Ubuntu 18.04
`
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
`
After browsing the Internet for solutions, I saw that the problem might be due to an old `ca-certificates` package. However, upgrading the package to the latest version does not seem to solve the problem.

[UploadLogs.txt](https://github.com/ruslo/hunter/files/2375456/UploadLogs.txt)

When using cURL, the communication with artifactory seem to work fine:
`curl -v {artifactory-url} -H "X-JFrog-Art-Api:{artifactory-token}"

* TCP_NODELAY set
* Connected to {myartifactory} (ip) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN={artifactory domain}
*  start date: Aug 28 00:00:00 2018 GMT
*  expire date: Sep 28 12:00:00 2019 GMT
*  subjectAltName: host "{artifactory domain}" matched cert's "{artifactory domain}"
*  issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
*  SSL certificate verify ok.
> GET /artifactory/{artifactory repo}/ HTTP/1.1
> Host: {artifactory domain}
> User-Agent: curl/7.58.0
> Accept: */*
> X-JFrog-Art-Api:{artifactory key}
>
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: X-Requested-With, Content-Type, X-Codingpedia
< Access-Control-Allow-Methods: GET, POST, DELETE, PUT
< Cache-Control: no-store
< Content-Type: text/html
< Date: Wed, 12 Sep 2018 14:00:03 GMT
< Server: Artifactory/6.1.0
< SessionValid: false
< X-Artifactory-Id: ac9df0045871f390:-375bace7:164f08c5dbb:-8000
< transfer-encoding: chunked
< Connection: keep-alive
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<html>
<head><title>Index of {artifactory repo}/</title>
</head>
<body>
<h1>Index of {artifactory repo}/</h1>
<pre>Name  Last modified      Size</pre><hr/>
<pre>No items found.
</pre>
`
Do you know what could be the root cause of this problem?

**Comment by OvermindDL1** [comment]
If using `curl` then I'm unsure if this is hunter related.  That's just a generic message from curl that means that the security certificate of the server could not be authenticated.  What is the URL of the server and I can check it over for you?

**Comment by ruslo** [comment]
> Do you know what could be the root cause of this problem? 

Under the hood `file(UPLOAD ...)` used here so it make sense to create simple CMake script with similar upload instructions and check if it will work.

`file(UPLOAD ...)`:
* https://github.com/ruslo/hunter/blob/d182815ca126349c2ec316ecbaf13f9dd57c16a2/cmake/modules/hunter_upload_single_file.cmake#L71-L76

Forming parameters:
* https://github.com/ruslo/hunter/blob/d182815ca126349c2ec316ecbaf13f9dd57c16a2/cmake/modules/hunter_upload_single_file.cmake#L44-L60

Plus part from this section:
* https://docs.hunter.sh/en/latest/user-guides/hunter-user/artifactory-cache-server.html#cmake-code

**Comment by ruslo** [comment]
Closing inactive discussion.
