### ISSUE TITLE
HUNTER_TLS_VERIFY is empty on iOS 12 SDK

### ISSUE THREAD

**Issue by olliwang** [ruslo/hunter#1545]
Hi, I just upgraded Xcode to version 10 GM (for iOS 12) released today, and suddenly hunter cannot build anymore. What's going wrong?

        -- [hunter *** DEBUG *** 2018-09-13T04:12:22] HUNTER_ROOT set using HOME environment variable
        -- [hunter *** DEBUG *** 2018-09-13T04:12:22] HUNTER_ROOT: /Users/usrname/.hunter
        -- [hunter *** DEBUG *** 2018-09-13T04:12:22] Settings (initialize):
        -- [hunter *** DEBUG *** 2018-09-13T04:12:22]   HunterGate done (NO)
        -- [hunter *** DEBUG *** 2018-09-13T04:12:22]   Cache init (YES)
        -- [polly] Used toolchain: iOS 12.0 Universal (iphoneos + iphonesimulator) / clang / c++14 support
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23] Multi-configuration generator
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23] Using default cache server
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23] List of cache servers:
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23]   * https://github.com/ingenue/hunter-cache
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23] Settings (finalize):
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23]   HunterGate done (NO)
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23]   Cache init (YES)
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23] Variables from HunterGate:
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23]   HUNTER_GATE_ROOT: /Users/usrname/.hunter
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23]   HUNTER_GATE_VERSION: 0.23.26
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23]   HUNTER_GATE_SHA1: 224d85df0e20d8e070896a6c4feb9a6823bd543a
        -- [hunter] Calculating Toolchain-SHA1
        -- [hunter *** DEBUG *** 2018-09-13T04:12:23] [/Users/usrname/workspace/proj2/app/ios/build/_3rdParty/Hunter/toolchain] > "/usr/local/Cellar/cmake/3.10.2/bin/cmake" "-DTOOLCHAIN_INFO_FILE=/Users/usrname/workspace/proj2/app/ios/build/_3rdParty/Hunter/toolchain/toolchain.info.NOLF" "-DCMAKE_TOOLCHAIN_FILE=/Users/usrname/workspace/proj2/deps/cmake/ios.cmake" "-DHUNTER_SELF=/Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked" "-GXcode" "-H/Users/usrname/workspace/proj2/app/ios/build/_3rdParty/Hunter/toolchain" "-B/Users/usrname/workspace/proj2/app/ios/build/_3rdParty/Hunter/toolchain/_builds" "-DCMAKE_MAKE_PROGRAM=/usr/bin/xcodebuild" "-DCMAKE_SUPERRELEASE_POSTFIX=-SuperRelease"
        -- [polly] Used toolchain: iOS 12.0 Universal (iphoneos + iphonesimulator) / clang / c++14 support
        -- The C compiler identification is AppleClang 10.0.0.10001145
        -- The CXX compiler identification is AppleClang 10.0.0.10001145
        -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
        -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
        -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        -- Configuring done
        -- Generating done
        -- Build files have been written to: /Users/usrname/workspace/proj2/app/ios/build/_3rdParty/Hunter/toolchain/_builds
        -- [hunter *** DEBUG *** 2018-09-13T04:12:52] Already exists: /Users/usrname/.hunter/_Base/224d85d/225b473/toolchain.info
        -- [hunter] Calculating Config-SHA1
        -- [hunter *** DEBUG *** 2018-09-13T04:12:52] Cache data is up-to-date
        -- [hunter] HUNTER_ROOT: /Users/usrname/.hunter
        -- [hunter *** DEBUG *** 2018-09-13T04:12:52] HUNTER_TOOLCHAIN_ID_PATH: /Users/usrname/.hunter/_Base/224d85d/225b473
        -- [hunter *** DEBUG *** 2018-09-13T04:12:52] HUNTER_CONFIGURATION_TYPES: SuperRelease
        -- [hunter *** DEBUG *** 2018-09-13T04:12:52] HUNTER_BUILD_SHARED_LIBS: 
        -- [hunter] [ Hunter-ID: 224d85d | Toolchain-ID: 225b473 | Config-ID: 388c1bf ]

        [hunter ** FATAL ERROR **] HUNTER_TLS_VERIFY is empty, please update HunterGate module
        [hunter ** FATAL ERROR **] [Directory:/Users/usrname/workspace/proj2/app/proj]

        ------------------------------ WIKI -------------------------------
            https://github.com/ruslo/hunter/wiki/error.incorrect.input.data
        -------------------------------------------------------------------

        CMake Error at /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
        Call Stack (most recent call first):
          /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
          /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_user_error.cmake:7 (hunter_fatal_error)
          /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_finalize.cmake:181 (hunter_user_error)
          /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_add_package.cmake:23 (hunter_finalize)
          /Users/usrname/workspace/proj2/app/proj/CMakeLists.txt:138 (hunter_add_package)

        -- Configuring incomplete, errors occurred!
        See also "/Users/usrname/workspace/proj2/app/ios/build/CMakeFiles/CMakeOutput.log".

        Fatal error: local() encountered an error (return code 1) while executing 'cmake -H. -Bbuild -GXcode -DCMAKE_TOOLCHAIN_FILE=/Users/usrname/workspace/proj2/deps/cmake/ios.cmake -DHUNTER_CONFIGURATION_TYPES=SuperRelease -DPOLLY_STATUS_DEBUG=OFF -DHUNTER_STATUS_DEBUG=ON'

PS. It seems the error occurs at this line.

    hunter_add_package(Boost)

**Comment by ruslo** [comment]
`HUNTER_TLS_VERIFY` set to `ON` by default here:
* https://github.com/hunter-packages/gate/blob/42c1c27cdd556dcbc358c6ba8ad7a72a68ee2a62/cmake/HunterGate.cmake#L61

> [hunter ** FATAL ERROR **] HUNTER_TLS_VERIFY is empty, please update HunterGate module

Usually it means that you're using old version of HunterGate module without `option(HUNTER_TLS_VERIFY ... ON)` line.

> I just upgraded Xcode to version 10 GM (for iOS 12) released today, and suddenly hunter cannot build anymore. What's going wrong?

I don't think it's related

**Comment by olliwang** [comment]
I'm using the latest 

    HunterGate(URL "https://github.com/ruslo/hunter/archive/v0.23.26.tar.gz"
               SHA1 "224d85df0e20d8e070896a6c4feb9a6823bd543a")

Is it normal that `boost` cannot pass TLS verification?

**Comment by olliwang** [comment]
You are right. It works fine after updating `HunterGate.cmake`. Thanks for your help. 👍
