### ISSUE TITLE
Cryptopp failed to build when CMAKE_IOS_INSTALL_COMBINED is YES

### ISSUE THREAD

**Issue by olliwang** [ruslo/hunter#1546]
I was trying to build cryptopp using polly's `ios.cmake` toolchain. However, it cannot build successfully without setting `CMAKE_IOS_INSTALL_COMBINED` to `NO` explicitly, but that builds only `arm64` arch instead of a universal `arm64` and `x86_64` library. Tested with iOS 11 and now iOS 12 SDK. Both cannot pass building without setting `CMAKE_IOS_INSTALL_COMBINED` to `NO`.

The error message below displayed right after `rm -fR ~/.hunter/`. And `CMAKE_IOS_INSTALL_COMBINED` is set to `YES` by default.

        /bin/sh -c /Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/cryptopp/Build/cryptopp-Release-prefix/src/cryptopp-Release-build/cryptopp.build/Release-iphoneos/install.build/Script-54C6D8A9AE8446ED83B9D8D2.sh
    /usr/local/Cellar/cmake/3.10.2/bin/cmake -DBUILD_TYPE=Release -DEFFECTIVE_PLATFORM_NAME=-iphoneos -P cmake_install.cmake
    -- Install configuration: "Release"
    -- Installing: /Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/cryptopp/Install/lib/libcryptopp.a
    [iOS combined] Target: cryptopp-static
    [iOS combined] Config: Release

    [iOS combined] Destination: /Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/cryptopp/Install/lib/libcryptopp.a
    [iOS combined] Architectures (iphonesimulator): x86_64
    [iOS combined] Architectures (iphoneos): arm64
    [iOS combined] Build `cryptopp-static` for `iphonesimulator`
    Build settings from command line:
        SDKROOT = iphonesimulator12.0
        TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault

    note: Using new build system
    note: Planning build
    note: Constructing build description
    Build system information
    error: unable to attach DB: error: accessing build database "/Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/cryptopp/Build/cryptopp-Release-prefix/src/cryptopp-Release-build/build/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.

    ** BUILD FAILED **

    CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/CMakeIOSInstallCombined.cmake:127 (message):
      Build failed
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/CMakeIOSInstallCombined.cmake:279 (_ios_install_combined_build)
      cmake_install.cmake:41 (ios_install_combined)

    make[1]: *** [install_buildpart_0] Error 1

    ** BUILD FAILED **

    The following build commands failed:
    	PhaseScriptExecution CMake\ PostBuild\ Rules /Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/cryptopp/Build/cryptopp-Release-prefix/src/cryptopp-Release-build/cryptopp.build/Release-iphoneos/install.build/Script-54C6D8A9AE8446ED83B9D8D2.sh
    (1 failure)
    make: *** [/Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/cryptopp/Build/cryptopp-Release-prefix/src/cryptopp-Release-stamp/Debug-iphoneos/cryptopp-Release-install] Error 65

    ** BUILD FAILED **

    The following build commands failed:
    	PhaseScriptExecution CMake\ Rules /Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/cryptopp/Build/Hunter.build/Debug-iphoneos/cryptopp-Release.build/Script-0B774046CAE84AE18BC1C2F1.sh
    (1 failure)

    [hunter ** FATAL ERROR **] Build step failed (dir: /Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/cryptopp
    [hunter ** FATAL ERROR **] [Directory:/Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/projects/cryptopp]

    ------------------------------ WIKI -------------------------------
        https://github.com/ruslo/hunter/wiki/error.external.build.failed
    -------------------------------------------------------------------

    CMake Error at /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
    Call Stack (most recent call first):
      /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
      /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_download.cmake:613 (hunter_fatal_error)
      /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/projects/cryptopp/hunter.cmake:53 (hunter_download)
      /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
      /Users/usrname/workspace/proj2/app/proj/CMakeLists.txt:138 (hunter_add_package)

**Comment by ruslo** [comment]
> The error message below displayed right after rm -fR ~/.hunter/. And CMAKE_IOS_INSTALL_COMBINED is set to YES by default.

Sounds like Xcode/CMake problem. Can you create minimal example with some dummy library to reproduce this issue without Hunter?

**Comment by olliwang** [comment]
You are right. It seems it happens for other packages, too. Not sure if this is caused by iOS 12 SDK released yesterday.

    [iOS combined] Architectures (iphoneos): arm64
    [iOS combined] Build `fmt` for `iphonesimulator`
    Build settings from command line:
        SDKROOT = iphonesimulator12.0
        TOOLCHAINS = com.apple.dt.toolchain.XcodeDefault

    note: Using new build system
    note: Planning build
    note: Constructing build description
    Build system information
    error: unable to attach DB: error: accessing build database "/Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/fmt/Build/fmt-Release-prefix/src/fmt-Release-build/build/XCBuildData/build.db": database is locked Possibly there are two concurrent builds running in the same filesystem location.

    ** BUILD FAILED **

    CMake Error at /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/CMakeIOSInstallCombined.cmake:127 (message):
      Build failed
    Call Stack (most recent call first):
      /usr/local/Cellar/cmake/3.10.2/share/cmake/Modules/CMakeIOSInstallCombined.cmake:279 (_ios_install_combined_build)
      fmt/cmake_install.cmake:67 (ios_install_combined)
      cmake_install.cmake:37 (include)


    CMake Warning (dev) in fmt/cmake_install.cmake:
      Policy CMP0011 is not set: Included scripts do automatic cmake_policy PUSH
      and POP.  Run "cmake --help-policy CMP0011" for policy details.  Use the
      cmake_policy command to set the policy and suppress this warning.

      The included script

        /Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/fmt/Build/fmt-Release-prefix/src/fmt-Release-build/fmt/cmake_install.cmake

      affects policy settings.  CMake is implying the NO_POLICY_SCOPE option for
      compatibility, so the effects are applied to the including context.
    Call Stack (most recent call first):
      cmake_install.cmake:37 (include)
    This warning is for project developers.  Use -Wno-dev to suppress it.

    make[1]: *** [install_buildpart_0] Error 1



    ** BUILD FAILED **


    The following build commands failed:
    	PhaseScriptExecution CMake\ PostBuild\ Rules /Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/fmt/Build/fmt-Release-prefix/src/fmt-Release-build/FMT.build/Release-iphoneos/install.build/Script-2408D6BA8C684FE79977B2A0.sh
    (1 failure)
    make: *** [/Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/fmt/Build/fmt-Release-prefix/src/fmt-Release-stamp/Debug-iphoneos/fmt-Release-install] Error 65

    ** BUILD FAILED **


    The following build commands failed:
    	PhaseScriptExecution CMake\ Rules /Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/fmt/Build/Hunter.build/Debug-iphoneos/fmt-Release.build/Script-FC2FBA909632460B9E559D04.sh
    (1 failure)

    [hunter ** FATAL ERROR **] Build step failed (dir: /Users/usrname/.hunter/_Base/224d85d/4046a5b/388c1bf/Build/fmt
    [hunter ** FATAL ERROR **] [Directory:/Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/projects/fmt]

    ------------------------------ WIKI -------------------------------
        https://github.com/ruslo/hunter/wiki/error.external.build.failed
    -------------------------------------------------------------------

    CMake Error at /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
    Call Stack (most recent call first):
      /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
      /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_download.cmake:613 (hunter_fatal_error)
      /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/projects/fmt/hunter.cmake:57 (hunter_download)
      /Users/usrname/.hunter/_Base/Download/Hunter/0.23.26/224d85d/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
      /Users/usrname/workspace/proj2/app/proj/CMakeLists.txt:143 (hunter_add_package)


    -- Configuring incomplete, errors occurred!
    See also "/Users/usrname/workspace/proj2/app/ios/build/CMakeFiles/CMakeOutput.log".

**Comment by olliwang** [comment]
Thanks for your hint. It seems the error is gone after upgrading CMake from 3.10.2 to 3.12.2.
