### ISSUE TITLE
On the usage of local cache.

### ISSUE THREAD

**Issue by Lord-Kamina** [ruslo/hunter#1557]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]** 
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

Hey there, people over at nlohmann/json suggested I might find Hunter useful for my project. 

What I want to have is, essentially, a way to look for a library and if it's not installed, fallback to a submodule I'd include in my project. I'd do this for nlohmann and a couple others (for which I'll probably need to make modules). 

The catch is, I want to make sure there's no download anywhere in the process. 
I've read some of the documentation, and I've seen some reference to both server and local caches, but generally it speaks of cached binaries. Is it possible to have a local source repository? And, how does this work for header-only libraries?

Many thanks in advance!

**Comment by ruslo** [comment]
> What I want to have is, essentially, a way to look for a library and if it's not installed, fallback to a submodule I'd include in my project.

Can you add an example of the CMake code you want to have? Please check that you don't want to implement something like this: https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#environment

> Is it possible to have a local source repository?

You can download all sources yourself and move them to [~/.hunter/_Base/Download](https://docs.hunter.sh/en/latest/reference/layouts/deployed.html#download). In this case there will be no download operations during Hunter run. Assuming that you have to do some combination of `wget`/`mkdir`/`mv` I don't see the point of managing sources manually because Hunter will do exactly the same. Probably if you will share more details it will be clearer why you need it.

You may want to check [HUNTER_DOWNLOAD_SERVER](https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-download-server) functionality.

> And, how does this work for header-only libraries?

There is no big difference. If package with header-only stuff use CMake as a build system then it's installed in the same way like any other CMake project: `cmake --build _builds --target install`.

**Comment by Lord-Kamina** [comment]
> Can you add an example of the CMake code you want to have? Please check that you don't want to implement something like this: https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#environment

Not really, or at least not entirely. I can give you an idea of what I wanted to do by pasting some of the code I would be using for nlohmann, though (This is without hunter; seeing it, they suggested hunter might be a good fit for what I want)

```
find_package(nlohmann_json 3.2.0 QUIET)

if(nlohmann_json_FOUND)
	message(STATUS "Nlohmann JSON Found.")
else()
	message(STATUS "Nlohmann JSON not found; will use included version.")
	include("${CMAKE_SOURCE_DIR}/3rdparty/json/CMakeLists.txt")
endif()
```
```
if(nlohmann_json_FOUND)
	target_link_libraries(performous PRIVATE nlohmann_json::nlohmann_json)
	set_target_properties(nlohmann_json::nlohmann_json PROPERTIES INTERFACE_COMPILE_FEATURES ${COMPUTED_CXX_STD})
else()
	target_link_libraries(performous nlohmann_json)
	set_target_properties(nlohmann_json PROPERTIES INTERFACE_COMPILE_FEATURES ${COMPUTED_CXX_STD})
endif()
```

> You can download all sources yourself and move them to ~/.hunter/_Base/Download. In this case there will be no download operations during Hunter run.

That'd be great.

> Assuming that you have to do some combination of wget/mkdir/mv I don't see the point of managing sources manually because Hunter will do exactly the same. Probably if you will share more details it will be clearer why you need it.

Ideally I'd like to provide some dependencies that might not be readily available in most package managers via submodules as a fallback (so, they'd be git trees). The reason I don't want downloads is because one of the package managers we use (and our recommened way for producing Win32 binaries) is MXE, which explicitly disallows downloading during package builds.

**Comment by ruslo** [comment]
```cmake
find_package(nlohmann_json ...)

if(nlohmann_json_FOUND)
  ...
else()
  ...
  include("${CMAKE_SOURCE_DIR}/3rdparty/json/CMakeLists.txt")
endif()
```

If you're using Hunter there is no need to do that because Hunter will install package and `find_package` will always succeed.

Also if you're using Hunter it's not correct, see:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#environment
* https://docs.hunter.sh/en/latest/faq/interaction-with-other-package-managers.html

Similar pattern can be used in case you want to hack nlohmann_json, but it will look different.

> The reason I don't want downloads is because one of the package managers we use (and our recommened way for producing Win32 binaries) is MXE, which explicitly disallows downloading during package builds.

I think I still don't follow... If you want to build package from sources you have to download archive with sources somehow. Will you use `wget` for this or will delegate it to Hunter there will be no difference.

**Comment by Lord-Kamina** [comment]
What I pasted is how I would go about this _without_ using hunter; this requires I do some changes to nlohmann's CMakeLists to account for the project directory not being nlohmann's but mine. I requested if they would be willing to support what I was doing so I wouldn't have to patch every release they make (this could be done by checking whether ```CMAKE_CURRENT_SOURCE_DIR``` does not equal ```CMAKE_CURRENT_LIST_DIR```, to which somebody suggested I look into hunter as a better alternative to achieve my goal: making sure nlohmann and other dependencies are always installed; without user intervention and/or the need to download them.

> I think I still don't follow... If you want to build package from sources you have to download archive with sources somehow. Will you use wget for this or will delegate it to Hunter there will be no difference.

I need to account for several different package managers that do not include either nlohmann or some other dependency I need. Generally it's not considered good form to have a package silently download/build/install dependencies not account for in the package manager, this is where the local source repository (git submodules) would come into play.

Following me yet?

**Comment by Lord-Kamina** [comment]
Basically, what I want is to have hunter (plus the source of a couple packages) embedded as submodules in my project so that it could look for & configure these packages for my project to use without needing to download them.

**Comment by OvermindDL1** [comment]
Ah, so @Lord-Kamina wants to package up the hunter cache and everything necessary to not need to download as a submodule for CI work where downloading isn't allowed I gather?  That could be quite useful.  And it would fit in the concourse CI system that I use quite well too.

**Comment by ruslo** [comment]
> Generally it's not considered good form to have a package silently download/build/install dependencies not available through the package manager, this is where the local source repository (git submodules) would come into play.

> Following me yet?

I'm afraid not :)

Anyway like I said if you don't want Hunter to download sources, then you can manually prepare [~/.hunter/_Base/Download](https://docs.hunter.sh/en/latest/reference/layouts/deployed.html#download). Hope this fit your needs.

> Basically, what I want is to have hunter (plus the source of a couple packages) embedded as submodules in my project so that it could look for & configure these packages for my project to use without needing to download them.

If you want all your third party packages to be a git submodule then you don't need package manager at all, just do:
```cmake
add_subdirectory(third_party/foo)
add_subdirectory(third_party/boo)

target_link_libraries(... foo::foo boo::boo)
```

> Ah, so @Lord-Kamina wants to package up the hunter cache and everything necessary to not need to download as a submodule for CI work where downloading isn't allowed I gather?

I don't understand the practical reason of it but you can pack `~/.hunter/_Base/Download` and `~/.hunter/_Base/Cache` in this case. But it will be much easier to use a cache server: https://docs.hunter.sh/en/latest/user-guides/hunter-user.html#uploading-binaries

**Comment by Lord-Kamina** [comment]
> Anyway like I said if you don't want Hunter to download sources, then you can manually prepare ~/.hunter/_Base/Download. Hope this fit your needs.

Not really because I can't really include things from the home folder inside my package, I could have a script copy them to the appropriate location from somewhere in the package I guess but that'd be pretty messy.

> If you want all your third party packages to be a git submodule then you don't need package manager at all, just do: *snip*

I am aware of this, but the idea isn't exactly this. I want my package to be able to provide them as fallback when they cannot be easily installed through some other means, rather than always using my included versions.

**Comment by ruslo** [comment]
> Not really because I can't really include things from the home folder inside my package,

Home folder is the default, you can set `HUNTER_ROOT` environment or CMake variable to any directory.

**Comment by Lord-Kamina** [comment]
> Home folder is the default, you can set HUNTER_ROOT environment or CMake variable to any directory.

Ah, so maybe what I want to do can be done after all.

**Comment by ruslo** [comment]
Closing inactive discussion.
