### ISSUE TITLE
Package Expat: Vulnerable outdated inofficial source

### ISSUE THREAD

**Issue by hartwork** [ruslo/hunter#1558]
Hi!

It came to my attention that [cmake/projects/*Expat*/hunter.cmake](https://github.com/ruslo/hunter/blob/master/cmake/projects/Expat/hunter.cmake) packages outdated version 2.1.0 from unofficial source https://github.com/alamaison/expat. Is there a chance that you could update it to 2.2.6 from official source https://github.com/libexpat/libexpat/releases ?

Thanks and best, Sebastian

**Comment by hartwork** [comment]
PS: Noticed the `-hunter.tar.gz` bits in `hunter.cmake` only now. Should I ask for an update over at  `alamaison/expat`, first? Please advise. Thank you!

**Comment by ruslo** [comment]
> Is there a chance that you could update it to 2.2.6 from official source https://github.com/libexpat/libexpat/releases ?

As far as I can see the fork vs upstream difference is only one commit:
* https://github.com/alamaison/expat/commit/35fe113c38e84a6297111894da889b948a944dab

If this change was already applied to upstream, then probably fork is no longer needed. Please check this instructions for updating package:
* https://docs.hunter.sh/en/latest/creating-new/update.html

**Comment by ruslo** [comment]
Closing inactive discussion.
