### ISSUE TITLE
adding a config for package using GIT_SUBMODULE fails to build if the repository has nested submodules.

### ISSUE THREAD

**Issue by mchiasson** [ruslo/hunter#1559]
tried a quick test with https://github.com/foonathan/memory

and added this to my local Hunter/config.cmake:
```
hunter_config(foonathan_memory
    GIT_SUBMODULE
        "thirdparty/memory"
    CMAKE_ARGS
        FOONATHAN_MEMORY_BUILD_EXAMPLES=OFF
        FOONATHAN_MEMORY_BUILD_TESTS=OFF
        FOONATHAN_MEMORY_BUILD_TOOLS=OFF
        BUILD_SHARED_LIBS=OFF
)
```
and didn't work because the repository had a submodule here: `memory/cmake/comp` and even if it was fully initialised and updated, the version inside `.hunter/_Base` did not have it and `memory/cmake/comp` remained blank.

**Comment by ruslo** [comment]
> didn't work because the repository had a submodule

Under the hood `git archive` used there:
* https://github.com/ruslo/hunter/blob/v0.23.27/cmake/modules/hunter_pack_git_submodule.cmake#L198

Not sure if `git archive` support this feature.

By the way it works similar to GitHub releases: https://github.com/foonathan/memory/archive/v0.6-1.tar.gz

**Comment by ruslo** [comment]
Closing inactive discussion.
