### ISSUE TITLE
Generated Link command error

### ISSUE THREAD

**Issue by 19317362** [ruslo/hunter#1561]
I'm test hunter. It's very cool. 
But I found something strange in the LD commond:  three pthread
-pthread 
-lanl 
-lrt 
-lpthread 
-lnsl 
-lpthread 

Is this a problem?

**Comment by NeroBurner** [comment]
It's not a problem. I think it's called automatic resolution of circular dependencies at link time
https://stackoverflow.com/questions/4802624/linking-libraries-that-contain-circular-references-in-gcc

**Comment by ruslo** [comment]
Closing inactive discussion.
