### ISSUE TITLE
The new version of package

### ISSUE THREAD

**Issue by t0p4** [ruslo/hunter#1567]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

There's the  new version of package tomcrypt, see [Github](https://github.com/libtom/libtomcrypt/releases/tag/v1.18.2)
Could you please update the package tomcrypt?

**Comment by ruslo** [comment]
Instructions for updating package can be found here:
* https://docs.hunter.sh/en/latest/creating-new/update.html

**Comment by t0p4** [comment]
Did according to the instructions, but there are some issuses https://travis-ci.com/t0p4/hunter/builds/86897403
Official https://github.com/libtom/libtomcrypt
Could anyone give me advice? I want update it

**Comment by ruslo** [comment]
> Did according to the instructions, but there are some issuses https://travis-ci.com/t0p4/hunter/builds/86897403

You did something wrong, `analyze` toolchain already excluded from testing and should not be run:
* https://travis-ci.org/ingenue/hunter/builds/436219376

iOS build stopped because of very verbose log, can be fixed by adding `VERBOSE=0`. Already done in `pkg.tomcrypt` (see same link above).

**Comment by t0p4** [comment]
Cool, if all pass what shoud next I do

**Comment by ruslo** [comment]
Please follow this guide: https://docs.hunter.sh/en/latest/creating-new/update.html

**Comment by t0p4** [comment]
resolved
