### ISSUE TITLE
 The new version of package

### ISSUE THREAD

**Issue by t0p4** [ruslo/hunter#1568]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

There's the new version of package tommath, see [Github](https://github.com/libtom/libtommath/releases/tag/v1.0.1)
Could you please update the package tommath?

**Comment by ruslo** [comment]
Instructions for updating package can be found here:
* https://docs.hunter.sh/en/latest/creating-new/update.html

**Comment by t0p4** [comment]
resolved
