### ISSUE TITLE
CURL build on iOS fails

### ISSUE THREAD

**Issue by ikliashchou** [ruslo/hunter#1569]
/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/688d96c/Build/CURL/Source/lib/vtls/openssl.c:1138:47: error: use of undeclared identifier 'ENGINE_METHOD_ALL'
    if(ENGINE_set_default(data->state.engine, ENGINE_METHOD_ALL) > 0) {

The same builds well on OS X without toolchain.

* I've created SSCCE reproducing the issue:
```cmake
# CMakeLists.txt

cmake_minimum_required(VERSION 3.0)

include("cmake/HunterGate.cmake")
HunterGate(
        URL "https://github.com/ruslo/hunter/archive/v0.23.27.tar.gz"
        SHA1 "70d75a25f895df3da00d8382417e8c2a08c93173"
)
project(foo)

hunter_add_package(OPENSSL)
hunter_add_package(CURL)
find_package(OPENSSL CONFIG REQUIRED)
find_package(CURL CONFIG REQUIRED)
```

* I'm building on OSX.
* I'm using official CMake release
* CMake version: 3.12.2

* I'm using unmodified toolchain ios-12-0-dep-9-0-device-bitcode-cxx11 from [Polly](https://github.com/ruslo/polly)

I'm using next command line:
```
python3 ~/polly/bin/polly.py --reconfig --toolchain=$toolchain --config Release --ios-multiarch --ios-combined --home $cmakeHome --output $output

```

**Comment by ikliashchou** [comment]
Here it is

`
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-float-conversion -Wno-non-literal-null-conversion -Wno-objc-literal-conversion -Wno-shorten-64-to-32 -Wpointer-sign -Wno-newline-eof -DCMAKE_INTDIR=\"Release-iphoneos\" -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -DHAVE_CONFIG_H -D__STDC_LIMIT_MACROS -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.0.sdk -fstrict-aliasing -Wdeprecated-declarations -miphoneos-version-min=9.0 -Wno-sign-conversion -Wno-infinite-recursion -Wno-comma -Wno-block-capture-autoreleasing -Wno-strict-prototypes -Wno-semicolon-before-method-body -fembed-bitcode -I/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/Release-iphoneos/include -I/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/include/curl -I/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Source/include -I/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/../include -I/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Source/lib/.. -I/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Source/lib/../include -I/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/.. -I/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Source/lib -I/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib -isystem /Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Install/include -I/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/CURL.build/Release-iphoneos/libcurl.build/DerivedSources/armv7 -I/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/CURL.build/Release-iphoneos/libcurl.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/Release-iphoneos -DNDEBUG -fPIC -fvisibility=hidden -MMD -MT dependencies -MF /Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/CURL.build/Release-iphoneos/libcurl.build/Objects-normal/armv7/openssl.d --serialize-diagnostics /Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/CURL.build/Release-iphoneos/libcurl.build/Objects-normal/armv7/openssl.dia -c /Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Source/lib/vtls/openssl.c -o /Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/CURL.build/Release-iphoneos/libcurl.build/Objects-normal/armv7/openssl.o
`

I see this line seems to have all includes from Hunter built modules

`
-isystem /Users/user/HUNTER_ROOT/_Base/70d75a2/f0d8992/9972854/Install/include
`

but the issue still here

**Comment by ruslo** [comment]
> but the issue still here

It means issue is not in CMake/Hunter.

**Comment by ruslo** [comment]
Closing inactive issue with "Broken package" label, see details:
* https://docs.hunter.sh/en/latest/reference/errors/error.external.build.failed.html#what-to-do
