### ISSUE TITLE
Boost stacktrace not found

### ISSUE THREAD

**Issue by Javanater** [ruslo/hunter#1581]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **Yes**
* I'm using latest Hunter URL/SHA1. **Yes**

* I've created SSCCE reproducing the issue:
```cmake
# CMakeLists.txt

cmake_minimum_required(VERSION 3.11)

include("HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.33.tar.gz"
    SHA1 "acbf4b9b77b5a0160adc1da1cdda35f64b14196a"
)

project(hunter_stacktrace)

hunter_add_package(Boost COMPONENTS stacktrace)
```

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
[CMakeOutput.log](https://github.com/ruslo/hunter/files/2470418/CMakeOutput.log)
```
-- Selecting Windows SDK version  to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.0.24215.1
-- The CXX compiler identification is MSVC 19.0.24215.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] Calculating Config-SHA1
-- [hunter] HUNTER_ROOT: C:/dev/hunter_root
-- [hunter] [ Hunter-ID: acbf4b9 | Toolchain-ID: 4bf98f5 | Config-ID: 5f49d4f ]

[hunter ** INTERNAL **] Component 'stacktrace' not found in project 'Boost'
[hunter ** INTERNAL **] [Directory:C:/dev/hunter_stacktrace]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at C:/dev/hunter_root/_Base/Download/Hunter/0.23.33/acbf4b9/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/dev/hunter_root/_Base/Download/Hunter/0.23.33/acbf4b9/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  C:/dev/hunter_root/_Base/Download/Hunter/0.23.33/acbf4b9/Unpacked/cmake/modules/hunter_get_project_files_to_load.cmake:48 (hunter_internal_error)
  C:/dev/hunter_root/_Base/Download/Hunter/0.23.33/acbf4b9/Unpacked/cmake/modules/hunter_add_package.cmake:39 (hunter_get_project_files_to_load)
  CMakeLists.txt:11 (hunter_add_package)
```

I've checked that the first error in logs **IS NOT** `external.build.failed`. **Yes**

* I'm building on Windows.
* I'm using official CMake release
* CMake version: 3.11.2

* I'm not using toolchain

I'm using next command line on generate step:
```
cmake "-GVisual Studio 14 2015"
```

**Comment by ruslo** [comment]
Please try https://github.com/ruslo/hunter/releases/tag/v0.23.34 version.

Note that there is no `libboost_stacktrace` library, hence you can't use `stacktrace` as a component for `find_package` and there is no `Boost::stacktrace` imported library.

You have to specify all libraries explicitly, see example:
* https://github.com/ruslo/hunter/blob/v0.23.34/examples/Boost-stacktrace/CMakeLists.txt#L12-L16

**Comment by Javanater** [comment]
That fixed it, @ruslo, thank you!

For anyone reading this in the future, you have to select which library you want to link to based on the boost::stacktrace documentation. As of 2018/10/12, the latest documentation is here: https://www.boost.org/doc/libs/1_68_0/doc/html/stacktrace/configuration_and_build.html

In my case I had to use stacktrace_windbg because I was using msvc.

**Comment by ruslo** [comment]
> For anyone reading this in the future

You can add to documentation anything you think might be useful for other users. Boost page:
* https://docs.hunter.sh/en/latest/packages/pkg/Boost.html
