### ISSUE TITLE
Boost Fiber example doesn't work on OSX

### ISSUE THREAD

**Issue by hef** [ruslo/hunter#1582]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **Yes**
* I'm using latest Hunter URL/SHA1. **Yes**
** technically, I'm using the git repo at version 574525bd
* I used the boost fiber example: https://github.com/ruslo/hunter/tree/master/examples/Boost-fiber
Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
* https://gist.github.com/hef/4775771dddfa95e06bea117777221fa7
* I've checked that the first error in logs **IS NOT** `external.build.failed`. **Yes**
* I'm building on OSX.
* I'm using system CMake
* CMake version: 3.12.2
* I'm not using toolchain

I'm using next command line on generate step:
```
cd hunter/examples/Boost-fiber
cmake .

```

---

**Comment by ruslo** [comment]
> I'm using next command line on generate step

This is not how it designed to be used, please use `jenkins.py` script for testing examples:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#testing-locally

I've tried `TOOLCHAIN=osx-10-14 PROJECT_DIR=examples/Boost-fiber ./jenkins.py` and it works fine. I'm using Xcode 10.0.

What is the content of ` /Users/hef/projects/hunter/_Base/xxxxxxx/9a57913/b499eae/Install/include` directory? Can you see Boost headers there? Can you see `libboost_fiber*` library in `Install/lib` directory?

**Comment by hef** [comment]
- results of running `TOOLCHAIN=osx-10-14 PROJECT_DIR=examples* /Boost-fiber ./jenkins.py`
  -  https://gist.github.com/hef/5a92f67e7baeb0af8011a648bb21ee51
- Can you see Boost headers there?
  - yes
- Can you see libboost_fiber* library in Install/lib directory?
  - No, but I see the following files.
    - cmake
     - libboost_chrono-mt-d.a
     - libboost_chrono-mt.a
     - libboost_context-mt-d.a
     - libboost_context-mt.a
     - libboost_system-mt-d.a
     - libboost_system-mt.a
     - libboost_thread-mt-d.a
     - libboost_thread-mt.a

I originally tried using the cmake command directly because it produced the same error I was having on another project. That project is using the following:

> HunterGate(
>     URL "https://github.com/ruslo/hunter/archive/v0.23.34.tar.gz"
>     SHA1 "70287b1ffa810ee4e952052a9adff9b4856d0d54"
> )

**Comment by hef** [comment]
ran `TOOLCHAIN=osx-10-14 PROJECT_DIR=examples/Boost-fiber ./jenkins.py`
* include contents: https://gist.github.com/hef/43ef1c31bef583935e9b2daeb573ec0a
* ./_testing/Hunter/_Base/0443a47/4a5f254/b499eae/Install/lib/libboost_fiber-mt.a  exists


I'm unclear on what is different between the example and what this repro I just created is doing:
* repro repo https://github.com/hef/repro-for-boost-fiber-in-hunter
* results of `cmake .` https://gist.github.com/hef/cfc9b70bf438b3b24906c6775f9364d0

**Comment by ruslo** [comment]
> results of cmake . https://gist.github.com/hef/cfc9b70bf438b3b24906c6775f9364d0

Hard to say, you should run build with `HUNTER_STATUS_DEBUG=ON` to see what is going on while Boost is building. Also looks like Boost already installed in `~/.hunter/_Base/.../` so to see build instructions you should set `HUNTER_ROOT` to another path or remove `~/.hunter`. By the way can you try to reproduce it with Travis CI?

Also avoid running `cmake .` - always prefer [out-of-source build](https://cgold.readthedocs.io/en/latest/tutorials/out-of-source.html).

**Comment by hef** [comment]
travis ci  produces the same error:
https://api.travis-ci.org/v3/job/440801110/log.txt


This build includes a fresh ~/.hunter.
I moved the cmake build dir in a later commit

**Comment by ruslo** [comment]
Looks like `fiber` needs C++11 flag. Try to build with toolchain with C++11 enabled, see:
* https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html#simple-toolchains

**Comment by hef** [comment]
adding a cmake toolchain file with set(CMAKE_CXX_STANDARD 11) fixed the issue, thank you.

**Comment by Warchant** [comment]
Having the same problem.
`set(CMAKE_CXX_STANDARD 11)` does not help.

`~/.hunter/_Base/60de9f2/7e73122/dda0f5e/Install/lib` does not have libboost_fiber* library

**Comment by ruslo** [comment]
- https://docs.hunter.sh/en/latest/contacts.html#please-don-t

```
Please avoid adding messages to closed issues unless it’s absolutely necessary ...
```
