### ISSUE TITLE
Silence Warnings of builds of hunter-packages

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#1584]
Is there a way to silence the compile warnings on hunter packages built as dependency of a project?

I've got a windows build in a CI and get a "Log exceeds limit" error because the logfile is too big because of warnings compiling creres-solver with suitesparse enabled

**Comment by ruslo** [comment]
> Is there a way to silence the compile warnings on hunter packages built as dependency of a project?

Suppress them in CMake code of the project or fix them I guess. As for Hunter you can use `HUNTER_STATUS_DEBUG=OFF`.

> I've got a windows build in a CI and get a "Log exceeds limit" error because the logfile is too big because of warnings compiling creres-solver with suitesparse enabled

If you're using Polly you can check `--discard`/`--tail` (e.g. https://github.com/ruslo/hunter/blob/v0.23.34/jenkins.py#L197-L198). If this one needed for `pkg.*` branch you can simply add `VERBOSE=0` environment variable.

**Comment by NeroBurner** [comment]
thx
