### ISSUE TITLE
toolchain.info creation error on msvc14 with toolset LLVM-vs2014

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#1589]
When compiling with toolchain `LLVM-vs2014` hunter throws an internal error

```
$ cmake -H. -B_build_llvm -G "Visual Studio 14 2015 Win64" -T "LLVM-vs2014"
```

[hunter-compilation-error.txt](https://github.com/ruslo/hunter/files/2500424/hunter-compilation-error.txt)

The interesting part of the Log
```
[hunter ** INTERNAL **] 'hunter_check_toolchain_definition' incorrect toolchain.info file,
[hunter ** INTERNAL **]  double definition of define '__amd64__'
[hunter ** INTERNAL **]  in file 'C:/Users/nw.HORN/.hunter/_Base/4629acb/18812f7/toolchain.info'.
[hunter ** INTERNAL **] [Directory:C:/Users/nw.HORN/.hunter/_Base/Download/Hunter/18.10.1/4629acb/Unpacked/cmake/projects/rdb]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at C:/Users/nw.HORN/.hunter/_Base/Download/Hunter/18.10.1/4629acb/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/Users/nw.HORN/.hunter/_Base/Download/Hunter/18.10.1/4629acb/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  C:/Users/nw.HORN/.hunter/_Base/Download/Hunter/18.10.1/4629acb/Unpacked/cmake/modules/hunter_check_toolchain_definition.cmake:62 (hunter_internal_error)
  C:/Users/nw.HORN/.hunter/_Base/Download/Hunter/18.10.1/4629acb/Unpacked/cmake/projects/rdb/hunter.cmake:17 (hunter_check_toolchain_definition)
  C:/Users/nw.HORN/.hunter/_Base/Download/Hunter/18.10.1/4629acb/Unpacked/cmake/modules/hunter_add_package.cmake:62 (include)
  CMakeLists.txt:23 (hunter_add_package)
```

I've narrowed the problem down on how the file `scripts/ShowPredefined.cpp` is compiled and reported. I've modified `scripts/create-toolchain-info` to write the raw compilation output `outresult` to a file
https://github.com/ruslo/hunter/blob/master/scripts/create-toolchain-info.cmake#L76-L82

compiling with msvc14
```
cmake -Hexamples/Eigen -B_build_llvm -G "Visual Studio 14 2015 Win64" -T "LLVM-vs2014"
```
[hunter_MSVC14.log](https://github.com/ruslo/hunter/files/2500358/hunter_MSVC14.log)

compiling with LLVM-vs2014
```
cmake -Hexamples/Eigen -B_build_llvm -G "Visual Studio 14 2015 Win64" -T "LLVM-vs2014"
```
[hunter_LLVM-vs2014.log](https://github.com/ruslo/hunter/files/2500359/hunter_LLVM-vs2014.log)

Clang prints the `#pragma message` as warning. And MSVC creates a summary at the end of all warnings occurred during the compilation. Therefore the `toolchain.info` file has all defines two times

Note: `rv18.10.1` is an internal version of Hunter based on `v0.23.29` with some additional private packages. No changes on `toolchain.info` creation

**Comment by ruslo** [comment]
I guess it's possible to add "remove duplicates" logic here:
* https://github.com/ruslo/hunter/blob/master/scripts/create-toolchain-info.cmake

Or simply ignore this warning for MSVC + LLVM toolchain:
* https://github.com/ruslo/hunter/blob/6078d6f80ab4f8b5cb11e68e95cdcb1821b9c072/cmake/modules/hunter_check_toolchain_definition.cmake#L61-L67

**Comment by NeroBurner** [comment]
as the toolchain reiterates every warning to us, we could just remember the first flag and finish the parsing of the `ShowPredefined.cpp` file early when the first flag is found again.

Do you think we should add a warning just in case?

**Comment by ruslo** [comment]
> just remember the first flag and finish the parsing of the ShowPredefined.cpp file early

Well it's true for our case but it may not be true for another compiler. Just removing duplicates sounds like a reasonable option which doesn't rely on any compiler specific features.

> Do you think we should add a warning just in case?

You mean warning instead of `hunter_internal_error`?

@NeroBurner Can you please try fix from branch [issue-1589](https://github.com/ruslo/hunter/tree/issue-1589) ?

**Comment by NeroBurner** [comment]
Maybe a bit late, but I thought of another solution

https://github.com/ruslo/hunter/blob/6078d6f80ab4f8b5cb11e68e95cdcb1821b9c072/cmake/modules/hunter_check_toolchain_definition.cmake#L61-L67

instead of always throwing an error we could throw the error only if the defines have different values?

will try your fix tomorrow. thanks!

**Comment by NeroBurner** [comment]
The branch is working! Thanks!

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.23.43
