### ISSUE TITLE
Altering CFLAGS and CXXFLAGS, trying to build libcurl for ARM Cortex A9

### ISSUE THREAD

**Issue by truelv** [ruslo/hunter#1590]
@ruslo  Thank  you  for  coming  here .  

I plan to build  this project  https://github.com/ethereum-mining/ethminer and  I found  it use hunter to download  third-party  libraries . 

platform ： ubuntu16.04     
Soc：xilinx  zynq7000   ARM cortexA9

**My  compile  option  is  below：**

```
cmake -DETHASHCUDA=OFF -DAPICORE=OFF -DBINKERN=OFF -DETHASHCL=OFF -DHUNTER_STATUS_DEBUG=ON  -DCMAKE_C_COMPILER=/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++    ..   
```

**It  goes  well  until  to  compile  CURL  and  I  see  the  error  print：**
```
[ 35%] Building C object lib/CMakeFiles/libcurl.dir/hostasyn.c.o
/home/wyh/.hunter/_Base/951e8da/cf077ce/4a08a2c/Build/CURL/Source/lib/strerror.c:32:6: error: #error "strerror_r MUST be either POSIX, glibc or vxworks-style"
 #    error "strerror_r MUST be either POSIX, glibc or vxworks-style"
      ^
```
**So  I  follow  the  tips  on  https://github.com/ruslo/hunter/issues/821  and   edit   ethminer/cmake/Hunter/config.cmake to  this :** 

```
hunter_config(CURL VERSION ${HUNTER_CURL_VERSION} CMAKE_ARGS HTTP_ONLY=ON CMAKE_USE_OPENSSL=OFF CMAKE_USE_LIBSSH2=OFF CURL_CA_PATH=none CMAKE_C_FLAGS=-DHAVE_POSIX_STRERROR_R  CMAKE_CXX_FLAGS=-DHAVE_POSIX_STRERROR_R)
```

**then the error before goes away but  comes  another one :** 
```
make[8]: *** [lib/CMakeFiles/libcurl.dir/base64.c.o] Error 1
lib/CMakeFiles/libcurl.dir/build.make:137: recipe for target 'lib/CMakeFiles/libcurl.dir/hostip.c.o' failed
make[8]: *** [lib/CMakeFiles/libcurl.dir/hostip.c.o] Error 1
lib/CMakeFiles/libcurl.dir/build.make:161: recipe for target 'lib/CMakeFiles/libcurl.dir/progress.c.o' failed
make[8]: *** [lib/CMakeFiles/libcurl.dir/progress.c.o] Error 1  
In file included from /home/wyh/.hunter/_Base/951e8da/cf077ce/5aa3745/Build/CURL/Source/lib/curl_setup.h:56:0,
                 from /home/wyh/.hunter/_Base/951e8da/cf077ce/5aa3745/Build/CURL/Source/lib/progress.c:23: 
/home/wyh/.hunter/_Base/951e8da/cf077ce/5aa3745/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:1004:19: error: two or more data types in declaration specifiers
 #define in_addr_t unsigned long
                   ^
/home/wyh/.hunter/_Base/951e8da/cf077ce/5aa3745/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:1004:28: error: two or more data types in declaration specifiers
 #define in_addr_t unsigned long
```

**So  I  try  to  build  CURL  separately  and  it  goes  well , here  is my steps：**

1. wget https://github.com/hunter-packages/curl/archive/v7.60.0-p0.tar.gz 
2. cmake -DHTTP_ONLY=ON -DCMAKE_USE_OPENSSL=OFF -DCMAKE_USE_LIBSSH2=OFF -DCURL_CA_PATH=none -DCMAKE_C_COMPILER=/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++
3. vi lib/curl_config.h and  edit  it  to   #define HAVE_POSIX_STRERROR_R   1 
4. make `

It  seems  compile  CURL  along  with  hunter  may  result  in  some  *.h   files   and  some  macro  can't  be  detected .
**I  don't  know  it's  a  issue  or  my  operation  error   and   want  to  know  what  can  I  do  to  solve  the   second   question  .  Thanks  for  help !**

**Comment by ruslo** [comment]
> -DCMAKE_C_COMPILER=/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -DCMAKE_CXX_COMPILER=/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++

If you want variables to be used while building third party you have to define them in toolchain:
* https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html

**Comment by truelv** [comment]
I follow your tips and  eit  my  two  files：cmake/Hunter/config.cmake  and  cmake/toolchain.cmake    
**config.cmake  shows  below  now**：(I change it to it's default appear)
```
hunter_config(CURL VERSION ${HUNTER_CURL_VERSION} CMAKE_ARGS  HTTP_ONLY=ON CMAKE_USE_OPENSSL=OFF CMAKE_USE_LIBSSH2=OFF CURL_CA_PATH=none)                                                                        
hunter_config(libjson-rpc-cpp VERSION ${HUNTER_libjson-rpc-cpp_VERSION} CMAKE_ARGS TCP_SOCKET_SERVER=ON)
hunter_config(Boost VERSION 1.66.0)
```
**toolchain.cmake  shows below  now**：(this is a new file)
```
set(CMAKE_C_COMPILER /media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc -DHAVE_POSIX_STRERROR_R)
set(CMAKE_CXX_COMPILER /media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ -DHAVE_POSIX_STRERROR_R) 
```

**But  I  also  see  the  errro  below**：
```
make[8]: *** [lib/CMakeFiles/libcurl.dir/base64.c.o] Error 1
lib/CMakeFiles/libcurl.dir/build.make:137: recipe for target 'lib/CMakeFiles/libcurl.dir/hostip.c.o' failed
make[8]: *** [lib/CMakeFiles/libcurl.dir/hostip.c.o] Error 1
lib/CMakeFiles/libcurl.dir/build.make:161: recipe for target 'lib/CMakeFiles/libcurl.dir/progress.c.o' failed
make[8]: *** [lib/CMakeFiles/libcurl.dir/progress.c.o] Error 1  
In file included from /home/wyh/.hunter/_Base/951e8da/cf077ce/5aa3745/Build/CURL/Source/lib/curl_setup.h:56:0,
                 from /home/wyh/.hunter/_Base/951e8da/cf077ce/5aa3745/Build/CURL/Source/lib/progress.c:23: 
/home/wyh/.hunter/_Base/951e8da/cf077ce/5aa3745/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:1004:19: error: two or more data types in declaration specifiers
 #define in_addr_t unsigned long
                   ^
/home/wyh/.hunter/_Base/951e8da/cf077ce/5aa3745/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/lib/curl_config.h:1004:28: error: two or more data types in declaration specifiers
 #define in_addr_t unsigned long
```

**Comment by ruslo** [comment]
> toolchain.cmake shows below now：(this is a new file)

I don't think `-DHAVE_POSIX_STRERROR_R` should be there.

> But I also see the errro below

I don't know what this error is about, please take a look at CURL sources.

**Comment by truelv** [comment]
@ruslo   sorry   to  disturb  you  again 

**I change  my  toolchain.cmake  to  this**  : 
```
SET(CMAKE_SYSTEM_NAME Linux)                                                                                                                                                                                     
set(CMAKE_C_COMPILER /media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER /media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++)
set(CMAKE_FIND_ROOT_PATH /media/sdb/btc-c100/xilinx)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
```

**then  the  error  comes  like  this** : 
```
-- Performing Curl Test HAVE_FSETXATTR_5
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_FSETXATTR_5 (advanced)
   HAVE_FSETXATTR_5__TRYRUN_OUTPUT (advanced)
For details see /home/wyh/.hunter/_Base/951e8da/8e036cf/4a08a2c/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/TryRunResults.cmake
...
...
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_GLIBC_STRERROR_R (advanced)
   HAVE_GLIBC_STRERROR_R__TRYRUN_OUTPUT (advanced)
For details see /home/wyh/.hunter/_Base/951e8da/8e036cf/4a08a2c/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/TryRunResults.cmake
-- Performing Curl Test HAVE_GLIBC_STRERROR_R - Failed
-- Performing Curl Test HAVE_POSIX_STRERROR_R
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_POSIX_STRERROR_R (advanced)
   HAVE_POSIX_STRERROR_R__TRYRUN_OUTPUT (advanced)
For details see /home/wyh/.hunter/_Base/951e8da/8e036cf/4a08a2c/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/TryRunResults.cmake
-- Performing Curl Test HAVE_POSIX_STRERROR_R - Failed
```

and  **then  I  take  a  look  at**  /home/wyh/.hunter/_Base/951e8da/8e036cf/4a08a2c/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/CMakeFiles/**CMakeError.log** ：
```
Linking C executable cmTC_e6c6c
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e6c6c.dir/link.txt --verbose=1
/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc    -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmiss
/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.4.1/../../../../arm-linux-gnueabihf/bin/ld: **can't  find  -lpthreads**
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_e6c6c.dir/build.make:97: recipe for target 'cmTC_e6c6c' failed
make[7]: *** [cmTC_e6c6c] Error 1
make[7]: Leaving directory '/home/wyh/.hunter/_Base/951e8da/8e036cf/4a08a2c/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_e6c6c/fast' failed
make[6]: *** [cmTC_e6c6c/fast] Error 2
make[6]: Leaving directory '/home/wyh/.hunter/_Base/951e8da/8e036cf/4a08a2c/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/CMakeFiles/CMakeTmp'
...
...  
Linking C executable cmTC_dda2b
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_dda2b.dir/link.txt --verbose=1
/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc    -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmiss
/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/5.4.1/../../../../arm-linux-gnueabihf/bin/ld: **can't find  -lsocket**
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_dda2b.dir/build.make:97: recipe for target 'cmTC_dda2b' failed
...
...
/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc   -I/home/wyh/.hunter/_Base/951e8da/8e036cf/4a08a2c/Install/include  -pedantic -Wall -W -Wpointer-arith 
/home/wyh/.hunter/_Base/951e8da/8e036cf/4a08a2c/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/CMakeFiles/CMakeTmp/CheckIncludeFiles.c:4:23: **fatal error: sys/filio.h: no such file or directory** 
```

I  think  I  have  give  CMAKE_FIND_ROOT_PATH_MODE_LIBRARY  and  CMAKE_FIND_ROOT_PATH_MODE_INCLUDE  in  the   toolchain.cmake . But  why  do  they  can't  find ?

**Comment by ruslo** [comment]
> and then I take a look at /home/wyh/.hunter/_Base/951e8da/8e036cf/4a08a2c/Build/CURL/Build/CURL-Release-prefix/src/CURL-Release-build/CMakeFiles/CMakeError.log

> But why error comes like "Undefined references to ‘pthread_create’ and can't find -lpthreads and can't find -lsocket and fatal error: sys/filio.h: no such file or directory"?

I think it's not related to real error.

Real error is:

```
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_GLIBC_STRERROR_R (advanced)
   HAVE_GLIBC_STRERROR_R__TRYRUN_OUTPUT (advanced)
```

I guess your host is x86_64 and target is ARM, so CMake can't run target tests on your host and you have to define some variables yourself. You can try to add this list to your local `hunter_config(CURL ... CMAKE_ARGS ...)`:
* https://github.com/ruslo/hunter/blob/v0.23.34/cmake/projects/CURL/hunter.cmake#L92-L101

**Comment by truelv** [comment]
@ruslo   
I follow your tips  and  edit  my  cmake/Hunter/config.cmake ：
```
hunter_config(CURL VERSION ${HUNTER_CURL_VERSION} CMAKE_ARGS 
    HTTP_ONLY=ON 
    CMAKE_USE_OPENSSL=OFF 
    CMAKE_USE_LIBSSH2=OFF 
    CURL_CA_PATH=none                                                                                                                                                                                            
    HAVE_FSETXATTR_5=0 
    HAVE_FSETXATTR_5__TRYRUN_OUTPUT=""  
    HAVE_FSETXATTR_6=0  
    HAVE_FSETXATTR_6__TRYRUN_OUTPUT="" 
    HAVE_GLIBC_STRERROR_R=1 
    HAVE_GLIBC_STRERROR_R__TRYRUN_OUTPUT="" 
    HAVE_POLL_FINE_EXITCODE=0 
    HAVE_POLL_FINE_EXITCODE__TRYRUN_OUTPUT=""  
    HAVE_POSIX_STRERROR_R=0 
    HAVE_POSIX_STRERROR_R__TRYRUN_OUTPUT=""
    )
hunter_config(libjson-rpc-cpp VERSION ${HUNTER_libjson-rpc-cpp_VERSION} CMAKE_ARGS TCP_SOCKET_SERVER=ON)
hunter_config(Boost VERSION 1.66.0)

```

error  goes  like : 
```
[hunter ** FATAL ERROR **] Bad `hunter_config` format (variable value is empty): BUILD_CURL_TESTS=OFF
[hunter ** FATAL ERROR **] BUILD_CURL_EXE=OFF
[hunter ** FATAL ERROR **] CMAKE_USE_OPENSSL=ON
[hunter ** FATAL ERROR **] CMAKE_USE_LIBSSH2=OFF
[hunter ** FATAL ERROR **] BUILD_TESTING=OFF
[hunter ** FATAL ERROR **] HTTP_ONLY=ON
[hunter ** FATAL ERROR **] CMAKE_USE_OPENSSL=OFF
[hunter ** FATAL ERROR **] CMAKE_USE_LIBSSH2=OFF
[hunter ** FATAL ERROR **] CURL_CA_PATH=none
[hunter ** FATAL ERROR **] HAVE_FSETXATTR_5=0
[hunter ** FATAL ERROR **] HAVE_FSETXATTR_5__TRYRUN_OUTPUT=
[hunter ** FATAL ERROR **] HAVE_FSETXATTR_6=0
[hunter ** FATAL ERROR **] HAVE_FSETXATTR_6__TRYRUN_OUTPUT=
[hunter ** FATAL ERROR **] HAVE_GLIBC_STRERROR_R=1
[hunter ** FATAL ERROR **] HAVE_GLIBC_STRERROR_R__TRYRUN_OUTPUT=
[hunter ** FATAL ERROR **] HAVE_POLL_FINE_EXITCODE=0
[hunter ** FATAL ERROR **] HAVE_POLL_FINE_EXITCODE__TRYRUN_OUTPUT=
[hunter ** FATAL ERROR **] HAVE_POSIX_STRERROR_R=0
[hunter ** FATAL ERROR **] HAVE_POSIX_STRERROR_R__TRYRUN_OUTPUT=
[hunter ** FATAL ERROR **] [Directory:/home/wyh/.hunter/_Base/Download/Hunter/0.23.6/951e8da/Unpacked/cmake/projects/CURL]
```

Are there any problems with different versions  of  hunter_config ?

**Comment by ruslo** [comment]
> [hunter ** FATAL ERROR **] Bad `hunter_config` format (variable value is empty)

Can you try this version: https://github.com/ruslo/hunter/releases/tag/v0.23.35

**Comment by truelv** [comment]
@ruslo   Thx  for  coming . 

**I tried hunter version v0.23.35 and  found  there  is  no  error  of  compiling  CURL .  But  error  with  package :  ethhash**   

**so  I  edit  cmake/toolchain.cmake  and  ethhash's  building  goes  all  right** : 
```
set(CMAKE_CXX_COMPILER /media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ -std=c++11)

```

**And  then  an  error  comes  from  compiling  OPENSSL  , the  error  is** : 
```
Operating system: x86_64-whatever-linux2
Configuring OpenSSL version 1.1.1 (0x1010100fL) for linux-x86_64
Using os-specific seed configuration
Creating configdata.pm
Creating Makefile

**********************************************************************
***                                                                ***
***   If you want to report a building issue, please include the   ***
***   output from this command:                                    ***
***                                                                ***
***     perl configdata.pm --dump                                  ***
***                                                                ***
**********************************************************************
[ 75%] Performing build step for 'OpenSSL'
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/bn_conf.h.in > crypto/include/internal/bn_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" crypto/include/internal/dso_conf.h.in > crypto/include/internal/dso_conf.h
/usr/bin/perl "-I." -Mconfigdata "util/dofile.pl" \
    "-oMakefile" include/openssl/opensslconf.h.in > include/openssl/opensslconf.h
make depend && make _all
make[1]: Entering directory '/home/wyh/.hunter/_Base/02f1fdd/cf077ce/ca3fcc5/Build/OpenSSL/Source'
make[1]: Leaving directory '/home/wyh/.hunter/_Base/02f1fdd/cf077ce/ca3fcc5/Build/OpenSSL/Source'
make[1]: Entering directory '/home/wyh/.hunter/_Base/02f1fdd/cf077ce/ca3fcc5/Build/OpenSSL/Source'
/media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc  -I. -Iinclude -fPIC -pthread -m64 -Wa,--noexecstack -Wall -O3 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DOPENSSLDIR="\"/home/wyh/.hunter/_Base/02f1fdd/cf077ce/ca3fcc5/Build/OpenSSL/Install/ssl\"" -DENGINESDIR="\"/home/wyh/.hunter/_Base/02f1fdd/cf077ce/ca3fcc5/Build/OpenSSL/Install/lib/engines-1.1\"" -DNDEBUG  -MMD -MF apps/app_rand.d.tmp -MT apps/app_rand.o -c -o apps/app_rand.o apps/app_rand.c
arm-linux-gnueabihf-gcc: error: unrecognized command line option '-m64'
Makefile:695: recipe for target 'apps/app_rand.o' failed
make[1]: *** [apps/app_rand.o] Error 1
make[1]: Leaving directory '/home/wyh/.hunter/_Base/02f1fdd/cf077ce/ca3fcc5/Build/OpenSSL/Source'
```

**In  my  understanding ,  this  erro  may  can  be  solved  by  typing "export  ARCH=arm"  into  Makefile , but  I  can't  manuly  put "export ARCH=arm" into  Makefile  since  it's  generated  automated .**

**Comment by ruslo** [comment]
> set(CMAKE_CXX_COMPILER /media/sdb/btc-c100/xilinx/gcc-linaro-5.4.1-2017.01-i686_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++ -std=c++11)

As with previous case, `-std=c++11` flag doesn't belong here, see:
* https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html#simple-toolchains

> And then an error comes from compiling OPENSSL , the error is ...

> In my understanding , this erro may can be solved by typing "export ARCH=arm" into Makefile , but I can't manuly put "export ARCH=arm" into Makefile since it's generated automated .

OpenSSL don't use CMake as a build system. Hunter has so-called custom build scheme for OpenSSL:
* https://github.com/ruslo/hunter/blob/v0.23.36/cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in

In practice, unfortunately, it means that for almost every new platform you have to modify/adapt this file.

**Comment by truelv** [comment]
@ruslo Thanks for your kindness . 

Could  you  please  tell  me  some  more  details  about   modifying  "url_sha1_openssl.cmake.in" ?  It  seems quite  complex  for  me .

**Comment by ruslo** [comment]
> Could you please tell me some more details about modifying "url_sha1_openssl.cmake.in" ?

It's a template for [ExternalProject_Add](https://cmake.org/cmake/help/latest/module/ExternalProject.html) command which is used to build OpenSSL. The commands from ExternalProject_Add is not suitable for your toolchain at this moment and you have to adapt it. I don't know what is the best way, you have to investigate and decide yourself. I guess it either will be something like checking CMake variable `CMAKE_SYSTEM_NAME`/`CMAKE_SYSTEM_PROCESSOR` (https://github.com/ruslo/hunter/blob/v0.23.36/cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in#L113) or custom CMake variable which you can set in `hunter_config` (like `BUILD_SHARED_LIBS`: https://github.com/ruslo/hunter/blob/v0.23.36/cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in#L126-L130).

**Comment by truelv** [comment]
@ruslo 
If  I  want  to  build  OPENSSL  manualy (without  hunter)  in  my  project   and  let  it  can  be  found  by  my  own  project . Is  it  possible ? I  think  to  do  like  so  may  be  easier  then  edit  "url_sha1_openssl.cmake.in" .

**Comment by ruslo** [comment]
> If I want to build OPENSSL manualy (without hunter) in my project and let it can be found by my own project . Is it possible ?

Assuming by "my own project" you mean project that use Hunter and has `hunter_add_package(OpenSSL)`? I guess in general it's possible but I'm pretty sure it will be pretty tricky, not saying that it's against main Hunter idea.

> I think to do like so may be easier than edit "url_sha1_openssl.cmake.in" .

In my opinion it's not.

**Comment by truelv** [comment]
@ruslo 
Is file "url_sha1_openssl.cmake.in"  used  to  convert  cmake  to  configure ?  

If  I  edit  file  "url_sha1_openssl.cmake.in"  then  which  place  should  I  put  in ?  My  own  project : ethmining/cmake/   or  ~/.hunter/_Base/02f1fdd/cf077ce/ca3fcc5/Build/OpenSSL/Source/schemes/ ？

**Comment by ruslo** [comment]
> If I edit file "url_sha1_openssl.cmake.in" then which place should I put in ?

In general to use it you have to create Hunter archive with new updates, then use the archive in `HunterGate(URL "file:///path/to/archive/hunter.tar.gz" SHA1 ...)`. The simpliest path in my opinion will be to use [jenkins.py](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#testing-locally) script for testing, this script will pack current directory with Hunter and run build.

`jenkins.py` use Polly to pick a toolchain. Since your toolchain is custom you will have to create new toolchain in https://github.com/ruslo/polly . There is no need to commit this toolchain upstream, you can keep it local. Also may be some existent toolchain can suit your needs? Like https://github.com/ruslo/polly/blob/master/linux-gcc-armhf-neon.cmake?

**Comment by truelv** [comment]
@ruslo 
It works and  my problem is solved , Thx a  lot !!!
