### ISSUE TITLE
Add 'nlopt' package

### ISSUE THREAD

**Issue by t0p4** [ruslo/hunter#1592]
* I'm interested in package `<nlopt>`
* Here is official site of package <https://nlopt.readthedocs.io>

* Official GitHub repository: <https://github.com/stevengj/nlopt>

* Used build system: [CMake]

* I have no information about dependencies

---

**Comment by ruslo** [comment]
Closed by https://github.com/ruslo/hunter/pull/1617

@t0p4 Thanks!
