### ISSUE TITLE
Add 'openscenegraph' package

### ISSUE THREAD

**Issue by t0p4** [ruslo/hunter#1593]
* I'm interested in package `<openscenegraph>`
* Here is official site of package <http://www.openscenegraph.org>

* Official GitHub repository: <https://github.com/openscenegraph/OpenSceneGraph>

* Used build system: [CMake]

* I have no information about dependencies

---

**Comment by t0p4** [comment]
Could you add https://github.com/openscenegraph/OpenSceneGraph to hunter packages, I'll want to use it

**Comment by ruslo** [comment]
> Could you add https://github.com/openscenegraph/OpenSceneGraph to hunter packages

Done: https://github.com/hunter-packages/OpenSceneGraph

**Comment by t0p4** [comment]
thanks

**Comment by ruslo** [comment]
Can you check that all dependencies are uploaded? If not, I can re-run upload for such packages.

**Comment by t0p4** [comment]
Do you mean external packages? I checked, are they uploaded for the hunter ( those that are needed)

**Comment by t0p4** [comment]
https://travis-ci.org/t0p4/hunter/jobs/470022342

**Comment by ruslo** [comment]
> I don't understand, could you clarify

Nothing we can do about Travis CI limitation. As a workaround for this problem I do build and upload package using my local machine, then uploaded artifacts can be used on Travis CI.

> https://travis-ci.org/t0p4/hunter/jobs/470022342

There are a lot of external packages built there Jpeg, PNG, freetype, etc. I see that you're using `gcc-hid-fpic` toolchain that is not part of standard set:
* https://github.com/ingenue/hunter/blob/a6c61f055559d6346219453a54e0ce34e61550dd/.travis.yml#L34-L71

Can you switch to something standard like `gcc-7-cxx17`?

**Comment by t0p4** [comment]
cxx-17 fail, need cxx-14.
gcc-hid-fpic toolchain only for test, don't pay attention on it

**Comment by t0p4** [comment]
https://github.com/ruslo/hunter/pull/1689
