### ISSUE TITLE
Which variables does Hunter pass to it's projects

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#1594]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

I think this question comes relatively often, but I didn't find the right answer in the docs.

Which variables does Hunter pass to it's built projects?
Only those defined in the toolchain-file?
Is there a technical reason why a toolchain file is needed? For example to set the C++ standard used, or set compiler flags?
A colleague of mine was under the impression, that hunter would pass the flags he sets in his project to the dependencies. At least the compiler flags defined before HunterGate is called. But when using boost with hunter and setting the CMAKE_CXX_STANDARD to 14 he ran into the following bug https://github.com/boostorg/system/issues/26

**Comment by ruslo** [comment]
> Which variables does Hunter pass to it's built projects?

Default global from `<project>/hunter.cmake` (see https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#cmake-options), custom user variables from local `config.cmake` (see https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-cmake-options) and also some options can be added by global variables like [HUNTER_BUILD_SHARED_LIBS](https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-build-shared-libs).

> Only those defined in the toolchain-file?

Toolchain is for global settings, you should not specify project CMake arguments there.

> Is there a technical reason why a toolchain file is needed? For example to set the C++ standard used, or set compiler flags?

Toolchain is used for simplicity. If you have some thoughts about another approach you can share them, but you have to be ready to design/implement/document everything yourself. It may be not a trivial effort.

> A colleague of mine was under the impression, that hunter would pass the flags he sets in his project to the dependencies. At least the compiler flags defined before HunterGate is called. But when using boost with hunter and setting the CMAKE_CXX_STANDARD to 14 he ran into the following bug

It's not clear what you mean, simple example to reproduce the behavior would be nice.

**Comment by ruslo** [comment]
Closing inactive discussion.
