### ISSUE TITLE
Boost-compute misses header file <boost/uuid/sha1.hpp>

### ISSUE THREAD

**Issue by achary** [ruslo/hunter#1600]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **Yes**
* I'm using latest Hunter URL/SHA1. **Yes**

I can reproduce the issue by compiling the same code as in `/examples/Boost-compute/foo.cpp`, but with adding the following header (which is likely to be used by almost any boost-compute user):

#include <boost/compute/algorithm/copy.hpp>

When doing so, compilation will end with:

```
6:31: fatal error: boost/uuid/sha1.hpp: No such file or directory
 #include <boost/uuid/sha1.hpp>
```

It is possible to workaround the issue by using local `cmake/Hunter/config.cmake` and downgrading Boost version used bu Hunter  from 1.68.0-p1 to e.g. 1.67.0-p1.

My line is this:

```
hunter_config(Boost VERSION 1.67.0-p1)
```
This will result with compilation warning only:

```
#pragma message :"This header is implementation detail and provided for backwards compatibility.
```

But the default combination of Boost-compute and Boost versions Hunter config has causes the issue.

I've checked that the first error in logs **IS NOT** `external.build.failed`. **Yes**

* I'm building on Linux.
* I'm using official CMake release
* CMake version: 3.13.0-rc2

* I'm using  toolchain: g++-7 (Ubuntu 7.2.0-1ubuntu1~16.04) 7.2.0

---

**Comment by ruslo** [comment]
So as a summary you have used `boost/uuid/sha1.hpp` which is not part of Boost 1.68 and you have switched to Boost 1.67. This gives you warning that the header you've included is part of the private implementation. Right? What kind of action do you expect from Hunter?

**Comment by ruslo** [comment]
> It's Hunter's provided BoostCompute that is depending on its presence and attempts to include this header

There is no such thing like "Hunter's provided BoostCompute", Hunter use some instructions (mostly official) to build BoostCompute, if something wrong with BoostCompute itself then the error should be reported to Boost, not to Hunter.

> ensure (whatever that may mean in details) to make sure the correct version of Boost is taken under the hood and used (as required dependency) that causes no compilation error.

Latest version of Boost will be used by default. If latest version of Boost cause you some troubles then you can switch to another version explictily by `hunter_config(Boost VERSION ...)` or, again, report your problem to Boost team.

> ideally, as regression test, examples/Boost-compute/foo.cpp example file that I think is used for quality checks to be more complex and include much more boost compute headers to ensure then issue is not coming back

Feel free to send pull request.

**Comment by achary** [comment]
I've look into details, and to me it's clear this is not a boost issue, but a Hunter issue.

Let me explain what I mean by "hunter provided BoostCompute" because I think it correctly describes the situation, or at lease part of a problem.
Whenever I use Hunter to link to a  BoostCompute library, it downloads a ZIP of it from:

https://github.com/hunter-packages/boost-compute/

This is a fork. Done exclusively for Hunter purpose (a "hunterisation" I believe). The sources used for  it seem to be a bit old and outdated. Its detached from rest of current version of Boost  where `compute` is a part of it now:

https://www.boost.org/doc/libs/1_68_0/libs/compute/doc/html/index.html

 - part of the very Boost library Hunter is offering as parallel package, but not exposed as a component there.

I think the missing header issue comes from this out-of-date package.
The problematic header has been deprecated in Boost starting from version 1.66 and the Boost compute library has adopted accordingly later on:

https://github.com/boostorg/compute/commit/615e1ac41bf1c3b83872768768df1bf691ea8f51

There are two ways to fix the problem IMO:

* a quick patch to Hunter targeting BoostCompute to bump up version it's serving. The latest one will correctly work with latest boost
* a more general (and correct approach IMO) to stop offering BoostCompute as a separate Hunter package, but rather as a Boost::compute component, if possible

**Comment by ruslo** [comment]
If Boost.compute is a part of Boost package (i.e. can be added by `hunter_add_package(Boost)`) then there is no need to use stand-alone BoostCompute (i.e. there is no need to use `hunter_add_package(BoostCompute)`). At this moment there is no conflct checker for such kind of situations, so you have to check consistency yourself.

> as a Boost::compute component, if possible

As far as I can see there is no `compute` component in boost (by "component" we mean build component here), so you can just link `Boost::boost` header-only part. See documentation:
* https://docs.hunter.sh/en/latest/packages/pkg/Boost.html

**Comment by achary** [comment]
Yes,
that's another work around. However, going down this road requires adding these (or similar) extra lines to the project's CMakeLists.txt manually, to set proper language standard and link against OpenCL libraries in the system:

```
find_package(OpenCL REQUIRED)
target_link_libraries(${TARGET} PUBLIC ${OpenCL_LIBRARIES})
target_compile_features(${TARGET} PUBLIC cxx_std_11)
```

This is something normally Hunter takes care for you automatically, when a package is available and maintained, right?

**Comment by ruslo** [comment]
> target_link_libraries(${TARGET} PUBLIC ${OpenCL_LIBRARIES})

You should link to OpenCL::OpenCL, see documentation:
* https://docs.hunter.sh/en/latest/packages/pkg/OpenCL.html

> target_compile_features(${TARGET} PUBLIC cxx_std_11)

You should use toolchain, see documentation:
* https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html#simple-toolchains

**Comment by achary** [comment]
Thanks for clarification.
