### ISSUE TITLE
adding 'KEEP_PACKAGE_SOURCES' to hunter_config after the fact doesn't re-trigger the build

### ISSUE THREAD

**Issue by mchiasson** [ruslo/hunter#1609]
work-around is to either nuke the `.hunter/` folder or manually add a dummy cmake arguments like so:
```
CMAKE_ARGS DUMMY=1
```

**Comment by mchiasson** [comment]
i'm wondering if adding some kind of `ALWAYS_REBUILD` keyword to `hunter_config` would be a good solution for this, where you can remove both `KEEP_PACKAGE_SOURCES` and `ALWAYS_REBUILD` when you're done without needing to nuke the `.hunter/` in the end

**Comment by ruslo** [comment]
Closing inactive discussion.
