### ISSUE TITLE
Packaging with Hunter: Finding LICENSE files to distribute with package

### ISSUE THREAD

**Issue by aadityakalsi** [ruslo/hunter#161]
In cases where 3rdparty libraries are used, how does one apporach the issue of packaging their license as part of one's own library?

Ex.

```
hunter_add_package(Boost COMPONENTS system filesystem)
set(Boost_USE_STATIC_LIBS ON)
find_package(Boost REQUIRED system filesystem)
# Other things
install(FILES ${all_license_files} '.')
```

How do we include the Boost license as part of ```all_license_files```?

**Comment by ruslo** [comment]
You can use `BOOST_ROOT` variable to access installed Boost directory directly. But I see no LICENSE file there. What do you think about manually downloading it from boost.org?
```cmake
file(DOWNLOAD "http://www.boost.org/LICENSE_1_0.txt" "/path/to/file")
```

**Comment by aadityakalsi** [comment]
Ok. I did not know about BOOST_ROOT. 

I just wanted to make sure that Hunter can deal with all kinds of 3p products, even licenses that require forwarding a copy with the binary or headers.

Boost was just one example. :)

**Comment by aadityakalsi** [comment]
In some sense, it would be nice to have a BOOST_LICENSE, or in general:

```${<PRODUCT>_LICENSE}``` variable to be able to include it if required.

For example:

```
if(<PRODUCT>_LICENSE)
  install(FILES ${<PRODUCT>_LICENSE ".")
endif()
```

**Comment by ruslo** [comment]
> I just wanted to make sure that Hunter can deal with all kinds of 3p products, even licenses that require forwarding a copy with the binary or headers

Yes, you can download anything you want. Just pick the scheme you need, see [wiki](https://github.com/ruslo/hunter/wiki/dev.build.schemes).

> In some sense, it would be nice to have a BOOST_LICENSE, or in general: `${<PRODUCT>_LICENSE}` variable to be able to include it if required.

Well it's possible to add such variable but I don't know how to implement it in real life. So we must store the path to the license somewhere? Like:
```
hunter_download(PACKAGE_NAME Boost LICENSE "http://www.boost.org/LICENSE_1_0.txt")
```

Or try to find LICENSE file in top of the unpacked archive (?) and copy it to the root directory. Like `<root>/licenses/Boost/LICENSE` (?)

**Comment by aadityakalsi** [comment]
Most products have the license as part of the unpacked archive. That seemed to be the right approach to me, but I haven't thought about it a lot.

Many times the license file is called COPYING, or LICENSE, etc. This is decided on a per-product level. It would be nice if Hunter also defined the <PRODUCT>_LICENSE variable so products that needed redistribution and do so with Hunter support, rather than going around Hunter for just this one piece.

**Comment by ruslo** [comment]
> Most products have the license as part of the unpacked archive. That seemed to be the right approach to me, but I haven't thought about it a lot

Okay, let's try it: https://github.com/ruslo/hunter/issues/162

**Comment by ruslo** [comment]
Implemented by: https://github.com/ruslo/hunter/pull/249
