### ISSUE TITLE
Add CLIUtils C++11 command-line parser

### ISSUE THREAD

**Issue by nzbart** [ruslo/hunter#1611]
* I'm interested in package `CLI11`
* Here is official site of package https://cliutils.gitlab.io/CLI11Tutorial/
* Official GitHub repository: https://github.com/CLIUtils/CLI11
* Used build system: CMake
* This package has no dependencies

**Comment by ruslo** [comment]
Already available:
* https://docs.hunter.sh/en/latest/packages/pkg/CLI11.html

**Comment by nzbart** [comment]
Thanks, @ruslo - you're absolutely correct.

I thought that it wasn't available because I didn't find it under the "Commandline Tools" section in the package list:

https://docs.hunter.sh/en/latest/packages/commandline.html

It might help others in future if it was added to this list.

**Comment by ruslo** [comment]
> It might help others in future if it was added to this list

@nzbart Feel free to send a pull request
