### ISSUE TITLE
build boost with ICU in hunter 

### ISSUE THREAD

**Issue by zxckiller** [ruslo/hunter#1619]
Hello,how can i find a way to complie boost with ICU in hunter , 
`hunter_add_package(Boost COMPONENTS locale )`
how to send the BOOST_HAS_ICU and ICU_PATH params to b2.

**Comment by ruslo** [comment]
There is no such feature at this moment as far as I know, feel free to work on it.
You would need to use approach similar to downloading ZLIB and BZip2:
* https://github.com/ruslo/hunter/blob/v0.23.52/cmake/modules/hunter_boost_component_b2_args.cmake#L83
* https://github.com/ruslo/hunter/blob/v0.23.52/cmake/modules/hunter_boost_component_b2_args.cmake#L110

**Comment by zxckiller** [comment]
It seems I can use some code , thank you.

**Comment by zxckiller** [comment]
I add these code in the hunter_boost_component_b2_args.cmake file,and it's works!
```
    hunter_add_package(ICU)
    find_package(ICU CONFIG REQUIRED)


    get_target_property(ICU_include ICU::uc INTERFACE_INCLUDE_DIRECTORIES)
    get_target_property(ICU_path ICU::uc IMPORTED_LOCATION_RELEASE)
    get_filename_component(ICU_dir ${ICU_path} DIRECTORY)
    get_filename_component(ICU_root ${ICU_dir} DIRECTORY)
  
    if(WIN32)
      list(APPEND myList "include=${ICU_include}" "-s" "ICU_PATH=${ICU_root}" "linkflags=/DYNAMICBASE Advapi32.lib")
    else()
      list(APPEND myList "include=${ICU_include}" "-s" "ICU_PATH=${ICU_root}")
    endif()
```
But still a small problem.ICU build by hunter on windows, lib's name is "icudata.lib" and "icui18n.lib".But boost's "has_icu_test.cpp" find "icudt.lib" and "icuin.lib", although they are the same library.
I don't know why this happened，maybe the unmatched version between icu and boost.
ICU from hunter is v55.1-p3
Boost from hunter is v1.68.0-p1

**Comment by ruslo** [comment]
> I don't know why this happened，maybe the unmatched version between icu and boost.

I don't know either, probably yes.

**Comment by zxckiller** [comment]
I found these words in the CMake source code file "FindICU.cmake"
```
# Note that on Windows ``data`` is named ``dt`` and ``i18n`` is named
# ``in``; any of the names may be used, and the appropriate
# platform-specific library name will be automatically selected.
```
It seems b2 select the wrong lib's name on windows.

**Comment by xsacha** [comment]
Maybe Hunter builds ICU with consistent naming that Boost does not expect.
Did you work out if it is upstream bug in Boost or naming difference in ICU?

**Comment by ruslo** [comment]
ICU library name should match standard ICU name. I think the problem is in Boost; I haven't opened any upstream issue though. Just for your info, there is work-in-progress branch `wip.boost.regex.icu`:
- https://github.com/ruslo/hunter/commits/wip.boost.regex.icu

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
