### ISSUE TITLE
Add `${PACKAGE_NAME}_LICENSE` variable

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#162]
Try to find one of the files: LICENSE, LICENSE.txt, COPYING, ... from the unpacked archive and if found install it to `<root-id>/licenses/${PACKAGE_NAME}` directory and set `${PACKAGE_NAME}_LICENSE` variable so user can use it in his project, like:
```cmake
install(FILES "${${PACKAGE_NAME}_LICENSE}" ".")

**Comment by aadityakalsi** [comment]
If we were to define these variables, where would the definition for each package go?

**Comment by ruslo** [comment]
@aadityakalsi I'm not sure I understand what you mean. Feature designed so Hunter find file and set `*_LICENSE` variable and user use `*_LICENSE` variable. For example:
* Boost has LICENSE.txt
* OpenSSL has COPYING

=>

* Hunter copy Boost LICENSE.txt to `<root-id>/licenses/Boost/LICENSE.txt` and set `Boost_LICENSE` variable to location of this file
* Same for OpenSSL but `OpenSSL_LICENSE=<root-id>/licenses/OpenSSL/COPYING`

**Comment by aadityakalsi** [comment]
@ruslo Sorry,I should've been clearer. I was trying to ask how to implement this and where should this definition of the variable be, i.e. the physical design.

**Comment by ruslo** [comment]
> i.e. the physical design

@aadityakalsi Let me think...

### hunter_download.cmake

Some theory:
* `HUNTER_INSTALL_PREFIX` is the final location of installed package (`<root-id>/Install`)
* `HUNTER_PACKAGE_INSTALL_PREFIX` is the temporary install location for cacheable packages (`<root-id>/Build/<package>/Install` - will be removed after successful build) or same as `HUNTER_INSTALL_PREFIX` for non-cacheable packages

So I guess next changes here:
* Introduce new variable `HUNTER_PACKAGE_LICENSE_FILE` which is equal to `${HUNTER_PACKAGE_INSTALL_PREFIX}/licenses/${HUNTER_PACKAGE_NAME}/LICENSE`. This variable will be used by build scheme as a copy-to destination of license file
* New variable `license_var = ${HUNTER_PACKAGE_NAME}_LICENSE`
* Set `license_var` to `${HUNTER_INSTALL_PREFIX}/licenses/${HUNTER_PACKAGE_NAME}/LICENSE` to `PARENT_SCOPE` (near the `set(${root_name} "${${root_name}}" PARENT_SCOPE)` I guess). This variable is for user, i.e. linked to the final destination.

### hunter_copy_license_file

Since license-copy logic will be applied to several schemes I guess we need to add extra cmake module with function `hunter_copy_license_file` which should accept two arguments: `source_dir` and `license_dst`. This function works quite simple: just check one of the `LICENSE`, `LICENSE.txt`, `COPYING` etc. file exists in `source_dir` directory and if found copy it to `license_dst`.

### build schemes

Add `hunter_copy_license_file("@HUNTER_PACKAGE_SOURCE_DIR@" "@HUNTER_PACKAGE_LICENSE_FILE@")`. For boost you only need to add this code to `url_sha1_boost.cmake` since this scheme will be called before building other components. Feel free to add this code to only schemes you need. I guess we can update/test this iteratively.

### examples

Update code of examples (one example for one scheme) to test this feature works:
```cmake
if(NOT EXISTS "${Boost_LICENSE}")
  message(FATAL_ERROR "License not found: ${Boost_LICENSE}")
endif()
```

**Comment by aadityakalsi** [comment]
One issue with this design is that including or excluding LICENSE file is a property of the Scheme and not the package. This breaks down if different packages using the same scheme want to make different choices for whether to include or exclude the LICENSE.

I believe the LICENSE should be made available for all packages if found. Whether the user wants to install or package the LICENSE for package X or Y is up to him, but Hunter supports each.

Does that sound reasonable?

**Comment by aadityakalsi** [comment]
Another issue:

I have this working in a prototype, but it errors because ```${HUNTER_INSTALL_PREFIX}/licenses/${HUNTER_PACKAGE_NAME}/LICENSE``` is different when building vs. post-install,

Post-install, ```${HUNTER_INSTALL_PREFIX}``` is the installation dir not build installation. What is a good way to solve this?

**Comment by ruslo** [comment]
> One issue with this design is that including or excluding LICENSE file is a property of the Scheme and not the package

I see no problems here for now. This is a job for `hunter_copy_license_file` function. Can you share scenario when it doesn't work (?)

> This breaks down if different packages using the same scheme

One package use LICENSE, other LICENSE.txt. Function will copy the file that exists.

> want to make different choices for whether to include or exclude the LICENSE

If LICENSE file exists we will copy it to `<root-id>/licences/<package>` user don't have to use it if it don't need this file. Still see no problems.

> Whether the user wants to install or package the LICENSE for package X or Y is up to him, but Hunter supports each.

Yes

> but it errors because ${HUNTER_INSTALL_PREFIX}/licenses/${HUNTER_PACKAGE_NAME}/LICENSE is different when building vs. post-install

See the difference between `HUNTER_PACKAGE_INSTALL_PREFIX` and `HUNTER_INSTALL_PREFIX` in the message above.

@aadityakalsi Sorry if I'm missing something it's always look easy in mind but on practice there can be some flaws.

**Comment by aadityakalsi** [comment]
@ruslo I will be adding a pull request to show some code. That pull request is not for acceptance. It is just for discussion.

**Comment by ruslo** [comment]
> I will be adding a pull request to show some code. That pull request is not for acceptance. It is just for discussion.

@aadityakalsi Okay, thanks

**Comment by ruslo** [comment]
Fixed by: https://github.com/ruslo/hunter/pull/249
