### ISSUE TITLE
Add package lodePNG

### ISSUE THREAD

**Issue by bkotzz** [ruslo/hunter#1627]
* I'm interested in package `LodePNG`
* Here is official site of package https://github.com/lvandeve/lodepng

* This package is using Git

* Official GitHub repository: https://github.com/lvandeve/lodepng

* Used build system: None currently

The package is extremely simple - I will add CMake support / hunter support

* This package has no dependencies

---

**Comment by bkotzz** [comment]
@ruslo can you make the fork in hunter_packages, and then I can send you a PR to hunterize it?

**Comment by ruslo** [comment]
> can you make the fork in hunter_packages, and then I can send you a PR to hunterize it?

Done: https://github.com/hunter-packages/lodepng

Please read this carefully:
* https://docs.hunter.sh/en/latest/creating-new/patch.html

> This package has no dependencies

Note that if this package has no dependencies you can send all CMake code to upstream, so there will be no need to maintain the fork.

**Comment by bkotsopoulossc** [comment]
Normally I would agree, but looks like others have sent cmake PRs years ago that never got a response. 

https://github.com/lvandeve/lodepng/pull/45
https://github.com/lvandeve/lodepng/pull/78
https://github.com/lvandeve/lodepng/pull/36

**Comment by ruslo** [comment]
> Normally I would agree, but looks like others have sent cmake PRs years ago that never got a response.

It's okay to use fork for this reason, just keep in mind upstream patches.

**Comment by bkotzz** [comment]
Fixed now
