### ISSUE TITLE
Build boost for android's arm64-v8a problem

### ISSUE THREAD

**Issue by zxckiller** [ruslo/hunter#1630]
I build boost for android's armeabi-v7a succeeded with the command line
`cmake -DCMAKE_TOOLCHAIN_FILE=/path/to/androidSDK/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_STL=c++_static ..`
But when I change the -DANDROID_ABI=armeabi-v7a to -DANDROID_ABI=arm64-v8a . It still build the 32bit library. 
I change the 
https://github.com/ruslo/hunter/blob/v0.23.52/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L296
because "@CMAKE_ANDROID_ARCH@" macro in the NDK's toolchain file names "@CMAKE_ANDROID_ARCH_ABI@".
Now, the ${build_opts} send to b2 have the address-model=64 option,but when I run again ,it's still build the 32bit library.
I found the boost.user.jam option in the ${build_opts} still wrong, How can I modify the jam file by Hunter?

**Comment by ruslo** [comment]
This issue will be closed because the required template file [ISSUE_TEMPLATE.md][1] was ignored. Please read and fill carefully all parts of this file while submitting a bug report.

Thanks for understanding.

[1]: https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE.md
