### ISSUE TITLE
Add package corrade 

### ISSUE THREAD

**Issue by pthom** [ruslo/hunter#1633]
* I'm interested in package `corrade`
* Here is official site of package  https://magnum.graphics/corrade/

* This package is using [Git]

* Official GitHub repository:https://github.com/mosra/corrade

* Used build system: [CMake]

* This package has no dependencies (only other find_package is find_package(Threads))

*********************
Note that is `corrade` is not that interesting without its sister project https://github.com/mosra/magnum 

(I have not yet tested to integrate this one into hunter, but I will try now)

***********************
I already worked on this package, below some info:

* branch : https://github.com/pthom/hunter/tree/pr.pkg.corrade

* I've followed [this guide](https://docs.hunter.sh/en/latest/creating-new/create/cmake.html) step by step carefully. **[Yes]**

* I've tested this package remotely and have excluded all broken builds.
  Here is the links to the Travis/AppVeyor with status "All passed":

  * https://ci.appveyor.com/project/pthom/hunter/builds/20626221
  * https://travis-ci.org/pthom/hunter/builds/460930548

* [Yes] I have submitted CI configs to https://github.com/ingenue/hunter targeting `pkg.template` branch 
* [Not Yet merged] see this merged pull request https://github.com/ingenue/hunter/pull/298

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/pull/1646

@pthom Thanks!

**Comment by OvermindDL1** [comment]
@pthom Definitely thanks!  I've been quite interested in this as well!

**Comment by pthom** [comment]
@OvermindDL1 : you are welcome, thank you !
