### ISSUE TITLE
Android NDK w/ Boost

### ISSUE THREAD

**Issue by arcanis** [ruslo/hunter#1634]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **Yes**
* I'm using latest Hunter URL/SHA1. **No**

I've noticed that Hunter is using the `CMAKE_ANDROID_ARCH` variable to set the `address-model` value used when compiling Boost:

https://github.com/ruslo/hunter/blob/78c5b2419487cd3bd7ad9ff93e0ece77a7966f05/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L296-L300

This value isn't set by the Android NDK toolchain - it's instead `ANDROID_SYSROOT_ABI` (cf [here](https://android.googlesource.com/platform/ndk/+/master/build/cmake/android.toolchain.cmake#307)).

Related to #618 and the discussion we've had previously regarding the NDK toolchain vs the Android toolchain (https://github.com/ruslo/hunter/issues/618#issuecomment-354015015)

I believe that #1630 is a similar issue.

**Comment by ruslo** [comment]
> I've noticed that Hunter is using the CMAKE_ANDROID_ARCH variable to set the address-model value used when compiling Boost

> This value isn't set by the Android NDK toolchain - it's instead ANDROID_SYSROOT_ABI (cf here).

I've already expressed my opinion in https://github.com/ruslo/hunter/issues/618 - `CMAKE_ANDROID_ARCH` variable is part of official documentation:
* https://cmake.org/cmake/help/latest/variable/CMAKE_ANDROID_ARCH.html

I don't see the point of supporting two set of Android variables. @arcanis what is the question exactly?

And also as mentioned in the same https://github.com/ruslo/hunter/issues/618 discussion you can use [this trick](https://docs.hunter.sh/en/latest/faq/android-studio.html#integration) to load Android NDK toolchain and have CMake friendly variables.

**Comment by arcanis** [comment]
At the very least it makes the issue more searchable for people with similar issues.

At the very best I think for the sake of a good developer experience it would make sense to do best effort to support both variables when possible - those issues are typically very frustrating and hard to debug.

**Comment by arcanis** [comment]
I'll also open an issue on the NDK repository to get their insight

**Comment by ruslo** [comment]
> At the very least it makes the issue more searchable for people with similar issues.

Feel free to add a F.A.Q. section

> At the very best I think for the sake of a good developer experience it would make sense to do best effort to support both variables when possible

You can make a fork, support both sets of variables, fix all issues in all related packages (e.g. OpenCV: https://github.com/hunter-packages/opencv/commit/6b1ca6faa66ea0c2a64c2c51781a6873de90e774), maintain this fork for some time, then see how much attention it will get. If it will be a good experiment I will think about merging it to master. Deal? :)

**Comment by arcanis** [comment]
I already spend a lot of time supporting Yarn (the open-source JS package manager), I unfortunately can't commit to other ones :)

Still, package management in the C++ space is an interesting problem and I'd be curious to see whether something could be started with the C++20 Modules TS. Maybe something radical that wouldn't necessarily try to support existing build chains by default.

**Comment by ruslo** [comment]
@arcanis Please close this discussion if you're not planning any actions.
