### ISSUE TITLE
Hunter breaks FindBoost

### ISSUE THREAD

**Issue by krsch** [ruslo/hunter#1637]
When I just add `hunter` to my `CMakeLists.txt` the search for Boost components fail. If I remove all the lines of `hunter` the configuration step succeeds. And I don't understand why `hunter` would want to break a package it doesn't install.

* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **Yes**
* I'm using latest Hunter URL/SHA1. **Yes**

* I've created SSCCE reproducing the issue:
```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.8)

### Hunter snapshot that will be used ###
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.59.tar.gz"
    SHA1 "a14e262b762df438116bab185ca6d72191e05254"
)
project(test)
find_package(Boost REQUIRED COMPONENTS filesystem)

add_executable(a.out test.c)
target_link_libraries(a.out PUBLIC Boost::filesystem)
```
`test.c` is empty

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
* https://gist.github.com/krsch/96f1c811775d954bc7422633d896a629

I've checked that the first error in logs **IS NOT** `external.build.failed`. **Yes**

* I'm building on Ubuntu 18.04.
* I'm using system CMake
* CMake version: 3.10.2

* I'm not using toolchain

I'm using next command line on generate step:
```
cmake ..
```

**Comment by ruslo** [comment]
> I've checked that all the hunter_add_package/find_package API used by me in example is the same as in documentation. Yes

It's "No" as far as I can see.

You have to use `hunter_add_package` + `find_package` calls if there is `HunterGate`. If you want to disable Hunter in such configuration then you can do `HUNTER_ENABLED=OFF`:
* https://docs.hunter.sh/en/latest/overview/compatibility.html

**Comment by krsch** [comment]
I want to use system-wide `Boost` and also install some packages from `hunter` like `fmt`. Can't I have both? If I add `hunter_add_package` it would install `boost` from source which I don't want. If I add `HUNTER_ENABLED=OFF` I will not be able to install `fmt` from hunter.

**Comment by krsch** [comment]
And why does hunter ship its own `FindBoost.cmake`? Doesn't it supply `BoostConfig.cmake`?

**Comment by ruslo** [comment]
> I've read F.A.Q. section and there is no solution to my problem there. **Yes**

> I want to use system-wide Boost and also install some packages from hunter like fmt. Can't I have both? 

See https://docs.hunter.sh/en/latest/faq/interaction-with-other-package-managers.html

> And why does hunter ship its own FindBoost.cmake? Doesn't it supply BoostConfig.cmake?

`BoostConfig.cmake` loads `FindBoost.cmake`:
* https://github.com/ruslo/hunter/blob/v0.23.60/cmake/templates/BoostConfig.cmake.in#L40

And `FindBoost.cmake` version in Hunter contains some patches.

**Comment by krsch** [comment]
Ok, if compatibility with system libraries is not a goal for hunter, I'll close this issue.
