### ISSUE TITLE
BZip2 is broken on iOS

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#164]
As mentioned [here](https://github.com/ruslo/hunter/issues/110) if you don't need `bzip2` in `boost.iostreams` you can use `IOSTREAMS_NO_BZIP2=1`

@headupinclouds Let me know if this is critical for you I will take a look. As far as I remember the problem is that `bzip2` package build some executable. So I guess it will be not so hard to apply patch with fix
##

**Comment by headupinclouds** [comment]
I don't need bzip2.  This is the solution I've been using.  Thanks.

**Comment by ruslo** [comment]
Fixed https://github.com/ruslo/hunter/pull/700
