### ISSUE TITLE
Where of how Hunter cache files before  building

### ISSUE THREAD

**Issue by Scorpovi4** [ruslo/hunter#1640]
Where does Hunter store (cache) data before` %USERNAME%\.hunter` making? I need to reset it, because it stored my old files and all the time after build I'll take old files in the` .hunter` folder.

**Comment by ruslo** [comment]
> Where does Hunter store (cache) data **before** %USERNAME%\.hunter making?

It's not before, first the `.hunter` folder created then the rest. Documentation for layout is here:
* https://docs.hunter.sh/en/latest/reference/layouts/deployed.html

>  I need to reset it, because it stored my old files and all the time after build I'll take old files in the .hunter folder.

Hunter designed so you don't have to do it on a regular basis. Usually on some update one of the `Hunter-ID`/`Toolchain-ID`/`Config-ID` should be updated automatically (see [customization](https://docs.hunter.sh/en/latest/overview/customization.html)). If you have to clean up the `.hunter` directory then it mean you did something wrong. What is the reason you want to remove old files?

**Comment by Scorpovi4** [comment]
My previous files had mistakes and as result I took errors, I fixed it but hunter still make `.hunter` with files with previous data in it.

I see this IDes within building http://prntscr.com/lpyy18 And how could I change one of it to reset building data?

**Comment by Scorpovi4** [comment]
What happened:
I had mistake to call `hunter_config(print VERSION 0.1.0.0)` here
http://prntscr.com/lq0fig
And now, I remove it but every time it make this file with my previous mistake what I removed!
http://prntscr.com/lq0i20

The same with another file, hunter cached somewhere my old versions and every time create `.hunter `with it
As I understand, to reset some of 3 IDs should be changed, but I don't use toolchain and config ID formed on the base of forked hunter repository but there I did another branch to change and took id like that (but SHA1 always the same and doesn't matter changes into another branches)
HunterGate(
```
    URL "https://github.com/Scorpovi4/hunter/archive/v0.23.61.1.tar.gz"
    SHA1 "142506dfc6ef30ad47abf69aa89f942383a9d02a"
    LOCAL
)
```
, so without playing with ids could I give some flag to build with new data
`cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install  `

**Comment by ruslo** [comment]
> "https://github.com/Scorpovi4/hunter/archive/v0.23.61.1.tar.gz"

Mistake is here? Create new archive.

**Comment by Scorpovi4** [comment]
Really, trouble was into archive, I tagged new commit pushed to remote repo, than calculate new SHA1 and changed it in CMakeLists.txt, that set relevant data in .hunter, thanx.
