### ISSUE TITLE
The package folly cannot pass the build under macOS

### ISSUE THREAD

**Issue by Junch** [ruslo/hunter#1641]
The example under the folder  _hunter/examples/folly_
cannot pass the build under macOS.

The error message is as below:
... error: unknown type name 'constexpr'

**Comment by ruslo** [comment]
This issue will be closed because the required template file [ISSUE_TEMPLATE.md][1] was ignored. Please read and fill carefully all parts of this file while submitting a bug report.

Thanks for understanding.

[1]: https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE.md
