### ISSUE TITLE
Add package libimagequant

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1648]
* I'm interested in package `libimagequant`
* Here is official site of package https://github.com/ImageOptim/libimagequant

* This package is using Git

* Official GitHub repository: https://github.com/ImageOptim/libimagequant

* Used build system: autotools/cargo

* Unofficial CMake support: https://github.com/ImageOptim/libimagequant/pull/19

The above PR added a cross-platform CMakeLists.txt that the author merged only into the msvc (Windows) branch for whatever reason. I think we'll need a fork.

* This package has no dependencies

@ruslo If you make a hunter-packages fork, I will hunterize this package.

**Comment by ruslo** [comment]
> If you make a hunter-packages fork, I will hunterize this package

Done: https://github.com/hunter-packages/libimagequant

I've created branch hunter-2.12.2 from upstream tag 2.12.2.

Patching hints:
* https://docs.hunter.sh/en/latest/creating-new/patch.html
