### ISSUE TITLE
Add package EntityX

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1650]
* I'm interested in package `EntityX`
* Here is official site of package https://github.com/alecthomas/entityx

* This package is using Git

* Official GitHub repository: https://github.com/alecthomas/entityx

* Used build system: CMake

* This package has next dependencies:

  * `SimpleSignal` (required, not available in Hunter https://github.com/ruslo/hunter/issues/1675)

@ruslo This package sets compilation flags that need to be removed for proper Hunterization. I need a fork to push to.

**Comment by ruslo** [comment]
> This package sets compilation flags that need to be removed for proper Hunterization. I need a fork to push to.

Done: https://github.com/hunter-packages/entityx

Branch `hunter-1.3.0` created from latest upstream tag `1.3.0`.
