### ISSUE TITLE
Add package NanoSVG

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1651]
* I'm interested in package `NanoSVG`
* Here is official site of package https://github.com/memononen/nanosvg

* This package is using Git

* Official GitHub repository: https://github.com/memononen/nanosvg

* Used build system: None (header-only)

* This package has no dependencies

**Comment by rbsheth** [comment]
@ruslo I have a working Hunterized version, if you make a fork I can push.

**Comment by ruslo** [comment]
> I have a working Hunterized version, if you make a fork I can push.

Done: https://github.com/hunter-packages/nanosvg

Branch `hunter-0.0.0-2b08dee` created from `2b08dee`.

**Comment by ruslo** [comment]
Fixed in https://github.com/ruslo/hunter/pull/1658

@bkotzz Thanks!
