### ISSUE TITLE
Add package nlohmann_fifo_map

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1652]
* I'm interested in package `nlohmann_fifo_map`
* Here is official site of package https://github.com/nlohmann/fifo_map

* This package is using Git

* Official GitHub repository: https://github.com/nlohmann/fifo_map

* Used build system: CMake

* This package has no dependencies

**Comment by rbsheth** [comment]
@ruslo I have a working Hunterized version, if you make a fork I can push.

**Comment by ruslo** [comment]
> I have a working Hunterized version, if you make a fork I can push

Done: https://github.com/hunter-packages/fifo_map

There are no releases yet, so I've created branch `hunter-0.0.0-0dfbf5d` from `0dfbf5d` commit.
