### ISSUE TITLE
Add package prometheus-cpp

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1653]
* I'm interested in package `prometheus-cpp`
* Here is official site of package https://github.com/jupp0r/prometheus-cpp

* This package is using Git

* Official GitHub repository: https://github.com/jupp0r/prometheus-cpp

* Used build system: CMake

* This package has next dependencies:

  * `civetweb` (required, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/civetweb.html)
  * `GTest` (not required, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/GTest.html)

@ruslo I have a working Hunterized version, need a fork to push to. Disabling testing eliminates the test dependencies.

**Comment by ruslo** [comment]
> I have a working Hunterized version, need a fork to push to. Disabling testing eliminates the test dependencies.

Done: https://github.com/hunter-packages/prometheus-cpp

Branch `hunter-0.6.0` created from upstream tag `v0.6.0`.
