### ISSUE TITLE
How can I specify version of python (3 or 2) for build of boost-python (how can I pass arguments to bootstrap?)

### ISSUE THREAD

**Issue by Algomorph** [ruslo/hunter#1660]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
---

* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **[Yes]**
* I'm using latest Hunter URL/SHA1. **[Yes]**

Directly related: #514

* I'm building on [Linux Ubuntu].
* [I'm using system CMake]
* I'm not using toolchain
Specific problem:

- Locally, my Hunter-based boost builds detect Python 3 by default.
- On Travis-CI server, the same builds detect Python 2 by default instead. I'm not certain why, since python3-dev is installed.
- I need Python 3 to build the python3 component, specifically, so my Travis-CI build fails.

I need to be able to specify to boost the python version.
According to various sources, this can be done by passing the information to bootstrap.sh, not to b2:

`./bootstrap.sh --with-python=/usr/bin/python3 --with-python-version=3.5 --with-python-root=/usr/lib/python3.5`

Alternatively, I can [modify user-config.jam file](https://stackoverflow.com/questions/5539557/boost-and-python-3-x).

Inspecting the Hunter [boost package documentation](https://docs.hunter.sh/en/latest/packages/pkg/Boost.html), I didn't find any way to do either one. Please, advise.

P.S. Adding PYTHON_buildid=3 (which produces b2 -s buildid=3) alone doesn't seem to do anything (buildid is [somehow related](https://stackoverflow.com/questions/28830653/build-boost-with-multiple-python-versions)).

---

**Comment by ruslo** [comment]
I guess we need new CMake option to control the behavior, similar to:
* https://docs.hunter.sh/en/latest/packages/pkg/Boost.html#cmake-options

> Alternatively, I can modify user-config.jam file.

Sounds better than adding arguments to `./bootstrap.sh`, in my opinion.

**Comment by Algomorph** [comment]
@ruslo thank you, I'm looking into what would be needed for the .jam files

**Comment by Algomorph** [comment]
@ruslo 
So, what exactly do we want, a low-level way to customize user-config.jam, such as this?
```CMake
hunter_config(
    Boost
    VERSION ${HUNTER_Boost_VERSION}
    CMAKE_ARGS
JAM_USER_CONFIG=using python : 3.6 : /usr/bin/python3 : /usr/include/python3.6m : /usr/lib ; #<potentially other lines for user_config.jam here separated by semicolons>
)
```
Or do we want something really high-level, as shown below?
```CMake
hunter_config(
    Boost
    VERSION ${HUNTER_Boost_VERSION}
    CMAKE_ARGS
 REQUESTED_PYTHON_VERSION=3.6 #attempts to find python 3.6 on the system, if it is found, configures user_config.jam with the appropriate arguments, otherwise doesn't touch user_config.jam at all
)
```

**Comment by Algomorph** [comment]
P.S. apparently, user-config.jam should be copied to / created in the [user's home directory](https://stackoverflow.com/a/45767023/844728) during the Boost build. (Verified in the [1.68 boost instructions](https://github.com/hunter-packages/boost/blob/5ad3418b0b64b9107871b61ff6405dea56f19565/tools/quickbook/doc/install.qbk).
Do we still want to make one, or would that be sort of a sandbox violation? Perhaps passing arguments to ./bootstrap.sh would be a better way, considering this?

**Comment by ruslo** [comment]
> Or do we want something really high-level, as shown below?

High-level. Variables with full paths should not be part of CMAKE_ARGS since they will be saved in cache, and cache should be relocatable.

> P.S. apparently, user-config.jam should be copied to / created in the user's home directory during the Boost build. (Verified in the 1.68 boost instructions.)

I think all work with jam file is already handled correctly, you just need to inject your part there.

This line did the trick I guess:
* https://github.com/ruslo/hunter/blob/master/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L212

**Comment by Algomorph** [comment]
Work-around: by default, the Boost build engine will use whichever python version it finds linked to "python" in the system path. Hence, if you ensure that "python" in the path links to the desired version of python, it will build the Boost Python library for the correct version.

NB: On Ubuntu, by default, python 2 and python 3 are both installed, but python is by default linked to python2.7. update_alternatives can be used to change this choice if one has sudo access. I'm not sure simply using "alias python=python3" in the shell would work, since it only changes the alias on the current shell level.

**Comment by Algomorph** [comment]
@ruslo , ага, спасибо, I can see where the file is being written to and appended with various things. 
I guess we'll want to somehow uncover if the requested python version is available.
I can see there is a very basic find_python.cmake script here:
[https://github.com/ruslo/hunter/blob/master/scripts/find_python.cmake](https://github.com/ruslo/hunter/blob/master/scripts/find_python.cmake)
It won't be sufficient. I already have some code I can adapt for this, perhaps tomorrow, originally borrowed from the OpenCV project.

Shall I make a separate cmake file, e.g. Boost/schemes/find_requested_python.cmake?

**Comment by ruslo** [comment]
> I can see there is a very basic find_python.cmake script here

This script is a workaround for some issues when Hunter used for cross-compiling. Standard root paths removed from search in this case (e.g. we don't need system macOS libraries when we are building iOS), and you can run isolated script with `find_package(PythonInterp)` call to find tools in host environment. Hence in Boost case probably `find_package(PythonInterp)` will be what we actually need.

Also in case if https://github.com/ruslo/hunter/issues/388 will be solved, then you can just do `hunter_add_package(python)` + `find_package(python CONFIG REQUIRED)`.

**Comment by ruslo** [comment]
> I think it could make sense to pass, as components, "python2" or "python3"

Components for `hunter_add_package` taken from Boost `--with-<component>` option. List of components from documentation:
* https://docs.hunter.sh/en/latest/packages/pkg/Boost.html#boost

Example from build logs (this part of log produced by Boost itself, not by Hunter):
* https://travis-ci.org/ingenue/hunter/jobs/451966777#L1393-L1424

There are no `python2` or `python3` component there so we should not use this approach.

I know that in this case `COMPONENTS` from `hunter_add_package` doesn't match `find_package`. Such peculiarities should be mentioned in documentation, e.g. see boost.math:
* https://docs.hunter.sh/en/latest/packages/pkg/Boost.html#math

> Or we could go with the original CMAKE_ARGS REQUESTED_PYTHON_VERSION=3.6 option in hunter_config.

Sounds good for me :+1:

**Comment by Algomorph** [comment]
@ruslo , please let me know if there is anything you'd like me to change in or add to the PR.
