### ISSUE TITLE
Add package cppcodec

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1674]
* I'm interested in package `cppcodec`
* Here is official site of package https://github.com/tplgy/cppcodec

* This package is using Git: https://github.com/tplgy/cppcodec

* Official GitHub repository: https://github.com/tplgy/cppcodec

* Used build system: CMake

* This package has no dependencies (header-only)

**Comment by rbsheth** [comment]
@ruslo I have a working Hunterized version, if you make a fork I can push.

**Comment by ruslo** [comment]
> if you make a fork I can push

Done: https://github.com/hunter-packages/cppcodec

**Comment by xsacha** [comment]
This issue should be closed. Came across it but it's already merged in.

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/pull/1676
