### ISSUE TITLE
Add package SimpleSignal

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1675]
* I'm interested in package `SimpleSignal`
* Here is official site of package https://github.com/larspensjo/SimpleSignal

* This package is using Git: https://github.com/larspensjo/SimpleSignal

* Official GitHub repository: https://github.com/larspensjo/SimpleSignal

* Used build system: None

* This package has no dependencies

I want to add EntityX but discovered this dependency copied into the source there: https://github.com/alecthomas/entityx/blob/master/entityx/3rdparty/simplesignal.h

@ruslo Guess we need a fork for this one too.

**Comment by ruslo** [comment]
> Guess we need a fork for this one too.

Done: https://github.com/hunter-packages/SimpleSignal
