### ISSUE TITLE
Add package vectorial

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1677]
* I'm interested in package `vectorial`
* Here is official site of package https://github.com/scoopr/vectorial

* This package is using Git: https://github.com/scoopr/vectorial

* Official GitHub repository: https://github.com/scoopr/vectorial

* Used build system: Visual Studio Solution/None

* This package has no dependencies

@ruslo Need a fork please. 😄

**Comment by ruslo** [comment]
> Need a fork please

Done: https://github.com/hunter-packages/vectorial
