### ISSUE TITLE
Add package MathFu

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1678]
* I'm interested in package `MathFu`
* Here is official site of package https://github.com/google/mathfu

* This package is using Git: https://github.com/google/mathfu

* Official GitHub repository: https://github.com/google/mathfu

* Used build system: CMake/custom

* This package has next dependencies:

  * `vectorial` (required, not available in Hunter, corresponding "New package" request: https://github.com/ruslo/hunter/issues/1677)
  * `fplutil` (optional??, not available in Hunter, not sure if we should add or bypass it since it is just a collection of build scripts for MathFu https://github.com/google/fplutil)

@ruslo I have a fork but I am not sure SIMD is working. We can work on a fork and see.

**Comment by ruslo** [comment]
> We can work on a fork and see

Fork created: https://github.com/hunter-packages/mathfu
