### ISSUE TITLE
Add package draco

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1679]
* I'm interested in package `draco`
* Here is official site of package https://github.com/google/draco

* This package is using Git: https://github.com/google/draco

* Official GitHub repository: https://github.com/google/draco

* Used build system: CMake

* This package has no dependencies

**Comment by rbsheth** [comment]
@ruslo I think draco needs a fork too, since they don't export targets in their CMakeLists.txt.

**Comment by ruslo** [comment]
Done: https://github.com/hunter-packages/draco
