### ISSUE TITLE
android arm64-v8a "unrecognized command line option '-m64'"

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#168]
I'm testing a new arm64 android toolchain 
```
set(ANDROID_NDK_VERSION "r10e")
set(ANDROID_NATIVE_API_LEVEL "21")
set(ANDROID_ABI "arm64-v8a")
```
And hit the following error when building:
```
aarch64-linux-android-g++: error: unrecognized command line option '-m64'
gcc.compile.c++ bin.v2/libs/filesystem/build/gcc-ndk/release/link-static/threading-multi/operations.o

    "/Users/dhirvonen/pkg/android/android-ndk-r10e/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-g++"  -ftemplate-depth-128 -O3 -finline-functions -Wno-inline -Wall -m64 -fexceptions -frtti -Wno-psabi --sysroot=/Users/dhirvonen/pkg/android/android-ndk-r10e/platforms/android-21/arch-arm64 -funwind-tables -fsigned-char -no-canonical-prefixes -fdata-sections -ffunction-sections -Wa,--noexecstack -std=c++11 -DANDROID -isystem  /Users/dhirvonen/pkg/android/android-ndk-r10e/platforms/android-21/arch-arm64/usr/include -isystem  /Users/dhirvonen/pkg/android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem  /Users/dhirvonen/pkg/android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include -isystem  /Users/dhirvonen/pkg/android/android-ndk-r10e/sources/cxx-stl/gnu-libstdc++/4.9/include/backward
```
aarch64-linux-android-g++ should already be building 64 bit, so presumably this argument can just be dropped.  Haven't looked through the boost stuff yet, so I'll try to track down where this is added, unless someone can point me there first.

UPDATE: Found this, but can't seem to find the right place to locate the patch.

http://rpmfind.net/linux/RPM/opensuse/factory/x86_64/boost-devel-32bit-1.58.0-2.1.x86_64.html
- add boost-aarch64-flags.patch: Avoid using -m64

Found it:
https://build.opensuse.org/package/view_file/devel:libraries:c_c++/boost/boost-aarch64-flags.patch?expand=1

I applied the patch and created a new recipe and it appears to be working.  I see the 1.58.0 hunter recipe is pointing to the official sourceforge URL, so it isn't easy to patch.  We could either import 1.58.0 on github and apply the patch there, or possibly just silence the "unrecognized option" error by passing the following option through to the b2 build:

```
-Wno-error=unknown-warning
```

**Comment by ruslo** [comment]
As we've disscussed in https://github.com/ruslo/hunter/issues/169 you can send your patch to branch `boost-1.58.0` of https://github.com/hunter-packages/boost/tree/boost-1.58.0

**Comment by headupinclouds** [comment]
This patch has been included in the current hunter-packages branch, so I'm closing this one.

**Comment by ruslo** [comment]
> This patch has been included in the current hunter-packages branch

@headupinclouds currently clean version of boost 1.58 used: https://github.com/hunter-packages/boost/commits/boost-1.58.0

**Comment by headupinclouds** [comment]
You are right.  I've just submitted a pull request.

**Comment by ruslo** [comment]
@headupinclouds Is this one fixed by https://github.com/ruslo/hunter/commit/719dd45ffb262af4ae94c1cd7ece24e9a208fd55?

**Comment by headupinclouds** [comment]
Yes.  Closed.
