### ISSUE TITLE
Portable PATCH_COMMAND for minor repository changes

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#169]
While looking into #168 I found a 3 line patch to boost 1.58.0 that fixes arm64 builds of Android.  I'm currently importing boost 1.58.0 to git in order to apply the change and host the release.  I contemplated just hosting the patched source in my public Dropbox folder and pointer the hunter recipe to that, but that seems a little out of spirit.  The simplest/cleanest thing would be to keep the hunter recipe pointing to the official sourceforge URL and just create a custom download scheme with support for applying standard patches. CMake doesn't have internal support for patches, but it does provide the PATCH_COMMAND for ExternalProject_Add.  That could do the job, but that introduces a slightly messy external dependency on a patch tool, which I don't think we can rely on for all host platforms.  I suppose that tool could be managed by hunter itself.  I'd appreciate hearing any thoughts on this.  For now I'm going to go with the brute force approach of cloning and patch boost in git.
##

**Comment by pretyman** [comment]
From previous comments from @ruslo ( https://github.com/ruslo/hunter/issues/149#issuecomment-104273862 ) I understood that either your dropbox approach is preferred, or you could send your patches to his boost repo. I also ended up with a separate boost repo for Android with boost 1.57 ( https://github.com/pretyman/boost ), although I am not sure the patches were needed as I had just collected them around the internet.

**Comment by headupinclouds** [comment]
Thanks for the pointer.  I guess the patch stuff could get messy.  I've forked a 1.58.0 boost on github and will apply the patch there in a hunter branch before building a release (that could eventually be migrated to hunter-packages).

**Comment by ruslo** [comment]
>  I've forked a 1.58.0 boost on github and will apply the patch there in a hunter branch before building a release

I vote for this too. See no point of adding patches to the repo since we can fork/release easily. See https://github.com/hunter-packages/boost (take a look at different branches).

**Comment by headupinclouds** [comment]
Done.  Sitting in my hunter fork.  I'll push this over tomorrow.

**Comment by ruslo** [comment]
> See https://github.com/hunter-packages/boost (take a look at different branches)

Usually I make a clean commit of unpacked `boost.tar.gz` archive, e.g.: https://github.com/hunter-packages/boost/commit/7c83bba90c02ea23276144fcbcf60d002149e7da

then I remove docs: https://github.com/hunter-packages/boost/commit/4a00b807b3994ebec36de6c718ff956e2c1ea181

and tests: https://github.com/hunter-packages/boost/commit/9ddea2c1f275bd128c1843ac238f6b9525b23b85

This change doesn't affect build procedure but reduce size significantly. E.g. boost 1.58 original is about 68MB and cut version is 19MB.

@headupinclouds Just for your information I've pushed cut version of Boost 1.58 for testing: https://github.com/ruslo/hunter/commit/1d67ed805458f3b9cd66297171a92f8bb1c74c81
