### ISSUE TITLE
Can't generate x64 project because of irrXML

### ISSUE THREAD

**Issue by NukeBird** [ruslo/hunter#1695]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

I have a pretty simple CMakeLists:
```cmake
cmake_minimum_required(VERSION 3.2)

### Hunter snapshot that will be used ###
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.83.tar.gz"
    SHA1 "12dec078717539eb7b03e6d2a17797cba9be9ba9"
)

project(DamnTracer)

hunter_add_package(glm)
find_package(glm REQUIRED)

hunter_add_package(SDL2)
find_package(SDL2 CONFIG REQUIRED)

hunter_add_package(Assimp)
find_package(Assimp CONFIG REQUIRED)
 
add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} Assimp::assimp glm SDL2::SDL2main SDL2::SDL2)
```
which works great for x32. But because of irrXML (I guess it is dependency of Assimp?) I can't generate project using this command:
`cmake .. -G "Visual Studio 15 2017" -A x64 -T host=x64 -DHUNTER_STATUS_DEBUG=ON`

Is here any official way to fix such problem? Or atleast some "dirty hack"? =)

**Comment by NukeBird** [comment]
https://github.com/ruslo/hunter/issues/1264
> irrXML testing table:
> 
> * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2963
> 
> x64 variant excluded from testing:
> 
> * https://github.com/ingenue/hunter/blob/4a950adbb767016b649b848a45027a5a203c0ac1/appveyor.yml#L20-L22
> 
> Meaning it's kind of a known issue and somebody have to fix it.

Can someone fix it, please?

**Comment by ruslo** [comment]
> Can someone fix it, please?

From https://github.com/ruslo/hunter/wiki/error.external.build.failed :

> If similar toolchain is excluded (or not present at all) then the problem is known, hence **there is no need to report bug if you're not planning to fix it yourself**.
