### ISSUE TITLE
Support CMAKE_OSX_ARCHITECTURES for libxml2

### ISSUE THREAD

**Issue by ikerr** [ruslo/hunter#1696]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **[Yes]**
* I'm using latest Hunter URL/SHA1. **[Yes]**

* I've created SSCCE GitHub repository to reproduce the issue: https://github.com/ikerr/hunter-libxml2

* I'm building on OSX.
* I'm using official CMake release
* CMake version: 3.12.3

* I'm using my toolchain: https://github.com/ikerr/hunter-libxml2/blob/master/cmake/toolchain.cmake

I'm using next command line on generate step:
```
cmake -DCMAKE_TOOLCHAIN_FILE=`pwd`/../cmake/toolchain.cmake -DCMAKE_MODULE_PATH=`pwd`/../cmake ..
```

---

Hunter does not respect `CMAKE_OSX_ARCHITECTURES` (specified in the toolchain file) when building libxml2. As a result, building the above project (which sets `CMAKE_OSX_ARCHITECTURES` to "i386;x86_64") results in the following linker error:

```
ld: warning: ignoring file /Users/<redacted>/.hunter/_Base/12dec07/d0f6aab/fa44168/Install/lib/libxml2.a, file was built for archive which is not the architecture being linked (i386): /Users/<redacted>/.hunter/_Base/12dec07/d0f6aab/fa44168/Install/lib/libxml2.a
Undefined symbols for architecture i386:
  "_xmlParseDoc", referenced from:
      _main in main.c.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I believe the root cause is that `hunter_autotools_project` does not support `CMAKE_OSX_ARCHITECTURES`:

https://github.com/ruslo/hunter/blob/0aa7dbe88463ffe0d296f9de086ec7fac8f2f57d/cmake/modules/hunter_autotools_project.cmake

(Note that it does appear to support `IPHONEOS_ARCHS`.)

This issue likely affects other packages using `hunter_autotools_project`.

**Comment by ruslo** [comment]
This issue will be closed because the required template file [ISSUE_TEMPLATE.md][1] was ignored. Please read and fill carefully all parts of this file while submitting a bug report.

Thanks for understanding.

[1]: https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE.md

**Comment by ikerr** [comment]
@ruslo I re-read through the issue template that you linked, but to me it's not clear what is missing from the above issue report. I'd be happy to resubmit with any missing information. Can you point me in the right direction?

**Comment by ruslo** [comment]
From [error.external.build.failed](https://github.com/ruslo/hunter/wiki/error.external.build.failed):

> Take a look at pkg.NAME CI testing table. If similar toolchain is excluded (or **not present at all**) then the problem is known, hence **there is no need to report bug** if you're not planning to fix it yourself.

**Comment by ruslo** [comment]
> The problem is that Hunter is building libxml2 for the wrong architectures (because it ignores CMAKE_OSX_ARCHITECTURES in this case).

> The only OS X test that I see commented out in the .travis.yml file for pkg.libxml2

> So, isn't this a new issue?

Logic is the same, there are quite a lot of features and use cases that are not covered by CI testing (was not originally designed or is not working/buggy). It make a very little sense to report an issue about it, please work on the fix, send pull request with new example (if needed), toolchain for testing and package update instead. Thanks.
