### ISSUE TITLE
Add package utf8

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1704]
* I'm interested in package `utf8`
* Here is official site of package http://utfcpp.sourceforge.net/

* This package is using SVN: https://sourceforge.net/p/utfcpp/code/HEAD/tree/v2_0/
Note that v2.3.4 is the latest released version and the version I am interested in.

* Used build system: None (header-only)

* This package has no dependencies

@ruslo I can work on a Hunterized fork.

**Comment by ruslo** [comment]
> I can work on a Hunterized fork

> Note that v2.3.4 is the latest released version and the version I am interested in

I've created https://github.com/hunter-packages/utf8 with branch `hunter-2.3.4` based on `v2.3.4` upstream release.

**Comment by hjmallon** [comment]
> Released: https://github.com/ruslo/hunter/releases/tag/v0.23.92

I believe this is done here https://github.com/ruslo/hunter/pull/1711
