### ISSUE TITLE
Boost + hunter_dump_cmake_flags.cmake lacks support for -fvisibility, -ffunction-sections, -fdata-sections

### ISSUE THREAD

**Issue by gkontsevich** [ruslo/hunter#1706]
Hey @ruslo 

Thanks for all your help and for making Hunter :) Continuing from the latest comments here: https://github.com/ruslo/hunter/issues/906

PR https://github.com/ruslo/hunter/pull/1204 added the ability to configure Boost modules through `b2`, however compiler-flags coming from toolchain-files seem to have a very incomplete mechanism for forwarded to `b2`.

@jdonald showed an edge case where on iOS the default standard library chosen by the compiler/`b2` ended up being different from the one specified in `CMAKE_CXX_FLAGS` in the toolchain file so Boost ended up with a different standard library from the rest of the build and the build failed on us.

However the issue goes further and we can't forward many flags like `-fvisibility`, `-ffunction-sections`, `-fdata-sections`. These aren't build-breaking issues (like forwarding the standard library) so they've probably slipped under the radar thus far

On [these lines ](https://github.com/ruslo/hunter/blob/master/cmake/projects/Boost/schemes/url_sha1_boost_ios_library.cmake.in#L151-L153)
a few flags get forwarded to `b2` but the lines are directly after a call to `hunter_dump_cmake_flags()` which seems to only "manually" preserve a select few flags  before any forwarding happens

We're a bit unclear on what a good permanent solution for this would be (I'm a bit unclear on why the dump needs to happen in the first place :) ). For the time being, crudely hard coding flags into the Boost configuration works .. but ideally this would be more hunterized and handled dynamically from the toolchain file.

Any help or insight you can provide would be appreciated :)

**Comment by ruslo** [comment]
> I'm a bit unclear on why the dump needs to happen in the first place

`hunter_dump_cmake_flags` module needed because not all flags that used in final compile/link command reflected in `CMAKE_CXX_FLAGS`. E.g. if you set `CMAKE_CXX_STANDARD` to `11` then **if you project is CMake based** you will see that `-std=c++11` flag added to build (it was added by **internal** CMake mechanism). However if it's a custom build scheme (just like Boost) then somebody have to translate `CMAKE_CXX_STANDARD=11` into `-std=c++11`. Robust solution is to add such functionality to CMake (so CMake can return final compile/link flags basing on currect CMake variables state), as far as I know there is no such feature at this moment so we have to do everything by hands.

> an edge case where on iOS the default standard library chosen by the compiler/b2 ended up being different from the one specified in CMAKE_CXX_FLAGS in the toolchain file

> issue goes further and we can't forward many flags like -fvisibility, -ffunction-sections, -fdata-sections

Let's focus on one problem at a time. What about "default standard library chosen"? Can you create a minimal example to reproduce and all details about setup you've used? Standard details I'm interested in can be found here: https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs and here: https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE.md

**Comment by gkontsevich** [comment]
Thanks for getting back so fast @ruslo :)

 What you're describing sounds like some flags end up missing from the `CMAKE_CXX_FLAGS` list and need to be added manually. I guess I understand that side of things - but why do the already existing flags need to be flushed? Can't they be forwarded as-is into `b2`?

@jdonald cooked up an example (big thanks!):
https://github.com/jdonald/hunter-issues
I won't really repeat the details b/c his `README.md` thoroughly explains how to replicate the problem

I'd also just say that this standard library bug isn't a huge issues for us b/c those are old systems we can stop supporting. We more concerned about the other flags mentioned in the issue title `-fvisibility`, `-ffunction-sections`, `-fdata-sections` b/c that is affecting all systems

**Comment by ruslo** [comment]
> I guess I understand that side of things - but why do the already existing flags need to be flushed? Can't they be forwarded as-is into b2?

They are not flushed, please show the example of what you mean.

>  I won't really repeat the details b/c his README.md thoroughly explains how to replicate the problem

> Standard details I'm interested in can be found here: https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs and here: https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE.md

CMake version, Xcode version, OS version, log with `HUNTER_STATUS_DEBUG=ON`.

> -DCMAKE_TOOLCHAIN_FILE="${POLLY_DIR}"/osx-10-7.cmake

I guess it's Xcode 4.6.3, pretty old stuff, I can't even launch it on my machine:
![01](https://user-images.githubusercontent.com/4346993/52234064-d3e84000-28d1-11e9-91d0-5b9419cc4587.png)

From my understanding, you don't have to use ancient Xcode to build an app for macOS 10.7. You can use something fresh and only set deployment target to 10.7, for example:
- https://github.com/ruslo/polly/blob/master/osx-10-10-dep-10-7.cmake

**Comment by geokon-gh** [comment]
Thank you for testing it out :) 
Sorry if there was some miscommunications but we are not running Xcode `4.6.3` 

To fill in the missing parts:
We are running -
`CMake 3.13.14`
Xcode Version `10.1` (10B61)
on macOS `10.14.2` Mojave

Logs have now been added here: https://github.com/jdonald/hunter-issues/releases/tag/logfiles
Hope this helps make the problem clearer

**Comment by gkontsevich** [comment]
Thank you for testing it out :) 
Sorry if there was some miscommunications but we are not running Xcode `4.6.3` 

To fill in the missing parts:
We are running -
`CMake 3.13.14`
Xcode Version `10.1` (10B61)
on macOS `10.14.2` Mojave

Logs have now been added here: https://github.com/jdonald/hunter-issues/releases/tag/logfiles
Hope this helps make the problem clearer

**Comment by ruslo** [comment]
> https://github.com/jdonald/hunter-issues/releases/download/logfiles/osx-10-7.log

```
-- [hunter *** DEBUG *** 2019-02-04T14:10:06] [/Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono] > "/Applications/CMake.app/Contents/bin/cmake" "-C/Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/cache.cmake" "-C/Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/args.cmake" "-H/Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono" "-B/Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/Build" "-DCMAKE_TOOLCHAIN_FILE=/Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/toolchain.cmake" "-GXcode" "-DCMAKE_MAKE_PROGRAM=/usr/bin/xcodebuild"
loading initial cache file /Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/cache.cmake
loading initial cache file /Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/args.cmake
-- [polly] Used toolchain: Xcode 10.7 target / LLVM Standard C++ Library (libc++) / c++11 support
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is unknown
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
-- Detecting CXX compile features
-- Detecting CXX compile features - done

[hunter ** INTERNAL **] Unexpected empty string
[hunter ** INTERNAL **] [Directory:/Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at /Users/jdonald/.hunter/_Base/Download/Hunter/0.23.95/58b72c4/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /Users/jdonald/.hunter/_Base/Download/Hunter/0.23.95/58b72c4/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  /Users/jdonald/.hunter/_Base/Download/Hunter/0.23.95/58b72c4/Unpacked/cmake/modules/hunter_assert_not_empty_string.cmake:9 (hunter_internal_error)
  CMakeLists.txt:40 (hunter_assert_not_empty_string)
```

Error occurs here as far as I understand (please check internal CMakeLists.txt to be sure):
- https://github.com/ruslo/hunter/blob/v0.23.99/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L40

Something wrong with toolchain or CMake or both:
```
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is unknown
```

Should be something like this (see for example https://travis-ci.org/ingenue/hunter/jobs/488905963):
```
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
```

**Comment by gkontsevich** [comment]
Thanks again for checking it out, but the error is spelled out in `osx-10-7-chrono-CMakeError.log`

```
Ld /Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/Build/CMakeFiles/3.13.4/CompilerIdCXX/CompilerIdCXX normal x86_64 (in target: CompilerIdCXX)
    cd /Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/Build/CMakeFiles/3.13.4/CompilerIdCXX
    export MACOSX_DEPLOYMENT_TARGET=10.7
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -L/Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/Build/CMakeFiles/3.13.4/CompilerIdCXX -F/Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/Build/CMakeFiles/3.13.4/CompilerIdCXX -filelist /Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/Build/CMakeFiles/3.13.4/CompilerIdCXX/CompilerIdCXX.build/Debug/CompilerIdCXX.build/Objects-normal/x86_64/CompilerIdCXX.LinkFileList -mmacosx-version-min=10.7 -Xlinker -object_path_lto -Xlinker /Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/Build/CMakeFiles/3.13.4/CompilerIdCXX/CompilerIdCXX.build/Debug/CompilerIdCXX.build/Objects-normal/x86_64/CompilerIdCXX_lto.o -Xlinker -dependency_info -Xlinker /Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/Build/CMakeFiles/3.13.4/CompilerIdCXX/CompilerIdCXX.build/Debug/CompilerIdCXX.build/Objects-normal/x86_64/CompilerIdCXX_dependency_info.dat -o /Users/jdonald/.hunter/_Base/58b72c4/70e2358/380b461/Build/Boost/__chrono/Build/CMakeFiles/3.13.4/CompilerIdCXX/CompilerIdCXX
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
ld: library not found for -lstdc++
clang: error
: linker command failed with exit code 1 (use -v to see invocation)
```
again, this is a flag propagation issue.  `-fvisibility=hidden` is also not getting pushed through - it's just not generating an error (this is a more serious issue for us b/c it affect more targets than the *libstdc++/libc++* issue)

**Comment by ruslo** [comment]
> but the error is spelled out in `osx-10-7-chrono-CMakeError.log`

@gkontsevich I don't understand where that log comes from.

 I'm not interested in analyzing random logs with an opaque setup. Why did you attach iOS log there? Why do you keep asking about `-fvisibility=hidden`? I've already said that we should focus on libc++ issue first.

Please follow this guide step by step carefully and create a minimal example, remove all unrelated stuff:
- https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs

It will be better if you will reproduce this issue using Travis CI. If you're using custom Polly toolchains please submit it first to https://github.com/ruslo/polly.

Thanks.

**Comment by gkontsevich** [comment]
Sorry for the frustration @ruslo , but I don't understand the confusion
This is the `CMakeError.log` from the end of the file you linked just before

At the end of https://github.com/jdonald/hunter-issues/releases/download/logfiles/osx-10-7.log
it reads
```
-- Configuring incomplete, errors occurred!
See also "/Users/jdonald/hunter-issues/build-osx-10-7/CMakeFiles/CMakeOutput.log".
See also "/Users/jdonald/hunter-issues/build-osx-10-7/CMakeFiles/CMakeError.log".
```
This is the file from the last line there. Maybe the leading  `osx-10-7-` was confusing ?

iOS is included b/c that also has this issue. Please see the root README again where we've tried to be as clear as possible about the issue: https://github.com/jdonald/hunter-issues

We can focus on the  `libc++` issue first, my point was simply that it's just the same issue as with all the other flags and it seems the fix should be comprehensive

(Could you reopen the issue? The problem is still outstanding)

**Comment by ruslo** [comment]
> This is the `CMakeError.log` from the end of the file you linked just before

That part is not interesting, we have the problem before. See `The CXX compiler identification is unknown` issue. If you will read [contributing](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) guide you will see that there is no requirement to add any extra files.

> iOS is included b/c that also has this issue

I said a few times that we should focus on one problem. Why exactly do you think that adding the log with another platform is a good idea?

> Could you reopen the issue?

No, please open new issue. Clean-up your example, remove unrelated stuff, remove unrelated logs.
Also:
- If you're using custom Polly toolchains please submit it first to https://github.com/ruslo/polly.
- Fix `The CXX compiler identification is unknown` issue. From my understanding this issue can be reproduced by plain simple CMakeLists.txt:
```cmake
cmake_minimum_required(VERSION 3.2)
project(foo)
```
as you can see there is no Hunter here, it's just CMake/Xcode and your toolchain.
