### ISSUE TITLE
FetchContent

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#1709]
I just stumbled upon FetchContent ([Documentation](https://cmake.org/cmake/help/v3.13/module/FetchContent.html)). It's available since CMake 3.11. Could we use this in Hunter?

**Comment by ruslo** [comment]
> Could we use this in Hunter?

How? Why? :) What new feature it will offer?

**Comment by NeroBurner** [comment]
took a closer look at the function. I thought it downloads and builds an external project, but I think it only downloads and extract the source and makes it available to use at configuration time (for example using `add_subdirectory`).

Maybe it could be handy with the `hunter_download` module

**Comment by NeroBurner** [comment]
Maybe I can use this to download the `HunterGate.cmake` file. A friend of mine complained, that there is no way for him to know if he has to update this HunterGate file. He said he would like to have the gate update and hunter update in one snippet which he can easily update. I'm thinking of something like this

```cmake
if(HUNTER_ENABLED)
  FetchContent(HunterGate URL and stuff we need to declare)
  include(${HunterGate_SOURCE_DIR}/HunterGate.cmake)
else()
  # declare dummies for HunterGate and hunter_add_package
  function(HunterGate)
  endfunction()
  function(hunter_add_package)
  endfunction()
endif()
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.89.tar.gz"
    SHA1 "a370290a8b32987755a36d64807bf8c7f5b61730"
)
```

**Comment by ruslo** [comment]
>  there is no way for him to know if he has to update this HunterGate file

Logic is simple, if everything works fine and as expected, then there is no need for HunterGate update.

> if(HUNTER_ENABLED)

`HUNTER_ENABLED` set in HunterGate.cmake. You have to explicitly declare `option(HUNTER_ENABLED ...)` in this case.

> declare dummies for HunterGate and hunter_add_package

That's something that HunterGate will do for you.

Most of the code snippets I saw that do automatic download of HunterGate is either not correct or size of the code is compared to the size of HunterGate (300 lines of code to download file with 500 lines of code). For this reason I strongly against automatic HunterGate download.

**Comment by ruslo** [comment]
Closing inactive discussion.
