### ISSUE TITLE
allowing optional with hunter_find_helper and hunter_find_helper_framework 

### ISSUE THREAD

**Issue by mchiasson** [ruslo/hunter#1712]
I was trying to do something like this for multiple platform (Android, iOS/tvos/OSX, Linux, Windows, etc):

```
find_package(gles2)
find_package(gles3)
find_package(metal)
find_package(Vulkan)

if(TARGET Vulkan::Vulkan)
    target_link_libraries(...... Vulkan::Vulkan)
elseif(TARGET metal::metal)
    target_link_libraries(...... metal::metal)
elseif(TARGET gles3::gles3)
    target_link_libraries(...... gles3::gles3)
elseif(TARGET gles2::gles2)
    target_link_libraries(...... gles2::gles2)
endif()
```
where it looks for whatever it can find, and links the best one it can find. However, it generates the following errors:
```
[hunter ** FATAL ERROR **] 'find_package(gles2)' should be called with REQUIRED
[hunter ** FATAL ERROR **] 'find_package(gles3)' should be called with REQUIRED
[hunter ** FATAL ERROR **] 'find_package(metal)' should be called with REQUIRED
```
which comes from here:

https://github.com/ruslo/hunter/blob/master/cmake/modules/hunter_find_helper.cmake#L58-L60
and here if i was trying
https://github.com/ruslo/hunter/blob/master/cmake/modules/hunter_find_helper_framework.cmake#L45-L47

**Comment by mchiasson** [comment]
at least, cmake's built-in `FindVulkan.cmake` works as expected.

**Comment by mchiasson** [comment]
you're going to need something like this in the end:
```
include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments
find_package_handle_standard_args(${package_name} DEFAULT_MSG _hunter_library _hunter_header)
```
and replace
```
  unset(_hunter_library CACHE)
  unset(_hunter_header CACHE)
```
by
```
  mark_as_advanced(_hunter_library _hunter_header)
```

**Comment by mchiasson** [comment]
Something like this definitely works 

[hunter_find_helper.zip](https://github.com/ruslo/hunter/files/2766752/hunter_find_helper.zip)

however, i have not tested the hunter_find_helper_framework changes I made due to the current unavailability to an OSX machine.

If you agree with this, I can PR it for you.

**Comment by ruslo** [comment]
> where it looks for whatever it can find, and links the best one it can find

That's against Hunter design, see:
* https://docs.hunter.sh/en/latest/faq/interaction-with-other-package-managers.html
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#environment

Originally `hunter_find_helper` was created for finding libraries that should **always** present in system, hence `REQUIRED` is necessary, and `hunter_find_helper_framework` is just a syntax sugar for `target_link_libraries(... -framework something)`.

**Comment by ruslo** [comment]
Closing inactive discussion.
