### ISSUE TITLE
There are a problem with the file encoding type in ethash~

### ISSUE THREAD

**Issue by tjkim0706** [ruslo/hunter#1716]
I am studying "aleth" in "windows 10 pro" environment.
However, I am worried about the following error during the build.

"C:\\.hunter\_Base\c4cfcc0\e941b8e\402d68a\Build\ethash\Source\lib\ethash\progpow.cpp"
Since this file(progpow.cpp) is only UTF-8 encoded, the following error occurs.
All other files are ANSI encoded.
Please correct this problem.

---

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/c4cfcc0/e941b8e/402d68a/Build/ethash
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.23.44/c4cfcc0/Unpacked/cmake/projects/ethash]

**Comment by headupinclouds** [comment]
You will probably have to resolve the issue in the project repository and then update the package with a PR to hunter.  It might be easiest to work through the build directly in the repo.

* https://github.com/chfast/ethash
* https://docs.hunter.sh/en/latest/creating-new/update.html

**Comment by NAKsir-melody** [comment]
How about convert files encoding your self?  most editors support it.

**Comment by tjkim0706** [comment]
> How about convert files encoding your self? most editors support it.

That step is to build into the VisualStudio environment.
I knew the problem and tried to fix it.
However, the hunterPackage updates with the problem part in the repo each time.

please, any other advice too.
thank you~ all~

**Comment by tjkim0706** [comment]
> You will probably have to resolve the issue in the project repository and then update the package with a PR to hunter. It might be easiest to work through the build directly in the repo.
> 
> * https://github.com/chfast/ethash
> * https://docs.hunter.sh/en/latest/creating-new/update.html

Can I do without permission?

**Comment by tjkim0706** [comment]
I recompiled "aleth branch:release/1.4" yesterday and I succeeded in building it.
After changing the encoding type of some files.
Other versions of this issue have not yet been resolved.

https://github.com/ethereum/aleth/issues/5413

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
