### ISSUE TITLE
Feature: Support external Android SDK or binary download

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#172]
This could use something similar to the environment variable check for a user installed ${HUNTER_ROOT} or ${SUGAR_ROOT}.   Maybe ${HUNTER_ANDROID_SDK_ROOT}?  I'm not exactly sure which packages are built for an android apk, but I'm guessing it is some subset of these:

Android-Apk
Android-Build-Tools
Android-Google-APIs
Android-Google-APIs-Intel-x86-Atom-System-Image
Android-Google-Repository
Android-Intel-x86-Atom-System-Image
Android-Modules
Android-SDK
Android-SDK-Platform
Android-SDK-Platform-tools
Android-SDK-Tools
Android-Support-Repository
Sources-for-Android-SDK

**Comment by ruslo** [comment]
I'm not sure I understand the question exactly.

> Maybe ${HUNTER_ANDROID_SDK_ROOT}?

You already can use `ANDROID-SDK_ROOT` variable. See [Android-SDK](https://github.com/hunter-packages/android-sdk/blob/master/CMakeLists.txt) for example. May be variable name looks quite ugly, it's combination of `TOUPPER` + append `_ROOT`. We can add `s,-,_,g` operation and name will be `ANDROID_SDK_ROOT` (?)

**Comment by headupinclouds** [comment]
Excellent.  Thanks for point me there.
