### ISSUE TITLE
ROS

### ISSUE THREAD

**Issue by acasadom** [ruslo/hunter#1721]
Hello
I am starting to play with ROS and using hunter for this seems a very good idea, however there still are a few repos in the todo lists and I have also seen that Lukas Solanka's repo differs from hunter and is having a couple of this ROS packages already integrated.

I wonder if this issue is a work in progress or has been just abandon in the way it is..

**Comment by ruslo** [comment]
> I wonder if this issue is a work in progress or has been just abandon in the way it is..

You should ask @lsolanka

**Comment by lsolanka** [comment]
Hi, sorry, a job/country and as a result life change :-) happened so I had to put this on hold.

There still is quite a few packages to do, related to ros_comm.

**Comment by lsolanka** [comment]
There's issue #1397 which contains the current state of the work. Might be good to close this and continue discussion there.

I think all the packages necessary to hunterize ros_comm are present but simply need to be integrated to the hunter ci system and pull requests made. Feel free to follow the standard documentation to create one for e.g. class_loader, rosconsole, pluginlib if you have some time.

**Comment by acasadom** [comment]
Hi Lukas,
  I have seen that in your forked repo for hunter you have a ros_comm package. is it working?

I am not an expert, neither in ROS neither in cmake. I am just having a big "project" with a lot of 3th-party dependencies and I would like to use hunter to handle this complexity. I am learning cmake, hunter and ROS as I go. 

I am thinking in trying to continue your work and see if I can make the "project" work, it has more ROS dependencies , for instance ros_perception,  but maybe I can manage to have some time to try this.

can I take you repo as an starting point to learn how to integrate ROS in hunter? 
are you aware of any "hidden issue in ROS" that could make this approach of using hunter not be usable?

Of course if I am able to make it work I will ask Ruslan to add all the new packages I would need to hunterise..
