### ISSUE TITLE
ZLIB doesn't pass tests with analyze-cxx17

### ISSUE THREAD

**Issue by hjmallon** [ruslo/hunter#1724]
ZLIB is a required lib for OpenEXR (https://github.com/ruslo/hunter/issues/361) but the tests cannot pass as ZLIB 1.2.8 fails the analyze-cxx17 test. I tested this by pushing the latest pkg.templates to the ZLIB branch on my fork and running appveyor/travis. Log from travis attached.
[travislog.txt](https://github.com/ruslo/hunter/files/2808934/travislog.txt)

**Comment by hjmallon** [comment]
The specific thing mentioned is fixed upstream (tested in v1.2.11). But there are (according to clang analyze in xcode at least) two further issues which are false positives.

**Comment by ruslo** [comment]
> he tests cannot pass as ZLIB 1.2.8 fails the analyze-cxx17 test

If you're not planning to fix all analyzer issues just exclude the toolchain from testing:
- https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#excluding-tests

**Comment by hjmallon** [comment]
The above Pull Req disables the test. I would like to look at rebasing the package to 1.2.11 as well. Please could you open a hunter-1.2.11 branch on the hunter-packages zlib repo?

**Comment by ruslo** [comment]
> Please could you open a hunter-1.2.11 branch on the hunter-packages zlib repo?

Done: https://github.com/hunter-packages/zlib
