### ISSUE TITLE
Add libusb-1.0

### ISSUE THREAD

**Issue by hjmallon** [ruslo/hunter#1732]
* I'm interested in package `libusb-1.0`
* Here is official site of package https://libusb.info/
* This package is using Git: https://github.com/libusb/libusb
* Used build system: autotools
* This package depends on udev on Linux, CoreFoundation and IOKit on macOS

**Comment by hjmallon** [comment]
Requirement on libudev makes this a little difficult to build. I don't think it makes sense to build systemd in Hunter? But maybe that is the 'correct' method?

Also this is lgpl-2 so people may want to build it dynamically.

**Comment by ruslo** [comment]
> Requirement on libudev makes this a little difficult to build. I don't think it makes sense to build systemd in Hunter? But maybe that is the 'correct' method?

As a workaround you can use dependency from the system, e.g.:
- https://docs.hunter.sh/en/latest/packages/pkg/OpenCL.html#pitfalls

But in general yes, it should be added to Hunter:
- https://docs.hunter.sh/en/latest/faq/interaction-with-other-package-managers.html

> Also this is lgpl-2 so people may want to build it dynamically.

It's not a problem:
- https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-build-shared-libs

**Comment by sjdrc** [comment]
Hey @ruslo, I'm working on this. The github project name is libusb, but the build library and generated Config.cmake file are both named libusb-1.0. Which name would you prefer the hunter package to have?

**Comment by ruslo** [comment]
I guess you should use `libusb` as a name because if the version changes the config files will have `libusb-2.0`, but the project name should remain.

**Comment by sjdrc** [comment]
Will need https://github.com/ruslo/hunter/issues/1828 to be fixed first.

**Comment by sjdrc** [comment]
@ruslo closed by https://github.com/ruslo/hunter/commit/61053cefb0e246c4581e9652a9e8b9770d6abf95
