### ISSUE TITLE
harfbuzz build fails on OSX

### ISSUE THREAD

**Issue by jhs67** [ruslo/hunter#1749]
The harfbuzz project is broken on OSX with no toolchain. The problem seems to have been introduced when the ICU integration was enabled. It looks like icu requires c++11 for the 'noexcept' keyword.

```
/Users/jon/.hunter/_Base/1b3f3ad/9e23df5/278cdfe/Install/include/unicode/localpointer.h:221:40: error: expected ';' at end of declaration list
    LocalPointer(LocalPointer<T> &&src) U_NOEXCEPT : LocalPointerBase<T>(src.ptr) {
```

* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **[Yes
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **[Yes
* I've checked that all the `hunter_add_package`/`find_package` API used by me in example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **[Yes
* I'm using latest Hunter URL/SHA1. **[Yes

* I've created SSCCE reproducing the issue:
```cmake
# CMakeLists.txt

cmake_minimum_required(VERSION 3.2)

include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.115.tar.gz"
    SHA1 "1b3f3addc801405769edbb7ebbe701223db3efa6"
    )
        
project(foo)
        
hunter_add_package(harfbuzz)
find_package(harfbuzz CONFIG REQUIRED)
```

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
[err.log](https://github.com/ruslo/hunter/files/2904292/err.log)

I've checked that the first error in logs **IS NOT** `external.build.failed`. No]** (it is)

* I'm building on OSX
* I'm using official CMake release
* CMake version: <3.11.3>

* I'm not using toolchain

I'm using next command line on generate step:
```
cmake -H. -B_builds -DHUNTER_DEBUG_STATUS=ON
```

**Comment by ruslo** [comment]
> I've checked that the first error in logs **IS NOT** `external.build.failed`. No]** (it is)

From [external.build.failed](https://docs.hunter.sh/en/latest/reference/errors/error.external.build.failed.html#what-to-do):

```
 there is no need to report bug if you’re not planning to fix it yourself
```

So I guess you want to fix it? What is your plan?

**Comment by ruslo** [comment]
From [external.build.failed](https://docs.hunter.sh/en/latest/reference/errors/error.external.build.failed.html#what-to-do):

```
If you want to try to fix the error and want to ask for advice
then prefer reporting it to hunterized repository
```

For `harfbuzz` it's a https://github.com/hunter-packages/harfbuzz/issues
