### ISSUE TITLE
Update sqlite3 to 3.27.2

### ISSUE THREAD

**Issue by hjmallon** [ruslo/hunter#1754]
* I'm interested in package `sqlite 3.27.2`
* Here is official site of package https://sqlite.org/index.html

SQLite3 has been updated. Please can we have a new branch in hunter-packages. I can work on rebasing the required commits if needed.

---

**Comment by ruslo** [comment]
Created: https://github.com/hunter-packages/sqlite3/tree/hunter-3.27.2

**Comment by hjmallon** [comment]
Released https://github.com/ruslo/hunter/releases/tag/v0.23.121
