### ISSUE TITLE
adding a forked release

### ISSUE THREAD

**Issue by dvirtz** [ruslo/hunter#1762]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

Let's say I have a fork of a package with a feature that isn't merged upstream. Can I add a release of this fork to Hunter? Should it be under a different package name?

---

**Comment by ruslo** [comment]
> Let's say I have a fork of a package with a feature that isn't merged upstream.

Isn't merged yet? Will be merged? Rejected?

> Should it be under a different package name?

No, if it provides the same C++ API, same headers, etc. then package name should remain.

**Comment by dvirtz** [comment]
> Isn't merged yet? Will be merged? Rejected?

It's an API breaking change. It might be merged when next major release is done.

**Comment by ruslo** [comment]
For now there are no strong rules (see https://github.com/ruslo/hunter/issues/1106) about compatibility, so common sense is the only rule. If it doesn't diverge too far from upstream and will be merged into the future version I'm okay with it.

Will be something like `vA.B.C-abcdef-p0` (see https://docs.hunter.sh/en/latest/creating-new/patch.html) where vA.B.C is the latest upstream version, `abcdef` upstream commit from where you forked and p0 mark the set of your patches (minimal set).

**Comment by dvirtz** [comment]
Seems reasonable, thanks.
