### ISSUE TITLE
Add sleef package

### ISSUE THREAD

**Issue by xsacha** [ruslo/hunter#1763]
* I'm interested in package `sleef`
* Here is official site of package https://sleef.org/

* This package is using [Git]: https://github.com/shibatch/sleef

* Used build system: [CMake]

* This package has no dependencies

It is a dependency of pytorch

Needs a hunter-package because it uses OpenSSL

**Comment by ruslo** [comment]
> Needs a hunter-package because it uses OpenSSL

Done: https://github.com/hunter-packages/sleef

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/pull/1780
