### ISSUE TITLE
OpenCV links against the static CRT by default on windows

### ISSUE THREAD

**Issue by oliverdaniell** [ruslo/hunter#177]
The convention appears to be that libraries built with hunter link against the dynamic CRT on windows. For OpenCV an additional CMAKE_ARGS needs to be added to the hunter.cmake file to force this behaviour

BUILD_WITH_STATIC_CRT=OFF

**Comment by ruslo** [comment]
> The convention appears to be that libraries built with hunter link against the dynamic CRT on windows

Not exactly. The only convention is to use CMake's defaults, see [default behaviour](https://github.com/ruslo/hunter/wiki/usr.adding.new.package#default-behaviour). So I guess OpenCV violates this principle here and rewrite compiler flags.

Please check this version with fix: https://github.com/ruslo/hunter/releases/tag/v0.11.2

**Comment by oliverdaniell** [comment]
Tested in visual studio 2013, OpenCV version 2.4.11, hunter v0.11.2, bug fixed

**Comment by ruslo** [comment]
> Tested in visual studio 2013

@oliverdaniell Thank you! :)
