### ISSUE TITLE
QT does not build with Visual Studio 2017

### ISSUE THREAD

**Issue by georged-youi** [ruslo/hunter#1771]
Qt5 does not build on Windows using Visual Studio 2017 due to this bug: https://github.com/bincrafters/community/issues/411

Qt5 5.11.2 fixes this issue. Is there a way to update hunter to that particular version of Qt5 for Windows?

Thanks

**Comment by ruslo** [comment]
Qt 5.11.3 available in https://github.com/ruslo/hunter/releases/tag/v0.23.130
