### ISSUE TITLE
Add "onnx" package

### ISSUE THREAD

**Issue by xsacha** [ruslo/hunter#1777]
* I'm interested in package `onnx`
* Here is the official site of package https://onnx.ai/

* This package is using [Git]: https://github.com/onnx/onnx

* Official GitHub repository: https://github.com/onnx/onnx

* Used build system: [CMake]

* This package has next dependencies:

  * `protobuf` (required, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/Protobuf.html)
  * `pybind11` (optional, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/pybind11.html)

---

This package is required by pytorch.

Attempt to use was here: https://github.com/xsacha/hunter/tree/onnx but required dependency 'protobuf' to succeed. So it needs a hunter-package.

**Comment by ruslo** [comment]
> Attempt to use was here: https://github.com/xsacha/hunter/tree/onnx but required dependency 'protobuf' to succeed. So it needs a hunter-package.

Done: https://github.com/hunter-packages/onnx

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/pull/1785
