### ISSUE TITLE
Add "cpuinfo" package

### ISSUE THREAD

**Issue by xsacha** [ruslo/hunter#1779]
* I'm interested in package `cpuinfo`
* Here is the official site of package https://pytorch.org/

* This package is using [Git]: https://github.com/pytorch/cpuinfo

* Official GitHub repository: https://github.com/pytorch/cpuinfo
* Used build system: [CMake]

* This package has no dependencies (unless testing or benchmarking)

---
Dependency of pytorch. Also, as far as I understand, only ever used for pytorch but potentially could be used for any project

Probably needs to be forked because of some design choices around whether it builds static or shared. Also requires a config installed.

**Comment by ruslo** [comment]
> Probably needs to be forked

Done: https://github.com/hunter-packages/cpuinfo

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/pull/1789
