### ISSUE TITLE
GLEW does not include GLU

### ISSUE THREAD

**Issue by mecharage** [ruslo/hunter#1784]
The `glew` package defines its target properties as such:

```cmake
add_library(glew::glew STATIC IMPORTED)
set_target_properties(glew::glew PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "GLEW_BUILD;GLEW_NO_GLU;GLEW_STATIC"
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "OpenGL::GL;\$<LINK_ONLY:-BASE:0x62AA0000>"
)
```

This unconditionally disables the implicit inclusion of `glu.h` from `glew.h` (`GLEW_NO_GLU`), making GLU functions inaccessible.

On the MSVC toolchain I'm using (a fresh install of VS 2017), manually including `glu.h` triggers a cascade of syntax errors. According to the comments inside `glew.h` itself, that's because it depends on `windows.h`:

```cpp
/*
 * GLEW does not include <windows.h> to avoid name space pollution.
 * GL needs GLAPI and GLAPIENTRY, GLU needs APIENTRY, CALLBACK, and wchar_t
 * defined properly.
 */
```

`glew.h` then proceeds to define the missing macros, conditionally include `glu.h`, before cleaning up behind itself. This leaves only three workarounds:

- Endure `windows.h` everywhere one needs `glu.h`;
- Replicate the work done by GLEW before including `glu.h`;
- Do without `glu.h`.

... which are all quite unpleasant. Is there a reason for the systematic disabling of `glu.h`?

**Comment by pretyman** [comment]
Hi, I think I imported this package back in the day. 

What do you need glu for? 

For windowing and context creation glfw is recommended.
For vector and matrix math glm is recommended.

Sorry for the late reply, I don't work with native code anymore ;(

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
