### ISSUE TITLE
Addition of CMAKE_CXX_FLAGS to boost_library scheme breaks boost build

### ISSUE THREAD

**Issue by oliverdaniell** [ruslo/hunter#179]
This issue was caused by commit  9f4834a21534b82214fa38c5399af1ea8af6e2e7, it looks like release 0.11.2 has been released from the development branch (was this intended) and includes this bug

line 233 adds the ${CMAKE_CXX_FLAGS}\n" after \"${boost_compiler}\". From the boost documentation http://www.boost.org/build/doc/html/bbv2/reference/tools.html these flags should be separated from the compiler by a colon

**Comment by ruslo** [comment]
> looks like release 0.11.2 has been released from the development branch (was this intended) and includes this bug

Yes, usually if release made from branch `develop` there is `Pre-release` badge at the left. After successfull travis build I've removed `Pre-release` and it became `Latest release`. But in own case travis works fine: https://travis-ci.org/ruslo/hunter/builds/67101839

> breaks boost build

What platform/toolchain you're using and what library building?

> these flags should be separated from the compiler by a colon

you mean that it should be just:
```cmake
     "using ${toolset_name}\n"
     "  : ${toolset_version}\n"
     "  : \"${boost_compiler}\" : ${CMAKE_CXX_FLAGS}\n"
     "  : <archiver> \"${CMAKE_AR}\"\n"
     ";\n"
```
?

**Comment by oliverdaniell** [comment]
Windows msvc-12.0 32bit

Boost b2 works if I use the following command:

     "using ${toolset_name}\n"
     "  : ${toolset_version}\n"
     "  : \"${boost_compiler}\"\n"
     "  : ${CMAKE_CXX_FLAGS} <archiver> \"${CMAKE_AR}\"\n"
     ";\n"

I'm not sure what the <archiver> command is doing, as far as I can tell this is not used by boost build.

There is another problem caused by 9f834a. Whitespace is introduced when line 242 is parsed

"linkflags=${CMAKE_EXE_LINKER_FLAGS}"
Is parsed as linkflags= /......
                                  ^
Boost b2 is unable to parse the white space

For testing I have removed this line

**Comment by oliverdaniell** [comment]
> What platform/toolchain you're using and what library building?
Tested using system and thread

**Comment by ruslo** [comment]
> I'm not sure what the archiver command is doing, as far as I can tell this is not used by boost build

I don't know too :) This was added in https://github.com/ruslo/hunter/commit/0724fb89ac0657f23e11332015bafbbf57b29ba6

@pretyman Does the `<archiver>` is critical for building on Android? I can't find reference to it in documentation: http://www.boost.org/build/doc/html/bbv2/reference/tools.html Though there are some links like: https://svn.boost.org/trac/boost/ticket/1055

**Comment by ruslo** [comment]
> Windows msvc-12.0 32bit

confirmed: `vs-12-2013` + `boost.system` is broken :(

**Comment by oliverdaniell** [comment]
reverting 0724fb8 fixes the problem for me, happy to test once you have a solution

**Comment by ruslo** [comment]
@oliverdaniell just for your information https://github.com/ruslo/hunter/issues/180

**Comment by pretyman** [comment]
@ruslo as far as I understand yes, the archiver is needed to package boost as Android libraries.
If we really want to compile flags in the jam file, and not as `cxxflags` in command line we can try to put it after colon with the archiver:
```
<archiver> ${CMAKE_AR}
<compileflags>${CMAKE_CXX_FLAGS}
```
I've seen single flags like this, but never more than one per `<compileflags>`, but since the tag is in plural, it makes be believe it should take more than one flag.

I think I tried back then to build boost without the archiver, but I was unsuccessful to use boost (I can't remember if it failed to build or if my tests failed to link with boost test)

**Comment by ruslo** [comment]
> it makes be believe it should take more than one flag

@pretyman I've tested it and seems that only one flag allowed in `<compileflags>` but section can be repeated several times. Solution: https://github.com/ruslo/hunter/commit/988eeb894b12d7568ecad18db8aeecc13345bbdc

> Boost b2 is unable to parse the white space between = and /machine

@oliverdaniell Works for me without this change. Can you please try this one: [v0.11.3](https://github.com/ruslo/hunter/releases/tag/v0.11.3)

**Comment by oliverdaniell** [comment]
Tested on v0.11.3 visual studio 2013.

> @oliverdaniell Works for me without this change. Can you please try this one: v0.11.3
My mistake, I was testing by copying the cmake output to the command line

**Comment by ruslo** [comment]
Since we hit this again here is the summary of solution of this bug:
* C++ flags should **not** be set in the section with compiler, i.e.
```cmake
file(APPEND ${boost_user_jam} "  : \"${boost_compiler}\" ${CMAKE_CXX_FLAGS}\n")
```
will **not** work for Visual Studio
* C++ flags should be set in `<compilefilags>` section (one flag for one `<compileflags>`, can be repeated several times)

To test: vs-12-2013 + Boost-system example
