### ISSUE TITLE
Boost install name on Mac improvement

### ISSUE THREAD

**Issue by khourig** [ruslo/hunter#1802]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
---
On Mac, Boost libraries are built using the `darwin` toolset rather than `clang-darwin`.

When built with `darwin`, the libraries have an install name with NO prefix, requiring the use of `DYLD_LIBRARY_PATH`, which is generally accepted on Linux (with `LD_LIBRARY_PATH`), but discouraged by Apple and counter to how Mac application bundles are built.

When built with `clang-darwin`, the libraries have an install name prefix of `@rpath/`, enabling their relocation to any folder that the calling application or library wishes to set its runpath to.

Even if it's decided not to switch the toolset, please consider adding the option of switching. As it is, this is not configurable. The only other recourse is to rewrite all install names during the build of MY application, not of just the Boost libraries, but also the other Boost libraries they list as dependencies, since their install name is copied to the dependents.

**Comment by ruslo** [comment]
> When built with darwin, the libraries have an install name with NO prefix

> When built with clang-darwin, the libraries have an install name prefix of `@rpath`

Sounds strange but I'm okay with adding a new option. You can add the `if` here:
- https://github.com/ruslo/hunter/blob/v0.23.151/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L67-L72

Please also update the documentation:
- https://docs.hunter.sh/en/latest/packages/pkg/Boost.html#cmake-options

Tests will be similar to OpenSSL: https://github.com/ruslo/hunter/issues/1804#issuecomment-480508212

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
