### ISSUE TITLE
JPEG is up to version 9c

### ISSUE THREAD

**Issue by khourig** [ruslo/hunter#1803]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
---
As the title says, Hunter is behind a version at 9b.

**Comment by ruslo** [comment]
Package update instruction is here:
- https://docs.hunter.sh/en/latest/creating-new/update.html

Feel free to work on it.

**Comment by sjdrc** [comment]
@ruslo closed by https://github.com/ruslo/hunter/commit/75645b0efa0e93a4bf68dbc17dc4b575dd5677ff
