### ISSUE TITLE
OpenSSL install name on Mac improvement

### ISSUE THREAD

**Issue by khourig** [ruslo/hunter#1804]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
---
On MacOSX, the generated shared libraries have the install name prefix of `@loader_path/../lib/` rather than `@rpath/`.

Using `@rpath/` allows relocating the libraries to any folder that the calling application or library wishes to set its runpath to.

**Comment by ruslo** [comment]
> Using @rpath/ allows relocating the libraries to any folder that the calling application or library wishes to set its runpath to.

:+1: yes, it sounds like a correct approach.

We use `install_name_tool` here:
- https://github.com/ruslo/hunter/blob/v0.23.151/cmake/projects/OpenSSL/schemes/url_sha1_openssl_macos.cmake.in#L100-L103

Should be not so hard to fix it, please send a pull request with the fix and test it locally to make sure it fits your needs.

Running tests is similar to "Update package" instructions:
- https://docs.hunter.sh/en/latest/creating-new/update.html

To refresh the server binary cache, please update `PACKAGE_INTERNAL_DEPS_ID`:
- https://docs.hunter.sh/en/latest/reference/user-modules/hunter_download.html

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
