### ISSUE TITLE
Deadlock on concurrent builds using same cache

### ISSUE THREAD

**Issue by PyrO70** [ruslo/hunter#1806]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **Yes**
* I'm using [latest](https://github.com/ruslo/hunter/releases) Hunter `URL`/`SHA1`. **Yes**

* I'm building on Linux.
* I'm using official CMake release: 
* CMake version: 3.14.1

* I'm using modified toolchain close to **gcc-7-cxx14.cmake** from Polly (https://github.com/ruslo/polly)
---
I am seeing a deadlock created by two concurrent builds on using the same cache.

**State of the lock files:**
```
cmake            3640  POSIX   0B WRITE* 0     0   0 /.hunter/_Base/Download/Boost/1.69.0-p0/2539b07/cmake.lock
cmake            3018  POSIX   0B WRITE  0     0   0 /.hunter/_Base/Download/Boost/1.69.0-p0/2539b07/cmake.lock
cmake           31307  POSIX   0B WRITE  0     0   0 /.hunter/_Base/Download/my_library/5.0.3/fd65139/cmake.lock
cmake            3018  POSIX   0B WRITE* 0     0   0 /.hunter/_Base/393d500/27bfa09/0c7b103/cmake.lock
cmake           31307  POSIX   0B WRITE  0     0   0 /.hunter/_Base/393d500/27bfa09/0c7b103/cmake.lock
```

**The situation is as follow:**
`3640` is blocked by `3018` on `/.hunter/_Base/Download/Boost/1.69.0-p0/2539b07/cmake.lock`
`3018` is blocked by `31307` on `/.hunter/_Base/393d500/27bfa09/0c7b103/cmake.lock`
`31307` is waiting for `3640`, `3640` is building a dependency

**Other information about the system:**
The two builds are happening in separate Docker containers with a shared mounted volume containing the cache

I am not sure how this situation occurs, let me know if I can provide more information regarding the state of the system? I am also trying to check the reason of the block but I am not familiar with the locking order in Hunter.

**Comment by ruslo** [comment]
> The two builds are happening in separate Docker containers with a shared mounted volume containing the cache

Probably that's the problem. Is there a chance that system locks will not work correctly in this case?

> I am also trying to check the reason of the block but I am not familiar with the locking order in Hunter

As you can see the `.hunter` directory is shared. Any local build can trigger shared Hunter package build; hence if two local builds use the same Hunter directory, one should wait while another will finish the external build:
- https://docs.hunter.sh/en/latest/overview/shareable.html

**Comment by ruslo** [comment]
Can you try this test?
```cmake
# script.cmake

cmake_minimum_required(VERSION 3.2)

function(testlock)
  foreach(i RANGE 10)
    message("# ${i}")
    message("Try lock")
    file(LOCK "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY GUARD FUNCTION)
    message("File locked")
    execute_process(COMMAND ${CMAKE_COMMAND} -E sleep 5)
    file(LOCK "${CMAKE_CURRENT_LIST_DIR}" DIRECTORY RELEASE)
  endforeach()
endfunction()

testlock()
```

Docker 1:
```
> cd /shared/folder
> cmake -P script.cmake
```

Docker 2:
```
> cd /shared/folder
> cmake -P script.cmake
```

If it works correctly, you should never see "File locked" message simultaneously. It should always be "Try lock" in one and "File locked" in another.

**Comment by PyrO70** [comment]
`docker run --rm --init -v /tmp/shared:/shared/folder -it ubuntu /bin/bash -c "cd /shared/folder; cmake -P script.cmake"` x 2
```
# 0
Try lock
File locked
# 1
Try lock
File locked
# 2
Try lock
File locked
# 3
Try lock
File locked
# 4
Try lock
File locked
# 5
Try lock
File locked
# 6
Try lock
File locked
# 7
Try lock
File locked
# 8
Try lock
File locked
# 9
Try lock
File locked
# 10
Try lock
File locked
```

```
# 0
Try lock
File locked
# 1
Try lock
File locked
# 2
Try lock
File locked
# 3
Try lock
File locked
# 4
Try lock
File locked
# 5
Try lock
File locked
# 6
Try lock
File locked
# 7
Try lock
File locked
# 8
Try lock
File locked
# 9
Try lock
File locked
# 10
Try lock
File locked
```

It works fine, I don't believe the volume mount system is creating the problem in the first place. This deadlocks happens usually when updating a lot of dependencies at once (moving to the latest release of hunter for instance). Most of the time the locking works.

**Comment by PyrO70** [comment]
- `Build 1`
  - `Build a`
- `Build 2`

`Build 1` holds a lock that `Build 2` needs and `Build 2` holds a lock that `Build a` needs. Normally everything would be fine, and `Build 1` would eventually finish, if they were independent builds, but because `Build 1` is waiting for `Build a` to finish (as `Build a` builds a dependency for `Build 1`), the deadlock happens.

In your opinion, that can only happen because a lock was skipped? Is that why you think it is the docker volume issue? Could it be an actual deadlock ?

**Comment by ruslo** [comment]
> It works fine

I guess you have tested it right but to be sure: just having script works correctly doesn't mean locks are working. Make sure you **never** see "File locked" message in two terminals **simultaneously**.

> This deadlocks happens usually when updating a lot of dependencies at once (moving to the latest release of hunter for instance).

Well, that's the situation when locks are really tested. If packages are installed, we don't need any locks, and they are not used.

> Build 1 holds a lock that Build 2 needs and Build 2 holds a lock that Build a needs

Can you add all logs with `-DHUNTER_STATUS_DEBUG=ON`? Are you sure we are not really just waiting for the build to finish?

**Comment by ruslo** [comment]
> Could it be an actual deadlock ?

I have analyzed it carefully and I think it is :)

![deadlock](https://user-images.githubusercontent.com/4346993/55671458-db5ba380-5898-11e9-8653-61dee1842f9c.png)

I can reprocude it:
- https://github.com/forexample/deadlock-test

The problem is that download step and build step is fused in ExternalProject_Add:
- https://github.com/ruslo/hunter/blob/v0.23.151/cmake/schemes/url_sha1_cmake.cmake.in#L142-L163

And for optimization reason `Download` directory can be shared between several CMake instances (and hence should be locked before modification).

I've prepared a quick fix, can you please try:
```cmake
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/de64d2f903e3e1884bb10b324530bb0fa5a8ab21.zip"
    SHA1 "577c775161dcc21eb59b27d5f65bc5e21387a74b"
)
```

It still not robust but should be better. For real fix:
- https://github.com/ruslo/hunter/issues/1807

**Comment by PyrO70** [comment]
> I guess you have tested it right but to be sure: just having script works correctly doesn't mean locks are working. Make sure you **never** see "File locked" message in two terminals **simultaneously**.

Indeed there were no message File Locked at the same time.

> I have analyzed it carefully and I think it is :)
> 
> ![deadlock](https://user-images.githubusercontent.com/4346993/55671458-db5ba380-5898-11e9-8653-61dee1842f9c.png)

This was exactly what I though was happening. I didn't know why tho.

> The problem is that download step and build step is fused in ExternalProject_Add:

Now that makes sense

> I've prepared a quick fix, can you please try:
> It still not robust but should be better. For real fix:
> 
> * #1807

I'll try the fix when back at work on Monday.

Thanks.

**Comment by ruslo** [comment]
Fix released: https://github.com/ruslo/hunter/releases/tag/v0.23.152

Thank for the report!
