### ISSUE TITLE
utf8 installs includes to non-default path

### ISSUE THREAD

**Issue by sjdrc** [ruslo/hunter#1808]
Please see https://github.com/hunter-packages/utf8/commit/fd445050845b6bce1c94fd20dcce9afff38f8b44

Ubuntu system packages install the utf8.h header file to include/. Moving this to a subfolder breaks our packages when trying to maintain compatibility with hunter and our legacy build system.

**Comment by ruslo** [comment]
Please open discussion here instead: https://github.com/hunter-packages/utf8/issues
