### ISSUE TITLE
Add "libzip" package

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1809]
* I'm interested in package `libzip`

* Official GitHub repository: https://github.com/nih-at/libzip

* Used build system: CMake

* This package has next dependencies:

  * `OpenSSL` (required, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/OpenSSL.html)
  * `BZip2` (required, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/BZip2.html)
  * `ZLIB` (required, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/ZLIB.html)

---

@ruslo I have a working fork, need one to push to in hunter-packages.

**Comment by ruslo** [comment]
> I have a working fork, need one to push to in hunter-packages.

Done: https://github.com/hunter-packages/libzip

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/pull/1877
