### ISSUE TITLE
Building boost (1.58.0-p0) on visual studio 2008 fails due to configuration checks being reported as errors

### ISSUE THREAD

**Issue by oliverdaniell** [ruslo/hunter#181]
Visual studio 2008
Boost 1.58.0-p0

It looks the errors from the boosts compiler checks are falling through to cmake when it is built with vs 2008. This does not occur with vs 2013. As a result cmake stops the build. It should be safe to ignore these errors as the install step still works as expected.

```
1>Performing install step for 'Boost'
1>32.cpp
1>Performing configuration checks
1>    - 32-bit                   : yes
1>arm.cpp
1>libs\config\checks\architecture\arm.cpp(12) : fatal error C1189: #error :  "No
t ARM"
1>    - arm                      : no
1>mips1.cpp
1>libs\config\checks\architecture\mips1.cpp(10) : fatal error C1189: #error :  "
Not MIPS1"
1>    - mips1                    : no
1>power.cpp
1>libs\config\checks\architecture\power.cpp(13) : fatal error C1189: #error :  "
Not PPC"
1>    - power                    : no
1>sparc.cpp
1>libs\config\checks\architecture\sparc.cpp(10) : fatal error C1189: #error :  "
Not SPARC"
1>    - sparc                    : no
1>x86.cpp
```

**Comment by oliverdaniell** [comment]
It looks like this is due to this bug http://lists.boost.org/boost-users/2013/04/78408.php.

**Comment by oliverdaniell** [comment]
Also relevant https://git.backbone.ws/cmake/cmake/commit/45d2966dcc0ebc08a925d6ac2ba1831549faa345?diffmode=sidebyside

**Comment by oliverdaniell** [comment]
It looks like the following fix works. I've tested it on vs 2008 only

url_sha1_boost.cmake.in

```
 if("@MSVC@")
   set(env_cmd "@HUNTER_MSVC_VCVARSALL@" "@HUNTER_MSVC_ARCH@")
+  set(msvc_cmd set VS_UNICODE_OUTPUT=)
 else()
   set(env_cmd "")
+  set(msvc_cmd "")
 endif()
```

```   INSTALL_COMMAND
-    ${install_cmd}
+	INSTALL_COMMAND ${msvc_cmd} COMMAND ${install_cmd}
```
Apologies for the lack of a proper patch, I need to lean how to use github properly

**Comment by ruslo** [comment]
@alamaison Is this related to https://github.com/ruslo/hunter/pull/145 ?

**Comment by ruslo** [comment]
> Apologies for the lack of a proper patch, I need to lean how to use github properly

@oliverdaniell Follow this steps:
* Fork `ruslo/hunter` - now you have your own copy `oliverdaniell/hunter`
* Clone it: `git clone https://oliverdaniell/hunter`
* Create separate branch, say `fix.181`: `git checkout -b fix.181`. This branch will be used for pull request. If in future you want to update your pull request just push more commits to this branch. And vice versa - do not push anything not releated to the fix to this branch.
* Commit changes and push them `git commit -m "..."; git push origin fix.181:fix.181`
* Open github, you must see `create pull request` button, click on it.

I'm not sure 100% about fork and branches, but you need to verify on some step that you making pull request agains branch `develop`.

**Comment by alamaison** [comment]
> Is this related to #145?

Yes, it's the same bug, but experienced via url_sha1_boost.cmake.in instead of url_sha1_boost_library.cmake.in. My fix only applied to the latter, so I guess we need a fix for all code calling bjam.

**Comment by ruslo** [comment]
> My fix only applied to the latter, so I guess we need a fix for all code calling bjam

Cool. @oliverdaniell Can you apply [this fix](https://github.com/ruslo/hunter/pull/145/files) to the `url_sha1_boost.cmake.in` scheme and test it. Please send me pull request if it works fine.

**Comment by ruslo** [comment]
@oliverdaniell also just for your information you can run tests locally using `jenkins.py` script from top directory. You need to install [build.py](https://github.com/ruslo/polly#buildpy) and set some environment variables `set TOOLCHAIN=vs-8-2005` + `set PROJECT_DIR=exemples\Boost`

**Comment by oliverdaniell** [comment]
Thanks for the info, I should get round to this next week

**Comment by oliverdaniell** [comment]
pull request https://github.com/ruslo/hunter/pull/182

**Comment by ruslo** [comment]
> pull request #182

Applied: https://github.com/ruslo/hunter/releases/tag/v0.11.5

@oliverdaniell Feel free to close this issue if it works for you

**Comment by oliverdaniell** [comment]
works for me, Thank you
