### ISSUE TITLE
Add "tmxparser" package

### ISSUE THREAD

**Issue by sjdrc** [ruslo/hunter#1813]
* I'm interested in package `tmxparser`
* Official GitHub repository: https://github.com/sainteos/tmxparser
* Used build system: CMake

* This package has next dependencies:
  * `tinyxml2` (required, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/tinyxml2.html)
  * `zlib` (required, available in Hunter:
https://docs.hunter.sh/en/latest/packages/pkg/ZLIB.html)
---
* I have a working hunterised fork here: https://github.com/black-ai/tmxparser

**Comment by ruslo** [comment]
> I have a working hunterised fork here: https://github.com/black-ai/tmxparser

I've created https://github.com/hunter-packages/tmxparser

**Comment by sjdrc** [comment]
Added by https://github.com/ruslo/hunter/commit/d74a399cdedb948953d82c3642d454879dab9d9e
