### ISSUE TITLE
Update "Boost" package to 1.70

### ISSUE THREAD

**Issue by Warchant** [ruslo/hunter#1815]
Update Boost package from 1.69 to 1.70 (was released April 12th, 2019 06:04 GMT)

**Comment by ruslo** [comment]
Already in latest release:
- https://github.com/ruslo/hunter/releases/tag/v0.23.153
- https://github.com/ruslo/hunter/commit/a1f6708538dd0fc79c1b319129547dd144bbce1e

**Comment by Warchant** [comment]
Wow, you're so fast :-)

**Comment by truedat101** [comment]
Curious, how does one know what version the hunter package is tied to ?  I see I can set this in the cmake.config

hunter_config(Boost VERSION 1.70.0)

But actually that doesn't work.  I would need to know that it's 1.70.0-p0.

**Comment by Warchant** [comment]
@truedat101 https://github.com/hunter-packages/boost

**Comment by truedat101** [comment]
@Warchant thank you for  the reply.  But generally speaking, I'm still a bit confused as to where to find the versions valid to use in hunter_config for a particular Hunter package.  Quite often the newest version isn't the one needed.  Is it based on the tag in the package project, or is there some metadata somewhere to find this?

**Comment by Warchant** [comment]
@truedat101 

old ruslo repo: https://github.com/ruslo/hunter/blob/master/cmake/projects/Boost/hunter.cmake#L144
new cpp-pm repo: https://github.com/cpp-pm/hunter/blob/master/cmake/projects/Boost/hunter.cmake#L144
