### ISSUE TITLE
Hunter adds '-isystem /usr/include' to compiler call

### ISSUE THREAD

**Issue by sjdrc** [ruslo/hunter#1818]
I have hunterised a library (library a) that we use internally, and am able to compile it fine on its own. When using it as a hunter dependency in another project, compilation fails with the following error:

```
In file included from /home/sebastien/.hunter/_Base/0c9801f/9d0c998/91bb880/Install/include/boost/config/platform/linux.hpp:15:0,
                 from /home/sebastien/.hunter/_Base/0c9801f/9d0c998/91bb880/Install/include/boost/config.hpp:57,
                 from /home/sebastien/.hunter/_Base/0c9801f/9d0c998/91bb880/Install/include/boost/cstdint.hpp:36,
                 from /home/sebastien/.hunter/_Base/0c9801f/9d0c998/91bb880/Build/echo3/Source/include/echo/Types.h:38,
                 from /home/sebastien/.hunter/_Base/0c9801f/9d0c998/91bb880/Build/echo3/Source/include/echo/Animation/AnimationTrack.h:4,
                 from /home/sebastien/.hunter/_Base/0c9801f/9d0c998/91bb880/Build/echo3/Source/src/Animation/Animation.cpp:1:
/usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
               ^~~~~~~~~~
compilation terminated.
```

When I compare this line with the compiler line from library a standalone, the only fundamental difference is that the hunter package has ```-isystem /usr/include``` in the compiler flags. This prevents stdlib.h from being found for some reason. How can I prevent this from being added? Am I doing something wrong?

**Comment by ruslo** [comment]
This issue will be closed because the required template file [bug_report.md][1] was ignored. Please read and fill carefully all parts of this file while submitting a bug report.

Thanks for understanding.

[1]: https://raw.githubusercontent.com/ruslo/hunter/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by sjdrc** [comment]
I mean I'm asking a general question as to why hunter adds ``` -isystem /usr/include``` to gcc call. We want to understand why hunter is doing what it is doing. But I will open a new issue following your template.

**Comment by ruslo** [comment]
> why hunter adds -isystem /usr/include to gcc call

Your assumption is not correct; Hunter is not doing it.

**Comment by sjdrc** [comment]
Well it's not in the compiler flags when I'm building the package separately and it appears when I'm building the package as a hunter dependency

**Comment by ruslo** [comment]
I guess the problem is in dependency then.
