### ISSUE TITLE
Reduced set of plugins causes missing PACKAGE_UNRELOCATABLE_TEXT_FILES

### ISSUE THREAD

**Issue by epvbergen** [ruslo/hunter#1823]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---

I'm using PARAM_EXTRA_FLAGS on gst_plugins_{base,good,ugly,bad} in my local config.cmake for Hunter 0.23.154 to limit the set of gstreamer plugins to be included in my project. (Incidentally: how to add multiple options using PARAM_EXTRA_FLAGS? Neither setting multiple instances nor using double quotes, ie. "--with-x --without-y" works for me).

I can see that the autotools configuration happens as it should and building is fine. However, when Hunter starts to save the build to cache it wants to patch the plugin's .la files as listed in the project's hunter.cmake under PACKAGE_UNRELOCATABLE_TEXT_FILES. The first file that's missing causes a FATAL ERROR: File not exists:

-- [hunter *** DEBUG *** 2019-04-18T21:34:23] Saving to cache: gst_plugins_base
[hunter ** FATAL ERROR **] File not exists:
[hunter ** FATAL ERROR **]   /home/emile/.hunter/_Base/d720f37/5930f74/e6c0184/Build/gst_plugins_base/Install/lib/gstreamer-1.0/libgstadder.la
[hunter ** FATAL ERROR **] (check HUNTER_PACKAGE_UNRELOCATABLE_TEXT_FILES)
[hunter ** FATAL ERROR **] [Directory:/home/emile/.hunter/_Base/Download/Hunter/0.23.154/d720f37/Unpacked/cmake/projects/gst_plugins_base]

(This also happens for me for gst_plugins_bad without having set PARAM_EXTRA_FLAGS, if I don't have hunter_add_package(BZip2) anywhere, since that prevents the bz2 plugin from being built). 

The question I'd like to raise is whether the patching for HUNTER_PACKAGE_UNRELOCATABLE_TEXT_FILES should not better silently skip files that have not been created during the build. If they were necessary, the issue will show up later, just as before the unrelocatable text file patching was implemented.

**Comment by ruslo** [comment]
> how to add multiple options

Both spaces and `;` should work fine:
```cmake
CMAKE_ARGS A=a b c d
```

```cmake
CMAKE_ARGS A=a;b;c;d
```

> Neither setting multiple instances

It's equivalent to `-DA=a -DA=b -DA=c` so they are overwriting each other.

> using double quotes

I'm not sure how autotools (GStreamer use non-CMake build scheme) interpreter this, but probably it ends up as a single argument with space or even argument with quotes inside.

If you do `A="a b"` it's passed as `\"a\ b\"` to a command line, see the example:
- https://cgold.readthedocs.io/en/latest/tutorials/variables/regular.html#quotes

> This also happens for me for gst_plugins_bad without having set PARAM_EXTRA_FLAGS, if I don't have hunter_add_package(BZip2) anywhere, since that prevents the bz2 plugin from being built

The default configuration should work fine:
- https://travis-ci.org/ingenue/hunter/builds/412409441

Probably that's the error.

> The question I'd like to raise is whether the patching for HUNTER_PACKAGE_UNRELOCATABLE_TEXT_FILES **should not better silently skip** files that have not been created during the build

As far as I can see it's not silently skipped, you have an error while creating cache archive.

> If they were necessary, the issue will **show up later**, just as before the unrelocatable text file patching was implemented.

You want an issue to be raised later? It's not clear for me what behavior you want to have.

**Comment by epvbergen** [comment]
Indeed, the issue isn't multiple CMAKE_ARGS but multiple PARAM_EXTRA_FLAGS (formerly EXTRA_FLAGS) for the autotools scheme. As you described in cgold under case c, PARAM_EXTRA_FLAGS="--option-1 --option-2" gets interpreted as an unquoted argument and the quotes end up in funny places. However, PARAM_EXTRA_FLAGS=--option-1 --option-2 will cause --option-2 to be interpreted as a CMAKE_ARGS argument and not be part of PARAM_EXTRA_FLAGS.

> The default configuration should work fine: https://travis-ci.org/ingenue/hunter/builds/412409441

That shows only gstreamer-1.0 itself, not gst_plugins_*, right?

> As far as I can see it's not silently skipped, you have an error while creating cache archive.

Right, and what I am wondering is if that is the right thing to do (sorry for expressing that a little unclearly). 

Right now, using HUNTER_PACKAGE_UNRELOCATABLE_TEXT_FILES requires that all listed files are present after building and fails if anyone of them is missing, even if for completely valid reasons (a reduced set of plugins, normal customization using CMAKE_ARGS). Having Hunter construct the list of files based on second guessing the package's build process and flags does not seem right and the project's default.cmake is not part of the configuration if you don't fork Hunter. It seems better to let the patching process take all files listed and just silently ignore missing files.

> You want an issue to be raised later? It's not clear for me what behavior you want to have.

If the build fails or any essential file is missing, that will cause an error later, somehow or other, and that's fine by me. I meant to say it's not important for the patching process for HUNTER_PACKAGE_UNRELOCATABLE_TEXT_FILES to check if all build artefacts are present for archiving.

The behaviour I'd like to see is that HUNTER_PACKAGE_UNRELOCATABLE_TEXT_FILES ignores missing files, quite simply.

**Comment by ruslo** [comment]
> That shows only gstreamer-1.0 itself, not gst_plugins_*, right?

It seems so. Qt camera example should use all of them:
- https://github.com/ruslo/hunter/blob/v0.23.158/examples/qt-camera/config.cmake#L47
- https://github.com/ruslo/hunter/blob/v0.23.158/cmake/projects/Qt/schemes/url_sha1_qt.cmake.in#L203-L209

Build log:
- https://travis-ci.org/ingenue/hunter/jobs/504140950

> It seems better to let the patching process take all files listed and just silently ignore missing files

> The behaviour I'd like to see is that HUNTER_PACKAGE_UNRELOCATABLE_TEXT_FILES ignores missing files, quite simply.

I don't think it's a good idea, at least to do it by default. Maybe an optional feature `UNRELOCATABLE_TEXT_FILES_OPTIONAL` or allow a user to customize it similar to `CMAKE_ARGS` mechanism.

**Comment by epvbergen** [comment]
I'm preparing a patch, please see https://github.com/ruslo/hunter/pull/1864

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
