### ISSUE TITLE
Generate Config.cmake file for autogen_autotools scheme

### ISSUE THREAD

**Issue by sjdrc** [ruslo/hunter#1828]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and haven't found an answer to my question. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**

---
Could you add the lines at the end of https://github.com/ruslo/hunter/blob/master/cmake/schemes/url_sha1_autotools.cmake.in that generate a Config.cmake file from autotools into https://github.com/ruslo/hunter/blob/master/cmake/schemes/url_sha1_autogen_autotools.cmake.in in order to have hunter generate config files for those projects too? This will be useful for #1732, and others.

**Comment by ruslo** [comment]
Pull request with tests is welcome.

**Comment by sjdrc** [comment]
I tested this with libusb by adding the missing lines from `url_sha1_autotools.cmake.in` into `url_sha1_autogen_autotools.cmake.in`, and libusb and example built fine. What tests do you want me to include for this?

**Comment by ruslo** [comment]
> I tested this with libusb by adding the missing lines from url_sha1_autotools.cmake.in into url_sha1_autogen_autotools.cmake.in, and libusb and example built fine

Sounds good, please submit them together.

**Comment by sjdrc** [comment]
Added by https://github.com/ruslo/hunter/commit/d74a399cdedb948953d82c3642d454879dab9d9e
