### ISSUE TITLE
set(ICU_BUILD_IO YS) have no effect

### ISSUE THREAD

**Issue by RPICtrl** [ruslo/hunter#1835]
I am trying to add ICU::io to my project in Visual Studio 2017, but the io files are not included.

when i test with the below file the following ICU's are added

ICU::data target found
ICU::i18n target found
ICU::io target not found
ICU::le target not found
ICU::lx target not found
ICU::tu target found
ICU::uc target found
ICU::pkgdata target found
ICU::icupkg target found
ICU::uc target found

This is a simple test CmakeLists.txt

cmake_minimum_required(VERSION 3.10)
set(HUNTER_TLS_VERIFY "OFF")
### Hunter snapshot that will be used ###
include("CMake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.152.tar.gz"
    SHA1 "0c9801f60a8149c3105db04501bbcfb155581b7d"
)
project(icu_test)

set(ICU_BUILD_IO YES)
set(ICU_BUILD_TOOLS YES)

hunter_add_package(ICU)
find_package(ICU CONFIG REQUIRED)

foreach(i data i18n io le lx tu uc pkgdata icupkg ${tu_lib} uc)
  if(TARGET ICU::${i})
   message("ICU::${i} target found")
  endif()
  if(NOT TARGET ICU::${i})
   message("ICU::${i} target not found")
  endif()
endforeach()

**Comment by ruslo** [comment]
>  set(HUNTER_TLS_VERIFY "OFF")

You should set it to `CACHE`:
- https://docs.hunter.sh/en/latest/reference/user-variables.html#cmake

>set(ICU_BUILD_IO YES)

That's not how it works:
- https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-package-version

**Comment by RPICtrl** [comment]
I have added the following to cmake\hunter\config.cmake

set(icu_args ICU_BUILD_IO=YES)

hunter_config(
    ICU
    VERSION ${HUNTER_ICU_VERSION}
    CMAKE_ARGS ${icu_args}
)

But it fails with the following

CMake Error at source/io/CMakeLists.txt:1 (add_library):
  Cannot find source file:
    sprintf.c
  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
CMake Error at source/tools/genrb/CMakeLists.txt:28 (add_executable):
  Cannot find source file:
    derb.c
  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
CMake Error at source/io/CMakeLists.txt:1 (add_library):
  No SOURCES given to target: icuio
CMake Error at source/tools/genrb/CMakeLists.txt:28 (add_executable):
  No SOURCES given to target: derb

**Comment by ruslo** [comment]
> CMake Error at source/io/CMakeLists.txt:1 (add_library):
> Cannot find source file:
> sprintf.c

Probably this part was not ported, feel free to send the fix to https://github.com/hunter-packages/icu

You can also try to use previous `55.1-p4` version:
- https://github.com/ruslo/hunter/blob/v0.23.160/cmake/projects/ICU/hunter.cmake#L44-L53

**Comment by RPICtrl** [comment]
Sorry I am not an expert on Github. but this is what needs to be changed

https://github.com/hunter-packages/icu/blob/hunter-63.1/source/io/CMakeLists.txt

add_library(
    icuio
    locbund.cpp
    sprintf.cpp
    sscanf.cpp
    ucln_io.cpp
    ufile.cpp
    ufmt_cmn.cpp
    uprintf.cpp
    uprntf_p.cpp
    uscanf.cpp
    uscanf_p.cpp
    ustdio.cpp
    ustream.cpp
)

and this one

https://github.com/hunter-packages/icu/blob/hunter-63.1/source/tools/genrb/CMakeLists.txt

if(ICU_BUILD_IO)
  add_executable(derb derb.cpp)

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
