### ISSUE TITLE
-isystem /usr/include is added to compiler flags when building package as hunter dependency

### ISSUE THREAD

**Issue by sjdrc** [ruslo/hunter#1836]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **[Yes]**
* I'm using [latest](https://github.com/ruslo/hunter/releases) Hunter `URL`/`SHA1`. **[Yes]**

* I've created [SSCCE](http://www.sscce.org/) reproducing the issue:
```cmake
# echo3/CMakeLists.txt
cmake_minimum_required(VERSION 3.13)
option(HUNTER_BUILD_SHARED_LIBS "Build dependencies as shared libraries" OFF)
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.158.tar.gz"
    SHA1 "4f3d8287a546091d1968ee80e02f121b312fceea"
)

project(echo3)

hunter_add_package(Boost COMPONENTS chrono date_time filesystem random regex system thread timer)
hunter_add_package(Box2D)
hunter_add_package(bullet)
hunter_add_package(freetype)
hunter_add_package(glew)
hunter_add_package(libogg)
hunter_add_package(OpenAL)
hunter_add_package(PNG)
hunter_add_package(Protobuf)
hunter_add_package(RapidJSON)
hunter_add_package(tmxparser)
hunter_add_package(utf8)
hunter_add_package(vorbis)
hunter_add_package(websocketpp)
hunter_add_package(ZLIB)

find_package(Boost CONFIG REQUIRED chrono date_time filesystem random regex system thread timer)
find_package(Box2D CONFIG REQUIRED)
find_package(bullet CONFIG REQUIRED)
find_package(freetype CONFIG REQUIRED)
find_package(glew CONFIG REQUIRED)
find_package(libogg CONFIG REQUIRED)
find_package(OpenAL CONFIG REQUIRED)
find_package(PNG CONFIG REQUIRED)
find_package(Protobuf CONFIG REQUIRED)
find_package(RapidJSON CONFIG REQUIRED)
find_package(tmxparser CONFIG REQUIRED)
find_package(utf8 CONFIG REQUIRED)
find_package(vorbis CONFIG REQUIRED)
find_package(websocketpp CONFIG REQUIRED)
find_package(ZLIB CONFIG REQUIRED)
```

```cmake
# graphite/CMakeLists.txt
cmake_minimum_required(VERSION 3.13)
option(HUNTER_BUILD_SHARED_LIBS "Build dependencies as shared libraries" OFF)
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.158.tar.gz"
    SHA1 "4f3d8287a546091d1968ee80e02f121b312fceea"
    LOCAL
)

project(graphite)

hunter_add_package(echo3)
hunter_add_package(CapnProto)
hunter_add_package(Eigen)
hunter_add_package(OpenCV)

find_package(echo3 CONFIG REQUIRED)
find_package(CapnProto CONFIG REQUIRED)
find_package(Eigen3 CONFIG REQUIRED)
find_package(OpenCV CONFIG REQUIRED)
find_package(realsense2 REQUIRED)
find_package(TensorRT)
```

```cmake
# graphite/cmake/Hunter/config.cmake
hunter_config(echo3 VERSION 0.1.0 URL <echo3.tar.gz url> SHA1 <echo3.tar.gz sha1>)
```
Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
* [Here](https://gist.github.com/sjdrc/c86e8e255aa918d9368d80fe68516fdd)

I've checked that the first error in logs **IS NOT** `external.build.failed`. **[Yes]**

* I'm building on [Linux].
* [I've built CMake from sources myself]
* CMake version: <3.13>

* I'm using my toolchain:
```
set(CMAKE_INSTALL_RPATH "\$ORIGIN/../lib")
```

I'm using the next command line on generate step:
```
cmake -Bbuild "-GUnix Makefiles"
```
---

When I build echo3 standalone, it compiles successfully.

When I build graphite standalone, the cmake configure step fails on this command:
```
[cmake] /usr/bin/c++  -DECHO_PLATFORM_LINUX -DGLEW_BUILD -DGLEW_NO_GLU -D_WEBSOCKETPP_CPP11_STL_ -Decho3_EXPORTS -I/home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Build/echo3/Source/include -I/home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Build/echo3/Build/echo3-Release-prefix/src/echo3-Release-build/include -I/home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Build/echo3/Build/echo3-Release-prefix/src/echo3-Release-build/include/echo/generated -isystem /home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Install/include -isystem /home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Install/include/freetype2 -isystem /usr/include -isystem /home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Install/include/AL -isystem /home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Install/include/tmxparser  -O3 -DNDEBUG -fPIC   -std=c++14 -o CMakeFiles/echo3.dir/src/Animation/Animation.cpp.o -c /home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Build/echo3/Source/src/Animation/Animation.cpp
```

with the following error (full log available above):

```
[cmake] In file included from /home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Install/include/boost/config/platform/linux.hpp:15:0,
[cmake]                  from /home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Install/include/boost/config.hpp:57,
[cmake]                  from /home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Install/include/boost/cstdint.hpp:36,
[cmake]                  from /home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Build/echo3/Source/include/echo/Types.h:38,
[cmake]                  from /home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Build/echo3/Source/include/echo/Animation/AnimationTrack.h:4,
[cmake]                  from /home/sebastien/.hunter/_Base/9892140/9d0c998/d5df2a9/Build/echo3/Source/src/Animation/Animation.cpp:1:
[cmake] /usr/include/c++/7/cstdlib:75:15: fatal error: stdlib.h: No such file or directory
[cmake]  #include_next <stdlib.h>
[cmake]                ^~~~~~~~~~
[cmake] compilation terminated.
```

When building echo3 as standalone, the compilation line for the same object file is:
```
[build] /usr/bin/c++  -DECHO_PLATFORM_LINUX -DGLEW_BUILD -DGLEW_NO_GLU -D_WEBSOCKETPP_CPP11_STL_ -Decho3_EXPORTS -I/usr/local/src/echo3/include -I/usr/local/src/echo3/build/include -I/usr/local/src/echo3/build/include/echo/generated -isystem /home/sebastien/.hunter/_Base/4f3d828/9d0c998/b8a3f62/Install/include -isystem /home/sebastien/.hunter/_Base/4f3d828/9d0c998/b8a3f62/Install/include/freetype2 -isystem /home/sebastien/.hunter/_Base/4f3d828/9d0c998/b8a3f62/Install/include/AL -isystem /home/sebastien/.hunter/_Base/4f3d828/9d0c998/b8a3f62/Install/include/tmxparser  -O3 -DNDEBUG -fPIC   -std=c++14 -o CMakeFiles/echo3.dir/src/Animation/Animation.cpp.o -c /usr/local/src/echo3/src/Animation/Animation.cpp
```

The only difference between the compiler calls that is causing it to fail is that when echo3 is being built as a hunter dependency of graphite, `-isystem /usr/include` is included in the flags.

**Comment by ruslo** [comment]
I experienced the same errors on my Linux machine, it's not Hunter. Some dependency adds `/usr/include` to the compiler.

In the project I've hit this I have:
```
CUDNN_INCLUDE:PATH=/usr/include
CUDNN_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libcudnn.so
```

Check your `CMakeCache.txt` file.

**Comment by sjdrc** [comment]
Which `CMakeCache.txt` file do you mean? in `/usr/local/src/echo3/build/` the file there contains several references to `/usr/include`, but running a build from there does not add `-isystem /usr/include` to the compiler there. The references to `/usr/include` are from Fontconfig, OpenGL, and X11 stuff. I'm not really sure why or how they are in there are all the dependencies for `echo3` are from hunter.

I've also created a more minimal `CMakeLists.txt` for `echo3test` which is as follows:

```
cmake_minimum_required(VERSION 3.13)

set(CMAKE_TOOLCHAIN_FILE "cmake/toolchain.cmake" CACHE STRING "Toolchain file for dependencies")
set(HUNTER_CONFIGURATION_TYPES "Release" CACHE STRING "Build configuration types")
option(HUNTER_BUILD_SHARED_LIBS "Build dependencies as shared libraries" ON)
option(HUNTER_STATUS_DEBUG "Print detailed hunter debugging info" ON)
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.158.tar.gz"
    SHA1 "4f3d8287a546091d1968ee80e02f121b312fceea"
	LOCAL
)
project(echo3test)
hunter_add_package(echo3)
find_package(echo3 CONFIG REQUIRED)
```

This still exhibits the same issue. Looking into the `~/.hunter/_Base/.../Build/echo3/Build/CMakeCache.txt` I can find no references to `/usr/include`

**Comment by sjdrc** [comment]
Okay, upon further inspection this is due to the `glew` requiring the installation of the system library `freeglut3-dev` (On ubuntu 18.04). I'd imagine this must be an issue for anyone using a hunterised libary that includes glew. Do you have any ideas on how I could work around this?

This hard dependency on a system library should be included in the documentation for glew.

**Comment by ruslo** [comment]
> Do you have any ideas on how I could work around this?

At this point no. Also, it's not clear why it appeared. I have a similar configuration worked fine before. It should be either something related to the compiler (GCC was working fine with `-isystem /usr/include`?) or to CMake (CMake was not adding `-isystem /usr/include` but `-I /usr/include`?). I don't feel it something that was changed in Hunter.

> This hard dependency on a system library should be included in the documentation for glew.

You mean [here](https://docs.hunter.sh/en/latest/packages/pkg/glew.html)? Ok, pull request is welcome as usual.

**Comment by ruslo** [comment]
> It should be either something related to the compiler or to CMake

See:
- https://github.com/Kitware/CMake/commit/890bae524c6b97d29ffcc3fe5a6a30235d800348
- https://github.com/Kitware/CMake/commit/5990ecb74133e1a9c885fc0ea62896b501d37fef

Hunter relies on some internal CMake variables, update needed:
- https://github.com/ruslo/hunter/commit/db52b5f332e9c5500aa7f19625ef6560fec1af2b

Can you try [v0.23.162](https://github.com/ruslo/hunter/releases/tag/v0.23.162) release?

**Comment by sjdrc** [comment]
Thanks for pushing a change so quick! Yep we have been using 3.14.0 so I'll update that and try 0.23.162 tomorrow morning when I get into the office :)

**Comment by sjdrc** [comment]
Fantastic! This seems to have solved the issue.
