### ISSUE TITLE
automake config files for x11 related packages do not support arm64

### ISSUE THREAD

**Issue by sjdrc** [ruslo/hunter#1854]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **[Yes]**
* I'm using [latest](https://github.com/ruslo/hunter/releases) Hunter `URL`/`SHA1`. **[Yes]**

* I've created [SSCCE](http://www.sscce.org/) reproducing the issue:
```cmake
# CMakeLists.txt

cmake_minimum_required(VERSION 3.2)

include("cmake/HunterGate.cmake")
HunterGate(
    URL "..."
    SHA1 "..."
)

project(foo)

hunter_add_package(xproto)
find_package(xproto CONFIG REQUIRED)
```

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
* <link-to-log-file>

I've checked that the first error in logs **IS NOT** `external.build.failed`. **[Yes]**

* I'm building on [Linux amd64].
* [I've built CMake from sources myself]
* CMake version: <3.14.3>

* I'm using my toolchain:
```
set(CMAKE_INSTALL_RPATH "\$ORIGIN/../lib")
```

I'm using the next command line on generate step:
```
cmake -H. -B_builds "-GUnix Makefiles"
```

---

When building X libraries on arm64, `config.guess` and `config.sub` are too old in the official releases to properly support amd64. I get the following error on all of the various X libraries that are built with autotools:

```
[ 62%] Performing configure step for 'x11'
cd /home/user/.hunter/_Base/7bcf092/5d27811/ec05bef/Build/x11/Source && . /home/user/.hunter/_Base/Download/Hunter/0.23.164/7bcf092/Unpacked/scripts/clear-all.sh && PATH=/home/user/.hunter/_Base/7bcf092/5d27811/ec05bef/Install/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin PKG_CONFIG_LIBDIR=/home/user/.hunter/_Base/7bcf092/5d27811/ec05bef/Install/lib/pkgconfig:/home/user/.hunter/_Base/7bcf092/5d27811/ec05bef/Install/share/pkgconfig LD_LIBRARY_PATH=/home/user/.hunter/_Base/7bcf092/5d27811/ec05bef/Install/lib: ./configure AR=/usr/bin/ar LD=/usr/bin/ld NM=/usr/bin/nm OBJCOPY=/usr/bin/objcopy OBJDUMP=/usr/bin/objdump RANLIB=/usr/bin/ranlib STRIP=/usr/bin/strip CC=/usr/bin/cc CXX=/usr/bin/c++ CPPFLAGS=-I/home/user/.hunter/_Base/7bcf092/5d27811/ec05bef/Install/include "CFLAGS=-O3 -DNDEBUG" "CXXFLAGS=-O3 -DNDEBUG" LDFLAGS=-L/home/user/.hunter/_Base/7bcf092/5d27811/ec05bef/Install/lib --enable-shared --disable-static --prefix=/home/user/.hunter/_Base/7bcf092/5d27811/ec05bef/Build/x11/Install
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2011-11-11, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2011-11-11

uname -m = aarch64
uname -r = 4.4.38-tegra
uname -s = Linux
uname -v = #1 SMP PREEMPT Thu May 17 00:15:19 PDT 2018
```

When I download the newest `config.guess` and `config.sub` from the urls mentioned in the error, this fixes the issue. However this is quite annoying to fork the sources for all these projects just to update these two files. Would it be possible to have hunter detect this issue, and replace these files in place?

**Comment by ruslo** [comment]
> Here is the log until first error reported by Hunter, option HUNTER_STATUS_DEBUG is ON

I don't see logs. What version of X11 you have there? It should be 1.6.7:
- https://github.com/ruslo/hunter/blob/v0.23.166/cmake/projects/x11/hunter.cmake#L26-L35

It's not 2011 release: `libX11-1.6.7.tar.bz2 | 2018-10-09 14:30 | 2.2M`

**Comment by sjdrc** [comment]
Will upload logs later today.
x11 package contains more recent config files from `2017-01-01` (which is still outdated compared to its release date)
For example: https://www.x.org/releases/individual/proto/xproto-7.0.31.tar.bz2
`xproto-7.0.31.tar.bz2	2016-09-23 06:50	293K`
If you download this file and extract its contents, you will find that `config.guess` and `config.sub` are outdated.
`grep 'timestamp' config.guess | head -1`
`timestamp='2006-02-23'`

**Comment by sjdrc** [comment]
https://gist.github.com/sjdrc/b38e2820039dafadf3bc8d4112ce539e
@ruslo You can see the issue occurring here with the latest renderproto.

**Comment by sjdrc** [comment]
@ruslo Any ideas on how best to fix this?

**Comment by ruslo** [comment]
> Any ideas on how best to fix this?

1. Fix upstream, use upstream URL
2. Patch upstream, use patched URL

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
