### ISSUE TITLE
Synchronize GTest with upstream release v1.8.1

### ISSUE THREAD

**Issue by andoks** [ruslo/hunter#1856]
Upstream GTest released [v1.8.1 autumn 2018](https://github.com/google/googletest/releases), in which one of the changes is a [fix for building with newer MSVC](https://github.com/google/googletest/issues/1616). Would be great to have this in hunter too.

**Comment by ruslo** [comment]
I've created branch `hunter-1.8.1` based on the `v1.8.1` tag:
- https://github.com/hunter-packages/googletest

Feel free to send patches from the previous version to this branch (not sure if they needed though):
- https://github.com/hunter-packages/googletest/tree/hunter

Related docs:
- https://docs.hunter.sh/en/latest/creating-new/patch.html
- https://docs.hunter.sh/en/latest/creating-new/update.html

**Comment by chfast** [comment]
I hope not a lot of changes are needed, but at least we should change the project version from `1.9.0` to `1.8.1`. It looks it confuses Hunter.

**Comment by ruslo** [comment]
> at least we should change the project version from 1.9.0 to 1.8.1

Yes, that looks not very consistent:
- https://github.com/google/googletest/blob/release-1.8.1/CMakeLists.txt#L8

Git tag is `release-1.8.1` and `GOOGLETEST_VERSION` is `1.9.0`.

Please contact upstream developers.

**Comment by chfast** [comment]
> Please contact upstream developers.

https://github.com/google/googletest/issues/2256

**Comment by chfast** [comment]
> > Please contact upstream developers.
> 
> [google/googletest#2256](https://github.com/google/googletest/issues/2256)

They are not going to fix it so it has to be fixed in hunter-packages.

**Comment by craffael** [comment]
Has anyone been working on this issue? I have the problem that I currently cannot compile googleTest with GCC9.1 because of this. Upgrading to 1.8.1 would resolve the issue for me...

**Comment by chfast** [comment]
No progress besides what was already said. 
The code is pulled to hunter-packages: https://github.com/hunter-packages/googletest/tree/hunter-1.8.1
Now it requires to apply Hunter and CMake changes on top of it.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst

**Comment by chfast** [comment]
The upstream GTest 1.8.1 seems to be working fine in Hunter, the only change is the target `GTest::main` is named `GTest::gtest_main`.

You can use it with local config.

```
hunter_config(
    GTest
    VERSION 1.8.1
    URL https://github.com/google/googletest/archive/release-1.8.1.tar.gz
    SHA1 152b849610d91a9dfa1401293f43230c2e0c33f8
)
```
