### ISSUE TITLE
PNG package has different target than CMake Upstream

### ISSUE THREAD

**Issue by cristianadam** [ruslo/hunter#1858]
The hunter PNG package should contain the same target name as the [FindPNG.cmake](https://cmake.org/cmake/help/v3.14/module/FindPNG.html) module (PNG::PNG, and not PNG::png)

vcpkg got it [right](https://github.com/microsoft/vcpkg/blob/master/ports/libpng/usage), and here is the [hunter example](https://github.com/ruslo/hunter/blob/master/examples/PNG/CMakeLists.txt)

This means that one can't use hunter with generic CMake code that would work on Linux / Windows.

```
    find_package(PNG REQUIRED)
    target_link_libraries(main PRIVATE PNG::PNG)
```

**Comment by ruslo** [comment]
Same as [here](https://github.com/ruslo/hunter/issues/1857#issuecomment-491940896), please send the patches [upstream](https://github.com/glennrp/libpng). As far as I can see the difference is that they are not using `NAMESPACE` at all:
- https://github.com/glennrp/libpng/blob/v1.6.37/CMakeLists.txt#L918

**Comment by ruslo** [comment]
`ALIAS` target `PNG::PNG` added:
- https://docs.hunter.sh/en/latest/packages/pkg/PNG.html

Released: https://github.com/ruslo/hunter/releases/tag/v0.23.177
