### ISSUE TITLE
Freetype has different package and target name than CMake Upstream

### ISSUE THREAD

**Issue by cristianadam** [ruslo/hunter#1859]
The hunter Freetype package should have the same name as the [FindFreetype.cmake](https://cmake.org/cmake/help/v3.14/module/FindFreetype.html) module (`Freetype` and not `freetype`), and the same target name (`Freetype::Freetype`, and not `freetype::freetype`)

vcpkg got it [right](https://github.com/microsoft/vcpkg/blob/master/ports/freetype/usage), and here is the [hunter example](https://github.com/ruslo/hunter/blob/master/examples/freetype/CMakeLists.txt)

This means that one can't use hunter with generic CMake code that would work on Linux / Windows.

```    
    find_package(Freetype REQUIRED)
    target_link_libraries(main PRIVATE Freetype::Freetype)
```

**Comment by ruslo** [comment]
Same as [here](https://github.com/ruslo/hunter/issues/1857#issuecomment-491940896), please send patches for generating imported target [upstream](https://www.freetype.org/).

**Comment by ruslo** [comment]
`ALIAS` target `Freetype::Freetype` added:
- https://docs.hunter.sh/en/latest/packages/pkg/freetype.html

Released: https://github.com/ruslo/hunter/releases/tag/v0.23.177
