### ISSUE TITLE
Add rabbitmq-c library

### ISSUE THREAD

**Issue by oliverdaniell** [ruslo/hunter#186]
Official version: https://github.com/alanxz/rabbitmq-c
Hunterized version: https://github.com/oliverdaniell/rabbitmq-c/releases

Pull request https://github.com/ruslo/hunter/pull/185

**Comment by oliverdaniell** [comment]
Let me know if any changes are required

**Comment by ruslo** [comment]
@oliverdaniell New wiki page: https://github.com/ruslo/hunter/wiki/pkg.rabbitmq.c

**Comment by oliverdaniell** [comment]
@ruslo Many Thanks! You've done a fantastic job with hunter.

**Comment by oliverdaniell** [comment]
@ruslo Is there any chance that you could do a pre-release, I'm trying to add SimpleAmqpClient which depends on rabbitmq-c

**Comment by ruslo** [comment]
>  Is there any chance that you could do a pre-release
Sure: https://github.com/ruslo/hunter/releases/tag/v0.11.8

**Comment by oliverdaniell** [comment]
got it, thanks
