### ISSUE TITLE
HUNTER_DOWNLOAD_SERVER is not applied to URL/SHA1 config

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#1866]
The URL + SHA1 package specification of the form

```
hunter_config(foo URL .. SHA1 ..)
```

is not currently handled by use of `HUNTER_DOWNLOAD_SERVER`.  I believe the URL + SHA1 feature was implemented after `HUNTER_DOWNLOAD_SERVER`, so that isn't surprising.  I'm assuming this is just an omission. 

Details below.

* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **[Yes]**
* I'm using [latest](https://github.com/ruslo/hunter/releases) Hunter `URL`/`SHA1`. **[Yes]**

* I've created [SSCCE](http://www.sscce.org/) GitHub repository to reproduce the issue:
  - https://github.com/headupinclouds/hunter_download_server_url_sha1_test

* Travis build reproducing issue: Please let me know if travis jobs are needed for this report and I can create them.

* I'm building on [Linux].
* [I'm using system CMake]
* CMake version: 3.12.4

* I'm using unmodified toolchain gcc from [Polly](https://github.com/ruslo/polly)

I'm using the next command line on generate step:
```
#!/bin/bash

HUNTER_DOWNLOAD_SERVER=${PWD}/_Downloads/
HALF_DIR=${HUNTER_DOWNLOAD_SERVER}/bc445fc2b91c7a2c4ea0025012068ecab18ef36d/bc445fc
HALF_FILENAME=${HALF_DIR}/v1.1.0-p1.tar.gz
EMPTY_DIR=${PWD}/_Empty
mkdir -p ${HALF_DIR}
mkdir -p ${EMPTY_DIR}
wget https://github.com/hunter-packages/half/archive/v1.1.0-p1.tar.gz -O ${HALF_FILENAME}

polly_opts=(
    --toolchain gcc
    --config-all Release
    --verbose
    --clear
)

SERVER_GOOD="HUNTER_DOWNLOAD_SERVER=file://${HUNTER_DOWNLOAD_SERVER}"
SERVER_FAIL="HUNTER_DOWNLOAD_SERVER=file://${EMPTY_DIR}"

polly.py ${polly_opts[@]} --fwd URL_FIX=OFF                  --clear | tee should_work_fix_off.txt
polly.py ${polly_opts[@]} --fwd URL_FIX=OFF "${SERVER_FAIL}" --clear | tee should_fail_fix_off.txt
polly.py ${polly_opts[@]} --fwd URL_FIX=ON  "${SERVER_GOOD}" --clear | tee should_work_fix_on.txt
polly.py ${polly_opts[@]} --fwd URL_FIX=ON  "${SERVER_FAIL}" --clear | tee should_fail_fix_on.txt

# Note: 
# grep -e "new URL" should*.txt 
# only shows up when URL_FIX=ON enable manual hunter_download_server_url in
# cmake/Hunter/config.cmake
```

**Comment by headupinclouds** [comment]
https://github.com/ruslo/hunter/blob/9e43e66c172663c5f4234549be75c9a6c9255bf4/cmake/modules/hunter_get_package_url.cmake#L42-L48

I believe this code below needs to be:
```
set(HUNTER_PACKAGE_VERSION "${HUNTER_PACKAGE_SHA1}")
```
Instead of:
```
set(HUNTER_PACKAGE_VERSION "${HUNTER_${package}_VERSION}") 
```

When using the URL/SHA1 variant.

https://github.com/ruslo/hunter/blob/229b04b5a57d497c4531284c4b9143974eb11213/cmake/modules/hunter_download.cmake#L79-L80

https://github.com/ruslo/hunter/blob/229b04b5a57d497c4531284c4b9143974eb11213/cmake/modules/hunter_download.cmake#L89-L94

**Comment by ruslo** [comment]
Locally specified `URL` takes a priority, it's here:
- https://github.com/ruslo/hunter/blob/2cfb020bd5b01bddc9b10ff7fe0e4c7cbee5f2a3/cmake/modules/hunter_get_package_url.cmake#L29-L35

[HUNTER_DOWNLOAD_SERVER](https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-download-server) was designed to overwrite global URLs from Hunter. Current logic is: modify everything global, do not touch anything specified by the user. Also, archive packed by `GIT_SELF` feature uses the same mechanism; it should not be affected by `HUNTER_DOWNLOAD_SERVER` too.

**Comment by headupinclouds** [comment]
Okay, that seems reasonable.  Shall I add a note here: https://github.com/ruslo/hunter/blob/master/docs/reference/user-variables.rst#hunter_download_server?

**Comment by ruslo** [comment]
> Shall I add a note here

Yes, sure

**Comment by headupinclouds** [comment]
I've added a note in PR https://github.com/ruslo/hunter/pull/1869
