### ISSUE TITLE
Unable to build OpenSSL with fPIC toolchain

### ISSUE THREAD

**Issue by sjdrc** [ruslo/hunter#1870]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **[Yes]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes]**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **[Yes]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **[Yes]**
* I'm using [latest](https://github.com/ruslo/hunter/releases) Hunter `URL`/`SHA1`. **[Yes]**

* I've created [SSCCE](http://www.sscce.org/) reproducing the issue:
```cmake
# CMakeLists.txt

cmake_minimum_required(VERSION 3.14.3)
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.171.tar.gz"
    SHA1 "5d68bcca78eee347239ca5f4d34f4b6c12683154"
)

project(foo)

hunter_add_package(OpenSSL)
find_package(OpenSSL CONFIG REQUIRED)
```

I've checked that the first error in logs **IS NOT** `external.build.failed`. **[No]**
https://gist.github.com/sjdrc/5f2b95e842d0eac982ae65a845fd8929

* I'm building on [Linux].
* [I've built CMake from sources myself]
* CMake version: <3.14.3>

* I'm using my toolchain:
```
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```

I'm using the next command line on generate step:
```
cmake -H. -B_builds "-GUnix Makefiles"
```

---
The issue here is that OpenSSL is already configured to build with -fPIC. When the toolchain adds this flag, it is duplicated and ./configure fails.

**Comment by ruslo** [comment]
> I've created SSCCE reproducing the issue

What is inside `LOCAL` ? `HunterGate` is not included.

> I'm using the next command line on generate step

Are you using toolchain?

> I've checked that the first error in logs IS NOT external.build.failed. [No]

Please read this part:
- https://docs.hunter.sh/en/latest/reference/errors/error.external.build.failed.html#what-to-do

There is no `PIC` toolchain in CI testing:
- https://travis-ci.org/ingenue/hunter/builds/516585068

> When the toolchain adds this flag, it is duplicated and ./configure fails.

See nothing wrong about it. If it's true feel free to report the issue upstream.

**Comment by sjdrc** [comment]
I erroneously had LOCAL in the HunterGate call.
Fixed minimal example.
Attached log with HUNTER_STATUS_DEBUG=ON.

The issue is that OpenSSL is being built with PIC by default, and hence using a PIC toolchain causes the build to fail. Seeing as using a toolchain is the only way to apply global options to dependencies, this breaks my builds. The only work around would be to specify custom `CMAKE_ARGS` to every dep except for OpenSSL.

**Comment by sjdrc** [comment]
If I edit the `cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in` script, to add the following lines onto line 132, after the `if (BUILD_SHARED_LIBS)` block then the issue no longer is present:

```cmake
if (CMAKE_POSITION_INDEPENDENT_CODE)
	string(REPLACE " -fPIC" "" configure_opts ${configure_opts})
endif()
```

Would this fix be acceptable to you? If so I will create a pull request.

**Comment by ruslo** [comment]
> string(REPLACE " -fPIC" "" configure_opts ${configure_opts})

Probably the problem is about leading space and not `-fPIC` flag, can you try:
- https://github.com/ruslo/hunter/blob/v0.23.172/cmake/projects/OpenSSL/schemes/url_sha1_openssl_macos.cmake.in#L73

?

Also, there is `SKIP_PIC` for macOS build (for Linux another scheme is used):
- https://github.com/ruslo/hunter/blob/v0.23.172/cmake/projects/OpenSSL/schemes/url_sha1_openssl_macos.cmake.in#L68-L71

**Comment by sjdrc** [comment]
> string(REGEX REPLACE "^ " "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
You're right, it was because of the leading space. I just inserted that line before "# Pass C compiler through" and now it works.

Would you like me to send a pull request for it or will you just make the change directly?

**Comment by sjdrc** [comment]
https://github.com/ruslo/hunter/pull/1875

**Comment by sjdrc** [comment]
Fixed by merged pull request
