### ISSUE TITLE
Add "libigl" package

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1871]
* I'm interested in package `libigl`
* Here is the official site of package https://github.com/libigl/libigl

* This package is using Git

* Official GitHub repository: https://github.com/libigl/libigl

* Used build system: CMake

* This package has next dependencies:

  * `Eigen` (required, available in Hunter: https://docs.hunter.sh/en/latest/packages/pkg/Eigen.html)

* I've disabled the following optional dependencies:
  * `CoMiso`
  * `Embree`
  * `GLFW`
  * `PNG`
  * `Tetgen`
  * `Triangle`
  * `XML`
  * `Python`

* Created an upstream PR here: https://github.com/libigl/libigl/pull/1202

While we wait, I need a fork. :smile: @ruslo

**Comment by ruslo** [comment]
> While we wait, I need a fork.

See https://github.com/hunter-packages/libigl

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/pull/1876
