### ISSUE TITLE
Add "zip" package

### ISSUE THREAD

**Issue by rbsheth** [ruslo/hunter#1874]
* I'm interested in package `zip`
* Here is the official site of package https://github.com/kuba--/zip

* This package is using Git

* Used build system: CMake

* This package has next dependencies:
  * `miniz` (required, not available in Hunter, modified from origin at https://github.com/richgel999/miniz)

@ruslo Need a branch for this one as well.

**Comment by ruslo** [comment]
Fork:
- https://github.com/hunter-packages/zip

**Comment by rbsheth** [comment]
@ruslo Was able to merge upstream https://github.com/kuba--/zip/pull/105, fork can be deleted.

**Comment by ruslo** [comment]
> Was able to merge upstream https://github.com/kuba--/zip/pull/105, fork can be deleted

@rbsheth Great! 👍 

Fixed: https://github.com/ruslo/hunter/pull/1878
