### ISSUE TITLE
Add PCRE2 package

### ISSUE THREAD

**Issue by cristianadam** [ruslo/hunter#1890]
* I'm interested in package PCRE2, since it's the **only external** that Qt6 Core needs, and  Hunter doesn't have.
* Here is the official site of package https://www.pcre.org/

* This package is using SVN: `svn co svn://vcs.exim.org/pcre2/code/trunk pcre`

* Used build system: CMake / autotools

I compiled it locally with CMake with MinGW like:
```
cmake -GNinja -DCMAKE_BUILD_TYPE=Release ^
  -DCMAKE_INSTALL_PREFIX=instdir ^
  ..\pcre2-10.33\ ^
  -DPCRE2_BUILD_PCRE2_16=ON ^
  -DPCRE2_SUPPORT_JIT=ON ^
  -DPCRE2_SUPPORT_UNICODE=ON
  -DPCRE2_STATIC=ON

cmake --build .
cmake --build . --target install 
```

vcpkg has it packaged here: https://github.com/microsoft/vcpkg/tree/master/ports/pcre2

**Comment by ruslo** [comment]
See:
- https://docs.hunter.sh/en/latest/packages/pkg/pcre2.html

Released:
- https://github.com/ruslo/hunter/releases/tag/v0.23.187

Name of the imported target is based on the project name:
- https://github.com/hunter-packages/pcre2/blob/6f5f21f460ff186e908994f8645e50806d13e591/CMakeLists.txt#L89
- https://github.com/hunter-packages/pcre2/blob/6f5f21f460ff186e908994f8645e50806d13e591/CMakeLists.txt#L543
