### ISSUE TITLE
Shared Library not working OpenTracing

### ISSUE THREAD

**Issue by akshit-sharma** [ruslo/hunter#1898]
The issue is with linking OpenTracing to the executable. As mentioned in `https://github.com/ruslo/hunter/blob/master/docs/packages/pkg/opentracing-cpp.rst`, there should be two version of library that can be used. Static library is able is compile successfully but the shared version gives the following error.

I  don't know if the shared version is no more supported or something. Raising this issue to highlight that opentracing-cpp.rst says it support both static and shared library but only one works.

```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.1)

include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.23.191.tar.gz"
    SHA1 "5292c5a83d56571cbefc76257dbea9b7bcedf164"
)

project(foo)

hunter_add_package(opentracing-cpp)
find_package(OpenTracing CONFIG REQUIRED)

add_executable(foo foo.cpp)
target_link_libraries(foo PUBLIC OpenTracing::opentracing)
```

C++ source is just printing a hello world line.

* I've created GitHub repository to reproduce the issue:
  - https://github.com/akshit-sharma/opentracing-hunter

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
CMake Error at CMakeLists.txt:15 (add_executable):
  Target "foo" links to target "OpenTracing::opentracing" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

* I'm building on [Linux].
* [I've built CMake from sources myself]
* CMake version: 3.12.4

---

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
