### ISSUE TITLE
Android test build failed in hunter_get_toolchain_binaries

### ISSUE THREAD

**Issue by Bjoe** [ruslo/hunter#1903]
I get [following cmake error](https://travis-ci.org/Bjoe/hunter/jobs/550267738#L643) in my [test.botan branch](https://github.com/Bjoe/hunter/tree/test.botan) for #1897 in android NDK r17 api 24 arm64 build:
<pre>
Unexpected empty string
</pre>

The root cause is this line:
[Hunter/unknown/71a7bfb/Unpacked/cmake/modules/hunter_get_toolchain_binaries.cmake:41](https://travis-ci.org/Bjoe/hunter/jobs/550267738#L656)
`41: hunter_assert_not_empty_string("${CMAKE_CXX_ANDROID_TOOLCHAIN_MACHINE}")`
This variable `CMAKE_CXX_ANDROID_TOOLCHAIN_MACHINE` via android polly toolchain.

I created also a [discussion for the workaround for Android studio](https://github.com/forexample/android-studio-with-hunter/issues/2) for the same issue.

Is this `hunter_get_toolchain_binaries` used somewhere for android ? Maybe we should change/fix this in `hunter_get_toolchain_binaries` ?

I'm also little bit confused why polly is set only `ANDROID_NDK` .... it looks like cmake is [expecting `CMAKE_ANDROID_NDK`](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling-for-android-with-the-ndk) ....

**Comment by ruslo** [comment]
> cmake is expecting CMAKE_ANDROID_NDK

There are few ways to set the path; all of them are valid and documented.

Quotes:

```
Else, if a cmake variable ANDROID_NDK is set it will be used as the value of
CMAKE_ANDROID_NDK, and the NDK will be used.
```

```
CMAKE_ANDROID_NDK
... If not specified, a default for this variable will be chosen as specified above.
```

> The root cause is this line:
> 41: hunter_assert_not_empty_string("${CMAKE_CXX_ANDROID_TOOLCHAIN_MACHINE}")

I don't know where is the error, probably in a custom scheme. I've just tried `android-ndk-r17-api-24-arm64-v8a-clang-libcxx14` toolchain with simple CMakeLists.txt, and both `CMAKE_CXX_ANDROID_TOOLCHAIN_MACHINE`/`CMAKE_C_ANDROID_TOOLCHAIN_PREFIX` are set.

**Comment by Bjoe** [comment]
@ruslo **grrr** sorry for that I didn't read the cmake documentation carefully ...

> I don't know where is the error, probably in a custom scheme

With custom scheme you mean [cmake/projects/botan/schemes/url_sha1_botan.cmake.in](https://github.com/Bjoe/hunter/blob/pr.botan/cmake/projects/botan/schemes/url_sha1_botan.cmake.in)

But what should I do there? `CMAKE_CXX_ANDROID_TOOLCHAIN_MACHINE/CMAKE_C_ANDROID_TOOLCHAIN_PREFIX` should be set globally.

Ok you try an example ... hm but I didn't get how your 

> with simple CMakeLists.txt,

looks like.

I'm just wondering, how the cmake builtin support for Android affecting 3rd party projects in Hunter when the cmake `*_ANDROID_*` variables are not set in a toolchain file. The [Hunter documentation ](https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html) says:

> The toolchain file is the only way to apply global settings for 3rd party projects in Hunter.
>
> Only CMAKE_TOOLCHAIN_FILE will be forwarded for all packages, neither standard CMAKE_CXX_COMPILER/CMAKE_CXX_FLAGS nor custom variables like ANDROID_FOO=boo will be applied globally.

That`s why I use in my projects the toolchain from google NDK.

**Comment by Bjoe** [comment]
Hm I think I get it .... The built in NDK support should be also affecting 3rd party projects because `ANDROID_NDK` and `CMAKE_SYSTEM_VERSION` is set via polly toolchain and should _"activate"_ the builtin NDK support, correct?

**Comment by Bjoe** [comment]
Ok my fault. You are right, my custom scheme was the root cause.
I used:

> project(Hunter LANGUAGES NONE)

instead of

>  project(Hunter)
