### ISSUE TITLE
ncursesw dependency fails to configure due to c preprocessor not working

### ISSUE THREAD

**Issue by tstack** [ruslo/hunter#1914]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **Yes**
* I'm using [latest](https://github.com/ruslo/hunter/releases) Hunter `URL`/`SHA1`. **Yes**

I could use a little direction on figuring out what is going wrong here.  The ncursesw CI builds work.  But, when trying to add the dependency into my project, it fails to configure.

Copying the example code from hunter and using this CMakeLists.txt file replicates the issue when running `cmake .` on OS X:

```cmake
cmake_minimum_required(VERSION 3.2)

include("cmake/HunterGate.cmake")
HunterGate(
        URL "https://github.com/ruslo/hunter/archive/v0.23.200.tar.gz"
        SHA1 "f6171fde181327a7d3329641bbd543a882222c91"
)

project(download-ncurses)

# DOCUMENTATION_START {
hunter_add_package(ncursesw)
find_package(ncursesw CONFIG REQUIRED)

add_executable(boo boo.cpp)
target_link_libraries(boo PUBLIC PkgConfig::ncursesw)
# DOCUMENTATION_END }
```

The ncursesw configure output before the failure looks like this:

```
checking whether we are using the GNU C compiler... yes
checking whether /Library/Developer/CommandLineTools/usr/bin/cc accepts -g... yes
checking version of /Library/Developer/CommandLineTools/usr/bin/cc... 10.0.1
checking for /Library/Developer/CommandLineTools/usr/bin/cc option to accept ANSI C... none needed
checking $CC variable... ok
checking how to run the C preprocessor... /lib/cpp
configure: error: C preprocessor "/lib/cpp" fails sanity check
```

The relevant parts of config.log contain:

```
It was created by configure, which was
generated by GNU Autoconf 2.52.20170501.  Invocation command line was

  $ ./configure AR=/Library/Developer/CommandLineTools/usr/bin/ar LD=/Library/Developer/CommandLineTools/usr/bin/ld NM=/Library/Developer/CommandLineTools/usr/bin/nm OBJDUMP=/Library/Developer/CommandLineTools/usr/bin/objdump RANLIB=/Library/Developer/CommandLineTools/usr/bin/ranlib STRIP=/Library/Developer/CommandLineTools/usr/bin/strip CC=/Library/Developer/CommandLineTools/usr/bin/cc CXX=/Library/Developer/CommandLineTools/usr/bin/c++ CPPFLAGS=-I/Users/tstack/.hunter/_Base/f6171fd/7e73122/e7c1989/Install/include CFLAGS=-O3 -DNDEBUG  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk CXXFLAGS=-O3 -DNDEBUG  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk LDFLAGS=-L/Users/tstack/.hunter/_Base/f6171fd/7e73122/e7c1989/Install/lib --enable-ext-mouse --enable-sigwinch --enable-ext-colors --enable-widec --enable-pc-files --disable-shared --enable-static --prefix=/Users/tstack/.hunter/_Base/f6171fd/7e73122/e7c1989/Build/ncursesw/Install --with-pkg-config-libdir=/Users/tstack/.hunter/_Base/f6171fd/7e73122/e7c1989/Build/ncursesw/Install/lib/pkgconfig

...

configure:2337: checking how to run the C preprocessor
configure:2363: /Library/Developer/CommandLineTools/usr/bin/cc -E -I/Users/tstack/.hunter/_Base/f6171fd/7e73122/e7c1989/Install/include conftest.c
configure:2359:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
configure:2369: $? = 1
configure: failed program was:
```

So, it looks like the standard include path was left out.  Looking at the previous invocations of the compiler, they seem to have `-isysroot` options, which are not included in the CPPFLAGS:

```
configure:2097: checking for /Library/Developer/CommandLineTools/usr/bin/cc option to accept ANSI C
configure:2154: /Library/Developer/CommandLineTools/usr/bin/cc  -c -O3 -DNDEBUG  -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -I/Users/tstack/.hunter/_Base/f6171fd/7e73122/e7c1989/Install/include conftest.c >&5
configure:2157: $? = 0
```

So, I'm wondering if the problem is in the ncursesw package or the hunter autotools machinery where the CPPFLAGS variable is not setup completely correctly.

* I'm building on OSX Mojave.
* I'm using brew CMake release
* CMake version: 3.14.5

* I'm using the Xcode toolchain

**Comment by ruslo** [comment]
> cmake .

Always do [out-of-source](https://cgold.readthedocs.io/en/latest/tutorials/out-of-source.html) configuration.

> I've read Reporting bugs section carefully. Yes

The full log is missing.

> I'm using the Xcode toolchain

This may be not related, but default `-G Xcode` is not part of the testing:
- https://github.com/ingenue/hunter/blob/af72aa360db1f61c078ae49b91d4db55b8d66e30/.travis.yml#L80-L90

> I'm building on OSX Mojave.
> I'm using brew CMake release
> CMake version: 3.14.5

CMake 3.14.4, Xcode 9.4.1, toolchain `osx-10-13-make-cxx14` is working fine for me.

Have you tried to reproduce the problem with Travis CI?

> So, it looks like the standard include path was left out. Looking at the previous invocations of the compiler, they seem to have -isysroot options, which are not included in the CPPFLAGS

I don't see `-isysroot` in my `CPPFLAGS` either and it doesn't seem to be an issue:
```
-- [hunter *** DEBUG *** ...]   CPPFLAGS=-I/.../.hunter/.../Install/include
-- [hunter *** DEBUG *** ...]   CFLAGS=-O3 -DNDEBUG  -isysroot /.../xcode/9.4.1/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.13
-- [hunter *** DEBUG *** ...]   CXXFLAGS=-O3 -DNDEBUG -std=c++14 -stdlib=libc++ -isysroot /.../xcode/9.4.1/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -mmacosx-version-min=10.13 -std=c++14
-- [hunter *** DEBUG *** ...]   LDFLAGS=-L/.../.hunter/.../Install/lib

```

**Comment by tstack** [comment]
> CMake 3.14.4, Xcode 9.4.1, toolchain osx-10-13-make-cxx14 is working fine for me.

With Xcode 10.2.1 and `osx-10-13-make-cxx14`, it's failing for me.

After applying the following change to get the `-isysroot` option added to CPPFLAGS, things start working.

```
diff --git a/cmake/modules/hunter_dump_cmake_flags.cmake b/cmake/modules/hunter_dump_cmake_flags.cmake
index b1adf933..23239846 100644
--- a/cmake/modules/hunter_dump_cmake_flags.cmake
+++ b/cmake/modules/hunter_dump_cmake_flags.cmake
@@ -41,6 +41,8 @@ function(hunter_dump_cmake_flags)
     endif()
   endif()
 
+  set(cppflags "")
+
   if(APPLE AND NOT IOS)
     if(NOT "${CMAKE_OSX_SYSROOT}" STREQUAL "")
       if(NOT EXISTS "${CMAKE_OSX_SYSROOT}")
@@ -49,16 +51,16 @@ function(hunter_dump_cmake_flags)
       # Note: do not use quotes here, see OpenSSL-1.0.2 example
       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isysroot ${CMAKE_OSX_SYSROOT}")
       set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -isysroot ${CMAKE_OSX_SYSROOT}")
+      set(cppflags "-isysroot ${CMAKE_OSX_SYSROOT}")
     endif()
 
     if(NOT "${CMAKE_OSX_DEPLOYMENT_TARGET}" STREQUAL "")
       set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
       set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
+      set(cppflags "${cppflags} -mmacosx-version-min=${CMAKE_OSX_DEPLOYMENT_TARGET}")
     endif()
   endif()
 
-  set(cppflags "")
-
   if(ANDROID)
     string(COMPARE EQUAL "${CMAKE_SYSROOT_COMPILE}" "" no_sysroot_compile)
     if(no_sysroot_compile)
```

**Comment by ruslo** [comment]
> After applying the following change to get the -isysroot option added to CPPFLAGS, things start working.

Feel free to open a pull request. This function is used in many packages, and we need to test them all.

**Comment by ruslo** [comment]
> Feel free to open a pull request. This function is used in many packages, and we need to test them all.

Fix https://github.com/ruslo/hunter/pull/1916 merged, thanks.

> With Xcode 10.2.1 and osx-10-13-make-cxx14, it's failing for me.

Probably it makes sense to add an extra toolchain to CI table to branch `pkg.ncursesw` so we can check it in future.

**Comment by ruslo** [comment]
> Probably it makes sense to add an extra toolchain to CI table to branch pkg.ncursesw so we can check it in future.

https://github.com/ingenue/hunter/pull/382 merged, closing
