### ISSUE TITLE
Cannot Build libTiff as a shared library

### ISSUE THREAD

**Issue by atemysemicolon** [ruslo/hunter#1917]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **[Yes|No]**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **[Yes|No]**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **[Yes|No]**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **[Yes|No]**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **[Yes|No]**
* I'm using [latest](https://github.com/ruslo/hunter/releases) Hunter `URL`/`SHA1`. **[Yes|No]**

```cmake
# CMakeLists.txt

cmake_minimum_required(VERSION 3.14)

# --- Dependency management
include("cmake/HunterGate.cmake")
HunterGate(
        URL "https://github.com/ruslo/hunter/archive/v0.23.202.tar.gz"
        SHA1 "931b1cb6b36a7a96948d2cfc8ec5e553bf3160f3"
        LOCAL
)

set(HUNTER_STATUS_DEBUG ON)

hunter_add_package(TIFF)
find_package(TIFF CONFIG REQUIRED)
```

and my local : cmake/Hunter/config.cmake is as follows :- 

`hunter_config(TIFF VERSION 4.0.2-p5 CMAKE_ARGS BUILD_SHARED_LIBS=ON)`

* I'm building on Linux.
* I'm using official CMake release
* CMake version: 3.14.5

* I'm not using toolchain

I'm using the next command line on generate step:
```
cmake ..
```

---

The above fails when Tiff's Shared option is not passed down to Zlibs. In my opinion, the hunter_package of Tiff should also have a hunter_config where build_shared_libs is passed on to the dependencies. 

However, the same passes when, in my config, I ask ZLIB to also be built as a shared library with 
`hunter_config(ZLIB VERSION 1.2.11-p1 CMAKE_ARGS BUILD_SHARED_LIBS=ON)`. But, on probing the built tiff library, it is not linked against zlib. 

```
pwd
/home/<username>/.hunter/_Base/931b1cb/8519698/19234f3/Install/lib

ls
cmake  liblibtiffd.so  liblibtiff.so  libzd.so  libzd.so.1  libzd.so.1.2.11  libz.so  libz.so.1  libz.so.1.2.11

ldd liblibtiffd.so 
	linux-vdso.so.1 (0x00007ffe8bbf5000)
	**libzd.so.1 => not found**
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f96522ae000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9652121000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f9651f37000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f96524e7000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9651f1d000)

ldd liblibtiff.so 
	linux-vdso.so.1 (0x00007ffe478b2000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f652420c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f6524081000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6523ef4000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6523d0a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f65244cd000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f6523cf0000)

```

if You see, in both cases liblibtiff and liblibtiffd are not linked against the built Zlib library; They are linked against the system one; And for liblibtiff.so , it seems like it cannot find the libzd.so.1 on the same path.

**Comment by ruslo** [comment]
> set(HUNTER_STATUS_DEBUG ON)

Set it to `CACHE`:
- https://docs.hunter.sh/en/latest/reference/user-variables.html#cmake

> The above fails when Tiff's Shared option is not passed down to Zlibs. In my opinion, the hunter_package of Tiff should also have a hunter_config where build_shared_libs is passed on to the dependencies.

It should not. Mixing shared and static libraries is tricky, but it's a valid configuration if you know what you're doing, hence `hunter_config(TIFF CMAKE_ARGS BUILD_SHARED_LIBS=ON)` should not automatically apply `hunter_config(ZLIB CMAKE_ARGS BUILD_SHARED_LIBS=ON`). If you want to build all your dependencies as shared, then use `HUNTER_BUILD_SHARED_LIBS`:
- https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-build-shared-libs

> on probing the built tiff library, it is not linked against zlib

I think it's a problem with RPATH, patch with a fix is welcome. As a workaround, you can do:

```
LD_LIBRARY_PATH=/home/<username>/.hunter/_Base/931b1cb/8519698/19234f3/Install/lib ldd liblibtiff.so 
```

**Comment by atemysemicolon** [comment]
My quick fix was to link with the Release lib, which somehow finds a zlib (though the wrong one)

Just to probe further and understand the paradigm behind the first point : -

**Thought experiment** : -
**Premise** : So let's say the library I build --libFoo-- depends on two libraries directly : - libtiff and libpng.
However, this indirectly depends on zlib because libtiff depends on zlib.  I want to link statically built libpng and dynamically built libTiff. 
**Method** : In order to do this, I would modify config.cmake with  `hunter_config(TIFF VERSION 4.0.2-p5 CMAKE_ARGS BUILD_SHARED_LIBS=ON) `and a similar one for **png** without the shared_libs flag. I don't mention flags for zlib, because, hypothetically, **I do not know about the dependency**.
**Possible Failure** : When you do this, tiff would not compile (right in the cmake ..) stage. It tries to link zlib againt libtiff, however zlib (tiff's dependency ) is built statically, and linking on linux fails with a request to use -fPIC error.  
**Possible fix** : Manually scan through dependencies of hunter package's dependency and declare them on the config.cmake to build as shared libs. 


_Is this the desired functionality?_

**Comment by ruslo** [comment]
> My quick fix was to link with the Release lib, which somehow finds a zlib (though the wrong one)

It's not a fix. It will work only accidentally.

> When you do this, tiff would not compile (right in the cmake ..) stage. It tries to link zlib againt libtiff, however zlib (tiff's dependency ) is built statically, and linking on linux fails with a request to use -fPIC error.

Build with PIC toolchain:
- https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html#simple-toolchains

ZLIB can't know a priori that you will link it to a shared library.

> Is this the desired functionality?

From my understanding, there are few sane ways to deal with static and shared:
- Build all static. The default option for `add_library` in CMake, that's why it's a default in Hunter. No action needed.
- Build all shared. Used in may package managers because it's easy to run an update. Since the code is shared, that leads to a small size overall. Use `HUNTER_BUILD_SHARED_LIBS=ON` for third parties and `BUILD_SHARED_LIBS=ON` for your local build.
- Build a local library as shared and dependencies as static. In this case, all dependencies will be "absorbed" by a local shared library. Allow you to have a single file like DLL or iOS/macOS framework (it's a directory to be precise) that you can drop into another project. Add `BUILD_SHARED_LIBS=ON` to your local build.

I don't see how the other cases can be managed automatically. You have to tweak everything manually if it's not as simple as described above.

**Comment by atemysemicolon** [comment]
Thanks, very useful. I'll have a look at the RPath issue to see whether I can come up with a fix

**Comment by atemysemicolon** [comment]
Hey, do you have some documentation on how to make a fix? I'm confused about the SHA part (in order to test it without using the hunter-packages version of my library). I'm looking at the pages in this section : https://docs.hunter.sh/en/latest/creating-new/patch.html , but it feels a bit unclear to me. 

What are the steps to go about if I want to make a change?

**Comment by ruslo** [comment]
> I'm looking at the pages in this section : https://docs.hunter.sh/en/latest/creating-new/patch.html , but it feels a bit unclear to me.

Can you be more specific, what is exactly unclear?

> What are the steps to go about if I want to make a change?

It depends on where the tweak should be introduced. The first step will be to apply a fix to the current version of the package:
- ZLIB is here: https://github.com/hunter-packages/zlib
- TIFF is here: https://github.com/hunter-packages/tiff

**Comment by atemysemicolon** [comment]
It´s unclear to me as to how to test locally whether my fix works. Like, as to how to calculate the SHA of a local change (before uploading it to github), and to make sure Hunter takes my locally fixed files and doesn't do a fresh download from Hunter Packages ..?

**Comment by ruslo** [comment]
> Like, as to how to calculate the SHA of a local change (before uploading it to github)

SHA1 of archive used in `hunter.cmake` file. You can push the changes to your fork and pick them like this:
- https://github.com/hunter-packages/tiff/archive/5dcec596c186c7689bcb901c4ed983f9520c639e.zip

Then run `jenkins.py`:
- https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#testing-locally

Check the logs that the right URL is used for the build. Also, you can create archive locally, e.g. with `git archive` command (you have to commit your patch) then add it to `hunter.cmake` in a similar way but use `URL file:///path/to/local/archive.tar` instead of `URL https://github.com/...`.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
