### ISSUE TITLE
Hunter: To be or not to be

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#1921]
Hi,

Peoples with a sharp eye may notice that the "Sponsor" button [appeared](https://github.com/ruslo/hunter/commit/3c2b009df51301c998196ee7db100b76fed84e81) at the top of the project's page on GitHub. It's not just a cool-looking button - it has a purpose :)

If I do not receive enough support on https://patreon.com/ruslo, I'm planning to stop the maintenance of the Hunter on **August 25**, 2019.

P.S. If this unfortunate event will take place and you're the developer who feels he is interested in maintenance, you can ping me at ruslan_baratov@yahoo.com (please don't leave any messages about it here!).

Thanks for understanding,
Ruslo

**Comment by wheybags** [comment]
This is an amazing project, it would be a huge shame to see it die. I have used hunter a lot in various jobs and open source projects, and it has made a serious difference to me. I've added my support on patreon :)
What would be "enough" support?
I really hope you can get what you need, but I understand the amount of work that goes into a project like this, and wouldn't hold it against you if you had to leave.
Good luck!

**Comment by dvirtz** [comment]
I've added my support as well.
The one big thing this project lacks is promotion. Making a good conference talk can bring a lot of users and supporters.

**Comment by tstack** [comment]
Ah, man, I just started converting [lnav](https://github.com/tstack/lnav) over to use hunter since it seemed easier than conan[1]/vcpkg[2].  I want the end-user to only need cmake since that's already installed or easily installable most places.  I also started to build a front-end command as mentioned in #1340.  So, I'd rather not see it go away.

[1] - It's nicer for the developer to be able to work within one build system, cmake, rather than having to learn a separate one as well.
[2] - There were no releases, which meant a package could not be added to brew.  So, the end-user would have to figure out how to do that.

**Comment by Kiddinglife** [comment]
@dvirtz I. Annoy agree with you more!

**Comment by cristianadam** [comment]
> The one big thing this project lacks is promotion. Making a good conference talk can bring a lot of users and supporters.

For example this talk [The State of Package Management in C++ - Mathieu Ropert [ACCU 2019]](https://www.youtube.com/watch?v=k99_qbB2FvM) mentioned Hunter, but then discarded it because Hunter was perceived as intrusive.

I pointed out that you can have the same level of support in Hunter like in Conan and VcPkg, you have to treat it separately from you build. You only have to edit one file, a `CMakeLists.txt` file, just like you would do with `conanfile.txt` or a script for vcpkg. The comment was removed from Youtube.

This `CMakeLists.txt` which does this 3rd party dependency download / compilation / installation for Qt6::Base looks like this:

``` cmake
cmake_minimum_required(VERSION 3.14)

file(
  DOWNLOAD https://raw.githubusercontent.com/hunter-packages/gate/master/cmake/HunterGate.cmake
  ${CMAKE_BINARY_DIR}/HunterGate.cmake)

file(WRITE ${CMAKE_BINARY_DIR}/hunter_config.cmake
[=[
hunter_config(pcre2
  VERSION
    ${HUNTER_pcre2_VERSION}
  CMAKE_ARGS
    PCRE2_BUILD_PCRE2_8=OFF
    PCRE2_BUILD_PCRE2_16=ON
    PCRE2_BUILD_PCRE2_32=OFF
    PCRE2_SUPPORT_JIT=ON)
]=])

set(HUNTER_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/hunter)

include(${CMAKE_BINARY_DIR}/HunterGate.cmake)
HunterGate(
  URL "https://github.com/ruslo/hunter/archive/v0.23.187.tar.gz"
  SHA1 "c62a35f423e6358ff0ec4325572527a9c8ddd5c8"
  FILEPATH ${CMAKE_BINARY_DIR}/hunter_config.cmake
)

set(HUNTER_CONFIGURATION_TYPES Release)

project(3rdparty)

hunter_add_package(freetype)
hunter_add_package(ZLIB)
hunter_add_package(PNG)
hunter_add_package(double-conversion)
hunter_add_package(pcre2)

# Create a toolchain file which sets CMAKE_PREFIX_PATH
file(READ ${CMAKE_BINARY_DIR}/_3rdParty/Hunter/install-root-dir hunter_install)
file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/hunter_toolchain.cmake
"list(APPEND CMAKE_PREFIX_PATH \"${hunter_install}\")\n")

if (CMAKE_TOOLCHAIN_FILE)
  file(APPEND ${CMAKE_CURRENT_SOURCE_DIR}/hunter_toolchain.cmake
    "include(${CMAKE_TOOLCHAIN_FILE})\n")
endif()
```

And then just configure the project with `-DCMAKE_TOOLCHAIN_FILE=.../hunter_toolchain.cmake`. 

@ruslo you need to provide some plan on what you would like to tackle in the near / middle / far future.
So that people would know what they buy. Some sort of regular reporting would help. I can think of [KDE Usability & Productivity](https://pointieststick.com/)

**Comment by ruslo** [comment]
> Making a good conference talk can bring a lot of users and supporters.

I really prefer videos like this awesome one:
- https://www.youtube.com/watch?v=TeeLEfT8nCU

Few things have to be polished a little, bit but it's good quality, compact and clean. If I had time, I'd rather spend it on doing something like this.

> For example this talk The State of Package Management in C++ - Mathieu Ropert [ACCU 2019] mentioned Hunter, but then discarded it because Hunter was perceived as intrusive.

I saw the same talk here and left a comment:

- https://www.youtube.com/watch?v=C1m-Uy4nuQA

Yeah, it's quite surprising that he had time to prepare and give a one hour talk but can't find time to read a brief overview or ask a question in Gitter.

I'm a technical guy; you have a problem - I can give you an answer/suggestion of how it can be solved. And I can provide an estimate (if possible) of how much time it can take. That's the social problem. Peoples believe in some things blindly and see what they want to see. Another popular myth about Hunter is that it supports only CMake project and always build packages from sources (i.e., there is no binary download option). Even if both are mentioned on [the front page](https://docs.hunter.sh/en/latest/) of documentation. Also, peoples prefer to spend 5 minutes to write a hateful speech about how everything is bad instead of spending 30 minutes actually to do the fix.

But I guess the strongest punch against Hunter is "Use CMake to write a package manager? Phhhh...". That's a killar argument :)

> you need to provide some plan on what you would like to tackle in the near / middle / far future

Hunter documentation issue was there for two years:
- https://github.com/ruslo/hunter/issues/677

Even there is no high quality skills or time required, only little part of it was done so far.

I almost stopped doing anything about general CMake tutorial:
- https://github.com/ruslo/CGold

Some topics like RPATH covered purely in official CMake/wiki but hit package management again and again:
- https://github.com/ruslo/hunter/issues/1917
- https://github.com/ruslo/hunter/issues/1804
- https://github.com/ruslo/hunter/issues/1802

Automation is missing but important for usability:
- https://github.com/ruslo/hunter/issues/449
- https://github.com/ruslo/hunter/issues/1632

Actually it's hard to find any part of development that don't require support.

> So that people would know what they buy. Some sort of regular reporting would help. I can think of KDE Usability & Productivity

I will provide a summary of the activity if the fundraising succeeds. Also at this point, it's a quite short report - nothing was done in the core for the last year, mostly maintenance and new packages.

> This CMakeLists.txt which does this 3rd party dependency download / compilation / installation for Qt6::Base looks like this:

See this note, I think that's what really you're looking for:
- https://gitter.im/ruslo/hunter?at=5d3698ed5ea6e644ec02bd5c

**Comment by wheybags** [comment]
I think something that would really help is an actual website.
ATM, we have a docs site, which is super necessary, but also not enough. If someone is just browsing around, they want to see a showcase website, something that explains what the project is, and how to use it in the high level. Basically something to "sell" people on trying hunter at all. Also a good place to ask for donations.
Honestly, I think with something more structured like that in place, and a bit of time, hunter could become financially viable. I'm not sure if that will happen before August 25th though, and it will require some input of non-technical work to get there. I hope the current push turns out to be ok, or at least enough to convince you @ruslo to keep pushing to get the project to a sustainable state. IMO the current deadline might just be too hard for that.

**Comment by handicraftsman** [comment]
As an experiment, i have built a simple package manager alongside with a build system wrapper (both are written in Go). Both use simple .json config files for describing packages and build pipeline. It is not compatible with hunter, but it allows easily defining custom packages to be built. Currently it is only tested on amd64 linux, but should work on almost any bash-capable environment. If anybody is interested, i can setup a CI (did not bother with it because its an experimental project) so anybody can download the tools at any time.

**Comment by OvermindDL1** [comment]
The main thing I like about hunter is not other programs needed to be downloaded, installed, whatever, everything is in cmake, so it is easy to drop-in to any existing project regardless of what else is used.  Something requiring Go is not.  ^.^;

Although a front-end to make submitting new libraries to hunter would be amazing, the current github-centric process is a bit... involved.  ^.^;

**Comment by handicraftsman** [comment]
Go compiler links its runtime statically - so you can compile binaries on a CI and them distribute them without requiring to install Go.

**Comment by OvermindDL1** [comment]
> Go compiler links its runtime statically - so you can compile binaries on a CI and them distribute them without requiring to install Go.

That becomes very platform specific though.  For example, I use hunter to acquire and compile dependencies on embedded arm32 systems (little low-power embedded servers around my house).  Are you going to distribute a go program for that?  Does go even support such a system where cmake does?

**Comment by ruslo** [comment]
@handicraftsman @OvermindDL1 I don't think this issue is the right place for such kind of discussions.

**Comment by Knitschi** [comment]
I always wondered how you managed to put so much work into this project in your spare time. I do not blame you that you want to get rid of this burden. 

If your fund raising fails, you could ask the CMake guys if you can add hunter to their project. That way they could manage further development so current users are not left standing in the rain.

**Comment by ruslo** [comment]
> you want to get rid of this burden

I don't want to "get rid of" it. I'm asking for help to make it better.

> so current users are not left standing in the rain

As my first comment states:

> you're the developer who feels he is interested in maintenance, you can ping me at ruslan_baratov@yahoo.com

**Comment by cipold** [comment]
Hi. In the company I work for we use Hunter in most of our C++ projects and are very happy with it! So thank you for providing such a great tool
We would like to support hunter by a monthly payment, however Patreon does not hand out any invoice for the payment only [online receipts](https://support.patreon.com/hc/en-us/articles/115002958303-Where-can-I-find-a-receipt-for-my-memberships-). I was informed that this will cause problems for our administration resulting in cost and thus there is hesitation. Does anyone have a solution for that?

**Comment by madmongo1** [comment]
I would happily contribute to maintenance but almost every time I submit a PR it's rejected on grounds from the ever-changing arbitrary rules.

**Comment by wheybags** [comment]
Your PRs were closed for inactivity.
I've just read through the comment threads, @ruslo went out of his way to help, so I wouldn't say they were "rejected on grounds of the ever-changing arbitrary rules". Changes were requested, and never made, so eventually the inactive PR was clsoed.
I get that it is painful making new packages with hunter, and that would be one thing I'd like to see improved too, but I don't think it's fair to say your packages were rejected arbitrarily, or even rejected at all.

Forking for your company is not the worst idea actually. The main project has to have higher standards for certain things, where your company might not care (eg, "package must work on all supported platforms" vs "we only support windows anyway"). What I have done in the past is make an internal fork and start using it, and get the package upstreamed later. I would encourage you to go back to your closed prs, and address the issues @ruslo raised, and we can all benefit from better packages :)

**Comment by madmongo1** [comment]
@wheybags if it were only me who has experienced the unhelpful, arbitrary, unpublished rules I would accept your rebuttal. It is not.

The project has lost a number of otherwise enthusiastic maintainers for the same reason.

I happen to know two of them.

It is a real problem.

**Comment by wheybags** [comment]
Well, I have added [several packages myself](https://github.com/ruslo/hunter/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Awheybags), and sure, I often had to change things to get them accepted, but they were all accepted when they reached that bar. I had no problems with this process, it is what I would expect when contributing to a well run FOSS project.
IMO the behaviour displayed by @ruslo  in your PRs is more than acceptable, you got prompt, actionable feedback.
As for other people, I can't say if I don't know who they are.

I will reiterate though, that I do agree that it can be too complicated to add and test a package, and that the project could benefit greatly from streamlining that process, but that is a technical issue, not a cultural one.

**Comment by ruslo** [comment]
> ... almost every time I submit a PR it's rejected on grounds of the ever-changing arbitrary rules.

Your pull requests were rejected because of the poor quality.

For example here:

- https://github.com/ruslo/hunter/pull/1862

The goal of the pull request was: "This change adds c++20 support, which is now supported by latest CMake"

The fix, in fact, is adding three characters:

- https://github.com/ruslo/hunter/commit/355a7aeb120a5a92dc06529435d4d292a60b5f22

You've opened pull request with seven(!) commits:
```
@madmongo1 added SocketIOClient package 3e7d0a5
@madmongo1 updated socketio hash 34cff1d
@madmongo1 Merge branch 'master' of https://github.com/ruslo/hunter abfbd47
@madmongo1 Merge remote-tracking branch 'upstream/master' c01768e
@madmongo1 Merge remote-tracking branch 'upstream/master' f9b14dc
@madmongo1 Merge remote-tracking branch 'upstream/master' 52b4c4a
@madmongo1 added cxx20 support 9e04392
```

Two of them is about adding a new package (half-ready effort), and four of them were a merge commits. This is below the par of any sane contribution guide.

Here:

- https://github.com/hunter-packages/socket.io-client-cpp/pull/2

You have used your write permissions and did merge even I have requested changes. That's absolutely unacceptable behavior. At this moment, there are 54 peoples and 232 teams in https://github.com/hunter-packages, and you're the only person I remember to remove from the organization. The fact that you're turning this issue into offtopic "I have a complaint" discussion just proving that what I've done was right.

**Comment by NukeBird** [comment]
I hope everything will go well because IMHO hunter is the best package manager for C++

**Comment by dan-42** [comment]
hey @ruslo 
first off all, I really like hunter and it would be very sad if the project stops.
So you got my support on patreon! 
I also promoted hunter on the meetingC++2018 in Berlin on a small lightningTalk(it was my first talk on a stage): https://www.youtube.com/watch?v=wrCObV3qlhM

On the other side, I can totally understand that it is a lot of work! And best would be if all the work can be shared between a maintainer-team and not just by you!

So I'm looking forward to your decision!

**Comment by ruslo** [comment]
> 10 patrons | $230 of $1,500 per month

I'm grateful for your help, but I hope it's clear for everyone that this number of supporters will give me neither motivations nor resources to continue. I've done a full refund for all patrons.

**Comment by ruslo** [comment]
> ... and you're the developer who feels he is interested in maintenance ...

Please send your pull requests and issues to https://github.com/cpp-pm/hunter

@rbsheth @bkotzz Good luck have fun! :)

**Comment by caseymcc** [comment]
Sorry to hear all this, I have been lost in haze of development lately so I did not see any of this till now (definitely would have supported, although it would not have made up for that short fall).

I just want to say thank you, your work has been greatly appreciated and I have always been thoroughly impressed with the work and your responses to questions/PRs/issues. Pretty much anything that you have done so far. Thanks again for all your hard work.
