### ISSUE TITLE
pkg-config targets are not created

### ISSUE THREAD

**Issue by tastytea** [ruslo/hunter#1925]
* I've read [Brief overview section](https://docs.hunter.sh/en/latest/overview.html) and do understand basic concepts. **Yes**
* I've read [F.A.Q. section](https://docs.hunter.sh/en/latest/faq.html) and there is no solution to my problem there. **Yes**
* I've read [Code of Conduct](https://github.com/ruslo/hunter/blob/master/.github/CODE_OF_CONDUCT.md), I promise to be polite and will do my best at being constructive. **Yes**
* I've read [Reporting bugs section](https://docs.hunter.sh/en/latest/contributing.html#reporting-bugs) carefully. **Yes**
* I've checked that all the `hunter_add_package`/`find_package` API used by me in the example is the same as in [documentation](https://docs.hunter.sh/en/latest/packages.html). **Not applicable**
* I'm using [latest](https://github.com/ruslo/hunter/releases) Hunter `URL`/`SHA1`. **Yes**

I'm trying to write a package for [libconfig](https://github.com/hyperrealm/libconfig/), but it doesn't seem to generate pkg-config targets. I get the error message `Target "boo_cpp" links to target "PkgConfig::libconfig++" but the target was not found.`.

Here is the commit: <https://github.com/tastytea/hunter/commit/8413187511fbd297144e782d266a7b66a5e37304>

There are 2 pkg-config files installed, `libconfig++` and `libconfig`. This is the resulting `libconfig++Config.cmake` (`libconfigConfig.cmake` is the same, but whithout `++`):

```cmake
# […]/Cellar/[…]/raw/lib/cmake/libconfig++/libconfig++Config.cmake
set(LIBCONFIG++_FOUND 1)
set(LIBCONFIG++_VERSION "1.7")
set(LIBCONFIG++_LIBRARIES "config++")
set(LIBCONFIG++_LIBRARY_DIRS "${exec_prefix}/lib")
set(LIBCONFIG++_LDFLAGS "")
set(LIBCONFIG++_INCLUDE_DIRS "${prefix}/include")
set(LIBCONFIG++_CFLAGS "")
)
```

This is the corresponding `libconfig++.pc`:

``` cfg
# […]/Cellar/[…]/raw/lib/pkgconfig/libconfig++.pc
prefix=__HUNTER_PACKAGE_INSTALL_PREFIX__
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
Name: libconfig++
Description: C++ Configuration File Library
Version: 1.7.2
URL: http://www.hyperrealm.com/main.php?s=libconfig
Requires:
Conflicts:
Libs: -L${libdir} -lconfig++
Libs.private:  
Cflags: -I${includedir}
```

* Travis build reproducing issue:
  - https://travis-ci.com/tastytea/hunter/builds/121464586

Here is the log until first error reported by Hunter, option `HUNTER_STATUS_DEBUG` is `ON`:
* [log.txt](https://github.com/ruslo/hunter/files/3453463/log.txt)

I've checked that the first error in logs **IS NOT** `external.build.failed`. **Yes**

* I'm building on Linux.
* I'm using system CMake
* CMake version: 3.14.3

* I'm using unmodified toolchain gcc from [Polly](https://github.com/ruslo/polly)

<hr/>
Edit: Added `libconfig++.pc`

**Comment by ruslo** [comment]
> There are 2 pkg-config files installed, libconfig++ and libconfig. This is the resulting libconfig++Config.cmake (libconfigConfig.cmake is the same, but whithout ++)

The file `libconfigConfig.cmake` created by the package itself, not by Hunter:
```
config.status: creating lib/libconfigConfig.cmake
config.status: creating lib/libconfig++Config.cmake
...
/usr/bin/install -c -m 644 libconfigConfig.cmake '/home/travis/build/tastytea/hunter/_testing/Hunter/_Base/c770725/239e635/c4d7b01/Build/libconfig/Install/lib/cmake/libconfig'
/bin/mkdir -p '/home/travis/build/tastytea/hunter/_testing/Hunter/_Base/c770725/239e635/c4d7b01/Build/libconfig/Install/lib/cmake/libconfig++'
/usr/bin/install -c -m 644 libconfig++Config.cmake '/home/travis/build/tastytea/hunter/_testing/Hunter/_Base/c770725/239e635/c4d7b01/Build/libconfig/Install/lib/cmake/libconfig++'
```

And as you can see, file `libconfigConfig.cmake` doesn't providing imported target as it should. A workaround is to patch the package. A solution is to send such patch upstream.

**Comment by tastytea** [comment]
A good motivator for finally learning a bit more CMake I guess. 🙂

Is there a way to disregard the supplied `*Config.cmake` and generate them from pkg-config in the meantime?

**Comment by ruslo** [comment]
> generate them from pkg-config in the meantime?

That's what Hunter do:
- https://github.com/ruslo/hunter/blob/v0.23.206/cmake/schemes/url_sha1_autotools.cmake.in#L74-L83

But the package overwrites this file on installation step.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/blob/v0.23.214/README.rst
