### ISSUE TITLE
feature: add android toolchain(s) to travis tests

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#193]
@ruslo: Any thoughts on adding one or more android toolchains to the travis tests in ${HUNTER_ROOT}/.travis.yml?  I think this would require bootstrapping with hunter to configure the android build environment first, so this could be quite time consuming, but probably worthwhile.  I could take an initial look if you think this should be done through travis.  (I recall you were considering some alternatives earlier.)
##

**Comment by ruslo** [comment]
> Any thoughts on adding one or more android toolchains to the travis tests

Yes, but I want to fix this one first: https://github.com/ruslo/hunter/issues/180

>  I think this would require bootstrapping with hunter to configure the android build environment first

Yes. I was thinking about managing it by Hunter too. First we need toolchains: https://github.com/ruslo/hunter/issues/150 then we need some special packages that can be downloaded before toolchain processed.

**Comment by headupinclouds** [comment]
FWIW, I did try adding the android setup 

```
    # install android ndk
    - wget http://dl.google.com/android/ndk/android-ndk-r10e-darwin-x86_64.bin
    - chmod +x android-ndk-r10e-darwin-x86_64.bin
    - ./android-ndk-r10e-darwin-x86_64.bin
    - export ANDROID_NDK_r10e="`pwd`/android-ndk-r10e"
    # -- end
    # verify android ndk
    - ls "${ANDROID_NDK_r10e}/README.txt"
    # -- end
```
And travis killed the job with a timeout:
```
Extracting  android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/src/iostream.cpp
Extracting  android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/test/input.output/iostreams.base/std.ios.manip/error.reporting/iostream_category.pass.cpp
Extracting  android-ndk-r10e/tests/device/test-gnustl-full/unit/iostream_header_test.cpp
Extracting  android-ndk-r10e/tests/device/test-stlport/unit/iostream_header_test.cpp
Extracting  android-ndk-r10e/tests/device/test-gnustl-full/unit/iostream_test.cpp
Extracting  android-ndk-r10e/tests/device/test-stlport/unit/iostream_test.cpp
Extracting  android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/test/input.output/iostream.format/input.streams/istream.formatted/istream_extractors/ios_base.pass.cpp
Extracting  android-ndk-r10e/sources/cxx-stl/llvm-libc++/libcxx/test/input.output/iostream.format/output.streams/ostream.formatted/ostream.inserters/ios_base.pass.cpp
Extracting  android-ndk-r10e/tests/device/test-gnustl-full/unit/i
No output has been received in the last %!f(time.Duration=3000000000000) minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

Travis is fairly new to me, so I'm not sure if the timeout can be configured or not.

**Comment by ruslo** [comment]
> Travis is fairly new to me, so I'm not sure if the timeout can be configured or not

As far as I know it can't be configured. Usually it indicates some problems with the script or virtual machine. Can you give me the link to the build?

**Comment by ruslo** [comment]
Android toolchains work fine as far as I know. Closing.
