### ISSUE TITLE
HUNTER_BUILD_SHARED_LIBS [$5]

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#21]
Support for choosing between shared/static type of libraries (see [BUILD_SHARED_LIBS](http://www.cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html)).
##

**Comment by sumedhghaisas** [comment]
I think the first thing we need to introduce to fix this issue is common hunter flags. Like every build system or even every project may have different flags to achieve the same thing(for eg. enabling shared libs). So user should be able to write hunter_config(<project> HUNTER_ARGS BUILD_SHARED=ON) rather than hunter_config(<project> CMAKE_ARGS BUILD_SHARED=ON). HUNTER_ARGS system should work for any project(it should give a warning if that flag does not apply for that project) and it should convert the global flag to project specific flag internally. This would involve storing a mapping of global flags to local flags for each project but will let us achieve consistent flag system in turn providing hunter more control over the build environment. It is trivial to resolve this issue when we have such a system implemented by simply setting this global flags.

**Comment by ruslo** [comment]
> Like every build system or even every project may have different flags to achieve the same thing(for eg. enabling shared libs)

This is work for scheme, see for example how Qt handles `HUNTER_CONFIGURATION_TYPES`:
* https://github.com/ruslo/hunter/blob/ffddec5892055f1d971e9ec3d1367f36e304ac5d/cmake/schemes/url_sha1_qt.cmake.in#L157

Schemes can be fixed one-by-one when needed.

**Comment by sumedhghaisas** [comment]
Ahh yes. Similar to HUNTER_CONFIGURATION_TYPES. Configuration types should be reserved for changing the build type. I think we should introduce another variable which should follow certain predefined variables. This way there can be consistency. If all the packages follow the same BUILD SHARED variable the global variable BUILD SHARED can be implemented easily. The other problem that remains is to pass these flags to subprojects.

**Comment by ruslo** [comment]
Not sure I follow, can you add an example?

From my point of view this is can be implemented like this:
* `HUNTER_BUILD_SHARED_LIBS` should be saved in toolchain-id calculation module since it's global flag that affects how end binaries will be built (like `HUNTER_CONFIGURATIN_TYPES`)
* if user set `BUILD_SHARED_LIBS` via `hunter_config` then we should use this one
* if user haven't set `BUILD_SHARED_LIBS` and `HUNTER_BUILD_SHARED_LIBS` is set, then use `HUNTER_BUILD_SHARED_LIBS`
* if none is set - use default (this is how it works now)
* for CMake-based projects this variable will be passed along with others `CMAKE_ARGS`, so there is no need to change anything
* for custom build schemes we should check the value of CMake `BUILD_SHARED_LIBS` and update confugure flags accordintly, like adding `--shared`/`--static`

**Comment by Knitschi** [comment]
I would like to have dynamic linkage for the qt package because of possible license trouble. Does this issue mean that this is currently not possible?

**Comment by ruslo** [comment]
> Does this issue mean that this is currently not possible?

@Knitschi No it doesn't. This issue about doing it globally for all packages. For now you can enable dynamic libraries for the specific package by `CMAKE_ARGS`:

```cmake
hunter_config(
    Qt
    VERSION ${HUNTER_Qt_VERSION}
    CMAKE_ARGS BUILD_SHARED_LIBS=ON
)
```

See:
* https://github.com/ruslo/hunter/blob/b65c889990ffbbd1c067bad8079414c91f1e4cbb/cmake/schemes/url_sha1_qt.cmake.in#L147
* https://github.com/ruslo/hunter/wiki/example.custom.config.id

**Comment by Knitschi** [comment]
I opened up an extra issue for my questions. #345

**Comment by ruslo** [comment]
I think this one is fixed by https://github.com/ruslo/hunter/pull/556. @caseymcc you can take the bounty :)

**Comment by caseymcc** [comment]
Keep the bounty use it on another item.

**Comment by ruslo** [comment]
@caseymcc I just wondering how it works :)

**Comment by caseymcc** [comment]
Never used it myself, but signed up and posted the pull as complete of the issue and it says the following.

> You have started working on this issue.  Edit
> You will be able to claim this bounty as soon as the original issue is marked as closed.

**Comment by ruslo** [comment]
> You will be able to claim this bounty as soon as the original issue is marked as closed

Okay, closing.
