### ISSUE TITLE
Add dbus

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#228]
See: https://github.com/ruslo/hunter/pull/227

**Comment by daminetreg** [comment]
I'm on it.

**Comment by ruslo** [comment]
@daminetreg I've created https://github.com/hunter-packages/dbus. This is kind of central organization of forked hunterized projects. `master` and other branches should be equal to the upstream, branch `hunter` is for patches. I've send you an invitation to the team so you should have access to push.

**Comment by ruslo** [comment]
> master and other branches should be equal to the upstream, branch hunter is for patches

releases should match upstream releases too, e.g. `v0.0.1` -> `v0.0.1-<suffix>-0`. I've used `hunter` as a `<suffix>` earlier, but since it looks long I'm okay with `p` too, like `v1.2.3-p5`.

**Comment by daminetreg** [comment]
I like the long name, it makes it clearer with `hunter` as suffix.

**Comment by daminetreg** [comment]
Thanks for creating a fork in hunter-packages and inviting me in the team :smile:

**Comment by ruslo** [comment]
@daminetreg Thanks!
