### ISSUE TITLE
Please add package for log4cplus library

### ISSUE THREAD

**Issue by piyushj** [ruslo/hunter#229]
Thanks for providing excellent collection of c++ packages.
Log4cplus is an extensible logging framework which would be very useful for majority of C++ development projects.

**Comment by ruslo** [comment]
@piyushj Is it this one: https://github.com/log4cplus/log4cplus ?

**Comment by piyushj** [comment]
Yes. You got the correct URL.

**Comment by ruslo** [comment]
@piyushj Added, see https://github.com/ruslo/hunter/wiki/pkg.log4cplus
