### ISSUE TITLE
Add Curl

### ISSUE THREAD

**Issue by jneidlinger** [ruslo/hunter#248]
It would be great to have libcurl support in Hunter!

https://github.com/bagder/curl

I love everything Hunter is trying to accomplish, thanks for all the hard work!

**Comment by ruslo** [comment]
@jneidlinger What platform are you interested in? The last time I've tried to build Curl universal iOS library I've hit some troubles. Mainly because it generates different headers for different architectures. With this exception it should "just work" since it has a CMake build. Can you try: https://github.com/ruslo/hunter/wiki/usr.adding.new.package ?

**Comment by jneidlinger** [comment]
Well, in a perfect world, Win/Lin/OSX + Android/IOS/WinRT

I've only ever built seperate libcurl iOS architectures and lipo'd them myself. Other's go the route of using a different build system, for example:

https://github.com/biasedbit/curl-ios-build-scripts

will build curl as a universal library for you

**Comment by ruslo** [comment]
> The last time I've tried to build Curl universal iOS library I've hit some troubles. Mainly because it generates different headers for different architectures.

Here is the place to workaround Curl header issue that I was talking about:
https://github.com/gcesarmza/curl-android-ios/blob/503d7ef85a9650503a0620993c066576509f5d7e/curl-compile-scripts/build_iOS.sh#L89

**Comment by ruslo** [comment]
> for example:
https://github.com/biasedbit/curl-ios-build-scripts
will build curl as a universal library for you

this script doesn't handle header issue, here is a bug: https://github.com/biasedbit/curl-ios-build-scripts/issues/24

Quote:
```
This is because curlbuild.h differs for the 32 bit and 64 bit versions,
but the build script assumes that they are the same, and uses just
the 32 bit version
```

**Comment by jneidlinger** [comment]
Good find

**Comment by ruslo** [comment]
> Well, in a perfect world, Win/Lin/OSX + Android/IOS/WinRT

I've never used WinRT, if it's supported by CMake should work too though. The rest platforms should work fine.

**Comment by ruslo** [comment]
Added by #511. Not all toolchains are working, see testing branches for available list:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.914
* https://travis-ci.org/ingenue/hunter/builds/157820991
