### ISSUE TITLE
Boost.filesystem analyzer

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#25]
Clang analyzer failed (Linux, Mac):

```
libs/filesystem/src/unique_path.cpp:131:7: warning: Assigned value is garbage or undefined
      int c = ran[nibbles_used/2];
      ^~~~~   ~~~~~~~~~~~~~~~~~~~
1 warning generated.
```
- report
- patch
- check new version
- update jenkins.py
##

**Comment by ruslo** [comment]
Not a Hunter issue, closing.

**Comment by isaachier** [comment]
This seems to have been addressed in the most recent source code: https://github.com/boostorg/filesystem/blob/develop/src/unique_path.cpp#L135.

**Comment by ruslo** [comment]
@isaachier Feel free to open pull request with enabling this toolchain in testing after fix will be released.
