### ISSUE TITLE
Xcode 7.0 Qt 5.5.0 build fails

### ISSUE THREAD

**Issue by jneidlinger** [ruslo/hunter#250]
The QT5 package notes this pitfall:

"Default version of Xcode should not be set to 7.0 for Qt 5.5.0. See bug [47383](https://bugreports.qt.io/browse/QTBUG-47383)"

I'm trying to build the examples at https://github.com/forexample/qt-ios-examples
and hitting the exact same error

```
lalr.cpp:241:1: error: declaration of anonymous struct must be a definition
struct _Nullable: public std::unary_function<Name, bool>
^
lalr.cpp:241:56: error: expected unqualified-id
struct _Nullable: public std::unary_function<Name, bool>
                                                       ^
lalr.cpp:303:98: error: expected expression
          NameList::iterator nn = std::find_if (rule->rhs.begin (), rule->rhs.end (), std::not1 (_Nullable (this)));
                                                                                                 ^
lalr.cpp:638:107: error: expected expression
                  NameList::iterator first_not_nullable = std::find_if (dot, rule->rhs.end (), std::not1 (_Nullable (this)));
```

Is there a current workaround? I noticed some homebrew fixes here https://github.com/Homebrew/homebrew/commit/7d6658232bd2743a957219c480a3d137a084d851

**Comment by jneidlinger** [comment]
Latest Hunter release works around the issue. Closing.

**Comment by ruslo** [comment]
> Latest Hunter release works around the issue

Strange... There was some changes in Qt build instructions but no workaround for this bug :)

Personally I'm using next set of environment: `xcode-select` points to the 6.4 version, toolchain to `ios-9-0` (Xcode 7.0 default SDK). You can take a look for the hints: https://github.com/ruslo/hunter/issues/238

> I noticed some homebrew fixes here Homebrew/homebrew@7d66582

This might be helpful (also there is a patch in bug itself). Problem with Qt is that the release archive is not taken from the git repository exactly. Archive is the result of fusing several submodules. It makes usual fork-upstream => release-hunter move tricky. Quite the same happens to Boost. So I've decided just to commit raw release to new git repository (e.g. https://github.com/hunter-packages/boost/tree/boost-1.56.0) and apply patches there (e.g. https://github.com/hunter-packages/boost/commit/7900bfe00ebc6b00d6e95b02c0646578abda007d). If you're interested I can create Qt repository for you so we can do the same.

**Comment by jneidlinger** [comment]
>Latest Hunter release works around the issue
Sorry, I removed that comment, it still errors with the same build issue - just later on

I'll try running xcode 6.4 side by side for now - would really like to be using 7 though.

A new git repo for applying QT patches might be useful so Hunter can move faster then upstream fixes. :)

**Comment by jneidlinger** [comment]
Also while we are on the note of QT - does Hunter support pointing to a local pre-built version of QT to import instead of building from source?

This would
- Remove the time taken (a long time) to build all architectures from source
- Use modified versions of QT

**Comment by ruslo** [comment]
> A new git repo for applying QT patches might be useful so Hunter can move faster then upstream fixes. :)

See: https://github.com/hunter-packages/Qt
I'm in process of creating 5.5.0 branch. It may take some time since I need to commit huge number of files. I will let you know when it's done.

**Comment by ruslo** [comment]
> Also while we are on the note of QT - does Hunter support pointing to a local pre-built version of QT to import instead of building from source?

No. The main issue with such approach is the dependencies. Though for now Qt dependencies doesn't resolved 100% correctly but in general this is a huge problem :)

> Maybe you noted how to do such a thing with packages, but I didn't see it.

Solution to this problem is to share a `Cache` directory: https://github.com/ruslo/hunter/issues/75

The main idea is that `Cache` directory (see `$HUNTER_ROOT/_Base/Cache`) is a kind of relocatable folder with packed archives and meta-data about package toolchain/config options/dependencies/... which you can copy back and forth.

> This would...

Well benefits are obvious :) Also it will help to use Hunter with a lot of dependencies on Travis (Jenkins should works fine already).

**Comment by jneidlinger** [comment]
>See: https://github.com/hunter-packages/Qt

Awesome - Thank you!

>Solution to this problem is to share a Cache directory: #75

Yep, that sounds like a good approach.

**Comment by ruslo** [comment]
> I will let you know when it's done

Branch `hunter-5.5.0` created: https://github.com/hunter-packages/Qt/tree/hunter-5.5.0

@jneidlinger Feel free to apply patches to this branch if you want :) You can apply them as a pull request if you want me to review it or do the push to `hunter-5.5.0` and release (you should have enough permissions to do it).

**Comment by jneidlinger** [comment]
I put up a PR https://github.com/hunter-packages/Qt/pull/1

**Comment by ruslo** [comment]
> I put up a PR hunter-packages/Qt#1

@jneidlinger Thanks. Patched version released: https://github.com/hunter-packages/Qt/releases/tag/v5.5.0-p0

**Comment by ruslo** [comment]
@jneidlinger Please test it with Hunter and let me know if it fix the Xcode 7.0 errors, thanks.

**Comment by jneidlinger** [comment]
Looks like its going to build... but 3 hours later and it's still building :/

Is there a way we can enable passing -J flags to make to let us parallel-ize when building dependencies?

**Comment by ruslo** [comment]
> Is there a way we can enable passing -J flags to Make to let us parallel-ize when building dependencies?

@jneidlinger Yes, see wiki: https://github.com/ruslo/hunter/wiki/usr.variables#hunter_jobs_number

I guess maximum number is already set for you.

For Qt it applied here: https://github.com/ruslo/hunter/blob/d1576715578001f33d3a22fa48497dcfd436fc97/cmake/schemes/url_sha1_qt.cmake.in#L210

> Looks like its going to build... but 3 hours later and it's still building :/

Note that by default iOS will build 5 architectures (armv7, armv7s, arm64, i386, x86_64) and two variants (Debug/Release). So it 10 times slower than for example using `ios-8-4-armv7` and set all 3rd parties to Release by HUNTER_CONFIGURATION_TYPES=Release (see [docs](https://github.com/ruslo/hunter/wiki/usr.variables#hunter_configuration_types)). Note that default `HUNTER_CONFIGURATION_TYPES=Debug;Release` goes to one `toolchain-id` and custom `HUNTER_CONFIGURATION_TYPES=Release` goes to another `toolchain-id`.

**Comment by jneidlinger** [comment]
I don't see build_opts applied here: 

https://github.com/ruslo/hunter/blob/d1576715578001f33d3a22fa48497dcfd436fc97/scripts/qt-build.cmake.in

or am I mistaken?

**Comment by ruslo** [comment]
@jneidlinger I've take a closer look and it's seems that actually it's a bug introduced by my commit: https://github.com/ruslo/hunter/commit/6963bc7ce079aba5c58cf3ea6c55a2575baecc1b

Thanks for observation, here is the fix: https://github.com/ruslo/hunter/commit/7fd2f3304ce9ce788fa33a1dfd093a1247bfa4fd
New version: https://github.com/ruslo/hunter/releases/tag/v0.12.18

Sorry :)

**Comment by jneidlinger** [comment]
Thanks - it built much faster now!

Qt builds - but it looks like there might be a problem with the Universal Library - building the ios QT examples for a device (ARM) work fine, but when building for the simulator

Calling: 
>Jordans-MacBook-Pro:qt-ios-examples-master jneidlinger$ cmake -H. -B_builds/ios-9-0 -GXcode -DCMAKE_TOOLCHAIN_FILE="${POLLY_ROOT}/ios-9-0.cmake" -DHUNTER_STATUS_DEBUG=ON
>

Finishes, I open the xcode proj to build for the simulator, yields:

>ld: warning: ignoring file /Users/jneidlinger/.hunter/_Base/89b148a/30ca105/2d207c4/Install/lib/libQt5Widgets_debug.a, missing required architecture x86_64 in file /Users/jneidlinger/.hunter/_Base/89b148a/30ca105/2d207c4/Install/lib/libQt5Widgets_debug.a (3 slices)
Undefined symbols for architecture x86_64:
  "qRegisterResourceData(int, unsigned char const*, unsigned char const*, unsigned char const*)", referenced from:
      qInitResources_main() in qrc_main.o
    ...
    ...
    ...
>

I checked the built libs:

>Jordans-MacBook-Pro:lib jneidlinger$ lipo -info libQt5Widgets_debug.a
Architectures in the fat file: libQt5Widgets_debug.a are: armv7 armv7s arm64
>

and indeed, they do not contain x86_64...

**Comment by ruslo** [comment]
> but it looks like there might be a problem with the universal lib creation

This is a known Qt defect: https://bugreports.qt.io/browse/QTBUG-47314 (see [wiki](https://github.com/ruslo/hunter/wiki/pkg.qt#notes)).

It's possible to make a workaround by adding extra script to install stage which will combine all `libQt5*_simulator.a` (i386, x86_64) and `libQt5*.a` (armv7, armv7s, arm64) into `libQt5*.a` (i386, x86_64, armv7, armv7s, arm64).

**Comment by jneidlinger** [comment]
>
It's possible to make a workaround by adding extra script to install stage which will combine all libQt5*_simulator.a (i386, x86_64) and libQt5*.a (armv7, armv7s, arm64) into libQt5*.a (i386, x86_64, armv7, armv7s, arm64).
>

I think that would be great. In the mean time - the patched QT 5.5 is working fine (I tested in on a device with the iOS QT examples)

**Comment by ruslo** [comment]
> I think that would be great

See https://github.com/ruslo/hunter/issues/252.

I've leaved an implementation notes so I if you can feel free to write this script.

**Comment by ruslo** [comment]
I've repacked sources using `7z` archiver. It saves us about 50% of space :)

Update: https://github.com/ruslo/hunter/commit/4ca43fd68925cc6ab98b3ee37c638dfcd0ea1e35
Version: https://github.com/ruslo/hunter/releases/tag/v0.12.19

@jneidlinger Fixed, closing this one
