### ISSUE TITLE
Add 'thread-pool-cpp' package

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#251]
This looks like a nice lightweight performant thread pool.

https://github.com/inkooboo/thread-pool-cpp

I can add this one.

**Comment by headupinclouds** [comment]
hunterized: https://github.com/headupinclouds/thread-pool-cpp/tree/hunter

@ruslo: Can you create hunter-packages/thread-pool-cpp and add me as a collaborator?

**Comment by ruslo** [comment]
> @ruslo: Can you create hunter-packages/thread-pool-cpp and add me as a collaborator?

done: https://github.com/hunter-packages/thread-pool-cpp

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.684
* https://travis-ci.org/ingenue/hunter/builds/145972186

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.687
* https://travis-ci.org/ingenue/hunter/builds/146089000

**Comment by ruslo** [comment]
> Uploading

Done. Package in branch `develop`. New wiki page: https://github.com/ruslo/hunter/wiki/pkg.thread-pool-cpp.
