### ISSUE TITLE
Qt iOS workaround for simulator libraries

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#252]
Make a workaround for bug: https://bugreports.qt.io/browse/QTBUG-47314

Idea:
* find all libraries with name `libQt5*_simulator.*` by `file(GLOB ...)`
* for each such library create name for corresponding device library `libQt5*.*`
* create device + simulator library by `lipo -create dev sim -output dev`
* remove simulator libraries

Code should be placed into `qt-install.cmake` script right after `configure_file` commands:
  https://github.com/ruslo/hunter/blob/7fd2f3304ce9ce788fa33a1dfd093a1247bfa4fd/scripts/qt-install.cmake.in#L103

**Comment by ruslo** [comment]
Fixed: [v0.12.21](https://github.com/ruslo/hunter/releases/tag/v0.12.21)

@jneidlinger I've tried it on [qt-widgets](https://github.com/ruslo/hunter/blob/master/examples/qt-widgets/CMakeLists.txt) example. Example is quite dumb and doesn't show anything but it works on device and simulator, hence libraries fused correctly.

**Comment by jneidlinger** [comment]
Awesome, nice work! Thank you!
