### ISSUE TITLE
find_package(Qt5Declarative REQUIRED) fails

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#253]
This issue is touched on in #116, but I'm not able to generate qtdeclarative with the latest hunter using the following cmake commands.

The following dies for me (android and libcxx toolchains tested) with the latest hunter on the `find_package(Qt5Declarative)` command.

This chunk of code:
```
if(BUILD_QT)
  hunter_add_package(Qt COMPONENTS qtbase qtmultimedia qtdeclarative)
  find_package(Qt5Widgets REQUIRED)
  find_package(Qt5Multimedia REQUIRED)
  find_package(Qt5Declarative REQUIRED)
endif()
```

results in:
```
CMake Error at CMakeLists.txt:60 (find_package):
  By not providing "FindQt5Declarative.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5Declarative", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5Declarative"
  with any of the following names:

    Qt5DeclarativeConfig.cmake
    qt5declarative-config.cmake

  Add the installation prefix of "Qt5Declarative" to CMAKE_PREFIX_PATH or set
  "Qt5Declarative_DIR" to a directory containing one of the above files.  If
  "Qt5Declarative" provides a separate development package or SDK, be sure it
  has been installed.
```

@pretyman Were you able to pull in the qt5declarative lib in any project?  I see you mentioned something similar in #116.

On a fresh build this results in:

```
Qt configure command: ./configure;-confirm-license;-nomake;examples;-nomake;tests;-opensource;-no-framework;-no-dbus;-verbose;-static;-prefix;/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/07d21d3/18855aa/Build/Qt/__qtbase/Install;-release;-skip;qt3d;-skip;qtactiveqt;-skip;qtandroidextras;-skip;qtcanvas3d;-skip;qtconnectivity;-skip;qtdeclarative;-skip;qtdoc;-skip;qtenginio;-skip;qtgraphicaleffects;-skip;qtimageformats;-skip;qtlocation;-skip;qtmacextras;-skip;qtmultimedia;-skip;qtquick1;-skip;qtquickcontrols;-skip;qtscript;-skip;qtsensors;-skip;qtserialport;-skip;qtsvg;-skip;qttools;-skip;qttranslations;-skip;qtwayland;-skip;qtwebchannel;-skip;qtwebengine;-skip;qtwebkit;-skip;qtwebkit-examples;-skip;qtwebsockets;-skip;qtwinextras;-skip;qtx11extras;-skip;qtxmlpatterns
+ cd qtbase
+ /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/07d21d3/18855aa/QtBuild/qtbase/configure -top-level -confirm-license -nomake examples -nomake tests -opensource -no-framework -no-dbus -verbose -static -prefix /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/07d21d3/18855aa/Build/Qt/__qtbase/Install -release -skip qt3d -skip qtactiveqt -skip qtandroidextras -skip qtcanvas3d -skip qtconnectivity -skip qtdeclarative -skip qtdoc -skip qtenginio -skip qtgraphicaleffects -skip qtimageformats -skip qtlocation -skip qtmacextras -skip qtmultimedia -skip qtquick1 -skip qtquickcontrols -skip qtscript -skip qtsensors -skip qtserialport -skip qtsvg -skip qttools -skip qttranslations -skip qtwayland -skip qtwebchannel -skip qtwebengine -skip qtwebkit -skip qtwebkit-examples -skip qtwebsockets -skip qtwinextras -skip qtx11extras -skip qtxmlpatterns
```

**Comment by ruslo** [comment]
From https://github.com/ruslo/hunter/issues/254:
```cmake
hunter_add_package(Qt COMPONENTS qtdeclarative)
find_package(Qt5Declarative REQUIRED)
```
doesn't work. Looks like current instructions don't install `Qt5DeclarativeConfig.cmake`. I can find this file in standard Qt directory (binaries from official site). I guess the reason is that we are skipping some component which must not be skipped for `qtdeclarative`.

**Comment by headupinclouds** [comment]
Apparently quite a few dependencies.  I'll see what I can find.
https://wiki.qt.io/Qt_Library_Cross_Dependencies
`QtDeclarative => QtCore, QtGui, QtNetwork, QtOpenGL, QtScript, QtSql, QtSvg, QtXmlPatterns`

**Comment by ruslo** [comment]
@headupinclouds Very nice find!

**Comment by ruslo** [comment]
I've found the place where deps list constructed: https://github.com/hunter-packages/Qt/blob/7c123afa113f779a9f1305818e1079ae7d6c8c72/qt.pro#L60

format is `(module name, mandatory deps, optional deps)`. This clarify next things:

##### - every module should not skip `qtbase`

This one states explicitly:
```
# only qtbase is required to exist. The others may not - but it is the
# users responsibility to ensure that all needed dependencies exist, or
# it may not build.
```
and if you build dep tree it is so in fact.

##### - skipping optional requirements is not an error

That's why `qtmultimedia` builds without errors but doesn't install some `qtdeclarative` files:
```
addModule(qtmultimedia, qtbase, qtdeclarative)
```
it means `qtmultimedia` depends on `qtbase` and has an optional `qtdeclarative` dependency.
If you build list of components which depends on `qtdeclarative` (optionally) this is quite the same that @pretyman has.

Compare [this list](https://github.com/ruslo/hunter/issues/116#issuecomment-126981978):
```
qt3d
qtcanvas3d
qtconnectivity
qtenginio
qtgraphicaleffects
qtlocation
qtmultimedia
qtsensors
qtwebchannel
qtwebkit
qtwebsockets
```

and this one build from `qt.pro`:
```
qt3d
qtcanvas3d
qtconnectivity
qtdoc
qtdocgallery
qtenginio
qtfeedback
qtgraphicaleffects
qtlocation
qtmultimedia
qtpim
qtquick1
qtquickcontrols
qtscript
qtsensors
qtsystems
qttools
qttranslations
qtwayland
qtwebchannel
qtwebengine
qtwebkit
qtwebkit-examples
qtwebsockets
qtwinextras
```

@headupinclouds But unfortunately it doesn't answer why we have no `Qt5Declarative` file installed. `qtdeclarative` component has only one mandatory requirement - `qtbase`, and this requirement is satisfied.

**Comment by ruslo** [comment]
I've found some clues about `Qt5Declarative` is part of the `qtquick1` component:
* https://packages.debian.org/sid/amd64/qtquick1-5-dev/filelist
* https://www.archlinux.org/packages/extra/i686/qt5-quick1/files
* https://github.com/hunter-packages/Qt/blob/7c123afa113f779a9f1305818e1079ae7d6c8c72/qttools/src/windeployqt/main.cpp#L118

but now I can't build it because of compiler errors

**Comment by pretyman** [comment]
As written in https://github.com/ruslo/hunter/issues/116#issuecomment-147138369 :

For the declarative module use find_package(Qt5Qml REQUIRED), however there are some dependencies missing for linking. Unfortunately my machine broke nearly 2 months ago and I couldn't generate Hunter patches to correct the dependencies. I had problems linking in MacOS, iOS and in Linux with the declarative module.

If you get around to working out the dependencies, you can use the Qt5Widgets_HunterPlugin.cmake tecnique that @ruslo used.

Be warned that he put depencies of QtCore together with the Qt5Widgets together into his plug-in, which is not a problem if you are using Qt5Widgets. Since I was not using Qt5Widgets, only declarative, the linking dependencies of Qt5Core didn't come.

**Comment by pretyman** [comment]
@headupinclouds are you trying to use QtQuick2 or QtQuick1 (from Qt 4.8.x) ?

**Comment by ruslo** [comment]
@pretyman @headupinclouds Little bit about terminology. `qtbase`, `qtquick1`, `qtdeclarative` are components of the package from the Hunter point of view:

```
hunter_add_package(Qt COMPONENTS qtbase)
hunter_add_package(Qt COMPONENTS qtquick1)
hunter_add_package(Qt COMPONENTS qtdeclarative)
```

Each component install CMake-config module, like `Qt5ConcurrentConfig.cmake`, `Qt5WidgetsConfig.cmake`:
```
find_package(Qt5Concurrent REQUIRED)
find_package(Qt5Widgets REQUIRED)
```

@headupinclouds I can't say can it be helpful for your end-goal but I see next issue need to be solved:
`Qt5DeclarativeConfig.cmake` CMake-config module **should** be installed by Qt (I see such file in official release + see the links above). What component exactly install such module is a mistery for me for now :) `qtdeclarative` component install next CMake-config modules in my tests:
```
hunter_add_package(Qt COMPONENT qtdeclarative)
find_package(Qt5Qml REQUIRED)
find_package(Qt5Quick REQUIRED)
find_package(Qt5QuickTest REQUIRED)
find_package(Qt5QuickWidgets REQUIRED)
```

(@pretyman I see Qt5Quick, probably QtQuick2 is 4.8?)

> however there are some dependencies missing for linking

@pretyman I've just discover recently that scheme are ignoring optional components and it was a reason of previous linking bugs. I've changed this logic, testing it now.

> Since I was not using Qt5Widgets, only declarative, the linking dependencies of Qt5Core didn't come

They came from one template file so it can be fine tuned to match requirements exactly I think.

**Comment by pretyman** [comment]
Sorry for not being clear. Let me try to be more explicit:

The `qtdeclarative` directory module in the Qt5 directory structure, which happens to be the hunter component of the same name, refers to the Qt5Qml CMake package used in `find_package(Qt5Qml REQUIRED)`. This deals with the Qml Parsing and registering C++ types into the Qml engine.

The `qtquick` directory module in the Qt5 directory structure, which also the hunter component of the same name, refers to the Qt5Quick CMake package used in `find_package(Qt5Quick REQUIRED)`. This deals with the QtQuick2 scene graph and C++ classes that can be extended create visual items in QtQuick2 from C++.

The `qtquick1` directory module in the Qt5 directory structure, and also hunter component, deals with the QtQuick from Qt 4.8.x, If memory does not fail me, it used to be the *also* called the `declarative` module in the old days, term used interchangeably with QtQuick. I have never used this module with CMake.

@headupinclouds so, what are you looking for? :-)

@ruslo thanks for figuring out the problem with the linking, I should come back to resume my hunter activities in a couple of months

**Comment by headupinclouds** [comment]
Thanks for all of the input.  

> @headupinclouds so, what are you looking for? :-)

Initially I'm just trying to resolve dependencies in a sample camera application (https://github.com/microsoft-mobile/qt-camera-demo/tree/master/doc) with Hunter.  The initial error was related to missing `<QDeclarativeItem>` includes.  I'm new to Qt, so I may be missing something obvious.  The .pro file from that project uses the following:

```
QT += declarative
CONFIG += mobility
MOBILITY += multimedia
```

And I believe the Mobility stuff is now just part of QT 5+.  Here is the compiler error:

```
fatal error: 'QDeclarativeItem' file not found
#include <QDeclarativeItem>
```
With a top level QT configuration (updated after the above) like this (satisfying some other QT app dependencies as well):
```
  hunter_add_package(Qt COMPONENTS qtbase qtdeclarative qtmultimedia qtscript qtsvg qtxmlpatterns)
  find_package(Qt5Widgets REQUIRED)
  find_package(Qt5Multimedia REQUIRED)
  find_package(Qt5MultimediaWidgets REQUIRED)
  find_package(Qt5OpenGL REQUIRED)
  find_package(Qt5Qml REQUIRED)
  find_package(Qt5Quick REQUIRED)
  #find_package(Qt5Declarative REQUIRED)
```
And in the app CMakeLists.txt:
```
target_link_libraries(qt-camera-demo
  Qt5::Widgets
  Qt5::Multimedia
  Qt5::Qml
  Qt5::Quick
)
```
I will likely need to learn more about QT to get this sample working.

**Comment by pretyman** [comment]
@headupinclouds `QDeclarative` class is from the 4.8.x declarative module AKA QtQuick1, so you will have to add `qtquick1` to your `hunter_add_package(Qt COMPONENTS ... qtquick1 ...)`.

Do you really have to use this code? There are more update examples using the Qt5 Multimedia module that uses the camera: http://doc.qt.io/qt-5/multimedia-examples.html

**Comment by headupinclouds** [comment]
> Do you really have to use this code? 

Probably not.  The stock camera app (from your link) builds and runs, but is not able to find the camera on my OS X machine as presently configured

https://github.com/headupinclouds/gatherer/tree/develop/src/app/qt-camera
```
defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.camera"
```

More info here: 

https://github.com/headupinclouds/gatherer/issues/42

It does seem to build and execute, so this may be a QT specific (i.e., non-hunter) issue that I need to sort through.

**Comment by pretyman** [comment]
Ok, let me explain you what is happening. 

The examples on the site expects you to use Qt with dynamically linked libraries. Because when loading the dynamic libraries, they run a piece of code that does some registration according to the plugin. 

In the case of the multimedia plugin, it registers the camera service.

When using Hunter, you are using static linking, if you have not changed the default, so you have to do the plugin registration yourself.

Below is the plugin registration for the Camera and Audio for MacOSX (maybe iOS too, I frankly don't remember, and can't test it because I am working with a borrowed laptop which runs Linux)

Put this before the `main`:
```c++
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QQmlEngine>
#include <QAudio>
#include <QQmlExtensionPlugin>
#include <QtQml/qqml.h>
#ifdef STATIC_BUILD
#include <QtPlugin>
Q_IMPORT_PLUGIN(QCocoaIntegrationPlugin)
Q_IMPORT_PLUGIN(QtQuick2Plugin)
Q_IMPORT_PLUGIN(QtQuick2WindowPlugin)
Q_IMPORT_PLUGIN(QMultimediaDeclarativeModule)

Q_IMPORT_PLUGIN(QtQuickLayoutsPlugin)

Q_IMPORT_PLUGIN(AVFServicePlugin) // Camera
Q_IMPORT_PLUGIN(AVFMediaPlayerServicePlugin)
Q_IMPORT_PLUGIN(AudioCaptureServicePlugin) // Record
Q_IMPORT_PLUGIN(CoreAudioPlugin)
#endif // STATIC_BUILD
``` 

then after you `Q*Application`:

```c++
int main(int argc, char *argv[])
{
                QGuiApplication app(argc, argv);
#ifdef STATIC_BUILD
                // registration because of https://bugreports.qt.io/browse/QTBUG-38661
                qRegisterMetaType<QAudio::Error>();
                qRegisterMetaType<QAudio::State>();
                qRegisterMetaType<QAudio::Mode>();

                qobject_cast<QQmlExtensionPlugin*>(qt_static_plugin_QtQuick2Plugin().instance())->registerTypes("QtQuick");
                qobject_cast<QQmlExtensionPlugin*>(qt_static_plugin_QMultimediaDeclarativeModule().instance())->registerTypes("QtMultimedia");
                qobject_cast<QQmlExtensionPlugin*>(qt_static_plugin_QtQuick2WindowPlugin().instance())->registerTypes("QtQuick.Window");
                qobject_cast<QQmlExtensionPlugin*>(qt_static_plugin_QtQuickLayoutsPlugin().instance())->registerTypes("QtQuick.Layouts");

#endif // STATIC_BUILD
....
```
I should organize this and we should really make this part of Hunter, it is just that I don't have time to do it now.

**Comment by headupinclouds** [comment]
@pretyman: Thank you for the tip, that probably saved me a couple weekends of QT google coding (at least).  I'll try it.

**Comment by pretyman** [comment]
link these, it is also taking QtQuickLayout into account, but should be no harm to link now to get your app working

(sorry for for bad formatting, pretty busy atm)

```cmake
set(qt_qml_libs
  "-L${qt_lib_dir}/../plugins/qmltooling"
  qmldbg_tcp
  "-L${qt_lib_dir}/../qml/QtQuick.2/"
  qtquick2plugin
  "-L${qt_lib_dir}/../qml/QtQuick/Window.2/"
  windowplugin
  # Multimedia
  "-L${qt_lib_dir}/../qml/QtMultimedia"
  Qt5MultimediaQuick_p
  declarative_multimedia
)

set(qt_multimedia_libs
    "-L${qt_lib_dir}/../plugins/mediaservice/"
    qavfcamera
                qavfmediaplayer
                qtmedia_audioengine
                "-L${qt_lib_dir}/../plugins/audio/"
                qtaudio_coreaudio
                "-framework AudioUnit"
                "-framework AudioToolbox"
                "-framework CoreAudio"
                "-framework AVFoundation"
                "-framework CoreMedia"
                "-framework CoreVideo"
                "-framework QuartzCore"
)

set(qt_qcocoa_libs
                "-framework IOKit"
)

set(qt_quick_layout_libs
                "-L${qt_lib_dir}/../qml/QtQuick/Layouts"
                qquicklayoutsplugin
)
```

**Comment by headupinclouds** [comment]
@pretyman: Had to resolve a few missing symbols, but... it works! 

https://github.com/headupinclouds/gatherer/blob/develop/src/app/qt-camera/CMakeLists.txt#L55

Thank you!

I'll be looking into repeating this for Linux, Android and iOS.

**Comment by ruslo** [comment]
Testing OSX now, looks like these lines not mandatory:
```cpp
qobject_cast<QQmlExtensionPlugin*>(qt_static_plugin_QtQuick2Plugin().instance())->registerTypes("QtQuick");
qobject_cast<QQmlExtensionPlugin*>(qt_static_plugin_QMultimediaDeclarativeModule().instance())->registerTypes("QtMultimedia");
qobject_cast<QQmlExtensionPlugin*>(qt_static_plugin_QtQuick2WindowPlugin().instance())->registerTypes("QtQuick.Window");
```

At least example works fine.

**Comment by pretyman** [comment]
These lines were there because I was using these QML modules. If they don't exist and one tries to use them, it results in a runtime error that the module was not found. Unfortunately their registration is manual with static linking.

**Comment by ruslo** [comment]
Fixed. `Qt5Declarative` module installed by `qtquick1` component:

```cmake
hunter_add_package(qtquick1)
find_package(Qt5Declarative REQUIRED)
```

See [wiki](https://github.com/ruslo/hunter/wiki/pkg.qt#usage).
