### ISSUE TITLE
Can I specify hunter packages local to a project?

### ISSUE THREAD

**Issue by Dravorek** [ruslo/hunter#262]
I'm having a little trouble figuring out how everything relates to each other.

So my issue is that I have a header-only library that I wrote a quick hacky "CMakeLists.txt" for and a "hunter.cmake" to find that library with hunter.

But I can't figure out where I should place the "hunter.cmake" so that hunter doesn't complain.

I would prefer to have it somewhere in a sub-folder of ${cmake_current_list_dir}, but putting it in ${CMAKE_CURRENT_LIST_DIR}/cmake/Hunter/config.cmake doesn't do a thing.

putting it in ${HUNTER_ROOT}/cmake/projects/prjname/hunter.cmake also doesn't work.

The only thing that seems to work is ${HUNTER_ROOT}\_Base\Download\Hunter\0.12.12\4c1ea8c\Unpacked\cmake\projects\prjname\hunter.cmake
plus adding the version to 
${HUNTER_ROOT}\_Base\Download\Hunter\0.12.12\4c1ea8c\Unpacked\cmake\configs\default.cmake

But forking Hunter just to add a package seems a little extreme to me.

**Comment by daminetreg** [comment]
I think this relates to #56 and for the moment you have to fork it I believe. 

I do this in a private project with hunter as submodule and use the following in my CMakeLists to override the hunter in use : 

```cmake
include("cmake/HunterGate.cmake")
set(HUNTER_ROOT ${CMAKE_CURRENT_LIST_DIR}/hunter) # Override hunter package collection with patched one avail as submodule
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.12.13.tar.gz"
    SHA1 "3c0b858f586675fd1c4e3042015e328ec41b6a01"
)
```

**Comment by ruslo** [comment]
> But I can't figure out where I should place the "hunter.cmake" so that hunter doesn't complain

@Dravorek for now you should clone Hunter repository, see
* [adding new package](https://github.com/ruslo/hunter/wiki/usr.adding.new.package)
* [testing](https://github.com/ruslo/hunter/wiki/dev.hunter.root)


> I think this relates to

@daminetreg Yep, quite correct. In future this can be improved by issue #56 fix.

**Comment by Dravorek** [comment]
Alright, I guess that's all the options I have for now. Thanks for the quick reply.
