### ISSUE TITLE
JPEG 

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#266]
Official: http://www.ijg.org 
CMake candidate: https://github.com/mmarat/jpeg8d-cmake

Note: OpenCV maintains this in a 3rdparty folder, so the changes previously applied for PNG and TIFF will need to be applied for JPEG.

See: #267

**Comment by ruslo** [comment]
Added: https://github.com/ruslo/hunter/wiki/pkg.jpeg
Version with updates OpenCV: https://github.com/ruslo/hunter/releases/tag/v0.14.5
