### ISSUE TITLE
JASPER

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#267]
Official: http://www.ece.uvic.ca/~frodo/jasper/
CMake candidate: https://github.com/vmarkovtsev/jasper

Note: OpenCV maintains this in a 3rdparty folder, so the changes previously applied for PNG and TIFF will need to be applied for JASPER.

See: #266
##

**Comment by ruslo** [comment]
OpenCV link:
* https://github.com/hunter-packages/opencv/tree/ab2d4be0ac4ef08c18ed534202d7881b736bc356/3rdparty/libjasper

**Comment by ruslo** [comment]
Added: https://docs.hunter.sh/en/latest/packages/pkg/jasper.html
Released: https://github.com/ruslo/hunter/releases/tag/v0.20.25
