### ISSUE TITLE
rebuilding hunter dependencies (removing toolchain cache entries)

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#271]
Occasionally there is a need to rebuild Hunter dependencies.  Is there a clean way to do this for a single toolchain without wiping the entire Hunter cache?

I was trying something like this:

```
shasum _builds/ios-9-1-hid/_3rdParty/Hunter/config-id/config.cmake 
562326632d345681c9cb76deafbea373b4c642e3  _builds/ios-9-1-hid/_3rdParty/Hunter/config-id/config.cmake
```

And then 

```
rm -rf ${HUNTER_ROOT}/_Base/xxxxxxx/5623266
```

But during my project build, I noticed it retrieves a cache of the individual packages (compiled with the old build settings):

```
/Users/dhirvonen/devel/hunter/_Base/Cache/raw/2f3fa2fd4a8ce3bae48297b730d638467323d8d5.tar.bz2
```

Is there a place where the hash of the package dependencies is stored, so that I can remove them programmatically in a shell script?

**Comment by headupinclouds** [comment]
Inspecting the logs a little more pointed me in the right direction.

I need to grab the toolchain ID

```
shasum _builds/ios-9-1-hid/_3rdParty/Hunter/toolchain/toolchain.info 
46a6b2646d686c68036fcc35f3e2492cb0680e18  _builds/ios-9-1-hid/_3rdParty/Hunter/toolchain/toolchain.info
```

And can use that to wipe the toolchain specific cache in:

```
rm -rf ${HUNTER_ROOT}/_Base/Cache/meta/46a6b26/
```

**Comment by ruslo** [comment]
> And can use that to wipe the toolchain specific cache in

This will remove all cache entries that built with `toolchain-id`. You can find meta information for the exact package by grep'ing `Cache HIT`:

```
-- [hunter *** DEBUG *** 2015-11-25T23:51:28] Checking cache directory: /.../Hunter/_Base/Cache/meta/5da9172/Boost/1.58.0-p1/bc417f9/da39a3e/a49b0e5/da39a3e/da39a3e
-- [hunter] Cache HIT: Boost
-- [hunter *** DEBUG *** 2015-11-25T23:51:28] Unpacking:
-- [hunter *** DEBUG *** 2015-11-25T23:51:28]   /.../Hunter/_Base/Cache/raw/088cd7ab065745ae1d28cd37bd357d71cc6245a7.tar.bz2
-- [hunter *** DEBUG *** 2015-11-25T23:51:28]   -> /.../Hunter/_Base/8574431/55402bc/5da9172/Install
```

and removing "cache directory" and raw ".tar.bz2" archive.

To do it nicely extra tool needed: https://github.com/ruslo/hunter/issues/173

**Comment by headupinclouds** [comment]
UPDATE: For reference...

A package will be rebuilt if the hunter-id, toolchain-id, or config-id changes.  In most cases, for a working package, this should be sufficient to trigger new builds when anything that will impact the compiled binaries changes.  One can run into scenarios where the above ID's are all fixed, but they still want the package to be reinstalled for some reason.  For example, if you are in the process of creating a package with a fixed name and version, and are fine tuning the package build files.  In this case you can **force** the package to rebuild by artificially modifying the config-id by introducing a new unused variables in the `CMAKE_ARGS` for the `hunter_config()` call:

```
hunter_config(foo VERSION ${HUNTER_foo_VERSION} CMAKE_ARGS DUMMY=1)
```
