### ISSUE TITLE
Provide an option to install in system path with all dependencies

### ISSUE THREAD

**Issue by daminetreg** [ruslo/hunter#272]
Currently if you download a library which is hunterized and use cmake && make, all will run fine, dependencies are installed by hunter and the library is built.

But then if someone want to use the library without hunter and he does "make install", the dependencies of the library are not installed with.

Would it be feasible to provide this option ?
##

**Comment by headupinclouds** [comment]
I'm assuming you can't use a shared library for your application?

In the case of static libraries, Ruslo had previously pointed me to the
fixup_bundle option, which can package all the library dependencies
(without headers?), but I haven't tried it yet.

It would also be nice to include header files to allow the end library
users to link to the same version of any shared dependencies within their
application.

Hunter does a nice job of installing all of these within
${HUNTER_ROOT}/_Base, as in:

tree ${HUNTER_ROOT}/_Base/xxxxxxx/d12aa17/3dad03a/Install/


I've been using bash scripts to grab the post installation layout from
there for redistribution after my builds, but a more automated approach
would be nice.  I've used CMake's portable "tar" build command to copy
directory structures with CMake scripts before.  I was thinking about a
hunter CMake macro that could be used to package a list of user specified
dependencies along with the build, but I suppose a similar feature could be
added to the build.py python script as a post build step.

**Comment by daminetreg** [comment]
I can naturally link everything statically, and this is possibly the best option to choose for a compiled binary.

But take a reusable header only library depending for example on boost, one could download the lib and make `cmake && make install`, this will download and install boost in hunter prefix, but then the library, and not boost headers will get installed in the system.

He could naturally use the library with hunter, but he is not obliged to, he can use it simply as installed with make install and make a simple find_package.

What I ask is if it would be a good idea to provide an `hunter_install`, which would add a target to install all dependencies required by a project using hunter in the destination `CMAKE_INSTALL_PREFIX` of the project.

The idea with the bundle might be the right thing to do, I'll play a bit with it to see if it's enough.

**Comment by daminetreg** [comment]
Thanks for sharing your ideas @headupinclouds  :smile:

**Comment by ruslo** [comment]
> But then if someone want to use the library without hunter and he does "make install", the dependencies of the library are not installed with

I don't get this scenario, can you describe it with example?

> What I ask is if it would be a good idea to provide an hunter_install, which would add a target to install all dependencies required by a project using hunter in the destination CMAKE_INSTALL_PREFIX of the project

It would be not so hard to add such target (which will be enabled by option). And when user run this target all files from `<root-id>/Install` installed to `CMAKE_INSTALL_PREFIX`. Note that since `<root-id>` in general can be shared between several projects final result is unpredictable, i.e. if your project `Foo` doesn't use `GTest` but some other project `Boo` use `GTest` then it will be copied too.

**Comment by ruslo** [comment]
> It would be not so hard to add such target (which will be enabled by option)

Important note that packages in root should be relocatable.

**Comment by daminetreg** [comment]
On 26/11/2015 01:57, Ruslan Baratov wrote:
>     It would be not so hard to add such target (which will be enabled by
>     option)
> 
> Important note that packages in root should be relocatable.


Imagine lib-banana dependent on boost and installing only headers and
using only headers from boost.

Typically before the hunter era :smile:, the people were used to install
libraries themselves on their system to be able to use them in their
application.

Meaning they would have done :

1. Download boost
2. bjam install boost in /usr/local/include/
3. Download lib-banana
4. run cmake && make install in lib-banana to get headers installed in
/usr/local/include/
5.  Add find_package(lib-banana) to their cmake
6. Develop their app based on lib-banana.


Today they can do the perfect hunter enabled scenari :

1. Add HunterGate to their CMakeLists
2. add hunter_add_package(lib-banana)
3. Develop their app based on lib-banana.

What I would like to, is that they can still benefit from Hunter even if
they don't use it.

1. Download lib-banana
2. run cmake && make
    - Which would download, make install Boost into hunter
3. run make install-with-deps
    - Which would install boost from the hunter cache in the system
    - install the library in the system.
4. Develop their app based on lib-banana.

This is naturally a generator for DLL hell and include hell, but it's a
typical past scenario that many developer I know do, and that would make
non hunter adopters benefit from hunter.

Similarly if they want to ship an app with shared objects, all
dependencies could be installed with and packed in an installer with cpack.

I think this would be a good feature, because today people might get
frustration when they take the imaginary lib-banana:

1. Download lib-banana
2. run cmake && make
- Which would download, make install Boost into hunter
- There they go for a coffee because boost install is long
3. run make install
4. Try to compile their app based on lib-banana. And boom COMPILE ERROR
boost isn't found.
5. They download unpack install boost a second time
6. They can compile, until the lib updates itself and boost version
changes...

But as you mean it's not a scenario that should be advised, I just think
that it would easy library author to integrate hunter in their own library.

Cheers,
--
Damien Buhl

**Comment by ruslo** [comment]
> I'm assuming you can't use a shared library for your application? In the case of static libraries, Ruslo had previously pointed me to the fixup_bundle option, which can package all the library dependencies (without headers?), but I haven't tried it yet.

Actually it's vice versa :) There is some info in dynamic libraries that can be used to determine dependencies (as far as I know there is no such info in static).

Some Qt application for example: https://github.com/forexample/qt-cmake/tree/master/TextFinder

It's possible to run `otool -L` to figure out what libraries we need to use.

Build configuration (i.e. without `fixup_bundle`):

```bash
> otool -L TextFinder.app/Contents/MacOS/TextFinder
TextFinder.app/Contents/MacOS/TextFinder:
	/usr/local/opt/qt5/lib/QtWidgets.framework/Versions/5/QtWidgets (compatibility version 5.5.0, current version 5.5.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 21.0.0)
	/usr/local/opt/qt5/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.5.0, current version 5.5.0)
	/usr/local/opt/qt5/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.5.0, current version 5.5.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 283.0.0)
```

As you can see Qt's libraries QtCore, QtGui, QtWidgets is outsize of the bundle. But if you run same `otool -L` command with installed bundle (after `fixup_bundle` applied):

```bash
> otool -L TextFinder.app/Contents/MacOS/TextFinder
TextFinder.app/Contents/MacOS/TextFinder:
	@executable_path/../Frameworks/QtWidgets.framework/QtWidgets (compatibility version 5.5.0, current version 5.5.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 21.0.0)
	@executable_path/../Frameworks/QtGui.framework/QtGui (compatibility version 5.5.0, current version 5.5.0)
	@executable_path/../Frameworks/QtCore.framework/QtCore (compatibility version 5.5.0, current version 5.5.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 104.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 283.0.0)
```

They moved inside, so you can copy `TextFinder.app` to another location (with or without Qt in `/usr/local/opt/qt5`) and it will just work.

Same happens for Windows - `*.dll` moved from some location from PATH to the current directory with binary. From my experience on Linux this command do nothing.

**Comment by ruslo** [comment]
> This is naturally a generator for DLL hell and include hell, but it's a typical past scenario that many developer I know do, and that would make non hunter adopters benefit from hunter

Additionally when you install Boost from Hunter to system you're rewriting results of job of native package manager. Not very good idea I guess :)

> What I would like to, is that they can still benefit from Hunter even if they don't use it

What about using `<root-id>/Install` directory but without Hunter integration code from HunterGate? You just need to update some variables like [CMAKE_MODULE_PATH](https://github.com/ruslo/hunter/blob/master/cmake/Hunter) or [CMAKE_FIND_ROOT_PATH](https://github.com/ruslo/hunter/blob/master/cmake/modules/hunter_finalize.cmake) so packages will be found from Hunter.

@daminetreg Thanks for example, now I see what is needed.

@daminetreg @headupinclouds So the best option will be to add some variable like `HUNTER_INSTALL_WITH_DEPENDENCIES=ON` which will on install copy all headers/libraries to `CMAKE_INSTALL_PREFIX` (alongside with "normal" installed target?).

**Comment by headupinclouds** [comment]
> So the best option will be to add some variable like
HUNTER_INSTALL_WITH_DEPENDENCIES=ON which will on install copy all
headers/libraries to CMAKE_INSTALL_PREFIX (alongside with "normal"
installed target?).

That makes sense to me.

**Comment by daminetreg** [comment]
> Additionally when you install Boost from Hunter to system you're rewriting results of job of native package manager. Not very good idea I guess :)

That's why you would typically install on linux in /usr/local or a development sysroot, or on windows in some C:\all-my-libs\.

This would also allow people compiling for example their apps with a non-cmake build to use an hunterized library installed with hunter. This use case for hunter appeared to me during the review of some library I'm writing : https://github.com/daminetreg/lib-cpp-pre/pull/1. 

Perhaps we should display a warning when this option get set, telling to take care that it will install the libraries and all it's dependencies, and better would be to use the library via hunter.

`HUNTER_INSTALL_WITH_DEPENDENCIES=ON` would be awesome. I'll look after I'm finished with pcre if I can implement a try.

**Comment by daminetreg** [comment]
> What about using <root-id>/Install directory but without Hunter integration code from HunterGate? You just need to update some variables like CMAKE_MODULE_PATH or CMAKE_FIND_ROOT_PATH so packages will be found from Hunter.

Hmmm... Would be possible, this means pointing the sysroot to the hunter sysroot. Actually this is not a bad idea and wouldn't need any special implementation from hunter side, but what if I already have a sysroot with other libraries ? And what if I don't have cmake, I have to configure alot in comparison to having the lib in the place where my default project settings already search.

I'm also a bit biased about it, but I think it so much typical that people try out libraries that way, that easing this use case would make sense.

**Comment by ruslo** [comment]
> This would also allow people compiling for example their apps with a non-cmake build to use an hunterized library installed with hunter

Yes, that's what David was describing above.

> I'll look after I'm finished with pcre if I can implement a try

I will open new `enhancement` issue with implementation notes.

> but what if I already have a sysroot with other libraries ?

It's a list-like variable, you can have several as far as I understand:
* https://cmake.org/cmake/help/v3.3/variable/CMAKE_FIND_ROOT_PATH.html

**Comment by ruslo** [comment]
> I will open new enhancement issue with implementation notes.

See https://github.com/ruslo/hunter/issues/274. May be will add more info/thoughts in future.

**Comment by daminetreg** [comment]
Thanks for #274, that's nice to have made such precise implementation notes. We could close this discussion in this case. :smile:

**Comment by ruslo** [comment]
Closing inactive discussion.
