### ISSUE TITLE
Add Lua package

### ISSUE THREAD

**Issue by Dinno** [ruslo/hunter#277]
http://www.lua.org/download.html

Note: I am doing it already in my fork, and I made this ticket with intention to trace my progress here, and ask questions.
##

**Comment by ruslo** [comment]
>  I am doing it already in my fork

if you want I can create new project here: https://github.com/hunter-packages
what github repo are you using? (well, is it github repo?)

**Comment by Dinno** [comment]
I don't understand how you use those projects. Are they just copies of original projects, or you make patches there? And I see that project for boost is empty, and I don't understand why.

**Comment by ruslo** [comment]
> Are they just copies of original projects, or you make patches there?

Yes, for patches.

> And I see that project for boost is empty, and I don't understand why

Try to switch branches :)

**Comment by Dinno** [comment]
Well. Lua, as far as I know, does not expose any kind of source management system to external world. Source is available as archive here: http://www.lua.org/ftp/lua-5.3.2.tar.gz And this archive includes only makefile and instructions how to build it using some other type of build system. So, placing it to some repo for patching (adding CmakeLists.txt file), is a good idea. I already have variant of CmakeLists.txt for Lua: [CmakeLists.txt](https://github.com/ruslo/hunter/files/50284/CmakeLists.txt)

And if you place Lua to some repo, I will need access to the repo for modification.

**Comment by ruslo** [comment]
> So, placing it to some repo for patching (adding CmakeLists.txt file), is a good idea

See: https://github.com/hunter-packages/lua

> And if you place Lua to some repo, I will need access to the repo for modification

Sure, just accept invitation

**Comment by Dinno** [comment]
I don't see the invitation. May be I just don't know where to look for it.

**Comment by ruslo** [comment]
> I don't see the invitation

Have no idea, usually I'm sending them, not receiving :) I see status pending

![lua](https://cloud.githubusercontent.com/assets/4346993/11547223/00fc4c1a-9985-11e5-93bc-6a83101d70f9.png)

**Comment by Dinno** [comment]
I received it. Thank you!

**Comment by ruslo** [comment]
I've reverted branch `master` so it contains only original code: https://github.com/hunter-packages/lua/tree/master
Hunterizing patch moved to branch `hunter`: https://github.com/hunter-packages/lua/tree/hunter (which is now default)

**Comment by Dinno** [comment]
I added commit to hunter branch of Lua patch repo. Could you review it please?

**Comment by ruslo** [comment]
> Could you review it please?

You can open pull request there and ping me

**Comment by Dinno** [comment]
Oh, I thought it was still open. I will do it. 

I have a problem with libRocket's source files layout. They placed CmakeLists.txt not into root directory of source tree, but into Build directory. ExternalProject_add can not build such project (AFAIK, and I searched Web for solution). I understand I can patch the package, but is there some other way to do it? 

I will ask creator of libRocket to move CMakeLists.txt to root dir anyway.

**Comment by ruslo** [comment]
> I understand I can patch the package, but is there some other way to do it?

Patching is the easiest know to me.

**Comment by ruslo** [comment]
> Oh, I thought it was still open. I will do it. 

I mean open pull request with your changes in https://github.com/hunter-packages/lua project, not in Hunter.

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/pull/283
