### ISSUE TITLE
Add glm package

### ISSUE THREAD

**Issue by Dinno** [ruslo/hunter#281]
http://glm.g-truc.net/0.9.7/index.html
##

**Comment by ruslo** [comment]
github repo: https://github.com/g-truc/glm
*note*: use CMake

**Comment by regnirpsj** [comment]
in that context https://github.com/g-truc/gli would fit very well too

**Comment by ruslo** [comment]
Let's add separate issue: https://github.com/ruslo/hunter/issues/382
@regnirpsj Feel free to add any useful info
