### ISSUE TITLE
Universal static library for iOS

### ISSUE THREAD

**Issue by tzemaitis** [ruslo/hunter#282]
Hello,

I am using patched CMake (https://github.com/ruslo/CMake/releases/tag/v3.4.0-gjasny-0).
To configure project I am using this toolchain: https://github.com/ruslo/polly/blob/master/ios-nocodesign-9-1.cmake
with command like this:
cmake -H. -B_builds/ios-9-1 -GXcode -DCMAKE_TOOLCHAIN_FILE=$POLLY_ROOT/ios-nocodesign-9-1.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DPOLLY_STATUS_DEBUG=ON -DHUNTER_STATUS_DEBUG=ON -DHUNTER_RUN_INSTALL=ON

All dependencies (like GTest and ZLIB) are downloaded and build, but when I use lipo -info on them, I see what libs are not fat and contains only armv7 architecture (only boost static libs are fat and contains all architectures, but looks like it uses different tools to get this)

I tried to add additions CMAKE arguments:
-DCMAKE_IOS_INSTALL_UNIVERSAL_LIBS=YES
-DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
but it do not helped.

What I am doing wrong?

**Comment by ruslo** [comment]
> I am using patched CMake (https://github.com/ruslo/CMake/releases/tag/v3.4.0-gjasny-0)

You should not use this version, it's marked as `Pre-release`. Try:
* https://github.com/ruslo/CMake/releases/tag/v3.4.0-rc2-p0

> I tried to add additions CMAKE arguments:
-DCMAKE_IOS_INSTALL_UNIVERSAL_LIBS=YES
-DCMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH=NO
but it do not helped.

This stuff has WIP status in CMake upstream. Currently Hunter use another approach. When CMake fix will be merged to official version I will make update of both README and Hunter internal code.

**Comment by ruslo** [comment]
I've merged newly `3.4.1` CMake version and add the exact link to README to avoid confusions in future:
* https://github.com/ruslo/CMake/releases/tag/v3.4.1-p0
* https://github.com/ruslo/hunter#notes-about-version-of-cmake

**Comment by ruslo** [comment]
> This stuff has WIP status in CMake upstream

Though you can experiment with it now:
* Hunter release: https://github.com/ruslo/hunter/releases/tag/v0.13.0
* CMake with new `IOS_INSTALL_UNIVERSAL_LIBS` feature: https://github.com/ruslo/CMake/releases/tag/v3.4.0-gjasny-0

I recommend you to create a separate `HUNTER_ROOT` directory for such experiments to avoid problems with cache.

**Comment by tzemaitis** [comment]
One more questions. How can I build my target project as fat lib with cmake --build command?

Configure like this:
cmake -H. -B_builds/ios-9-1 -GXcode -DCMAKE_TOOLCHAIN_FILE=$POLLY_ROOT/ios-9-1.cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DPOLLY_STATUS_DEBUG=ON -DHUNTER_STATUS_DEBUG=ON -DHUNTER_RUN_INSTALL=ON -DCMAKE_INSTALL_PREFIX=<some_custom_path>

then build with:
cmake --build _builds/ios-9-1 --config Release
and this one build only iphoneos debug for armv7 arch

If I do build with xcodebuild -target install -configuration Debug on generated project file, everything is done correctly. Are this is the correct way and cmake --build is not capable to build fat binaries?

**Comment by ruslo** [comment]
> How can I build my target project as fat lib with cmake --build command?

I think it's possible to set `ONLY_ACTIVE_ARCH=NO` dynamically (after project created) to `xcodebuild`, not sure about syntax. This will build fat simulator or fat device library.

Patched CMake is not designed to build simulator + device in build directory, only on installation step (same for the upstream CMake feature). First reason is that it may be tricky/not optimal in some scenarios. Second reason is about workflow:
* You have Xcode openned
* You want to test new fix on device or simulator
* You choose device or simulator and hit "RUN" button
* Only one architecture built and application executed (if `ONLY_ACTIVE_ARCH` is `NO`)
* If `ONLY_ACTIVE_ARCHS` is `YES` then some extra architectures will be built, but in fact are not used on run. Hence it's just increase build time without any useful features

**Comment by ruslo** [comment]
> Thanks for your help, with correct cmake everything works perfect! 

Closing.
