### ISSUE TITLE
How add new component in boost? 

### ISSUE THREAD

**Issue by VladEvka** [ruslo/hunter#291]
I need boost::uuid.

**Comment by ruslo** [comment]
> I need boost::uuid. 

Looks like it's a header-only library, right?

**Comment by VladEvka** [comment]
@ruslo, I don't know) 
It sems no.
https://github.com/boostorg/uuid

http://stackoverflow.com/questions/3247861/example-of-uuid-generation-using-boost-in-c#3248017

**Comment by ruslo** [comment]
> It sems no. https://github.com/boostorg/uuid

Well, I see only tests

From build log, list of components to build:
```
Component configuration:

    - atomic                   : not building
    - chrono                   : not building
    - container                : not building
    - context                  : not building
    - coroutine                : not building
    - date_time                : not building
    - exception                : not building
    - filesystem               : not building
    - graph                    : not building
    - graph_parallel           : not building
    - iostreams                : not building
    - locale                   : not building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - program_options          : not building
    - python                   : not building
    - random                   : not building
    - regex                    : not building
    - serialization            : not building
    - signals                  : not building
    - system                   : not building
    - test                     : not building
    - thread                   : not building
    - timer                    : not building
    - wave                     : not building
```

**Comment by ruslo** [comment]
Example works fine for me: https://github.com/ruslo/hunter/commit/d00f6a39c7b05bba413b997d1844333ff3350b07

**Comment by VladEvka** [comment]
@ruslo , ths! 
I don't see:
# Header-only libraries
https://github.com/ruslo/hunter/wiki/pkg.boost

Sorry. Closed.

**Comment by ruslo** [comment]
I think it might be helpful to have this list in wiki to avoid confusion in future:
* https://github.com/ruslo/hunter/wiki/pkg.boost#boost

**Comment by VladEvka** [comment]
@ruslo, +1. + Add Boost::uuid [example](examplehttps://github.com/ruslo/hunter/commit/d00f6a39c7b05bba413b997d1844333ff3350b07)

**Comment by ruslo** [comment]
> Add Boost::uuid example.

Ok, updated: https://github.com/ruslo/hunter/wiki/pkg.boost

@VladEvka Just for your information it's a wiki, so feel free to add more notes if you think something missing :)
