### ISSUE TITLE
package CMAKE_ARGS not passed on to final CMake project !?

### ISSUE THREAD

**Issue by Knitschi** [ruslo/hunter#292]
Hi Ruslan, 

I am currently trying to create a hunter package for the current GoogleTest master branch because I want to use GTest+GMock in my project. I followed your tutorial dutifully and everything went fine. GoogleTest was downloaded, compiled and finding the package worked. Awesome! :-)

But I live on Windows and I want to compile the package with the compiler option /MDd instead of /MTd which is the default set in GoogleTest. The GoogleTest CMakeLists files allow to change that flag by calling 

`set( gtest_force_shared_crt ON CACHE BOOL "Always use msvcrt.dll" )`

In order to do that via the CMAKE_ARGS option in the config file I added the line

`hunter_config(GoogleTest VERSION master CMAKE_ARGS -Dgtest_force_shared_crt:BOOL=ON )    # This package includes GTest and GMock`

in the config file and added GoogleTest as a project. This works when i manually build GoogleTest with CMake. The debug output of hunter tells me that the argument is passed on to the call that executes cmake on the CMakeLists file that contains the call to `ExternalProject_Add()` but somehow the variable seems not to be set when that file is run. When I add the `set( gtest_force_shared_crt ON CACHE BOOL "Always use msvcrt.dll" )` line manually to that CMakeLists file it works fine and GoogleTest is compiled with the desired /MDd option.

My CMake knowledge is limited so I am asking you if you have any idea why this is not working? Maybe you clear the cmake cache before you call `ExternalProject_Add()` or something like that.

Thanks for your Help.

**Comment by Knitschi** [comment]
Ok I solved the problem myself. The correct use of `hunter_config()` is:

`hunter_config(GoogleTest VERSION master CMAKE_ARGS gtest_force_shared_crt:BOOL=ON )`

My project compiles now but issues a warning:

`gtestd.lib(gtest-all.obj) : warning LNK4099: PDB 'vc120.pdb' was not found with 'gtestd.lib(gtest-all.obj)' or at 'C:\Synced With Datenbunker\Projekte\HunterTests\VS2013x64\Debug\vc120.pdb'; linking object as if no debug info`

But this is a problem of future Knitschi. Or maybe someone can give me a hint how to solve this.

**Comment by ruslo** [comment]
> Ok I solved the problem myself. The correct use of hunter_config() is

Yes, just for your information there is wiki page with examples: https://github.com/ruslo/hunter/wiki/example.custom.config.id

**Comment by Knitschi** [comment]
Must have overlooked that. Thanks.

**Comment by ruslo** [comment]
> Ok I solved the problem myself

Closing.
