### ISSUE TITLE
Does hunter support prebuilt binary dependencies?

### ISSUE THREAD

**Issue by LegalizeAdulthood** [ruslo/hunter#296]
If I have a wxWidgets or Qt application, it doesn't make sense to rebuild the GUI framework every time I rebuild my application.  From what I can tell, Hunter only supports dependencies that are source distributions (at least that's what I see in the examples so far).

Does Hunter support pre-built binaries for my dependencies?  If so, how does this work?

**Comment by headupinclouds** [comment]
Hunter maintains a binary cache for project dependencies/packages, so they don't have to be rebuilt each time.  This is usually the `HUNTER_ROOT` environment variable as described [here](https://github.com/ruslo/hunter#first-step).  This allows the same binaries to be shared across projects on the same system (where possible).  This way they won't be rebuilt unless you change something in your project's hunter configuration that would require a rebuild.

**Comment by ruslo** [comment]
> From what I can tell, Hunter only supports dependencies that are source distributions (at least that's what I see in the examples so far)

@LegalizeAdulthood It supports any type that you can implement with ExternalProject. However pre-built binaries require to build different archives for different systems. For example for Qt you have to build and distribute Linux, OSX, Windows, iOS, Android, ... instead of one source package. Pre-built binaries can be supported by sharing cache on some central server, see this feature request: https://github.com/ruslo/hunter/issues/75. tl;dr it will do the same but automatically/correctly.

**Comment by LegalizeAdulthood** [comment]
I don't see how an environment variable is going to help me when it's something like travis-ci and I get a fresh virtual machine on every build and there is no state shared between builds on the machine doing the building.

**Comment by headupinclouds** [comment]
@LegalizeAdulthood: You are quite right.  I didn't know your use case and that is an important distinction.  Travis builds are timing out for me after adding QT to some projects that were previously manageable as build-from-source.  Apart from @rulos's reference to #75 above, I know travis has some support for caching dependencies [here](https://docs.travis-ci.com/user/caching/), but unfortunately it is limited to private repositories.

**Comment by LegalizeAdulthood** [comment]
So until Hunter supports this directly, what I have to do is use a Hunter recipe for a 3rd-party dependency that understands where to download binary dependencies and how to unpack them so that the usual cmake recipe of:

```
find_package(Boost 1.55 REQUIRED COMPONENTS unit_test_framework date_time regex)
```

would succeed.

The typical Hunter recipe for a dependency would be a cmake recipe for building the package from source and getting the includes and libraries put into the place where Hunter would look for them so that `find_package` succeeds.

For a binary dependency, my Hunter recipe would be one that downloads and unpacks the appropriate binary archive containing the headers and pre-built libraries.

Is this sounding correct?

**Comment by headupinclouds** [comment]
If it is just a single project, my initial thought would be to use hunter to build the project dependencies from source somewhere using your desired toolchain and package configuration (if posible), and then package the full set of hunter managed binary dependencies (contents of `${HUNTER_ROOT}`) for reuse later.  All hunter dependencies should already be relocatable and will already have the CMake packaging required for your `find_package()` calls to work.  I think you could download your bundled `HUNTER_ROOT` in travis, then set your `export HUNTER_ROOT=<path>` before building.  Probably easier said then done! ;) 

If you are really only concerned with regression testing your direct project code and you have your dependencies uploaded from `${HUNTER_ROOT}`, then you should even be able to disable hunter at that point if you have the necessary`*.cmake` files in your `CMAKE_MODULES_PATH`.

From the readme.md:
`Backward compatibility. Turn Hunter off by adding one option HUNTER_ENABLED=OFF to use your old settings `

I'm not sure how much you have tinkered with this, but in case it helps, your per project Install folder (and nested *.cmake) file can all be found here:

```
find ${HUNTER_ROOT}/ -name "Install" -or -name "*.cmake"
```

I don't have enough experience this to predict the issues, but I hope some of that helps for now.

Here is a related thread that might also help: #272.

**Comment by ruslo** [comment]
> For a binary dependency, my Hunter recipe would be one that downloads and unpacks the appropriate binary archive containing the headers and pre-built libraries.

This approach may work but require a lot of efforts for implementation (at least to do it correctly). Almost all this work already done by "cache" feature, so it will be much easier to implement #75.

>  I think you could download your bundled HUNTER_ROOT in travis, then set your export HUNTER_ROOT=<path> before building

Downloading all HUNTER_ROOT directory may not work since it may hold hardcoded paths stuff. The quite correct way will be to download only HUNTER_ROOT/Cache directory.

>  Probably easier said than done! ;) 

Yes, you have to check carefully that your local environment fits Travis CI environment exactly, e.g. compiler id and version.

**Comment by LegalizeAdulthood** [comment]
> Yes, you have to check carefully that your local environment fits Travis CI environment exactly, e.g. compiler id and version.

@ruslo I thought that Hunter was already encoding this information in the combination of hunter-id/config-id/toolchain-id SHA1 hashes?

To elaborate my thinking a little more to make sure I understand things properly:

Where I work I built a binary dependency mechanism where a `dependencies.json` file lists package names that are needed for building.  The package names include a version number in the name so that we can migrate to new builds of dependent packages by publishing those binary packages and then updating the JSON.  We build for 32-bit and 64-bit architectures on Windows and MacOS operating systems.  The script that processes the JSON downloads the appropriate package for the host operating system.  The package has within it both 32-bit and 64-bit variations of the prebuilt libraries.

Mapping this to a Hunter-based approach, we would have one hunter-id that mapped the specific set of dependencies for a build.  This would be comparable to a specific version of our `dependencies.json`.  My understanding is that the hunter-id is one-to-one with a specific set of recipes for all the libraries that Hunter knows how to build.  (I see that work is progressing to allow a sort of federated model of recipes, but for now it is a single global authority.)

For the 4 Debug/Release 32-bit/64-bit combinations, each of those would map to a Hunter config-id encompassing two runs of `cmake` since only a 32-bit or 64-bit build can be generated at a time with `cmake`.

We currently only need one compiler supports on either Windows or MacOS, but each of those would map to a different toolchain-id in Hunter terms.

So, if the Hunter dependency build recipe changes, then that's a new hunter-id and we'd download new prebuilt binary packages for that updated build recipe.

If the configuration changes (say we only supported 32-bit before and now we add 64-bit), then that would change the config-id, and that would cause new packages to download.

If we upgrade the compiler from VS 2013 to VS 2015, then the toolchain-id changes and that would cause new packages to download.

Am I missing something?

**Comment by ruslo** [comment]
> I thought that Hunter was already encoding this information in the combination of hunter-id/config-id/toolchain-id SHA1 hashes?

Yes this information saved internally. I mean that if you will build your package locally using Xcode 7.2 and upload `${HUNTER_ROOT}/Cache` directory to some server and then Travis CI script will download it from server to local VM's environment but generator will be different, like Xcode 7.0 (hence different compiler) then there will be no cache hit and package will be rebuild from scratch. This can be checked by finding `Toolchain-ID` string in logs: https://github.com/ruslo/hunter#toolchain-id

> For the 4 Debug/Release 32-bit/64-bit combinations, each of those would map to a Hunter config-id encompassing two runs of cmake since only a 32-bit or 64-bit build can be generated at a time with cmake.

Yes you need to have 2 different toolchain for 32/64 bit and run CMake twice. Since Debug+Release is the default configuration this will build 4 sets of libraries. Just to note global value of configurations to build goes to toolchain-id, local/per package goes to config-id.

> We currently only need one compiler supports on either Windows or MacOS, but each of those would map to a different toolchain-id in Hunter terms.

Yes, different toolchain-id.

> So, if the Hunter dependency build recipe changes, then that's a new hunter-id and we'd download new prebuilt binary packages for that updated build recipe.

Yes, if build recipe changes then we need to rebuild library, so there will be no cache hit again. If recipe changes - hunder-id changes too, but not every hunter-id change affects archive of package in cache. So if you change boost build scheme but not Qt's scheme then Qt's will be downloaded from cache (if it's created before).

> If the configuration changes (say we only supported 32-bit before and now we add 64-bit), then that would change the config-id, and that would cause new packages to download

Yes, new packages need to be downloaded, but 32/64 build will change toolchain-id to be precise.

> If we upgrade the compiler from VS 2013 to VS 2015, then the toolchain-id changes and that would cause new packages to download

Yes, since it's different compilers, they simply produce different binaries.

**Comment by LegalizeAdulthood** [comment]
>> If we upgrade the compiler from VS 2013 to VS 2015, then the toolchain-id changes and that would cause new packages to download

> Yes, since it's different compilers, they simply produce different binaries.

Just to clarify: different compilers result in different toolchain-ids, correct?

Naturally they produce different binaries because they are different compilers.

When changing compilers this is reflected in Hunter's toolchain-id, or even the same compiler but with different flags as [described in the readme](https://github.com/ruslo/hunter/tree/develop#toolchain-id).  (For instance, I might want a version of Qt with profile-guided optimization and this would be a different set of libraries from the regular Qt libraries.)

**Comment by ruslo** [comment]
> Just to clarify: different compilers result in different toolchain-ids, correct?

Yes.

> When changing compilers this is reflected in Hunter's toolchain-id, or even the same compiler but with different flags as described in the readme

Yes

> For instance, I might want a version of Qt with profile-guided optimization and this would be a different set of libraries from the regular Qt libraries

In general yes, but in practice we may have some bugs. For example if some CMake-based project rewrite/force some flags then flags from toolchain may be ignored. This is issue in package itself, not Hunter, see this wiki section: https://github.com/ruslo/hunter/wiki/usr.adding.new.package#default-behaviour. For non-CMake builds everything depends on how scheme is fine tuned for such job. Boost for example picks flags from `CMAKE_CXX_FLAGS`, but Qt not. In this case scheme need to be improved.

Also `toolchain-id` calculated from checking what C++ macroses defined: https://github.com/ruslo/hunter/blob/master/scripts/predefined.list. This works for such stuff like CPU type, OS, compiler version, stdlib type/version, c++11/c++98 and so on. Some flags can't be detected in such way and need to set hint for Hunter. E.g. sanitize address, memory and thread can be detected, but not sanitize leak. We need to add hint string to `HUNTER_TOOLCHAIN_UNDETECTABLE_ID`: https://github.com/ruslo/polly/blob/master/flags/sanitize_leak.cmake. Probably profile-guided optimization need this improvement too.

**Comment by LB--** [comment]
I'm just here to comment about travis - I have no opinion on the actual subject matter.

> I don't see how an environment variable is going to help me when it's something like travis-ci and I get a fresh virtual machine on every build and there is no state shared between builds on the machine doing the building.

Travis has caching support! Just be aware that if your build times out, it doesn't upload the cache, so you may need to comment out some parts of your build to get the cache initially. (It also uploads the cache if the build fails)

> I know travis has some support for caching dependencies here, but unfortunately it is limited to private repositories.

This is not true. I have been using caching in my public open source builds for free.

**Comment by headupinclouds** [comment]
@LB-- : Thanks for the info.  I'm very interested in this actually, but haven't had time to experiment with it.  Do you have a pointer to the open source project where you use this functionality?

**Comment by LegalizeAdulthood** [comment]
@LB The problem with not using sudo is that their compilers in their environments are quite old (gcc 4.6.3), no boost available, etc.  When I setup travis for my builds, I had to update the compiler, pull down boost from a PPA (haven't found a PPA that tracks boost reliably yet), install cmake, and clang's static analyzer.

I still can't find accurate documentation of exactly what C++ tools and versions are installed in their various images.  They now appear to have CMake, but who knows about the rest of the stuff without making spike scripts and trying to get the tools to barf out their versions.

**Comment by LB--** [comment]
@headupinclouds @LegalizeAdulthood See https://github.com/LB--/travis where I both use caching and have already done the hard work of updating tools for you

**Comment by LegalizeAdulthood** [comment]
@LB-- I found it just before you added your note, thanks.  However, all your scripts are cloning tip of trunk for various things and that just yields too many surprises.  I think instead you want to check out particular release tags.  Otherwise, how do you know you're getting the same thing from build to build?

**Comment by LegalizeAdulthood** [comment]
[Travis docs on caching](https://docs.travis-ci.com/user/caching/)

Looks like you could add `$HUNTER_ROOT` to the cache as the simplest approach for Hunter-based travis jobs.  Unfortunately this doesn't solve the time out problem when building your dependencies takes longer than travis allows for your job to run (Boost, Qt and wxWidgets are notoriously lengthy compiles).

**Comment by ruslo** [comment]
> Just be aware that if your build times out, it doesn't upload the cache, so you may need to comment out some parts of your build to get the cache initially

@LB-- The problem that there is no way to comment out Qt steps. It takes a lot of time even for one component. And as far as I know same timeouts used for private Travis CI repos. So there is no much choice here - we need to build Qt somewhere else and upload archives from cache to some server for further usage.

> The catch is that it has to use the new container based infrastructure which does not allow use of sudo

@LB-- Does it work on their OSX machines?

>  Unfortunately this doesn't solve the time out problem when building your dependencies takes longer than travis allows for your job to run (Boost, Qt and wxWidgets are notoriously lengthy compiles)

@LegalizeAdulthood Boost can be compiled step-by-step. Each component compiles quite independently. Qt can't be optimized this way, see above. Don't know about wxWidgets.

**Comment by LB--** [comment]
> Does it work on their OSX machines?

@ruslo I [just checked](https://github.com/LB--/travis/blob/600af3de79de2af53bf8e054fff3d71cfc23ea6b/.travis.yml), and it appears [it does not](https://travis-ci.org/LB--/travis/builds/102031702). Caching is still an experimental feature so they are probably only testing it in the Ubuntu VMs right now. Either way as you said it does not solve the problem of the initial long build that cannot be broken up. One might be able to do a dumb hack of causing the build to fail (e.g. compilation error) before the timeout and then continuing the build in the next commit, but that is honestly a last-ditch workaround and quite the opposite of ideal.

**Comment by ruslo** [comment]
Implemented. See new wiki page about uploading cache:
* https://github.com/ruslo/hunter/wiki/Uploading-binaries-to-server
