### ISSUE TITLE
Add libpq from PostgreSQL

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#300]
Hi Ruslan, hope you are doing good :-)

I am trying to add `libpq` to hunter. I've created a repository on https://github.com/pretyman/libpq with the postgres 9.5.0 source tarball but without the bin dir and some minor changes to the makefiles to not compile the binaries utilities and other targets that `libpq` does not depend on.

My doubts are:
1. The library is `libpq`, but `CMake` comes with a `Modules/FindPostgreSQL.cmake`. Should I name the package PostgreSQL?
2. If we are to use FindPostgreSQL, it does not define a target `libpq`, nor any target, that we could conveniently add to `target_link_libraries`. Should I then I could leave the hunter package named libpq, create our own `Findlibpq.cmake` script, that possibly uses internally `FindPostgreSQL.cmake`, but defines a target `libpq` with the correct include directories and libraries? 

For me creating a separate `Findlibpq.cmake` which defines its own target makes more sense, but let me know your thoughts.

Thanks, со Старым Новым годом!

**Comment by ruslo** [comment]
> I've created a repository on https://github.com/pretyman/libpq with the postgres 9.5.0 source tarball

I forked it to https://github.com/hunter-packages/libpq. I've sent you invitation to the team.

> Should I name the package PostgreSQL?

I think yes

> If we are to use FindPostgreSQL, it does not define a target libpq, nor any target, that we could conveniently add to target_link_libraries

You can patch standard FindPostgreSQL so it will define `PostgreSQL::libpq` imported target and save it to [cmake/find](https://github.com/ruslo/hunter/tree/master/cmake/find) directory. This directory has high priority. `PostgreSQL_LIBRARIES` can be set to `PostgreSQL::libpq` for backward compatibility, `PostgreSQL_INCLUDE_DIRS` can be set to empty string.

> со Старым Новым годом!

Спасибо :)

**Comment by pretyman** [comment]
If I name the package PostgreSQL, shouldn't you create a repository https://github.com/hunter-packages/PostgreSQL instead of libpq ? Or it is better that I create and you fork?

**Comment by ruslo** [comment]
> If I name the package PostgreSQL, shouldn't you create a repository https://github.com/hunter-packages/PostgreSQL instead of libpq ?

Both repository and team name renamed

**Comment by pretyman** [comment]
Thanks, you can delete branch libpq-9.5.0 if you wish
