### ISSUE TITLE
Troubles adding MySQL client library to hunter

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#303]
Hi Ruslan,

I am facing some troubles adding the MySQL client library 6.1.6 to hunter, it is not cleanly fully building with hunter + polly. 

My platform is OSX 10.11.2 + Xcode 7.1.1:
```
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
```

It seems that the CMakeLists.txt of the mysql connector is broken when building with Debug config. I can build it outside hunter, but with hunter it seems to force a Debug build:

```
[ 56%] Creating directories for 'MySQL-client-Debug'
...
[ 97%] Built target libmysql
make[3]: *** [all] Error 2
make[2]: *** [MySQL-client-Debug-prefix/src/MySQL-client-Debug-stamp/MySQL-client-Debug-install] Error 2
make[1]: *** [CMakeFiles/MySQL-client-Debug.dir/all] Error 2
make: *** [all] Error 2
```
The full build log is at https://gist.github.com/pretyman/fea1909a9f100094b1b5
The erros show if I go into the hunter build directory and build it manually:

```
make[5]: *** No rule to make target `extra/yassl/taocrypt/libtaocrypt.a', needed by `libmysql/mysqlclient_depends.c'.  Stop.
make[4]: *** [libmysql/CMakeFiles/mysqlclient.dir/all] Error 2
```

My question is: how can I disable the debug build of a url_sha1_cmake build scheme? I tried `--config Release` with polly, but it seems to compile the MySQL library in Debug anyway. Since when buildings outside hunter it does not produce the error, I believe there should be a way to patch it.

It is possible to reproduce the error by checking out the branch MySQL-client on https://github.com/pretyman/hunter and run the build on examples/MySQL-client  

Thanks!

**Comment by ruslo** [comment]
> It seems that the CMakeLists.txt of the mysql connector is broken when building with Debug config

So if you build it without Hunter but with Debug config it will fail?

> how can I disable the debug build of a url_sha1_cmake build scheme?

You can set `hunter_configuration_types` explicitly in `hunter.cmake`: https://github.com/ruslo/hunter/wiki/usr.adding.new.package#build-types

> I tried --config Release with polly, but it seems to compile the MySQL library in Debug anyway

This is correct behaviour since type of 3rd party build may be different from type of local build.

**Comment by pretyman** [comment]
> So if you build it without Hunter but with Debug config it will fail?

Exactly.

Building with polly and without Hunter on Debug results in the same error.

Building with polly and without Hunter on Release results in success.

> You can set hunter_configuration_types explicitly in hunter.cmake: https://github.com/ruslo/hunter/wiki/usr.adding.new.package#build-types

Thank you so much! This worked!

It is acceptable to contribute the package like this?

**Comment by ruslo** [comment]
> It is acceptable to contribute the package like this?

In general yes. But of course if you figure out what's the problem and make a fix it would be best

**Comment by ruslo** [comment]
> Thank you so much! This worked!

Closing.
