### ISSUE TITLE
Qt Creator + Ninja not supported on Windows with Visual C++ target

### ISSUE THREAD

**Issue by cristianadam** [ruslo/hunter#311]
hunter uses `${CMAKE_GENERATOR}` to determine which version of Visual C++ compiler is used.

But when using Ninja as CMake generator then it fails. Hunter needs to have a better way to detect the Visual C++ compiler.

Qt Creator uses internally also the `vcvarsall.bat` but it uses the `CodeBlocks - Ninja` CMake generator to have the project information from the CodeBlocks xml (cbp) file.

Hunter could parse the `LIB` environment variable (`$ENV{LIB}` in cmake speak), which is set by `vcvarsall.bat`.

Visual C++ 2013 32bit:

```LIB=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\ATLMFC\LIB;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x86;```

Visual C++ 2013 64bit:
```LIB=C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\LIB\amd64;C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\ATLMFC\LIB\amd64;C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64;```

**Comment by ruslo** [comment]
> hunter uses ${CMAKE_GENERATOR}" to determine which version of Visual C++ compiler is used.

Not exactly, if you are talking about [hunter_setup_msvc](https://github.com/ruslo/hunter/blob/master/cmake/modules/hunter_setup_msvc.cmake) module. This module defines variables `HUNTER_MSVC_ARCH`, `HUNTER_MSVC_VERSION`, `HUNTER_MSVC_YEAR` if they are not defined. You can define them manually, e.g. here are CMake modules that used in `nmake-*` toolchains:
* https://github.com/ruslo/polly/blob/master/compiler/msvc-2015.cmake
* https://github.com/ruslo/polly/blob/master/arch/msvc-x64.cmake

> Hunter could parse the LIB environment variable (ENV{LIB} in cmake speak), which is set by vcvarsall.bat

As alternative we can try to check some CMake variables, e.g. [MSVC_VERSION](https://cmake.org/cmake/help/latest/variable/MSVC_VERSION.html).

**Comment by cristianadam** [comment]
I've tried to get the [bzip2 example](https://github.com/ruslo/hunter/tree/master/examples/BZip2) working.

I've copied the [foo.cpp](https://raw.githubusercontent.com/ruslo/hunter/master/examples/BZip2/foo.cpp) and [CMakeLists.txt](https://raw.githubusercontent.com/ruslo/hunter/master/examples/BZip2/CMakeLists.txt) from the [bzip2 example wiki page](https://github.com/ruslo/hunter/tree/master/examples/BZip2).

Then got the [HunterGate.cmake](https://raw.githubusercontent.com/hunter-packages/gate/master/cmake/HunterGate.cmake) and put it in the `cmake/HunterGate.cmake` subdirectory.

Finally I've changed the `CMakeLists.txt` to use HunterGate. My CMakeLists.txt looks like this:

```
# Copyright (c) 2014, Ruslan Baratov
# All rights reserved.

cmake_minimum_required(VERSION 3.0)

include(cmake/HunterGate.cmake)

HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.12.39.tar.gz"
    SHA1 "587bc8f6278f2b09ec8759d2b6a2f8d828c30f49"
)

project(download-bzip2)

hunter_add_package(BZip2)

find_package(BZip2 CONFIG REQUIRED)
add_executable(foo foo.cpp)
target_link_libraries(foo BZip2::bz2)
```

Then I've opened `CMakeLists.txt` with Qt Creator. And selected my Visual C++ 2013 x64 kit and clicked on "Run CMake" in Qt Creator CMake wizard.

The output of the Run CMake is below:

```
Running: 'C:\Tools\cmake-3.3\bin\cmake.exe' with arguments '-DCMAKE_BUILD_TYPE=Release' in 'C:\Projects\C++\build-bzip2-Visual_C_2013_x64-Release'.
-- The C compiler identification is MSVC 18.0.40629.0
-- The CXX compiler identification is MSVC 18.0.40629.0
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [hunter] Calculating Config-SHA1
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] HUNTER_ROOT: C:/.hunter
-- [hunter] [ Hunter-ID: 587bc8f | Config-ID: 26d60e4 | Toolchain-ID: 4063cf5 ]

[hunter ** INTERNAL **] Invalid MSVC generator: Ninja
[hunter ** INTERNAL **] [Directory:C:/Projects/C++/bzip2]-- Configuring incomplete, errors occurred!
See also "C:/Projects/C++/build-bzip2-Visual_C_2013_x64-Release/CMakeFiles/CMakeOutput.log".
```

I was expecting everything to just work. But unfortunately it didn't.

**Comment by ruslo** [comment]
> Qt Creator uses internally also the vcvarsall.bat but it uses the CodeBlocks - Ninja CMake generator to have the project information from the CodeBlocks xml (cbp) file

I see only `Ninja`/`NMake` choices. Does it differs to `CodeBlocks - Ninja`? If so how can I add it?

![qt-creator-choice](https://cloud.githubusercontent.com/assets/4346993/12577145/21055b64-c44b-11e5-805f-b7a6c14a29b8.png)

**Comment by cristianadam** [comment]
Qt Creator uses "CodeBlcoks - Ninja" as a CMake generator. Simply use the "Ninja" target from above.

**Comment by ruslo** [comment]
> Qt Creator uses "CodeBlcoks - Ninja" as a CMake generator. Simply use the "Ninja" target from above

Okay, I see, thanks.

**Comment by cristianadam** [comment]
Please don't use MSVC_VERSION because then I don't think cmake uses this version when Clang compiler is used.

To use Clang for Windows one needs to have:

1. Visual C++ 2013 or 2015
2. [Clang for Windows](http://llvm.org/releases/download.html#3.7.1)
3. Qt Creator and then clone a Visual C++ Kit
4. Set the following environment variables for the new Kit:
```
INCLUDE=c:\Program Files\LLVM\lib\clang\3.7.1\include\;$(INCLUDE)
PATH=c:\Program Files\LLVM\msbuild-bin\;$(PATH)
```

Then everything works as one would use the regular Visual C++ target, but instead `clang-cl` is being used.

**Comment by cristianadam** [comment]
The CMake error log with Clang for Windows is a bit different:

```
Running: 'C:\Tools\cmake-3.3\bin\cmake.exe' with arguments '-DCMAKE_BUILD_TYPE=Release' in 'C:\Projects\C++\build-bzip2-Clang_3_7_1_over_Visual_C_2013_x64-Default'.
-- The C compiler identification is Clang 3.7.1
-- The CXX compiler identification is Clang 3.7.1
-- Check for working C compiler using: Ninja
-- Check for working C compiler using: Ninja -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Ninja
-- Check for working CXX compiler using: Ninja -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- [hunter] Calculating Config-SHA1
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] HUNTER_ROOT: C:/.hunter
-- [hunter] [ Hunter-ID: 587bc8f | Config-ID: 26d60e4 | Toolchain-ID: a96077a ]

[hunter ** INTERNAL **] Invalid MSVC generator: Ninja
[hunter ** INTERNAL **] [Directory:C:/Projects/C++/bzip2]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.12.39/587bc8f/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.12.39/587bc8f/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.12.39/587bc8f/Unpacked/cmake/modules/hunter_setup_msvc.cmake:24 (hunter_internal_error)
  C:/.hunter/_Base/Download/Hunter/0.12.39/587bc8f/Unpacked/cmake/modules/hunter_finalize.cmake:97 (hunter_setup_msvc)
  C:/.hunter/_Base/Download/Hunter/0.12.39/587bc8f/Unpacked/cmake/modules/hunter_add_package.cmake:23 (hunter_finalize)
  CMakeLists.txt:15 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "C:/Projects/C++/build-bzip2-Clang_3_7_1_over_Visual_C_2013_x64-Default/CMakeFiles/CMakeOutput.log".
```

**Comment by ruslo** [comment]
> Please don't use MSVC_VERSION because then I don't think cmake uses this version when Clang compiler is used

Well, variables `HUNTER_MSVC_*` set only for `MSVC` so I think it's okay.

**Comment by ruslo** [comment]
> The CMake error log with Clang for Windows is a bit different

> Well, variables HUNTER_MSVC_* set only for MSVC so I think it's okay

Looks like `MSVC` is set for `Ninja` + `Clang` tools. Is it correct? Can it be CMake bug?

**Comment by cristianadam** [comment]
> Looks like MSVC is set for Ninja + Clang tools. Is it correct? Can it be CMake bug?

It means that the Clang people did a good job at making `clang-cl` to fake `cl.exe` :)

Clang uses the Visual C++ include files and libraries. I don't think it's wise to treat it different. In source code one can ask for `__clang__` preprocesor define.

**Comment by ruslo** [comment]
For now you can use toolchain workaround. I've added `ninja-vs-12-2013-win64`:
* https://github.com/ruslo/polly/blob/master/ninja-vs-12-2013-win64.cmake

To use it just add `-DCMAKE_TOOLCHAIN_FILE=/path/to/ninja-vs-12-2013-win64.cmake` to arguments.

**Comment by ruslo** [comment]
> It means that the Clang people did a good job at making clang-cl to fake cl.exe :)

Can you check what values have `CMAKE_CXX_COMPILER_ID` and `MSCV_VERSION` variables?

**Comment by cristianadam** [comment]
> Can you check what values have CMAKE_CXX_COMPILER_ID and MSCV_VERSION variables?

```
message("${CMAKE_CXX_COMPILER_ID}")
message("${MSVC_VERSION}")
```
resulted in:
```
Clang
1800
```

**Comment by ruslo** [comment]
> resulted in:
> Clang
> 1800

Looks like the version of MSVC it tries to mimic. Problem with `HUNTER_MSVC_*` variables is mainly about custom schemes. They are used to load environment from `vcvarsall.bat` and provide some arguments like architecture (`vcvarsall.bat amd64`). I guess that some of the non-CMake packages will not survive this feature by design.

**Comment by cristianadam** [comment]
> Looks like the version of MSVC it tries to mimic. Problem with HUNTER_MSVC_* variables is mainly about custom schemes. They are used to load environment from vcvarsall.bat and provide some arguments like architecture (vcvarsall.bat amd64). I guess that some of the non-CMake packages will not survive this feature by design.

For clang `vcvarsall.bat` is also called. The LIB and INCLUDE environment variables need to be changed afterwards.

**Comment by ruslo** [comment]
In new version: https://github.com/ruslo/hunter/releases/tag/v0.12.40 variables `MSVC_VERSION`, `MSVC_CXX_ARCHITECTURE_ID` used to set `HUNTER_MSVC_{YEAR,VERSION,ARCH,VCVARSALL}` so this should work for Ninja, NMake Makefiles and Visual Studio generators.

I've openned separate feature request for clang-cl: https://github.com/ruslo/hunter/issues/313

**Comment by cristianadam** [comment]
With v0.12.40 the application compiled with Qt Creator + ninja. Thank you.

Unfortunately application doesn't start due to:

```
---------------------------
foo.exe - System Error
---------------------------
The program can't start because libbz2.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
```

For some reason Bzip2 is not creating libbz2.dll. 

I'll close this ticket though.
