### ISSUE TITLE
Cross compiling boost picks up incorrect CMAKE_CXX_COMPILER

### ISSUE THREAD

**Issue by lbuchy** [ruslo/hunter#312]
I am trying to cross-compile a project for an armv7 based SoC using a linaro gcc toolchain.

This is my toolchain file:
```
# The second and first parts of a target triplet (`gcc -dumpmachine`)
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(CMAKE_C_COMPILER   /usr/local/linaro-multilib-2014.06-gcc4.9/bin/arm-linux-gnueabihf-gcc)
set(CMAKE_CXX_COMPILER /usr/local/linaro-multilib-2014.06-gcc4.9/bin/arm-linux-gnueabihf-g++)

set(SYSTEM_PROCESSOR_C_FLAGS "-mthumb -march=armv7-a -mtune=cortex-a9 -mlittle-endian -mfloat-abi=hard -mfpu=neon -Wa,-mimplicit-it=thumb")
set(SYSTEM_PROCESSOR_CXX_FLAGS "${SYSTEM_PROCESSOR_C_FLAGS}")
set(CMAKE_C_FLAGS   "${CMAKE_C_FLAGS} ${SYSTEM_PROCESSOR_C_FLAGS}" CACHE STRING "Flags used by the C compiler")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${SYSTEM_PROCESSOR_CXX_FLAGS}" CACHE STRING "Flags used by the CXX compiler")
```

I am adding the following to my CMakeLists.txt:
```
include("${CMAKE_CURRENT_LIST_DIR}/CMake/huntergate/cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.12.39.tar.gz"
    SHA1 "587bc8f6278f2b09ec8759d2b6a2f8d828c30f49"
    FILEPATH "${CMAKE_CURRENT_LIST_DIR}/hunter.cmake"
    )

# ...

hunter_add_package(Boost COMPONENTS thread system filesystem regex)
find_package(Boost CONFIG REQUIRED thread system filesystem regex)

# ...
add_executable(TestApp ${TEST_SRCS})
add_executable(App ${APP_SRC} Boost::thread Boost::system Boost::filesystem Boost::regex)
```

Then I generate the build files:
```
cmake ${src} -DCMAKE_TOOLCHAIN_FILE=MyToolchain.cmake
```

As a sanity check, compiling the TestApp does give me a cross-compiled executable.  However, I am seeing boost getting built with my native machine's toolchain.  This is probably due to a flaw in the how the user.config.jam file is written (IIRC, it looks like it contains
```gcc : :``` 
but it should probably contain:
```gcc : : <path to cross compiler>```

If I add this statement into url_sha1_boost.cmake.in, CMAKE_CXX_COMPILER gives me /usr/bin/c++
```
hunter_internal_error("url_sha1_boost.cmake.in @CMAKE_CXX_COMPILER@")
```

**Comment by lbuchy** [comment]
Just to follow up, expanding `${CMAKE_CXX_COMPILER}` gives the correct compiler path.  This might therefore stem from my lack of knowledge about the how the atmark-surrounded-variables work.  Any insight into this? I couldn't find any documentation about them.

**Comment by ruslo** [comment]
> If I add this statement into url_sha1_boost.cmake.in

This scheme is for header-only libraries, so in fact compiler will not be used. This is a place where compiler set to jam file: https://github.com/ruslo/hunter/blob/40ef35f31043d6621aeb12dca43b257ecad9e241/cmake/schemes/url_sha1_boost_library.cmake.in#L249

Also you can add `HUNTER_STATUS_DEBUG=ON` and there will be a lot of information printed about build, including `boost.user.jam` content.

> Just to follow up, expanding ${CMAKE_CXX_COMPILER} gives the correct compiler path

In main CMakeLists.txt or in scheme?

**Comment by ruslo** [comment]
> However, I am seeing boost getting built with my native machine's toolchain

I've installed `g++-arm-linux-gnueabihf` to my Ubuntu Linux and created similar toolchain. Looks like everything works as expected. Here is excerpt from boost.system log build:

```
"/usr/bin/arm-linux-gnueabihf-g++" "-mthumb" "-march=armv7-a"
"-mtune=cortex-a9" "-mlittle-endian" "-mfloat-abi=hard" "-mfpu=neon"
"-Wa,-mimplicit-it=thumb"  -ftemplate-depth-128 -O0 -fno-inline -Wall -g
-pthread  -DBOOST_ALL_NO_LIB=1 -DBOOST_SYSTEM_STATIC_LINK=1  -I"." -c -o
"bin.v2/libs/system/build/gcc-4.8/debug/link-static/threading-multi/error_code.o"
"libs/system/src/error_code.cpp"
```

@lbuchy Can you create testing repo with your example so I can follow your test accurately?

**Comment by lbuchy** [comment]
@ruslo I got around to trying to make a testing repo and found it works correctly; I must have been doing something incorrect somewhere though I'm not sure exactly what.  I'll close this issue unless I figure out good repro instructions.
