### ISSUE TITLE
example setup in wiki/usr.adding.new.package is broken

### ISSUE THREAD

**Issue by chulup** [ruslo/hunter#318]
Following instructions in https://github.com/ruslo/hunter/wiki/usr.adding.new.package you will get following error:
[hunter ** INTERNAL **] Project 'Example' not found

That happens because hunter_add_package.cmake tries to find cmake/projects/Example/hunter.cmake in ${HUNTER_SELF} and not in ${HUNTER_ROOT} as described in wiki.

**Comment by ruslo** [comment]
> ${HUNTER_SELF} and not in ${HUNTER_ROOT}

Instructions assumed that Hunter is cloned for patching (note that there is no need to clone repository in general since HunterGate will do all download stuff). I've updated wiki page. However I recommend to use this script for testing: https://github.com/ruslo/hunter/wiki/dev.hunter.root

**Comment by ruslo** [comment]
Closing. Feel free to open new issue if you have any questions.
