### ISSUE TITLE
add boost.compute

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#321]
https://github.com/boostorg/compute (header only OpenCL interface)

**Comment by ruslo** [comment]
Is it a boost candidate or already part of boost? We may have conflicts here.

**Comment by headupinclouds** [comment]
This [page](http://boostorg.github.io/compute/) mentions that "it isn't yet an official boost library."  It is a purely header only library, so my initial thought was that the port would be fairly straightforward.

**Comment by ruslo** [comment]
Done: https://github.com/ruslo/hunter/wiki/pkg.boost.compute
