### ISSUE TITLE
clang++/c++11/libc++: GTest pack failed

### ISSUE THREAD

**Issue by tatraian** [ruslo/hunter#325]
I tried to compile GTest but I cannot build it with the latest hunter (currently 0.12.43). I got the following error:

```
[100%] Completed 'GTest-Debug'
[100%] Built target GTest-Debug
-- [hunter] Build step successful (dir: XXXXX/hunter/_Base/fdaeb5a/b8ad68d/d411be5/Build/GTest)
CMake Error: archive_read_disk_entry_from_file: Can't lstat --
CMake Error: Problem creating tar: XXXXX/hunter/_Base/Cache/raw/cache.tar.bz2

[hunter ** INTERNAL **] Packing failed
[hunter ** INTERNAL **] [Directory:XXXXX/hunter/_Base/Download/Hunter/0.12.43/fdaeb5a/Unpacked/cmake/projects/GTest]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at XXXXX/hunter/_Base/Download/Hunter/0.12.43/fdaeb5a/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  XXXXX/hunter/_Base/Download/Hunter/0.12.43/fdaeb5a/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  XXXXX/hunter/_Base/Download/Hunter/0.12.43/fdaeb5a/Unpacked/cmake/modules/hunter_pack_directory.cmake:59 (hunter_internal_error)
  XXXXX/hunter/_Base/Download/Hunter/0.12.43/fdaeb5a/Unpacked/cmake/modules/hunter_save_to_cache.cmake:78 (hunter_pack_directory)
  XXXXX/hunter/_Base/Download/Hunter/0.12.43/fdaeb5a/Unpacked/cmake/modules/hunter_download.cmake:422 (hunter_save_to_cache)
  XXXXX/hunter/_Base/Download/Hunter/0.12.43/fdaeb5a/Unpacked/cmake/projects/GTest/hunter.cmake:160 (hunter_download)
  XXXXX/hunter/_Base/Download/Hunter/0.12.43/fdaeb5a/Unpacked/cmake/modules/hunter_add_package.cmake:87 (include)
  CMakeLists.txt:16 (hunter_add_package)


-- Configuring incomplete, errors occurred!
```

I used polly 0.8.1 for builds. I got the same result with gcc as well. I expected that this worked with earlier releases, as I found v0.9.9 was the last working version.

**Comment by ruslo** [comment]
```cmake
CMake Error: archive_read_disk_entry_from_file: Can't lstat --
CMake Error: Problem creating tar: XXXXX/hunter/_Base/Cache/raw/cache.tar.bz2
```

This is not Hunter error message, this message comes from CMake itself. Since you've mentioned that it was working before I think it make sense to check:
* Does CMake version changed (may be it's CMake bug?)
* Do you have enough disk space? Probably CMake can't allocate space for creating file?

**Comment by tatraian** [comment]
I used the same CMake in both cases (stock ubuntu 15.04/CMake 3.0.2)
I have 60 GB free disk space as well. The cache.tar.bz2 is created but it is empty.

I could reproduce it with hunter-simple project. I got the same error.
If I changed Hunter version to v0.9.9 then it works well. (But it doesn't work with v0.10.0, and both versions use GTest-1.7.0-hunter-10)

**Comment by ruslo** [comment]
> If I changed Hunter version to v0.9.9 then it works well

This version without cache feature. I.e. it doesn't run `cmake -E tar` to save archive with installed files for GTest.

> CMake 3.0.2

I'm pretty sure it's CMake bug. See recommended CMake version: https://github.com/ruslo/hunter#notes-about-version-of-cmake Which lead to this comment: https://github.com/ruslo/hunter/pull/198#issuecomment-120630877

**Comment by tatraian** [comment]
I upgraded CMake to 3.2.2 and now it works properly.

Thanks for the fast help!

**Comment by ruslo** [comment]
@tatraian Glad it helps :)
