### ISSUE TITLE
Automatic hunter download fails with "Protocol "https" not supported or disabled in libcurl"

### ISSUE THREAD

**Issue by Knitschi** [ruslo/hunter#328]
This probably not a problem of hunter but of my linux (Debian) configuration but maybe someone here has an idea how to solve the problem. I have not much experience with linux.

Typing
$ curl --version
yields
````
curl 7.47.1 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1k zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP 
````
so https support should be there. Any ideas?
calling wget for the same tar.gz file works by the way.

Here is more lengthy error output from cmake
````
SourceCode
-- [hunter *** DEBUG *** 2016-02-19T20:23:39] HUNTER_ROOT detected by environment variable
-- [hunter *** DEBUG *** 2016-02-19T20:23:39] HUNTER_ROOT: /home/knitschi/CppLibraries/HunterRoot
-- [hunter *** DEBUG *** 2016-02-19T20:23:39] Locking directory: /home/knitschi/CppLibraries/HunterRoot/_Base/Download/Hunter/0.12.45/a1d363c
-- [hunter *** DEBUG *** 2016-02-19T20:23:39] Lock done
-- [hunter *** DEBUG *** 2016-02-19T20:23:39] Run generate
-- Configuring done
-- Generating done
-- Build files have been written to: /home/knitschi/CppLibraries/HunterRoot/_Base/Download/Hunter/0.12.45/a1d363c/Build
-- [hunter] Initializing Hunter workspace (a1d363c7ffb324eb55a410715868ada32e595622)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.12.45.tar.gz
-- [hunter]   -> /home/knitschi/CppLibraries/HunterRoot/_Base/Download/Hunter/0.12.45/a1d363c
Scanning dependencies of target Hunter
[ 12%] Creating directories for 'Hunter'
[ 25%] Performing download step (download, verify and extract) for 'Hunter'
-- downloading...
     src='https://github.com/ruslo/hunter/archive/v0.12.45.tar.gz'
     dst='/home/knitschi/CppLibraries/HunterRoot/_Base/Download/Hunter/0.12.45/a1d363c/v0.12.45.tar.gz'
     timeout='none'
CMake Error at Build/Hunter-prefix/src/Hunter-stamp/download-Hunter.cmake:27 (message):
  error: downloading
  'https://github.com/ruslo/hunter/archive/v0.12.45.tar.gz' failed

    status_code: 1
    status_string: "Unsupported protocol"
    log: Protocol "https" not supported or disabled in libcurl

  Closing connection -1

  



CMakeFiles/Hunter.dir/build.make:89: recipe for target 'Hunter-prefix/src/Hunter-stamp/Hunter-download' failed
make[2]: *** [Hunter-prefix/src/Hunter-stamp/Hunter-download] Error 1

```

**Comment by ruslo** [comment]
What CMake version are you using? Does CMake built from sources?

**Comment by Knitschi** [comment]
I will report more on this when I go back to building on linux. I currently need to fix my Windows build.

**Comment by Knitschi** [comment]
So now I am back at the problem. I am using cmake 3.3.0 on a Debian machine. I can not really remember how I got cmake, but I think I did not build it from source but rather used ```apt-get install cmake```. But as I said I do not really remember.

**Comment by ruslo** [comment]
> I can not really remember how I got cmake

Hint for the future: if you building it yourself never install it in default system location, system package manager will be confused.

If you want to try to build it from sources add `CMAKE_USE_SYSTEM_CURL=YES` to configuration step.

> I am using cmake 3.3.0 on a Debian machine

If you're sure that CMake installed by system package manager try to do `update`/`upgrade` step and if it will not help I think there is no choice - you should open bug report.

**Comment by Knitschi** [comment]
I solved the problem by exchaning the downloaded packages cmake and curl with self-compiled versions.
First I removed cmake and curl
````
$ sudo apt-get remove cmake
$ sudo apt-get remove curl
````
Then I downloaded the curl source code from here: https://curl.haxx.se/download.html
Compiled the curl with
````
/CurlExtractFolder$ ./configure --with--ssl
/CurlExtractFolder$ make
/CurlExtractFolder$ sudo make install
````
Then I cloned the git repository of CMake to CMakeExtractFolder and build it with
````
/CMakeExtractFolder$ ./bootstrap --system-curl
/CMakeExtractFolder$ make
/CMakeExtractFolder$ sudo make install
````
Now it worked.

**Comment by ruslo** [comment]
> Now it worked

Good to know. Thanks for sharing this info.

**Comment by mirandole** [comment]
@Knitschi It was very helpful to install cpp-ethereum. Thank you

**Comment by awilliamson** [comment]
@Knitschi Fantastic! Absolutely solved an issue I was having with ethereum/cpp-ethereum also!

**Comment by daichunkai** [comment]
Great，Thank you ！ @Knitschi

**Comment by benwiley4000** [comment]
@Knitschi thanks so much! I'm not sure reinstalling curl was actually necessary, but I'd already tried to build curl from source after I'd convinced myself there was really a curl-specific problem (even though I kept telling myself there wasn't)... so I appreciate you including those instructions as well. :smile:

**Comment by lehathanh** [comment]
@Knitschi I tried to build ethminer from scratch by installing everything from beginning but only not using --system-curl for cmake. It turned out that cmake could not download hunter package while building ethminer. Even if I managed to bypass this step, the building got stuck at [BOOST_ROOT] without any error message and made me go to nowhere!
Checking with your solution, I tried :

$ ./bootstrap --system-curl

And it worked! 
Thank you so much! I appreciate your detail and easy to understand instruction!

**Comment by OhGodADog** [comment]
> 
> 
> @Knitschi I tried to build ethminer from scratch by installing everything from beginning but only not using --system-curl for cmake. It turned out that cmake could not download hunter package while building ethminer. Even if I managed to bypass this step, the building got stuck at [BOOST_ROOT] without any error message and made me go to nowhere!
> Checking with your solution, I tried :
> 
> $ ./bootstrap --system-curl
> 
> And it worked!
> Thank you so much! I appreciate your detail and easy to understand instruction!

Confirming, tried on Ubuntu 14, with compiled verison of CMake, re-compiling with only the CMake with --system-curl fixes the issue.

**Comment by swappart** [comment]
Thank you @Knitschi I've been trying for 3 days to get CMake to work with curl. I knew curl was working with SSL, because I tested it. I had no idea CMake used it's own install.
