### ISSUE TITLE
Add 'benchmark' (gbenchmark) package

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#332]
##

**Comment by ruslo** [comment]
Note: CMake based

**Comment by yowidin** [comment]
I plan to implement this package but `benchmark` is very generic name. Any suggestions on a better one? `GBenchmark`, `google-benchmark`?

**Comment by ruslo** [comment]
as far as I can see user need to include `benchmark/benchmark.h`, so it's okay to name it `benchmark`

**Comment by ruslo** [comment]
WIP: https://github.com/ruslo/hunter/pull/672

**Comment by ruslo** [comment]
GitHub: https://github.com/google/benchmark

**Comment by isaachier** [comment]
Did this in #1088. Can be close.
