### ISSUE TITLE
Add libsodium package

### ISSUE THREAD

**Issue by Cyberunner23** [ruslo/hunter#335]
https://github.com/jedisct1/libsodium

Note: Non-CMake based

**Comment by novocodev** [comment]
I'm trying to port [libsodium-CMake](https://github.com/novocodev/libsodium-CMake.git) to [hunter](https://github.com/novocodev/hunter/pull/1).

Following the `Adding New Package` Wiki, I have successfully completed up to:

`Test it using ExternalProject_Add`

When I then try to use lib sodium in my project I get a build error that I can't figure out.

This is what I changed in my projectCMakeLists.txt

```
HunterGate(
        URL "https://github.com/novocodev/hunter/archive/v0.13.12.tar.gz"
        SHA1 "ef7d49370ca03acad734c6da55545d6b109851e5"
)

hunter_add_package(libsodium)
```

The build fails because it tries to run ./configure but there is no configure file. I can't figure out is whats triggering that call. I have attached the project build log.
[log.txt](https://github.com/ruslo/hunter/files/181250/log.txt)

**Comment by ruslo** [comment]
> I'm trying to port libsodium-CMake to hunter

So this is CMakefied version of libsodium? Does build works with CMake? If so you just need to change your build scheme to `url_sha1_cmake.cmake`.

**Comment by ruslo** [comment]
> The build fails because it tries to run ./configure but there is no configure file

Yep, I'm sure that is the main defect, no more no less :) Autotools scheme expects `configure` script at top. What is the official build instructions?

**Comment by ruslo** [comment]
> I'm trying to port libsodium-CMake

For your information here is a repository for forked hunterized projects:
* https://github.com/hunter-packages

I've made a fork:
* https://github.com/hunter-packages/libsodium

@novocodev I've added you to the `libsodium` team, check your email. You have permissions to push directly but I recommend you to create pull requests anyway for review reasons. Also please keep upstream branches like `master` clean so anybody can merge it with just `--ff-only` option. Use `hunter` branch for patches (this is default branch now). Thanks.

**Comment by novocodev** [comment]
@ruslo, I'll copy over to the fork once I have this fully working.

Thanks for the scheme pointer, I started with a copy from another package that was't CMake based.

I have a new error now generated from this line in my project CMakeLists.txt

`find_package(libsodium CONFIG REQUIRED)`

Error:

```CMake Error at CMakeLists.txt:30 (find_package):
  Could not find a package configuration file provided by "libsodium" with
  any of the following names:

    libsodiumConfig.cmake
    libsodium-config.cmake
```

These config files look like they should be generated as part of the build, but not sure what would control this.

I have attached the [build log](https://github.com/ruslo/hunter/files/181395/log.txt)

**Comment by ruslo** [comment]
> These config files look like they should be generated as part of the build

Yes, as part of the install step to be precise.

> but not sure what would control this

Usually I do copy/paste this part of code:
* https://github.com/forexample/package-example/blob/cf2ea1d6a209fb9eca2ab83fdd0ac15fe4d3e807/Foo/CMakeLists.txt#L64

and it just works.

**Comment by Cyberunner23** [comment]
> What is the official build instructions?

The official instructions demands ./autogen.sh to be run before doing ./configure (autogen will make the ./configure). Essentially it runs

    if [ -x "`which autoreconf 2>/dev/null`" ] ; then
      exec autoreconf -ivf
    fi
    
    $LIBTOOLIZE && \
    aclocal && \
    automake --add-missing --force-missing --include-deps && \
    autoconf

$LIBTOOLIZE being either glibtoolize or libtoolize which ever it finds on the system.
It also checks if automake and autoconf is present on the system.


Also I see that the libsodium-CMake is a fork of my attempt to make a CMake build system for libsodium. I would in fact suggest to not use it because updating it is quite a pain. Looking at the autotools build system and figuring out what was added and then make the necessary changes in the CMake file is quite a lengthy and treacherous process. Unless you want to do maintain such a fork I would rather suggest using the autotools schema but calling ./autogen.sh right before ./configure somehow and also perhaps create a schema for MSBuild (Can use that to build libsodium on windows, it would also be useful for other projects that can use MSBuild to be incorporated into the hunter packaging system).


>    find_package(libsodium CONFIG REQUIRED)

This will not work with my CMake build system because it needs to have extra bits that will allow find_package to be used in CONFIG mode. I don't have these bits of code in my CMake file because I made it way before I was aware of this feature.

**Comment by ruslo** [comment]
> I would in fact suggest to not use it because updating it is quite a pain

Figuring out all peculiarities of autotools and emulating CMake behaviour for Android/iOS + imported targets is not a trivial task too so if project doesn't use compex structure of components like Qt or Boost it may worth to add CMakeLists.txt and emulate autotools behaviour.

> Looking at the autotools build system and figuring out what was added and then make the necessary changes in the CMake file is quite a lengthy and treacherous process

Does the build system changes a lot? I expect most of the changes happens in sources (no need to update) or new sources added (trivial update). No?

**Comment by Cyberunner23** [comment]
The build system does not change that much but it does change from time to time. Also, I was wondering, What if instead of recreating the whole autotools build system in CMake, just use ExternalProject in it, add the bits to make it work with find_package in CONFIG mode. So instead of having an extra schema for hunter to do it, the CMake file will build the library with the autotools and MSBuild build systems essentially offloading the autotools and its extra step out of hunter into the library itself. I think this would greatly simplify the CMake build system and make it easier to maintain because there will be no need to update it when the build other build systems update. What do you think?

**Comment by ruslo** [comment]
> What do you think?

I think it is quite the same. Also if you have several similar projects then using Hunter is more optimal. Say you have A, B, C using `autoreconf` + `MSBuild`. So you have to create `ExternalProject` with such settings 3 times. Why not create one build scheme in Hunter and use it for A, B and C?

**Comment by Cyberunner23** [comment]
Makes sense, we could create a build scheme for MSBuild and autotools with the autogen.sh however I'm wondering what we should do, make the build schemes or continue with the CMake file?

**Comment by ruslo** [comment]
> make the build schemes or continue with the CMake file?

Depends on you - I only can describe all pros and cons. Personally since I hope that it in very far future all projects will use CMake as a build system I vote for migrating to CMake.

**Comment by Cyberunner23** [comment]
I vote for making schemes actually, I do love CMake but I honestly don't think that every project will be using CMake in the future, people have different needs/tastes so I think there will always be mess in terms of build systems (unless the C++ committee makes CMake as the official build system, and even then...). I do hope to be wrong though, I really like CMake.

**Comment by ruslo** [comment]
> I vote for making schemes actually

I'm okay with it.

**Comment by novocodev** [comment]
@Cyberunner23 I have been using your libsodium-CMake for a while with CPPCPM package manager.

I'm moving my project over to polly/hunter, CMake is still a learning curve for me so I decided to port what was already working. I have no preference for a long term hunter solution, I'm happy to help with/test another solution.

**Comment by novocodev** [comment]
I have a working libsodium package, that exports public headers and links to my parent project.

Still a WIP.

I have one question, for IOS builds I have set `XCODE_ATTRIBUTE_ENABLE_BITCODE YES` in my top level project.

Prior to adding a dependency on libsodium package my library would build with bit code enabled, Boost was linked in without error and I could use the Generated framework in Xcode with Bitcode enabled.

My libsodium package generates a link error because libsodium.a does not have bitcode enabled. How should I propagate the `XCODE_ATTRIBUTE_ENABLE_BITCODE YES` to the libsodium dependency package?

```
ld: '/Users/dev/projects/huntergate/_Base/9f2c645/7cdace2/5932ef3/Install/lib/liblibsodium.a(crypto_box.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I set `XCODE_ATTRIBUTE_ENABLE_BITCODE NO` then libsodium is linked to the top level project and I can pull the Framework into Xcode with Bitcode disabled.

**Comment by ruslo** [comment]
> for IOS builds I have set XCODE_ATTRIBUTE_ENABLE_BITCODE YES in my top level project

Was set to `NO` in Polly toolchains:
* https://github.com/ruslo/polly/blob/27eca517d26cf05887e61a15beedf9ef22627c34/os/iphone.cmake#L149

This is because it breaks old code.

Does `XCODE_ATTRIBUTE_ENABLE_BITCODE` affect compiling stage, i.e. extra flag added to compiler? This is important on how it will be visible by toolchain-id calculation module.

> How should I propagate the XCODE_ATTRIBUTE_ENABLE_BITCODE YES to the libsodium dependency package?

Should be done in toolchains:
* move old code `..._ENABLE_BITCODE NO` to the `flags` directory
* load `flags/enable-bitcode.cmake` in old toolchains
* load `flags/disable-bitcode.cmake` in new toolchains (new name `ios-9-2-bitcode`)

**Comment by Cyberunner23** [comment]
@novocodev Is this still being worked on? or should I work on the scheme based option I was thinking about?

**Comment by novocodev** [comment]
@Cyberunner23 I have been using my [fork](https://github.com/novocodev/libsodium-CMake.git) in my project, but there may be issues that I have not found. After going through the porting exercise I would agree that the scheme based approach will be easier to maintain for new releases of libsodium.

**Comment by Cyberunner23** [comment]
libsodium merged, one slight bug we found after the fact to fix, should be complete soon

**Comment by Cyberunner23** [comment]
Ohh and before I forget, new wiki page https://github.com/ruslo/hunter/wiki/pkg.libsodium

**Comment by Cyberunner23** [comment]
Fix merged in, everythig is working, closing
