### ISSUE TITLE
Add ZMQPP package

### ISSUE THREAD

**Issue by tatraian** [ruslo/hunter#338]
ZMQPP package is a C++ front-end for ZeroMQ. Please create a hunter-packages repository for it
(https://github.com/zeromq/zmqpp) and I commit the changes that required for hunter compiling. After I will come with hunter pull request.
I don't have Windows compiler currently I could test it only on Linux.
##

**Comment by ruslo** [comment]
> Please create a hunter-packages repository

Done: https://github.com/hunter-packages/zmqpp
