### ISSUE TITLE
How can I verify that my qt libraries are really linked dynamicly

### ISSUE THREAD

**Issue by Knitschi** [ruslo/hunter#345]
I use the qt package with Visual Studio 2013 and I use the config

````
hunter_config(
    Qt 
    VERSION 5.5.1-cvpixelbuffer-2-p1
    CMAKE_ARGS BUILD_SHARED_LIBS=ON
)
````
in order to use dynamic linkage for the qt libraries.
But I don't think that this worked because the hunter package does not seem to contain any dlls, just libs. The bin folder only contains executables.

Did I do anythin wrong or is it not working? I included the Qt package with:

````
set( HUNTER_STATUS_DEBUG ON)
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.12.45.tar.gz"
    SHA1 "a1d363c7ffb324eb55a410715868ada32e595622"
    LOCAL
)

hunter_add_package(Qt)

# Find includes in corresponding build directories
set(CMAKE_INCLUDE_CURRENT_DIR ON)

# Instruct CMake to run moc automatically when needed.
set(CMAKE_AUTOMOC ON)

# Find the Qt libraries
find_package(Qt5Core REQUIRED)
find_package(Qt5Widgets REQUIRED)
find_package(Qt5Gui REQUIRED)
find_package(Qt5Test REQUIRED)
````

**Comment by ruslo** [comment]
Can you add build logs please.

**Comment by sumedhghaisas** [comment]
You can also check if .dll files of Qt are present in your hunter install folder. .dll files on windows are put in 'bin' folder of your hunter install folder.

**Comment by Knitschi** [comment]
Must have been some error on my side. I deleted the hunter libraries, recompiled and now I have the dlls in place. Sorry for taking your time.
