### ISSUE TITLE
Add FFMPEG package

### ISSUE THREAD

**Issue by liupengking1** [ruslo/hunter#347]
Add FFMPEG package, build shared libraries.
##

**Comment by ruslo** [comment]
Can you provide sources/github forks?

**Comment by liupengking1** [comment]
https://github.com/FFmpeg/FFmpeg 	
version n3.0 would be good, thanks!

**Comment by ruslo** [comment]
Okay, thank. Looks like it doesn't use CMake as a build system. It might be useful if you find CMake-filed forks.

**Comment by liupengking1** [comment]
Sorry I didn't have luck to find a CMake-filed fork either. I tried using ExternalProject_Add to build it in my project but find it seems too much hassle to manage its dependencies. Thats why I am searching for a package manager for cmake.

**Comment by ruslo** [comment]
> Sorry I didn't have luck to find a CMake-filed fork either

If project is relatively simple it make sense to start new one.

Alternatively you can create custom build scheme. There are some tools that helps you to automate process:
* [hunter_autotools_project](https://github.com/ruslo/hunter/blob/506379a1405d44327bc6fc6b3fc7e96191cf1967/cmake/modules/hunter_autotools_project.cmake)
* Usage example: [odb-sqlite](https://github.com/ruslo/hunter/blob/506379a1405d44327bc6fc6b3fc7e96191cf1967/cmake/schemes/url_sha1_odb-sqlite_autotools.cmake.in)

You can contact @pretyman for discussion. He created this awesome module and actively using it.

> I tried using ExternalProject_Add to build it in my project but find it seems too much hassle to manage its dependencies

Just for your information we should add dependencies first, so feel free to open package requests and mention them as a dependency for this package.

**Comment by ruslo** [comment]
Version:
- https://github.com/ruslo/hunter/commit/8fa7e22fad28a7af0bf4c2fcbb8a44ce15c30cdd

Docs:
- https://docs.hunter.sh/en/latest/packages/pkg/ffmpeg.html

Supported platforms at this moment:
- https://travis-ci.org/ingenue/hunter/builds/522735212

Released:
- https://github.com/ruslo/hunter/releases/tag/v0.23.157
