### ISSUE TITLE
How to satisfy dependency on Boost 1.60.0

### ISSUE THREAD

**Issue by novocodev** [ruslo/hunter#348]
I have a dependency on Boost 1.60.0.

Using 

HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.13.1.tar.gz"
    SHA1 "bd7711df37a53134e642220d2f649a69cb34dde3"
)

and 

# download boost
hunter_add_package(Boost)

I think it's pulling in Boost 1.57.0.

Is there is away to force Boost 1.60.0 to be pulled instead.

**Comment by ruslo** [comment]
As you may notice Boost 1.60 is not listed in available versions:
* [cmake/projects/Boost/hunter.cmake](https://github.com/ruslo/hunter/blob/0ec6fccd1ba1dd20f34a2123dad5fc1a89ee137a/cmake/projects/Boost/hunter.cmake)

so first somebody have to add it.

As mentioned [here](https://github.com/ruslo/hunter/pull/299#issuecomment-188213546) 1.59 and 1.60 versions ready:
* [boost/releases](https://github.com/hunter-packages/boost/releases).

You just need to calculated SHA1 of archives and contribute it.

**Comment by novocodev** [comment]
I got this working locally by adding the following to Boost/hunter.cmake

```
hunter_add_version(
    PACKAGE_NAME
    Boost
    VERSION
    "1.60.0"
    URL
    "https://github.com/hunter-packages/boost/archive/v1.60.0.tar.gz"
    SHA1
    28a5b0f739114fde5d4ed1d7f52e5b6cf13fe54a
)
```

and updating configs/default.cmake with

```
hunter_config(Boost VERSION 1.60.0)
```

Do you want me to create a PR? This change is likely to conflict with PR linked above.

**Comment by ruslo** [comment]
> Do you want me to create a PR?

Of course! Please add 1.59 to `hunter.cmake` too (leave 1.60 in `configs/default.cmake`).

**Comment by novocodev** [comment]
Created Pull Request #351

**Comment by ruslo** [comment]
> Created Pull Request #352

Merged. Closing.
