### ISSUE TITLE
OpenCV 3.x with Qt back-end support

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#349]
Hi Ruslan,

It would be great if there was a way to enable the Qt back-end for OpenCV, since it enables various tools when developing on the desktop. The instructions that I found were in: https://cvisionnotes.wordpress.com/2015/09/27/build-opencv-with-qt/ however I could not figure out how to set the variables in the current hunter project design. What would you suggest? Instructions I copied below:

### Build OpenCV with Qt Backend Support:
This note describes how to build and install OpenCV 3.0 to OS X Yosemite. In order to buil Qt Backend support, we will take some actions in step 5 of the Preparation phase.

1) In CMake GUI, find and check WITH_QT. Hit [Configure]
2) Set values as follows:
```
QT_QMAKE_EXECUTABLE = /opt/local/libexec/qt5-mac/bin/qmake
Qt5Concurrent_DIR = /opt/local/libexec/qt5-mac/lib/cmake/Qt5Concurrent
Qt5Core_DIR = /opt/local/libexec/qt5-mac/lib/cmake/Qt5Core
Qt5Gui_DIR = /opt/local/libexec/qt5-mac/lib/cmake/Qt5Gui
Qt5Test_DIR = /opt/local/libexec/qt5-mac/lib/cmake/Qt5Test
Qt5Widgets_DIR = /opt/local/libexec/qt5-mac/lib/cmake/Qt5Widgets
```
3) Hit [Configure]

4) Set another value, if being asked
```
QT5OpenGL_DIR = /opt/local/libexec/qt5-mac/lib/cmake/Qt5OpenGL
```
5) Hit [Configure] and then [Generate]

**Comment by ruslo** [comment]
> however I could not figure out how to set the variables in the current hunter project design. What would you suggest?

As far as I understand all you need to do is to hunterize OpenCV:
* https://github.com/hunter-packages/opencv

i.e. find a place where Qt used and add `hunter_add_package(Qt)`.

Then enabling Qt will be trivial:
```
hunter_config(
    OpenCV
    VERSION "${HUNTER_OpenCV_VERSION}"
    CMAKE_ARGS WITH_QT=YES
)
```

**Comment by pretyman** [comment]
How should there be any changes in `project/OpenCV/hunter.cmake` to add Qt in there? How will the build order be guaranteed to build Qt first, to then have OpenCV as its dependencies?

**Comment by ruslo** [comment]
> How should there be any changes in project/OpenCV/hunter.cmake to add Qt in there?

Mainly not in `OpenCV/hunter.cmake` but in OpenCV sources. Then new patched OpenCV version will be placed into `OpenCV/hunter.cmake`.

> How will the build order be guaranteed to build Qt first, to then have OpenCV as its dependencies?

As usual. First build of OpenCV will be triggered, then when `hunter_add_package(Qt)` of OpenCV is reached we will run `Qt` build.

**Comment by pretyman** [comment]
Ok, I will do this in 2 steps: first update OpenCV to 3.1.0, the add the Qt backend. 

I need to send https://github.com/pretyman/opencv/tree/hunter-3.1.0 to I guess I'll need write access for that, or maybe there is some other way to get this branch there?

**Comment by ruslo** [comment]
> to I guess I'll need write access

You have now

**Comment by pretyman** [comment]
> You have now
Thanks, but I see you created the branch, so I guess I can send normal pull requests as usual.

Should a tag be created for 3.1.0 so I can refer it from `cmake/projects/OpenCV/hunter.cmake`? I would guess so, and should be its name? All, but one, patch from 3.0.0 got rebased, so what should be the tag name?

Looks like `OpenCVConfig.cmake` does not do the `find_package(Qt5Widgets)` and other dependencies, it only adds the targets to the link libraries, hence when compiling `examples/OpenCV` it fails with 
```
-- Configuring done
CMake Error at CMakeLists.txt:19 (add_executable):
  Target "foo" links to target "Qt5::Core" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
(...) plus other Qt5 packages
```

I guess I should fix `OpenCVConfig.cmake` in OpenCV instead of creating a new `FindOpenCV.cmake` for Hunter, correct?

**Comment by ruslo** [comment]
> Should a tag be created for 3.1.0 so I can refer it from cmake/projects/OpenCV/hunter.cmake?

If this is for next version 3.1.0 then yes. I see that there is no branch `3.1` upstream, they just use `master`. So pull all changes `--ff-only` to `master`, then create branch `hunter-3.1.0` and cherry-pick (or rebase) all hunterization commits.

> I guess I should fix OpenCVConfig.cmake in OpenCV instead of creating a new FindOpenCV.cmake for Hunter, correct?

Yep. There should be some variables describing the fact that Qt is used in OpenCV so OpenCVConfig.cmake.in should use them to generate conditions for `find_package` (or [find_dependency](https://cmake.org/cmake/help/v3.5/module/CMakeFindDependencyMacro.html)).

Will looks like this (have no idea about variable/file names, just mythical example!):
```cmake
# OpenCV/CMakeLists.txt
if(WITH_QT)
  find_package(QtWidgets REQUIRED)
  target_compile_definitions(... PUBLIC WITH_QT=1)
endif()
```

```cmake
# OpenCVConfig.cmake.in
if(@WITH_QT@)
  find_package(QtWidgets REQUIRED)
endif()
```

**Comment by pretyman** [comment]
> I see that there is no branch 3.1

They don't have a branch, but they do have a tag: https://github.com/Itseez/opencv/tree/3.1.0 . I used this tag to rebase the hunter patches.

> Will looks like this

Ok, thanks for the support, working on it

**Comment by ruslo** [comment]
As far as I understand we are done here (?)
