### ISSUE TITLE
Best way to copy shared libraries of packages to the binary output folder?

### ISSUE THREAD

**Issue by Knitschi** [ruslo/hunter#354]
I am using the Qt package build as shared libraries. Now I have the problem that I need somehow to copy the dlls to the folder of the executable. What is the best way to do that?

I hit two problems.
1. Qt uses internally the qwindows.dll which must be located in a /platforms subfolder. I can get the locations of the primary Qt dlls with the ```get_property(... LOCATION )``` command but I do not know how I can get the location of the qwindows.dll. Is there a way to recursively get all the dependencies of the dependencies?
2. All the instructions that I can find about copying files use post build commands or custom targets. I would rather copy the files at cmake-time. Is that possible?

I know that this is not really a hunter problem but you guys seem to have deep cmake knowlege and you probably have a solution already up your sleeve.

**Comment by ruslo** [comment]
> What is the best way to do that?

This is a job for [fixup_bundle](https://cmake.org/cmake/help/latest/module/BundleUtilities.html) function. The last time I've tried it has some errors so I have to apply workarounds. Take a look at this example: https://github.com/forexample/qt-cmake/blob/master/TextFinder/CMakeLists.txt

**Comment by Knitschi** [comment]
thanks for the hint.

**Comment by ruslo** [comment]
> thanks for the hint.

Closing.
