### ISSUE TITLE
Sources for projects compiled with Debug symbols

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#359]
Hi Ruslan,

As I understand Hunter created Debug and Release builds of CMake packages, such a OpenCV. In my Xcode project, generated with `cmake -G Xcode`, I see that the Debug versions of the libraries are getting linked, but when I step into OpenCV code, I cannot see the source because I believe they are deleted after compilation.

Is there any way to keep the source of Debug builds? Debug builds become much more useful when it is possible to navigate through them.

Thanks
##

**Comment by ruslo** [comment]
> I cannot see the source because I believe they are deleted after compilation

Yes, they are.

> Is there any way to keep the source of Debug builds?

Actually I don't know what is the right way to do it. If you have any suggestions please share. Question is about where to store them, i.e. should they need to be installed near the debug libraries and how paths will be corrected + how it will work for different platforms.

> Debug builds become much more useful when it is possible to navigate through them

Sure :) But just for the record it is not the only thing which is useful. Since `NDEBUG` is disabled in `Debug` builds - `assert` works, which may run some important but costly checks. Also if your Debug and Release version of executable behaves differently then probably you have to check that there is no UB in your code, like strict aliasing rule violation.

**Comment by pretyman** [comment]
**lldb** [ for OSX mostly, I guess] would require a `. lldbinit` file with contents along the lines of: 
```
settings set target.source-map <old-build-directory>/Build <root-id>/Install
``` 
in its project directory [ Xcode needs the plugin https://github.com/alloy/lldb-is-it-not for this to work ]. Information from [stackoverflow]( http://stackoverflow.com/questions/12973633/lldb-equivalent-of-gdb-directory-command-for-specifying-source-search-path)

**gdb** would require a .gdbinit file in the debugging directory with:
```
set substitute-path <old-build-directory>/Build <root-id>/Install
```
Source: https://sourceware.org/gdb/onlinedocs/gdb/Source-Path.html

This seems to be *kind of* toolchain related. Since the toolchain.cmake is run first thing in CMake, would be cool to have a debugger.cmake that ran last :> 

I'm aware CMake is designed just to build. So would be cool is hunter offered a way to aid the debugging the libraries it controls. 

Sad thing is that I can't think of a way to do this in a per project's CMakeLists.txt basis by calling a function at the end like `hunter_fix_debugger_paths()`. 

We would have to save the original Install paths, and use it to fill in the source path substitution.

**Comment by ruslo** [comment]
> This seems to be kind of toolchain related

For the start it's not related neither to toolchain nor to package management. If you don't mind I will open CGold issues for saving general information and examples:

* https://github.com/ruslo/CGold/issues/6
* https://github.com/ruslo/CGold/issues/7

> Sad thing is that I can't think of a way to do this in a per project's CMakeLists.txt basis by calling a function at the end like hunter_fix_debugger_paths(). 

No, it's not an option.

> We would have to save the original Install paths, and use it to fill in the source path substitution.

Similar to PACKAGE_UNRELOCATABLE_TEXT_FILES?

**Comment by alamaison** [comment]
FWIW this is also an issue with visual studio. The linker prints hundreds
of warnings because it can't find the PDBs

**Comment by ruslo** [comment]
> The linker prints hundreds of warnings because it can't find the PDBs

Yep, I've seen that too but I think this actually can already be handled by CMake. Anyway let's start with the general stuff here just like with the previous problems: https://github.com/ruslo/CGold/issues/8

**Comment by pretyman** [comment]
> For the start it's not related neither to toolchain nor to package management. 

I agree, however on second thoughts, hunter's cache mechanism is the feature which relocates the packages, hence making the source path invalid if sources were kept

**Comment by ruslo** [comment]
> hence making the source path invalid if sources were kept

Not exactly. Sources is not kept, it's true, but even if they will be kept the full path to sources is not the same for the remote machine where package is built and local machine where they used. You should built everything from scratch and keep source directory.

**Comment by ruslo** [comment]
Variable [HUNTER_KEEP_PACKAGE_SOURCES](https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-keep-package-sources) can be used as a workaround for now. Available since [v0.18.22](https://github.com/ruslo/hunter/releases/tag/v0.18.22) release.

**Comment by pretyman** [comment]
Thanks for the workaround Ruslan, live is worth living once again :+1:

**Comment by ruslo** [comment]
Closing inactive discussion.
