### ISSUE TITLE
Add GLEW package

### ISSUE THREAD

**Issue by USADavid** [ruslo/hunter#360]
https://github.com/nigels-com/glew
uses cmake

**Comment by pretyman** [comment]
@headupinclouds Hey, I see there is a https://github.com/hunter-packages/GLEW with an uppercase name, that is the status on this? I am working on putting version 2.0.0 of glew - although I have not tested my app with version 2.0.0, I could end up adding a previous version.

@ruslo 
Should we take the opportunity that this package is not yet in hunter and rename it for lower case?

**Comment by ruslo** [comment]
> I see there is a https://github.com/hunter-packages/GLEW with an uppercase name, that is the status on this?

As far as I understand this code is taken from Urho3D. I moved it to https://github.com/hunter-packages/glew-old.

I fork official GitHub repo: https://github.com/hunter-packages/glew. We need to add top level CMakeLists.txt so it will be ExternalProject_Add friendly and add installation of export files. They have one but it's done not so nicely as it might be, see https://github.com/hunter-packages/GLEW-old/blob/master/CMakeLists.txt.

**Comment by ruslo** [comment]
Fixed https://github.com/ruslo/hunter/pull/488
