### ISSUE TITLE
How to get include directories that are injected by config.cmake.in based packages?

### ISSUE THREAD

**Issue by Knitschi** [ruslo/hunter#369]
When I link to a hunter library that is found with the _config mode_ of ```find_package( ... REQUIRED )``` for example Qt5::Core, then the needed include directories get somehow injected into my library Foo and it will find includes like ```#include <QString>```. This is all nice and good but...

In order to solve some other problem I now need access to the names of the include directories and I do not know how to get it. For the formerly used _module mode_ packages I could call ```get_target_property( incDirs TARGET Foo PROPERTY INCLUDE_DIRECTORIES)``` but with the _config mode_ packages this will not return the Qt-Directories. Does anybody of you know how I can get the names of the directories?

**Comment by ruslo** [comment]
> For the formerly used module mode packages I could call get_target_property( incDirs TARGET Foo PROPERTY INCLUDE_DIRECTORIES)

Same same. But property called [INTERFACE_INCLUDE_DIRECTORIES](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_INCLUDE_DIRECTORIES.html). Also just for your information after `hunter_add_package` command new variable `QT_ROOT` will be added to the scope. Note that it's Hunter specific, e.g. will not work when [HUNTER_ENABLED](https://github.com/ruslo/hunter/wiki/usr.variables#hunter_enabled) if `OFF`.

**Comment by Knitschi** [comment]
Thanks! This helps.
