### ISSUE TITLE
installing thirdparty library

### ISSUE THREAD

**Issue by tatraian** [ruslo/hunter#376]
Maybe this is an already solved problem just I didn't find the solution in wiki.

I have a project with several libraries built by hunter. I can link my libraries to them by during install only my target will be installed and not the thirdparties.

How can I install the dependencies of my target (with recursion if it is possible).

**Comment by alamaison** [comment]
By default, the third-party libraries are statically linked into your project.  You don't need to install them.

**Comment by ruslo** [comment]
@tatraian Take a look at this feature request: https://github.com/ruslo/hunter/issues/274 Is this look the same? Will it help?

@alamaison That's true for executable but not if you're building library (both shared and static by the way). E.g. I have library `Foo` that depends on `Boost` and `OpenSSL` from Hunter. When I install it to custom location only `libFoo.a` is installed but I need to find `libboost_*.a` and `libcrypto.a` too. As far as I understand this is a scenario of distributing dependencies without Hunter, of course it's not a problem when you delegate this job to Hunter.
