### ISSUE TITLE
Relocatable .pc files

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#377]
While trying to fix https://github.com/ruslo/hunter/issues/375 I hit the problem with non-relocatable `*.pc` files, i.e. path to package is hardcoded there. Does anybody know how to make all paths in `*.pc` relative to the current directory?

@pretyman I remember you have some similar problems before. What is your experience?

Not related directly to relocation problems but I've found some information that might be useful:
* https://cmake.org/pipermail/cmake/2008-November/025050.html

We should clean `PKG_CONFIG_PATH` and `PKG_CONFIG_LIBDIR` and prefer `PKG_CONFIG_LIBDIR` in [autotools helper module](https://github.com/ruslo/hunter/blob/e1b531364272aa7d6ca4f23b490b503d23cc6486/cmake/modules/hunter_autotools_project.cmake#L267) (?)

**Comment by ruslo** [comment]
Have no idea now does it relates to the problem or not, just for the record:
* http://patchwork.ozlabs.org/patch/595275/

**Comment by ruslo** [comment]
> We should clean PKG_CONFIG_PATH and PKG_CONFIG_LIBDIR

See:
* https://github.com/ruslo/hunter/pull/378

**Comment by pretyman** [comment]
I recall having similar problems with libtool `*.la` files, and they needed absolute paths in them, as libtool did not allow relative paths inside of its `.la` files. This was described in https://github.com/ruslo/hunter/issues/218 . I don't know pkg-config, but it seems to suffer from a similar problem.

Your solution of cleaning the vars is the best.

**Comment by ruslo** [comment]
> This was described in #218

Okay, thanks for the reference I lost it :) So effectively I've implemented this approach: https://github.com/ruslo/hunter/issues/218#issuecomment-130233161 but with different variable names. Will substitute names for something more general.

**Comment by ruslo** [comment]
Fixed by: https://github.com/ruslo/hunter/commit/e3430ac72142d4f2914e7e0b885287ab54e50091
