### ISSUE TITLE
huntergate url and cmake https downloads

### ISSUE THREAD

**Issue by regnirpsj** [ruslo/hunter#380]
looks like that the standard cmake on the ubuntu container at travis-ci does not support https protocol (see build error at the end of https://travis-ci.org/regnirpsj/hugh-support/jobs/121972917). i even tried forcing `http://...` but github redirects all requests. local tests with `curl` indicate that github's server has a policy enforcing `https://...` protocol.
https://stackoverflow.com/questions/29816529 describes a similar problem and a possible solution: using `DOWNLOAD_COMMAND wget https:...` within the `ExternalProject_Add()` function. this should probably be done only if the original `ExternalProject_Add()` call does not succeed (and the result indicates a protocol problem, though i've no idea if that kind of information would be available).

**Comment by ruslo** [comment]
> using DOWNLOAD_COMMAND wget https:... within the ExternalProject_Add() function

This is very tricky. What if `wget` is not installed? What if it's Windows and there is no `wget` at all? That's what CMake for - unify and satisfy all such requirements. As a workaround you can download and unpack last CMake version yourself:

```bash
> wget https://cmake.org/files/v3.5/cmake-3.5.1-Linux-x86_64.tar.gz
> tar xf cmake-*.tar.gz
> export PATH="`pwd`/cmake-.../bin":$PATH
```

Also you can use `install-ci-dependencies.py` script which will download latest CMake version. The pros of this script is that it will download new version of CMake when it became available. See usage:
* https://github.com/forexample/hunter-simple/blob/master/.travis.yml

**Comment by regnirpsj** [comment]
ok, guess i gotta go with that. out of interest, because i couldn't find it: what or where is `install-ci-dependencies.py`?

**Comment by ruslo** [comment]
> what or where is install-ci-dependencies.py?

Just like I said you can find usage in [.travis.yml](https://github.com/forexample/hunter-simple/blob/master/.travis.yml):

```
  # Install latest Polly toolchains and scripts
  - wget https://github.com/ruslo/polly/archive/master.zip
  - unzip master.zip
  - POLLY_SOURCE_DIR="`pwd`/polly-master"
  - export PATH="${POLLY_SOURCE_DIR}/bin:${PATH}"

  # Install dependencies (CMake, Android NDK)
  - install-ci-dependencies.py
```

`install-ci-dependencies.py` is a part of Polly, helper script to install CI tools: CMake, Ninja, Android NDK (may be more in future):
* https://github.com/ruslo/polly/blob/6ec82da11f5be007d85fb384cb401afcb28a824d/bin/install-ci-dependencies.py

**Comment by ruslo** [comment]
Hope this helps, closing.
