### ISSUE TITLE
Boost + static build + Visual Studio

### ISSUE THREAD

**Issue by harsszegi** [ruslo/hunter#383]
Hello,

I am trying to use Boost with Hunter, the following way:

* set(BOOST_CMAKE_ARGS BUILD_SHARED_LIBS=OFF)
  hunter_config(Boost VERSION 1.60.0 CMAKE_ARGS "${BOOST_CMAKE_ARGS}")
* Boost_USE_STATIC_LIBS ON
* find_package(Boost CONFIG REQUIRED ...)

even if doing this the compiled libraries within .hunter are like -mt.lib and -mt-gd.lib, but not -mt-s.lib or -mt-sgd.lib (or such).
As an end result I have various MD_DynamicRelease (in Boost) vs MT_StaticRelease (in my application) conflicts.

Can anyone tell me what am I missing? Why isn't hunter building "really" the static versions for MSVC?
Thanks,

**Comment by ruslo** [comment]
> set(BOOST_CMAKE_ARGS BUILD_SHARED_LIBS=OFF)

Has no effect, boost is always static. See feature request:
* https://github.com/ruslo/hunter/issues/130

**Comment by harsszegi** [comment]
How come then that Visual Studio sees the compiled .libs as Dynamic libraries and not Static ones?

**Comment by ruslo** [comment]
> How come then that Visual Studio sees the compiled .libs as Dynamic libraries and not Static ones?

Do you see any `boost*.dll`?

**Comment by harsszegi** [comment]
Ok, it appears that I'm a bit lame. Of course the Hunter builds .libs and not .dlls, so they are static, however I also want to use static runtime libraries as well, so I enabled Boost_USE_STATIC_RUNTIME ON, and I also do /MD vs /MT changes in CFLAGS parameters. 
It appears Boost_USE_STATIC_RUNTIME doesn't have any effect on building.
Or would hunter_config sort that out?
Thanks,

**Comment by ruslo** [comment]
> It appears Boost_USE_STATIC_RUNTIME doesn't have any effect on building

This one used in `find_package`, i.e. after Boost was built.

> Or would hunter_config sort that out?

We need to add separate option to custom Boost build scheme. It means that since Boost doesn't use CMake as a build tool we have to do everything manually.

> and I also do /MD vs /MT changes in CFLAGS parameters

As far as I know `/MD` conflicts with `/MT` so you have to build all the 3rd party packages you're using. Usually such flags should be added to toolchain.

**Comment by harsszegi** [comment]
Does it mean that currently I have no "stock" option in hunter to force static library and static runtime compilation of boost?

**Comment by ruslo** [comment]
> Does it mean that currently I have no "stock" option in hunter to force static library and static runtime compilation of boost?

No, it not implemented. For building shared library see https://github.com/ruslo/hunter/issues/130.
Feel free to open new feature request for runtime compilation. Also I think that fixing #130 is not hard, need to add `shared` to `b2` configuration - patches welcome.
