### ISSUE TITLE
【CMake Problem】

### ISSUE THREAD

**Issue by Need4Speak** [ruslo/hunter#385]
Dear CMake developers:
    
I have a problem: there is a function add_subdirectory(subdir) in CMake . When cmake current CMakeLists.txt, it will automatically cmake the CMakeLists.txt in sub directory, and this function just
work when the CMakeLists.txt in the sub directory, what i need is when i cmake CMakeLists.txt in the
current directory, it can cmake other CMakeLists.txt in the same level directory, what should i do？

Chao

**Comment by ruslo** [comment]
I don't see how it relates to Hunter, please use [stackoverflow](http://stackoverflow.com/) or [cmake mailing list](https://cmake.org/mailman/listinfo/cmake) to ask general questions about CMake.
