### ISSUE TITLE
Add Apache Thrift and others

### ISSUE THREAD

**Issue by lucmichalski** [ruslo/hunter#390]
Hi Ruslan,

Hope you are doing well !

I was trying Hunter today, and it is awesome, and wanted to suggest the following:
- Apache Thrift (https://github.com/apache/thrift)
- NanoMsg (https://github.com/nanomsg/nanomsg)
- Libmill (https://github.com/sustrik/libmill)
- Libdill (https://github.com/sustrik/libdill)
- Flatbuffers (https://github.com/google/flatbuffers)

Again, Hunter is awesome ! 

Cheers,
Luccio

**Comment by ruslo** [comment]
> I was trying Hunter today, and it is awesome, and wanted to suggest the following

Thanks, I've added:
* https://github.com/ruslo/hunter/issues/395
* https://github.com/ruslo/hunter/issues/394
* https://github.com/ruslo/hunter/issues/393
* https://github.com/ruslo/hunter/issues/392
* https://github.com/ruslo/hunter/issues/391
