### ISSUE TITLE
Add `Flatbuffers` package

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#395]
GitHub repo:
* https://github.com/google/flatbuffers

Note: CMake based

**Comment by headupinclouds** [comment]
Hunterized: https://github.com/headupinclouds/flatbuffers/releases/tag/v1.3.0-p2
https://github.com/headupinclouds/hunter/blob/pr.dest/cmake/projects/flatbuffers/hunter.cmake

**Comment by ruslo** [comment]
> @ruslo : Can you create a hunter-packages/flatbuffers repository? 

done: https://github.com/hunter-packages/flatbuffers

**Comment by ruslo** [comment]
Work-in-progress: https://github.com/headupinclouds/flatbuffers

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.691
* https://travis-ci.org/ingenue/hunter/builds/146096797

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.696
* https://travis-ci.org/ingenue/hunter/builds/146131569

**Comment by ruslo** [comment]
> Uploading

Done.

Package in branch `develop`. New wiki page: https://github.com/ruslo/hunter/wiki/pkg.flatbuffers
