### ISSUE TITLE
Add autobahn|cpp library

### ISSUE THREAD

**Issue by tatraian** [ruslo/hunter#398]
I would like to add autobahn|cpp library to hunter.

As I see it has the following dependencies:
 - [x] boost [already in hunter]
 - [x] openssl [already in hunter]
 - [x] ZLib [already in hunter]
 - [x] websocketpp [must add to hunter]
 - [x] Msgpack [must add to hunter]

and the package itself

 - [x] autobahn-cpp

I already created [websocketpp](https://github.com/tatraian/websocketpp/tree/0.7.0-hunter) fork and transformed it to hunter compatible. Please create a websocketpp fork into hunter-packages and I send the pull request.

**Comment by ruslo** [comment]
> Please create a websocketpp fork into hunter-packages and I send the pull request

Done

**Comment by tatraian** [comment]
Thanks, PR arrived: #400

**Comment by tatraian** [comment]
Please add msgpack-c and autobahn-cpp repositories to hunter-packages.

**Comment by ruslo** [comment]
> Please add msgpack-c and autobahn-cpp repositories to hunter-packages

This forks:
* https://github.com/msgpack/msgpack-c
* https://github.com/crossbario/autobahn-cpp

?

**Comment by tatraian** [comment]
Yes. Sorry I forgot the urls...

**Comment by ruslo** [comment]
Done:
* https://github.com/hunter-packages/autobahn-cpp
* https://github.com/hunter-packages/msgpack-c

**Comment by tatraian** [comment]
Just for note:
websocketpp version that handles dependencies is arriving in #404 
The other dependency: msgpack-s is arriving in #406

**Comment by tatraian** [comment]
Arriving in PR: #564
