### ISSUE TITLE
Should hunter be a binary?

### ISSUE THREAD

**Issue by LegalizeAdulthood** [ruslo/hunter#4]
I really like this notion of specifying my package dependencies:

```
Hunter (0.4.2) = { Boost (1.55.0), GTest (1.7.0), JsonSpirit(0.0.1), OpenSSL(1.0.1h), ... }
```

However, when I look at the crazy amount of ad-hoc cmake needed to make this work in it's present form, I wonder if Hunter simply shouldn't be an executable that is contributed to CMake itself and becomes part of what you get when you download CMake.

I tried to find a way to contact you by email for this discussion, but couldn't identify anything that would let me contact you directly, so I guess we can have this discussion in the issue tracker :).

I have been looking around at package systems lately and I find a number of package systems built on top of a giant heap of CMake files on github.  All of them were more complicated than Hunter, from what I could tell without actually trying to use them.  All of them, including Hunter, have only a single contributor making commits.  That tells me that none of these approaches is gaining "mindshare" and building a community of advocates.

I like the idea expressed above in the Hunter snippet; it is similar to the `package.json` conventions in the node world that work with `npm`.  With C++ we have the additional wrinkle that the code needs to be compiled with a compatible toolchain and build options.

What are the pros/cons of being a separate binary?  If we could get a package system adopted into the CMake distribution, it seems that would give a package system a clear boost ahead of the others.  Also, I find it hard to believe that Kitware and the CMake community as a whole haven't had big discussions about this and what needs to be there for it to be useful.

How can we bring people together on a packaging system that is good enough that large numbers of projects can make use of it without having to customize it heavily?
##

**Comment by bhack** [comment]
I think that [c++ modules](http://blog.conan.io/2016/06/01/Building-and-packaging-C++-modules-in-VS2015.html) will change something.

**Comment by ruslo** [comment]
> I think that c++ modules will change something

Is it relates to the original "Should hunter be a binary?" discussion?

Also I don't think c++ modules will make any difference for creating package managers. For example [clang documentation](http://clang.llvm.org/docs/Modules.html#problems-modules-do-not-solve) explicitly saying that:
```
Modules have no notion of version information. Programmers must still rely on
the existing versioning mechanisms of the underlying language (if any exist) to
version software libraries.
```

**Comment by bhack** [comment]
Yes versioning it is not handled buy the proosed ISOCPP but the example that I linked is a combination of modules and conan so it is an overview on how a pipeline with new modules could work with versioning and binary or source building with another framework.

**Comment by ruslo** [comment]
@bhack please open another issue if you have any thoughts to share. I don't understand why you're posting it in "Should hunter be a binary?" discussion. Thanks.

**Comment by bhack** [comment]
Ok but I've commented cause the issue have touched already the third party binary topic in the thread with https://github.com/ruslo/hunter/issues/4#issuecomment-51972454

**Comment by ruslo** [comment]
Front-end binary: https://github.com/ruslo/hunter/issues/1340
Disk space management utility: https://github.com/ruslo/hunter/issues/1226
