### ISSUE TITLE
Add ceres-solver

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#401]
https://github.com/ceres-solver/ceres-solver

Note: CMake based
Relates to TheiaSFM #276 (dependency)
##

**Comment by tbaudier** [comment]
Hi,
I "hunterized" ceres for my own project.
For the moment, ceres is available on my github:
https://github.com/tbaudier/ceres/tree/hunter
But I don't know how I can merge it in hunter-packages.
Thanks
Thomas

**Comment by ruslo** [comment]
> But I don't know how I can merge it in hunter-packages

@tbaudier Feel free to push it here: https://github.com/hunter-packages/ceres-solver

You're invited to the team (check your email). Please read these notes too: https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html#maintenance

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/pull/648#issuecomment-290589054
