### ISSUE TITLE
Find confusion

### ISSUE THREAD

**Issue by shumash** [ruslo/hunter#403]
First of all, kudos for making hunter. Such a great idea.

I'm trying to figure out how to add a new package to hunter, and have some issues with project interdependencies. I created a cmake/projects/my_package/hunter.cmake, and in general everything works great, but I am not entirely sure what is going on with the find modules. When I link my_package using the recommended method:
```
hunter_add_package(my_package)

find_package(my_package CONFIG REQUIRED)

target_link_libraries(my_exec my_package)
```
everything works great, and the library that is linked in is: 
.../HUNTER_TEST/hunter/_Base/xxxxxxx/e983464/1280480/Install/lib/libmy_packaged.a

However, the results of find_package are confusing, as the variables set to:
```
my_package_LIBRARIES=my_package
my_package_TARGET=my_package_static
```
So, if some other package (B) I rely on tries to link this library using ```${my_package_LIBRARIES}```, they do not reference the install directory ```.../HUNTER_TEST/hunter/_Base/xxxxxxx/e983464/1280480/Install/lib/```, and there is a linker error. 
What is a good way to fix that? I know that one way is to [change B to use the Hunter way](https://github.com/ruslo/hunter/wiki/usr.adding.new.package.with.dependencies), but is that really necessary?

Also, I am not entirely sure why "_static" is appended to the TARGET (this seems to be happening in HUNTER_TEST/hunter/_Base/xxxxxxx/e983464/1280480/Install/lib/cmake/gflags/gflags-config.cmake).  There is no actual library created with "_static" appended to its name. Where is this config file generated, and how can I control its behavior?

**Comment by ruslo** [comment]
I'm not sure I understand the problem.

> link this library using ${my_package_LIBRARIES}

So effectively it will link imported target `my_package`, right? So it should not reference to full path install directory.

> What is a good way to fix that? I know that one way is to change B to use the Hunter way, but is that really necessary?

What is alternative? If you want to use `my_package` you have to download it and find:

```cmake
# This is package B
hunter_add_package(my_package)
find_package(my_package CONFIG REQUIRED)
target_link_libraries(b-library PUBLIC my_package)
```

> Also, I am not entirely sure why "_static" is appended to the TARGET (this seems to be happening in HUNTER_TEST/hunter/_Base/xxxxxxx/e983464/1280480/Install/lib/cmake/gflags/gflags-config.cmake)

This is `gflags` specific, as far as I know this is not a part of autogenerated configs.

>  Where is this config file generated, and how can I control its behavior?

You may find this useful:
* http://stackoverflow.com/questions/20746936/cmake-of-what-use-is-find-package-if-you-need-to-specify-cmake-module-path-an/20857070#20857070
* https://github.com/forexample/package-example

Hope this helps.

**Comment by shumash** [comment]
Thanks for the quick reply. 

To clarify, this is what I am doing:
```
hunter_add_package(gflags)  # Only in my version of hunter
find_package(gflags CONFIG REQUIRED)

hunter_add_package(glog)  # Already in hunter
find_package(glog CONFIG REQUIRED) 

target_link_libraries(my_main glog gflags)
```

This is what happens:
```
[ 50%] Linking CXX executable my_main
cd <ROOT_DIR> && /usr/local/Cellar/cmake/3.5.0/bin/cmake -E cmake_link_script CMakeFiles/my_main.dir/link.txt --verbose=1
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++    -std=c++11 -Wl,-search_paths_first -Wl,-headerpad_max_install_names  CMakeFiles/my_main.dir/my_main.cpp.o  -o my_main  <SOME_DIR>/HUNTER_TEST/hunter/_Base/xxxxxxx/e983464/1280480/Install/lib/libglogd.a <SOME_DIR>/HUNTER_TEST/hunter/_Base/xxxxxxx/e983464/1280480/Install/lib/libgflagsd.a -lgflags-static
ld: library not found for -lgflags-static
```

The -lgflags-static is only appended when I link to glog (gflags is a dependency). I am confused why this happens and how to fix this without patching the glog CMakeLists.txt. It would seem it should be able to find the gflags lib installed by hunter automatically.

**Comment by ruslo** [comment]
> The -lgflags-static is only appended when I link to glog (gflags is a dependency)

Something wrong with `gflags` package. Target imported by `find_package(... CONFIG)` works wrongly.

**Comment by ruslo** [comment]
Closing, let me know if you have any further questions.
