### ISSUE TITLE
Integrating CMake targets with autotools projects

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#407]
Hi Ruslan,

I've been trying to add a new feature for the `hunter_autotools_project` module to take CMake targets, for example:

```CMake
hunter_autotools_project(...
    ...
    LINK_TARGETS
      SQLite3
      odb
)
```

As an alternative to the API we have today:

```CMake
hunter_autotools_project(...
    ...
    CPPFLAGS
      "-I${ODB_INCLUDE_DIR} -I${SQLITE3_INCLUDE_DIR}"
    LDFLAGS
      "-L${ODB_LIB_DIR} -lodb -L${SQLITE3_LIB_DIR} -lsqlite3"
)
```

My questions are:

1. Given your CMake knowledge, do you even think it is possible to do such thing?
2. I've tried to get properties from the CMake targets to build the `CPPFLAGS` such as `INCLUDE_DIRECTORIES` and `COMPILE_DEFINITIONS`. Since they are strings separated by space, I replaced the spaces with `;` to turn them into a list which I could do a `foreach`. However this broke generator expressions
  1. Do you think it would be best to rebuild the generator expressions by searching for `$<` on the start of the string, then counting the number of less than `<` characters and merging the next strings in the list with a space until I find the equivalent number of greater than `>` characters to finish the generator expression?
  2. For `INCLUDE_DIRECTORIES` and `COMPILE_DEFINITIONS` maybe I can just use a generator expression to solve it? Such as: `$<$<BOOL:$<TARGET_PROPERTY:cmake_target,INTERFACE_INCLUDE_DIRECTORIES>>:-I$<JOIN:$<TARGET_PROPERTY:cmake_target,INTERFACE_INCLUDE_DIRECTORIES>, -I>>`
3. However for the property `LINK_INTERFACE_LIBRARIES` I don't think I can rely only in generator expressions because I must check that the string is a target or, if it is a target I have to recurse into that target to get its `LINK_INTERFACE_LIBRARIES`, `INCLUDE_DIRECTORIES`, `COMPILE_DEFINITIONS`, `COMPILE_FLAGS` and build the `CPPFLAGS`, `{C,CXX}FLAGS` and `LDFLAGS`

I find generator expressions hard to maintain, but they seem to be a reality in CMake, so there is no running away from them, but if you know of better ways to achieve this functionality, if it is achievable at all, then please let me know.

Thanks

**Comment by ruslo** [comment]
@pretyman Thanks, I'll take a look when will have more time and leave a notes.

**Comment by ruslo** [comment]
> However this broke generator expressions

But where generator experssions come from? `autotools`-based target depends on CMake-based target? What is the build instructions if you don't use Hunter?

**Comment by pretyman** [comment]
> But where generator experssions come from? autotools-based target depends on CMake-based target? 

Exactly, when CMake targets are put in the `LINK_TARGETS` arguments, they can contain generator expressions. To tell you the truth, I've done this feature in the past - December 2015 - where I encountered this problem, but then other things came up and I ended up losing the code. Right now I have no targets that have generator expressions on them because I don't remember what targets I put in previously, but I know that is a problem that is bound to occur sooner or later.

>What is the build instructions if you don't use Hunter?

I guess they would be put "by hand" on the `./configure` command line of autotools via `CPPFLAGS` for include and define options, `LDFLAGS` for linking flags, and `{C,CXX}FLAGS` for C and C++ compiling flags.

Don't worry about this issue, I think what I'm doing is the only way, what I'm doing is: reading the properties and processing them at CMake configure time, and when I find a generator expression, just leave it as it is.

I should have some code to be reviewed next week, since I just moved countries, been a little busy. Maybe I should learn `pkgconfig` first to see if this is actually needed or not. It could be that this feature is pointless :|

**Comment by ruslo** [comment]
> and when I find a generator expression, just leave it as it is

May work wrongly because we are on the different "stages" of build. When generator expression expanding we are on the configuring of ExternalProject_Add stage, i.e. Debug/Release doesn't play any role - build type added in one of the ExternalProject_Add steps. Also as far as I understand autotools scheme doesn't pick Debug/Release flags or build several types of libraries. Actually this is an issue, at least about performance (e.g. `-O3 -DNDEBUG` not added).

> Maybe I should learn pkgconfig first to see if this is actually needed or not

Yes, `*.pc` files play the same role as usage requirements from `*Config.cmake` as far as I understand.

**Comment by pretyman** [comment]
Yes, I did realize there is no treatment of the `CMAKE_BUILD_TYPE` or `CMAKE_CONFIGURATION_TYPES` with autotools when I was looking at the CMake properties: https://cmake.org/cmake/help/v3.0/manual/cmake-properties.7.html#properties-on-targets and saw the properties with `_<CONFIG>` suffix while working on this issue. 

The behavior we have today is a bug, I guess :< 

The autotools approach to deal with different build configuration types seems to use the `--prefix` option of `./configure` to set a custom directory for each output such as `release` or `debug` directory. 

The drawback is that we end up with duplicate headers in the disk. Also I think I'll need to modify the CMake find scripts to treat this structure.

On the other hand, in CMake world I saw that projects use `OUTPUT_NAME_<CONFIG>` to determine a  different name for each configuration type.

In the ideal world I think I should have one ExternalProject_Add for each `CMAKE_CONFIGURATION_TYPES` or `CMAKE_BUILD_TYPE`, is that correct? And no duplicate header files. 

I guess this is subject for a issue of its own

**Comment by ruslo** [comment]
> Yes, I did realize there is no treatment of the CMAKE_BUILD_TYPE or CMAKE_CONFIGURATION_TYPES with autotools when I was looking at the CMake properties

To clarify scheme should use `HUNTER_PACKAGE_CONFIGURATION_TYPES`  variable. How each build type treated is a separate question.

> The autotools approach to deal with different build configuration types seems to use the --prefix option of ./configure to set a custom directory for each output such as release or debug directory

CMake approach is to add postfix to the different build types, e.g. empty for Release and `d` for Debug. Headers should be the same. Here is example when `*Config.cmake` is the same for both types:
* https://github.com/forexample/package-example

Type specific goes to `*-release.cmake`/`*-debug.cmake`. I think changing layout of binaries may lead to the problems. Need to figure out how to deal with `*.pc` files. I guess they are not designed so.

> In the ideal world I think I should have one ExternalProject_Add for each CMAKE_CONFIGURATION_TYPES or CMAKE_BUILD_TYPE, is that correct?

Yes

> And no duplicate header files.

Yes

> I guess this is subject for a issue of its own

Agree: https://github.com/ruslo/hunter/issues/411

**Comment by pretyman** [comment]
I found this to be really non trivial and, I guess, not worth while. I'll close this issue for now.
