### ISSUE TITLE
How to set compile flags for INTERFACE_SOURCES

### ISSUE THREAD

**Issue by Knitschi** [ruslo/hunter#408]
When I use the staticly linked qt package it will add some INTERACE_SOURCES to my own target. Namely the file "static_qt_plugin.cpp".

Now I have the problem that this file causes warnings and I compile with warnings as errors. So I need to reduce the warning level for this file.

Do you have any idea how i can do this. I think the file does no really belong to my target, because I tried using
````
get_source_file_property( flags ${filename} COMPILE_FLAGS)
````
and
````
get_property(flags SOURCE ${filename} PROPERTY COMPILE_FLAGS)
````
using both, the full filename of the trouble-making .cpp file and the short name only.
No flags are returned.

I do my calls in the scope where my target is created. 
Do you have any ideas how i can change the compile flags for that file?

**Comment by ruslo** [comment]
> Do you have any ideas how i can change the compile flags for that file?

Can you try to add `-w` (disable warning) instead of removing `-Werror`?

**Comment by ruslo** [comment]
> Can you try to add -w (disable warning)

See http://stackoverflow.com/a/37070903/2288008

**Comment by Knitschi** [comment]
Thank you again. I marked your answer as the correct one on stackoverflow.
