### ISSUE TITLE
Linking dynamic library as dependency on windows

### ISSUE THREAD

**Issue by tzemaitis** [ruslo/hunter#424]
One of project dependencies are dynamic library. Hunter build it and stored it in hunter root _Base/<ids..>/Install/bin directory. Compilation and linking of application is fine, but on runtime (for example running tests, debug on build location) library can't be found on windows, because windows do not look for dynamic libraries in this directory. How to handle this in general way?

**Comment by headupinclouds** [comment]
I have very little Windows experience but am curious about how this is done myself.  This discussion might be helpful:

http://cmake.3232098.n2.nabble.com/Windows-rpath-emulation-td7588537.html

It seems you have a couple options:
1) install the application and DLL in the same folder (bin)
2) add the DLL folder to your PATH variable
3) (perhaps preferably) you can use a manifest

Here are a few CMake + manifest links that might help:

https://gist.github.com/bjornblissing/6fc452fe7ec1fdfe3419
http://stackoverflow.com/questions/6335352/how-can-i-embed-a-specific-manifest-file-in-a-windows-dll-with-a-cmake-build

**Comment by ruslo** [comment]
David provide a good answer here, closing.
