### ISSUE TITLE
Password protected sources (Git)

### ISSUE THREAD

**Issue by rooi** [ruslo/hunter#426]
Hi,

I'm wondering if there is any option to include git/svn sources that are password/login protected? As far as I know there is no option to generate input fields in cmake to enter passwords and such. Adding the login details in plain text is an option, but obviously not preferred.

Thanks!

Roy
##

**Comment by ruslo** [comment]
> is any option to include git/svn sources

Using SHA1 of commit + git repository instead of URL + SHA1 of archive is not implemented but planned in future.

> that are password/login protected?

Hunter use for downloading commands `file(DOWNLOAD ...)` and `ExternalProject_Add` so password/login features should be implemented in CMake first.

**Comment by fire** [comment]
If you can assign git repositories, you can use ssh keys. Is that possible @ruslo ?

**Comment by ruslo** [comment]
> If you can assign git repositories, you can use ssh keys. Is that possible @ruslo ?

never have tried it. you can experiment with `ExternalProject_Add` - if it will work then it's possible to implement this feature

**Comment by rooi** [comment]
I'll try to ssh option soon, the SCM Mangerer git repo ssh plugin does not seem to be supported any longer, but perhaps there is a workaround.

The is another option to use _netrc of .netrc files with the login details, but that only seems to work if I change the cmake source to allow optional netrc files (or am I missing something?)

**Comment by ruslo** [comment]
> cmake source to allow optional netrc files (or am I missing something?)

why cmake? I think cmake do call regular git executable so it reads standard configuration files

**Comment by rooi** [comment]
Ah, that could be the thing I was missing... I need to look into that

**Comment by fire** [comment]
Documentation for [ExternalProject](https://cmake.org/cmake/help/v3.0/module/ExternalProject.html) shows git options. Using a ssh git repository would automatically use your existing ssh keys to access a git:// link.

**Comment by ruslo** [comment]
> Hunter use for downloading commands file(DOWNLOAD ...) and ExternalProject_Add so password/login features should be implemented in CMake first

Available since CMake 3.7

Sources protected by HTTP password available in Hunter since [v0.16.22](https://github.com/ruslo/hunter/releases/tag/v0.16.22). Documentation:
* https://docs.hunter.sh/en/latest/user-guides/cmake-user/protected-sources.html

Note that git repository can't be specified as a source for now so obviously no access to protected git repositories too. Feature request: https://github.com/ruslo/hunter/issues/230

**Comment by ruslo** [comment]
Closing inactive discussion.
