### ISSUE TITLE
Autotools bootsrap option.

### ISSUE THREAD

**Issue by Cyberunner23** [ruslo/hunter#428]
Some libraries that use autotools as a build system use some sort of bootstrap command such as `./autogen.sh` or `./bootstrap` before doing the usual
    
    ./configure
    make
    make install

(I'm looking at you libsodium)
So I was wondering if it would be possible to add some sort of option where one can set such boostrap command and make it run just before the ./configure. I was thinking of putting it in [hunter_autotools_project.cmake](https://github.com/ruslo/hunter/blob/master/cmake/modules/hunter_autotools_project.cmake) so we can easily make a schema without rederiving hunter_autotools_project.cmake for each bootstrap command.

**Comment by ruslo** [comment]
> if it would be possible to add some sort of option where one can set such boostrap command

I guess it's possible. You can add option `BOOTSTRAP` to `hunter_autotools_project`. @pretyman what do you think?

**Comment by pretyman** [comment]
Sorry, late for the party since I've been without internet. Yeah it makes total sense to be there 

👍
