### ISSUE TITLE
Add 'Assimp' package

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#431]
official: http://assimp.org
official github repo: https://github.com/assimp/assimp
hunterized fork: https://github.com/hunter-packages/assimp
note: cmake-based
needed for [Urho3D](https://github.com/ruslo/hunter/issues/389)

Dependencies (see contrib folder)
- [x] [ConvertUTF](https://github.com/ruslo/hunter/issues/432)
- [x] [polyclipping(clipper)](https://github.com/ruslo/hunter/issues/433)
- [x] [irrXML](https://github.com/ruslo/hunter/issues/434)
- [x] [openddlparser](https://github.com/ruslo/hunter/issues/435)
- [x] [poly2tri](https://github.com/ruslo/hunter/issues/436)
- [x] [minizip(unzip)](https://github.com/ruslo/hunter/issues/437)
- [x] [zlib](https://github.com/ruslo/hunter/wiki/pkg.zlib)

**Comment by headupinclouds** [comment]
Initial release: https://github.com/hunter-packages/clipper/releases/tag/v22.0.0-p0
https://github.com/headupinclouds/hunter/blob/develop.urho3d/cmake/projects/clipper/hunter.cmake
NOTE: The original clipper cpp lib goes by the name `polyclipping`, so I did the same.

**Comment by headupinclouds** [comment]
@ruslo, @fire, @pretyman : I've added a few dependencies as hunter packages and am looking at testing these locally within the main assimp package now.  In the case of pre-existing CMakeLists.txt projects, such as this one, there is often a fair degree of complexity related to inline toolchain definitions and other customizations that aren't used in hunter packages, and may conflict with external toolchains.  I'm trying to decide if it makes sense to use a fresh minimal hunter CMakeLists.txt (to improve readability and maintainability) or to try to manage the hunter adaptations side-by-side in the original CMakeLists.txt.  My sense is that significant hunter changes will most likely make it difficult to merge from upstream anyway.  I wanted to open this one up for discussion to see what other folks thought.

**Comment by ruslo** [comment]
All dependencies on board. Doing `assimp` package now.

**Comment by headupinclouds** [comment]
:+1:

**Comment by ruslo** [comment]
Assimp using clipper version 4.8: https://github.com/assimp/assimp/blob/9b6de15b74f4d44220f0514766d6344f6238cf2f/contrib/clipper/clipper.hpp#L4

4 years old: https://sourceforge.net/projects/polyclipping/files/?source=navbar

**Comment by ruslo** [comment]
Clipper version fixed, have to update RapidJSON too. Linux seem to work:
![screen](https://cloud.githubusercontent.com/assets/4346993/16287055/1fa5c7f0-38e9-11e6-97a8-22da7d470ac3.png)

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.605
* https://travis-ci.org/ingenue/hunter/builds/139641077

**Comment by ruslo** [comment]
Upload in process:
* https://travis-ci.org/ingenue/hunter/builds/139879782
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.629

**Comment by ruslo** [comment]
> Upload in process

iOS 9.3 and MinGW builds hit an environment limits. iOS 9.3 stops by timeout, MinGW has a memory allocating problems (`cc1plus.exe: out of memory allocating 65536 bytes`). Interesting fact that `ios-nocodesign` with 5 architectures works faster then `ios-nocodesign-9-3-wo-armv7s` with 4 architectures.

Uploading from my local machine.

**Comment by ruslo** [comment]
> Uploading from my local machine

Done.

Release available: https://github.com/ruslo/hunter/releases/tag/v0.14.29
New wiki page: https://github.com/ruslo/hunter/wiki/pkg.assimp
