### ISSUE TITLE
Add 'ConvertUTF' package

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#432]
extract from assimp: https://github.com/assimp/assimp/tree/master/contrib/ConvertUTF
hunterized fork: https://github.com/hunter-packages/convertutf

**Comment by headupinclouds** [comment]
Existing github fork: https://github.com/plenluno/convertutf

**Comment by ruslo** [comment]
Merged to `develop`, binaries uploaded, new wiki: https://github.com/ruslo/hunter/wiki/pkg.convertutf
