### ISSUE TITLE
Add 'polyclipping' package

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#433]
official: https://sourceforge.net/projects/polyclipping/
hinterized: https://github.com/hunter-packages/clipper

**Comment by headupinclouds** [comment]
Existing sourceforge mirror on github:
https://github.com/hakito/Clipper

**Comment by headupinclouds** [comment]
The Urho3D package contains only the top level clipper.{h,cpp} files. 
```
tree Urho3D/Source/ThirdParty/Assimp/contrib/clipper/
Urho3D/Source/ThirdParty/Assimp/contrib/clipper/
├── License.txt
├── clipper.cpp
└── clipper.hpp
```
The full release is larger with a number of language bindings.  I will limit the initial import to C++. 
```
tree clipper/
clipper/
├── C#
│   ├── ConsoleDemo
│   │   ├── ConsoleDemo
│   │   │   ├── ConsoleDemo.csproj
│   │   │   ├── Program.cs
│   │   │   ├── Properties
│   │   │   │   └── AssemblyInfo.cs
│   │   │   └── bin
│   │   │       └── Release
│   │   │           ├── ConsoleDemo.exe
│   │   │           ├── clip.txt
│   │   │           ├── clipper_library.dll
│   │   │           └── subj.txt
│   │   └── ConsoleDemo.sln
│   ├── GuiDemo
│   │   ├── GuiDemo
│   │   │   ├── Form1.Designer.cs
│   │   │   ├── Form1.cs
│   │   │   ├── Form1.resx
│   │   │   ├── GuiDemo.csproj
│   │   │   ├── Program.cs
│   │   │   ├── Properties
│   │   │   │   ├── AssemblyInfo.cs
│   │   │   │   ├── Resources.Designer.cs
│   │   │   │   ├── Resources.resx
│   │   │   │   ├── Settings.Designer.cs
│   │   │   │   └── Settings.settings
│   │   │   ├── Settings.cs
│   │   │   ├── aust.bin
│   │   │   └── bin
│   │   │       └── Release
│   │   │           ├── GuiDemo.exe
│   │   │           └── clipper_library.dll
│   │   └── GuiDemo.sln
│   └── clipper_library
│       ├── Properties
│       │   └── AssemblyInfo.cs
│       ├── clipper.cs
│       └── clipper_library.csproj
├── Delphi
│   ├── cairo demo
│   │   ├── Cairo Resources.txt
│   │   ├── CairoClipperDemo1.dpr
│   │   ├── CairoClipperDemo1.res
│   │   └── cairo_clipper.pas
│   ├── clipper.pas
│   └── main demo
│       ├── GR32_Misc.pas
│       ├── clipper_demo.dpr
│       ├── clipper_demo.exe
│       ├── clipper_demo.res
│       ├── main.dfm
│       ├── main.pas
│       └── polygons.res
├── Documentation
│   ├── clipper.chm
│   ├── default.css
│   ├── offset_triginometry.svg
│   ├── offset_triginometry2.svg
│   └── offset_triginometry3.svg
├── License.txt
├── README
├── README.md
├── Third Party
│   ├── Flash
│   │   └── AS3_flash_readme.txt
│   ├── Go
│   │   └── Go_readme.txt
│   ├── Haskell
│   │   └── Haskell_readme.txt
│   ├── Java
│   │   └── java_readme.txt
│   ├── LuaJIT
│   │   └── LuaJIT_readme.txt
│   ├── Matlab
│   │   ├── matlab_readme.txt
│   │   └── mexclipper.cpp
│   ├── ObjectiveC
│   │   └── objectivec_readme.txt
│   ├── perl
│   │   └── perl_readme.txt
│   ├── python
│   │   ├── clipper.py
│   │   ├── clipper_demo.py
│   │   └── python_readme.txt
│   └── ruby
│       └── ruby_readme.txt
└── cpp
    ├── CMakeLists.txt
    ├── clipper.cpp
    ├── clipper.hpp
    ├── cpp_agg
    │   ├── agg_conv_clipper.h
    │   ├── clipper_test.cpp
    │   ├── clipper_test.exe
    │   ├── clipper_test.sln
    │   ├── clipper_test.vcxproj
    │   ├── clipper_test.vcxproj.filters
    │   └── icon.res
    ├── cpp_cairo
    │   ├── Cairo Resources.txt
    │   ├── cairo.sln
    │   ├── cairo.vcxproj
    │   ├── cairo_clipper.cpp
    │   ├── cairo_clipper.hpp
    │   ├── libcairo-2.lib
    │   └── main.cpp
    ├── cpp_console
    │   ├── clipper_console_demo.cpp
    │   ├── clipper_console_demo.exe
    │   ├── clipper_console_demo.sln
    │   └── clipper_console_demo.vcxproj
    ├── cpp_opengl
    │   ├── clipper_demo.exe
    │   ├── clipper_demo.sln
    │   ├── clipper_demo.vcxproj
    │   ├── icon.res
    │   ├── main.cpp
    │   └── menu.res
    └── polyclipping.pc.cmakein
```

**Comment by ruslo** [comment]
> Existing sourceforge mirror on github: https://github.com/hakito/Clipper

As far as I understand you've used this repo as a start point (?)

I have some thoughts to share:
* official clipper use SVN: https://sourceforge.net/p/polyclipping/code/HEAD/tree/
* Git repos produced by svn->git converter. The peculiarity of this step is about nonrepeatability of final result. As you can see same commit in different repos has different SHA1:
 * https://github.com/hakito/Clipper/commit/cfd8f7a070b98dba730e5de6e8a7c058bb033271
 * https://github.com/antialize/clipper-cpp/commit/301706e40d35a0ac4639d33d4cedb90fbf044e10
 * https://github.com/anders9ustafsson/clipper/commit/728b6afd2408d3984369f0e2083d5830decdd744
 
this make updating of this stuff very tricky. Assume we have svn-state-A, converting it to git-state-A. Then upstream updates svn-state-A + svn-delta, when you run svn->git converter it doesn't produce git-state-A + git-delta, it produce git-state-B. Now we have our patches git-state-A + hunterization and need to apply updates from git-state-B - this will lead to the resolving conflicts all over the whole history since git doesn't know that git-state-A and git-state-B is almost the same.

Instead I offer to use Qt/Boost updating approach. We do commit plain release `x.y.z` to the branch with the same name. Hunterization patches will be applied to this branch. Cons: same as with svn->git converter, we have to resolve conflicts some times but difference is that we resolving conflicts in **our** patches, not in upstream patches. Pros: we doesn't depends on unofficial mirrors (to work we need only official releases), we don't need to run git->svn converters.

I will experiment with such approach here: https://github.com/hunter-packages/polyclipping

@pretyman we have discussed svn->git converter before, feel free to add any notes you have.

**Comment by headupinclouds** [comment]
@ruslo: I have no strong preference.

> We do commit plain release x.y.z to the branch with the same name. Hunterization patches will be applied to this branch.

Is the source imported to git or does the repository just host the TGZ release?

**Comment by ruslo** [comment]
> Is the source imported to git or does the repository just host the TGZ release?

unpack TGZ release, I don't want to use svn->git because of reasons I've described

**Comment by ruslo** [comment]
Uploading binaries:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.527
* https://travis-ci.org/ingenue/hunter/builds/138392328

**Comment by ruslo** [comment]
Merged to `develop`, binaries uploaded, new wiki page: https://github.com/ruslo/hunter/wiki/pkg.polyclipping
