### ISSUE TITLE
Add 'minizip' package

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#437]
official: http://www.winimage.com/zLibDll/minizip.html
check: https://github.com/assimp/assimp/tree/master/contrib/unzip

**Comment by Cyberunner23** [comment]
Just checked, the 'unzip' included in assimp is a lightly modified minizip. Assimp just adds switches to use the included zlib or the system-wide zlib and removes the 'OF' macro (for function prototypes) at the end of each function declaration, slight function changes and slight include changes.

**Comment by ruslo** [comment]
@Cyberunner23 okay, thanks

**Comment by headupinclouds** [comment]
@ruslo : I see no hunter-packages/unzip.  Shall we add this?

**Comment by ruslo** [comment]
@headupinclouds so it should be minizip, right?

**Comment by ruslo** [comment]
https://github.com/hunter-packages/minizip

**Comment by ruslo** [comment]
> Just checked, the 'unzip' included in assimp is a lightly modified minizip

Too much changes, mostly formatting. Using minizip as is, hope this will work.

Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.558
* https://travis-ci.org/ingenue/hunter/builds/138623318

**Comment by ruslo** [comment]
Branch develop, binaries uploaded, new wiki page: https://github.com/ruslo/hunter/wiki/pkg.minizip
