### ISSUE TITLE
Add 'dest' package

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#439]
original: https://github.com/cheind/dest
hunterized: https://github.com/headupinclouds/dest

TODO: need hunter-packages/dest repository for hosting

Only need flatbuffers for the initial lib only release

Dependencies:
- [x] eigen 
- [x] flatbuffers : only needs single header ext/flatbuffers/flatbuffers.h

NOTE: Will omit packages needed by samples in the initial release

Samples: 
- [ ] [tinydir](https://github.com/ruslo/hunter/issues/443)
- [ ] [tclap](https://github.com/ruslo/hunter/issues/444)
- [x] opencv

**Comment by ruslo** [comment]
> TODO: need hunter-packages/dest repository for hosting

see https://github.com/hunter-packages/dest

**Comment by ruslo** [comment]
Work-in-progress: https://github.com/headupinclouds/hunter/commits/pr.dest

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.692
* https://travis-ci.org/ingenue/hunter/builds/146106435

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.698
* https://travis-ci.org/ingenue/hunter/builds/146134197

**Comment by ruslo** [comment]
> Uploading

Done. Package in branch `develop`. New wiki page: https://github.com/ruslo/hunter/wiki/pkg.dest
