### ISSUE TITLE
Add 'ogles_gpgpu' package

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#442]
@ruslo: Please create a hunter-packages/ogles_gpgpu repository.

**Comment by ruslo** [comment]
done: https://github.com/hunter-packages/ogles_gpgpu

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.694
* https://travis-ci.org/ingenue/hunter/builds/146116360

**Comment by ruslo** [comment]
Uploading:
* https://travis-ci.org/ingenue/hunter/builds/146154423
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.700

**Comment by ruslo** [comment]
> Uploading

Done. Release: https://github.com/ruslo/hunter/releases/tag/v0.15.0

New wiki page: https://github.com/ruslo/hunter/wiki/pkg.ogles_gpgpu
