### ISSUE TITLE
Add 'tinydir' package

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#443]

**Comment by headupinclouds** [comment]
Please add a tinydir repository to hunter-packages.

**Comment by ruslo** [comment]
done: https://github.com/hunter-packages/tinydir

**Comment by ruslo** [comment]
@headupinclouds do we need this package? I think `dest` compiles fine without it.

**Comment by ruslo** [comment]
GitHub sources: https://github.com/cxong/tinydir

**Comment by headupinclouds** [comment]
Not critical for a first version, but it would be nice to have.  That is only needed when building the project directly (with hunter) including applications.

**Comment by ruslo** [comment]
I figured out that it's one file project, will add.

**Comment by ruslo** [comment]
Testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.695
* https://travis-ci.org/ingenue/hunter/builds/146123503

**Comment by ruslo** [comment]
Uploading:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.701
* https://travis-ci.org/ingenue/hunter/builds/146155584

**Comment by ruslo** [comment]
> Uploading

Done.

Package in branch `develop`. New wiki page: https://github.com/ruslo/hunter/wiki/pkg.tinydir
