### ISSUE TITLE
include-what-you-use 

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#457]
An interesting clang header analyzer I wasn't aware of until now:  

https://github.com/include-what-you-use/include-what-you-use

http://stackoverflow.com/a/30951493
http://stackoverflow.com/a/31086619

**Comment by ruslo** [comment]
Probably this feature is for [Polly](https://github.com/ruslo/polly) toolchains?

**Comment by headupinclouds** [comment]
> Probably this feature is for Polly toolchains?

I think you are right.  I can post an issue there and will close this one.

I did run some initial experiments.  It was fairly easy to get it working, but it became apparent this is still alpha SW.  The automatic python header fixer got tripped up by a number of cases.  Still an interesting resource, but it seems to be require supervision nat this point.
