### ISSUE TITLE
Add 'tesseract-ocr' package

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#459]
Hi Ruslan,

I'm trying to add 'tesseract-ocr' to hunter, but I'm having some problems.

It depends on https://github.com/DanBloomberg/leptonica which I did some patching to CMake scripts and [hunterized](https://github.com/pretyman/leptonica/commit/d526c8af1ef26594311b62a673b2aefdb5fa909f).

However when trying to hunterize tesseract, the include path of `_Base/hunter-id/config-id/toolchain-id/Install/include` is not added to the targets of the CMakeLists of tesseract.

I guess the Leptonica package would have this directory to `target_include_directories(leptonica INTERFACE "_Base/hunter-id/config-id/toolchain-id/Install/include")` where the [leptonica target is defined](https://github.com/pretyman/leptonica/blob/da7a4ba45c7cdb91de99ce686440b2c00e26fdd0/src/CMakeLists.txt), but how do I do this in a way it will work with caching later?

Thanks
##

**Comment by ruslo** [comment]
> It depends on https://github.com/DanBloomberg/leptonica which I did some patching to CMake scripts and hunterized.

I've added: https://github.com/ruslo/hunter/issues/460

> I guess the Leptonica package would have this directory to target_include_directories(leptonica INTERFACE "_Base/hunter-id/config-id/toolchain-id/Install/include") where the leptonica target is defined, but how do I do this in a way it will work with caching later?

Should be just "include", see https://github.com/forexample/package-example/blob/cf2ea1d6a209fb9eca2ab83fdd0ac15fe4d3e807/Foo/CMakeLists.txt#L111

**Comment by pretyman** [comment]
> Should be just "include", see https://github.com/forexample/package-example/blob/cf2ea1d6a209fb9eca2ab83fdd0ac15fe4d3e807/Foo/CMakeLists.txt#L111

Thanks, I added the include, however it still does not pick up the include path, even with target `leptonica` is added to `target_link_libraries(tesseract ${Leptonica_LIBRARIES})`.

I'll continue investigating

**Comment by ruslo** [comment]
What is the compiler output? Does any path added as include? Is there any warnings in CMake code? Why do you need to use `${Leptonica_LIBRARIES}`? You can use just `leptonica`, dependent libraries should be linked automatically.

**Comment by pretyman** [comment]
> Why do you need to use ${Leptonica_LIBRARIES}? You can use just leptonica

Sorry for not being clear: `${Leptonica_LIBRARIES}` expands to `leptonica` (that how it is in the original CMake scripts of `tesseract`)

> What is the compiler output? Does any path added as include? Is there any warnings in CMake code?

As I brought leptonica + tesseract into hunter, now the compiler won't run and I get errors in CMake code. I understand what is happening, but not really why.

CMake errors:
````
-- Configuring done
CMake Error at CMakeLists.txt:239 (add_executable):
  Target "tesseractmain" links to target "JPEG::jpeg" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:239 (add_executable):
  Target "tesseractmain" links to target "PNG::png" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?


CMake Error at CMakeLists.txt:239 (add_executable):
  Target "tesseractmain" links to target "TIFF::libtiff" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
(...)
```
Package `leptonica`'s script installs files:
```
./lib/cmake/Leptonica/LeptonicaConfig-version.cmake
./lib/cmake/Leptonica/LeptonicaConfig.cmake
./lib/cmake/Leptonica/LeptonicaTargets.cmake
```

In LeptonicaTargets.cmake

```
# Import target "leptonica" for configuration "Debug"
set_property(TARGET leptonica APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(leptonica PROPERTIES
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "JPEG::jpeg;PNG::png;TIFF::libtiff;ZLIB::zlib;m"
  IMPORTED_LOCATION_DEBUG "/Users/discipline/.hunter/_Base/xxxxxxx/ec42007/8c5e650/Build/leptonica/Build/leptonica-Debug-prefix/src/leptonica-Debug-build/src/Debug/libleptonicad.1.73.dylib"
  IMPORTED_SONAME_DEBUG "/Users/discipline/.hunter/_Base/xxxxxxx/ec42007/8c5e650/Build/leptonica/Build/leptonica-Debug-prefix/src/leptonica-Debug-build/src/Debug/libleptonicad.1.73.dylib"
  )
```

So the `leptonica` target gets imported by `tesseract`, but `tesseract` did not do `FindPackage(...)` in the transitive dependencies of `JPEG`, `PNG`, etc.. to see targets `JPEG::jpeg`, `PNG::png`, etc.. and I would think it shouldn't do the `FindPackage(...)` because that's `leptonica`'s information.

I guess `leptonica`'s CMake scripts and `tesseract`'s are broken.

My question is: how should this scenario with transitive dependencies be treated? I think I should just rewrite `leptonica`'s and `tesseract`'s CMake scripts, following your example in https://github.com/forexample/package-example . But do you think your example would treat this scenario?

Thanks

**Comment by ruslo** [comment]
You need to add `find_package` to `Config.cmake.in` template:
```cmake
@PACKAGE_INIT@

find_package(JPEG CONFIG REQUIRED)
find_package(PNG CONFIG REQUIRED)
find_package(TIFF CONFIG REQUIRED)

include("${CMAKE_CURRENT_LIST_DIR}/@targets_export_name@.cmake")
check_required_components("@PROJECT_NAME@")
```

in general [find_dependency](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html) macro should be used here but I'm not sure about CONFIG vs MODULE (i.e. either it will use FindJPEG or JPEGConfig).

**Comment by xsacha** [comment]
Tesseract-OCR now has CMake support in 3.05 so it should be easier to hunterise.

**Comment by xsacha** [comment]
Since #460 is complete, can we have a hunter package for tesseract?

**Comment by ruslo** [comment]
@xsacha feel free to work on it

**Comment by xsacha** [comment]
#830

**Comment by pretyman** [comment]
Thanks a lot for working on this, I'm still on the a stage before the ocr in my app, so I was not going to work on this too soon.

**Comment by xsacha** [comment]
@ruslo this was completed a while ago.
