### ISSUE TITLE
autotools default paths 

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#462]
https://github.com/ruslo/hunter/issues/411#issuecomment-220546303

> I remember that I was against modifying PATH and PKG_CONFIG_PATH by default, that's why we have MODIFY_PATH and MODIFY_PKG_CONFIG. I guess I'm ready to change my mind now :) Adding:
>

> - -I@HUNTER_INSTALL_PREFIX@/include

>- -L@HUNTER_INSTALL_PREFIX@/lib
> - PKG_CONFIG_PATH=@HUNTER_INSTALL_PREFIX@/lib/pkgconfig:@HUNTER_INSTALL_PREFIX@/share/pkgconfig
> - PATH=@HUNTER_INSTALL_PREFIX@/bin:${default_path}

>seems consistent to me, feel free to remove MODIFY_PATH/MODIFY_PKG_CONFIG. We can add options for disabling of modifications of anything in case there will be some issues about it.

**Comment by pretyman** [comment]
> We can add options for disabling of modifications of anything in case there will be some issues about it.

I've been thinking, would it make any sense to have the option to disable this?

**Comment by ruslo** [comment]
> would it make any sense to have the option to disable this?

We can have defaults and **if** there will be problems in future **then** we can add such options. I think we can move without them for now.
