### ISSUE TITLE
Cached packages must also substitute @HUNTER_INSTALL_PREFIX@/lib in text files

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#472]
As per https://github.com/ruslo/hunter/pull/467#issuecomment-235301895 , when building a cacheable package, with packages using libtool, it could link to libraries in `@HUNTER_INSTALL_PREFIX@/lib`. This information goes into the `*.la` files and  `@HUNTER_INSTALL_PREFIX@/lib` is not considered in the patching text files.

With libtool, this information goes into the `dependency_libs` for example:

```
dependency_libs=' -L/home/travis/build/ingenue/hunter/_testing/Hunter/_Base/2a647da/6d7617a/8928885/Install/lib /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/2a647da/6d7617a/8928885/Install/lib/libXau.la'
```

This must be considered when patching a cacheable package.

**Comment by pretyman** [comment]
Can I close this now or should I wait for the changes to be merged into `master` branch?

**Comment by ruslo** [comment]
Released: https://github.com/ruslo/hunter/releases/tag/v0.15.2

**Comment by pretyman** [comment]
Thanks! :+1:
