### ISSUE TITLE
Autotools iOS packages must patch unrelocatable text files before being merged with lipo

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#474]
The toolchain for iOS is failing for Autotools packages with unrelocatable text files. They need to be patched in all architectures. The patch must remove the architecture information which is present as the build directory in the text files.

Such examples of text files include `*.la` and `*.pc`.

Example of log of failure from https://travis-ci.org/ingenue/hunter/jobs/116995545#L2742

```
CMake Error at autotools-merge-lipo.cmake:234 (message):
  lipo execution failed: fatal error: lipo: can't figure out the architecture
  type of:
  /Users/travis/build/ingenue/hunter/_testing/Hunter/_Base/e53f669/58e7826/a239ac9/Build/odb/Build/multi-arch/armv7/lib/pkgconfig/libodb.pc
```

Today libtool `*.la` are being removed, so this behaviour should also be changed and the `*.la` files must be patched as per above.

A naive approach would be to use `PACKAGE_UNRELOCATABLE_TEXT_FILES` as the list of files to be patched, although I cannot guarantee that it will be enough.

**Comment by ruslo** [comment]
We already discussed it, no?

* https://github.com/ruslo/hunter/issues/218
* https://github.com/ruslo/hunter/issues/207

**Comment by pretyman** [comment]
Sheesh, my bad, completely forgot about it. Let's close this and continue discussion on https://github.com/ruslo/hunter/issues/218
