### ISSUE TITLE
Add 'Poco::Crypto' to Poco package

### ISSUE THREAD

**Issue by trungnq97** [ruslo/hunter#479]
Hi **hunter**,
Please add 'Poco::Crypto' to Poco package.
Thanks!

**Comment by ruslo** [comment]
I think you need to set custom build option `ENABLE_CRYPTO=ON`. Defaults that used in [PocoCpp/hunter.cmake](https://github.com/ruslo/hunter/blob/master/cmake/projects/PocoCpp/hunter.cmake):
```cmake
hunter_cmake_args(
    PocoCpp
    CMAKE_ARGS
        CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE
        POCO_STATIC=ON
        ENABLE_CPPUNIT=OFF
        ENABLE_MONGODB=OFF
        ENABLE_NETSSL=OFF
        ENABLE_CRYPTO=OFF
        ENABLE_DATA=OFF
        ENABLE_PAGECOMPILER=OFF
        ENABLE_PAGECOMPILER_FILE2PAGE=OFF
        ENABLE_REDIS=OFF
)
```

See wiki page: https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-cmake-options

**Comment by trungnq97** [comment]
Thanks ruslo! I'll take a look at custom build option.

Btw, the wiki page of Poco does not mention about Crypto. That's why I thought Crypto is missing. https://github.com/ruslo/hunter/wiki/pkg.pococpp

I'll resolve this issue now. Thanks again!

**Comment by ruslo** [comment]
> Btw, the wiki page of Poco does not mention about Crypto. That's why I thought Crypto is missing.

Feel free to add :)

**Comment by trungnq97** [comment]
The **cmake_args** here, how are they mapped to components mentioned in the wiki?

```
CMAKE_ARGS
        CMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE
        POCO_STATIC=ON
        ENABLE_CPPUNIT=OFF
        ENABLE_MONGODB=OFF
        ENABLE_NETSSL=OFF
        ENABLE_CRYPTO=OFF
        ENABLE_DATA=OFF
        ENABLE_PAGECOMPILER=OFF
        ENABLE_PAGECOMPILER_FILE2PAGE=OFF
        ENABLE_REDIS=OFF
```

Components mentioned in [wiki](https://github.com/ruslo/hunter/wiki/pkg.pococpp).
```
Foundation (Poco::Foundation)
JSON (Poco::JSON)
Net (Poco::Net)
Util (Poco::Util)
XML (Poco::XML)
Zip (Poco::Zip)
```

**Comment by ruslo** [comment]
>  how are they mapped to components mentioned in the wiki?

I don't know. I guess this is a question to the Poco documentation itself. It would be nice to have a link in Hunter wiki though.

**Comment by ruslo** [comment]
> Components mentioned in wiki.

This one added by @aarnchng. @aarnchng can you help?

**Comment by trungnq97** [comment]
I've found the map between cmake_args and Poco components in https://github.com/pocoproject/poco/blob/develop/CMakeLists.txt. I've updated the wiki.

**Comment by ruslo** [comment]
@trungnq97 Great, thank you.
