### ISSUE TITLE
Could hunter be more verbose by default ?

### ISSUE THREAD

**Issue by daminetreg** [ruslo/hunter#485]
In my team we now use hunter for some projects.

Often we have issues to download packages, because the SHA sum doesn't fit or because we have some issue with the company proxy.

We see this issues late, because it takes time to fail ( _e.g._ retry policy of HunterGate) or in the middle of a first build and because the error messages aren't displayed. Naturally if we enable HUNTER_STATUS_DEBUG=ON then we see directly what is wrong.

Wouldn't it be a good improvement to make hunter more verbose per default ? 
##

**Comment by ruslo** [comment]
You can always set `option(HUNTER_STATUS_DEBUG "Hunter debug info" ON)` before `HunterGate`:

```cmake
option(HUNTER_STATUS_DEBUG "Hunter debug info" ON)
HunterGate(
    URL ...
    SHA1 ...
)
```

**Comment by daminetreg** [comment]
Yes naturally per-project I can set this, but I mean the hunter project itself would benefit I think for showing more the details of his failures per default. 

HUNTER_STATUS_DEBUG is naturally alot, but I believe that everything related to download issues would benefit to be displayed per default. Because if you have an internal company proxy which provides a Not-Authenticated.html page for any request, hunter will continuously fail thinking he got the package at the URL but it's just the SHA1 which didn't match.

I think it would help for the acceptance of Hunter.

**Comment by ruslo** [comment]
Sorry, I'm not sure I follow. So you're saying that `HUNTER_STATUS_DEBUG=ON` is enough, right? But if `HUNTER_STATUS_DEBUG` is `ON` there is a lot of info. So do you want Hunter to determine a priory will there be an error on not? :) Also Hunter do use ExternalProject_Add for downloading projects, there is no any special logic about handling errors or debug messages. May be if you describe the use case with logs it clarify the scenario a bit.

**Comment by ruslo** [comment]
Closing inactive discussion.
