### ISSUE TITLE
Add LibUV

### ISSUE THREAD

**Issue by dthompso99** [ruslo/hunter#493]
##

**Comment by ruslo** [comment]
https://github.com/libuv/libuv

Build system: GYP or autotools

**Comment by cristianadam** [comment]
CMake will have libuv as a dependency for cmake-server, see http://public.kitware.com/pipermail/cmake-developers/2016-August/029235.html

CMake has some other 3rd party integrated libraries (e.g. curl), which I don't know if they can be used by Hunter.

**Comment by ruslo** [comment]
> which I don't know if they can be used by Hunter

CMake has a bootstrap mode. In this mode the only requirement is c++ compiler. So we have chicken-egg problem: to make `file(DOWNLOAD ...)` work we need CURL, to have CURL we need to download it, hence we need `file(DOWNLOAD ...)`. Though even without that problem you should really ask CMake team about decisions they made :sunglasses:

**Comment by ruslo** [comment]
Fixed by https://github.com/ruslo/hunter/pull/711
