### ISSUE TITLE
Cross compiling with Hunter

### ISSUE THREAD

**Issue by fwinnen** [ruslo/hunter#494]
I have a cmake crossplatform c++ project which uses Protobuf and has to support at least Linux, iOS and Android. Cross compiling protobuf is not the issue, but the project setup gets kind of messy when cross compiling libprotobuf for target (i.e iOS) and having protoc on host (i.e macOS) available to generate source files from .proto in cmake.

I had a custom setup with a hierarchy of ExternalProject's where the outer-most project uses default toolchain and creates protoc for host and the actual project for target with custom toolchains for iOS
and Android. 

As you see, this is hard to maintain, so i am investigating polly's toolchains with hunter for dependencies (Protobuf).

I was able to adapt the hunter package of Protobuf to skip compiling protoc when cross compiling and import a user specified host-protoc so everything works fine. Only problem is, that i need to supply the instance of protoc which i would like to also have as a hunter dependency.

Do you guys have some idea, how i can manage hunter dependencies for different toolchains?
If there is some mechanic in hunter that i could extend for that purpose or if there is some other way to achieve this with hunter, please let me know.
##

**Comment by ruslo** [comment]
I haven't worked with protobuf but as far as I understand you need to have protobuf library and some protoc executable tool, right? I.e. you need some kind of mix:
* Linux host + Android target: protoc tool compiled with Linux host toolchain + protobuf lib compiled with Android toolchain
* OSX host + Android target: protoc tool compiled with OSX host toolchain + protobuf lib compiled with Android toolchain
* OSX host + iOS target: protoc tool compiled with OSX host toolchain + protobuf lib compiled with iOS toolchain
* OSX host + OSX target: protoc tool and protobuf lib compiled both with OSX host toolchain

Is my vision correct?

**Comment by fwinnen** [comment]
Thx for the fast response!

Your vision is totally right.
Also the hunter package already builds the library and the executable (obviously for the same target). I would imagine, that i need to switch toolchains in code, or supply a separate host toolchain for hunter_add_package...

**Comment by ruslo** [comment]
> Your vision is totally right

It is good :) Another good news is that it's important feature and I have a plan to implement it.
However the bad news is that it's quite tricky and I can't say in will be done in near future. This is something that is not designed in CMake itself: https://cgold.readthedocs.io/en/latest/overview/cmake-can-not.html#incomplete-functionality-coverage

> supply a separate host toolchain for hunter_add_package

Kind of. You need to build protoc using host toolchain (I guess default will be OK) first, then feed path to host protoc to the target toolchain. I guess the next question will be how to connect them in automated fashion. You can try to run host toolchain from target CMakeLists.txt by

```cmake
execute_process(
    COMMAND
    "${CMAKE_COMMAND}" -Hhost "-B${CMAKE_CURRENT_BINARY_DIR}/host-build"
    ...
)
```

This will trigger host build and install protoc. You can save path to current host-root directory in plain text in some file like "${CMAKE_CURRENT_BINARY_DIR}/host-build/path.to.protoc" and read this file in target toolchain.

Host toolchain (`host/CMakeLists.txt`):

```cmake
hunter_add_package(Protobuf)
file(WRITE "${CMAKE_BINARY_DIR}/path.to.protoc" "${PROTOBUF_ROOT}/bin/protoc")
```

Target toolchain (top-level `CMakeLists.txt`):

```cmake
execute_process(...)
file(READ "${CMAKE_CURRENT_BINARY_DIR}/host-build/path.to.protoc" host_protoc) # find host protoc
execute_process(COMMAND "${host_protoc}" ...) # use it
```

I haven't tried it myself, let me know how it will work if you wish to try.

**Comment by fwinnen** [comment]
> You can try to run host toolchain from target CMakeLists.txt by
The idea is similar to what i did before hunter integration, but i used ExternalProject and got all kind of problems with toolchains partly passed through and order of dependency execution...
 
Your approach with execute_process could be the simple and more elegant solution. I will try this out and report back.

What would be the preferred way to make this kind of a more general solution (to play nice with expectations of other hunter users)? 

* Make building protoc optional for all
* Assume protoc is only relevant for host (correct for Android and iOS but but maybe not for other cross compiling cases)
* Have all Targets as protobuf:: and protobuf_host:: variants (which would be just alias when target==host) 

How to figure out we want to cross compile at all?
* Android toolchains sets CMAKE_CROSSCOMPILING
* iOS toolchain only sets IOS
* only make special cases for those two?

Anyways, i guess i will start to try this out and figure out the details if everything work. Thanks again for your input!

**Comment by ruslo** [comment]
> Just figured out that your approach is all client/user side and not in the package

Yep, I think package should not contain this stuff. It may looks solid in this case when you can say that "we are building executable hence it's not for target but for host", but it may be not true for other packages. Though I can't provide any examples. Another problem with this approach is about CMake itself, just like I say there is no support of two toolchain in one project, so it's simply not possible - we have to run build twice anyway.

However what project should provide is an option to do optimal build. E.g. if we have `foo_lib` for target library and `foo_tool` for host executable there should be option `FOO_BUILD_LIB` and `FOO_BUILD_TOOL`:

```cmake

  option(FOO_BUILD_LIB "Build library" ON)
  option(FOO_BUILD_TOOL "Build tool" ON)

  if(FOO_BUILD_LIB)
    add_library(foo_lib ...)
  endif()

  if(FOO_BUILD_TOOL)
    add_executable(foo_tool ...)
  endif()
```

Next cases:
* native development: by default both options are ON and we install everything to host root
* while cross-compiling: set FOO_BUILD_LIB=OFF and use host toolchain to install tool
* while cross-compiling: set FOO_BUILD_TOOL=OFF and use target toolchain to install library

I've openned feature request here: https://github.com/ruslo/hunter/issues/495

**Comment by rcdailey** [comment]
I know this isn't constructive feedback, but I've been keeping an eye on support for cross compiling as well. The hosts and targets we support at `$DAYJOB` are:

Hosts:

* Windows x86
* Linux x86

Targets:

* Windows x86 (MSVC toolchain)
* Linux x86 (GCC or Clang toolchain)
* Android ARM (NDK-supplied toolchain)
* Android x86/Intel (NDK-supplied toolchain)

**Comment by ruslo** [comment]
This particular issue is about **mixing** both toolchains in one project, i.e. using project simultaneously for the target and host. For example if you're working on Linux and create package for Android and you want package `Foo` to install some stuff for Linux x86 **and** Android arm in one shot. 

@rcdailey Is this your case?

**Comment by rcdailey** [comment]
Yes that's it.

**Comment by ruslo** [comment]
> Yes that's it

@rcdailey Can you provide details? Does it fall at any cases described [here](https://github.com/ruslo/hunter/issues/495) or it is something new?

**Comment by rcdailey** [comment]
Here is some detail on specifically what we do. We support a few different platforms & toolchain combinations:

* Windows + MSVC
* Windows + Android NDK (armeabi-7v / gcc 4.9)
* Linux + GCC 4.9 x86
* Linux + Android NDK (armeabi-7v / gcc 4.9)

Simply put, on a given platform we need to be able to use CMake "normally" (on Windows, use Visual Studio; on Linux, use selected make program + C/CXX env variables to define toolchain), and also specify the toolchain manually for cross compilation on Android using the NDK's prebuilt toolchains. We use a custom version of [takanome's CMake toolchain for Android NDK](https://github.com/taka-no-me/android-cmake) to give CMake the information it needs to find and use the Android NDK toolchains.

For each combination of platform and toolchain, we generate 1 time in CMake. There is a separate CMake binary directory for each combination. In other words, we do not support swapping the toolchain after generation. You must clear the CMake cache and generate all over again.

As mentioned before, we have separate manual builds of third party libraries for every platform+toolchain combo. What I expect from hunter is the ability to automate builds for these third party libraries, but allow me to specify the toolchain to use when building these libraries. This specifically covers the Android NDK case, where without this functionality, hunter would have no idea what toolchain to use.

If it can somehow use the same configuration that CMake is using, that'd be great. But I haven't used hunter at all yet so I really have no idea how it works so far. This is my general feedback, though.

I hope that is helpful and clear enough. Let me know if you have other questions.

**Comment by ruslo** [comment]
> I hope that is helpful and clear enough

It is perfectly clear. I'm using the same Android toolchains for Hunter. I haven't used it on Windows host (usually it's Linux host/Android target, OSX host/Android target) but it should work I guess.

@rcdailey I'm still thinking that you misunderstood my question. This particular issue is about doing package management for both host and target toolchain **simultaneously**. For example if you have next CMakeLists.txt:

```cmake
find_package(foo REQUIRED CONFIG)
```

With Hunter you can do:

```cmake
hunter_add_package(foo)
find_package(foo REQUIRED CONFIG)
```

Then for your cases:

* Start this code on Windows with "-G Visual Studio" and this code will install `foo` using Visual Studio (target and host toolchains matches)
* Start this code on Windows with "-DCMAKE_TOOLCHAIN_FILE=android" and this code will install `foo` using Android toolchain (target Android, host Windows)
* Start this code on Linux with "-G Unix Makefiles" and this code will install `foo` using Makefile (target and host toolchains matches)
* Start this code on Linux with "-DCMAKE_TOOLCHAIN_FILE=android" and this code will install `foo` using Android toolchain (target Android, host Linux)

**This issue** about packages that need to be installed **for both target and host**, i.e. when you use this CMakeLists.txt it should do:

* Start this code on Windows with "-DCMAKE_TOOLCHAIN_FILE=android" and this code will install `foo` using Android toolchain **and** `foo` using Visual Studio
* Start this code on Linux with "-DCMAKE_TOOLCHAIN_FILE=android" and this code will install `foo` using Android toolchain **and** `foo` using Makefile

In this case there will be **two** root directories. We will take some components from `foo` installed on host and use them for building `foo` for target.

If you take a look at [this pull request](https://github.com/ruslo/hunter/pull/496) you may see that by `hunter_add_package(Protobuf)` we do install `protoc` tool for **host platform**, then `protoc` used in the CMakeLists.txt for helping to use protobuf library for the **target platform**.

**Comment by rcdailey** [comment]
You're right, it does sound like I'm misunderstanding. To make sure I get it now, what you're saying is that for each single CMake binary directory, you want to do a 2 pass with hunter: Build & install for host and then again for provided toolchain?

This is, in effect, the same as having 2 cmake binary directories, one generated for host and one generated against toolchain file. Is this correct?

**Comment by ruslo** [comment]
> you want to do a 2 pass with hunter: Build & install for host and then again for provided toolchain?

For this particular issue yes. Note that the files may differs. E.g. you want to build OpenCV, Boost and Protobuf for Android. You can use Android toolchain and Hunter packages:
```cmake
hunter_add_package(OpenCV) # install Android library
hunter_add_package(Boost) # install Android library
hunter_add_package(Protobuf) # install Android library
```
but additionally you must have separate **host CMakeLists.txt**:

```cmake
# host/CMakeLists.txt
hunter_add_package(Protobuf) # install 'protoc' tool for host
```

It should be executed before we use Protobuf and information about 'protoc' should be transmitted to target toolchain.

> This is, in effect, the same as having 2 cmake binary directories, one generated for host and one generated against toolchain file. Is this correct?

Yes. But the question about how they will know about each other. To be accurate: target build need to know information about host root directory. That's the issue now.

**Comment by rcdailey** [comment]
It's good to hear that hunter already supports the scenario I need. My case is simple: I just need to build the libraries for target toolchain and link to them. Thanks for explaining @ruslo!

**Comment by ruslo** [comment]
Closing inactive discussion.
