### ISSUE TITLE
Interface targets in all cases?

### ISSUE THREAD

**Issue by rcdailey** [ruslo/hunter#500]
I posted this on your Q&A site linked in your readme but seems desolate. I'll repost my question here.

For every hunter package that's created, is there also a corresponding interface target provided? Even if that package doesn't natively use CMake, I would still expect an interface target.

One pain point of working with external libraries in CMake is dealing with the different ways to propagate them as a dependency. find_package() provides interface targets for those that support them, and for others use the old-style separate variables for libraries, headers, etc.

Does Hunter unify this system and make it consistent?
##

**Comment by ruslo** [comment]
> I posted this on your Q&A site linked in your readme

Sorry, I haven't received any notifications :) I'll take a look.

**Comment by ruslo** [comment]
> I'll take a look

Seems that it's not so good as it looks :) Don't understand how to deal with notifications. I've removed links to avoid confusion.

**Comment by ruslo** [comment]
> For every hunter package that's created, is there also a corresponding interface target provided?

Not any special. If we are talking about CMake based projects it's responsibility of package's CMake code.

> Even if that package doesn't natively use CMake, I would still expect an interface target.

You have several choices:
1) Patch your project to use CMake. The best option.
2) Patch your custom build system so it can install CMake-friendly `*Config.cmake` modules along with other installed files (headers, binaries). This is how Qt works for example.
3) Use Hunter to do the same. Do additional step in build process to configure and install `*Config.cmake` files. For example this is how Boost imported libraries introduced: https://github.com/ruslo/hunter/blob/878318af2e8dcaa4e9fc5946cbdf3067a94c9c2a/cmake/templates/BoostConfig.cmake.in#L28-L42

**Comment by rcdailey** [comment]
Your answer is from the perspective of the maintainer of the library not using CMake. In my case, I'm a consumer of those libraries. I use Hunter to provide those libraries to my own projects. At the moment I hand-compile everything and build my own CMakeLists.txt files for each of them that I do add_subdirectory() on. Each of these scripts does a very simple interface target and points to the fixed include and libs. This allows me to simply use target_link_libraries() to include third party dependencies in my own code. I don't have to use find_package() or setup library libs and headers manually each time I want to use them.

I'd probably want to continue that trend with Hunter. Instead of contributing CMake upstream to that library (which is, a lot of times, far more work than I'm willing to put in), I'd rather just have my own personal ad-hoc config.cmake for that specific package. I'll take a look at the boost targets you maintain separately, that's probably the route I want to go.

**Comment by ruslo** [comment]
Closing inactive discussion.
