### ISSUE TITLE
Use system packages

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#501]
For now Hunter designed so that user should not use packages installed by system. However there is an improvement possible to avoid confict that described [here](https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html#conflict) by marking package as system. I guess it will look like this:

``` cmake
hunter_config(ZLIB VERSION SYSTEM)
```
- All packages from such `Config-ID` will use system version
- We should forbid uploading of binary cache produced by such configuration
##

**Comment by ruslo** [comment]
https://docs.hunter.sh/en/latest/faq/interaction-with-other-package-managers.html

**Comment by ruslo** [comment]
Example of conflict: https://github.com/forexample/android-cmake/issues/1#issuecomment-254098171

**Comment by ruslo** [comment]
Somehow related:

I've added helper module which use `find_library`/`find_path` to locate system libraries:
* https://github.com/ruslo/hunter/blob/59f2ce14f8e5faec9bd45fb720ffe33b5d596ac0/cmake/modules/hunter_find_helper.cmake#L83-L84

Valid case is the libraries that **always** present in system. E.g. `android.so` and `log.so` are always a part of Android NDK:
* https://github.com/ruslo/hunter/blob/59f2ce14f8e5faec9bd45fb720ffe33b5d596ac0/cmake/find/Findandroid_log.cmake
* https://github.com/ruslo/hunter/blob/59f2ce14f8e5faec9bd45fb720ffe33b5d596ac0/cmake/find/Findandroid.cmake

Or as a workaround to currently missing packages like `OSMesa.so`:
* https://github.com/ruslo/hunter/issues/904

Wiki pages for such packages do not have `hunter_add_package` directives:
* https://github.com/ruslo/hunter/wiki/pkg.android
* https://github.com/ruslo/hunter/wiki/pkg.android_log
* https://github.com/ruslo/hunter/wiki/pkg.osmesa

**Comment by Lectem** [comment]
I would personally like to have this but with a fallback. That is, if the library exists on the system, use it, otherwise download it as a standard hunter package

**Comment by ruslo** [comment]
> That is, if the library exists on the system, use it, otherwise download it as a standard hunter package

It violates reproducibility principle.

>  By that I mean HUNTER_ENABLED with disabled-mode per package

It doesn't relate to this discussion at all.

As a general note this feature looks weak and may not work in some cases that already described (see Qt). So I doubt it make sense to implement it.

**Comment by ruslo** [comment]
Will not happen.

**Comment by lsolanka** [comment]
Is this completely dead? It could actually be quite useful in some situations.

It would of course make the build system dependent, but I believe that might actually be desired in some situations.

**Comment by ruslo** [comment]
> Is this completely dead?

I have no plans. And I'm not aware of anybody working on it.

> It could actually be quite useful in some situations.

The maintenance and clean cache friendly implementation of this feature will require an unbelievable amount of work at least from my understanding. If you turn off cache server feature, it will make you impossible to speed up builds with ready to use binaries. That's a controversial goal: you want to speed up the build by not building packages with Hunter, and at the same time you can't use binaries from Hunter cache server and have to build everything from source.

Also, it still will not save you from:
- https://github.com/forexample/android-cmake/issues/1#issuecomment-254098171
- https://github.com/ruslo/hunter/issues/1811#issuecomment-481198389
