### ISSUE TITLE
Build fail with lib in lib64 instead of lib/

### ISSUE THREAD

**Issue by dsarrut** [ruslo/hunter#503]
Hello, 

I tried to use Hunter for a project that require odb (https://github.com/ruslo/hunter/tree/master/examples/odb-sqlite), but it fails after compilation. I'm on Linux OpenSuse 13.2 (3.16.7-42-desktop)

Here is my CmakeLists.txt:
```
cmake_minimum_required(VERSION 3.0)
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.15.20.tar.gz"
    SHA1 "1771b5509cf8645bdb1c7ac12bc5d29a35465d12"
)
project(myproject)
hunter_add_package(Boost COMPONENTS date_time system filesystem)
hunter_add_package(odb-compiler)
hunter_add_package(odb-sqlite)
```

And the last part of the error message:
```
-- [hunter] Build step successful (dir: /home/dsarrut/.hunter/_Base/1771b55/cef4daf/c658a14/Build/odb)
[hunter ** FATAL ERROR **] File not exists:
[hunter ** FATAL ERROR **]   /home/dsarrut/.hunter/_Base/1771b55/cef4daf/c658a14/Build/odb/Install/lib/libodb.la
[hunter ** FATAL ERROR **] (check HUNTER_PACKAGE_UNRELOCATABLE_TEXT_FILES)
[hunter ** FATAL ERROR **] [Directory:/home/dsarrut/.hunter/_Base/Download/Hunter/0.15.20/1771b55/Unpacked/cmake/projects/odb]
```

I checked and libodb.la exist but in lib64/ not in lib/. Do you have an idea to correct that ? 

thanks !
David

**Comment by pretyman** [comment]
Seems relevant: http://stackoverflow.com/questions/9247769/lib-directory-on-64-bit-opensuse-distribution

Looks like an OpenSuse issue, I guess we could add `--libdir` to the autotools scheme

**Comment by pretyman** [comment]
Or even better could be clear the variable LIBDIR which *might* be present in OpenSuse in the clear vars script. I have to download an Image and run it in a VM to test it out

**Comment by ruslo** [comment]
@pretyman Is https://github.com/ruslo/hunter/pull/507 fixing this one?

**Comment by pretyman** [comment]
Yep

**Comment by ruslo** [comment]
> Yep

@dsarrut Can you confirm? Here is the version with fix: https://github.com/ruslo/hunter/releases/tag/v0.15.23

**Comment by dsarrut** [comment]
It was ok with the version privately send by @pretyman, but with the v0.15.23, it is ok for odb but there is an error with boost:
```
[hunter ** INTERNAL **] Library not exists: /home/dsarrut/.hunter/_Base/xxxxxxx/5cfabc3/c658a14/Install/lib/libboost_date_time-mt-d.a
[hunter ** INTERNAL **] [Directory:/home/dsarrut/.hunter/_Base/ab53ab9/5cfabc3/c658a14/Install/lib/cmake/Boost]
------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------
```
(of course xxxxxx folder does not exist). Maybe it is not related, I could investigate a bit more early next week ...

**Comment by dsarrut** [comment]
yes, thanks you for you fast reaction !
