### ISSUE TITLE
SQLite3 and Visual Studio

### ISSUE THREAD

**Issue by wisk** [ruslo/hunter#504]
Hi there,

I've a question regarding the package SQLite3. At this time, it only uses the official `sqlite-autoconf-3140100.tar.gz` archive which relies on autoconf.
Unfortunately , autoconf is not available on Windows / Visual Studio. However I found [this repository](https://github.com/alex85k/sqlite3-cmake) which provides a CMake script to build SQLite3.
I made a really simple [hunter.cmake](https://gist.github.com/wisk/94b18d24324663eedeaf5f1a6343fcd8) script which works like a charm.
I'm wondering if the official hunter repository can include either the CMake script made by @alex85k or fork its repository to provide an alternative for Visual Studio users?

Thank you,
##

**Comment by pretyman** [comment]
Hi, I guess you can send a pull request, however the SQLite3 in hunter today has build flags `-DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_ENABLE_RTREE=1`


- `SQLITE_ENABLE_UNLOCK_NOTIFY=1` is for `odb-sqlite`
-  `SQLITE_ENABLE_RTREE=1` which I think it was for spatialite, which I never got around to contribute but should at some point [ I guess this can be removed until the future ]

Any chance you can keep `SQLITE_ENABLE_UNLOCK_NOTIFY=1` and test `odb-sqlite` to see if it works with this scheme?

Thanks

**Comment by ruslo** [comment]
> fork its repository to provide an alternative for Visual Studio users?

@wisk I like the approach of substituting native build with CMake so instead of using this repo only for Visual Studio we can use it for all platforms. However since package already exists we should make it compatible with native old variant (see @pretyman comments). If it's hard to do we can always add it under `if(WIN32)` condition:

```cmake
if(WIN32)
  hunter_add_version(... <url-with-visual-studio-build> ...)
else()
  hunter_add_version(... <url-with-autotools-build> ...)
endif()
```

**Comment by wisk** [comment]
@pretyman:
I guess it's just about adding some ``target_compile_definitions`` so it should be pretty easy.
I'm not familiar with ``.la`` or ``.pc``, I need to document myself to know how it works.

@ruslo:
I think it's better to rely on ``MSVC`` to determine which compiler is used, AFAIK ``WIN32`` could be defined even if the compiler is not Visual Studio.

Thanks for your advice. :)

**Comment by ruslo** [comment]
> AFAIK WIN32 could be defined even if the compiler is not Visual Studio

Yes, but since Linux and OSX is [already working](https://travis-ci.org/ingenue/hunter/builds/146957970) and there is no toolchains on Windows I was hoping that by introducing CMake we **may** have MinGW (or even MSYS).

**Comment by pretyman** [comment]
hi @wisk ,

I guess you won't need the `*.la` files and `*.pc` in Visual Studio, but if you could have at least `SQLITE_ENABLE_UNLOCK_NOTIFY=1`, when/if we integrate `odb` to work with Visual Studio, it would make transitioning smoother. However they could be interesting for MinGW and MSYS [ although I don't have experience with these platforms ]

Anyway, Ruslan is the boss, so it's his final call.

Since I'm also interested in this package, I could in the future craft our own CMake scripts where these compilation define flags could be controlled by [CMAKE_ARGS](https://github.com/ruslo/hunter/wiki/dev.modules#hunter_config). However no time frame can be given, it would be done when more control over these flags is actually needed.

**Comment by ruslo** [comment]
> I guess you won't need the *.la files and *.pc in Visual Studio

I was talking about the case when we can use CMake version **for all platforms**.

> However they could be interesting for MinGW and MSYS

Here I mean that when we have CMake build then **it may work** for other platforms too. I always prefer step-by-step approach so if Visual Studio will be working without breaking old OSX/Linux tests it's quite enough.

**Comment by wisk** [comment]
Sorry for the delay, I forked his project and added ``SQLITE_ENABLE_UNLOCK_NOTIFY``.
https://github.com/wisk/sqlite3-cmake

**Comment by ruslo** [comment]
> I forked his project

Do you want me to create repository in hunter-packages?

See: https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html#maintenance

**Comment by wisk** [comment]
Sorry for the late reply.
Actually I prefer you keep the lead on this project(, and the source code). Even if hunter check against sha1 packate's project, I truly think you've more trustfully if you manage it, plus you have more experience on CMake scripting.
However, if you lack of resources, I could give some help on this package.
Actually, this package is very bound to SOCI library, which I really depend on for my own project.
Just tell me what do it's more convenient for you.

**Comment by ruslo** [comment]
> Actually I prefer you keep the lead on this project

You're asking whom? You want me to be a maintainer of `sqlite3-cmake` fork?

**Comment by wisk** [comment]
Sorry for the misunderstanding, I wasn't clear.
I'm not asking you to be the maintainer of this fork, I only think it's safer if this package is hosted in this repository https://github.com/hunter-packages than mine.
If my account is deleted or renamed, it'll break this package.

**Comment by ruslo** [comment]
>  only think it's safer if this package is hosted in this repository https://github.com/hunter-packages than mine

Sure, repository created: https://github.com/hunter-packages/sqlite3-cmake

@wisk You're invited. After you'll accept invitation (check your email) you will be able to do pushes and releases.

**Comment by wisk** [comment]
Thanks for the invitation. :)

**Comment by ruslo** [comment]
Closing inactive discussion.
