### ISSUE TITLE
FindBoost.cmake does not find Boost COMPONENT math

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#506]
Hi Ruslan,

Boost math library is not being found by [FindBoost.cmake](https://github.com/ruslo/hunter/blob/deb87cf2c8377e7138df5a9ccecb985f0eff8cea/cmake/find/FindBoost.cmake) as it has different naming conventions, instead of libboost_{component} it generates libraries named at the listing at the end of this post. 

What should we do about the diff from FindBoost.cmake in Hunter and the latest from CMake? I guess upstream would benefit from such a patch. To maintain [FindBoost.cmake](https://github.com/ruslo/hunter/blob/deb87cf2c8377e7138df5a9ccecb985f0eff8cea/cmake/find/FindBoost.cmake) is quite annoying [ file is very long ], so I trying to get this work done only once. 

```
libboost_math_c99
libboost_math_c99l
libboost_math_tr1   
libboost_math_tr1l
libboost_math_c99f 
libboost_math_c99l   
libboost_math_tr1f
libboost_math_tr1l
libboost_math_c99  
libboost_math_c99f   
libboost_math_tr1  
libboost_math_tr1f
```

Thanks

Edit: Can reproduce with the following CMakeLists.txt:

``` CMake
cmake_minimum_required(VERSION 3.0)

# Enable HunterGate:
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.15.20.tar.gz"
    SHA1 "1771b5509cf8645bdb1c7ac12bc5d29a35465d12"
)
project(boost_math_test)

hunter_add_package(Boost COMPONENTS math)
set(Boost_DEBUG ON)
find_package(Boost CONFIG REQUIRED math)
```
##

**Comment by ruslo** [comment]
> Boost math library is not being found by FindBoost.cmake as it has different naming conventions

Are you sure we are not talking about `BoostConfig.cmake`?

> What should we do about the diff from FindBoost.cmake in Hunter and the latest from CMake?

As far as I remember after imported targets introduced into upstream FindBoost.cmake it start conflict with Hunter version so you should be careful here, you can merge everything except `Boost::` stuff.

**Comment by pretyman** [comment]
> Are you sure we are not talking about BoostConfig.cmake?

From what I understood, it is FindBoost.cmake as BoostConfig.cmake calls find_package(Boost MODULE ...).

Upstream FindBoost.cmake suffers from same problem.

I don't want to sound like a dick, but since I only need the header part of Boost math, I won't be working on this as FindBoost.cmake is a real monster. I have little time to dev these days.

Should I leave this issue open to acknowledge the problem? Or just close it?

**Comment by ruslo** [comment]
> Upstream FindBoost.cmake suffers from same problem.

Okay I see, this should be fixed first then.

> Should I leave this issue open to acknowledge the problem? Or just close it?

I will mark it as a broken package but on practice it will be open until somebody express the wish to fix it. So not a big difference compared to closing :)

**Comment by ruslo** [comment]
> > Upstream FindBoost.cmake suffers from same problem.

> Okay I see, this should be fixed first then.

Not a Hunter issue, closing.
