### ISSUE TITLE
cannot build boost thread example on travis.

### ISSUE THREAD

**Issue by tatraian** [ruslo/hunter#509]
I created a boost thread hunter branch:
https://github.com/tatraian/hunter/tree/Boost-thread-example

https://github.com/tatraian/hunter/tree/Boost-thread-example/examples/Boost-thread

I launched a travis build from it.

https://travis-ci.org/tatraian/hunter_test/builds/157588984

Most of the tests fail because link error to clock_gettime.

(And type_traits is not found on osx in clang-libstdcxx).

I get the same error during autobahn build: 
https://github.com/hunter-packages/autobahn-cpp/pull/1

**Comment by ruslo** [comment]
There is no test with `Boost::thread` target: https://github.com/ingenue/hunter/blob/pkg.boost/.travis.yml. Probably we should start with example creation.

**Comment by tatraian** [comment]
Almost fixed with #510.

**Comment by ruslo** [comment]
> Almost fixed with

Kind of. Now it's time for Boost::chrono example.

**Comment by tatraian** [comment]
Fixed by #524
