### ISSUE TITLE
hunter badge

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#513]
It would be nice to have a hunter "badge" to easily identify hunterized packages/branches.
##

**Comment by ruslo** [comment]
I have a few thoughts about it:
* https://github.com/ruslo/hunter/issues/138#issuecomment-98802473
* https://github.com/ruslo/hunter/issues/449#issuecomment-227339551

But I'm not sure how it can be applied for "branches". Can you describe the scenario?

**Comment by headupinclouds** [comment]
> But I'm not sure how it can be applied for "branches".

You are right.  I meant forks.  Hunterized opencv, etc.

**Comment by ruslo** [comment]
> Markdown (SVG): `![Alt text](https://img.shields.io/badge/hunter-v0.15.18-blue.svg)`

Amazing, how you did that? :)

> You are right. I meant forks. Hunterized opencv, etc.

Okay, so I can add this badge to Hunter release, then users can use this code to mark their packages with such badge. Right?

**Comment by headupinclouds** [comment]
> Amazing, how you did that? :)

The shields.io site makes it easy for us.  Scroll down the main page until you see this:

![your_badge](https://cloud.githubusercontent.com/assets/554720/18438155/2856e314-78ce-11e6-8bc7-9b3ce9de91b7.jpg)

But you can do the same thing directly via url manipulation once you see the basic form.

> Okay, so I can add this badge to Hunter release, then users can use this code to mark their packages with such badge. Right?

Yes.  Users just need to include the correct URL format for their version of Hunter.

**Comment by headupinclouds** [comment]
It would be nice to provide an official Hunter aware badge, such that the version is extracted automatically from the repository CMakeLists.txt.  I'm scanning through the `shields` docs to see if this might be possible.

https://github.com/badges/shields/blob/master/doc/TUTORIAL.md

**Comment by ruslo** [comment]
I can't find related discussion where I mentioned that see no point of adding version of Hunter to badge. It make sense to write name of the package and go to `https://docs.hunter.sh/en/latest/packages/pkg/<name>.html` instead. I've added such badge to Gauze:
* https://github.com/hunter-packages/gauze

@headupinclouds What do you think?

**Comment by headupinclouds** [comment]
That makes sense to me.  Specifying the exact package name helps clarify usage, and the link can provide addition details.  Users are probably more interested in how to use the library through Hunter, rather than what version of Hunter will be used to manage dependencies from a local build of the project.

**Comment by ruslo** [comment]
> That makes sense to me

I've added "Badge" section to documentation:
* https://docs.hunter.sh/en/latest/creating-new/create/cmake.html#badge
