### ISSUE TITLE
Boost.Python with multiple python versions

### ISSUE THREAD

**Issue by dvirtz** [ruslo/hunter#514]
I'm trying to use Boost.Python with both python 2.7 and 3.5.
However, no matter what I do it is built with python 2.7 only.

According to the examples at [Boost.Python docs](http://www.boost.org/doc/libs/1_61_0/libs/python/doc/html/building/configuring_boost_build.html#building.configuring_boost_build.examples), user_config.jam needs to have the following lines:

```
using python : 2.5 ;  # Make both versions of Python available
using python : 3.5 ;  # To build with python 3.5, add python=3.5
                  # to your command line.
```

I tried to configure the package with `CMAKE_ARGS PYTHON_python=3.5` but it doesn't work.

Is there a way to achieve this with Hunter?

I'm using CMake 3.3.0 on Windows with MSVC 2015.
##

**Comment by ruslo** [comment]
> I tried to configure the package with CMAKE_ARGS PYTHON_python=3.5 but it doesn't work

It is converted to `b2 -s python=3.5` (see [pkg.boost](https://github.com/ruslo/hunter/wiki/pkg.boost)). Is this a right way to set Python version in Boost build?

**Comment by dvirtz** [comment]
It does, but like I wrote it is probably not the right way.
In the meantime I'm trying to fork Hunter and fix it myself.

**Comment by ruslo** [comment]
Closing inactive discussion.
