### ISSUE TITLE
How to grab a package at a specific/fixed version?

### ISSUE THREAD

**Issue by rcdailey** [ruslo/hunter#515]
I am following the "first steps" tutorial for boost, but it just downloads version 1.61. I want to make it download, build, and install 1.59 instead. How can I simply specify the version number that `hunter_add_package` should use? The tutorial does not cover this very basic and common use case.

I did some digging but I didn't find anything helpful. The closest thing I found was `hunter_config`, where users can specify a version number. But this somehow utilizes some sort of config file which I do not understand right now. Also [the wiki page](https://github.com/ruslo/hunter/wiki/error.unexpected.hunter_config) about this macro states that it shouldn't really be used normally.

Any advice on this please?

**Comment by rcdailey** [comment]
Ah, I finally get it. I have to create a `config.cmake` and use `FILEPATH` parameter with `HunterGate()`. This will allow me to override versions of libraries. Assuming this is accurate, I will close this issue.

**Comment by ruslo** [comment]
> I have to create a config.cmake and use FILEPATH parameter with HunterGate()

You can set LOCAL to use default `cmake/Hunter/config.cmake` location, see https://github.com/hunter-packages/gate#usage-custom-config

**Comment by ruslo** [comment]
> Also the wiki page about this macro states that it shouldn't really be used normally

This is a "error" page. It means you have used it wrongly, hopefully it will guide users how to use it correctly :)
