### ISSUE TITLE
Why is there a FindPNG.cmake file? 

### ISSUE THREAD

**Issue by aybassiouny** [ruslo/hunter#518]
Cmake has its own nice FindPNG.cmake. The file under hunter/cmake/find actually failed my build for [https://github.com/davisking/dlib](url) under windows since `PNG_ROOT` is not defined under windows. Deleting the file fixed my build. 

Any reason this file is there? It should not override cmake's findpng at least, right? :)

**Comment by ruslo** [comment]
> Any reason this file is there?

> It should not override cmake's findpng at least, right? :)

No it should. That's the reason why it's there. Something was not working with default FindPNG I guess. Also I recommend you to use `find_package(PNG CONFIG REQUIRED)`: https://github.com/ruslo/hunter/wiki/pkg.png.

> The file under hunter/cmake/find actually failed my build for https://github.com/davisking/dlib

There is already `dlib` build in Hunter and it works for Windows: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.807

Feel free to send pull request with FindPNG updates. If tests will pass I will merge it.

**Comment by aybassiouny** [comment]
Oh didn't realize there's a hunter png package, nice
