### ISSUE TITLE
Create Package from precompiled tar.gz and zip files

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#519]
I want to create a package, but I only have precompiled tar.gz or zip files. Is it possible to add them to a hunter package and download the right version (os, compiler)?
There is a precompiled tar-ball for each os-architecture-compiler combination

currently I'm using a SuperBuild schema. 
To define CMAKE_ARCH if use the following [script](https://github.com/axr/solar-cmake/blob/master/TargetArch.cmake).

First I define the download link as follows:

```
set(url_base ${SuperBuild_DOWNLOAD_BASE_URL})

# foolib
list(APPEND projects foo)
set(foolib_version "2.0.802")
if (CMAKE_ARCH STREQUAL "x86_64")
    set(foo_arch "x86_64")
elseif(CMAKE_ARCH STREQUAL "i386")
    set(foo_arch "x86")
elseif(CMAKE_ARCH MATCHES "(arm)|(armv5)|(armv6)|(armv7)")
    set(foo_arch "arm")
else()
    message(FATAL_ERROR "foo unknown architecture: ${CMAKE_ARCH}")
endif()
if(WIN32)
    set(foo_os "windows")
elseif(UNIX AND NOT APPLE)
    set(foo_os "linux")
else()
    message(FATAL_ERROR "foo unknown OS (not windows and not linux")
endif()
set(foo_url_base "${url_base}/foolib")
set(foo_url "${foo_url_base}/${foolib_version}/fooblib-${foolib_version}-${foo_arch}-${foo_os}-factory.tar.gz")
```

Then I define an External Project with an URL (but without sha-checksum).

```
set(_install "${SuperBuild_INSTALL_PREFIX}")

ExternalProject_Add(foo
    URL ${foo_url}
    UPDATE_COMMAND ""
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND ${CMAKE_COMMAND} -E make_directory ${_install}
        COMMAND ${CMAKE_COMMAND} -E copy_directory <SOURCE_DIR>/interface/c ${_install}/include
        COMMAND ${CMAKE_COMMAND} -E copy_directory <SOURCE_DIR>/interface/cpp ${_install}/include
        COMMAND ${CMAKE_COMMAND} -E copy_directory <SOURCE_DIR>/library ${_install}/lib
    LOG_DOWNLOAD 1
    LOG_INSTALL 1
)

list(APPEND CMAKE_FIND_ROOT_PATH
    "${CMAKE_SOURCE_DIR}/cmake"
)
```

There are some custom copy commands because the archives have the following architecture:

```
- interface
  - c # c-interface
  - cpp # cpp interface
  - python # python interface
- library (the compiled c-libraries, *.so* for linux, *.dll for windows tar-ball)
```

I copy the usefull headerfiles into the `/include` folder and the libraries into the `/lib` folder
##

**Comment by ruslo** [comment]
> I want to create a package, but I only have precompiled tar.gz or zip files. Is it possible to add them to a hunter package and download the right version (os, compiler)?

Yes, take a look at `url_sha1_unpack_install` scheme. In case it's not just copy-to-the-final-directory code then probably you need to introduce new scheme. Also note that Hunter do support binaries upload so everything you have here can be done automatically. Do you have source code for such library? Is it public?

**Comment by NeroBurner** [comment]
Unfortunately it is a private closed source library, so I can't provide a link

Could you guide me to documentations on the binaries upload feature?
The [wiki-faq](https://docs.hunter.sh/en/latest/faq/why-binaries-from-server-not-used.html) entry is only about binary incompatibility and thus local rebuilds.

Things I'm currently unclear about:
- How do the cache servers work?
  - When and how are binaries uploaded to the cache servers?
- can I host a cache server on a private Gitlab server? Or is it Github only?

**Comment by ruslo** [comment]
> Unfortunately it is a private closed source library, so I can't provide a link

Actually I think you can build it and upload binaries without sharing sources. If you provide valid SHA1 and invalid URL only binaries from server will be used (probably new mark can be introduced here). Though logic about cache hit is more pedantic than just `arm` vs `x86` vs `x86_64` vs etc.

> Could you guide me to documentations on the binaries upload feature?

It a part of the FAQ: https://docs.hunter.sh/en/latest/faq/why-binaries-from-server-not-used.html Will move it to the appropriate location in future :)

> can I host a cache server on a private Gitlab server?

What part of the code you want to be private?

> Or is it Github only?

For now yes. But in general any server with files available by `file(DOWNLOAD)` can work.

**Comment by NeroBurner** [comment]
I'm taking another shot at this, but for now without the binary cache server. I'v seen that in the generated `toolchain.info` there is a define `#define __amd64 1` and one `#define __x86_64 1`. Is there also one for arm?

Can I use this information in a custom hunter package to decide which tarball to download? I'm thinking about something like the following
```
set(_mypkg_name "mypkg")
set(_mypkg_version "1.0.2")
if(win32)
	if(amd64)
		hunter_add_version(
			PACKAGE_NAME
			${_mypkg_name}
			VERSION
			${_mypkg_version}
			URL
			"http://example.com/mypgk/1.0.1/mypkg-1.0.2-x86_64-windows.zip"
			SHA1
			somesha1sum
		)
	else if(x86)
		hunter_add_version(
			PACKAGE_NAME
			${_mypkg_name}
			VERSION
			${_mypkg_version}
			URL
			"http://example.com/mypgk/1.0.1/mypkg-1.0.2-x86-windows.zip"
			SHA1
			somesha1sum
		)
	else()
		# Error
	endif()
else() # assume linux
	if(amd64)
		hunter_add_version(
			PACKAGE_NAME
			${_mypkg_name}
			VERSION
			${_mypkg_version}
			URL
			"http://example.com/mypgk/1.0.1/mypkg-1.0.2-x86_64-linux.zip"
			SHA1
			somesha1sum
		)
	else if(x86)
		hunter_add_version(
			PACKAGE_NAME
			${_mypkg_name}
			VERSION
			${_mypkg_version}
			URL
			"http://example.com/mypgk/1.0.1/mypkg-1.0.2-x86-linux.zip"
			SHA1
			somesha1sum
		)
	else if(armv7)
		hunter_add_version(
			PACKAGE_NAME
			${_mypkg_name}
			VERSION
			${_mypkg_version}
			URL
			"http://example.com/mypgk/1.0.1/mypkg-1.0.2-arm-linux.zip"
			SHA1
			somesha1sum
		)
	else()
		# Error
	endif()
endif()
```

as second question: the tar file contains a mypkg_config.cmake file. Currently to use the library I extract the tarball and then set the cmake variable `mypkg_DIR`. For example
```
cmake .. -Dmypkg_DIR=~/mypkg/interface/cpp
```

can I do something simmilar in Hunter?

**Comment by ruslo** [comment]
> Is there also one for arm?

Tons of them :) Take a look here: https://github.com/ruslo/hunter/blob/250d688ce57a87a2ac7de45d3ddc4683d959af3c/scripts/predefined.list

> Can I use this information in a custom hunter package to decide which tarball to download? I'm thinking about something like the following

You can use standard CMake variables like `WIN32`/`APPLE`. I'm not sure about variables describing architectures. Need to investigate.

> Currently to use the library I extract the tarball and then set the cmake variable mypkg_DIR.

CMake provide all mechanisms to create relocatable package. I think you should use them instead of introducing extra functionality in Hunter. You can start from here:
* https://github.com/ruslo/hunter/wiki/usr.adding.new.package#important

there are few links to docs and examples.

**Comment by NeroBurner** [comment]
o.O that are really tons of defines!

> You can use standard CMake variables like WIN32/APPLE. I'm not sure about variables describing architectures. Need to investigate.

The easiest way I've found is this [TargetArch-script](https://github.com/axr/solar-cmake/blob/master/TargetArch.cmake). Copy it to `${HUNTER_ROOT}/scripts/TargetArch.cmake` and then use it in the hunter-package-definition as follows
```
include("${HUNTER_ROOT}/scripts/TargetArch.cmake")
target_architecture(TARGET_ARCH)

if(win32)
	...
else() # assume LINUX
	if(TARGET_ARCH STREQUAL "x86_64")
		set(mypkg_URL "http://example.com/mypgk-amd64-linux.tar.gz")
		set(mypkg_SHA1 somesha1sumforamd64)
	elseif(TARGET_ARCH STREQUAL "i386")
		set(mypkg_URL "http://example.com/mypgk-i386-linux.tar.gz")
		set(mypkg_SHA1 somesha1sumfori386)
	elseif(TARGET_ARCH  MATCHES "(arm)|(armv5)|(armv6)|(armv7)")
		set(mypkg_URL "http://example.com/mypgk-arm-linux.tar.gz")
		set(mypkg_SHA1 somesha1sumforarm)
	else()
		hunter_fatal_error("mypkg: target architecture not provided: ${TARGET_ARCH}")
	endif()
endif()
hunter_add_version(
	PACKAGE_NAME
	mypkg
	VERSION
	1.0.2
	URL
	"${mypkg_url}"
	SHA1
	${mypkg_SHA1}
)
set(mypkg_URL)
set(mypkg_SHA1)
```

> CMake provide all mechanisms to create relocatable package. I think you should use them instead of introducing extra functionality in Hunter. You can start from here:

I may have chosen a bad example name. `mypkg` is not under my controll, I only have precompiled tarballs. The `mypkg_config.cmake` file in `interface/cpp` is (as far as I know) manually written. But it provides a self contained way to use the library. The  `mypkg_config.cmake` file automatically compiles a CPP wrapper for the C library.

I'm looking for a way to tell hunter to search for the `mypkg_config.cmake` file in `<mypkg_install_folder>/interface/cpp`. Then The user can use `find_package(mypkg)` when using hunter, an extracted tarball of mypkg or a system wide installed one.

**Comment by ruslo** [comment]
> The easiest way I've found is this TargetArch-script

Can you check if [CMAKE_SYSTEM_PROCESSOR](https://cmake.org/cmake/help/latest/variable/CMAKE_SYSTEM_PROCESSOR.html) fits? Also `CMAKE_SYSTEM_NAME` is equal `Linux` on Linux.

> I'm looking for a way to tell hunter to search for the mypkg_config.cmake file in `<mypkg_install_folder>/interface/cpp`

There are a few standard places where CMake will search for config file. Hunter will set CMAKE_PREFIX_PATH to `<root-id>/Install` so if you will install mypkg_config.cmake to `lib/cmake/mypkg/mypkg_config.cmake` then it will be found by `find_package`.

As alternative you have direct access by `${MYPKG_ROOT}/interface/cpp/mypkg_config.cmake` on user's side and you can do what you want with it.

**Comment by NeroBurner** [comment]
on a i386 schroot the variable `CMAKE_SYSTEM_PROCESSOR` is still on `x86_64`. So unfortunately this solution doesn't fit my needs.

May be tested with following simple project:
```
cmake_minimum_required(VERSION 2.8.12) 
project(TestCakeVariables CXX) 
 
message("CMAKE_SYSTEM_PROCESSOR ${CMAKE_SYSTEM_PROCESSOR}") 
```

**Comment by ruslo** [comment]
> on a i386 schroot the variable CMAKE_SYSTEM_PROCESSOR is still on x86_64

Sad, but I kind of expect it :(

> The easiest way I've found is this TargetArch-script.

Actually I think it make sense to start discussion in CMake mailing list since such feature can be useful for all CMake users, not just Hunter.

As for some workaround for now I think we can search for C++ macro in `toolchain.info` file. Such feature can be wrapped with function:

```cmake
# hunter.cmake
hunter_toolchain_cpp_define(SYMBOL "__arm__" DEFINED _arm_defined)
if(_arm_defined)
  # ARM stuff
endif()
```

**Comment by NeroBurner** [comment]
That would be awesome!

**Comment by ruslo** [comment]
Closing inactive discussion.
