### ISSUE TITLE
Doc: Create HunterGate archive

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#520]
I wasn't able to find a wiki entry on how to create a HunterGate archive.

The [wiki entry](https://github.com/ruslo/hunter/wiki/usr.adding.new.package.custom.scheme#03-add-new-package) for how to create a new custom (non cmake package) has a dead link to a note about directories layout

My questions:
- Is there a wiki entry I have missed on how to create a HunterGate Archive file?
- Is there a specific layout the archive.tar.gz file for the HunterGate call has to fulfill?
- How is the official HunterGate Archive file created?
##

**Comment by ruslo** [comment]
> I wasn't able to find a wiki entry on how to create a HunterGate archive.

It's just a release snapshot of this repository: https://github.com/ruslo/hunter/releases

If you want to run tests please use this wiki info about jenkins.py: https://github.com/ruslo/hunter/wiki/dev.hunter.root#jenkinspy. I recommend you to have separate cloned git repository which is not linked to the default HUNTER_ROOT directory.

**Comment by ruslo** [comment]
Closing inactive discussion.
