### ISSUE TITLE
[Boost] conflict with --layout when auto_link is enabled

### ISSUE THREAD

**Issue by wisk** [ruslo/hunter#522]
Hi there,

I'm facing an issue on Windows when I use the package Boost.
I got the following error message when I compiled:
```
 LINK : fatal error LNK1104: cannot open file 'libboost_filesystem-vc140-mt-1_61.lib'
```
The CMakeLists.txt relies on ``Boost::boost``, ``Boost::filesystem``, ``Boost::system`` and ``Boost::program_options``.
If I take a look on generated libraries I've the file **libboost_filesystem-vc140-mt.lib** present(, notice the absence of boost version in the filename).
I dump the property LOCATION for the target Boost::filesystem and get:
```
Boost::filesystem LOCATION = C:/Users/wisk/.hunter/_Base/7b6ced4/2bd496d/90ae7c9/Install/lib/libboost_filesystem-mt.lib
```
Once again the version is missing.
I was wondering how ``cl`` could try to link against a filename with a version appended where the property tells the filename hasn't.
I start to dig bjam options and figure out the switch ``--layout`` is ``tagged``, according the ``hunter.cmake`` (https://github.com/ruslo/hunter/blob/master/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L223). This layout doesn't append the version on the lib filename.
I tried to define BOOST_ALL_NO_LIB as a workaround but no chance here.

Aaand, I might finally find out the root cause: in the file url_sha1_boost.cmake.in, the ``--layout`` option is defined as a ``INSTALL_COMMAND`` where (, if I understand correctly,) it should be in ``BUILD_COMMAND``.
This scheme is in charge to handle the target ``Boost::boost`` which I included in my CMakeLists.txt, if I remove it, the linking works like a charm.
My hypothesis is that, since I included ``Boost::boost`` and ``--layout`` is not set in the ``BUILD_COMMAND``, it uses the default layout (, which is ``versioned`` on Windows). Because of the auto-link feature, the header generates ``#pragma comment(link, ...)`` with the ``versioned`` lib filename (i.e. with the version appended). That's cause a conflict between other libraries with are correctly set as ``tagged`` layout.

I see 2 potentials fixes here:
- set ``--layout`` option in ``BUILD_COMMAND`` should fix the issue,
- forbid ``Boost::boost`` when at least one boost component is used.
I didn't try to first fix, I'll give a try later.

Sorry for the long issue, I hope it could help someone else.

**Comment by ruslo** [comment]
Can you provide an simple example? There are system, filesystem, iostreams, thread, chrono, serialization testing on Windows and it looks well: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.923

>  LINK : fatal error LNK1104: cannot open file 'libboost_filesystem-vc140-mt-1_61.lib'

This kind of error usually can be fixed by `BOOST_ALL_NO_LIB`, which is added automatically by Hunter when you use imported `Boost::*` targets: https://github.com/ruslo/hunter/blob/c8feaa4a6b50bb7f475625930f2beef970d930af/cmake/templates/BoostConfig.cmake.in#L39 (all libraries linked to Boost::boost).

As wiki page states for compatibility `Boost_LIBRARIES` variant you have to add it yourself: https://github.com/ruslo/hunter/wiki/pkg.boost#compatibility-mode

**Comment by wisk** [comment]
That's embarrassing, I made a smaller example and it works as expected.
I don't know why I'm facing this issue in my bigger project.
Adding manually ``add_definitions("-DBOOST_ALL_NO_LIB=1")`` fixes this issue.
For some reason, it seems it wasn't defined by hunter.
I close this issue for now since it looks to come from my CMake scripts.

Sorry for the noise.

**Comment by ruslo** [comment]
> Adding manually add_definitions("-DBOOST_ALL_NO_LIB=1") fixes this issue

If you're using `find_package(Boost CONFIG REQUIRED ...)` and `Boost::*` targets then `BOOST_ALL_NO_LIB=1` should be added by Hunter automatically. One scenario I know about is when your package use Boost at C++ level but doesn't express this in CMake level. I.e. you have `#include <boost/filesystem.hpp>` but no `target_link_libraries(... Boost::filesystem)`.
