### ISSUE TITLE
Hunter project flatbuffers not found

### ISSUE THREAD

**Issue by ahundt** [ruslo/hunter#525]
I tried running hunter with flatbuffers and got the following error:

```
-- [hunter] Initializing Hunter workspace (53b198e364dc7bc8360fc545f798563229bd7e20)
-- [hunter]   https://github.com/ruslo/hunter/archive/v0.10.9.tar.gz
-- [hunter]   -> /Users/athundt/.hunter/_Base/Download/Hunter/0.10.9/53b198e
-- [hunter] Calculating Config-SHA1
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] HUNTER_ROOT: /Users/athundt/.hunter
-- [hunter] [ Hunter-ID: 53b198e | Config-ID: 1c72480 | Toolchain-ID: a651279 ]

[hunter ** INTERNAL **] Project 'flatbuffers' not found
[hunter ** INTERNAL **] [Directory:/Users/athundt/source/distributed_systems_cs437]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at /Users/athundt/.hunter/_Base/Download/Hunter/0.10.9/53b198e/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /Users/athundt/.hunter/_Base/Download/Hunter/0.10.9/53b198e/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  /Users/athundt/.hunter/_Base/Download/Hunter/0.10.9/53b198e/Unpacked/cmake/modules/hunter_add_package.cmake:30 (hunter_internal_error)
  CMakeLists.txt:31 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "/Users/athundt/source/distributed_systems_cs437/build/CMakeFiles/CMakeOutput.log".
```

I based this off of the [example script](https://github.com/ruslo/hunter/blob/develop/examples/flatbuffers/CMakeLists.txt), and the repository it appears it should clone seems to be a bit out of date compared to the mainline flatbuffers repository.

This is on OS X 10.11.6.

**Comment by ruslo** [comment]
> I tried running hunter with flatbuffers and got the following error

Use newer version of archive: https://github.com/ruslo/hunter/releases

> the repository it appears it should clone seems to be a bit out of date compared to the mainline flatbuffers repository

Feel free to update, see details: https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html#maintenance

**Comment by ahundt** [comment]
I've created a [pull request to merge these patches upstream](https://github.com/google/flatbuffers/pull/4035). Would that be worthwhile to you? 

It seems all comitters would need to [sign a contributors license agreement](https://cla.developers.google.com/) with google before they will accept the pull request however. Alternatively I could reimplement equivalent changes myself since I've already signed the agreement.

**Comment by ruslo** [comment]
> I've created a pull request to merge these patches upstream. Would that be worthwhile to you? 

Yes, thank you, merged. What version number is it?

> It seems all comitters would need to sign a contributors license agreement with google before they will accept the pull request however.

I already signed it:

---
![signed](https://cloud.githubusercontent.com/assets/4346993/18816905/bbebdd0e-835b-11e6-9ceb-1f24c2adb0bf.png)
---

@headupinclouds David, can you please take a look? You need to login with email used in your commits and sign https://cla.developers.google.com/.

**Comment by ahundt** [comment]
@ruslo How do I configure my hunter version to point to the flatbuffers change I just specified? That merge was actually to master, which is 63 commits beyond the most recent [flatbuffers release 1.4.0](https://github.com/google/flatbuffers/releases/tag/v1.4.0). Perhaps it should actually be set on 1.4.0 proper?  

@headupinclouds would you be willing to sign the google CLA to merge your flatbuffers changes to the upstream flatbuffers repository?

**Comment by ruslo** [comment]
> How do I configure my hunter version to point to the flatbuffers change I just specified?

I will make release of hunter-packages/flatbuffers and you can use it to create pull request for Hunter.

> Perhaps it should actually be set on 1.4.0 proper?

Not a bad idea. Will you do it?

**Comment by ahundt** [comment]
> Not a bad idea. Will you do it?

Not sure how to roll back the changes so they can be merged again in the future. I've only done it when I have full repo control and can force push dropping a bunch of commits. Any suggestions or links to instructions?

I found the [link for adding packages](https://github.com/ruslo/hunter/wiki/usr.adding.new.package), and the [file I need to modify](https://github.com/ruslo/hunter/blob/master/cmake/projects/flatbuffers/hunter.cmake). Seems doable once the github fix is figured out.

**Comment by ruslo** [comment]
> I've only done it when I have full repo control and can force push dropping a bunch of commits

I've sent you an invitation to the team. Once accepted (check your email) you can do force pushes and create releases.

**Comment by ruslo** [comment]
> I found the link for adding packages

Package is already in system, you don't have to create it from scratch, just update.

> and the file I need to modify

Yep, this file. And don't forget to set default version to `cmake/configs/default.cmake`.

> Seems doable once the github fix is figured out.

Also take a look at this page about `jenkins.py` testing script: https://github.com/ruslo/hunter/wiki/dev.hunter.root#jenkinspy

**Comment by ahundt** [comment]
I created a branch that only includes flatbuffers 1.4.0:
https://github.com/ahundt/flatbuffers/tree/v1.4.0-hunter

**Comment by ruslo** [comment]
> I created a branch that only includes flatbuffers 1.4.0

You have permissions now to push it to https://github.com/hunter-packages/flatbuffers and make a release.

**Comment by ahundt** [comment]
https://github.com/ruslo/hunter/pull/529

Should resolve:
https://github.com/ruslo/hunter/issues/525

However, I think this item #525 should remain open until the following is merged to the upstream flatbuffers:
https://github.com/google/flatbuffers/pull/4035

When that happens the upstream version should be used by default.

**Comment by ruslo** [comment]
> is merged to the upstream flatbuffers: google/flatbuffers#4035

I think you sent some unintended patched there.

**Comment by headupinclouds** [comment]
> headupinclouds would you be willing to sign the google CLA to merge your flatbuffers changes to the upstream flatbuffers repository?

Sure.  I won't be able to do this today, but will try to get this out tomorrow.

**Comment by ruslo** [comment]
Closing inactive discussion.
