### ISSUE TITLE
Delete hunter lock-files

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#530]
After aborting a hunter-download and build of a dependency (boost) hunter doesn't want to start again. I have found mentions about the usage of lock files in the hunter directory 
[here](https://docs.hunter.sh/en/latest/overview/shareable.html) and [here](https://github.com/ruslo/hunter/wiki/error.can.not.lock)

The first time (under linux) I just deleted the `.hunter` folder. The second time (under windows) I used the define `HUNTER_SKIP_LOCK=ON`

Have I missed some documentation on how hunter locks the .hunter directory? Does it lock the whole directory, just a specific project (Boost, ...) or something else?

How are those cmake interruptions during hunter download and hunder compilation handled?

**Comment by ruslo** [comment]
> hunter doesn't want to start again

What do you mean? It crashes or hangs on trying to acquire the lock?

> Have I missed some documentation on how hunter locks the .hunter directory?

You don't need to know the details. Hunter doesn't lock the whole directory, just the directories that currently are "under contruction".

> How are those cmake interruptions during hunter download and hunder compilation handled?

Correctly :) Lock released after user hit `Ctrl+C`. `file(LOCK ...)` documentation is here: https://cmake.org/cmake/help/latest/command/file.html

**Comment by NeroBurner** [comment]
I was compiling in a Windows Virtual machine. It takes a long time at:
```
[ 25%] Performing download step (download, verify and extract) for 'Boost'
```
So long that I thought it was locked by a previous aborted call. I don't know if it is the slow disc access in the virtual machine or cmake under windows, but under Linux these steps finish much faster

> You don't need to know the details. Hunter doesn't lock the whole directory, just the directories that currently are "under contruction".

I'm very happy to hear that only busy directories are locked.

Do you know what happens when a cmake process is force closed (for example with `killall -9 cmake`? Are the directories then locked or are the locks released somehow?

**Comment by ruslo** [comment]
> I don't know if it is the slow disc access in the virtual machine or cmake under windows, but under Linux these steps finish much faster

I have quite the same experience. I don't know what is the problem. I guess that it's about Boost release archive which contains a lot of junk with long paths. Though I'm not sure :) Binary cache is a huge time/space saver in this situation since it contains minimal amount of necessary parts.

> Do you know what happens when a cmake process is force closed (for example with killall -9 cmake? Are the directories then locked or are the locks released somehow?

Lock will be released, this is a responsibility of OS itself.
