### ISSUE TITLE
Multiple hunter packages in single project

### ISSUE THREAD

**Issue by xsacha** [ruslo/hunter#531]
I have found that doing a hunter_add_package on a hunter package such as OpenCV or CURL then downloads and uses a completely different version of hunter and then the dependencies are downloaded using that hunter and ignore my config.cmake.
This is true of all packages that are dependent on other hunter packages.
At best, this downloads multiple versions of hunter for no reason. At worst, this ends up linking multiple versions of the same library to an executable where this was not desired or breaks packages that were expecting different versions to be linked.

I think that hunter packages do not need a HunterGate because the top-level project that performed the hunter_add_package would have already used one -- guaranteed. Otherwise, if there is not a guarantee for whatever reason, it should at least check if HUNTER_HOST_URL / HUNTER_HOST_SHA1 has already been used.

**Comment by ruslo** [comment]
> This is true of all packages that are dependent on other hunter packages.

As far as I know it's not true. Please provide simple example with logs. HunterGate settings from top-level project will be inherited by all subprojects (both added by `add_subdirectory` or 3rd parties from Hunter).

> it should at least check if HUNTER_HOST_URL / HUNTER_HOST_SHA1 has already been used

Are we talking about `hunter_experimental_add_host_project`?

**Comment by xsacha** [comment]
For example, I use hunter_add_package(CURL) and then CURL uses its own hunter and does a hunter_add_package(OpenSSL).
In my config.cmake, I specified OpenSSL VERSION 1.1.0a, however, CURL now grabs 1.0.2i and ignores my config.cmake. I end up with 1.1.0a elsewhere in my project as well as 1.0.2i, via CURL.

**Comment by ruslo** [comment]
@xsacha Using combination of GitHub and Hunter it's kind of a trivial task to create example which reproduce an issue. Please do it.

If you take a look at [one of the testings logs](https://travis-ci.org/ingenue/hunter/jobs/157834412) you may notice that all libraries came from one `bad4e20` Hunter-ID:

```
/usr/bin/g++-4.8
    -std=c++11
    -O3
    -DNDEBUG
    CMakeFiles/foo.dir/foo.cpp.o
    -o
    foo
    -rdynamic
    /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/bad4e20/5b11d99/8928885/Install/lib/libcurl.a
    -lidn
    -llber
    -lldap
    /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/bad4e20/5b11d99/8928885/Install/lib/libssl.a
    /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/bad4e20/5b11d99/8928885/Install/lib/libcrypto.a
    -ldl
    /home/travis/build/ingenue/hunter/_testing/Hunter/_Base/bad4e20/5b11d99/8928885/Install/lib/libz.a
```

**Comment by xsacha** [comment]
OK, it works in the ingenue branch so must be an issue on my end.

Thanks
