### ISSUE TITLE
Boost on windows fails on first build

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#533]
I've created a simple example project, which shows that hunter fails to compile boost on first try under Windows 7
https://gist.github.com/NeroBurner/f24952848c9f049441860a1f58a4f055
Just download and add the `cmake/HunterGate.cmake` file in the example project folder

Build instructions under Windows 7 with Visual Studio 12.0 Express and cmake 3.5.2 installed
- open cmd.exe

```
"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x86_amd64
cd <path_to_example_project>
mkdir build
cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release
```

The call errors with the following message

```
...
-- Generating done
-- Build files have been written to: C:/.hunter/_Base/7849ccc/1a169c2/4d6ae23/Bu
ild/Boost/Build
Scanning dependencies of target Boost
[ 12%] Creating directories for 'Boost'
[ 25%] Performing download step (download, verify and extract) for 'Boost'
-- Boost download command succeeded.  See also C:/.hunter/_Base/7849ccc/1a169c2/
4d6ae23/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-download-*.log
[ 37%] No update step for 'Boost'
[ 50%] No patch step for 'Boost'
[ 62%] Performing configure step for 'Boost'
-- Boost configure command succeeded.  See also C:/.hunter/_Base/7849ccc/1a169c2
/4d6ae23/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-configure-*.log
[ 75%] No build step for 'Boost'
[ 87%] Performing install step for 'Boost'
CMake Error at C:/.hunter/_Base/7849ccc/1a169c2/4d6ae23/Build/Boost/Build/Boost-
prefix/src/Boost-stamp/Boost-install-Debug.cmake:16 (message):
  Command failed: 1

   'C:/Program Files (x86)/CMake/bin/cmake.exe' '-Dmake=' '-Dconfig=' '-P' 'C:/.
hunter/_Base/7849ccc/1a169c2/4d6ae23/Build/Boost/Build/Boost-prefix/src/Boost-st
amp/Boost-install-Debug-impl.cmake'

  See also

    C:/.hunter/_Base/7849ccc/1a169c2/4d6ae23/Build/Boost/Build/Boost-prefix/src/
Boost-stamp/Boost-install-*.log


NMAKE : fatal error U1077: 'echo' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 12.0
\VC\BIN\nmake.exe"' : return code '0x2'
Stop.

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/7849ccc/1a16
9c2/4d6ae23/Build/Boost
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.15.33/7
849ccc/Unpacked/cmake/projects/Boost]
```

Boost-configure-out.log reads:

```
The specified configuration type is missing.  The tools for the
configuration might not be installed.
Building Boost.Build engine

Failed to build Boost.Build engine.
Please consult bootstrap.log for further diagnostics.

You can try to obtain a prebuilt binary from

   http://sf.net/project/showfiles.php?group_id=7586&package_id=72941

Also, you can file an issue at http://svn.boost.org 
Please attach bootstrap.log in that case.
```

Boost-configure-err.log is empty
Boost-install-out.log is empty
Boost-install-err.log reads

```
CMake Error at C:/.hunter/_Base/7849ccc/1a169c2/4d6ae23/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake:9 (message):
  Command failed (The system cannot find the file specified):

   'b2' '--layout=tagged' '-d0' 'install' '--without-atomic' '--without-chrono' '--without-container' '--without-context' '--without-coroutine' '--without-coroutine2' '--without-date_time' '--without-exception' '--without-filesystem' '--without-graph' '--without-graph_parallel' '--without-iostreams' '--without-locale' '--without-log' '--without-math' '--without-metaparse' '--without-mpi' '--without-program_options' '--without-python' '--without-random' '--without-regex' '--without-serialization' '--without-signals' '--without-system' '--without-test' '--without-thread' '--without-timer' '--without-type_erasure' '--without-wave' '--prefix=C:/.hunter/_Base/7849ccc/1a169c2/4d6ae23/Build/Boost/Install'
```

I can't find those logs after the second build to compare the outputs

As a side note: As soon as I'm using a boost component (not hust header only) I need to add the define `-DBOOST_ALL_NO_LIB` under Windows. The linker otherwise does not find the linked boost libraries. But I think a seperate issue should be used for that discussion

Edit: the second build successfully builds boost

**Comment by ruslo** [comment]
> cmake_minimum_required(VERSION 2.8)

Minimum version is 3.0: https://docs.hunter.sh/en/latest/quick-start/cmake.html

> cmake .. -G "NMake Makefiles" -DCMAKE_BUILD_TYPE=Release

As you may notice there is no `nmake` toolchain in testing:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1010

If you take a look at appveyor.yml then you will see that `nmake` is commented out:
* https://github.com/ingenue/hunter/blob/b658f82c4620eafd11c7f20fc123b0170344b8f6/appveyor.yml#L21-L23

Which means that it's a kind of a known issue. So feel free to fix.

> As soon as I'm using a boost component (not hust header only) I need to add the define -DBOOST_ALL_NO_LIB under Windows. The linker otherwise does not find the linked boost libraries. But I think a seperate issue should be used for that discussion

This is not an issue, please take a look carefully at pkg.boost:
* https://github.com/ruslo/hunter/wiki/pkg.boost

If you're using `find_package(Boost CONFIG ...)` then Hunter will add this macro automatically. If you're using `find_package(Boost ...)` without CONFIG you have to add it yourself.

> Edit: the second build successfully builds boost

I don't know what is the reason of this. Sounds strange.

**Comment by NeroBurner** [comment]
>>     cmake_minimum_required(VERSION 2.8)

> Minimum version is 3.0: https://docs.hunter.sh/en/latest/quick-start/cmake.html

Does Hunter react to the actual cmake version or the minimum required cmake version? I'd like to be able to choose if I use the hunter package on Ubuntu 14.04, Ubuntu 16.04 or Windows.
On Windows and Ubuntu 16.04 this should be no problem, but on Ubuntu 14.04 the default cmake version is 2.8.12. If I want to build on the standard cmake Version I need to define the minimum required version <= 2.8.12 and not include HunterGate

**Comment by ruslo** [comment]
Put the absolute minimum at the start (it's `cmake_minimum_required(VERSION 2.8)`) then analyze `CMAKE_VERSION` variable. E.g.:
```cmake
cmake_minimum_required(VERSION 2.8.12)

option(HUNTER_ENABLED ...)

if(CMAKE_VERSION VERSION_LESS "3.0")
  if(HUNTER_ENABLED)
    message(FATAL_ERROR "3.0 required ...")
  endif()
else()
  include("cmake/HunterGate.cmake")
  HunterGate(URL ... SHA1 ...)
endif()
```
