### ISSUE TITLE
OpenCV Package broken on Ubuntu 16.04 LTS?!

### ISSUE THREAD

**Issue by floschne** [ruslo/hunter#539]
Hi,

I tried to build a small sample project using OpenCV and Boost.

My CMakeLists.txt looks like this:
[CMakeLists.txt](https://github.com/ruslo/hunter/files/513887/CMakeLists.txt)

I tried to run with the following command on **two different machines running Ubuntu 16.04 multiple times and always get the same error**.
## Build Command:

`cmake -H. -BbuildDebug -DHUNTER_STATUS_DEBUG=ON -DCMAKE_BUILD_TYPE=DEBUG
cmake --build buildDebug --config Debug`
## Error Message:

`/usr/bin/ld: /home/visy/.hunter/_Base/53b198e/1c72480/fcae049/Install/lib/libpng.a(png.c.o): relocation R_X86_64_32 against`.rodata.str1.8' can not be used when making a shared object; recompile with -fPIC
/home/visy/.hunter/_Base/53b198e/1c72480/fcae049/Install/lib/libpng.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
modules/python2/CMakeFiles/opencv_python2.dir/build.make:248: recipe for target 'lib/cv2.so' failed
make[5]: **\* [lib/cv2.so] Error 1
make[5]: Leaving directory '/home/visy/.hunter/_Base/53b198e/1c72480/fcae049/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build'
CMakeFiles/Makefile2:4116: recipe for target 'modules/python2/CMakeFiles/opencv_python2.dir/all' failed
make[4]: **\* [modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make[4]: Leaving directory '/home/visy/.hunter/_Base/53b198e/1c72480/fcae049/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build'
Makefile:152: recipe for target 'all' failed
make[3]: **\* [all] Error 2
make[3]: Leaving directory '/home/visy/.hunter/_Base/53b198e/1c72480/fcae049/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build'
CMakeFiles/OpenCV-Release.dir/build.make:76: recipe for target 'OpenCV-Release-prefix/src/OpenCV-Release-stamp/OpenCV-Release-install' failed
make[2]: **\* [OpenCV-Release-prefix/src/OpenCV-Release-stamp/OpenCV-Release-install] Error 2
make[2]: Leaving directory '/home/visy/.hunter/_Base/53b198e/1c72480/fcae049/Build/OpenCV/Build'
CMakeFiles/Makefile2:107: recipe for target 'CMakeFiles/OpenCV-Release.dir/all' failed
make[1]: **\* [CMakeFiles/OpenCV-Release.dir/all] Error 2
make[1]: Leaving directory '/home/visy/.hunter/_Base/53b198e/1c72480/fcae049/Build/OpenCV/Build'
Makefile:86: recipe for target 'all' failed
make: **\* [all] Error 2

[hunter *\* FATAL ERROR **] Build step failed (dir: /home/visy/.hunter/_Base/53b198e/1c72480/fcae049/Build/OpenCV
[hunter *\* FATAL ERROR **] [Directory:/home/visy/.hunter/_Base/Download/Hunter/0.10.9/53b198e/Unpacked/cmake/projects/OpenCV]

------------------------------ WIKI -------------------------------
##     https://github.com/ruslo/hunter/wiki/error.external.build.failed

CMake Error at /home/visy/.hunter/_Base/Download/Hunter/0.10.9/53b198e/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  /home/visy/.hunter/_Base/Download/Hunter/0.10.9/53b198e/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  /home/visy/.hunter/_Base/Download/Hunter/0.10.9/53b198e/Unpacked/cmake/modules/hunter_download.cmake:384 (hunter_fatal_error)
  /home/visy/.hunter/_Base/Download/Hunter/0.10.9/53b198e/Unpacked/cmake/projects/OpenCV/hunter.cmake:118 (hunter_download)
  /home/visy/.hunter/_Base/Download/Hunter/0.10.9/53b198e/Unpacked/cmake/modules/hunter_add_package.cmake:72 (include)
  CMakeLists.txt:23 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/home/visy/BachelorThesis/OCRScannerApp/buildDebug/CMakeFiles/CMakeOutput.log".
make: **\* No targets specified and no makefile found.  Stop.
`

Does anybody know what the problem is? Is it something I did wrong or isn't it supported for Ubuntu 16.04 LTS?

Thanks in advance!

**Comment by xsacha** [comment]
This isn't related to Ubuntu 16.04. Happens on every distro I have tried.

Solution is to use a toolchain that sets fPIC.

**Comment by xsacha** [comment]
The shared libraries that OpenCV links against need to have the same relocatable status (fPIC).
Something in the OpenCV build resets cxxflags when compiling dependencies (such as libpng in your situation).
Ultimately it is best if these flags are passed on but right now they are not. I recently fixed this in OpenSSL.

As a workaround, if you set the flag in your prochain (e.g. polly's gcc-pic),  it will override the flag and prevent it being reset.

**Comment by ruslo** [comment]
The original problem is about OpenCV building shared library (which is not default) and need static PNG library (which is by default static with no `-fPIC`). I think you can try disable those OpenCV component.

> Ultimately it is best if these flags are passed on but right now they are not. I recently fixed this in OpenSSL.

The issue with OpenSSL was about incomplete build scheme. The issue about OpenCV is different. Also as far as I understand OpenCV adds `-fPIC` always. Which is not good in my opinion (global flags should be set in toolchain, `-fPIC` is a global flag).

**Comment by floschne** [comment]
Thanks for your answers!
I will see if I can disable the OpenCV Component and report asap! 
I hope I wont run into the OpenSSL problem because I use both of the libraries in my Project. I think it will get even more complicated if I have to fix both of the problems.. But lets hope for the best ;-)

**Comment by ruslo** [comment]
> I hope I wont run into the OpenSSL problem because I use both of the libraries in my Project

OpenSSL issue was fixed.

**Comment by ruslo** [comment]
Closing inactive discussion.
