### ISSUE TITLE
dlib package does not build lib file.

### ISSUE THREAD

**Issue by caseymcc** [ruslo/hunter#543]
The dlib package does not build the static library when included into a project. The hunter-fied CMakeLists.txt does not include an "add_subdirectory(dlib)" adding the lib for build. Should this just be added to the hunter-fied CMakelists file or should there be an option added to build/not build the lib?

**Comment by ruslo** [comment]
Please discuss it's here: https://github.com/hunter-packages/dlib/issues/3
In short if you know how to fix it please send the patch.
