### ISSUE TITLE
Add 'rapidxml' package

### ISSUE THREAD

**Issue by roalz** [ruslo/hunter#546]
http://rapidxml.sourceforge.net/index.htm
A clone on GitHub: https://github.com/dwd/rapidxml

Note: headers-only, few header files.

(My personal doubt: does it even make sense to have it as Hunter package?)
##

**Comment by ruslo** [comment]
> My personal doubt: does it even make sense to have it as Hunter package?

Why not?

**Comment by roalz** [comment]
Another fork on github, this one with tags for official versions and added CMake build, that may be easier to include in Hunter.
https://github.com/timniederhausen/rapidxml

**Comment by ruslo** [comment]
Fixed by https://github.com/ruslo/hunter/pull/589
