### ISSUE TITLE
Android-clang for travis

### ISSUE THREAD

**Issue by xsacha** [ruslo/hunter#557]
Since android-gcc is deprecated and has not and will not be upgraded from 4.9, I think it would be a good idea to start building compatibility with android-clang.
For example: Boost compiles with android-gcc but not android-clang right now. In fact, the scheme specifically hardcodes the toolset to gcc if targeting Android.

Android-clang allows Android to compile more modern c++14/17 projects.

**Comment by ruslo** [comment]
Android Clang toolchain in Travis:
* https://github.com/ingenue/hunter/blob/74515c770f35182efa7f904a326d5989eca51414/.travis.yml#L37-L38
