### ISSUE TITLE
`URL/SHA1` for `hunter_config`

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#56]
Allow extension of space of versions by adding custom version with URL/SHA1 in `hunter_config`:

```
hunter_config(
    Foo
    VERSION 1.2.3new
    URL "https://.../1.2.3new.tar.gz"
    SHA1 "abc123..."
)
```
##

**Comment by ruslo** [comment]
Allow SHA1 of commit of git repo:
```cmake
hunter_config(Foo GIT_SHA1 xxx GIT_REPO https://.../Foo.git)
```

Allow getting GIT_SHA1 from submodule:
```cmake
hunter_config(Foo GIT_SUBMODULE)
```

**Comment by ruslo** [comment]
Implementation notes:
* [hunter_add_package](https://github.com/ruslo/hunter/blob/master/cmake/modules/hunter_add_package.cmake) need to detect that url and sha1 is provided by `hunter_config` and not by `hunter.cmake` and call `hunter_pick_scheme(DEFAULT url_sha1_cmake)` (supporting only CMake scheme) and `hunter_download` explicitly
* `hunter_config(... URL ... SHA1)` must set the same variables as a [hunter_add_version](https://github.com/ruslo/hunter/blob/master/cmake/modules/hunter_add_version.cmake) do, i.e. `HUNTER_<package>_URL` and `HUNTER_<package>_SHA1`
* version of the package should be equal to `SHA1` (`HUNTER_<package>_VERSION`)
* [hunter_calculate_config_sha1](https://github.com/ruslo/hunter/blob/master/cmake/modules/hunter_calculate_config_sha1.cmake) module need to find out that we are adding new package. Probably some new variable needed

Extra (related: https://github.com/ruslo/hunter/issues/138):
* script to package a project to 'tar.gz' archive, calculate SHA1 of archive and emit code for importing to config, like:
```
> hunter-dev.py --create-package /path/to/Foo
hunter_config(
    Foo
    URL /path/to/this/dir/Foo.tar.gz
    SHA1 xxxxx
)
> hunter-dev.py --create-package /path/to/Foo >> /path/to/local/config/cmake/Hunter/config.cmake
```

Note that every package creation will result new `<config-id>`, i.e. root will be rebuilt from scratch (cacheable packages will be unpacked from `Cache/raw/*.tar.gz` archive). Further improvements: https://github.com/ruslo/hunter/issues/204

**Comment by andoks** [comment]
This sounds very useful in scenarios where people using hunter need to patch one or two dependencies, but can't wait for upstream to incorporate the patch and release it, and for it then to be included in hunter.

**Comment by ruslo** [comment]
> people using hunter need to patch one or two dependencies

Yes, kind of. This feature may be used as a temporary workaround, it doesn't scale.

**Comment by ruslo** [comment]
`hunter_config(foo URL ... SHA1 ...)` form can be used since v0.21.19:
* https://github.com/ruslo/hunter/releases/tag/v0.21.19
