### ISSUE TITLE
Add 'grpc' RPC and networking library

### ISSUE THREAD

**Issue by fire** [ruslo/hunter#561]
Website: http://www.grpc.io/
Github: https://github.com/grpc/grpc

Notes: CMake build, depends on Protocol Buffers. 

Remote Procedure Calls (RPCs) provide a useful abstraction for building distributed applications and services. The libraries in this repository provide a concrete implementation of the gRPC protocol, layered over HTTP/2. These libraries enable communication between clients and servers using any combination of the supported languages.

---

**Comment by isaachier** [comment]
Working on it. Adding https://github.com/ruslo/hunter/pull/1087 to get c-ares dependency.
