### ISSUE TITLE
include HunterGate fail with VS2015 x64 generator

### ISSUE THREAD

**Issue by Ubiquite** [ruslo/hunter#566]
[hunter *\* INTERNAL **] vcvarsall.bat not found in `/VC`
[hunter *\* INTERNAL **] [Directory:C:/.hunter/_Base/Download/Hunter/0.10.9/53b198e/Unpacked/cmake]

**Comment by Ubiquite** [comment]
OK it's just because the documentation in out of date : https://docs.hunter.sh/en/latest/quick-start/boost-components.html
should be update with
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.16.15.tar.gz"
    SHA1 "6974c2150fc0d3b09de3ad1efcbf15d360647ffa"
)
I guess

**Comment by ruslo** [comment]
> OK it's just because the documentation in out of date : https://docs.hunter.sh/en/latest/quick-start/boost-components.html
should be update with

Feel free to send the patch.

**Comment by ruslo** [comment]
Closing inactive discussion.
