### ISSUE TITLE
boost filesystem is being looked at the wrong folder

### ISSUE THREAD

**Issue by dvirtz** [ruslo/hunter#569]
I get the error:

`[hunter ** INTERNAL **] Library not exists: /home/dviry/.hunter/_Base/74993dd/c701288/321aadf/Install/lib/libboost_filesystem-mt-d.a
`

However, the library is installed at 

`~/.hunter/_Base/74993dd/5eca26d/615089b/Install/lib/libboost_filesystem-mt-d.a`

This is my configuration:

```
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.15.25.tar.gz"
    SHA1 "74993ddf2cf8a6a4c3e0b9d58027a624bf3060e7"
	LOCAL
)
set(BOOST_VERSION 1.55.0-patched-3)
set(BOOST_COMPONENTS filesystem system regex thread program_options serialization)
hunter_add_package(Boost COMPONENTS ${BOOST_COMPONENTS})
```

Hunter/config.cmake:

`hunter_config(Boost VERSION ${BOOST_VERSION} CMAKE_ARGS CMAKE_CXX_FLAGS=-fPIC) `

**Comment by xsacha** [comment]
I have had this before when I compiled for one platform and then another.

**Comment by ruslo** [comment]
The problem was about some Boost variables stuck in cache while the config-id/toolchain-id changed. I've added more patterns to clear https://github.com/ruslo/hunter/commit/eb8acc093dc3dfd58ffac098ae95f0b41344fa8c should do the trick for Boost.

Release available: https://github.com/ruslo/hunter/releases/tag/v0.16.19

**Comment by ruslo** [comment]
> hunter_config(Boost VERSION ${BOOST_VERSION} CMAKE_ARGS CMAKE_CXX_FLAGS=-fPIC)

Just for your info it's better to use toolchain for adding global flags like `-fPIC`. See for example [gcc-pic](https://github.com/ruslo/polly/blob/master/gcc-pic.cmake).

**Comment by dvirtz** [comment]
Thanks for the quick resolution.

> Just for your info it's better to use toolchain for adding global flags like -fPIC. See for example gcc-pic.

I prefer not to add another dependency on Polly. There's also not sufficient documentation (or at least I didn't find such) on how to integrate Polly with Hunter.

**Comment by ruslo** [comment]
> I prefer not to add another dependency on Polly

It don't have to be Polly but it have to be toolchain if we are talking about Hunter. From [docs](https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html):
```
Toolchain file is the only way to apply global settings for 3rd party projects in Hunter
```

> how to integrate Polly with Hunter

From the user's perspective Polly is just a collection of toolchains, so `-DCMAKE_TOOLCHAIN_FILE=/path/to/polly/gcc-pic.cmake` is all you have to do. Though there is a helper script `build.py` that will make an integration easier.

> There's also not sufficient documentation (or at least I didn't find such)

Ask questions and do improve the docs :)
