### ISSUE TITLE
Use hunter packages defined locally within a repository (not inside HUNTER_ROOT)

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#57]
I've found documentation for adding new packages to the HUNTER_ROOT/cmake/projects/ folder:

> cd ${HUNTER_ROOT}
> mkdir cmake/projects/Example
> cat cmake/projects/Example/hunter.cmake

But I'd like to have the build work out of the box using a stock Hunter installation via:

include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.5.10.tar.gz"
    SHA1 "d534c6f3ab9c53c325ca4d3607f65bbf981913db"
)

Where that would  be able to use some pre-existing custom packages defined inside the project.  Maybe something like:

${CMAKE_SOURCE_DIR}/HunterPackages/cmake/projects/OpenCV/hunter.cmake

Is there an "include" mechanism to support this?

**Comment by headupinclouds** [comment]
Creating a symlink from the installed hunter package (via ${HUNTER_SELF})  to the local project definitions seems to work fine.

include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.7.5.tar.gz"
    SHA1 "264a0bd8f658bb6f50767146bde080d7c9788baf"
)

# Link our local package definitions into the installed hunter directory:
execute_process(COMMAND ${CMAKE_COMMAND} -E create_symlink
  ${CMAKE_SOURCE_DIR}/cmake/projects/OpenCV
  ${HUNTER_SELF}/cmake/projects/OpenCV
)

**Comment by ruslo** [comment]
* Have you seen this feature: https://github.com/ruslo/hunter/issues/56 probably it can be helpful?
* `I've found documentation for adding new packages` note that this instructions is about packages that doesn't depends on any 3rd party libraries. AFAIK OpenCV depends on many of them: https://github.com/Itseez/opencv/tree/master/3rdparty Some of them can conflict (like OpenCV zlib and Hunter zlib). I've openned this [bug](https://github.com/ruslo/hunter/issues/61) please subscribe
