### ISSUE TITLE
Add `Microsoft.GSL` library

### ISSUE THREAD

**Issue by rynkowsg** [ruslo/hunter#570]
GitHub: https://github.com/Microsoft/GSL

This repo contains Microsoft's implementation of GSL.

The Guideline Support Library (GSL) contains functions and types that are suggested for use by the C++ Core Guidelines maintained by the Standard C++ Foundation. The library includes types like `owner<>`, `not_null<>`, `span<>`, `string_span` and others.

C++ Core Guidelines: https://github.com/isocpp/CppCoreGuidelines
Stroustrup's talk about GSL: https://www.youtube.com/watch?v=1OEu9C51K2A
##

**Comment by xsacha** [comment]
How do we deal with the name conflict? There is already a 'GSL' package in hunter, but it is a different GSL.

**Comment by ruslo** [comment]
> There is already a 'GSL' package in hunter, but it is a different GSL

See not so much choices here. Just name it differently.

Mentioned here:
* https://github.com/ruslo/hunter/issues/527#issuecomment-249555061

**Comment by ithron** [comment]
I'm currently working on creating the package.
I'd name it _guideline_support_library_. However, GSL was not installing XXXConfig.cmake file. Issued a [pull request](https://github.com/Microsoft/GSL/pull/708) with a fix.

**Comment by ruslo** [comment]
> I'd name it Microsoft.GSL.

Okay

> However, GSL was not installing XXXConfig.cmake file. Issued a pull request with a fix.

Just for the record [this package](https://docs.hunter.sh/en/latest/packages/pkg/GSL.html) will install `GSLConfig.cmake` too. So we still got conflicts.

**Comment by ithron** [comment]
Changed the pull request so that the GSL target is exported in the Microsoft.GSL:: namespace.
Also changed the config file to Microsoft.GSLConfig.cmake to avoid conflicts.

**Comment by andoks** [comment]
@ruslo: I think this can be closed after #1499 added it.
