### ISSUE TITLE
CMAKE_ARGS in hunter_config or hunter_cmake_args

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#58]
I'm having trouble getting platform specific CMAKE_ARGS passed through to my OpenCV hunter package.  This is most likely user error, but any help would be greatly be appreciated either way.  In my top level CMakeLists.txt file, I have an if/else switch to control my platform specific CMAKE_ARGS options, this will typically be fairly long, but the following demonstrates the idea (if there is a better way to do this sort of thing, please let me know):
```
# OpenCV configuration
if(is_ios)
  message("Use the OpenCV-ios hunter packages to grab the iOS framework (TODO)") 
elseif(APPLE)
  message ("Configure OpenCV for OS X") 
  set(OPENCV_CMAKE_ARGS WITH_FFMPEG:BOOL=OFF)
elseif(MSCV)
  message("Configure minimal OpenCV for MSVC (TODO)")
  set(OPENCV_CMAKE_ARGS WITH_FFMPEG:BOOL=OFF)
elseif(is_linux)
  message("Configure minimal OpenCV for Linux (TODO)")
  set(OPENCV_CMAKE_ARGS WITH_FFMPEG:BOOL=OFF)
elseif(ANDROID)
  message("Configure minimal OpenCV for Android (TODO)")
  set(OPENCV_CMAKE_ARGS WITH_FFMPEG:BOOL=OFF)
endif()

message("OPENCV_CMAKE_ARGS ${OPENCV_CMAKE_ARGS}")
hunter_config(OpenCV VERSION 3.0.0-beta CMAKE_ARGS "${OPENCV_CMAKE_ARGS}")
hunter_cmake_args(OpenCV CMAKE_ARGS "${OPENCV_CMAKE_ARGS}")
hunter_add_package(OpenCV)
find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
```
I've created a public test project for this [here](https://github.com/headupinclouds/GPUOpenCV).

I start the build in my top level directory
```
 build.py --toolchain libcxx --verbose
```
Which eventually triggers an OpenCV download and build.  In the early stages it seems to pass along my custom CMAKE_ARGS
```
-- [hunter *** DEBUG ***] OpenCV version: 3.0.0-beta
<SNIP>
-- [hunter *** DEBUG ***] Add extra CMake args: WITH_FFMPEG:BOOL = OFF
-- [hunter *** DEBUG ***] Add extra CMake args: WITH_OPENEXR:BOOL = OFF
-- [hunter *** DEBUG ***] Add package: OpenCV
-- [hunter *** DEBUG ***] Install tag: libcxx
-- [hunter *** DEBUG ***] Variants: [release;debug]
-- [hunter *** DEBUG ***] Download scheme: url_sha1_release_debug
-- [hunter *** DEBUG ***] Url: https://github.com/Itseez/opencv/archive/3.0.0-beta.tar.gz
-- [hunter *** DEBUG ***] SHA1: 560895197d1a61ed88fab9ec791328c4c57c0179
-- [hunter *** DEBUG ***] Run generate
```
but later on in the log the actual CMake command is lacking the CMAKE_ARGS
```
/usr/local/Cellar/cmake/3.2.1/bin/cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/Users/dhirvonen/devel/hunter/_Base/Install/libcxx -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_TOOLCHAIN_FILE=/Users/dhirvonen/devel/GPUOpenCV/_builds/libcxx/_3rdParty/hunter/external/toolchain.cmake "-GUnix Makefiles" /Users/dhirvonen/devel/hunter/_Base/Source/OpenCV
```
Which leads to the wrong build configuration (FFMPEG should be set to "NO"):
```
--   Video I/O:
--     DC1394 1.x:                  NO
--     DC1394 2.x:                  NO
--     FFMPEG:                      YES
--       codec:                     YES (ver Unknown)
--       format:                    YES (ver Unknown)
--       util:                      YES (ver Unknown)
--       swscale:                   YES (ver Unknown)
--       gentoo-style:              YES
```
The [documentation] (https://github.com/ruslo/hunter/wiki/Adding-new-package) mentions specifying the hunter_config in a cmake/config.cmake, 
```
Second, specify version in config.cmake:
> grep Example cmake/config.cmake 
hunter_config(Example VERSION 1.0.1)
```
but I wasn't clear on where exactly that should go.  In the hunter repository or in the top level ${CMAKE_SRC_DIR}/cmake/config.cmake of my project (does hunter look there automatically)?  After some experimentation, and since I need to specify different CMAKE_ARGS, I was able to get the basic functionality working by including hunter_config directly in my CMakeLists.txt, but it still doesn't pick up the CMAKE_ARGS.

I also so a recent post discussing a hunter_cmake_args option.  I experimented a little with that as well, but with similar results.  

I expect I'm hitting some walls due to lack of CMake experience, but hopefully this is of some use to other folks trying out this build system.

If I run the build manually and pass the options on the command line, it works as expected:
```
cmake "-GUnix Makefiles" -H. -B_build -DWITH_FFMPEG:BOOL=OFF -DWITH_OPENEXR:BOOL=OFF
```
Triggers the following:
```
--     FFMPEG:                      NO
--       codec:                     NO
--       format:                    NO
--       util:                      NO
--       swscale:                   NO
--       gentoo-style:              NO
```
```

**Comment by headupinclouds** [comment]
It turns out the CMAKE_ARGS need to be specified with a different (and simpler) format than I was using.  I was using options returned from cmake-gui's "command line" output option, which is fine when using cmake directly on the command line (i.e., -DWITH_FFMPEG:BOOL=OFF) but when passing CMAKE_ARGS to hunter_config it requires arguments in the form WITH_FFMPEG=OFF.

**Comment by ruslo** [comment]
This is a bug. For now format `-DOPTION=ON` converts to `set(OPTION ON)`, so `-DOPTION:BOOL=ON` must be converted to `set(OPTION ON)` but not to `set(OPTION:BOOL ON)`

**Comment by ruslo** [comment]
Fixed
```cmake
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.8.4.tar.gz"
    SHA1 "e07a124192b0a47b0b60ade40fa873a42ec27822"
)
```
