### ISSUE TITLE
Requirements for a hunter package

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#587]
All boost packages except the latest one (1.62.0) are modified and provided in a hunter specific repository.

What are the requirements for a Package to be added to hunter directly without modification? How is boost 1.62 different from the previous Versions?

**Comment by ruslo** [comment]
> How is boost 1.62 different from the previous Versions?

Boost contains a lot of files that are not used while build in fact. From my experience 80MB of original size can be reduced to 17MB by removing documentation, tests and examples. That's what [hunter-packages/boost](https://github.com/hunter-packages/boost/tree/boost-1.56.0) repository for and that's how it differs from original. Though it's a place where we can apply patches too, e.g. https://github.com/hunter-packages/boost/commit/7900bfe00ebc6b00d6e95b02c0646578abda007d

> What are the requirements for a Package to be added to hunter directly without modification?

Almost all custom-scheme packages can be used as is. Good written CMake packages without dependencies can be used as is. CMake-based packages with dependencies should be "hunterized" however hunterization part may coexist with original code without having any effects on it. See details here:
* https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html
