### ISSUE TITLE
hunter_add_package load specific version

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#590]
There are different Versions of the packages defined, but I haven't found a way to define a specific version of a package beside the standard one.

I have found the functions `hunter_config` to define the default values for packages. But how do I specify a specific version I want to load into a project (aside from the default version). The `VERSION` flag from `find_package` does not work with `hunter_add_package`.

#

**Comment by ruslo** [comment]
See https://github.com/ruslo/hunter/wiki/example.custom.config.id

**Comment by ruslo** [comment]
Closing inactive discussion.
