### ISSUE TITLE
Add CZMQ library

### ISSUE THREAD

**Issue by roalz** [ruslo/hunter#599]
CZMQ is the official high-level C Binding for ZeroMQ.
Official website: http://czmq.zeromq.org/
Github: https://github.com/zeromq/czmq

Notes: it has CMake building, but depends on libzmq, so it may need an hunter-package fork

**Comment by ErniBrown** [comment]
@ruslo, I'm already working on this: https://github.com/ErniBrown/czmq
Would it be bossible to create a hunter-package repository? I plan to discard my fork as soon as a hunter-package repo is available, maybe it would be easier to fork directly https://github.com/zeromq/czmq

**Comment by ruslo** [comment]
@ErniBrown Created https://github.com/hunter-packages/czmq

**Comment by ErniBrown** [comment]
@ruslo, czmq was added, I think you can close this issue
