### ISSUE TITLE
Is libcurl a dependency

### ISSUE THREAD

**Issue by mg262** [ruslo/hunter#607]
I'm trying to follow the quick start guide and getting the following error message: 

```
error: downloading 'https://github.com/ruslo/hunter/archive/v0.10.9.tar.gz' failed
  status_code: 1
  status_string: "Unsupported protocol"
  log:
  --- LOG BEGIN ---
  Protocol "https" not supported or disabled in libcurl
Closing connection -1
```

I'm puzzled because the Hunter documentation (https://docs.hunter.sh/en/latest/overview/cmake-only.html) says: 

>No other dependencies - just CMake and your environment/IDE (no need for Git or Python or anything).

Do I need a particular version of `libcurl` on my system to get Hunter to run? If so, could you update the documentation, please?

**Comment by ruslo** [comment]
This is the problem in CMake. It looks like your have built it yourself, you have to build it with openssl support so `file(DOWNLOAD)` command can perform `https` downloadings.

**Comment by xsacha** [comment]
I run in to this problem sometimes.
When configuring cmake, use:
```
./bootstrap --prefix=/usr/local --system-curl
```

Also note that CMake provides binaries.

**Comment by mg262** [comment]
I haven't built CMake myself. I'm using the v. provided by the Cygwin package manager.

**Comment by ruslo** [comment]
@mg262 in this case you should contact cygwin team or build cmake yourself. unfortunately there is nothing hunter can do about it.
