### ISSUE TITLE
Recursive dependencies

### ISSUE THREAD

**Issue by caseymcc** [ruslo/hunter#609]
This more of a question than an issue.

I am trying to get librtmp hunterized and I am running into an issue when trying to link the example program.

librtmp uses both openssl and zlib (which I have them coming from hunter). However when the example program links against librtmp I get the following error.

```
CMake Error at CMakeLists.txt:15 (add_executable):
  Target "librtmp_example" links to target "ZLIB::zlib" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```

I gather from my searches on google/stackoverflow that this seems to be an issue with cmake and outside of including find_package(ZLIB) (with I am assuming a hunter_add_package as well) there is not much else that can be done. This seems a bit breaking for hunter as the example program really doesn't know which version of zlib (or hunter) that librtmp was built with much less the options used.

Is there a way to have librtmp's project config file setup in a manner to include the require include/lib directories so that zlib's target has the information needed rather than including a find_package for zlib? Can a zlib target be created in librtmp's project config?

**Comment by caseymcc** [comment]
When librtmpTargets.cmake gets built, this is the linked libraries added to the imported librtmp::librtmp target

```
set_target_properties(librtmp::librtmp PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "D:/projects/hunter_cmake/hunter_librtmp/_Base/xxxxxxx/d362e5a/f730664/Install/lib/ssleay32.lib;D:/projects/hunter_cmake/hunter_librtmp/_Base/xxxxxxx/d362e5a/f730664/Install/lib/libeay32.lib;ZLIB::zlib;ws2_32;winmm;gdi32"
)
```

you can see that openssl is included as just the libraries but zlib is included as a target name, the CmakeLists.txt for librtmp os set up like this

```
hunter_add_package(OpenSSL)
find_package(OpenSSL REQUIRED)

hunter_add_package(ZLIB)
find_package(ZLIB REQUIRED)
...
set(librtmp_libs
    ${OPENSSL_LIBRARIES}
    ${ZLIB_LIBRARIES}
)
...
target_link_libraries(librtmp ${librtmp_libs})
```

would it be better to extract the lib location from the ZLIB::zlib target and include that in target_link_libraries rather than the target name?

**Comment by ruslo** [comment]
> However when the example program links against librtmp I get the following error

`*Config.cmake` file produced by CMake should contains `find_dependency` call, for example OpenCV depends on Jpeg (optionally):
* https://github.com/hunter-packages/opencv/commit/f0352cf5cfc62b01e46ed9c499fec9775a7734fd

the effect is similar to calling `find_package(ZLIB)` from user space but without user really knowing about dependency (which may be optional).

> When librtmpTargets.cmake gets built, this is the linked libraries added to the imported librtmp::librtmp target

Actually this is wrong because of hardcoded full path to library. Such configuration is not relocatable. `OpenSSL::SSL` and `OpenSSL::Crypto` should be used, see
* https://github.com/ruslo/hunter/wiki/pkg.openssl

**Comment by ruslo** [comment]
Closing inactive discussion.
