### ISSUE TITLE
CMake error when using MinGW of Qt Windows build

### ISSUE THREAD

**Issue by tdauth** [ruslo/hunter#611]
When using the MinGW compiler provided by the Qt binary release 5.7 I get the error:

```
Führe "E:\CMake\bin\cmake.exe E:/Projekte/fairytale "-GCodeBlocks - MinGW Makefiles"" in E:\Projekte\fairytale\build aus.
CMake Error at E:/CMake/share/cmake-3.3/Modules/CMakeMinGWFindMake.cmake:22 (message):
  sh.exe was found in your PATH, here:

  E:/cygwin/bin/sh.exe
```

Using the following CMake instructions:

```
cmake_minimum_required(VERSION 3.0.0)

include("cmake/HunterGate.cmake")

HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.7.0.tar.gz"
    SHA1 "e730118c7ec65126398f8d4f09daf9366791ede0"
)
```
Without them everything works just fine. My CMAKE_CXX_COMPILER is set to "C:/Qt/Tools/mingw530_32/bin/g++.exe", CMAKE_MAKE_PROGRAM to "C:/Qt/Tools/mingw530_32/bin/mingw32-make.exe" and my CMAKE_GENERATOR to "MinGW Makefiles". Besides that CMAKE_SH is empty on purpose but it does not help.

The single line:
`include("cmake/HunterGate.cmake")`

does not cause any problems. I need the Codeblocks MinGW generator to parse the paths etc correctly and the Qt MinGW compiler for the paths as well. Otherwise the combination of generator and compiler wont work due to path parsing issues.

I am using this HunterGate.cmake file:
https://github.com/hunter-packages/gate/blob/624a9de6eae06db47919b75b083bc12dbee48354/cmake/HunterGate.cmake

**Comment by ruslo** [comment]
This is not a Hunter issue, this is a general CMake limitation. You can try this example:
```cmake
cmake_minimum_required(VERSION 3.0)
project(Foo)
```
should fail with the same error.

The fix is to remove path with `sh.exe` from current `PATH`:
* https://github.com/ruslo/hunter/blob/d988ee959ff3c5fbec5ab8fc351b056272b7e8fb/appveyor.yml#L92

**Comment by ruslo** [comment]
Closing inactive discussion.
