### ISSUE TITLE
OpenCL debug windows DLL

### ISSUE THREAD

**Issue by wheybags** [ruslo/hunter#613]
When I compile the OpenCL test application on windows on nvidia hardware in debug mode, I get an error when I run it that it can't start because it can't find OpenCLd.dll.
Release mode works fine.
Is it possible to have this package use the release OpenCL.dll even in debug mode? It's a plain C interface so it should work fine, and not all (any?) vendors will ship a debug dll.

ping @caseymcc

**Comment by caseymcc** [comment]
Ill check it in a few, I have only been using debug (haven't really tested with release) so I am a bit baffled as to why the debug one is having problems. But I also haven't tested the released one yet (my code base is still linked to my fork).

**Comment by caseymcc** [comment]
I just pulled the develop branch off of mailine and ran it. It compiled both debug and release versions. I am only testing with VS2015, anything below VS2012 won't work.

Few things:
1. Tell my how you are compiling (compiler, cmake version, etc...), I generally go the project folder "hunter/examples/OpenCL" and execute
"cmake -H. -B_build" or "cmake -G"Visual Studio 14 2015 Win64" -H. -B_buildx64" for x64
then assuming that succeeds
"cmake --build _build" or "cmake --build _buildx64" for x64

2. Can you check the install folder for both libraries after you compile. If you do not setup a hunter folder it is going to be at c:\.hunter. Inside should be "Cache", "Download" and any number of folders with random-ish numbers. Follow the latest random-ish folder all the way down to a "Build" and "Install" folder, in the "Install" folder should be a lib folder with OPenCL.lib and OpenCLd.lib

3. Send me any errors that happen in the first item.

**Comment by caseymcc** [comment]
Also the OpenCL package includes the ICD (Installable Client Driver) which is a dll (OpenCL.dll/OpenCLd.dll) that will load the proper system OpenCL.dll for the device you selected. This means that the package will build OpenCL.dll and OpenCLd.dll that you should link against rather than the release only one provided by the device vendor.

**Comment by caseymcc** [comment]
ah, nevermind. I know what you are talking about. Yeah VS does not know where the dll is as I think currently hunter does not provide the bin directory to VS. There is some cmake magic that can tell VS when debugging where to look for dlls.

Part of a 3rd party cmake module, CreateLaunchers.cmake (https://github.com/rpavlik/cmake-modules/blob/master/CreateLaunchers.cmake) is:
create_target_launcher, there you can set RUNTIME_LIBRARY_DIRS and WORKING_DIRECTORY. The RUNTIME_LIBRARY_DIRS basically adds on directory you put in there to VS debug path enviroment. Then t can find it. I will see if there is a way to work that into hunter but likely be a bit before I could get it in, need to ask Ruslo some suggestions and at the moment I think he is MIA (guessing holidays).

**Comment by caseymcc** [comment]
As a work around, in VS under the project poperty pages set
Debugging/Enviroment = %path%;{hunter bin directory}

for example mine is:
C:/.hunter/_Base/2a2f193/05395d8/a8b798f/Install/bin

so I would set:

Debugging/Enviroment = %path%;C:/.hunter/_Base/2a2f193/05395d8/a8b798f/Install/bin

**Comment by wheybags** [comment]
Oh, I presumed you were building a static library. I guess at runtime I was
able to find the nvidia opencl.DLL despite having been linked against the
icd one. Is there any reason not to switch the build type to static? It
seems to be the norm employed by all the other hunter packages I've used,
and is one of the best things about hunter IMO.

**Comment by caseymcc** [comment]
The ICD is just a drop in replacement for the vendor provided DLL and should work just like it, meaning it has to be a DLL as well. As far as the project is concerned it is a vendor provided DLL. The nice thing about the ICD is that if you want to open multiple platforms Intel, Amd, nVidia, etc... you can by linking to the ICD and each platform will show up and can be used at the same (different OpenCL contexts would be required of course).

**Comment by ruslo** [comment]
You can use CTest to orchestrate your testing, in this case you can add additional `PATH` to the tested executable:
```cmake
if(WIN32)
  set_property(
      TEST ThisIsTheTest
      PROPERTY
      ENVIRONMENT
      "PATH=$<TARGET_FILE_DIR:ThisIsDLL>;$ENV{PATH}"
  )
endif()
```

**Comment by wheybags** [comment]
The other possibility is just to set CMAKE_DEBUG_SUFFIX to empty string? I
still don't see why not just statically link it though, to be consistent
with all the other packages. If a user wants it dynamically linked, they
could just specify that no?

**Comment by ruslo** [comment]
Closing inactive discussion.
