### ISSUE TITLE
include(${wxWidgets_USE_FILE}) lost the information in a subproject

### ISSUE THREAD

**Issue by termi3** [ruslo/hunter#619]
Hi, I am very new to hunter but fascinated from it.
Actually I get an error:
the include(${wxWidgets_USE_FILE}) works in the main project
but gets "empty" value in a libraries, which are added with "add_subdirectory" and are small projects.
Any idea?

**Comment by ruslo** [comment]
I'm not sure I understand what is the issue. Can you check that your example is similar to one in wiki page:
* https://github.com/ruslo/hunter/wiki/pkg.wxwidgets

**Comment by termi3** [comment]
Not exact. 
For Project 1 and Project 2 it works, but it seems somehow in Lib1 and Lib2 etc. the information for the wxwidgets get losts. The Structure is so:

Directory Structure - all Projects in one solution

Project1
Project2
Libs
Libs/Lib1	
Libs/Lib2


#Main folder:	
CMakeLists.txt
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.10.9.tar.gz"
    SHA1 "53b198e364dc7bc8360fc545f798563229bd7e20"
)

PROJECT(Main_Solution)

hunter_add_package(wxWidgets)
find_package(wxWidgets REQUIRED core base xrc xml ribbon propgrid)

ADD_SUBDIRECTORY( Project1)
ADD_SUBDIRECTORY( Project2 )
ADD_SUBDIRECTORY( Libs)

#Subdirectory Project1
CMakeLists.txt
PROJECT( Project1 )
include(${wxWidgets_USE_FILE})
...
INCLUDE_DIRECTORIES( 
	${PROJECT_SOURCE_DIR}/src
	${wxWidgets_INCLUDE_DIRS}
	)
...

#Subdiretory Libs
CMakeLists.txt
ADD_SUBDIRECTORY(Lib1)
ADD_SUBDIRECTORY(Lib2)

# Subdiretory Lib1
CMakeLists.txt
PROJECT(Lib1) 
include(${wxWidgets_USE_FILE})
...
INCLUDE_DIRECTORIES( 
	${PROJECT_SOURCE_DIR}/src
	${wxWidgets_INCLUDE_DIRS}
	)

**Comment by ruslo** [comment]
Don't see any issues related to Hunter.

**Comment by termi3** [comment]
:-) sure, 
but without hunter the structure works, it means the projects in the libs have the correct include folders of the wxWidgets. With the hunter - only for the proects this works, in the libs somehow get lost. 
My question is if hunter does not "resets" some variables or if I have to add some "hunter_" commands within the add_subdirectory issues.

**Comment by ruslo** [comment]
I haven't used this package and have no idea about all aspects how it works, the only things I know that custom `Find*.cmake` module called by Hunter is here:
* https://github.com/ruslo/hunter/blob/master/cmake/find/FindwxWidgets.cmake

> My question is if hunter does not "resets" some variables

Hunter does reset some variables at the start of the work in some cases, but it happens only on start and there is no "magic" hooks at the enter of every subdirectory.

> if I have to add some "hunter_" commands within the add_subdirectory issues

The only command user need to call is `hunter_add_package`

**Comment by termi3** [comment]
Solution found. The problem seems to be connected with the understanding of the linker process of several libraries - how the single libraries are compiled and linked.

After adding 
${wxWidgets_LIBRARIES}
in the TARGET_LINK_LIBRARIES block of CMakeLists.txt 
the include folder for wxWidgets appears in the projects for the libraries, too.

So it seems that CMAKE checks, which sources are included as library and include these in the "include folders" only if they are presented as well in the Link_Libraries

So for the wiki - do not forget to add linking to wxWidgets for the "small sublibraries"
TARGET_LINK_LIBRARIES(source
${wxWidgets_LIBRARIES}
)
Why this works in the same project structure with cmake but without hunter is not clear for me, but that is not so bad now.

**Comment by ruslo** [comment]
> So for the wiki - do not forget to add linking to wxWidgets for the "small sublibraries"

As far as I understand this is exactly what current version of wiki page saying:
* https://github.com/ruslo/hunter/wiki/pkg.wxwidgets

> So it seems that CMAKE checks, which sources are included as library and include these in the "include folders" only if they are presented as well in the Link_Libraries

Check the values of `wxWidgets_USE_FILE` and `wxWidgets_LIBRARIES` variables. Seems that Hunter version use imported targets for relocation reason and "normal" version use full paths (which is not relocatable). In both cases same name for variables used for compatibility reason.
