### ISSUE TITLE
package zmqpp uses CMAKE_CXX_FLAGS

### ISSUE THREAD

**Issue by kubo-d** [ruslo/hunter#621]
Hello,
I tried to use hunter package zmqpp without success on Fedora as well as Windows machines - running cmake on a minimal example prints error message: "C++11 required for building ZMQPP" and fails. I think the problem might be caused by the fact that the package's list files rely on setting the CMAKE_CXX_FLAGS variable. I am a new user of CMake and hunter, so not able to efficiently fix the issue.

Is there a way to quickly fork / modify hunter-package repo and run hunter on it? Can you please suggest how?

Thanks!

**Comment by ruslo** [comment]
> Is there a way to quickly fork / modify hunter-package repo and run hunter on it? Can you please suggest how?

The fork that used in Hunter is here:
* https://github.com/hunter-packages/zmqpp

Feel free to send patches. However if patches is not related directly to Hunter please report an issue/patches to upstream first.

@tatraian +cc

**Comment by kubo-d** [comment]
Thank you!
Now I see that master branch of zmqpp repository doesn't contain any CMake list file. The [one](https://github.com/hunter-packages/zmqpp/blob/4.1.2-hunter/CMakeLists.txt) used by hunter  is quite different from [one](https://github.com/zeromq/zmqpp/blob/develop/CMakeLists.txt) in zmqpp development branch.

I'll further investigate this issue and probably move it to upstream repo.

**Comment by lepinkainen** [comment]
I'm having the exact same issue and can't find a proper workaround.

All of this and the regex-based check still fails.

`
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_compile_options(-std=c++11) 

set(CMAKE_CXX_FLAGS "-std=c++11 ${CMAKE_CXX_FLAGS}" FORCE)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -pedantic" FORCE)
`

Any idea what could be done with this?

**Comment by ruslo** [comment]
> All of this and the regex-based check still fails

Where this code is used? If you want to apply C++11 flags for 3rd parties you have to use toolchain. This is the only way to customize build:
* https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html

**Comment by lepinkainen** [comment]
My whole project is C++11, because I'm using features not available in previous versions. I tried all of the above in my project's CMakeFile.txt.

But for some reason the Hunter ZMQPP package _still_ doesn't detect it as C++11 and fails to even start compiling. I'll try the toolchain way next, if that really is the only way to have ZMQPP detect the correct C++ version.

**Comment by ruslo** [comment]
Closing inactive discussion.

**Comment by ckaminski** [comment]
https://github.com/hunter-packages/zmqpp/blob/4.1.2-hunter/CMakeLists.txt 

```
  string(REGEX MATCH "-std=c[+][+]11" CXX11_PRESENTED "${CMAKE_CXX_FLAGS}")
  if(NOT CXX11_PRESENTED)
    message(FATAL_ERROR "C++11 required for building ${PROJECT_NAME}")
  endif() 

```

This seems to preclude using C++14 features, doesn't it?  

Also I'm using a toolchain file called toolchain.cmake that includes only: 
`set(CMAKE_CXX_FLAGS "-std=c++11")`

Calling with: 
`cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/toolchain.cmake -DHUNTER_STATUS_DEBUG=ON`

I still get this error when using the the ZMQPP example in ruslo/hunter examples.  

```
CMake Error at CMakeLists.txt:30 (message):
  C++11 required for building ZMQPP
```

A) am I doing toolchains properly for this case? 
B) Is there a better way to check for C++11 or greater?

**Comment by ruslo** [comment]
@ckaminski You can find recommendations for managing C++ standard here: https://cgold.readthedocs.io/en/latest/tutorials/toolchain/globals/cxx-standard.html#summary

Also please don't start new discussion in closed issues.
