### ISSUE TITLE
Building Eigen when Boost installed

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#628]
Configuration:
```cmake
hunter_add_package(Boost)
hunter_add_package(Eigen)
```
Will fail on Eigen build step (if Eigen is not taken from cache). The reason is that `find_package(Boost)` called in Eigen code but there is no `hunter_add_package(Boost)`. Conflict is similar to:
* https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html#conflict

Fix is to "hunterize" Eigen. Workaround is to add option to exclude tests (`find_package(Boost)` needed only for tests).

New test added:
* https://travis-ci.org/ingenue/hunter/jobs/186519682

@NeroBurner I will revert https://github.com/ruslo/hunter/pull/626 partially. Default version will be `3.2.4-p0`.

**Comment by NeroBurner** [comment]
I personally prefer the workaround. To add Boost just to compile tests which are not even run by hunter is a bit much overhead. Maybe for the long run a solution is to do both the fix and the workaround. Add a `EIGEN_ENABLE_TESTS` and only call `hunter_add_package(Boost)` when tests are compiled

**Comment by NeroBurner** [comment]
I've created a pull request upstream. I hope they merge the change
https://bitbucket.org/eigen/eigen/pull-requests/287/add-cmake-option-to-enable-disable/diff

until then, shall we create a hunter-fork at github or shall we use something different?

**Comment by ruslo** [comment]
> I've created a pull request upstream

Thanks you, looks good.

>  shall we create a hunter-fork at github

Yes, but it's a little bit trickier as usual since Eigen use mercurial as a VCS. I created branch [hunter-3.3.1](https://github.com/hunter-packages/eigen/tree/hunter-3.3.1) with clean 3.3.1 version, please send pull request there.

**Comment by NeroBurner** [comment]
done
https://github.com/hunter-packages/eigen/pull/2

**Comment by ruslo** [comment]
Released: https://github.com/hunter-packages/eigen/releases/tag/v3.3.1-p0
