### ISSUE TITLE
Bountysource-plugin broken?

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#630]
The bountysource message is broken for me (Firefox 50.1.0, Ubuntu 16.04). I just see the text. the markdown seems to be disabled or ignored.

```

**Comment by ruslo** [comment]
Broken for me too (Firefox, Chrome). I'm not sure what I can do with it, any ideas?

**Comment by NeroBurner** [comment]
the markdown seems to be legit, but somehow I thing githubs parser doesn't like the `<bountysource-plugin>`-flags. For me it works to change the line

```
<bountysource-plugin>
```
to
```
---<bountysource-plugin>
```

it results to the following:
---<bountysource-plugin>
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40558425-bountysource-plugin-broken?utm_campaign=plugin&utm_content=tracker%2F1032790&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F1032790&utm_medium=issues&utm_source=github).
</bountysource-plugin>

**Comment by ruslo** [comment]
> but somehow I thing githubs parser doesn't like the <bountysource-plugin>-flags

Sounds like GitHub or Bountysource issue.

**Comment by ruslo** [comment]
Closing inactive discussion.
