### ISSUE TITLE
Non-intrusive way to add new packages?

### ISSUE THREAD

**Issue by flm8620** [ruslo/hunter#640]
Hunter is a nice project that I had keeping looking for longtime. However, when we want to add a new library with dependencies, we need to hunterize it, which is an intrusive way.

Is there a possibility to add library with dependencies directly from a trusty source?
Then let it be aware of hunter by passing some argument to cmake, for example, passing a cmake initial-cache file.

I used to use `ExternalProjet_Add()` to manage large project. Those libraries with well-written modern-style CMake files can generate `<libname>-config.cmake` file. I install them to the same place by indicating `${CMAKE_INSTALL_PREFIX}`. So what I need to do is to note paths of all these `<libname>-config.cmake` file to a cmake cache file `third_paty.cmake` and store paths in `${LIBNAME_DIR}`.

By providing  `third_paty.cmake` , for my project or other libraries with dependencies, I can run `cmake .. -C third_paty.cmake` to guide all `find_package()`, maybe change it to CONFIG mode when necessary.

The advantages of this way:
* I can add any library with well-written modern-style CMake files, without changing it
* I can write my project with normal cmake file, without custom cmake functions. so I can publish my code directly, other users can chose their way to configure it
* I can change to the latest version of a library by changing URL, instead of merging lastest version to my fork

Disadvantages:
* I need repeat `ExternalProjet_Add()` every where. It's better to have some template for this(so we have Hunter now)
* I need to teach some library to use CMake properly, to generate `<libname>-config.cmake`. So I should create a patch for `CMakelists.txt`, or fork it to make change.

Personally, I think it's better to popularize the modern-style CMake files to other libraries than to modify `CMakelists.txt` for hunterization.
So what do you think? Or is there any other reasons that make a non-intrusive way impossible?

**Comment by headupinclouds** [comment]
> Personally, I think it's better to popularize the modern-style CMake files to other libraries than to modify CMakelists.txt for hunterization

That is definitely worthwhile, but for now it seems we need something intrusive to make things play well together.  In practice, it seems unlikely that libraries will just evolve to be more compatible without a specific framework or standard to support that (hunter or otherwise).

In general, as you suggest, well written modern CMake packages can be used directly in hunter with some luck.  I believe there are a few hunter projects that point directly upstream. 

> Or is there any other reasons that make a non-intrusive way impossible?

Apart from the challenge of learning and writing effective/scalable CMake itself, I think one of the fundamental/inevitable roadblocks that will arise in complex projects that lack a shared versioning system such as hunter, is dependency conflicts (i.e., "one definition rule" issues: libA -> {libB,libC} ; libB -> libPNG v1.0; libC -> libPNG v2.0).

**Comment by flm8620** [comment]
I think the problem of CMake is the lack of good tutorials and lack of standard way to write `CMakelists.txt`. Maybe there will be some tools to generate `CMakelists.txt`. But this will make CMake become just a cross-platform version of Autotools. 
This remind me of this phrase in Autoconf tutorial:

> Those who do not understand Autoconf are condemned to reinvent it, poorly.

Maybe the complexity of Autotools is necessary for the messy GNU world. And CMake has not yet evolved to a complex tool which can well handle the messy cross-platform world.

For dependency conflicts, project Ryppl has a [plan](https://meetingcpp.com/tl_files/2014/talks/DependencyHell.pdf) for it, using the boolean satisfyability problem. But Ryppl is now dead.

However, I think dependency conflicts is not really a big problem for C++ developer. For a complex project, maybe it worth to spend one day to pick a correct library version that makes every one happy, or modify some code to make it compatible. While the problem is often that CMake always search weird places quietly(including Windows' registry, Oh My God), and find wrong version of libraries. And projects like Hunter can help you keep everything in a sandbox, which doesn't disturb the system, nor disturbed by the system.

**Comment by wawiesel** [comment]
Yes, I have been thinking about this as well. I experimented with overriding the find_package command for a project to use hunter, i.e. 
```
function(find_package)
    hunter_add_package(${ARGV})
    _find_package(${ARGV})
endfunction()
```
That way I didn't need to change all the find_package commands. 

It would be nice to be able to badge a project with "Modern CMake" or something like that to show that it satisfies some requirements for installation as a proper TPL where find_package(X CONFIG) will work later. Then hunter could work directly on it. Another possibility if the repo in question is GIT, to use git subtrees or git submodule in a "wrapper" repo. I think this might be preferable to a fork. The repo wrapper would be really small, essentially just
```
cmake/HunterGate.cmake
CMakeLists.txt (some commands to Hunterize then add_subdirectory(link))
link/ --> subtree of repo
```
You could have a branch for each tagged version of the master repo.

**Comment by flm8620** [comment]
You can override CMake's internal function ? That's interesting to know. But how do you define `_find_package()` ? Can you use the original `find_package()` again to define `_find_package()` ?

I did these 3 experiment:
This one works.
```cmake
cmake_minimum_required(VERSION 3.6)
function(_message)
  message(${ARGV})
endfunction()

function(message)
  _message(${ARGV})
endfunction()
message("hello")
```
This one seems leads to infinity loop, and CMake crashed
```cmake
cmake_minimum_required(VERSION 3.6)
function(message)
  _message(${ARGV})
endfunction()

function(_message)
  message(${ARGV})
endfunction()
message("hello")
```
This one also crash CMake 
```cmake
cmake_minimum_required(VERSION 3.6)
function(message)
  message(${ARGV})
endfunction()

message("hello")
```

So you can redefine `find_package `using the internal `find_package`
What a good news

**Comment by wawiesel** [comment]
Yes, a colleague told me that although CMake allows redefining a function called NAME, _NAME will always refer to the CMake internal version.

**Comment by ruslo** [comment]
> I used to use ExternalProjet_Add() to manage large project. Those libraries with well-written modern-style CMake files can generate <libname>-config.cmake file. I install them to the same place by indicating ${CMAKE_INSTALL_PREFIX}. So what I need to do is to note paths of all these <libname>-config.cmake file to a cmake cache file third_paty.cmake and store paths in ${LIBNAME_DIR}.

In this case you don't need LIBNAME_DIR, you just need:
* set CMAKE_PREFIX_PATH to the path which is used for CMAKE_INSTALL_PREFIX
* install `*Config.cmake` to some default location (like `lib/cmake/<package>/<package>Config.cmake`, see [find_package](https://cmake.org/cmake/help/latest/command/find_package.html))

This is what Hunter do:
* https://github.com/ruslo/hunter/blob/ca3adc81c78cdba67bc1567088d0fba309df2fb8/cmake/modules/hunter_finalize.cmake#L80

Install layout:
* http://cgold.readthedocs.io/en/latest/tutorials/install/layout.html

> Is there a possibility to add library with dependencies directly from a trusty source?

If you're worring about trust you should think about two possibilities:
* Make you fork trusty. You can use the fork only you have access to, or you can use 'hunter-packages' organization and I can set you as an only maintainer
* Send hunterization patch upstream. See HUNTER_ENABLED and backward-compatibility feature: https://docs.hunter.sh/en/latest/overview/compatibility.html

> Personally, I think it's better to popularize the modern-style CMake files to other libraries than to modify CMakelists.txt for hunterization.

It's completely different things. Hunterization is adding HunterGate and calling hunter_add_package, modern-style CMake files is must-have feature in projects. It doesn't depend on particular package management system. CMake updates of code which is not related to Hunter should not be send to the fork, but should be send upstream:
* https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html#maintenance ("Do not push general fixes and improvements, do push them upstream instead")

> So what do you think? Or is there any other reasons that make a non-intrusive way impossible?

If we are talking about modern-style CMake package, then only problem with non-intrusive is about DRY. Descibed here:
* https://docs.hunter.sh/en/latest/overview/automatic.html

It is a big deal for the project that is bigger than 'hello-world' application :)

**Comment by ruslo** [comment]
> Yes, I have been thinking about this as well. I experimented with overriding the find_package command for a project to use hunter

There are two problems with it:
* what if somebody want to override find_package too in their project for any reason?
* package may not always be found with find_package, users can do 'include(Find*)' (which I personally think is wrong)

Also note that not all the Hunter packages is C++ libraries, there are extra sources, CMake modules, etc. which doesn't fit 'find_package' scenario:
* https://docs.hunter.sh/en/latest/overview/anything.html

**Comment by ruslo** [comment]
Closing inactive discussion.
