### ISSUE TITLE
Qt update to 5.7.x

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#643]
What steps must be taken to update to Qt 5.7.x? I've tried to add the file `hunter_generate_qt_5_7_info.cmake` and just replace the 5.6 with 5.7. I Also added the download link for 5.7.1 at `Qt/hunter.cmake` and updated the default version
```
hunter_add_version(
    PACKAGE_NAME
    Qt
    VERSION
    "5.7.1"
    URL
    "http://download.qt.io/official_releases/qt/5.7/5.7.1/single/qt-everywhere-opensource-src-5.7.1.7z"
    SHA1
    72ed6f62f4921d3308e7f237865475f74f943bab
)
```

I tried to build the example `/hunter/examples/qt-core`.
The error at qt configure is the following:
```
Attempting to skip non-existent module qtenginio.
CMake Error at qt-configure.cmake:366 (message):
  Qt configure failed: 1
```

**Comment by pretyman** [comment]
Add to `cmake/projects/Qt/hunter.cmake.in` the following:

```CMake
## 5.7 only --
string(COMPARE EQUAL "@qt_component@" "qtenginio" _is_qtenginio)

if(_is_qtenginio)
  if(NOT HUNTER_Qt_VERSION MATCHES "^5\\.7\\.")
    return()
  endif()
endif()
## -- end
```

**Comment by NeroBurner** [comment]
I edited the file `hunter_generate_qt_5_7_info.cmake` to not contain qtenginio. Could yu explain what this condition does? for me it returns on the `qtenginio` only if it is not Qt 5.7.x

For easier code sharing I've created a PR #644

**Comment by headupinclouds** [comment]
Due to size, the hunter-package Qt releases are usually significantly pruned.  I made a small script for this based on a gist @ruslo shared previously.

```
#!/bin/bash -e
#
# See: https://gist.github.com/ruslo/817fb379cf150f9c7dbc6514b8ca00c8
# Copyright (C) 2016, Ruslan baratov

# Warning! Commit all the changes you need before running the script!
#
# Rule of thumb:
#
# > git status
## nothing
#
# > git branch -vv
## check that you're on the right branch
#
# > /path/to/create-7z.sh # run this script

set -x
BRANCHNAME="`git rev-parse --abbrev-ref HEAD`"
echo "Packing branch: '${BRANCHNAME}'"
rm -rf _packing ${BRANCHNAME}.tar ${BRANCHNAME}.7z
mkdir _packing
git archive ${BRANCHNAME} > ${BRANCHNAME}.tar
tar -x -f ${BRANCHNAME}.tar -C _packing
(cd _packing && 7z a -t7z -m0=lzma -mx=9 -mfb=128 -md=64m -ms=on ../${BRANCHNAME}.7z .)
ls -la ${BRANCHNAME}.7z
```

**Comment by NeroBurner** [comment]
I'd prefer upstream packages over filesize when no hunter specific patches are needed. It comes down to lower maintenance and more obvious update paths for new contributors

**Comment by ruslo** [comment]
> I'd prefer upstream packages over filesize when no hunter specific patches are needed

Yes of course. But we have to patch previous Qt version anyway.

**Comment by headupinclouds** [comment]
FWIW, it looks like Qt 5.8 will be released soon: https://www.phoronix.com/scan.php?page=news_item&px=Qt-5.8-Last-Minute-Testing

**Comment by ruslo** [comment]
May be useful:
* https://bugreports.qt.io/browse/QTBUG-54666

**Comment by headupinclouds** [comment]
FWIW, Qt 5.9 is out http://blog.qt.io/blog/2017/05/31/qt-5-9-released/

**Comment by ruslo** [comment]
https://github.com/hunter-packages/Qt/issues/11#issuecomment-323568530
