### ISSUE TITLE
Boost 1.63 fails to build in Windows 10 with NMake generator.

### ISSUE THREAD

**Issue by nicber** [ruslo/hunter#657]
I am trying to build ruslo/weather and I have come across two issues:
The configuration step fails but hunter proceeds as if it succeeded.
```
Scanning dependencies of target Boost
[ 12%] Creating directories for 'Boost'
[ 25%] Performing download step (download, verify and extract) for 'Boost'
-- Boost download command succeeded.  See also C:/.hunter/_Base/b561a1c/4a538fd/add6f89/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-download-*.log
[ 37%] No update step for 'Boost'
[ 50%] No patch step for 'Boost'
[ 62%] Performing configure step for 'Boost'
-- Boost configure command succeeded.  See also C:/.hunter/_Base/b561a1c/4a538fd/add6f89/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-configure-*.log
[ 75%] No build step for 'Boost'
[ 87%] Performing install step for 'Boost'
CMake Error at C:/.hunter/_Base/b561a1c/4a538fd/add6f89/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug.cmake:16 (message):
  Command failed: 1

   'C:/Program Files/CMake/bin/cmake.exe' '-Dmake=' '-Dconfig=' '-P' 'C:/.hunter/_Base/b561a1c/4a538fd/add6f89/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake'

  See also

    C:/.hunter/_Base/b561a1c/4a538fd/add6f89/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-*.log
```
This error message was extracted from `bootstrap.log` from the `Source` folder. It seems to fail because the compiler was installed in a path with spaces.
```
C:\.hunter\_Base\b561a1c\4a538fd\add6f89\Build\Boost\Source\tools\build\src\engine>.\bootstrap\jam0 -f build.jam --toolset=vc14 "--toolset-root=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\..\..\VC\ "  clean 
build.jam:192: in module scope
*** argument error
* rule toolset ( name command .type ? : opt.out + : opt.define * : flags * : linklibs * )
* called with: ( cc C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe : -o  : -D : -s -O :  )
* extra argument (x86)/Microsoft
build.jam:156:see definition of rule 'toolset' being called
```
If I call bootstrap.bat from the VS command line it works fine, which seems weird since the compiler path is the same.

**Comment by ruslo** [comment]
Boost package doesn't work with NMake generator, kind of known issue:
* https://github.com/ingenue/hunter/blob/add60d558463dfece5ae7f1a8ccdd7ed78ebfcb4/appveyor.yml#L21-L27

**Comment by ruslo** [comment]
Closing inactive discussion.

**Comment by dvirtz** [comment]
I have the same problem with VS 2017 15.5. Any idea?

**Comment by ruslo** [comment]
> I have the same problem with VS 2017 15.5. Any idea?

This issue is about NMake generator. NMake was never worked as far as I remember. Are you sure is not about https://github.com/ruslo/hunter/issues/745#issuecomment-316629752 ?

**Comment by dvirtz** [comment]
I've deleted the %USERPROFILE%\Source folder so it shouldn't be that case. 
I get the same error as the OP on bootstrap.log.
Build log with HUNTER_STATUS_DEBUG=ON is on https://gist.github.com/dvirtz/dcfb2dba4563d1849b45b4a06681918f

**Comment by ruslo** [comment]
> I get the same error as the OP on bootstrap.log

What generator you're using? NMake was **never working**, somebody have to fix it.

**Comment by dvirtz** [comment]
Ninja.
The strange thing is that Boost components I add directly build
successfully.
The problem occurs when building Boost as a dependency of another library
(Beast).

**Comment by ruslo** [comment]
> Ninja

Was never working too as far as I remember.

> The strange thing is that Boost components I add directly build successfully. The problem occurs when building Boost as a dependency of another library (Beast).

I agree it's strange, but can't say anything without details.

**Comment by dvirtz** [comment]
You right, switching to VS 2017 generator solved it.
Thanks.

**Comment by tomjaguarpaw** [comment]
> > Ninja

> Was never working too as far as I remember.

If I issue the CMake command two or three times then I can generate Ninja files.  The first time always fails.
