### ISSUE TITLE
HDF5 not cross-platform

### ISSUE THREAD

**Issue by palmerc** [ruslo/hunter#663]
As noted by the folks at HDFGroup this project isn't cross-compilable as-is and Android therefore isn't really supported.
https://support.hdfgroup.org/HDF5/faq/compile.html

Someone once upon a time hacked their way through the build process by-hand and I uploaded that as a gist.
https://gist.github.com/palmerc/e723d63c0e07ed6a862205e92d3157db

It would seem that to get this to be cross-platform you would need to fix their cmake scripts to kick off an android emulator, adb push the generated test programs, run, adb pull the result. The DCMTK project http://dcmtk.org does something similar to this.

**Comment by ruslo** [comment]
> Someone once upon a time hacked their way through the build process by-hand and I uploaded that as a gist

Those instructions is about Makefile. As far as I can see CMake used as a build system for HDF5 in Hunter.

> kick off an android emulator, adb push the generated test programs, run, adb pull the result

Sounds too complex. Using some defaults for Android platform should do the trick.

**Comment by palmerc** [comment]
Yes, they are for a Makefile, but it illustrates the issue. There are many architectural dependent tests, so coming up with a set of generic defaults for Android doesn't seem likely and I've seen this done on at least a couple of libraries that are architecture dependent. On Android you would need separate defaults for MIPS32 and 64, ARM32 and 64, X8632 and 64.

**Comment by ruslo** [comment]
> On Android you would need separate defaults for MIPS32 and 64, ARM32 and 64, X8632 and 64 to cover currently supported architectures

Don't see the problem here, it just need to be organized carefully. Otherwise if I want to try to build with MIPS32 toolchain I have to have MIPS32 Android device?

**Comment by palmerc** [comment]
You would need a MIPS32 emulator, yes. In these very architecture dependent libraries you need to know about the hardware and the compiler. For example, what is the size of char and is it signed or unsigned. Endianess of the architecture, and so on.

In the project check config/cmake/
[ConversionTests.c](https://github.com/ruslo/hunter/files/757109/ConversionTests.c.txt)
ConversionTests.c

This is just one series of tests where they're trying to determine how types are handled. Some other C code is actually generated by the makefile, compiled, run, and the results read out.

**Comment by ruslo** [comment]
> For example, what is the size of char and is it signed or unsigned. Endianess of the architecture, and so on

This is a compile-time stuff, not runtime. By the way they are the part of the toolchain-id:
* https://github.com/ruslo/hunter/blob/00ab4d3ee7ab48ee15010b038dc0d756c9bcf35a/scripts/predefined.list#L14
* https://github.com/ruslo/hunter/blob/00ab4d3ee7ab48ee15010b038dc0d756c9bcf35a/scripts/predefined.list#L16

> You would need a MIPS32 emulator, yes

Android emulators use host architecture, no? Meaning emulator usually is x86/x86_64.

> In the project check config/cmake/ConversionTests.c

I'm not sure about HDF5 details but some common sense:  the code in this file generated by compiler and will not run differently on the different devices. This looks like an analysis of how compiler generates code. Let me know if I'm missing something.

**Comment by palmerc** [comment]
Emulators on Android run in qemu and are emulating the underlying hardware and running the native build for that architecture. This has been a key difference between iOS (simulator) and Android (emulator).

**Comment by ruslo** [comment]
> Emulators on Android run in qemu and are emulating the underlying hardware and running the native build for that architecture

Cool, I see. Just noticed I can create `armeabi` device in AVD.

**Comment by ruslo** [comment]
Closing inactive discussion.
