### ISSUE TITLE
Manage projects with a yaml file

### ISSUE THREAD

**Issue by roscopecoltran** [ruslo/hunter#666]
Hi,

After some searches, I could not find any helpers to parse or regex CMakeLists.txt and its commands with arguments. So, I was wondering if it would be realistic to manage hunter's packages like this tool for golang, called glide: https://github.com/Masterminds/glide

**yaml example**: https://github.com/Masterminds/glide/blob/master/docs/example-glide.yaml

Also, is there any parser/lexer for CMakelists.txt available in order to extract an ast tree of any CMake based project ? (found these projects [cmake-ast](https://github.com/polysquare/cmake-ast), [peg-cmake ](https://github.com/twxs/peg-cmake) and [cmakelists_parsing](https://github.com/wjwwood/parse_cmake) but not sure they deal properly with multi-lined commands and hunter macros) 

**Goal:**

It would help to find package dependencies with version and components and help to hunterize wider projects, like helping to find where to pre-prend hunter_add_package (line number) commands in CMakeLists.txt. Ultimately, it would help to build docker containers for c++ based project by building dependencies from sources (especially for alpine based images). 

At the end, it would be easy to make a golang based tool to like glide for CMake base projects and add some macros to chain sub-commands (eg. [nut](https://github.com/matthieudelaro/nut)).

Hope that was a clear enough, and wish u a great day !

Regards

**Comment by ruslo** [comment]
Sounds complex but interesting. Don't know much about it.

**Comment by ruslo** [comment]
Closing inactive discussion.
