### ISSUE TITLE
Add pugixml

### ISSUE THREAD

**Issue by designerror** [ruslo/hunter#685]
Hi,

pugixml is light-weight, simple and fast XML parser for C++ with XPath support
https://github.com/zeux/pugixml

CMake:
https://github.com/zeux/pugixml/blob/master/CMakeLists.txt

Regards

**Comment by rusdevops** [comment]
I created pull request
https://github.com/ingenue/hunter/pull/95

**Comment by ruslo** [comment]
> I created pull request

@rusdevops Please reopen it in https://github.com/ruslo/hunter

**Comment by rusdevops** [comment]
@ruslo, I reopened pull request:
https://github.com/ruslo/hunter/pull/902

**Comment by rusdevops** [comment]
@ruslo, I reopened pull request:
#903
