### ISSUE TITLE
Android Studio: Escape backslashes in generated toolchain.cmake

### ISSUE THREAD

**Issue by jomof** [ruslo/hunter#693]
https://github.com/ruslo/hunter/blob/2421a9c467116b393724e7c2a9a251e6fc62df95/cmake/modules/hunter_download.cmake#L394

The particular problem for Android Studio on Windows is that CMAKE_MAKE_PROGRAM is like this:
set(CMAKE_MAKE_PROGRAM "C:\Users\jomof\AppData\Local\Android\Sdk\cmake\3.6.3155560\bin\ninja.exe" CACHE INTERNAL "")

The back slashes need to be escaped to work on Windows

**Comment by jomof** [comment]
Android Studio user can kind work around by adding something like this in build.gradle:

        externalNativeBuild {
            cmake {
                arguments "-DCMAKE_MAKE_PROGRAM=C:/Users/jomof/AppData/Local/Android/Sdk/cmake/3.6.3155560/bin/ninja.exe"
            }
        }

It isn't so good though because you have to hard-code a path that would be different on CI servers or other user's machine.

**Comment by ruslo** [comment]
Here is the fix:
* https://github.com/ruslo/hunter/commit/133bfd21ac657dac5d5edcba54f39de49bfefdfa

Testing it with OpenCV:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1412
* https://travis-ci.org/ingenue/hunter/builds/209649397

**Comment by ruslo** [comment]
> Testing it with OpenCV

Looks like sometimes we still have to use backslashes. NMake failed:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1412

Fixing them manually:
* https://github.com/ruslo/hunter/commit/873824854a9e1d63f84f26c8591e95dc29238ba6

GTest tests:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1414
* https://travis-ci.org/ingenue/hunter/builds/209695751

OpenCV tests:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1415
* https://travis-ci.org/ingenue/hunter/builds/209696094

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/releases/tag/v0.18.14
