### ISSUE TITLE
Visual Studio 2017 not supported

### ISSUE THREAD

**Issue by xosdy** [ruslo/hunter#696]
`[hunter ** INTERNAL **] Unexpected MSVC_VERSION: '1910'`

**Comment by ruslo** [comment]
Try this version:
* https://github.com/ruslo/hunter/releases/tag/v0.18.13

**Comment by xosdy** [comment]
`[hunter ** INTERNAL **] Environment variable VS150COMNTOOLS is empty`

There's no `VS150COMNTOOLS` under Visual Studio 2017, and the `vcvarsall.bat` is under `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build`

**Comment by ruslo** [comment]
> There's no VS150COMNTOOLS under Visual Studio 2017

It should be in saved in system during Visual Studio installation. Can you check `Environment Variables` -> `System variables`?

**Comment by xosdy** [comment]
Yes, I've checked it. The installation didn't create it.

**Comment by ruslo** [comment]
> Yes, I've checked it. The installation didn't create it.

Okay, I see.

> the vcvarsall.bat is under C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build

We need to find the way to determine location of `vcvarsall.bat` (Visual Studio may be installed not to `C:\Program Files (x86)\`). Any ideas?

**Comment by ruslo** [comment]
TODO, check:
* https://cmake.org/cmake/help/latest/variable/CMAKE_VS_MSBUILD_COMMAND.html
* https://cmake.org/cmake/help/latest/variable/CMAKE_VS_DEVENV_COMMAND.html
* https://cmake.org/cmake/help/latest/variable/CMAKE_MAKE_PROGRAM.html

**Comment by xosdy** [comment]
👍

**Comment by Knitschi** [comment]
Seriously? Beating me by three hours to report this issue ;-)
Guess everybody uses the weekend to play around with the new VS.

**Comment by Knitschi** [comment]
To commit something actual useful ...
They say VS150COMNTOOLS will be available in the next release.

https://developercommunity.visualstudio.com/content/problem/730/vs154-env-var-vs150comntools-missing-from-build-sy.html

**Comment by ruslo** [comment]
> They say VS150COMNTOOLS will be available in the next release

Let me guess, also `MSVC_VERSION` will be changed from [1910 to 2000](https://github.com/ruslo/hunter/blob/c0ed5b2c79d9c5e1a87d7567a459ea68bd1eb987/cmake/modules/hunter_setup_msvc.cmake#L38-L44)? :)

> https://developercommunity.visualstudio.com/content/problem/730/vs154-env-var-vs150comntools-missing-from-build-sy.html

Thanks for the link. So it resolved twice - in october and november, but fix is still not available in fact.

**Comment by Knitschi** [comment]
VS150COMNTOOLS is currently not available for me which seems to be a bug. At least I found some posts that complained about it missing.

I get an error that vcvarsall.bat is missing when I set VS150COMNTOOLS manually because it is now under
%VS150COMNTOOLS%..\..\VC\Auxiliary\Build\vcvarsall.bat
instead of
%VS140COMNTOOLS%..\..\VC\vcvarsall.bat
in VS 2015

**Comment by Knitschi** [comment]
Sorry just saw that that link was quite old later, thats why deleted my comment. But I found outher discussions where people complain that the variable is missing. But I am not sure yet if it is an installer bug or if it was removed intentionally.

**Comment by Knitschi** [comment]
> Let me guess, also MSVC_VERSION will be changed from 1910 to 2000? :)

At least CMake says:

    -- The CXX compiler identification is MSVC 19.10.25017.0

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/releases/tag/v0.18.20

**Comment by gashmish** [comment]
I had same problem with VS2017
When using v0.18.20 i've got another error:

`
Performing install step for 'Boost'
CMake Error at C:/cygwin64/home/dsplabs/.hunter/_Base/8f75b22/8d0c407/c565a23/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug.cmake:16 (message):
    Command failed: 1
     'C:/Program Files/CMake/bin/cmake.exe' '-Dmake=' '-Dconfig=Debug' '-P' 'C:/cygwin64/home/dsplabs/.hunter/_Base/8f75b22/8d0c407/c565a23/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake'
`

In Boost-install-err.log:
`CMake Error at C:/cygwin64/home/dsplabs/.hunter/_Base/8f75b22/8d0c407/c565a23/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake:9 (message):
  Command failed (1):
   'b2' '--layout=tagged' '-d0' 'install' '--without-atomic' '--without-chrono' '--without-container' '--without-context' '--without-coroutine' '--without-coroutine2' '--without-date_time' '--without-exception' '--without-fiber' '--without-filesystem' '--without-graph' '--without-graph_parallel' '--without-iostreams' '--without-locale' '--without-log' '--without-math' '--without-metaparse' '--without-mpi' '--without-program_options' '--without-python' '--without-random' '--without-regex' '--without-serialization' '--without-signals' '--without-system' '--without-test' '--without-thread' '--without-timer' '--without-type_erasure' '--without-wave' '--prefix=C:/cygwin64/home/dsplabs/.hunter/_Base/8f75b22/8d0c407/c565a23/Build/Boost/Install'
`

With VS2015 this worked fine

**Comment by ruslo** [comment]
@gashmish It's related, but bug is not the same, please open separate issue.

**Comment by fcoulombe** [comment]
i just got this issue but for 1916. 
i'm guessing that i'm one version ahead?
i tried tag 18.20 but get the same error.
looked at the code and...
    string(COMPARE EQUAL "${MSVC_VERSION}" "1900" _vs_14_2015)
    string(COMPARE EQUAL "${MSVC_VERSION}" "1910" _vs_15_2017)

no 1916 

adding
string(COMPARE EQUAL "${MSVC_VERSION}" "1916" _vs_15_2017)

seems to make it work

**Comment by fcoulombe** [comment]
maybe https://docs.hunter.sh/en/latest/quick-start/boost-components.html should be updated with a more up to date version?

**Comment by ruslo** [comment]
@fcoulombe Feel free to send the pull request
