### ISSUE TITLE
Travis CI: switch to `dist: trusty`

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#718]
Test `.travis.yml`:
- [x] https://github.com/ruslo/polly
- [x] https://github.com/forexample/hunter-simple
- [x] https://github.com/hunter-packages/gate
- [x] https://github.com/travis-ci-tester/toolchain-table
- [x] https://github.com/ruslo/polly/wiki/Travis-CI-AppVeyor-support-table

Create/find docker image:
- [x] https://github.com/hunter-packages/travis-linux-docker
- [x] Update section: https://github.com/hunter-packages/travis-linux-docker#testing

Test some packages:
- [x] GTest (simple, all toolchains)
- [x] OpenCV (CMake-based, big package with dependencies)
- [x] Boost (for https://github.com/ruslo/hunter/pull/715)
- [x] OpenSSL (for https://github.com/ruslo/hunter/pull/715)
- [x] odb-boost (for https://github.com/ruslo/hunter/pull/715)
- [x] Qt (upload on Travis doesn't work because of timeouts, testing of Docker image)

**Comment by ruslo** [comment]
@chfast For your info I got problems with Python on new Trusty image:
```
> easy_install3 --user requests
> python3 "${POLLY_SOURCE_DIR}/bin/install-ci-dependencies.py"
...
ImportError: No module named 'requests'
```

Example:
* https://travis-ci.org/ruslo/polly/builds/214181910

**Comment by chfast** [comment]
Trusty should have pip. I've seen you used easy_install because of the lack of pip.

**Comment by ruslo** [comment]
> Trusty should have pip

Yep, did the fix, thanks.

Current problem is that `sanitize-thread` toolchain is not working:
* https://travis-ci.org/ruslo/polly/builds/214269616

Executable produce error:
```
FATAL: ThreadSanitizer can not mmap the shadow memory (something is mapped at 0x5572fc6cd000 < 0x7cf000000000)
```

Suggested fix from [documentation](https://github.com/google/sanitizers/wiki/ThreadSanitizerCppManual#faq):
```
> echo 2 >/proc/sys/kernel/randomize_va_space
```

Bug we have to run it with `sudo` which is disabled :(

**Comment by ruslo** [comment]
> Current problem is that sanitize-thread toolchain is not working

To clarify, the error is runtime. So we build/link fine but we can't run tests. It's bad if we lose toolchain by moving from 12.04 to 14.04 but I like the fact that we don't have to install a lot of stuff. This reduce the build time from ~3 minutes to ~40 seconds:
* https://travis-ci.org/ruslo/polly/builds/212960859
* https://travis-ci.org/ruslo/polly/builds/214269616

**Comment by chfast** [comment]
The issue with thread sanitizer is probably doe to Ubuntu upgrade. I have do the same on my local machine. Maybe asking Travis to enable that kernel option by default in their non-sudo images?

**Comment by ruslo** [comment]
> Maybe asking Travis to enable that kernel option by default in their non-sudo images?

I guess as a last resort. Will spend some time looking for solution, may be we can do it without `sudo`.

**Comment by ruslo** [comment]
Trying to build docker image for finding solution to current problems:
* https://github.com/travis-ci/travis-ci/issues/7518

**Comment by ruslo** [comment]
> Trying to build docker image for finding solution to current problems

Image is ready, instructions updated:
* https://github.com/hunter-packages/travis-linux-docker

> The issue with thread sanitizer is probably doe to Ubuntu upgrade. I have do the same on my local machine. Maybe asking Travis to enable that kernel option by default in their non-sudo images?

It is set to `2` in docker container but still doesn't work...

Related links:
* https://bugzilla.kernel.org/show_bug.cgi?id=66721
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=59410
* https://github.com/google/sanitizers/issues/503

So there are kernel fixes and compiler fixes. On my local Ubuntu 16.04 machine I got similar error, I can "fixed" it by using Clang 3.8 without PIE, but Clang 3.5 (which is used on Travis CI) doesn't support ThreadSanitizer without PIE.

So I'm planning to give up ThreadSanitizer toolchain for now. Don't want to make the `.travis.yml` too complex by adding instructions for installing Clang 3.8+ just for ThreadSanitizer. Using custom compilers should be manageable by Hunter itself in future and discussed here:
* https://github.com/ruslo/hunter/issues/495

**Comment by ruslo** [comment]
Polly updated:
* https://github.com/ruslo/polly/pull/131

**Comment by ruslo** [comment]
Almost ready. Hit this one now:
* https://github.com/travis-ci/travis-ci/issues/7558

We need it for Qt+Android:
* https://travis-ci.org/ingenue/hunter/builds/217670290
* http://superuser.com/a/360398/252568

**Comment by ruslo** [comment]
> Almost ready. Hit this one now: travis-ci/travis-ci#7558

Removing APK creating from this test for now, C++ build still remains.

Everything ready, closing. Most of the packages still use Ubuntu 12.04 in `.travis.yml`, will be updated one-by-one on demand.
