### ISSUE TITLE
OpenCV 3.0.0-beta (was: OS X GStreamer.framework <-> ZLIB assert error)

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#72]
On my OS X system /Library/Frameworks/GSTreamer.framework seems to be first in line for providing ZLIB (and possibly PNG) dependencies.  That framework provides an assert.h file which ends up leaving the assert macro undefined in files which rely on the standard /usr/include/assert.h macro.

I believe that is responsible for the errors I'm seeing in the OpenCV build now.  If I temporarily move GStreamer out of the way, that fixes the undeclared identifiers issues in the OpenCV assert calls.

Errors:
```
[ 53%] Building CXX object modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/loadsave.cpp.o
cd /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Build/OpenCV-release-prefix/src/OpenCV-release-build/modules/imgcodecs && /usr/bin/clang++   -DOPENCV_NOSTL -D__OPENCV_BUILD=1 -std=c++11 -stdlib=libc++ -fPIC   -fsigned-char -W -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -Wno-semicolon-before-method-body -fno-omit-frame-pointer -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-deprecated-declarations -O3 -DNDEBUG  -DNDEBUG -I/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/3rdparty/libjasper -I/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/3rdparty/libjpeg -I/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/3rdparty/ippicv/unpack/ippicv_osx/include -I/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Build/OpenCV-release-prefix/src/OpenCV-release-build -isystem /usr/local/include/eigen3 -isystem /Library/Frameworks/GStreamer.framework/Headers -I/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgcodecs/include -I/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgcodecs/src -I/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Build/OpenCV-release-prefix/src/OpenCV-release-build/modules/imgcodecs -I/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/core/include -I/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgproc/include    -o CMakeFiles/opencv_imgcodecs.dir/src/loadsave.cpp.o -c /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgcodecs/src/loadsave.cpp
In file included from /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgcodecs/src/loadsave.cpp:46:
In file included from /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgcodecs/src/precomp.hpp:50:
In file included from /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgproc/include/opencv2/imgproc/imgproc_c.h:46:
In file included from /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgproc/include/opencv2/imgproc/types_c.h:46:
In file included from /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/core/include/opencv2/core/core_c.h:48:
/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/core/include/opencv2/core/types_c.h:485:5: error: use of undeclared identifier 'assert'
    assert( (unsigned)CV_MAT_DEPTH(type) <= CV_64F );
    ^
/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/core/include/opencv2/core/types_c.h:526:5: error: use of undeclared identifier 'assert'
    assert( (unsigned)row < (unsigned)mat->rows &&
    ^
/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/core/include/opencv2/core/types_c.h:533:9: error: use of undeclared identifier 'assert'
        assert( type == CV_64FC1 );
        ^
/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/core/include/opencv2/core/types_c.h:543:5: error: use of undeclared identifier 'assert'
    assert( (unsigned)row < (unsigned)mat->rows &&
    ^
/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/core/include/opencv2/core/types_c.h:550:9: error: use of undeclared identifier 'assert'
        assert( type == CV_64FC1 );
        ^
In file included from /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgcodecs/src/loadsave.cpp:46:
In file included from /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgcodecs/src/precomp.hpp:50:
In file included from /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgproc/include/opencv2/imgproc/imgproc_c.h:46:
In file included from /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/imgproc/include/opencv2/imgproc/types_c.h:46:
/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Source/modules/core/include/opencv2/core/core_c.h:1133:5: error: use of undeclared identifier 'assert'
    assert( _elem->flags >= 0 /*&& (elem->flags & CV_SET_ELEM_IDX_MASK) < set_header->total*/ );
    ^
6 errors generated.
make[5]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/src/loadsave.cpp.o] Error 1
make[4]: *** [modules/imgcodecs/CMakeFiles/opencv_imgcodecs.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [OpenCV-release-prefix/src/OpenCV-release-stamp/OpenCV-release-build] Error 2
make[1]: *** [CMakeFiles/OpenCV-release.dir/all] Error 2
make: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV
[hunter ** FATAL ERROR **] [Directory:/Users/dhirvonen/devel/hunter/cmake/projects/OpenCV]
```
This really seems to have nothing to do with hunter, although it does affect hunter packages, and I'm posting this in case other people run into this same issue, which appears to be a side effect of the GStreamer framework shadowing the assert.h file locally.

UPDATE: Looking at the CMakeCache.txt of the OpenCV recipe, it seems GStreamer is picked up for both PNG and TIFF packages (which ends up putting the GStreamer assert.h in the preprocessor path), so providing a top level PNG_ROOT and TIFF_ROOT hint could be a work around.

```
/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Build/CMakeCache.txt:WITH_GSTREAMER:INTERNAL=OFF
/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Build/OpenCV-release-prefix/src/OpenCV-release-build/CMakeCache.txt:PNG_PNG_INCLUDE_DIR:PATH=/Library/Frameworks/GStreamer.framework/Headers
/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Build/OpenCV-release-prefix/src/OpenCV-release-build/CMakeCache.txt:TIFF_INCLUDE_DIR:PATH=/Library/Frameworks/GStreamer.framework/Headers
/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Build/OpenCV-release-prefix/src/OpenCV-release-build/CMakeCache.txt://Enable Gstreamer 0.10 support (instead of 1.x)
/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV/Build/OpenCV-release-prefix/src/OpenCV-release-build/CMakeCache.txt:WITH_GSTREAMER_0_10:BOOL=OFF
/
```

**Comment by ruslo** [comment]
> /Users/dhirvonen/devel/hunter/_Base/**xxxxxxx**/ccec2c2/b2b5fbe

`xxxxxxx` means you're using Hunter cloned from git. This usage case is for development and mean that `HunterGate` is not actually loading anything. So you need to update local git repository manually. In general you don't need to clone Hunter, `HunterGate` will do all the job for you.


> On my OS X system /Library/Frameworks/GSTreamer.framework seems to be first in line for providing ZLIB (and possibly PNG) dependencies

It's not the case of Hunter. There must be a string `ZLIB::zlib` in cache. Please try to find `CMakeCache.txt` first in `/Users/dhirvonen/devel/hunter/_Base/xxxxxxx/ccec2c2/b2b5fbe/Build/OpenCV` directory. And this file must contain information about zlib:

```bash
> grep -i zlib /.../CMakeCache.txt
```

**Comment by ruslo** [comment]
I'm testing `libcxx` toolchain on OS X, I see this flag in build:
```
-isystem /.../_Base/9308d01/ccec2c2/c018e63/Install/include
```
and some important info from cache `/Build/OpenCV/Build/OpenCV-release-prefix/src/CMakeCache.txt`:
```bash
> grep -i zlib
//The directory containing a CMake configuration file for ZLIB.
ZLIB_DIR:PATH=/.../_Base/9308d01/ccec2c2/c018e63/Install/lib/cmake/ZLIB
//Build zlib from source
BUILD_ZLIB:INTERNAL=OFF
//Details about finding ZLIB
FIND_PACKAGE_MESSAGE_DETAILS_ZLIB:INTERNAL=[ZLIB::zlib][/.../_Base/9308d01/ccec2c2/c018e63/Install/include][v1.2.8()]
```

I'm using:
```cmake
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.8.10.tar.gz"
    SHA1 "9308d01ea52c7b8cf1347073c982c679dbac3c09"
)
```

**Comment by headupinclouds** [comment]
>> xxxxxxx means you're using Hunter cloned from git. This usage case is for development and mean that HunterGate is not actually loading anything. So you need to update local git repository manually. In general you don't need to clone Hunter, HunterGate will do all the job for you.

I have a few new hunter packages I've defined locally, so I've been using a hunter clone to support that (they are slowly getting pushed to hunter, but I'll probably always need to maintain some set of local package definitions for things I'm experimenting with).  

I believe in this case GStreamer is picked up to satisfy OpenCV TIFF and PNG dependencies, but the new hunter.cmake OpenCV recipe is disabling those 

```
hunter_cmake_args(
    OpenCV
    CMAKE_ARGS
        BUILD_DOCS=OFF
        BUILD_TESTS=OFF
        BUILD_PERF_TESTS=OFF
        BUILD_opencv_apps=OFF
        BUILD_EXAMPLES=OFF
        # Find packages in Hunter (instead of building from OpenCV sources)
        BUILD_ZLIB=OFF
        BUILD_TIFF=OFF
        BUILD_PNG=OFF
)
```

I hadn't looked through the updates to that file carefully, but they all make sense.    You had added that to  help hunterize OpenCV in the new "2.4.11-p1" release (to fix 3rd party conflicts), but my code is still dependent on the unhunterized "3.0.0-beta" release, so when it is told to use (but not build) TIFF, for example, it looks elsewhere.   When a 3.0.0-beta-p1 release is made that will probably fix the issue.  In short, this is probably due to an OpenCV module that is under construction, combined with a broken GSTreamer release.  After some more searching, I fetched the latest GStreamer.framework, and they have apparently renamed their internal assert.h file to something much friendlier.

**Comment by headupinclouds** [comment]
I'm going to leave this open until the other opencv releases are hunterized (or temporarily removed).

**Comment by ruslo** [comment]
> I have a few new hunter packages I've defined locally, so I've been using a hunter clone to support that (they are slowly getting pushed to hunter, but I'll probably always need to maintain some set of local package definitions for things I'm experimenting with)

I was thinking about implementing injections correctly in smoother way. As I mentioned earlier take a look at this feature: https://github.com/ruslo/hunter/issues/56

Spoiler: in such way aslo can be supported GIT_SHA1 or even reading GIT_SHA1 from git submodule

**Comment by ruslo** [comment]
Talking about `c++11`. I've got this error on my OS X build:
```
/.../hunter-packages/opencv/modules/highgui/src/window_cocoa.mm:153:42: error: cannot initialize a parameter of type 'NSApplicationActivationPolicy' with an rvalue of type 'int'
```

window_cocoa.mm:
```
147 #if MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_6
148
149 #ifndef NSAppKitVersionNumber10_5
150 #define NSAppKitVersionNumber10_5 949
151 #endif
152     if( floor(NSAppKitVersionNumber) > NSAppKitVersionNumber10_5 )
153         [application setActivationPolicy:0/*NSApplicationActivationPolicyRegular*/]; // <<< conversion error
154 #endif
```

**Comment by headupinclouds** [comment]
Which version of OS X and Xcode do you have installed?  I'm on OS X 10.9.5
and Xcode 6.2.


Is this the same error that was fixed by switching to ios-8-2-cxx98?  I'd
be curious if running the stock opencv framework python script points to
any solutions:


opencv//platforms/ios/build_framework.py


python platforms/ios/build_framework.py ios


I don't see anything that would seem to be specific to c++11 in those few
lines of code.

I noticed I still have these configurations in my CMakeLists.txt.  I'm
assuming your original ios-8-2 was similar.

list(APPEND CMAKE_CXX_FLAGS "-std=c++11")

list(APPEND CMAKE_CXX_FLAGS "-stdlib=libc++")


set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++11")

set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LIBRARY "libc++")

set(CMAKE_XCODE_ATTRIBUTE_CLANG_ENABLE_OBJC_ARC YES)

**Comment by ruslo** [comment]
> running the stock opencv framework python script points to any solutions

this build doesn't set `c++11` flags

> Is this the same error that was fixed by switching to ios-8-2-cxx98

I think yes

> Which version of OS X and Xcode do you have installed?  I'm on OS X 10.9.5 and Xcode 6.2

I'm using Xcode 6.2 too, I don't think OS X version matter, but I have 10.10.3

> I don't see anything that would seem to be specific to c++11 in those few lines of code

I think some conversion policies are just more pedantic. I've used `NSApplicationActivationPolicyRegular` instead of `0` and it works. I'm applying hunterize patches anyway, so I will apply this one too.

> I noticed I still have these configurations in my CMakeLists.txt.  I'm
assuming your original ios-8-2 was similar

> list(APPEND CMAKE_CXX_FLAGS "-std=c++11")
> list(APPEND CMAKE_CXX_FLAGS "-stdlib=libc++")

Does it work for you? If this is toolchain file then this flags will be ignored, you need to set to CACHE. Also CMAKE_CXX_FLAGS is not a list but a string, so you need to set it like this:
```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```

**Comment by ruslo** [comment]
@headupinclouds OpenCV 3.0.0 added: https://github.com/ruslo/hunter/commit/eb7658b101ba9f0c7f80227fde8196a5363cd2c0 please pull branch `develop`. c++11 patches applied too, so must work fine with `ios-8-2` toolchain.

**Comment by ruslo** [comment]
@headupinclouds Hi David. So OpenCV 3.0.0 works for you and this bug can be closed?

**Comment by headupinclouds** [comment]
Yes.
