### ISSUE TITLE
OpenCV and CUDA

### ISSUE THREAD

**Issue by caseymcc** [ruslo/hunter#731]
Since we don't have a package for CUDA should we default the OpenCV package to turn off CUDA. Currently it searches the host system for CUDA and uses it if found. However this seems to go against the cross-compile ideology.

**Comment by ruslo** [comment]
> Currently it searches the host system for CUDA and uses it if found

Yes we should disable it by default, please send the patch with the corresponding option.

**Comment by caseymcc** [comment]
patch has been merged
https://github.com/ruslo/hunter/pull/732
