### ISSUE TITLE
Binaries cache

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#74]
Share built binaries between several `Hunter-ID` directories. For now sharing implemented only for downloaded sources (`${HUNTER_ROOT}/_Base/Download`).

Need to check this idea is working:
* Install package to package's specific location first => patch build schemes so they use `HUNTER_PACKAGE_INSTALL_DIR` instead of global `HUNTER_INSTALL_PREFIX`
* Pack `HUNTER_PACKAGE_INSTALL_DIR` to `*.tar.gz` archive and move it to cache `${HUNTER_ROOT}/_Base/Cache`
* Save meta information using formula:
 * SHA1 of archive of sources **+**
 * SHA1 of cache `*.tar.gz` of dependencies **+**
 * SHA1 of toolchain.info **+**
 * SHA1 of args.cmake (build options, cmake_args) **+**
 * SHA1 of internal dependent files (like build scheme) (?) **=**
 * SHA1 of cache `*.tar.gz`
* Unpack `*.tar.gz` archive from cache to `HUNTER_INSTALL_PREFIX` for each `Hunter-ID` build on cache hit (same meta information)

Some major problems to fix/implement:
* Track dependencies for packages. In general we must track all dependencies transitively. Probably introduce some internal variable that holds information about currently building package and when `hunter_download` triggered use this variable to store info `Foo depends on Boo`.
* Fix packages relocation problems. All packages must use CMake imported target format (like `ZLIB::zlib`). As far as I know this is the only sense way to make relocatable package that works nicely with transitive `find_package` commands with target usage requirement. Need to patch existing CMake builds + introduce imported version of `Find*` modules for non-CMake packages like Boost or OpenSSL

**Comment by ruslo** [comment]
I'm testing this feature now. Code is in branch 'bin.cache'.
Release: https://github.com/ruslo/hunter/releases/tag/v0.10.0

As I've already mentioned not all the packages are relocatable by default.
Cache will be used only for packages that marked by [hunter_cacheable][1] command.
For now I've added some packages which I tested: TIFF, ZLIB and GTest.

I will add more so we can build GPUOpenCV from cache:
* OpenCV (fix [bug][2] + dependent [PNG][3])
* Boost (fix [bug][4])
* cvmatio (can be cached already?)
* GPUImage (can be cached already?)

and will close this bug, other packages will be added in future.

Some important changes which are visible by users:
* successful build of cacheable package:
```
-- [hunter] Cache saved: /.../.hunter/_Base/Cache/raw/752c8b96f5613ee865c0cda5f3306d67e463a977.tar.bz2
```
* successful cache look-up (reuse/unpacked from cache):
```
-- [hunter] Cache HIT: GTest
```

[1]: https://github.com/ruslo/hunter/wiki/dev.modules#hunter_cacheable
[2]: https://github.com/ruslo/hunter/issues/81
[3]: https://github.com/ruslo/hunter/issues/114
[4]: https://github.com/ruslo/hunter/issues/106

**Comment by headupinclouds** [comment]
This is really cool.  I will take a look this weekend.

>> and will close this bug

This is technically more of a feature, isn't it?  Not that it matters.

>> hunter toolchain sharing

Question: Is it possible to specify identical polly toolchains that differ
only in use of the generator (same ABI, etc).  For example, I'd like to
make sure OpenCV and boost builds are generated 1x and shared between both
Unix Makefiles and Xcode CMake generator build trees for my current
project.  I haven't hunted around to see if this is already happening, and
have no idea what work is involved if it isn't happening.  Maybe that is a
messy feature, but if the config-id is the same it would seem to be
possible.

**Comment by ruslo** [comment]
> Question: Is it possible to specify identical polly toolchains that differ
only in use of the generator (same ABI, etc)

Well in general yes, but for now `CMAKE_GENERATOR` variable is part of the toolchain-id information. This is mainly because such generators like Visual Studio vs NMake and Makefile vs Xcode was building configurations (Release/Debug) differently. For now this is unified in one build scheme `url_sha1_cmake`. But there are some peculiarities I've noticed:
* Seems that NMake doesn't work well with '/MP' (use all cores) option. Visual Studio generator use 100% of all available cores (from my experience)
* Some packages is broken for Visual Studio, but works for NMake (see [LLVM](https://github.com/ruslo/hunter/blob/3b32477cfb39e8cbab3d4da1e28ff0b18ff327cc/cmake/projects/LLVM/hunter.cmake#L69))

so what to choose exactly when you need to build Visual Studio/NMake ABI-compatible environment?
Probably same problems can occurs with Makefile vs Xcode, but in general if all other compatibility info  is the same I can just remove `CMAKE_GENERATOR` field from toolchain-id calculator and I expect it will work fine.

**Comment by ruslo** [comment]
Version [0.10.7](https://github.com/ruslo/hunter/releases/tag/v0.10.7) has cacheable packages:
* OpenCV (+ dependencies)
* Boost (updated [pkg.boost](https://github.com/ruslo/hunter/wiki/pkg.boost))
* cvmatio
* GPUImage

**Comment by ruslo** [comment]
```    
* Save meta information using formula:
    SHA1 of archive of sources +
    SHA1 of cache *.tar.gz of dependencies +
    SHA1 of toolchain.info +
    SHA1 of args.cmake (build options, cmake_args) +
    SHA1 of internal dependent files (like build scheme) (?) =
    SHA1 of cache *.tar.gz
```

> SHA1 of internal dependent files (like build scheme) (?)

`PACKAGE_INTERNAL_DEPS_ID` added. See https://github.com/ruslo/hunter/issues/194.

**Comment by jakesyl** [comment]
It looks like this feature is only working for 1 dependency at a time
