### ISSUE TITLE
pkg:zmqpp - CMake not finding zmqppd.lib on Windows

### ISSUE THREAD

**Issue by Mystfit** [ruslo/hunter#740]
I'm attempting to add ZMQPP to a project on windows but I'm running into this issue.

```
CMake Error at C:/.hunter/_Base/4ef305d/b3db82c/f74f01e/Install/lib/cmake/ZMQPP/ZMQPPTargets.cmake:87 (message):
  The imported target "ZMQPP::zmqpp" references the file

     "C:/.hunter/_Base/4ef305d/b3db82c/f74f01e/Install/lib/zmqppd.lib"

  but this file does not exist.
```

Checking the C:\.hunter\_Base\4ef305d\b3db82c\f74f01e\Install\lib folder, there are both zmqpp-static.lib and zmqpp-staticd.lib files present, so it looks as though the libraries are being built, but hunter is searching for a lib file with the wrong suffix.

Adding this line to my cmake/Hunter/config.cmake file results in the same error.
`hunter_config(ZMQPP VERSION ${HUNTER_ZMQPP_VERSION} CMAKE_ARGS ZMQPP_BUILD_STATIC=on ZMQPP_BUILD_SHARED=on)`

Is there a flag I should be setting in order to set the correct suffix for the library? I'm currently building on Windows 10 using Visual Studio Community 2015 version 14 and CMake 3.8.0-rc4.

**Comment by ruslo** [comment]
> there are both zmqpp-static.lib and zmqpp-staticd.lib files present, so it looks as though the libraries are being built, but hunter is searching for a lib file with the wrong suffix

It's not Hunter responsibility, looks like `*Config.cmake` file is written incorrectly. It's an upstream issue. For your info fork is here:
* https://github.com/hunter-packages/zeromq4-1

Feel free to send the patch with fixes.

> I'm currently building on Windows 10 using Visual Studio Community 2015 version 14 and CMake 3.8.0-rc4

According to the [pkg.zmqpp](https://github.com/ruslo/hunter/wiki/pkg.zmqpp) this package works only on Linux. You can take a look at testing toolchains here:
* https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=pkg.zeromq

If you follow AppVeyor link (Windows testing) there is only "dummy" toolchain, which means that there are no real toolchains used in testing.

**Comment by ruslo** [comment]
Not a Hunter issue, closing.
