### ISSUE TITLE
Broken package: Boost + Visual Studio 2017

### ISSUE THREAD

**Issue by gashmish** [ruslo/hunter#745]
I have problem building Boost package with VS2017 on v0.18.20 

`
Performing install step for 'Boost' CMake Error at C:/cygwin64/home/dsplabs/.hunter/_Base/8f75b22/8d0c407/c565a23/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug.cmake:16 (message): Command failed: 1 'C:/Program Files/CMake/bin/cmake.exe' '-Dmake=' '-Dconfig=Debug' '-P' 'C:/cygwin64/home/dsplabs/.hunter/_Base/8f75b22/8d0c407/c565a23/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake'
`

In Boost-install-err.log:
`
CMake Error at C:/cygwin64/home/dsplabs/.hunter/_Base/8f75b22/8d0c407/c565a23/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake:9 (message): Command failed (1): 'b2' '--layout=tagged' '-d0' 'install' '--without-atomic' '--without-chrono' '--without-container' '--without-context' '--without-coroutine' '--without-coroutine2' '--without-date_time' '--without-exception' '--without-fiber' '--without-filesystem' '--without-graph' '--without-graph_parallel' '--without-iostreams' '--without-locale' '--without-log' '--without-math' '--without-metaparse' '--without-mpi' '--without-program_options' '--without-python' '--without-random' '--without-regex' '--without-serialization' '--without-signals' '--without-system' '--without-test' '--without-thread' '--without-timer' '--without-type_erasure' '--without-wave' '--prefix=C:/cygwin64/home/dsplabs/.hunter/_Base/8f75b22/8d0c407/c565a23/Build/Boost/Install'
`

With VS2015 and v0.16.15 this worked fine

**Comment by ruslo** [comment]
> Command failed (1)

So it just failed, no other messages?

**Comment by gashmish** [comment]
Yes, this is a whole Boost-install-err.log

**Comment by dvirtz** [comment]
This is due to vcvarsall changing directory to %USERPROFILE%\Source unless VSCMD_START_DIR is set to some other directory. See https://developercommunity.visualstudio.com/content/problem/26780/vsdevcmdbat-changes-the-current-working-directory.html

@ruslo Do you have an idea how to set this variable before calling vcvarsall?
My only idea is to add a new batch file which will set this variable to current directory but maybe there's a better solution.

**Comment by ruslo** [comment]
Environment variables is a weak point of ExternalProject_Add. For now you have to create CMake wrapper script and use `set(ENV{name} ${value})` there. Then call this script on ExternalProject_Add stage.
Read this issue https://github.com/ruslo/hunter/issues/290.

May be there is an argument we can add to `vcvarsall.bat` call?

Am I understanding correctly that removing `%USERPROFILE%\Source` will do the trick too?

**Comment by dvirtz** [comment]
Deleting %USERPROFILE%\Source works for me.
What about calling vcvarsall via cmake -E env command?

**Comment by ruslo** [comment]
> What about calling vcvarsall via cmake -E env command?

Not sure

**Comment by xsacha** [comment]
Is this still an issue? I seem to have built Boost 1.64 with MSVC2017 just fine.

**Comment by ruslo** [comment]
> I seem to have built Boost 1.64 with MSVC2017 just fine

Closing.

**Comment by ruslo** [comment]
> This is due to vcvarsall changing directory to %USERPROFILE%\Source unless VSCMD_START_DIR is set to some other directory.

Should not be a problem anymore, see this pull request: https://github.com/ruslo/hunter/pull/1145
