### ISSUE TITLE
adding Beast

### ISSUE THREAD

**Issue by dvirtz** [ruslo/hunter#747]
https://github.com/vinniefalco/Beast

please create a Hunter repo.

**Comment by xsacha** [comment]
Would tests be hunterised or excluded?
Right now tests compile all the zlib 1.2.8 source in-project.

**Comment by dvirtz** [comment]
I'm not sure, what's the convention?

**Comment by ruslo** [comment]
> please create a Hunter repo.

Done: https://github.com/hunter-packages/Beast

> Would tests be hunterised or excluded?

Tests should be excluded, it's not a Hunter responsibility:
* https://docs.hunter.sh/en/latest/creating-new/cmake.html#cmake-options

**Comment by headupinclouds** [comment]
Close?

**Comment by ruslo** [comment]
> Close?

Yep

**Comment by MatrixHan** [comment]
then boost children  not found beast
