### ISSUE TITLE
add package for mysql-client

### ISSUE THREAD

**Issue by caseymcc** [ruslo/hunter#750]
Fixed some of the issues with the mysql-client, but it requires some minor modifications to its cmake setup so going to need a hunter package. Fixed the issues with the debug build as well as compiling on windows.

https://travis-ci.org/caseymcc/hunter/builds/218650665
https://ci.appveyor.com/project/caseymcc/hunter/build/1.0.100

**Comment by ruslo** [comment]
Is there GitHub official repo? Does Git used as a VCS for official sources?

**Comment by caseymcc** [comment]
There seems to be (https://github.com/mysql/mysql-connector-cpp) but it is not the same that is used to build the current mysql-client (missing some of the source libraries used in the main mysql repository). It was downloaded from (https://dev.mysql.com/downloads/connector/cpp/1.0.html). It might be worth checking if the connector-cpp is all that is need to actually build a functional connector.

For the fix I downloaded the source and pushed it to https://github.com/caseymcc/mysql-client, then created a hunter branch with the fixes.

**Comment by ruslo** [comment]
Ok, I see, created: https://github.com/hunter-packages/mysql-client

> For the fix I downloaded the source and pushed it to https://github.com/caseymcc/mysql-client, then created a hunter branch with the fixes.

This is similar to Boost approach:
* https://github.com/hunter-packages/boost

Please create branch with version and add clean state first. Then add patches. Example:
* https://github.com/hunter-packages/boost/commits/boost-1.58.0

**Comment by caseymcc** [comment]
package opened and merged.
https://github.com/ruslo/hunter/pull/755
