### ISSUE TITLE
CMAKE_VS_DEVENV_COMMAND is empty

### ISSUE THREAD

**Issue by alienzj** [ruslo/hunter#751]
1> Command line: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\zhujie\AppData\Local\CMakeBuild\877c8177-4761-4033-89b6-882311601906\build\install"  --DCMAKE_BUILD_TYPE="Debug" "D:\projects\metapp"
1> Working directory: C:\Users\zhujie\AppData\Local\CMakeBuild\877c8177-4761-4033-89b6-882311601906\build\x86-Debug
1> -- [hunter] Calculating Config-SHA1
1> -- [hunter] Calculating Toolchain-SHA1
1> -- [hunter] HUNTER_ROOT: D:/program/hunter_root
1> -- [hunter] [ Hunter-ID: 50eaca2 | Config-ID: a9b8ca2 | Toolchain-ID: 5ae8cae ]
1> 
1> [hunter ** INTERNAL **] CMAKE_VS_DEVENV_COMMAND is empty
1> [hunter ** INTERNAL **] [Directory:D:/projects/metapp]
1> 
1> ------------------------------ WIKI -------------------------------
1>     https://github.com/ruslo/hunter/wiki/error.internal
1> -------------------------------------------------------------------
1> 
1> CMake Error at D:/program/hunter_root/_Base/Download/Hunter/0.18.36/50eaca2/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
1> Call Stack (most recent call first):
1>   D:/program/hunter_root/_Base/Download/Hunter/0.18.36/50eaca2/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
1>   D:/program/hunter_root/_Base/Download/Hunter/0.18.36/50eaca2/Unpacked/cmake/modules/hunter_setup_msvc.cmake:117 (hunter_internal_error)
1>   D:/program/hunter_root/_Base/Download/Hunter/0.18.36/50eaca2/Unpacked/cmake/modules/hunter_finalize.cmake:104 (hunter_setup_msvc)
1>   D:/program/hunter_root/_Base/Download/Hunter/0.18.36/50eaca2/Unpacked/cmake/modules/hunter_add_package.cmake:23 (hunter_finalize)
1>   CMakeLists.txt:11 (hunter_add_package)
1> 
1> 
1> -- Configuring incomplete, errors occurred!
1> See also "C:/Users/zhujie/AppData/Local/CMakeBuild/877c8177-4761-4033-89b6-882311601906/build/x86-Debug/CMakeFiles/CMakeOutput.log".
1> C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Visual Studio 15 2017" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\zhujie\AppData\Local\CMakeBuild\877c8177-4761-4033-89b6-882311601906\build\install"  --DCMAKE_BUILD_TYPE="Debug" "D:\projects\metapp" returned with exit code: 1

**Comment by LovelornPig** [comment]
D:\projects\metapp>cmake -H. -B_builds -DHUNTER_STATUS_DEBUG=ON -DCMAKE_BUILD_TYPE=Release
-- [hunter *** DEBUG *** 2017-04-05T22:30:54] HUNTER_ROOT detected by environment variable
-- [hunter *** DEBUG *** 2017-04-05T22:30:54] HUNTER_ROOT: D:/program/hunter_root
-- [hunter *** DEBUG *** 2017-04-05T22:30:54] Settings (initialize):
-- [hunter *** DEBUG *** 2017-04-05T22:30:54]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2017-04-05T22:30:54]   Cache init (YES)
-- The C compiler identification is MSVC 19.10.25017.0
-- The CXX compiler identification is MSVC 19.10.25017.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- [hunter *** DEBUG *** 2017-04-05T22:31:07] Single-configuration generator
-- [hunter *** DEBUG *** 2017-04-05T22:31:07] List of cache servers:
-- [hunter *** DEBUG *** 2017-04-05T22:31:07]   * https://github.com/ingenue/hunter-cache
-- [hunter *** DEBUG *** 2017-04-05T22:31:07] Settings (finalize):
-- [hunter *** DEBUG *** 2017-04-05T22:31:07]   HunterGate done (NO)
-- [hunter *** DEBUG *** 2017-04-05T22:31:07]   Cache init (NO)
-- [hunter *** DEBUG *** 2017-04-05T22:31:07] Variables from HunterGate:
-- [hunter *** DEBUG *** 2017-04-05T22:31:07]   HUNTER_GATE_ROOT: D:/program/hunter_root
-- [hunter *** DEBUG *** 2017-04-05T22:31:07]   HUNTER_GATE_VERSION: 0.18.36
-- [hunter *** DEBUG *** 2017-04-05T22:31:07]   HUNTER_GATE_SHA1: 50eaca2a8083ac266bdec6655c64f352c380b784
-- [hunter] Calculating Config-SHA1
-- [hunter *** DEBUG *** 2017-04-05T22:31:08] Set CMAKE_DEBUG_POSTFIX to: d
-- [hunter] Calculating Toolchain-SHA1
-- [hunter *** DEBUG *** 2017-04-05T22:31:08] [D:/projects/metapp/_builds/_3rdParty/Hunter/toolchain] > "D:/program/cmake-3.7.2/bin/cmake.exe" "-DTOOLCHAIN_INFO_FILE=D:/projects/metapp/_builds/_3rdParty/Hunter/toolchain/toolchain.info" "-DHUNTER_SELF=D:/program/hunter_root/_Base/Download/Hunter/0.18.36/50eaca2/Unpacked" "-GNMake Makefiles" "-HD:/projects/metapp/_builds/_3rdParty/Hunter/toolchain" "-BD:/projects/metapp/_builds/_3rdParty/Hunter/toolchain/_builds" "-DCMAKE_MAKE_PROGRAM=nmake" "-DCMAKE_RELEASE_POSTFIX=" "-DCMAKE_DEBUG_POSTFIX=d"
-- The C compiler identification is MSVC 19.10.25017.0
-- The CXX compiler identification is MSVC 19.10.25017.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/HostX64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: D:/projects/metapp/_builds/_3rdParty/Hunter/toolchain/_builds
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] Locking directory: D:/program/hunter_root/_Base/50eaca2/a9b8ca2/8e315c1
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] Lock done
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] Locking directory: D:/program/hunter_root/_Base/50eaca2/a9b8ca2/8e315c1
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] Lock done
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] Toolchain info: D:/program/hunter_root/_Base/50eaca2/a9b8ca2/8e315c1/toolchain.info
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] Toolchain SHA1: 8e315c18780bb31b76e5f482e5932d2e111f3da7
-- [hunter] HUNTER_ROOT: D:/program/hunter_root
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] HUNTER_TOOLCHAIN_ID_PATH: D:/program/hunter_root/_Base/50eaca2/a9b8ca2/8e315c1
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] HUNTER_CONFIGURATION_TYPES: Release;Debug
-- [hunter] [ Hunter-ID: 50eaca2 | Config-ID: a9b8ca2 | Toolchain-ID: 8e315c1 ]
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] Locking directory: D:/program/hunter_root/_Base/50eaca2/a9b8ca2/8e315c1
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] Lock done
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_C_SIZEOF_DATA_PTR = 8
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_C_COMPILER_ABI =
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_C_IMPLICIT_LINK_LIBRARIES =
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_C_IMPLICIT_LINK_DIRECTORIES =
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_C_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES =
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_C_LIBRARY_ARCHITECTURE =
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_C_ABI_COMPILED = TRUE
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_CXX_SIZEOF_DATA_PTR = 8
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_CXX_COMPILER_ABI =
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_CXX_IMPLICIT_LINK_LIBRARIES =
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES =
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_CXX_IMPLICIT_LINK_FRAMEWORK_DIRECTORIES =
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_CXX_LIBRARY_ARCHITECTURE =
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] ABI forwarding: CMAKE_CXX_ABI_COMPILED = TRUE
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] HUNTER_MSVC_VERSION: 15
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] HUNTER_MSVC_YEAR: 2017
-- [hunter *** DEBUG *** 2017-04-05T22:31:14] HUNTER_MSVC_ARCH: amd64

[hunter ** INTERNAL **] vcvarsall.bat not found in `C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC`
[hunter ** INTERNAL **] [Directory:D:/projects/metapp]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at D:/program/hunter_root/_Base/Download/Hunter/0.18.36/50eaca2/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  D:/program/hunter_root/_Base/Download/Hunter/0.18.36/50eaca2/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  D:/program/hunter_root/_Base/Download/Hunter/0.18.36/50eaca2/Unpacked/cmake/modules/hunter_setup_msvc.cmake:143 (hunter_internal_error)
  D:/program/hunter_root/_Base/Download/Hunter/0.18.36/50eaca2/Unpacked/cmake/modules/hunter_finalize.cmake:104 (hunter_setup_msvc)
  D:/program/hunter_root/_Base/Download/Hunter/0.18.36/50eaca2/Unpacked/cmake/modules/hunter_add_package.cmake:23 (hunter_finalize)
  CMakeLists.txt:11 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "D:/projects/metapp/_builds/CMakeFiles/CMakeOutput.log".
See also "D:/projects/metapp/_builds/CMakeFiles/CMakeError.log".

**Comment by ruslo** [comment]
> 1> [hunter ** INTERNAL **] CMAKE_VS_DEVENV_COMMAND is empty

It means the version of CMake is old and have no such variable defined.

> [hunter ** INTERNAL **] vcvarsall.bat not found in C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC

I've added extra debugging info (it's not fixed yet), please try this toolchain:
* https://github.com/ruslo/hunter/releases/tag/v0.18.38

**Comment by dvirtz** [comment]
this the version of CMake which comes with VS2017. Seems like it doesn't set CMAKE_VS_DEVENV_COMMAND, but does set CMAKE_VS_MSBUILD_COMMAND. 
See https://github.com/Microsoft/CMake/blob/cmake-daemon/Source/cmGlobalVisualStudio15Generator.cxx#L216

Maybe you can check for this variable as well?

**Comment by ruslo** [comment]
>  Seems like it doesn't set CMAKE_VS_DEVENV_COMMAND, but does set CMAKE_VS_MSBUILD_COMMAND

Sounds like an issue for me, it should be fixed in this version of CMake, not in Hunter. This variable is available in CMake 3.0:
* https://cmake.org/cmake/help/v3.0/variable/CMAKE_VS_DEVENV_COMMAND.html

**Comment by ShikiGami** [comment]
VS2017 is incompatible right now with Hunter, it may be an issue with the CMake in VS2017, but it still means that we cannot use just out of the box Hunter on VS2017 because of some trivial variable name.

**Comment by ruslo** [comment]
> VS2017 is incompatible right now with Hunter

It's not true Hunter works fine in general with Visual Studio 15 2017 generator.

> it may be an issue with the CMake in VS2017
>  use just out of the box Hunter on VS2017 because of some trivial variable name

Exactly, this is an issue in non-standard version of CMake. It should be fixed in there, not in Hunter.

**Comment by ShikiGami** [comment]
> It's not true Hunter works fine in general with Visual Studio 15 2017 generator.
Then we live in alternate realities, because every time I try Hunter on VS2017 with automatic generation it just fails with this error.

**Comment by ruslo** [comment]
https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1996:

```
`cmake`
`-HC:\projects\hunter\examples\GTest`
`-BC:\projects\hunter\_testing\_builds\vs-15-2017`
`-GVisual Studio 15 2017`
...
-- [hunter *** DEBUG *** 2017-07-22T06:36:28] HUNTER_MSVC_VERSION: 15
-- [hunter *** DEBUG *** 2017-07-22T06:36:28] HUNTER_MSVC_YEAR: 2017
-- [hunter *** DEBUG *** 2017-07-22T06:36:28] HUNTER_MSVC_ARCH: x86
-- [hunter *** DEBUG *** 2017-07-22T06:36:28] Environment 'VS150COMNTOOLS': ''
-- [hunter *** DEBUG *** 2017-07-22T06:36:28] CMAKE_VS_DEVENV_COMMAND: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community/Common7/IDE/devenv.com'
...
-- The C compiler identification is MSVC 19.10.25019.0
-- The CXX compiler identification is MSVC 19.10.25019.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/Hostx86/x86/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/Hostx86/x86/cl.exe -- works
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/Hostx86/x86/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.25017/bin/Hostx86/x86/cl.exe -- works
...
```

PS @ShikiGami Sorry, I don't have a portal gun to your reality, you have to find it yourself.

**Comment by kingofthebongo2008** [comment]
Hey i have got exactly the same problem as reported here with brand new windows 10 install and visual studio 2017 installed

Microsoft Visual Studio Community 2017 
Version 15.2 (26430.16) Release
Visual Studio tools for CMake   1.0

**Comment by kingofthebongo2008** [comment]
You can try replace the cmake from visual studio with the latest cmake 3.9

I have replaced it and this error went away. seems that microsoft are compiling different version of cmake, which is 3.7.20170106-gd3236-dirty-MSVC_2

I guess somebody should report this to the visual studio devteam somehow, otherwise hunter will not compile. i think they are compiling with different arguments there or do not distribute a script or something

**Comment by ShikiGami** [comment]
Yep, they are using their own version of CMake which doesn't implement these variables.

I don't know what environment @ruslo has, but it obviously isn't the pure last release of VS2017.

**Comment by ruslo** [comment]
> seems that microsoft are compiling different version of cmake

I've said it twice already in this thread.

**Comment by ruslo** [comment]
Release https://github.com/ruslo/hunter/releases/tag/v0.19.38 contains link to wiki page with explanation and workarounds: https://github.com/ruslo/hunter/wiki/error.vs.devenv

Closing.

**Comment by kapulkin** [comment]
Setting VS150COMNTOOLS to "D:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools" in my case, as written in https://github.com/ruslo/hunter/wiki/error.vs.devenv, really works.

**Comment by hjmallon** [comment]
I use the Microsoft Build tools. They include MSBUILD but do not include devenv (so the variable `CMAKE_VS_DEVENV_COMMAND` is set to "devenv.com"). CMAKE_VS_MSBUILD_COMMAND is set however to `"C:/Program Files (x86)/Microsoft Visual Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe"` where the vcvarsall script is in `"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build"`. Could hunter check the MSBuild key as well. For now I guess I can work around by setting VS150COMNTOOLS to `"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools"` manually.

**Comment by ruslo** [comment]
> Could hunter check the MSBuild key as well?

Not sure about details, but feel free to send pull request, if it will look good and tests for other toolchains will pass then we can do merge.

Also please avoid adding new comments to closed issues:
- https://docs.hunter.sh/en/latest/contacts.html#please-don-t
