### ISSUE TITLE
Cached builds of Boost for CI

### ISSUE THREAD

**Issue by chfast** [ruslo/hunter#759]
Based on requirements by cpp-ethereum project:

- [x] Boost, Ubuntu 14.04, GCC, Toolchain-ID: 8456c41
- [x] Boost.random, Ubuntu 14.04, GCC, Toolchain-ID: 8456c41
- [x] Boost.test, Ubuntu 14.04, GCC, Toolchain-ID: 8456c41
- [x] Boost, XCode 8.2, Toolchain-ID: fef358f
- [x] Boost.random, XCode 8.2, Toolchain-ID: fef358f
- [x] Boost.test, XCode 8.2, Toolchain-ID: fef358f
- [x] Boost, VS 14 2015 Win64, Toolchain-ID: 13789f3
- [x] Boost.random, VS 14 2015 Win64, Toolchain-ID: 13789f3
- [x] Boost.test, VS 14 2015 Win64, Toolchain-ID: 13789f3
- [x] Boost.filesystem, VS 14 2015 Win64, Toolchain-ID: 13789f3
- [x] Boost.system, VS 14 2015 Win64, Toolchain-ID: 13789f3
- [x] Boost.thread, VS 14 2015 Win64, Toolchain-ID: 13789f3

PR: https://github.com/ethereum/cpp-ethereum/pull/3653
Travis: https://travis-ci.org/ethereum/cpp-ethereum/builds/220520525

**Comment by ruslo** [comment]
> Boost, XCode 8.2, Toolchain-ID: fef358f

We have mismatch here, the problem probably is about deployment version of SDK. We can check it by comparing compiler flags, but I don't see it in https://travis-ci.org/ethereum/cpp-ethereum/builds/220520525 because there is no CMAKE_VERBOSE_MAKEFILE=ON added.

**Comment by chfast** [comment]
New verbose build on macOS: https://travis-ci.org/ethereum/cpp-ethereum/jobs/220592977.

**Comment by chfast** [comment]
Boost for Linux ready after upgrading the Hunter to the latest version: https://travis-ci.org/ethereum/cpp-ethereum/jobs/220686280#L613.

**Comment by ruslo** [comment]
> Log: https://s3.amazonaws.com/archive.travis-ci.org/jobs/220592977/log.txt

According to the logs compiler is not Xcode: `ccache /usr/local/opt/ccache/libexec/g++`. Also generator is just a `Unix Makefiles`. Seems that we need introduce new toolchain here.

**Comment by ruslo** [comment]
> Boost, VS 14 2015 Win64, Toolchain-ID: 13789f3
> Boost.random, VS 14 2015 Win64, Toolchain-ID: 13789f3
> Boost.test, VS 14 2015 Win64, Toolchain-ID: 13789f3

Should be ready:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1576

**Comment by ruslo** [comment]
> Seems that we need introduce new toolchain here

New `cxx11` toolchain added to Polly:
* https://travis-ci.org/forexample/hunter-simple/builds/220877572#L1568
* `-- [hunter] [ Hunter-ID: ... | Config-ID: ... | Toolchain-ID: fef358f ]`

**Comment by ruslo** [comment]
Running missing uploads:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1578
* https://travis-ci.org/ingenue/hunter/builds/220884533

**Comment by chfast** [comment]
Can't wait, thanks.

**Comment by chfast** [comment]
All Boost components taken from cache. Thanks a lot!
