### ISSUE TITLE
Cross compiling and pkg-config

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#762]
Hi Ruslan,

Cross compiling packages which use `pkg-config` (ex: OpenCV) ends up with the packages picking up the `*.pc` files in the default search directory (usually `/usr/lib/pkgconfig:/usr/share/pkgconfig`), hence breaking the build.

To avoid this, I hack into my toolchain file:
```CMake
set(ENV{PKG_CONFIG_LIBDIR} "<root-id>/share/pkgconfig:<root-id>/lib/pkgconfig")
``` 
I guess this behavior should be somewhere in either hunter or polly, but I find hard to precise. Would be nice to have some logic like:
```CMake
if(CMAKE_CROSSCOMPILING)
  set(ENV{PKG_CONFIG_LIBDIR} "<root-id>/share/pkgconfig:<root-id>/lib/pkgconfig")
endif()
```
Note that in the Autotools module something similar is done to change the `PKG_CONFIG_PATH`: which provides similar funcionality: [hunter_autotools_project.cmake](https://github.com/ruslo/hunter/blob/4cbd47b0fc87cea77b32e4adb9a0e08625537d88/cmake/modules/hunter_autotools_project.cmake#L318), however is superseeded by `PKG_CONFIG_LIBDIR`.

Do you have any idea how this problem could be solved?

Thanks

Reference: [man pkg-config](https://linux.die.net/man/1/pkg-config)

**Comment by ruslo** [comment]
> Would be nice to have some logic like

Sounds good for me. We can do it after we know `HUNTER_INSTALL_PREFIX`. Take a look at `hunter_finalize` module:
* https://github.com/ruslo/hunter/blob/4cbd47b0fc87cea77b32e4adb9a0e08625537d88/cmake/modules/hunter_finalize.cmake#L79

> Note that in the Autotools module something similar is done to change the PKG_CONFIG_PATH: which provides similar funcionality: hunter_autotools_project.cmake, however is superseeded by PKG_CONFIG_LIBDIR

Probably we should use PKG_CONFIG_LIBDIR here too?

**Comment by pretyman** [comment]
> Probably we should use PKG_CONFIG_LIBDIR here too?

If we did, then the system's `*.pc` files won't be found. I guess this is not the intention for now. (?)

**Comment by ruslo** [comment]
> If we did, then the system's *.pc files won't be found

Actually it fits better:
* https://docs.hunter.sh/en/latest/faq/interaction-with-other-package-managers.html

**Comment by ruslo** [comment]
Fixed by https://github.com/ruslo/hunter/pull/765 as far as I understand.
