### ISSUE TITLE
Add package for Gumbo, Google HTML parser library

### ISSUE THREAD

**Issue by eraxillan** [ruslo/hunter#767]
[The link](https://github.com/google/gumbo-parser)

It is pure C library without CMake support, only autotools supported.
However, i wrote one myself (see attach)
[CMakeLists.txt](https://github.com/ruslo/hunter/files/946168/CMakeLists.txt)

Please add this library to the Hunter repo.
Thanks!

**Comment by isaachier** [comment]
Please close this issue.
