### ISSUE TITLE
OpenCV should create static library by default

### ISSUE THREAD

**Issue by alamaison** [ruslo/hunter#77]
OpenCV is creating a shared library.  This means the build breaks with the usual PIC error on Linux because of #63.  By default, OpenCV in hunter should be configured to produce a static library.

**Comment by alamaison** [comment]
```
Linking CXX shared library ../../lib/libopencv_core.so
/usr/bin/ld: /home/ubuntu/workspace/hunter/PROJECT/OpenCV/TOOLCHAIN/default/_testing/Hunter/_Base/d628e6d/015448b/d580c2e/Install/lib/libz.a(gzlib.o): relocation R_X86_64_32S against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
```

**Comment by headupinclouds** [comment]
How about passing BUILD_SHARED_LIBS=OFF in the CMAKE_ARGS passed to the hunter_config command in CMakeLists.txt?  That's actually how I'm using it. 

```
# Configure this as needed for each platform
    set(OPENCV_CMAKE_ARGS 
      WITH_GSTREAMER=OFF
      WITH_OPENCLAMDBLAS=OFF
      WITH_CUDA=OFF
      WITH_FFMPEG=OFF
      WITH_WEBP=OFF
      WITH_OPENEXR=OFF
      BUILD_PACKAGE=OFF
      WITH_GIGEAPI=OFF
      WITH_CUFFT=OFF
      WITH_V4L=OFF
      WITH_OPENCLAMDFFT=OFF
      WITH_VTK=OFF
      BUILD_PERF_TESTS=OFF
      BUILD_DOCS=OFF
      WITH_1394=OFF
      WITH_LIBV4L=OFF
      WITH_EIGEN=ON
      BUILD_OPENEXR=OFF
      BUILD_FAT_JAVA_LIB=OFF
      BUILD_SHARED_LIBS=OFF
      WITH_OPENCL=OFF
      WITH_PVAPI=OFF
      BUILD_TESTS=OFF)

hunter_config(OpenCV VERSION 3.0.0-beta-p2 CMAKE_ARGS "${OPENCV_CMAKE_ARGS}")
hunter_add_package(OpenCV)
find_package(OpenCV REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
```

```
grep BUILD_SHARED ${HUNTER_ROOT}/_Base/xxxxxxx/015448b/b2b5fbe/Build/OpenCV/Build/CMakeCache.txt 
BUILD_SHARED_LIBS:INTERNAL=OFF
```

```
${HUNTER_ROOT}/_Base/xxxxxxx/015448b/b2b5fbe/Install/lib/libopencv_core.a 
```

**Comment by ruslo** [comment]
> How about passing BUILD_SHARED_LIBS=OFF in the CMAKE_ARGS

This can be used as a workaround but in general all packages must respect CMake "defaults". By default CMake command `add_library` produce static library. See [documentation](https://github.com/ruslo/hunter/wiki/usr.adding.new.package#default-behaviour).

> That's actually how I'm using it

Well, `hunter_config` command designed to be used only in `config.cmake` file effectively forming [Config-ID](https://github.com/ruslo/hunter/tree/develop#config-id). I will think about checking this - https://github.com/ruslo/hunter/issues/78

**Comment by ruslo** [comment]
Fixed in [v0.8.11](https://github.com/ruslo/hunter/releases/tag/v0.8.11). Looks like it's enough to add extra option 'BUILD_SHARED_LIBS=OFF`.

**Comment by alamaison** [comment]
Is that the right solution?  Doesn't that prevent using shared lib dependencies entirely?  How would someone choose to use shared libs?

I though the solution should be to add `hunter_cmake_args(OpenCV BUILD_SHARED_LIBS=OFF ...)` to `projects/OpenCV/hunter.cmake`.  Would have done it myself but was travelling.

**Comment by ruslo** [comment]
> Doesn't that prevent using shared lib dependencies entirely?

Nope. You can set it via 'hunter_config'. Since custom options has high priority this will work like this:
```cmake
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
# build shared here
```

Also [HUNTER_BUILD_SHARED_LIBS](https://github.com/ruslo/hunter/issues/21) will work similar, i.e. you can rewrite default value by custom CMAKE_ARGS from `hunter_config`.

**Comment by alamaison** [comment]
Great :) sorry for the noise
