### ISSUE TITLE
OpenSSL 1.1.0 does not build on Windows

### ISSUE THREAD

**Issue by zhuhaow** [ruslo/hunter#774]
Currently, building OpenSSL 1.1.0 on windows is disabled and 1.0.2 is picked up by default.

I run a few experiments and it seems like there is no other option to compile OpenSSL 1.1.0 for Windows without NASM. Though it is possible to use `no-asm` to run the perl configuration script, it still tries to use `ml64` and spits some errors when compiling (even if I add the path of ml64).

```
        set ASM=ml64
        "C:\Perl\bin\perl.exe" "ms\uplink-x86_64.pl" "auto" crypto\uplink-x86_64
.asm
no assembler found on %PATH% at ms\../crypto/perlasm/x86_64-xlate.pl line 98.
        ml64 /c /Cp /Cx /Zi /Focrypto\uplink-x86_64.obj "crypto\uplink-x86_64.as
m"
Microsoft (R) Macro Assembler (x64) Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

 Assembling: crypto\uplink-x86_64.asm
crypto\uplink-x86_64.asm(1) : error A2088:END directive required at end of file
NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\bin\amd64\ml64.EXE"' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"c:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\bin\amd64\nmake.exe"' : return code '0x2'
Stop.
```

As per the issue [here](https://github.com/openssl/openssl/issues/967), nasm will be a requirement to build OpenSSL and `no-asm` should not be used since it's only for debugging.
I'm wondering if it is possible to download nasm (it's less then 500KB compressed) by the CMake script. Not quite sure if it violates some principle of Hunter because it does adds a few things that are not part of OpenSSL. If that's a problem, we can either:
1. Put it in a temp folder and delete it afterwards
2. Just leave it in the source code folder.

Anyway, I would like to help to fix the OpenSSL building on Windows. Do let me know your thoughts.

**Comment by ruslo** [comment]
> I'm wondering if it is possible to download nasm

Yes, we can create `nasm` package.

**Comment by zhuhaow** [comment]
How do you think we should create the `nasm` package? By put it in a temp file and remove it afterwards? Or put it in the folder with OpenSSL source?

**Comment by ruslo** [comment]
> How do you think we should create the nasm package?

It depends. Is this tool open source? Or only binary available?

> By put it in a temp file and remove it afterwards? Or put it in the folder with OpenSSL source?

Adding to `PATH` should do the trick I guess.

**Comment by zhuhaow** [comment]
Released under 2-clause BSD license with officially build binary.

I think we should put it in some folder with OpenSSL source, add that to `PATH`, compile OpenSSL, then revert the `PATH`.

**Comment by ruslo** [comment]
> Released under 2-clause BSD license with officially build binary

Any links?

> I think we should put it in some folder with OpenSSL source, add that to PATH, compile OpenSSL, then revert the PATH.

I don't see the point of moving it to OpenSSL sources. Is it a requirement?

**Comment by zhuhaow** [comment]
http://www.nasm.us

> I don't see the point of moving it to OpenSSL sources. Is it a requirement?

It's not a requirement, but I think it makes thing look more self-contained. Of course it depends on how Hunter handles building dependencies.

**Comment by ruslo** [comment]
> http://www.nasm.us

See https://github.com/ruslo/hunter/issues/775

> Of course it depends on how Hunter handles building dependencies

We will call `hunter_add_package(nasm)` in build scheme to download/install dependency, then use variable `NASM_ROOT` to locate installed `nasm` binary and to update PATH.

**Comment by ruslo** [comment]
Closing inactive discussion.
