### ISSUE TITLE
Private gitlab Hunter_cache server

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#777]
I'd like to create a hunter_cache server just for me and my gitlab-ci builders. Currently only the official hunter github server is supported as hunter cache. Where would I need to begin to add any gitlab repo as server?

**Comment by ruslo** [comment]
There is Python script for uploading:
* https://github.com/ruslo/hunter/blob/master/maintenance/upload-cache-to-github.py

CMake modules for downloading:
* https://github.com/ruslo/hunter/blob/master/cmake/modules/hunter_download_cache_meta_file.cmake
* https://github.com/ruslo/hunter/blob/master/cmake/modules/hunter_download_cache_raw_file.cmake

> gitlab repo as server?

I don't know the capabilities of Gitlab. The best way is to have the ability to upload plain structure of the [cache directory](https://docs.hunter.sh/en/latest/reference/layouts/deployed.html#cache). Like:
```
https://example.com/hunter-cache/raw/XXX.tar.bz2
https://example.com/hunter-cache/meta/XXX/XXX/XXX/cache.sha1
https://example.com/hunter-cache/meta/XXX/XXX/XXX/cache.DONE
```
just to mirror original layout.

**Comment by hof** [comment]
I think you could also use a Nexus repository manager (raw) repository for this. 

http://stackoverflow.com/questions/37543120/how-to-manually-deploy-artifacts-in-nexus-repository-manager-oss-3/37547202#37547202

**Comment by ruslo** [comment]
> I think you could also use a Nexus repository manager (raw) repository for this.

Need to clarify the question. @NeroBurner Do we need to use Gitlab as a service for storing cache binaries or we need **anything** that can work with Gitlab. In the latter case it can be just Nginx with root directory pointing to cache directory (see the structure above).

**Comment by NeroBurner** [comment]
I didn't consideranything else than gitlab server, but I will try to use Nginx

**Comment by ruslo** [comment]
Example of using private non-GitHub binary server:
* https://docs.hunter.sh/en/latest/user-guides/hunter-user/nexus-cache-server.html
