### ISSUE TITLE
Check `hunter_config` is not used in user's `CMakeLists.txt`

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#78]
From: https://github.com/ruslo/hunter/issues/77

**Comment by headupinclouds** [comment]
I frequently need to change the OpenCV configuration via CMake flags on a per release and per platform basis.  It seemed that the cleanest way to do this was via platform specific hunter_config calls and the CMAKE_ARGS parameter within an if(a)/elseif(b)/endif() block in my project's CMakeLists.txt.   If hunter_config can't be specified inside CMakeLists.txt, then would such customization need to be made inside a user maintained ${HUNTER_ROOT}/cmake/configs/default.cmake?  

I suppose the local hunter.cmake module injections you have mentioned elsewhere would at some point provide an alternative mechanism for this, without require a user to maintain and modify contents of ${HUNTER_ROOT}.

**Comment by ruslo** [comment]
See wiki: https://github.com/ruslo/hunter/wiki/example.custom.config.id

**Comment by ruslo** [comment]
Fixed in [v0.8.12](https://github.com/ruslo/hunter/releases/tag/v0.8.12). Also see: https://github.com/ruslo/hunter/wiki/error.unexpected.hunter_config
