### ISSUE TITLE
boost fails to build with LLVM-vs2013 toolset

### ISSUE THREAD

**Issue by dvirtz** [ruslo/hunter#782]
boost filesystem build fails with 
`'C:Program' is not recognized as an internal or external command,
operable program or batch file.`

This is my CMakeLists.txt:

```cmake
cmake_minimum_required(VERSION 3.0)

list(APPEND CMAKE_MODULE_PATH ${CMAKE_SOURCE_DIR}/cmake)
include(HunterGate)

HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.18.46.tar.gz"
    SHA1 "e368cbf2a98cf8b8fa7a379fde74eca8ded425e3"
)

project(Test)

hunter_add_package(Boost COMPONENTS filesystem)
find_package(Boost CONFIG REQUIRED filesystem)

add_executable(Test main.cpp)

target_link_libraries(Test Boost::filesystem)
```

CMake version 3.3.1. command line
`cmake . -B_build -G "Visual Studio 12" -T LLVM-vs2013`

**Comment by xsacha** [comment]
Does LLVM-vs* work upstream?
I noticed it isn't part of their test suite. http://www.boost.org/users/history/version_1_64_0.html#bottom

**Comment by ruslo** [comment]
Closing inactive discussion.
