### ISSUE TITLE
Incorrect include path set for freetype package

### ISSUE THREAD

**Issue by 9prady9** [ruslo/hunter#784]
[Forge](https://github.com/arrayfire/forge) recently received a PR with hunter functionality. While hunter setup is great, we have encountered an issue using freetype package from hunter. 

The [documentation of freetype](https://www.freetype.org/freetype2/docs/tutorial/step1.html#section-1) suggests including `<root if any>/include/freetype2` as the include directory for any project using freetype2. However, freetype package from is including the parent folder of `freetype2` folder. 
Compilation Error 
```
forge/src/backend/opengl/font_impl.cpp:25:22: fatal error: ft2build.h: No such file or directory
compilation terminated.
src/backend/opengl/CMakeFiles/forge.dir/build.make:686: recipe for target 'src/backend/opengl/CMakeFiles/forge.dir/font_impl.cpp.o' failed
make[2]: *** [src/backend/opengl/CMakeFiles/forge.dir/font_impl.cpp.o] Error 1
CMakeFiles/Makefile2:215: recipe for target 'src/backend/opengl/CMakeFiles/forge.dir/all' failed
make[1]: *** [src/backend/opengl/CMakeFiles/forge.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

```
I believe this has to be fixed in freetype package for hunter. Please suggest how should we proceed for this or a work around for this issue.

Thanks.

**Comment by ruslo** [comment]
> The documentation of freetype suggests including <root if any>/include/freetype2 as the include directory for any project using freetype2

According to documentation include should looks like `#include <ft2build.h>`, example from Hunter for testing use the same approach:
* https://github.com/ruslo/hunter/blob/master/examples/freetype/foo.cpp

> Compilation Error

Can you show me the compiler flags?

**Comment by 9prady9** [comment]
Yes, that is how [the source](https://github.com/arrayfire/forge/blob/devel/src/backend/opengl/font_impl.cpp#L25) includes `ft2build.h`.

The link command is as follows
```
/usr/bin/c++   -DOS_LNX -DUSE_FREEIMAGE -DUSE_GLFW -Dforge_EXPORTS -I/home/pradeep/gitroot/forge/include -I/home/pradeep/.hunter/_Base/d2c8c42/04939ff/e1266bb/Install/include -I/home/pradeep/gitroot/forge/builds/hunter/src/backend -I/home/pradeep/gitroot/forge/src/backend/opengl -I/home/pradeep/gitroot/forge/src/api/c -I/home/pradeep/gitroot/forge/src/api/cpp -I/home/pradeep/gitroot/forge/src/backend -I/home/pradeep/gitroot/forge/builds/hunter/third_party/glb/include  -fPIC -g -fPIC   -Wall -std=c++11 -fvisibility=hidden -o CMakeFiles/forge.dir/font_impl.cpp.o -c /home/pradeep/gitroot/forge/src/backend/opengl/font_impl.cpp
/home/pradeep/gitroot/forge/src/backend/opengl/font_impl.cpp:25:22: fatal error: ft2build.h: No such file or directory
compilation terminated.
```
Below is the hunter install base `ls` command output
```
~/gitroot/forge/builds/hunter (devel *) $ls  /home/pradeep/.hunter/_Base/d2c8c42/04939ff/e1266bb/Install/include
boost  freetype2  glm
```

**Comment by ruslo** [comment]
It seems that freetype installed to `<root>/include/freetype2`. Looks like the `target_link_libraries(... freetype::freetype)` is missing - path will be added by this directive. See usage:
* https://github.com/ruslo/hunter/wiki/pkg.freetype

**Comment by 9prady9** [comment]
That worked, thank you for the prompt response! @ruslo
