### ISSUE TITLE
Add Caffe

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#79]
* http://caffe.berkeleyvision.org/installation.html

**Comment by ruslo** [comment]
Android port: https://github.com/sh1r0/caffe-android-lib

**Comment by ruslo** [comment]
Available since [v0.16.5](https://github.com/ruslo/hunter/releases/tag/v0.16.5). For now works only on Linux with minimal set of dependencies.

**Comment by wheybags** [comment]
Is there a way for a package to declare what platforms it works on? And if
not, is it something you'd be interested to see added?

**Comment by ruslo** [comment]
@wheybags There is [hunter_report_broken_package](https://github.com/ruslo/hunter/blob/master/cmake/modules/hunter_report_broken_package.cmake) module which you can add to `hunter.cmake`:
```cmake
if(APPLE)
  hunter_report_broken_package("Caffe script not works for the OSX because of missing ??? dependency")
endif()
```

User will see the message and link to the wiki page: https://github.com/ruslo/hunter/wiki/error.broken.package

This code will be checked before the real build instructions will be triggered so can save you some time. However for now this file is loaded only if corresponding `hunter_add_package` command called. Hence if there will be few directives earlier, the build command for them will be executed before such checks. It may be improved for some cases I think, need to discuss design.

Also you can check what toolchain used to upload the binaries:
* https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=caffe

As you can see for 'caffe' there is only Linux toolchain available:
* https://travis-ci.org/ingenue/hunter/builds/164987504

**Comment by wheybags** [comment]
Oh, cool
