### ISSUE TITLE
xorg-macros: `--strip` autoconf issue

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#795]
I noticed this in a `glfw` package build in an ubuntu unit test:

https://travis-ci.org/headupinclouds/ogles_gpgpu/jobs/232261502#L1041-L1048

This isn't critical for me, but I'll try to debug it later this week.  I'm not sure if this is specific to the package or the autoconf scheme stuff.

**Comment by ruslo** [comment]
I guess build script read environment variable `INSTALL`. If so we can add `INSTALL` to this list:
* https://github.com/ruslo/hunter/blob/master/scripts/clear-all.cmake

**Comment by ruslo** [comment]
Fixed by https://github.com/ruslo/hunter/pull/870
