### ISSUE TITLE
OpenCV can't find dependencies after change in pkg-config path on Linux

### ISSUE THREAD

**Issue by szatan** [ruslo/hunter#800]
OpenCV can't find FFMPEG (and other stuff like GTK, Qt, or V4L2) since https://github.com/ruslo/hunter/commit/f6f096561f0e09b4c85e4049a4eb7948ad24d7eb
This effectively makes OpenCV unable to process video on Linux.
The funny thing is everything seems to work fine on Windows and Mac.

Reverting the mentioned commit fixes the issue.
It is my understanding that isolating the build env from system libraries is the hunter way of doing things, but since none of the mentioned libraries can be built via hunter, using the system libraries seems like the only way to go in this particular case.
Am I missing something? Is there a way around it?

**Comment by ruslo** [comment]
This issue should be fixed by adding missing packages to Hunter. As a workaround you can use your own fork in development.

**Comment by szatan** [comment]
That's what I ended up doing in the end.
It's worth mentioning in https://github.com/ruslo/hunter/wiki/pkg.opencv
May same someone quite a lot of time.

**Comment by ruslo** [comment]
@szatan feel free to edit

**Comment by szatan** [comment]
Done

**Comment by ruslo** [comment]
@szatan Thanks. I think it's worth mentioning your fork where people can find ready-to-use releases.

**Comment by szatan** [comment]
Yeah, why not. I can't guarantee that I'll be updating it on a regular basis, but it'll be a good starting point.
I updated the wiki page.
