### ISSUE TITLE
Possible to alter CPPFLAGS in hunter_autotools_project?

### ISSUE THREAD

**Issue by tdavis** [ruslo/hunter#803]
So I've been adding/editing some packages to a local hunter clone. I'd like to change some of the `CPPFLAGS` specified for the `SQLite3` configuration, but I'd prefer to do it in a way that didn't involve just manually editing the scheme file since that would be tough to contribute back here and my flags aren't necessarily right for everyone. Is there a way to do this through CMake args? Or hunter.cmake? A custom scheme that can be picked via some mechanism before/when calling `hunter_add_package()` (e.g. `hunter_cmake_args()`)? Thanks for this extremely useful project!

**Comment by ruslo** [comment]
You can use [custom options](https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-cmake-options) feature:
```cmake
hunter_config(
    SQLite3
    VERSION ${HUNTER_SQLite3_VERSION}
    CMAKE_ARGS CMAKE_CXX_FLAGS=-fsomething
)
```

Should do the trick.

What kind of a nature is the problem? If flag is global then it should be set in toolchain. If it's SQLite3 specific and fix something, may be it make sense to contribute it to Hunter so other users can use it?

**Comment by tdavis** [comment]
My particular issue was not having SQLite3 configured with `-DSQLITE_ENABLE_COLUMN_METADATA` which enables a feature used by a library I also wrote a Hunter script for. However, I also added some other flags that SQLite folks recommend:

    -DSQLITE_DEFAULT_MEMSTATUS=0 
    -DSQLITE_DEFAULT_WAL_SYNCHRONOUS=1 
    -DSQLITE_LIKE_DOESNT_MATCH_BLOBS

These may not be appropriate to all Hunter users. Beyond that, I added the most recent version of the library (`autoconf-3190000`). Happy to submit a patch.

**Comment by ruslo** [comment]
We should mimick CMake here and use `CMAKE_ARGS`. Create the list of CMake variables for converting to C++ definitions and use them in CPPFLAGS:

```cmake
set(
    list_of_sqlite_args
    SQLITE_DEFAULT_MEMSTATUS
    SQLITE_DEFAULT_WAL_SYNCHRONOUS
    SQLITE_LIKE_DOESNT_MATCH_BLOBS
    SQLITE_ENABLE_UNLOCK_NOTIFY
    SQLITE_ENABLE_RTREE
)

set(sqlite_cppflags "")
foreach(x ${list_of_sqlite_args})
  string(COMPARE EQUAL "${${x}}" "0" is_zero)
  string(COMPARE EQUAL "${${x}}" "1" is_one)

  if(is_zero)
    set(sqlite_cppflags "${sqlite_cppflags} -D${x}=0")
  elseif(is_one)
    set(sqlite_cppflags "${sqlite_cppflags} -D${x}=1")
  else()
    hunter_fatal_error("...")
  endif()
endforeach()

hunter_autotools_project(
   # ...
   CPPFLAGS "${sqlite_cppflags}"
)
```

Plus add `SQLITE_ENABLE_UNLOCK_NOTIFY=1` and `SQLITE_ENABLE_RTREE=1` as a default args.

**Comment by tdavis** [comment]
A clever approach. Would you like me to enumerate the major compile options and supply a patch? My only concern (more like question) with the specific implementation is that some flags are presented as `FOO_FEATURE` rather than `FOO_FEATURE=1` or `FOO_FEATURE=0`. Do you think `FOO_FEATURE=0` would be equivalent to simply not having the flag present or should the loop consider presence only?

**Comment by ruslo** [comment]
> Would you like me to enumerate the major compile options and supply a patch?

Yes, it would be nice.

> My only concern (more like question) with the specific implementation is that some flags are presented as FOO_FEATURE rather than FOO_FEATURE=1 or FOO_FEATURE=0

I've never used such feature in Hunter CMAKE_ARGS but `if(DEFINED ...)` should do the trick:
```cmake
if(is_zero)
  set(sqlite_cppflags "${sqlite_cppflags} -D${x}=0")
elseif(is_one)
  set(sqlite_cppflags "${sqlite_cppflags} -D${x}=1")
elseif(DEFINED "${x}")
  set(sqlite_cppflags "${sqlite_cppflags} -D${x}")
endif()
```

Assuming that we are expecting only `0`, `1` or nothing there should be extra check that defined-only argument is an empty string in fact.

**Comment by tdavis** [comment]
Great. I will submit a PR when it's done.

**Comment by pretyman** [comment]
Sorry for arriving late on this issue. I'm caught up until next week, but let me leave my 2 cents.

I actually was planning to kill the SQLite3 build scheme ( + odb custom schemes ) in favor of the default autotools scheme, and passing all the options to `hunter_autotools_project` through the `hunter.cmake` with CMAKE_ARGS and which could then be overriden on hunter's `config.cmake` file (as mentioned by @ruslo above). Like that one could have his config file with specific build option and there would be one less files to maintain.

Also there will be a new option for creating CMake targets from pkg-config module and this would go into the default autotools scheme as well.

I can't push anything until next week so do as you guys see fit :-)

**Comment by tdavis** [comment]
Sounds like your approach is the preferred one anyway. I'm fine with using
my fork until it's available.

**Comment by tdavis** [comment]
Just seeing if this is still on your radar, @pretyman

**Comment by ruslo** [comment]
Closing inactive discussion.
