### ISSUE TITLE
Docs for transitive dependencies

### ISSUE THREAD

**Issue by wheybags** [ruslo/hunter#810]
So, I want to create a package (A) that has a dependency on another package (B). I've setup the cmake scripts for A so that it builds fine, but when I add the package to hunter and add A as a depenendency to an example project, I get errors about missing a target for B.

I gathered there is some sort of mechanism for this case, by looking at the cmake scripts for libtiff, but I'm not sure how it works. Is there docs for that anywhere?

(BTW, the real package in question is libtomcrypt, I want to add libtommath as a dependency to enable some optional functionality that depends on it, and once that's done, then finally finish my real goal, which is a package for https://github.com/ladislav-zezula/StormLib)

**Comment by ruslo** [comment]
> I get errors about missing a target for B

I can guess you mean missing `find_dependency` call in `*Config.cmake`:
* https://github.com/hunter-packages/opencv/blob/6a267eaf804573d39e05950ab234f98974dc0d25/cmake/templates/OpenCVConfig.cmake.in#L267-L283
* https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html

**Comment by ruslo** [comment]
Hope examples help, closing.
