### ISSUE TITLE
How to use a specific version of a package?

### ISSUE THREAD

**Issue by lepinkainen** [ruslo/hunter#811]
I'm using ZeroMQ in my CMake project with hunter, but it always grabs the latest version.

For Windows-specific reasons I need ZeroMQ 4.0.4, how do I tell Hunter to grab that exact version instead of the latest?

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-package-version

**Comment by ruslo** [comment]
Hope the link with examples helps, closing.
