### ISSUE TITLE
Passing config options to openssl

### ISSUE THREAD

**Issue by rabarar** [ruslo/hunter#813]
How do I configure hunter to pass a config option like no-afalgeng to the build process?

**Comment by ruslo** [comment]
From Gitter chat:
* Update OpenSSL scheme https://github.com/ruslo/hunter/blob/a4e16e4386b03ef0d5ba15487a786b0c6b1a721e/cmake/projects/OpenSSL/schemes/url_sha1_openssl.cmake.in
* change PACKAGE_INTERNAL_DEPS_ID for OpenSSL: https://docs.hunter.sh/en/latest/reference/user-modules/hunter_download.html
* test it with jenkins.py: https://github.com/ruslo/hunter/wiki/dev.hunter.root
* If it works then open pull request

Question for me now is about the cases when current OpenSSL scheme doesn't work. What do we missing and how can we detect this case using CMake. I.e. we need:
```cmake
if(<something-bad>)
  list(APPEND configure_command no-afalgeng)
endif()
```

**Comment by ruslo** [comment]
Closing inactive discussion.
