### ISSUE TITLE
add 'eigen3-nnls' to hunter-packages

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#817]
https://github.com/hmatuschek/eigen3-nnls

This is required for an `eos` update.  
I have a hunter patch.
Thanks.

UPDATE: https://github.com/headupinclouds/eigen3-nnls/tree/hunter

**Comment by ruslo** [comment]
https://github.com/hunter-packages/eigen3-nnls

**Comment by headupinclouds** [comment]
#823
