### ISSUE TITLE
upgrade 'glm' to 0.9.8

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#818]
Needed for resolution in `eos` update w/ `ceres` example: https://github.com/g-truc/glm/issues/541#issuecomment-246059559

If you add me as a collaborator I can make the update, release and hunter PR.

**Comment by ruslo** [comment]
> If you add me as a collaborator

Done

**Comment by headupinclouds** [comment]
See: #824

**Comment by headupinclouds** [comment]
Thanks.
