### ISSUE TITLE
modifying a local ${CMAKE_SRC_DIR}/cmake/Hunter/config.cmake forces a rebuild of all hunter dependencies

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#82]
I've migrated all my hunter_config commands from my top level CMakeLists.txt file, as required by the latest HunterGate call.  Now it seems every time I make a small change to that file, it ends up recompiling all of the dependencies.  This project is using both boost and opencv, so that makes for incredibly long build times (I haven't timed it, but this is probably close to 1 hour).  I'm guessing there is a sha1 computed on the entire config.cmake file and to do a lazy per module rebuild for changes in each hunter_config line would require a fair amount of additional parsing.  I'd welcome any fixes or short term workarounds.

**Comment by ruslo** [comment]
> it ends up recompiling all of the dependencies

this is because `Config-ID` changed so we must build new directory "Hunter-ID/**Config-ID**/Toolchain-ID"

>  I'd welcome any fixes or short term workarounds

It's hard to invent some workaround here, this must be fixed carefully. That's exactly what this bug about: https://github.com/ruslo/hunter/issues/74
