### ISSUE TITLE
OS X: find_package() call for hunter packages prefers /System/Library/Frameworks over hunter builds

### ISSUE THREAD

**Issue by headupinclouds** [ruslo/hunter#83]
I was testing a FindGPUImage.cmake file for a hunter GPUImage dependency:
# cmake/Hunter/config.cmake
```
hunter_config(GPUImage VERSION 0.1.6-hunter-1)
```
# CMakeLists.txt
```
hunter_add_package(GPUImage)
find_package(GPUImage)
message("GPUIMAGE: ${GPUIMAGE_INCLUDE_DIR} ${GPUIMAGE_LIBRARY} ${GPUIMAGE_FOUND}")
```
When I run this:
```
build.py --toolchain libcxx --verbose --clear
```
it prints:
```
GPUIMAGE: /System/Library/Frameworks/GPUImage.framework /System/Library/Frameworks/gpuimage.framework TRUE
```
and if I remove the /System/Library/Frameworks/GPUImage.framework
```
sudo mv /System/Library/Frameworks/GPUImage.framework /tmp;
build.py --toolchain libcxx --verbose --clear
```
it finds the hunter library:
```
GPUIMAGE: /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/7bc3715/b2b5fbe/Install/include /Users/dhirvonen/devel/hunter/_Base/xxxxxxx/7bc3715/b2b5fbe/Install/lib/libgpuimage.a TRUE
```

It would seem we always want the hunter builds to be given preference, but I'm not familiar enough with all of this to know if this is something that should be handled in FindGPUImage.cmake or within the hunter framework itself.  (The FindGPUImage.cmake is using the stock cmake find_library call.)  Posting this as an issue in case it is actually something hunter needs to adapt to.  I believe this is related to some problems I hit earlier where a GStreamer framework was being used to satisfy some hunter dependencies.

This is using a simple FindGPUImage.cmake file:

```
# Find GPUImage
#
#  GPUIMAGE_INCLUDE_DIR - where to find GPUImage/logging.h, etc.
#  GPUIMAGE_LIBRARY     - List of libraries when using libglog.
#  GPUIMAGE_FOUND       - True if libglog found.
#
# Lineage: 4/21/2015
#   Modified from https://github.com/facebook/hhvm/blob/master/CMake/FindGlog.cmake

IF (GPUIMAGE_INCLUDE_DIR)
  # Already in cache, be silent
  SET(GPUIMAGE_FIND_QUIETLY TRUE)
ENDIF ()

FIND_PATH(GPUIMAGE_INCLUDE_DIR GPUImage/GPUImage.h)

FIND_LIBRARY(GPUIMAGE_LIBRARY gpuimage)

# handle the QUIETLY and REQUIRED arguments and set Libmemcached_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GPUIMAGE DEFAULT_MSG GPUIMAGE_LIBRARY GPUIMAGE_INCLUDE_DIR)

MARK_AS_ADVANCED(GPUIMAGE_LIBRARY GPUIMAGE_INCLUDE_DIR)
```

**Comment by ruslo** [comment]
Hunter version of GPUImage is config-mode package. I've added wiki example: https://github.com/ruslo/hunter/wiki/pkg.gpuimage

> and if I remove the /System/Library/Frameworks/GPUImage.framework ... it finds the hunter library

Yep, this is because `Find<...>.cmake` has higher priority then `<...>Config.cmake`

**Comment by headupinclouds** [comment]
I see.  I was missing the CONFIG in: find_package(GPUImage CONFIG)
