### ISSUE TITLE
error at cmake/HunterGate.cmake:82

### ISSUE THREAD

**Issue by chronakazi** [ruslo/hunter#832]
Ive been trying to cmake this repo ethereum-mining/ethminer and cant get by this error. Any ideas whats wrong? Thanks.

CMake Error at CMakeLists.txt:2 (project):

  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    

[hunter ** INTERNAL **] Configure project failed
[hunter ** INTERNAL **] [Directory:E:/ETH/ethminer-master/ethminer-master]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at cmake/HunterGate.cmake:82 (message):
Call Stack (most recent call first):
  cmake/HunterGate.cmake:92 (hunter_gate_wiki)
  cmake/HunterGate.cmake:329 (hunter_gate_internal_error)
  cmake/HunterGate.cmake:498 (hunter_gate_download)
  CMakeLists.txt:10 (HunterGate)

Configuring incomplete, errors occurred!

**Comment by ruslo** [comment]
Have you tried to run simple CMakeLists.txt?

**Comment by chronakazi** [comment]
Will try a simple CMakeLists.txt tonight. thanks for the help! Any idea what might be throwing this error? something simple i can maybe correct in the repo?

**Comment by ruslo** [comment]
> Any idea what might be throwing this error?

I think something wrong with Visual Studio setup or Visual Studio is not installed at all.

**Comment by chronakazi** [comment]
good call ill reinstall visual studio and give it another shot. I truly appreciate the help!

**Comment by ruslo** [comment]
> ill reinstall visual studio

I don't think it's necessary if it's installed. First you should try to build simple project without Hunter.

**Comment by chronakazi** [comment]
I just reinstalled the microsoft "build tools" package and that solved the issue. Everythings hashing nicely now. Truly appreciate all the work.

**Comment by ruslo** [comment]
> I just reinstalled the microsoft "build tools" package and that solved the issue

Great, I guess issue can be closed.

**Comment by stray128** [comment]
**error at cmake/HunterGate.cmake:83**
Cannot configure the project in the directory Build
`cmake ..`
gives the following error:
`-- [cable ] Cable 0.2.3 initialized                                                
-- [hunter] Initializing Hunter workspace (aa1faccd24f33dd2c368f85a4e9ca2e5d9c249cb)                                    -- [hunter]   https://github.com/ruslo/hunter/archive/v0.21.16.tar.gz                                                   
-- [hunter]   -> C:/.hunter/_Base/Download/Hunter/0.21.16/aa1facc                                                       
The system cannot find the file specified                                                                               
CMake Error: Generator: execution of make failed. Make command was: "nmake" "/nologo"                                                                                                                                                           [hunter ** INTERNAL **] Build project failed                                                                            
[hunter ** INTERNAL **] [Directory:C:/Users/Ashwith Basani/cpp-ethereum]                                                                                                                                                                        ------------------------------ WIKI -------------------------------                                                         https://github.com/ruslo/hunter/wiki/error.internal                                                                 
-------------------------------------------------------------------                                                                                                                                                                             CMake Error at cmake/HunterGate.cmake:83 (message):                                                                     
Call Stack (most recent call first):                                                                                      cmake/HunterGate.cmake:93 (hunter_gate_wiki)                                                                            cmake/HunterGate.cmake:349 (hunter_gate_internal_error)                                                                 cmake/HunterGate.cmake:513 (hunter_gate_download)                                                                       CMakeLists.txt:43 (HunterGate)      `
