### ISSUE TITLE
package jsoncpp failed

### ISSUE THREAD

**Issue by zhou304** [ruslo/hunter#835]
[hunter ** INTERNAL **] Packing failed
[hunter ** INTERNAL **] [Directory:C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/projects/jsoncpp]

CMake Error at C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_pack_directory.cmake:59 (hunter_internal_error)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_save_to_cache.cmake:94 (hunter_pack_directory)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_download.cmake:562 (hunter_save_to_cache)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/projects/jsoncpp/hunter.cmake:59 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_add_package.cmake:87 (include)
  CMakeLists.txt:89 (hunter_add_package)

**Comment by ruslo** [comment]
I've added extra debug info, please try https://github.com/ruslo/hunter/releases/tag/v0.19.13

**Comment by zhou304** [comment]
Thanks a lot. When I try it again, it's ok to pack jsoncpp. And report “Packing failed” at next package. When I try it again, the next package is ok too. Finally, hunter+cmake finished correctly. If I met other errors, I will send it to you.

**Comment by ruslo** [comment]
> report “Packing failed” at next package

Try new version, it will print more info about error.

**Comment by ruslo** [comment]
Closing inactive discussion.
