### ISSUE TITLE
Feature to skip cache for testing purposes

### ISSUE THREAD

**Issue by pretyman** [ruslo/hunter#837]
Hi Ruslan,

What do you think about having a variable like `HUNTER_SKIP_CACHE` that could hold a list of packages that would have the cache feature disabled for them for testing purposes?

I made some changes to autotools that shouldn't change the package contents, I could bump the `PACKAGE_INTERNAL_ID` for the packages, but wouldn't that waste disk space on the cache server?

Thanks

**Comment by ruslo** [comment]
> wouldn't that waste disk space on the cache server?

This should be solved by "reproducible builds" feature:
* https://github.com/ruslo/hunter/issues/660

> What do you think about having a variable like HUNTER_SKIP_CACHE that could hold a list of packages that would have the cache feature disabled for them for testing purposes?

This may be tricky. For now "internal-id + sha1 + other stuff" traits is static and don't change on the fly. I'm afraid that it will affect cache working mechanism. Is the disk space the only concern?

**Comment by pretyman** [comment]
>  Is the disk space the only concern?

Mainly, yes.

But, somewhat related: when developing for hunter, I would find useful to have some kind of `HUNTER_FORCE_BUILD=package` to force a build of a package, even if it has been built already (when I was refactoring autotools, I wanted to make sure I had the exact order for the `./configure` parameters I had before, and I had changed the files a lot, so I kept rebuilding the packages to check the parameters and changed the CMake code until they matched).

Right now I `cd _Base && rm -rf Cache xxxxxx` then `cd examples/package && polly_build` if I could do just `polly_build -DHUNTER_FORCE_BUILD=package` that would be pretty cool because it wouldn't need to build the package dependencies.

**Comment by ruslo** [comment]
You can use `jenkins.py`:
* https://github.com/ruslo/hunter/wiki/dev.hunter.root#jenkinspy

```
> TOOLCHAIN=<toolchain> PROJECT_DIR=examples/<package> ./jenkins.py --verbose --clear-except
```

**Comment by pretyman** [comment]
As I understand ` --clear-except` would do basically what my little commands do.

However a `-DHUNTER_FORCE_BUILD=package` would just try to build the package as it was not built yet, not clearing anything. For example: after we finish the saga of `x264`, I hope to also add `FFmpeg`. 

`x264` can have `FFmpeg` as a dependency, so I would change the `x264` scheme. However during the development of the scheme, it would be really time cosuming to keep building `FFmpeg` before `x264` to test the updated `x264` scheme.

Nothing critical I guess, I feel that it would just speed up adding (+ integrating) packages with dependencies.

**Comment by ruslo** [comment]
I think making package uncacheable while testing will solve all the issues.

**Comment by pretyman** [comment]
I keep it not cached usually. But to solve my problem I can save the `<root-id>` before the dependencies, build, and when I need to rebuild, I can erase the new `<root-it>`, and copy back the old one without the package I'm working on, but with its dependencies.

It is all good

**Comment by ruslo** [comment]
> But to solve my problem I can save the <root-id> before the dependencies, build, and when I need to rebuild, I can erase the new <root-it>, and copy back the old one without the package I'm working on, but with its dependencies

I think it don't have to be so complex. You can remove `hunter_cacheable` from package you want to work on. Run test, it will create `root-id-1` and build/cache all dependencies. Update build scheme and run `jenkins.py` again. Since build scheme changed => archive SHA1 changed => hunter-id changed => you will have some `root-id-2`. In this case all dependencies will be taken from cache but not the package you're testing (because it's not cacheable) => build for the package will start again, build scheme with your changes will be used.

**Comment by ruslo** [comment]
Closing inactive discussion.
