### ISSUE TITLE
OPENCV_WITH_EXTRA_MODULES: how to use only selected modules?

### ISSUE THREAD

**Issue by ikliashchou** [ruslo/hunter#840]
I followed [this](https://github.com/ruslo/hunter/issues/167) and tried to build OpenCV under iOS

This package is big, but I need only one module from it (xfeatures2d). Is it possible to configure to build and use only selected modules via Hunter/CMake flags/options?

The issue is that OpenCV cannot be build with extra modules by default, at least on my end. There are cmake errors during configure stage even.

Also I see that OpenCV-Extra module is using version 3.0.0 at the moment from already deprecated repository, while [here](https://github.com/opencv/opencv_contrib/archive/3.2.0.tar.gz) 3.2.0 is available already. Should I make pull request with an update? 

Thanks!

**Comment by ruslo** [comment]
> Is it possible to configure to build and use only selected modules via Hunter/CMake flags/options?

It depends on the package itself, if there is some options then use them.

> Should I make pull request with an update?

Sure. Though there is no testing of OpenCV example with extra modules, it make sense to add one before.

**Comment by gomons** [comment]
What kind of testing do you mean? examples/OpenCV or something else?

**Comment by ruslo** [comment]
> What kind of testing do you mean? examples/OpenCV or something else?

Yes, there is only `examples/OpenCV` testing in pkg.opencv:
* https://github.com/ingenue/hunter/branches/all?utf8=%E2%9C%93&query=pkg.opencv

We need `examples/OpenCV-extra` and new `.travis.yml`/`appveyor.yml` in pkg.opencv-extra branch.

**Comment by ikliashchou** [comment]
ok, I have some examples and .yml files based on pkg.opencv template, what should I do next?

**Comment by ruslo** [comment]
`examples/OpenCV-extra` to the `ruslo/hunter`, `.travis.yml`/`appveyor.yml` to the `ingenue/hunter@pkg.opencv`.

**Comment by ruslo** [comment]
Closing inactive discussion.
