### ISSUE TITLE
Add gflags dependency to the glog package

### ISSUE THREAD

**Issue by v1bri** [ruslo/hunter#842]
The glog package explicitly disables the gflags dependency (https://github.com/ruslo/hunter/blob/master/cmake/projects/glog/hunter.cmake#L34-L35) which means the resulting application cannot take advantage of glog's command line flags (`--alsologtostderr`, `--v=1`, etc). These are quite useful in development and testing so I'd like to get the dependency restored if possible. 

Happy to submit a pull request if that will help.

**Comment by ruslo** [comment]
Glog should be "hunterized":
* https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html#maintenance

It means you need to add [hunter_add_package(gflags)](https://github.com/ruslo/hunter/wiki/pkg.gflags) into the code. Please send pull request to https://github.com/hunter-packages/glog.

**Comment by v1bri** [comment]
Can do. What's the procedure for pointing HunterGate at a development repo/branch for testing? Example: pull gflags from https://github.com/v1bri/gflags.

**Comment by ruslo** [comment]
> What's the procedure for pointing HunterGate at a development repo/branch for testing?

Not sure what you mean by this.

**Comment by caseymcc** [comment]
Setup Travis and Appveyor to test off your git hunter fork. Then check out the latest pkg.<name> from https://github.com/ingenue/hunter update it with the hunter upstream from  https://github.com/ruslo/hunter. Then modify the the pkg location in the /hunter/cmake/<name>/hunter.cmake (and update the sha) to the repo you want to test from. Then check that all in under your hunter fork under the pkg.<name> branch then travis and appveyor should go to work.

**Comment by caseymcc** [comment]
Oh and if you were just wanting to test locally on your machine all you need is your hunter fork checked out and then just modify /hunter/cmake/projects/{name}/hunter.cmake (and sha) to point at your repo. So for this case if you are testing glog with a modified gflag then modify

/hunter/cmake/projects/gflags/hunter.cmake

    ...
    hunter_add_version(
        PACKAGE_NAME
        gflags
        VERSION
        2.1.2-p0
        URL
        "https://github.com/hunter-packages/gflags/archive/v2.1.2-p0.tar.gz"
        SHA1
        113255cba87b6af61663014f446e2d69d0d2bc3a
    )
    ...

to

    ...
    hunter_add_version(
        PACKAGE_NAME
        gflags
        VERSION
        2.1.2-p0
        URL
        "https://github.com/v1bri/gflags"
        SHA1
        new sha
    )
    ...

then goto /hunter/examples/glog and run

cmake -H. -B_build
cmake --build _build

and that should test it likely any errors will occur at first cmake call.

**Comment by ruslo** [comment]
It's better to use `jenkins.py` script:
* https://github.com/ruslo/hunter/wiki/dev.hunter.root#jenkinspy

**Comment by ruslo** [comment]
Closing inactive discussion.
