### ISSUE TITLE
Problems with Flatbuffers

### ISSUE THREAD

**Issue by ssbanerje** [ruslo/hunter#847]
I am trying to get access to a function defined in `FindFlatbuffers.cmake` [(here)](https://github.com/hunter-packages/flatbuffers/blob/hunter/CMake/FindFlatBuffers.cmake#L37-L52).

However when I add a the library using hunter --

```cmake
# ...
hunter_add_package(flatbuffers)
find_package(flatbuffers CONFIG REQUIRED)
FLATBUFFERS_GENERATE_C_HEADERS(test test.fbs)
# ....
```

This function is not defined. 

```
-- [hunter] FLATBUFFERS_ROOT: /Users/subho/.hunter/_Base/7e8c747/0906605/a5fd140/Install (ver.: 1.3.0-p3)
CMake Error at CMakeLists.txt:22 (FLATBUFFERS_GENERATE_C_HEADERS):
  Unknown CMake command "FLATBUFFERS_GENERATE_C_HEADERS".
```

Am I supposed do something additionally to make sure that `flatc` gets compiled and that this function is exported?

**Comment by ruslo** [comment]
> I am trying to get access to a function defined in FindFlatbuffers.cmake

You should not use this module, because automatically generated `flatbuffersConfig.cmake` is better.
See also:
* http://cgold.readthedocs.io/en/latest/rejected/find-modules.html

**Comment by ssbanerje** [comment]
I am not sure how this is meant to be used, but the `flatbuffers` build does not:
- Generate the `flatc` executable target
- Put the requisite macros in the file: `$HOME/.hunter/_Base/7e8c747/0906605/a5fd140/Install/lib/cmake/flatbuffers/flatbuffersConfig.cmake`

The example shown [here](https://github.com/ruslo/hunter/blob/master/examples/flatbuffers/CMakeLists.txt) does not actually compile a flatbuffer schema to a C++ header file.

The `protobuf` example however shows how the compiler target is created and then used [(here)](https://github.com/ruslo/hunter/blob/master/examples/Protobuf/messages/CMakeLists.txt#L6-L20). Flatbuffers should also have a similar workflow.

**Comment by ruslo** [comment]
It should be fixed in flatbuffers, fork is here:
* https://github.com/hunter-packages/flatbuffers

**Comment by ssbanerje** [comment]
Looks like the hunter-packages/flatbuffers creates the `flatc` executable by default. Looks like the flags are coming from hunter [(here)](https://github.com/ruslo/hunter/blob/master/cmake/projects/flatbuffers/hunter.cmake#L26-L29).

**Comment by ruslo** [comment]
I guess because of Android/iOS.

**Comment by ssbanerje** [comment]
How do I override those values?

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-cmake-options

**Comment by ssbanerje** [comment]
I have a working version [here](https://github.com/ssbanerje/flatbuffers). However looks like there has been a lot of change since the last merge between `hunter-packages/flatbuffers` and `google/flatbuffers`. Maybe the thing to do would be to bump the version up to the latest `google/flatbuffers` release and then merging.

**Comment by ruslo** [comment]
I've started branch `hunter-1.7.1` from tag `v1.7.1`. Feel free to send any pull requests there (I guess we need stuff from branch `hunter`). Note that if pull request is not about "hunterization" then it should be send upstream. We can still use `hunter-packages/flatbuffers` as a temporary place though.

See: https://docs.hunter.sh/en/latest/creating-new/cmake-dependencies.html#maintenance

**Comment by ruslo** [comment]
Closing inactive discussion.
