### ISSUE TITLE
Build locally with Hunter fork

### ISSUE THREAD

**Issue by lukegravitt** [ruslo/hunter#848]
I'm attempting to build using only local packages. I've cloned hunter and modified the `hunter.cmake` for all the projects I'm using. I want to use a relative directory in the URL strings. I attempted to use both CMAKE_SOURCE_DIR, HUNTER_ROOT, and my own variable.

However, they all break down when adding recursive dependencies. For example, myRepo depends on package1 (works fine) but when package1 depends on package2, these variables are no longer set correctly. Is there any variable I could use that is set consistently?

I see two options, if the above doesn't work.

1. Call `hunter_add_package()` on the lowest dependencies first.
2. Use an environment variable.

Thoughts on getting around this issue?

**Comment by ruslo** [comment]
> I attempted to use both CMAKE_SOURCE_DIR, HUNTER_ROOT, and my own variable.

It is not designed to be used this way. Full path in URL or using environment variable will do the trick. Just for your info feature request:
* https://github.com/ruslo/hunter/issues/521

**Comment by ruslo** [comment]
Closing inactive discussion.
