### ISSUE TITLE
Add ICU

### ISSUE THREAD

**Issue by aadityakalsi** [ruslo/hunter#85]
Out of a bunch of libraries providing internationalization support, this is probably the most widely used and referenced. It would be nice to have ICU available via Hunter.

http://site.icu-project.org/download
##

**Comment by ruslo** [comment]
Thanks for request. Also I've made some hacking earlier but haven't finished it: https://github.com/hunter-packages/icu

**Comment by sffc** [comment]
FYI, there is an ICU ticket for adding CMake support:

http://bugs.icu-project.org/trac/ticket/7747

I would also like to see ICU in Hunter.

**Comment by annulen** [comment]
As you can see, that ticket was created 7 years ago, so it seems to be extermely unlikely that ICU project will change their build system. I think it would be much more productive to support building of ICU via autotools (runConfigureICU), and support MSVC with its `MSYS/MSVC` platform option (like done e.g. in [1]), or by using devenv & msbuild (like done in [2])

[1] https://github.com/bincrafters/conan-icu/blob/testing/59.1/conanfile.py#L109
[2] https://github.com/Vitallium/conan-icu/blob/master/conanfile.py#L36

**Comment by ruslo** [comment]
Version 55.1 added to Hunter, available since v0.20.40:
* https://github.com/ruslo/hunter/releases/tag/v0.20.40

**Comment by sffc** [comment]
Thanks for adding ICU to Hunter. :)

Why such an old version?  ICU 55.1 is 3 years old.  ICU 61.1 is the latest version.

**Comment by ruslo** [comment]
> Why such an old version? ICU 55.1 is 3 years old

This version was needed by the project that use ICU.

>  ICU 61.1 is the latest version

If you want I can create hunter-61.1 branch and you can send pull request with CMake ported from 55.1. In this case please start discussion here:
* https://github.com/hunter-packages/icu

**Comment by NikitaFeodonit** [comment]
Please see:
[ICU build files for CMake build tools](https://github.com/LibCMaker/LibCMaker_ICU/tree/master/cmake/modules/icu-61.1/icu)

In the ICU build files for CMake build tools are released most configure
options, compile and linker flags and others from the original ICU files:

```
 'configure.ac', '*/*.m4', '*/Makefile.in', 'icudefs.mk.in', 'config/mh-*',
 'data/pkgdataMakefile.in', 'data/makedata.mak', 'allinone/allinone.sln',
 'allinone/Build.Windows*.ProjectConfiguration.props', '*/*.vcxproj'
```

Unrealized options are marked with 'TODO' in CMake files.
Extras, samples and test building is not released.
Layoutex building is partially implemented, need to study the work with
the library icu-le-hb without pkg-config, only with CMake.

ICU data building from scratch ('files' mode) is not released.
Now ICU_DATA_PACKAGING can be 'archive', 'library', 'static' and 'auto'.
For iOS, Android and Microsoft Store (Windows Store) platforms is always 'auto'.

Building and sample running are tested on Ubuntu 18.04 with GCC 7.3.0 and
Clang 6.0.0. Only building is tested with Android NDK 17.1.4828580.
In these configurations static and shared buildings are tested.

For building with CMake copy the files to ICU source tree and just run:

```
cd ./icu
mkdir ./build
cd ./build
cmake ../ \
 -DICU_ENABLE_EXTRAS=OFF \
 -DICU_ENABLE_SAMPLES=OFF \
 -DICU_ENABLE_TESTS=OFF \
 -DBUILD_SHARED_LIBS=ON \
 -DCMAKE_BUILD_TYPE=Release \
 -DCMAKE_INSTALL_PREFIX=inst
cmake --build .
```

For more info see file ['README_CMakeLists.txt'](https://github.com/LibCMaker/LibCMaker_ICU/blob/master/cmake/modules/icu-61.1/icu/README_CMakeLists.txt)

The main idea belongs to Ruslan Baratov with Hunter package manager. Thanks.

See file ['LICENSE_CMakeLists'](https://github.com/LibCMaker/LibCMaker_ICU/blob/master/cmake/modules/icu-61.1/icu/LICENSE_CMakeLists) for license information.

**Comment by sffc** [comment]
Thank you!  This looks like a great starting point.

I am working on a standalone data build script in Python for ICU.  Right now the data build configurations are part of the Makefile, and that means they are not as portable and not as easy to configure, so moving them to a script gives us more flexibility.  It also should mean that it is easier to invoke the data build from other build systems like CMake.

**Comment by NikitaFeodonit** [comment]
There is also some discussion here:
https://unicode-org.atlassian.net/browse/ICU-7747
