### ISSUE TITLE
GTest 1.8.0-hunter-p5 fails to build with BUILD_GMOCK=OFF (OSX)

### ISSUE THREAD

**Issue by lukegravitt** [ruslo/hunter#850]
Failure states that there is no install target:

[ 43%] Performing install step for 'GTest-Release'
cd [snip]/GTest/Build/GTest-Release-prefix/src/GTest-Release-build && /usr/local/Cellar/cmake/3.8.1/bin/cmake --build . --target install --config Release
make[3]: *** No rule to make target `install'.  Stop.
make[2]: *** [GTest-Release-prefix/src/GTest-Release-stamp/GTest-Release-install] Error 2
make[1]: *** [CMakeFiles/GTest-Release.dir/all] Error 2
make: *** [all] Error 2

[hunter ** FATAL ERROR **] Build step failed (dir: [snip]/GTest
[hunter ** FATAL ERROR **] [Directory:[snip]/cmake/projects/GTest]

**Comment by ruslo** [comment]
It's not a Hunter issue. Package itself should be fixed.

**Comment by Knitschi** [comment]
I can reproduce the error. This could be a problem of our version of googletest. Our fork adds an install target and maybe I need to check the BUILD_GTEST and BUILD_GMOCK variables when adding the install target. I will take a look into this. I think I will also invest some time within the next view weeks to lobby for adding the install target and cmake config file code upstream.

**Comment by Knitschi** [comment]
I moved this to the package hunter-packages/googletest#16. You can close this here.

**Comment by ruslo** [comment]
> You can close this here.

ok
