### ISSUE TITLE
Boost source download for every component and duplicate build of components

### ISSUE THREAD

**Issue by vdsrd** [ruslo/hunter#851]
# Multiple boost source download

The boost package is downloading and extracting the source for every component, although the source can be shared for the build of all components.

This leads to significant build time increase, especially on Windows which is very slow with handling a lot of small files of the boost source. But even on Linux there is a considerable amount of time wasted.

**Figures for Windows:**
00:36:54.814   Creating directories for 'Boost-chrono'
00:36:54.970   Performing download step (download, verify and extract) for 'Boost-chrono'
00:44:55.100   -- Boost-chrono download command succeeded.

In a summary, 8 minutes are lost per component. Assuming you build 10 components, you loose 80 minutes.

**Figures for Linux:**
00:06:54.265 [ 12%] Creating directories for 'Boost-chrono'
00:06:54.277 [ 25%] Performing download step (download, verify and extract) for 'Boost-chrono'
00:06:54.280 -- verifying file...
00:06:54.280        file='boost_1_61_0.tar.bz2'
00:06:54.769 -- File already exists and hash match (skip download):
00:06:54.769   file='boost_1_61_0.tar.bz2'
00:06:54.769   SHA1='f84b1a1ce764108ec3c2b7bd7704cf8dfd3c9d01'
00:06:54.777 -- extracting...
00:06:54.777      src='boost_1_61_0.tar.bz2'
00:06:54.777      dst='/hunter/_Base/63718d6/c4b89cb/db0d7e2/Build/Boost/__chrono/Source'
00:06:54.777 -- extracting... [tar xfz]
00:07:18.127 -- extracting... [analysis]
00:07:18.127 -- extracting... [rename]
00:07:18.127 -- extracting... [clean up]
00:07:18.127 -- extracting... done

In a summary, 24 seconds are lost per component. Assuming you build 10 components, you loose 4 minutes.

# Multiple boost component build

There is another side effect using this technique. For example when you use boost::system and boost::chrono components, the following happens:
- The system component builds in /Build/Boost/__system/Source/stage/lib the libraries for system.
- The chrono component builds in /Build/Boost/__chrono/Source/stage/lib the libraries for chrono **and system**, as chrono has an internal dependency to system! This means that components are built multiple times and files are overwritten randomly in the install directory.

# Summary

Is there any reason why every component downloads the source again instead of using a shared source directory?

Fixing that has several advantages:
- Download of source is done only once (performance improvement and good practice anyway!)
- Every component is built only once (performance improvement and building it multiple times and randomly overwriting in the install directory is a bug!)

**Comment by ruslo** [comment]
> The boost package is downloading and extracting the source for every component

As far as I know archive downloaded only once, check logs with `HUNTER_STATUS_DEBUG=ON`.

> The chrono component builds in /Build/Boost/__chrono/Source/stage/lib the libraries for chrono and system

I think it's really Boost issue. Since it's just a libraries we don't have to build dependencies.

> although the source can be shared for the build of all components

Usually it's "unpack -> build -> install -> remove source directory" to keep HDD usage low. There must be command to say "it's a last component, now sources can be removed", there is no such command as you understand. You can use [HUNTER_KEEP_PACKAGE_SOURCES](https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-keep-package-sources), this could do the trick.

As a general note if you want the build to work fast you can use binary cache server feature. Will work for Boost too.

**Comment by vdsrd** [comment]
>> The boost package is downloading and extracting the source for every component

> As far as I know archive downloaded only once, check logs with HUNTER_STATUS_DEBUG=ON.

True, at least the download seams to be cached. On Windows this is not displayed, but Linux does:
_00:06:54.769 -- File already exists and hash match (skip download):_

Still the extract of the sources is done for every component.

>> The chrono component builds in /Build/Boost/__chrono/Source/stage/lib the libraries for chrono and system

> I think it's really Boost issue. Since it's just a libraries we don't have to build dependencies.

This is no boost issue, because if chrono uses system, chrono needs to link system when building shared libraries. On Windows you can see with depends.exe that "boost_chrono-mt.dll" is linking "boost_system-mt.dll", therefore you need to build that library first. When you do a boost build without Hunter, you typically build all components within the same source tree and then this problem is solved.

>> although the source can be shared for the build of all components

> Usually it's "unpack -> build -> install -> remove source directory" to keep HDD usage low. There must be command to say "it's a last component, now sources can be removed", there is no such command as you understand. You can use HUNTER_KEEP_PACKAGE_SOURCES, this could do the trick.

HUNTER_KEEP_PACKAGE_SOURCES could do the trick, but only if every component would install the source to the same folder. This is currently not the case.

Wouldn't it be interesting as a general concept that Hunter packages which are build from components have a parent which is owning the source (download, extract, install headers) and the components are only building within the source tree. And only if all components are done, the cleanup is done (optionally depending on HUNTER_KEEP_PACKAGE_SOURCES)? This could make component based packages much better and more efficient imho.

> As a general note if you want the build to work fast you can use binary cache server feature. Will work for Boost too.

Caching is a solution for sure. In my case this is a build job which creates the build to be uploaded to the cache server. This job is always doing a full rebuild of the used Hunter packages for testing reasons. This job currently consumes 2 hours alone for boost on Windows, whereas this is not needed. All other packages are pretty fast.

**Comment by ruslo** [comment]
> On Windows this is not displayed, but Linux does

Check your CMake version. There should be no difference.

> This is no boost issue, because if chrono uses system, chrono needs to link system when building shared libraries.

To build library chrono we need only headers of system, we don't need system libraries themself.

> When you do a boost build without Hunter, you typically build all components within the same source tree and then this problem is solved

Image situation when you're building boost without Hunter. You've build boost.system before and copy libraries somewhere, then you removed sources. Now you realized that you need boost.chrono, why should you rebuild boost.system again? So I still think it's a boost issue.

> HUNTER_KEEP_PACKAGE_SOURCES could do the trick, but only if every component would install the source to the same folder. This is currently not the case

Well yes, probably will not work :)

> And only if all components are done, the cleanup is done

That's the problem. How do you know that all components are done?

> This job is always doing a full rebuild of the used Hunter packages for testing reasons

Well if you're rebuilding everything from scratch every time why you're surprised that it takes a long time?

**Comment by ruslo** [comment]
Closing inactive discussion.
