### ISSUE TITLE
ceres-solver: add suitesparse support

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#855]
## dependencies of ceres-solver:

- [x] Eigen3
- [x] glog
- [x] suitesparse
  - [x] lapack + blas

### lapack
I intend to use lapack from http://netlib.org/lapack/#_lapack_version_3_7_1_2

It has a cmake project, but it requires a fortran compiler. On Ubuntu this is provided by the `gfortran` package. On Windows the mingw-w64 suite ships a gfortran compiler

### suitesparse
there is a project on github providing a cmake project for suitesparse
https://github.com/jlblancoc/suitesparse-metis-for-windows

It works also on Ubuntu, but needs some updates:
- find the current lapack version with the cmake config
- the provided cmake-config exports targets spqr, amd etc instead of namespaced variables
- for using this suitesparse package we need to find the package and then include a usesuitesparse file https://github.com/jlblancoc/suitesparse-metis-for-windows/blob/master/example-projects/spqr/CMakeLists.txt#L26
- transient dependencies is flaky, need to investigate some more

## Questions

- is is possible to have suitesparse as optional dependency of ceres-solver? How would we define to use or not use the optional dependency in the project
- is it possible to define a fortran compiler like mingw-gfortran (build dlls) and build the rest with msvc? 

Otherwise a project using suitesparse (and therefore lapack) on windows needs to be compiled with mingw completely

**Comment by ruslo** [comment]
> is is possible to have suitesparse as optional dependency of ceres-solver? How would we define to use or not use the optional dependency in the project

It depends on ceres-solver, if it can be built without suitesparse then it's possible in practice. You just need to add an option:
```cmake
option(CERES_SOLVER_WITH_SUITESPARSE "Build with Suitesparse support" ON)

if(CERES_SOLVER_WITH_SUITESPARSE)
  find_package(Suitesparse ...)
endif()
```

For enabling/disabling `CERES_SOLVER_WITH_SUITESPARSE` in Hunter see:
* https://github.com/ruslo/hunter/wiki/example.custom.config.id#custom-cmake-options

Of course if Suitesparse will not be in Hunter then `CERES_SOLVER_WITH_SUITESPARSE` should be set to `OFF` by default in package or in `hunter.cmake` by `hunter_cmake_args`.

> is it possible to define a fortran compiler like mingw-gfortran (build dlls) and build the rest with msvc?

It's not possible right now, see feature request:
* https://github.com/ruslo/hunter/issues/495

As a workaround you can try to find the right version of fortran in package itself. User will be responsible for setting path to fortran in PATH environment variable.

> Otherwise a project using suitesparse (and therefore lapack) on windows needs to be compiled with mingw completely

It's fine. We don't have to have all working toolchains at once, you or somebody else can add this later.
