### ISSUE TITLE
Configure project failed

### ISSUE THREAD

**Issue by ldellacherie** [ruslo/hunter#857]
CMake Error at cmake/HunterGate.cmake:82 (message):
Call Stack (most recent call first):
  cmake/HunterGate.cmake:92 (hunter_gate_wiki)
  cmake/HunterGate.cmake:329 (hunter_gate_internal_error)
  cmake/HunterGate.cmake:498 (hunter_gate_download)
  CMakeLists.txt:10 (HunterGate)

**Comment by ruslo** [comment]
Are you able to run simple CMake project without Hunter?
Like:
```cmake
cmake_minimum_required(VERSION 3.0)
project(foo)
```

**Comment by ruslo** [comment]
Closing inactive discussion.
