### ISSUE TITLE
Poco NetSSL Linkage 

### ISSUE THREAD

**Issue by swbae31** [ruslo/hunter#859]
I was trying to use Poco to send https requests. I looked through the cmake_args and set the correct flags ON as so:

```shell
hunter_config(PocoCpp VERSION 1.7.6-p0 CMAKE_ARGS ENABLE_NETSSL=ON ENABLE_CRYPTO=ON)
```
(ENABLE_NETSSL=ON only works when ENABLE_CRYPTO=ON)

After the build, I was able to find and add the header files and reference the classes but got linkage errors.

```shell
undefined symbols for architecture x86_64:
  "Poco::Net::HTTPSClientSession::HTTPSClientSession(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned short, Poco::AutoPtr<Poco::Net::Context>)", referenced from:
```
So after some testing I found out that I had to add the NetSSL to the package in the CMakeLists.txt

```shell
find_package(Poco REQUIRED Foundation Net NetSSL CONFIG)
target_link_libraries(Foo Poco::Foundation Poco::Net Poco::NetSSL OpenSSL::SSL OpenSSL::Crypto)
```
(Not sure if the OpenSSL packages are a dependency)

NetSSL (Poco::NetSSL) should be added to available components in the documentation. And it would be better if the Hunter Poco documentation covered all of this a bit better.

**Comment by ruslo** [comment]
> NetSSL (Poco::NetSSL) should be added to available components in the documentation. And it would be better if the Hunter Poco documentation covered all of this a bit better.

Page [pkg.pococpp](https://github.com/ruslo/hunter/wiki/pkg.pococpp) is available for editing, feel free to add any useful information.

**Comment by ruslo** [comment]
Closing inactive discussion.
