### ISSUE TITLE
building boost-system with android toolchain on windows hang out on performing build step

### ISSUE THREAD

**Issue by katmatus** [ruslo/hunter#865]
Boost has built successfully, but after starting performing build step for 'Boost-system' cmake hangs out with 75%. 
[ 75%] Performing build step for 'Boost-system'
notice: found boost-build.jam at C:/HUNTER_ROOT/_Base/a9e1315/a98ecd5/d369bb1/Build/Boost/__system/Source/boost-build.jam

notice: loading Boost.Build from C:/HUNTER_ROOT/_Base/a9e1315/a98ecd5/d369bb1/Build/Boost/__system/Source/tools/build/src

notice: will use 'C:/Users/AppData/Local/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/aarch64-linux-android-g++.exe' '-std=c++11' '-funwind-tables' '-no-canonical-prefixes' '-D__ANDROID_API__=21' '-fexceptions' '-frtti' '--sysroot=C:/Users/AppData/Local/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64' '-isystem' 'C:/Users/AppData/Local/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include' '-isystem' 'C:/Users/AppData/Local/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/arm64-v8a/include' '-isystem' 'C:/Users/AppData/Local/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/backward' '-isystem' 'C:/Users/AppData/Local/Android/sdk/ndk-bundle/sysroot/usr/include' '-isystem' 'C:/Users/AppData/Local/Android/sdk/ndk-bundle/sysroot/usr/include/aarch64-linux-android' '-fPIC' '-DANDROI
D' for gcc, condition <toolset>gcc-ndk

notice: using gcc libraries :: <toolset>gcc-ndk ::

**Comment by ruslo** [comment]
Closing inactive.
