### ISSUE TITLE
cmake ..  bug "pthread.h" no such file or directory

### ISSUE THREAD

**Issue by hahann0099** [ruslo/hunter#868]
Hello, I found an issue while running just "cmake .." which generated the following error.

Determining if the include file pthread.h exists failed with the following output:
Change Dir: D:/Users/q/Downloads/ethminer-master/ethminer-master/ethminer/CMakeFiles/CMakeTmp

Run Build Command:"C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe" "cmTC_fe13f.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=11.0"
Microsoft (R) Build Engine version 4.7.2046.0

[Microsoft .NET Framework, version 4.0.30319.42000]

Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2017-07-06 9:46:49 PM.

Project "D:\Users\q\Downloads\ethminer-master\ethminer-master\ethminer\CMakeFiles\CMakeTmp\cmTC_fe13f.vcxproj" on node 1 (default targets).

PrepareForBuild:

  Creating directory "cmTC_fe13f.dir\Debug\".

  Creating directory "D:\Users\q\Downloads\ethminer-master\ethminer-master\ethminer\CMakeFiles\CMakeTmp\Debug\".

InitializeBuildStatus:

  Creating "cmTC_fe13f.dir\Debug\cmTC_fe13f.unsuccessfulbuild" because "AlwaysCreate" was specified.

ClCompile:

  D:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\CL.exe /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"cmTC_fe13f.dir\Debug\\" /Fd"cmTC_fe13f.dir\Debug\vc110.pdb" /Gd /TC /analyze- /errorReport:queue "D:\Users\q\Downloads\ethminer-master\ethminer-master\ethminer\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  Microsoft (R) C/C++ Optimizing Compiler Version 17.00.61030 for x86

  Copyright (C) Microsoft Corporation.  All rights reserved.

  

  cl /c /Zi /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"cmTC_fe13f.dir\Debug\\" /Fd"cmTC_fe13f.dir\Debug\vc110.pdb" /Gd /TC /analyze- /errorReport:queue "D:\Users\q\Downloads\ethminer-master\ethminer-master\ethminer\CMakeFiles\CMakeTmp\CheckIncludeFile.c"

  

  CheckIncludeFile.c

D:\Users\q\Downloads\ethminer-master\ethminer-master\ethminer\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [D:\Users\q\Downloads\ethminer-master\ethminer-master\ethminer\CMakeFiles\CMakeTmp\cmTC_fe13f.vcxproj]

Done Building Project "D:\Users\q\Downloads\ethminer-master\ethminer-master\ethminer\CMakeFiles\CMakeTmp\cmTC_fe13f.vcxproj" (default targets) -- FAILED.

Build FAILED.

"D:\Users\q\Downloads\ethminer-master\ethminer-master\ethminer\CMakeFiles\CMakeTmp\cmTC_fe13f.vcxproj" (default target) (1) ->

(ClCompile target) -> 

  D:\Users\q\Downloads\ethminer-master\ethminer-master\ethminer\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [D:\Users\q\Downloads\ethminer-master\ethminer-master\ethminer\CMakeFiles\CMakeTmp\cmTC_fe13f.vcxproj]

    0 Warning(s)

    1 Error(s)

Time Elapsed 00:00:00.18

**Comment by xsacha** [comment]
What if you run:
`cmake -G "Visual Studio 11 2012" ..`
instead?

**Comment by hahann0099** [comment]
Hello xsacha,

Thank you for the fast response :)

I've tried running your command and I get another error.

CMakeError at  D:\Program Files\CMake\share\cmake-3.9/Modules/FindCUDA.cmake:649 (message):
Specify CUDA_TOOLKIT_ROOT_DIR

I've manually installed cmake so that the cmake command could work.

**Comment by ruslo** [comment]
@hahann0099 please stop posting random errors with your setup. It's a Hunter bugtracker, I'm expecting discussion of errors related to Hunter.
