### ISSUE TITLE
cmake --build . command error

### ISSUE THREAD

**Issue by hahann0099** [ruslo/hunter#869]
Hello,

I was running the "cmake --build ." command and got an error with boost/algorithm/string.hpp.
I checked the boost folder and it does appear that string.hpp exists.

C:\ethminer-master\ethminer\build>cmake --build .
Microsoft (R) Build Engine version 4.7.2046.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 2017-07-06 11:11:04 PM.
Project "C:\ethminer-master\ethminer\build\ALL_BUILD.vcxproj" on node 1 (defaul
t targets).
Project "C:\ethminer-master\ethminer\build\ALL_BUILD.vcxproj" (1) is building "
C:\ethminer-master\ethminer\build\ZERO_CHECK.vcxproj" (2) on node 1 (default ta
rgets).
InitializeBuildStatus:
  Creating "Win32\Debug\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild" because "Alway
  sCreate" was specified.
CustomBuild:
  All outputs are up-to-date.
FinalizeBuildStatus:
  Deleting file "Win32\Debug\ZERO_CHECK\ZERO_CHECK.unsuccessfulbuild".
  Touching "Win32\Debug\ZERO_CHECK\ZERO_CHECK.lastbuildstate".
Done Building Project "C:\ethminer-master\ethminer\build\ZERO_CHECK.vcxproj" (d
efault targets).

Project "C:\ethminer-master\ethminer\build\ALL_BUILD.vcxproj" (1) is building "
C:\ethminer-master\ethminer\build\ethminer.vcxproj" (3) on node 1 (default targ
ets).
InitializeBuildStatus:
  Touching "ethminer.dir\Debug\ethminer.unsuccessfulbuild".
CustomBuild:
  All outputs are up-to-date.
ClCompile:
  D:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\bin\CL.exe /c /I"C:\et
  hminer-master\ethminer\.." /Zi /nologo /W3 /WX- /Od /Ob0 /Oy- /D WIN32 /D _WI
  NDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:prec
  ise /Zc:wchar_t /Zc:forScope /GR /Fo"ethminer.dir\Debug\\" /Fd"ethminer.dir\D
  ebug\vc110.pdb" /Gd /TP /analyze- /errorReport:queue "C:\ethminer-master\ethm
  iner\main.cpp"
  main.cpp
c:\ethminer-master\ethminer\MinerAux.h(32): fatal error C1083: Cannot open incl
ude file: 'boost/algorithm/string.hpp': No such file or directory [C:\ethminer-
master\ethminer\build\ethminer.vcxproj]
Done Building Project "C:\ethminer-master\ethminer\build\ethminer.vcxproj" (def
ault targets) -- FAILED.

Done Building Project "C:\ethminer-master\ethminer\build\ALL_BUILD.vcxproj" (de
fault targets) -- FAILED.

Build FAILED.

"C:\ethminer-master\ethminer\build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\ethminer-master\ethminer\build\ethminer.vcxproj" (default target) (3) ->
(ClCompile target) ->
  c:\ethminer-master\ethminer\MinerAux.h(32): fatal error C1083: Cannot open in
clude file: 'boost/algorithm/string.hpp': No such file or directory [C:\ethmine
r-master\ethminer\build\ethminer.vcxproj]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.99

**Comment by ruslo** [comment]
What exactly makes you think that this is a Hunter issue? :)

**Comment by hahann0099** [comment]
Hello ruslo,

Thank you for the quick comment.

I am not very certain if it is a hunter issue, but I came here by reading https://github.com/ruslo/hunter/wiki/error.external.build.failed, as it was the only help I could find.

I was hoping if it is a hunter issue, you could help out and if not, someone could please help guide me in the right place to ask :)

**Comment by ruslo** [comment]
> but I came here by reading https://github.com/ruslo/hunter/wiki/error.external.build.failed, as it was the only help I could find

Actually this page said that the reason of the failure is inside package itself and not in Hunter.

> someone could please help guide me in the right place to ask :)

Stackoverflow is a nice place to ask general questions about CMake: https://stackoverflow.com/
