### ISSUE TITLE
CMAKE_VS_DEVENV_COMMAND is not absolute

### ISSUE THREAD

**Issue by isavegas** [ruslo/hunter#871]
Attempting to configure [Ethminer](https://github.com/ethereum-mining/ethminer) at commit [f99ca](https://github.com/ethereum-mining/ethminer/tree/f99ca98229ce54707cf7bc7d99c61c64e0481862) throws the following error:
```
> cmake .. -G "Visual Studio 15 2017 Win64" -DETHASHCUDA=ON -DETHASHCL=OFF -DETHSTRATUM=ON

-- [hunter] Calculating Config-SHA1
-- [hunter] Calculating Toolchain-SHA1
-- [hunter] HUNTER_ROOT: C:/.hunter
-- [hunter] [ Hunter-ID: 435b09a | Config-ID: 61c532d | Toolchain-ID: 3a4fa27 ]

[hunter ** INTERNAL **] CMAKE_VS_DEVENV_COMMAND is not absolute
[hunter ** INTERNAL **] [Directory:C:/Users/isavegas/Git/ethminer]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_setup_msvc.cmake:127 (hunter_internal_error)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_finalize.cmake:114 (hunter_setup_msvc)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_add_package.cmake:23 (hunter_finalize)
  CMakeLists.txt:86 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/isavegas/Git/ethminer/build/CMakeFiles/CMakeOutput.log".
```
CMakeOutput.log can be found here: [https://pastebin.com/JCptEmqk](https://pastebin.com/JCptEmqk).
Setting ```-DCMAKE_VS_DEVENV_COMMAND``` and/or environment variable ```CMAKE_VS_DEVENV_COMMAND``` to the path to VS 2017's ```devenv.exe``` has no effect.

**Comment by ruslo** [comment]
Try to run this project:
```cmake
cmake_minimum_required(VERSION 3.0)
project(foo)

message("CMAKE_VERSION: ${CMAKE_VERSION}")
message("CMAKE_VS_DEVENV_COMMAND: ${CMAKE_VS_DEVENV_COMMAND}")

```

**Comment by isavegas** [comment]
Works with ```-G "Visual Studio 14 2015 Win64"```, so I assume it's an issue with VS 2017 support.

**Comment by ruslo** [comment]
What do you mean by "works"? `CMAKE_VS_DEVENV_COMMAND` is empty for VS 2017? Can you try latest CMake version?

**Comment by isavegas** [comment]
The error doesn't exist when using the VS 2015 generator. I've been using CMake 3.8.2. When using the VS 2015 generator, `CMAKE_VS_DEVENV_COMMAND` is `C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/devenv.com`, and with VS 2017, it is just `devenv.com`.
Passing `-DCMAKE_VS_COMMAND="C:/Program Files (x86)/Microsoft Visual Studio/Common7/IDE/devenv.com" doesn't affect the value output by CMake.

**Comment by ruslo** [comment]
>  I've been using CMake 3.8.2

Try latest CMake version.

**Comment by kapulkin** [comment]
I have the same issue with CMake 3.9.0

>[hunter ** INTERNAL **] CMAKE_VS_DEVENV_COMMAND is not absolute
>[hunter ** INTERNAL **] [Directory:D:/Users/Stas/Documents/Projects/Small/ethminer]
>
>------------------------------ WIKI -------------------------------
>    https://github.com/ruslo/hunter/wiki/error.internal
>-------------------------------------------------------------------
>
>CMake Error at C:/.hunter/_Base/Download/Hunter/0.19.14/d4216c8/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
>Call Stack (most recent call first):
>  C:/.hunter/_Base/Download/Hunter/0.19.14/d4216c8/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
>  C:/.hunter/_Base/Download/Hunter/0.19.14/d4216c8/Unpacked/cmake/modules/hunter_setup_msvc.cmake:127 (hunter_internal_error)
>  C:/.hunter/_Base/Download/Hunter/0.19.14/d4216c8/Unpacked/cmake/modules/hunter_finalize.cmake:114 (hunter_setup_msvc)
>  C:/.hunter/_Base/Download/Hunter/0.19.14/d4216c8/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
>  CMakeLists.txt:87 (hunter_add_package)

**Comment by ruslo** [comment]
@kapulkin what is the result of buillding this project:
```cmake
cmake_minimum_required(VERSION 3.0)
project(foo)

message("CMAKE_VERSION: ${CMAKE_VERSION}")
message("CMAKE_VS_DEVENV_COMMAND: ${CMAKE_VS_DEVENV_COMMAND}")
```

**Comment by ruslo** [comment]
https://github.com/ruslo/hunter/issues/751#issuecomment-317257280
