### ISSUE TITLE
OpenCV bitcode

### ISSUE THREAD

**Issue by ikliashchou** [ruslo/hunter#873]
Actually trying to compile iOS framework with OpenCV 3.2.0 statically linked and have issues with archiving the project:

`ld: bitcode bundle could not be generated because '/Users/HUNTER_ROOT/_Base/0dd355c/ee52902/928d405/Install/lib/libopencv_core.a(convert.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7`

I'm using hunter 0.19.27 and polly toolchain ios-10-3-dep-8-0-bitcode.cmake with bitcode enabled.

I have made already changes for OpenSSL to support bitcode with adapting the scheme for iOS bitcode, should I do the same for OpenCV to make it correctly linking or am I doing something wrong?

**Comment by ruslo** [comment]
Build with verbose log and take a look at compile/link stages of OpenCV library. Do you see bitcode flags? Probably OpenCV rewrite compiler/linker options?

**Comment by ikliashchou** [comment]
As you may see from the log below, OpenCV seems to ignore CXX_FLAGS set before it. At least -fembed-bitcode is not there

But, what is more interesting, it adds -fembed-bitcode-marker for all kind of configs (both Debug and Release) on compile (see log below)

Config log
----

-- General configuration for OpenCV 3.2.0 =====================================
--     Host:                        Darwin 16.6.0 x86_64
--     Target:                      Darwin
--     CMake:                       3.8.2
--     CMake generator:             Xcode
--     CMake build tool:            /usr/bin/xcodebuild
--     Xcode:                       8.3.3
--   C/C++:
--     Built as dynamic libs?:      NO
--     C++ Compiler:                /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++  (ver 8.1.0.8020042)
--     C++ flags (Release):         -std=c++11 -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG -O3 -fomit-frame-pointer -ffast-math  -DNDEBUG

--     C++ flags (Debug):           -std=c++11 -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
--     C flags (Release):           -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fPIC   -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG

Actual compile log
------
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x c++ -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -Wno-trigraphs -fpascal-strings -O3 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-return-type -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wno-unused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DCMAKE_INTDIR=\"Release-iphoneos\" -D__OPENCV_BUILD=1 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -miphoneos-version-min=8.0 -Wno-sign-conversion -Wno-infinite-recursion -Wno-move -fembed-bitcode-marker -I/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build/lib/Release/include -I/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build -I/_Base/xxxxxxx/cd4937f/928d405/Install/include/eigen3 -I/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Source/modules/core/include -I/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Source/modules/core/src -I/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build/modules/core -I/_Base/xxxxxxx/cd4937f/928d405/Install/include -I/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build/modules/core/OpenCV.build/Release-iphoneos/opencv_core.build/DerivedSources/armv7 -I/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build/modules/core/OpenCV.build/Release-iphoneos/opencv_core.build/DerivedSources -Wmost -Wno-four-char-constants -Wno-unknown-pragmas -F/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build/lib/Release -std=c++11 -fPIC -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -Wno-comment -fdiagnostics-show-option -Qunused-arguments -Wno-semicolon-before-method-body -fno-omit-frame-pointer -mfpu=neon -fvisibility=hidden -fvisibility-inlines-hidden -DNDEBUG -fomit-frame-pointer -ffast-math -DNDEBUG -I/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build -isystem /_Base/xxxxxxx/cd4937f/928d405/Install/include/eigen3 -I/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Source/modules/core/include -I/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Source/modules/core/src -I/_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build/modules/core -isystem /_Base/xxxxxxx/cd4937f/928d405/Install/include -MMD -MT dependencies -MF /_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build/modules/core/OpenCV.build/Release-iphoneos/opencv_core.build/Objects-normal/armv7/arithm.d --serialize-diagnostics /_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build/modules/core/OpenCV.build/Release-iphoneos/opencv_core.build/Objects-normal/armv7/arithm.dia -c /_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Source/modules/core/src/arithm.cpp -o /_Base/xxxxxxx/cd4937f/928d405/Build/OpenCV/Build/OpenCV-Release-prefix/src/OpenCV-Release-build/modules/core/OpenCV.build/Release-iphoneos/opencv_core.build/Objects-normal/armv7/arithm.o

**Comment by ruslo** [comment]
> CXX_FLAGS set before it. At least -fembed-bitcode is not there

This flag should not be in CMAKE_CXX_FLAGS. Bitcode controlled by Xcode attribute `CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE` so it's fine.

> it adds -fembed-bitcode-marker for all kind of configs

This one added by Xcode because of `CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE`. I guess it's valid.

As a summary everything looks good, I don't know why you have `was built without full bitcode` error. May be we have to set more Xcode attributes?

**Comment by ikliashchou** [comment]
https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9

> The marker or -fembed-bitcode-marker option for Bitcode is only useful for testing. You can have an app with Bitcode Enabled, using a binary from a library that was built with the -fembed-bitcode-marker setting, for example, and it'll work fine while you're testing. But if you try to Archive your app, you'll get an error such as this:
>`ld: bitcode bundle could not be generated because ‘{project dir}/path/to/SomeLib.a’ was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture arm64`

So, to have actual bitcode embedded in static libraries we should have `-fembed-bitcode` for `Release` configurations for all modules

**Comment by ikliashchou** [comment]
And this goes beyond OpenCV, I noticed that JPEG, ZLIB, PNG, TIFF (all used by OpenCV but are separate packages) also do not contain actual bitcode.

**Comment by ruslo** [comment]
It means issue is in Polly toolchain.

**Comment by ruslo** [comment]
We should rethink this https://github.com/ruslo/polly/pull/151

**Comment by ikliashchou** [comment]
I can extend CMAKE_CXX_FLAGS with `-fembedd-bitcode` for `Release` in  polly/flags/bitcode.cmake 

What do you think?

**Comment by ruslo** [comment]
I think there should be Xcode attribute that we can use. What native Xcode users do? See https://stackoverflow.com/a/35225379/2288008 for hints.

**Comment by ikliashchou** [comment]
There is attribute CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE :)
But as we already know it adds `-fembed-bitcode-marker` instead of `-fembed-bitcode`.

As we use Debug and Release configurations only when building packages, we never actually do `Archive` and this means no actual bitcode in libraries. 

I think the only way to build `full bitcode` static libraries for packages without using `archive` is to add `-fembed-bitcode` to Release configuration for both `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS` in polly/flags/bitcode.cmake.

**Comment by ruslo** [comment]
> bitcode bundle could not be generated because

I was not able to reproduce this problem with the simple executable + library example. Can you create [sscce](http://www.sscce.org/) ?

**Comment by ruslo** [comment]
Okay, I can reproduce it by trying to "Archive". Fix that works for me: https://github.com/ruslo/polly/commit/540b1135eb9a2cfb3b8f61f8623e14de8e089c23

@ikliashchou can you try latest Polly?

**Comment by ikliashchou** [comment]
I tried myself and it worked.

But, this means debug libraries will be also built with bitcode, and this will add extra time but actually useless.

Is it possible to make change in polly to add `-fembed-bitcode` for release configuration and `-fembed-bitcode-marker` for debug configuration in both `CMAKE_C_FLAGS` and `CMAKE_CXX_FLAGS`?

I'm not so familiar with cmake yet :)

**Comment by ruslo** [comment]
> this will add extra time but actually useless
> -fembed-bitcode-marker for debug configuration

Why do we need any flags at all for Debug in this case?

> Is it possible to make change in polly to add -fembed-bitcode for release configuration

Yes, `CMAKE_CXX_FLAGS_RELEASE` will do the trick. Note that it means that MinSizeRel/RelWithDebInfo will not have them.

**Comment by ikliashchou** [comment]
I have a project where I build a number of my own libraries, that depend on OpenCV, for example, and framework, that maintains all together. Then this framework is used with the app that is built not via cmake, but native Xcode. 

In the app ENABLE_BITCODE is set to YES, means that it expects my framework to have at least -fembed-bitcode-marker in Debug as well.

I found another post [here](https://stackoverflow.com/questions/31486232/how-do-i-xcodebuild-a-static-library-with-bitcode-enabled)

**Comment by ruslo** [comment]
I guess it means
```
CMAKE_CXX_FLAGS_RELEASE -fembed-bitcode
CMAKE_CXX_FLAGS_DEBUG -fembed-bitcode-marker
CMAKE_CXX_FLAGS_MINSIZEREL -fembed-bitcode
CMAKE_CXX_FLAGS_RELWITHDEBINFO -fembed-bitcode
```

(plus `CMAKE_C_FLAGS_*` version?)

@ikliashchou can you test such toolchain and submit pull request to Polly? You have to update `HUNTER_TOOLCHAIN_UNDETECTABLE_ID` to avoid conflict with old bitcode toolchain.

**Comment by ikliashchou** [comment]
I found out that adding only this line to `bitcode.cmake` instead of all discussed before solves the problem:

`set(CMAKE_XCODE_ATTRIBUTE_BITCODE_GENERATION_MODE "bitcode")`

Should I still update `HUNTER_TOOLCHAIN_UNDETECTABLE_ID` in pull request?

**Comment by ruslo** [comment]
> Should I still update HUNTER_TOOLCHAIN_UNDETECTABLE_ID in pull request?

Yes
