### ISSUE TITLE
SDL2::SDL2-static is not static on Windows 10 with Visual Studio 2015

### ISSUE THREAD

**Issue by mchiasson** [ruslo/hunter#899]
I haven't tried other versions of Windows, and haven't tried other IDEs other than Visual Studio 2015

Here's the part where I link `SDL2::SDL2-static` to my `MutCube` sample app
```
    target_link_libraries(MutCube
        SDL2::SDL2-static
        ${OPENGL_LIBRARIES}
        glm
    )
```

And here's what I get when I run the app:
![image](https://user-images.githubusercontent.com/961637/28525367-fc8a146e-7051-11e7-8e8b-9c6c350b2dec.png)

**Comment by ruslo** [comment]
It's clearly not a Hunter issue, it's a SDL2 issue. Also just for your information: https://github.com/ruslo/hunter/pull/896

**Comment by mchiasson** [comment]
It's not an SDL2 issue.  To build SDL2 statically, hunter was supposed to pass `-DSDL_STATIC=1` down to SDL's cmake build.

**Comment by ruslo** [comment]
There is standard CMake variable to control static/shared:
* https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

There is no need to invent new one. Project should respect standard variables, it's a requirement for now:
* https://docs.hunter.sh/en/latest/creating-new/cmake.html#default-behavior

**Comment by mchiasson** [comment]
I agree that SDL2 has not been following the recommended way for dealing with shared vs static.

**Comment by ruslo** [comment]
@mchiasson I think it's improved by @wheybags in https://github.com/ruslo/hunter/pull/896 pull request. Can you try https://github.com/ruslo/hunter/releases/tag/v0.19.39 release?

**Comment by ruslo** [comment]
Closing inactive.
