### ISSUE TITLE
Need to build boost with a custom define

### ISSUE THREAD

**Issue by madmongo1** [ruslo/hunter#906]
Hi, I need to ensure that boost is build with the cxx_flag -DCMAKE_CXX_FLAGS=-DBOOST_SP_USE_SPINLOCK set.

This is to prevent a known segfault bug when using Boost::log

What should I put in the hunter.config file?

I have tried

hunter_config(Boost VERSION 1.64.0 CMAKE_ARGS=-DCMAKE_CXX_FLAGS=-DBOOST_SP_USE_SPINLOCK)

But this has no effect (or at least I cannot see this flag attached to the Boost targets in BoostConfig.cmake.

What is the correct procedure to ensure that boost is built the way I need?

Thank you in advance.

**Comment by ruslo** [comment]
> CMAKE_ARGS=-DCMAKE_CXX_FLAGS=-DBOOST_SP_USE_SPINLOCK

It should be `CMAKE_ARGS CMAKE_CXX_FLAGS=-DBOOST_SP_USE_SPINLOCK`. But I'm not sure if it will work :)

> But this has no effect (or at least I cannot see this flag attached to the Boost targets in BoostConfig.cmake

It will not have any effect at `BoostConfig.cmake`. If you want such feature you have to introduce it first. For now such macro like `BOOST_ALL_NO_LIB=1` or `NOMINMAX` used only while building Boost itself:
* https://github.com/ruslo/hunter/blob/382aec18eba519d49c34491106a8e125cbc035e0/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L213-L223

Flags like `-DANDROID`/`-std=c++11`/`-isysroot` should came from toolchain, i.e. will be used globally for all projects. Hence there is no need to add them to `BoostConfig.cmake`.

**Comment by ruslo** [comment]
Closing inactive discussion.

**Comment by jdonald** [comment]
Related: For iOS armv7 (32-bit) we're hitting the problem that recent versions of Boost can't even build with the default stdlib=libstdc++.

We need to pass `CMAKE_CXX_FLAGS="-stdlib=libc++"`. However, as indicated in the ticket description it doesn't work to set this in the toolchain file, whether directly or via including polly's library/std/libcxx.cmake. As @ruslo said above it also won't work to do:
```
hunter_config(Boost VERSION 1.67.0-p1 CMAKE_ARGS CMAKE_CXX_FLAGS=-stdlib=libc++)
```
#1204 added support for CMAKE_ARGS but doesn't specifically address compiler flags among those, and what's the point of [these three lines](https://github.com/ruslo/hunter/blob/master/cmake/projects/Boost/schemes/url_sha1_boost_ios_library.cmake.in#L151-L153) if the toolchain CMAKE_CXX_FLAGS aren't actually getting passed down?

Ultimately what has worked for us is editing those lines in url_sha1_boost_library.cmake.in to force `cxxflags=-stdlib=libc++` in the bjam/b2 options in our fork of hunter. I wonder if I'm missing something or if there's currently no way to build iOS 32-bit Boost out of the box without extending url_sha1_boost_ios_library.cmake.in.

**Comment by ruslo** [comment]
> Related: For iOS armv7 (32-bit) ... We need to pass CMAKE_CXX_FLAGS="-stdlib=libc++"

@jdonald your issue and scenario is not matching original issue at all. I don't understand why you think that adding a comment to the closed discussion is a good idea.

**Comment by jdonald** [comment]
Because just as in the original ticket, this was exactly the scenario of needing to build boost with a custom entry in CMAKE_CXX_FLAGS (even if not a #define flag as in @madmongo1's case).

Fortunately we were able to resolve the iOS Boost build problem (without passing more to CMAKE_CXX_FLAGS) by raising our target iOS version. clang defaults to -stdlib=libstdc++ when the target version is iOS 6.0 or older, but with 7.0 or newer it defaults to -stdlib=libc++ which may explain why it's unlikely for others to hit this issue nowadays.

Since then we've come across other needed flags with this problem, but that's a larger discussion so we'll file a separate ticket.

**Comment by ruslo** [comment]
> Because just as in the original ticket, this was exactly the scenario of needing to build boost with a custom entry in CMAKE_CXX_FLAGS

Original issue was about Boost specific macro and your question is about global compiler flag. In general try to avoid adding comments/questions to the closed issues unless it's absolutely necessary.
