### ISSUE TITLE
CURL with IDN support

### ISSUE THREAD

**Issue by chfast** [ruslo/hunter#910]
Looks like CURL enabled IDN support if it find suitable library in the system (https://github.com/curl/curl/blob/master/CMakeLists.txt#L520). This makes the package not cachable, because cached library depends on system library that might not be installed. See failing build: https://circleci.com/gh/ethereum-mining/ethminer/138.

I'm not sure my conclusion is right, but CURL should expose an option to build with/without IDN support.

**Comment by ruslo** [comment]
Fixed here:
* https://github.com/hunter-packages/curl/commit/1db60165bea90cfd256303f80aafe3a535df8c94

Will apply it soon.

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/releases/tag/v0.19.50
