### ISSUE TITLE
Update nlohmann/json package

### ISSUE THREAD

**Issue by v1bri** [ruslo/hunter#914]
Since the Hunter fork of [nlohmann/json](https://github.com/nlohmann/json) some updates to the project's CMake settings seem to have made it possible to remove the fork. I have tested this out with a local HUNTER_ROOT and the [v2.1.1 release](https://github.com/nlohmann/json/releases/tag/v2.1.1) of nlohmann/json and it seems to work nicely. However the project name has been changed to `nlohmann_json` (from simply `json`), while the Hunter fork refers to it as `nlohmann-json` and in CMakeLists.txt as `nlohmann-json::nlohmann-json`.

I'd like to update Hunter to the project's latest release and avoid breaking current users. Any suggestions on how to proceed? My best guess is to create a new Hunter project that uses the official name (`nlohmann_json`) and indicate on the wiki that `nlohmann-json` is deprecated.

**Comment by ruslo** [comment]
Already dealing with it here:
* https://github.com/ruslo/hunter/pull/907

**Comment by ruslo** [comment]
See https://github.com/ruslo/hunter/commit/9cc93efdee2db17c76670cb198d980cbba95331d
