### ISSUE TITLE
LLVM on VS and NMake

### ISSUE THREAD

**Issue by dvirtz** [ruslo/hunter#918]
Trying to build LLVM on Visual Studio gives the error
```
Broken package:  LLVM build broken on Visual Studio, see: 
http://llvm.1065342.n5.nabble.com/Install-Problem-of-Compiler-rt-with-Visual-Studio-Express-2013-for-Windows-Desktop-td66575.html  
(use MINGW or NMake generators)
```

1. This issue is quite old, wasn't it fixed already?
2. Trying to build with NMake I'm getting
```
[ 60%] Linking CXX static library ..\..\..\..\lib\clang\3.6.2\lib\windows\clang_rt.asan-i386.lib                                                                          
LINK : fatal error LNK1181: cannot open input file '../sanitizer_common/CMakeFiles/RTSanitizerCommonLibc.i386.dir/sanitizer_coverage_mapping_libcdep.cc.obj'              
```
I believe it's due to the filenames being longer than 260. Is there any way to make Hunter use shorter paths?

**Comment by ruslo** [comment]
> I believe it's due to the filenames being longer than 260. Is there any way to make Hunter use shorter paths?

Discussed few times already. I have no good workaround/fix for it. The only way is to minimize `HUNTER_ROOT` path, e.g. try `C:\Hunter`. Note that it's neither Hunter nor CMake issue, it's a limitation of build tools on Windows. CMake is not a build system, it's a generator for real build system, not much we can do.

**Comment by dvirtz** [comment]
Well, after setting HUNTER_BINARY_DIR to avoid the long filenames, I get hit by [this](https://bugs.llvm.org/show_bug.cgi?id=25650) Clang's bug.

Can I get an access to the LLVM packages to see if upgrading the versions can help?

**Comment by ruslo** [comment]
> Well, after setting HUNTER_BINARY_DIR to avoid the long filenames

Oh, yeah, there was one workaround. I haven't check that it's working, may behave incorrectly in some cases, be aware :)

> Can I get an access to the LLVM packages to see if upgrading the versions can help?

You can check it locally/fork, why do you need access? :)

**Comment by dvirtz** [comment]
@ruslo can you make a hunter fork of Compiler RT?
I need it in order to fix the installation when using VS.
I also need new branches for 4.0.1 on https://github.com/hunter-packages/llvm and https://github.com/hunter-packages/clang

**Comment by ruslo** [comment]
> @ruslo can you make a hunter fork of Compiler RT?

https://github.com/hunter-packages/LLVMCompilerRT

> I also need new branches for 4.0.1 on https://github.com/hunter-packages/llvm and https://github.com/hunter-packages/clang

Done
