### ISSUE TITLE
Add testing version in local hunter-config file

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#922]
I'm trying to add a testing version of a hunter package inside a local hunter-config file

in my `cmake/Hunter/config.cmake` file I have the following:
```
include(hunter_add_version)
set(foo_version "0.1.2-testing")
hunter_add_version(
        PACKAGE_NAME
        foo
        VERSION
        ${foo_version}
        URL
        "some-url.tar.gz"
        SHA1
        "some-sha1-of-package"
    )
hunter_config(foo
   VERSION ${foo_version}
)
```

I try to define a new version of an existing hunter package and to immediately use this new testing version

hunter throws an error while configuring
```
[hunter ** FATAL ERROR **] Version not found: 0.1.2-testing. See 'hunter_config' command.
```

**Comment by ruslo** [comment]
You declare `hunter_add_version` inside local `cmake/Hunter/config.cmake`? It's simply not designed to be used so. If you want to test package locally you still have to create Hunter archive with your version. `jenkins.py` can do it for you: https://github.com/ruslo/hunter/wiki/dev.hunter.root#jenkinspy

**Comment by NeroBurner** [comment]
I've got a package in beta stage, which will change its sha1sum very frequently. To release a new hunter bundle for each beta release does not seem practical for me. Is there a way to ignore the sha1sum for some specific beta/testing packages? (no cacheable, download each time etc)

I'd like to add a testing entry for my package. It wouldn't be default, but could be chosen by other devs in the development process. Then the other devs could get always the latest version of the testing package

**Comment by ruslo** [comment]
> I've got a package in beta stage, which will change its sha1sum very frequently

In your example you still have SHA1 of package, so how it's different?

> To release a new hunter bundle for each beta release does not seem practical for me

If we are talking about local testing you can use `jenkins.py`, if you want to share this version you have to make a release anyway.

Take a look at this feature:
* https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html

**Comment by NeroBurner** [comment]
It would be the same url, but different files (and thus different sha1sum)

On July 31, 2017 4:13:30 PM GMT+02:00, Ruslan Baratov <notifications@github.com> wrote:
>> I've got a package in beta stage, which will change its sha1sum very
>frequently
>
>In your example you still have SHA1 of package, so how it's different?
>
>> To release a new hunter bundle for each beta release does not seem
>practical for me
>
>If we are talking about local testing you can use `jenkins.py`, if you
>want to share this version you have to make a release anyway.
>
>Take a look at this feature:
>*
>https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ruslo/hunter/issues/922#issuecomment-319079082

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ruslo** [comment]
> It would be the same url, but different files (and thus different sha1sum)

I understand that. I mean that in the code snippet from your first comment you still have SHA1 of package, so argument "will change its sha1sum very frequently" doesn't play any role. For example for "git-submodule" feature you don't have to change SHA1 - you need to update submodule and Hunter will create new archive automatically if needed.

**Comment by NeroBurner** [comment]
could you elaborate on your example. I don't fully understand it

**Comment by ruslo** [comment]
> could you elaborate on your example. I don't fully understand it

You want to release package very often.

For **now** every package release costs:
* one package release itself
* add SHA1 of package to `cmake/projects/<package>/hunter.cmake`
* release of Hunter
* add SHA1/URL of new Hunter archive to your project

Suggested **by you**:
* one package release itself
* add SHA1 of package to local `cmake/Hunter/config.cmake`

Hunter [Git-submodule integration](https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html):
* Commit changes to submodule

**Comment by NeroBurner** [comment]
Nice, I didn't know about the Git-submodule integration. Handy feature to know

While having this conversation I had an Idea: add `unstable` (or `latest`, `testing`, `master`) version:
- the URL is added to `cmake/projects/<package>/hunter.cmake` without a SHA1
- no SHA1 required

to use it a project must define the version `unstable` (or other fitting keyword) in local `cmake/Hunter/config.cmake`

This would make it possible to have packages upgraded by
- upgrade a branch of a project (for example `hunter` or `master` branch) or
- update the archive the release URL (for example `https://example.com/mypackage/latest.tar.gz`)

Would this feature be possible or even desirable?

**Comment by ruslo** [comment]
That will affect reproducibility, it's a basic feature of Hunter. Without SHA1 you can't check that archive is not broken and that archive is ready to be unpacked. Current mechanism of checking that previous download was successful is to check SHA1, new mechanism need to be introduced here.

Imagine: you're updating often some package, you've sent to developers "unstable" version of Hunter release. Now every time you releasing your package what will happen? Since nothing changed on side of developers they have to do something manually. Remove internal stamps from Hunter? Remove the whole Hunter root? Add new option like `-DHUNTER_FLUSH_PACKAGE=mypackage`? What if you broke something and they want to revert changes? You will leave them with broken version without any way to revert everything back to working state?

Note that current system it's pretty convenient for developers. You've creating release and adding it to CMakeLists.txt. All that developers need to do is to `git pull` latest changes. Build is reproducible and if you want to revert something you can just checkout latest working commit back.

Git-submodule integration feature is convenient for both and doesn't affect reproducibility.

**Comment by NeroBurner** [comment]
Yes, I agree. I haven't thought about it that way

Back to git-submodule: would it be possible to create the source tar ball of just a subdirectory of the submodule?

The `git archive` call would be able to do this `git archive -o ../subarchive.zip HEAD:subdir`
https://stackoverflow.com/a/17351814

**Comment by ruslo** [comment]
> Back to git-submodule: would it be possible to create the source tar ball of just a subdirectory of the submodule?

There is no such feature at this moment.

> The git archive call would be able to do this git archive -o ../subarchive.zip HEAD:subdir

What is the purpose and why we can't use the whole archive?

**Comment by NeroBurner** [comment]
once again pre-compiled C-libraries available for windows (amd64, i386), linux (amd64, i386, armhf), and darwin. I've created a package for these libs, where for each os/architecture combination another URL/SHA1 combination is chosen (using `hunter_check_toolchain_definition`).

```
# determine architecture
include(hunter_check_toolchain_definition)
hunter_check_toolchain_definition(NAME "__amd64__" DEFINED amd64_defined)
hunter_check_toolchain_definition(NAME "_WIN64"    DEFINED WIN64_defined)
hunter_check_toolchain_definition(NAME "__i386__"  DEFINED i386_defined)
hunter_check_toolchain_definition(NAME "_WIN32"    DEFINED WIN32_defined)
hunter_check_toolchain_definition(NAME "__arm__"   DEFINED arm_defined)
hunter_check_toolchain_definition(NAME "__arm64__" DEFINED arm64_defined)
```

My problem is how to add testing versions to hunter. Those testing versions are updated without a schedule (whenever a new feature is added, or a bug is fixed) and the previous archives are overwritten (same URL, different SHA1).
Adding just the stable versions to Hunter works AWESOME. Unfortunately, a few of my colleagues need to use (and test) some features before they are included into the next stable release.
If a dev needs some new feature in the testing package the developer can't use the CI to test his package until the next stable release.

If I add the testing version to a hunter-release the hunter package would be inconsistent with the next update of the testing packages. Therefore I'm looking for an alternative way

**Comment by NeroBurner** [comment]
where should I start to implement such a subfolder feature?

**Comment by ruslo** [comment]
> the previous archives are overwritten (same URL, different SHA1)

You are loosing reproducibility here. This may be okay for your team and your workflow but in my opinion it's a huge flaw in general.

> If I add the testing version to a hunter-release the hunter package would be inconsistent with the next update of the testing packages. Therefore I'm looking for an alternative way

I don't understand this one. Why it's inconsistent?

**Comment by ruslo** [comment]
> once again pre-compiled C-libraries

Hunter already have binary cache with pre-compiled libraries feature. So as alternative you can collect toolchain-id of your users and upload binaries for them. If your sources is private you can protect them with password: https://docs.hunter.sh/en/latest/user-guides/cmake-user/protected-sources.html Actually in final Hunter release you can put invalid URL. Hunter will use only SHA1 of source archive to get SHA1 of archive with binaries.

> GIT_SUBMODULE_DIR. Is the dir variable used for?

It's internal variable, full path to submodule.

**Comment by NeroBurner** [comment]
> I don't understand this one. Why it's inconsistent?

if I add the testing version to a hunter-release it will work until the testing packages are upgraded. With the upgrade the URL stays the same, but the archive behind the URL changes, which results in a different SHA1. Now the testing version in my hunter-release cannot be used anymore

> Hunter already have binary cache with pre-compiled libraries feature. So as alternative you can collect toolchain-id of your users and upload binaries for them. If your sources is private you can protect them with password: https://docs.hunter.sh/en/latest/user-guides/cmake-user/protected-sources.html Actually in final Hunter release you can put invalid URL. Hunter will use only SHA1 of source archive to get SHA1 of archive with binaries.

I don't have access to the sources and I have no Cache server set up yet (CI has LAN access only, so no github)

> It's internal variable, full path to submodule.

is the `hunter_config` function called two times? first with `GIT_SUBMODULE` and then with `GIT_SUBMODULE_DIR`?

**Comment by ruslo** [comment]
> if I add the testing version to a hunter-release it will work until the testing packages are upgraded. With the upgrade the URL stays the same, but the archive behind the URL changes, which results in a different SHA1

That's the general issue, it will be inconsistent with any approach, not just with Hunter.

> Now the testing version in my hunter-release cannot be used anymore

If you're not changing machine and sources already downloaded then everything will be fine actually. If you're not removing root then Hunter will just switch to the old Hunter-ID. If root is removed but downloads are saved then Hunter will check SHA1 of sources and reuse them.

> CI has LAN access only, so no github

As mentioned [here](https://github.com/ruslo/hunter/issues/777) GitHub is no longer a requirement for server. I haven't tried it but I think you can use shared directory with `Cache` in LAN as a server.

> is the hunter_config function called two times? first with GIT_SUBMODULE and then with GIT_SUBMODULE_DIR?

Yes, we need it for calculating Config-ID.

**Comment by NeroBurner** [comment]
Closed in favor of using `hunter_config` with the `GIT_SUBMODULE` flag

https://github.com/ruslo/hunter/issues/927
