### ISSUE TITLE
fix SDL2 package missing toolchains

### ISSUE THREAD

**Issue by wheybags** [ruslo/hunter#925]
- [ ] vs-10-2010
- [ ] vs-12-2013-xp
- [ ] vs-9-2008
- [ ] mingw
- [ ] msys
- [ ] android-ndk-r10e-api-19-armeabi-v7a-neon osx
- [ ] android-ndk-r10e-api-19-armeabi-v7a-neon linux
- [ ] ios-nocodesign-9-3

These are all currently disabled in CI.
The SDL_mixer package should also have these enabled in CI once they are working for the SDL2 package

**Comment by ruslo** [comment]
Moved to https://github.com/hunter-packages/SDL2/issues/1
