### ISSUE TITLE
Libcurl on Windows

### ISSUE THREAD

**Issue by simon-p-r** [ruslo/hunter#926]
Are you willing to accept a PR to improve the libcurl package?  I cannot build with its CMake file as it is not very good see [here](https://github.com/curl/curl/blob/master/CMakeLists.txt#L49).  I need to be able to build libcurl with OpenSSL and libssh2 which is tricky with CMake but rather than roll my own I thought I would try to help improve hunter.

**Comment by ruslo** [comment]
> I cannot build with its CMake file as it is not very good see here.

Have you tried it? CURL builds fine on WIndows:
* https://ci.appveyor.com/project/ingenue/hunter/build/1.0.2082

**Comment by simon-p-r** [comment]
So I need to install other packages other than gate, I was using the tutorial in docs to try Hunter out.

**Comment by ruslo** [comment]
I don't understand your question. If you're using Hunter first time please follow this guides:
* https://docs.hunter.sh/en/latest/quick-start/boost-components.html
* https://github.com/forexample/hunter-simple

And this video:
* https://www.youtube.com/watch?v=TeeLEfT8nCU

**Comment by simon-p-r** [comment]
I cannot link against curl, I have had problems building libssh2 and issues with the wrong OpenSSL library being found so I will make a repos to show problems.

**Comment by ruslo** [comment]
Closing inactive discussion.
