### ISSUE TITLE
hunter_config(foo GIT_SUBMODULE) with subdirectory

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#927]
moving the idea from https://github.com/ruslo/hunter/issues/922 into a new issue

I'd like to add a  feature to `hunter_config`'s `GIT_SUBMODULE` (https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html) to include just one subdirectory of the submodule into the archive.

My problem is the following:

until now I have one tar.gz file per os/architecture with pre-compiled C-libraries. The archives are named `libfoo-<version>-<os>-<architecture>.tar.gz` with the following content
```
libfoo-<version>-<os>-<architecture>/
  include/
  lib/
  share/cmake/foo-config.cmake
```
I use the `url_sha1_unpack_install` scheme to extract and use these package archives.

My problem are the testing versions, which have the same architecture, but on update those files are replaced. I think, that I can use hunters `GIT_SUBMODULE` feature and provide a git-repo with the latest testing versions extracted. The root of the repository could look as follows
```
libfoo-0.1.2-windows-amd64-testing
libfoo-0.1.2-linux-amd64-testing
libfoo-0.1.2-linux-i386-testing
libfoo-0.1.2-linux-armhf-testing
```
Each folder having the `lib`, `include` and `share` folders.
I could update the versions in the repository if a new testing version is released, and the using project stays consistent.

In the project I would add the submodule to `3rdparty/libfoo` and to the local `cmake/Hunter/config.cmake` file I'd add
```
# set(OS ...)
# set(ARCHITECTURE ...)
hunter_config(foo GIT_SUBMODULE "3rdparty/libfoo" GIT_SUBMODULE_SUBDIR "libfoo-0.1.2-${OS}-${ARCHITECTURE}-testing")
```

**Comment by ruslo** [comment]
To keep things consistent with caching mechanism I suggest using special `CMAKE_ARGS` like `HUNTER_SUBMODULE_SOURCE_SUBDIR`. Similar to `HUNTER_INSTALL_LICENSE_FILES` https://github.com/ruslo/hunter/issues/656. You should parse `CMAKE_ARGS` to find the value of `HUNTER_SUBMODULE_SOURCE_SUBDIR` and use it in `hunter_pack_git_submodule` function.
