### ISSUE TITLE
boost package broken

### ISSUE THREAD

**Issue by roscopecoltran** [ruslo/hunter#929]
Hi guys,

Hope you are all well !

I wanted to build/add the Boost package to a project, just after updating to the latest version of Hunter/Polly, and got the following error message:

```
cd /Users/roscopecoltran/local/cpp/cmake/hunter/_Base/xxxxxxx/b25a533/8abe383/Build/Boost/Source && /usr/local/Cellar/cmake/HEAD-611f162/bin/cmake -GXcode /Users/roscopecoltran/local/cpp/cmake/hunter/_Base/xxxxxxx/b25a533/8abe383/Build/Boost/Source
CMake Error: The source directory "/Users/roscopecoltran/local/cpp/cmake/hunter/_Base/xxxxxxx/b25a533/8abe383/Build/Boost/Source" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make[1]: *** [/Users/roscopecoltran/local/cpp/cmake/hunter/_Base/xxxxxxx/b25a533/8abe383/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Debug/Boost-configure] Error 1
Command /bin/sh failed with exit code 2
```

Any idea how to fix it ?

Have a good day !

Cheers,

**Comment by ruslo** [comment]
> _Base/xxxxxxx/b25a533/8abe383

`xxxxxxx` means that you're using Hunter from Git, please try regular last version.

**Comment by roscopecoltran** [comment]
Unfortunatelly, I have the same message. 

I tried:

**Hunter:**
```
### Hunter snapshot that will be used ###
include("cmake/HunterGate.cmake")
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.19.20.tar.gz"
    SHA1 "54c6499f084f17de02c7d081acd98583ac5d9442"
    LOCAL
)
```

**config.cmake**
```config.cmake
set(DLIB_CMAKE_ARGS
  DLIB_HEADER_ONLY=OFF #all previous builds were header on, so that is the default
  DLIB_ENABLE_ASSERTS=OFF #must be set on/off or debug/release build will differ and config will not match one
  HUNTER_INSTALL_LICENSE_FILES=dlib/LICENSE.txt
  )

hunter_config(dlib VERSION ${HUNTER_dlib_VERSION} CMAKE_ARGS "${DLIB_CMAKE_ARGS}")

hunter_config(Boost VERSION 1.62.0)
```
**CMake:**
```
cmake --version
cmake version 3.9.20170802-g611f1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by ruslo** [comment]
> URL "https://github.com/ruslo/hunter/archive/v0.19.20.tar.gz"

> hunter_config(Boost VERSION 1.62.0)

What about latest release and default Boost version?

Just for your info Xcode is tested with `osx-10-11` toolchain, latest build results:
* https://travis-ci.org/ingenue/hunter/builds/251672065

**Comment by PickApig** [comment]
same error.

**Comment by ruslo** [comment]
@PickApig With default Boost version? With 1.62 Boost version? Latest Hunter release?

**Comment by PickApig** [comment]
@ruslo thanks for your your reply :) , with this 
HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.19.73.tar.gz"
    SHA1 "d2cb11ad1f454bf14adafd9ff54d6accebe405b7"
)

**Comment by PickApig** [comment]
@ruslo 
CMake Error: The source directory "/home/ubuntu/.hunter/_Base/d2cb11a/0452b62/83c9441/Build/Boost/Source" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
CMakeFiles/Boost.dir/build.make:108: recipe for target 'Boost-prefix/src/Boost-stamp/Boost-configure' failed
make[2]: *** [Boost-prefix/src/Boost-stamp/Boost-configure] Error 1
make[1]: *** [CMakeFiles/Boost.dir/all] Error 2
make: *** [all] Error 2
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Boost.dir/all' failed
Makefile:83: recipe for target 'all' failed


cmake version 3.9.20170817-gd3760

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by ruslo** [comment]
> /home/ubuntu/.hunter/_Base

@PickApig Error is not the same. Original issue was about OSX and Xcode and you're on Linux. Please open new issue, add `HUNTER_STATUS_DEBUG=ON` on configure step and attach build log.

**Comment by ruslo** [comment]
CMake issue, closing.

Details: https://github.com/ruslo/hunter/issues/976#issuecomment-324262499
