### ISSUE TITLE
can't use hunter_check_toolchain_definition in cmake/Hunter/config.cmake

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#931]
I'm trying to determine my build architecture in `cmake/Hunter/config.cmake`
```
# determine architecture
include(hunter_check_toolchain_definition)
hunter_check_toolchain_definition(NAME "__amd64__" DEFINED amd64_defined)
hunter_check_toolchain_definition(NAME "_WIN64"    DEFINED WIN64_defined)
hunter_check_toolchain_definition(NAME "__i386__"  DEFINED i386_defined)
hunter_check_toolchain_definition(NAME "_WIN32"    DEFINED WIN32_defined)
hunter_check_toolchain_definition(NAME "__arm__"   DEFINED arm_defined)
hunter_check_toolchain_definition(NAME "__arm64__" DEFINED arm64_defined)
```

The following line in `hunter_check_toolchain_definition` fails:
https://github.com/ruslo/hunter/blob/a645723ba976e7ef705e81eb66c3a0551102871a/cmake/modules/hunter_check_toolchain_definition.cmake#L46
```
  # the toolchain path must be set
  hunter_test_string_not_empty("${HUNTER_TOOLCHAIN_ID_PATH}")
```

can we somehow determine the toolchain earlier in the process or create a temporary toolchain file to parse with `hunter_check_toolchain_definition`?

**Comment by ruslo** [comment]
> can we somehow determine the toolchain earlier in the process

Actually I think it's possible since Toolchain-ID is about global things and not about particular packages. Toolchain-ID calculated in `hunter_calculate_toolchain_sha1`, Config-ID calculated in `hunter_calculate_config_sha1`. They both called in `hunter_finalize`. But I'm afraid impact will be huge because we need to change order
```
[ Hunter-ID | Config-ID | Toolchain-ID ]
```
to
```
[ Hunter-ID | Toolchain-ID | Config-ID]
```

As alternative since `hunter_finalize` processed after toolchain was read by CMake you can use `WIN32`, `CMAKE_SYSTEM_NAME`, `CMAKE_ANDROID_ARCH_ABI`, etc. variables.

**Comment by NeroBurner** [comment]
I'm looking through `hunter-apply_gate_settings` and created a rough call structure

- `hunter_apply_gate_settings`
  - `hunter-calculate_self`
    - set(hunter_self)
  - `hunter_set_config_location`
    - set(config_location)
  - `hunter_calculate_config_sha1(hunter_self, hunter_base, config_location as user_config)
    - include(default_config)
    - include(user_config)
    - create unified `config.cmake` (includeing normal `hunter_config` calls and ones with `GIT_SUBMODULE`)
    - calculate SHA1 of `config.cmake` and set as `HUNTER_GATE_CONFIG_SHA1
  - `hunter_calculate_toolchain_sha1`
    - set(local_toolchain_info) to `tmpdir/toolchain.info`
    - copy `hunter/scripts/create_toolchain-info.cmake` to `tmpdir/CMakeLists.txt`
    - prepare cmake cmd
    - `hunter_print_cmd`
    - run cmake cmd in tmpdir
    - calculate SHA1 of `local_toolchain_info`-file and set as `HUNTER_GATE_TOOLCHAIN_SHA1
    - make path `hunter_base/HUNTER_GATE_SHA1/HUNTER_GATE_CONFIG_SHA1/HUNTER_GATE_TOOLCHAIN_SHA1
    - set path as `hunter_toolchain_id_path`
    - copy `local_toolchain_info`-file to `hunter_toolchain_id_path/toolchain.info`

we could split `hunter_calculate_toolchain_sha1` into `hunter_calculate_toolchain_local_sha1` and `hunter_move_local_toolchain_to_global_path`. Then we could call `hunter_calculate_toolchain_local_sha1` before `hunter_calculate_config_sha1`.
And also add an optional parameter `TOOLCHAIN_FILE` to `hunter_check_toolchain_definition`

**Comment by ruslo** [comment]
> we could split hunter_calculate_toolchain_sha1 into hunter_calculate_toolchain_local_sha1 and hunter_move_local_toolchain_to_global_path

I think we can keep the `hunter_calculate_toolchain_sha1` name and call second module `hunter_create_toolchain_info`.

> And also add an optional parameter TOOLCHAIN_FILE to hunter_check_toolchain_definition

What for?

**Comment by NeroBurner** [comment]
> I think we can keep the `hunter_calculate_toolchain_sha1` name and call second module `hunter_create_toolchain_info`.

what would each module do? How should we separate the functions?

> What for?

`hunter_check_toolchain_definition` always uses `${HUNTER_TOOLCHAIN_ID_PATH}/toolchain.info`. When we create only a local toolchain file `hunter_check_toolchain_definition` will not find it at the expected location. We could
- create local toolchain-info file
- set `HUNTER_TOOLCHAIN_ID_PATH` to the local file
- call `hunter_calculate_config_sha1`
- move local toolchain info file to global directory

**Comment by ruslo** [comment]
> We could

Sounds like a hack. I think it means that `hunter_calculate_toolchain_sha1` should be called before `hunter_calculate_config_sha1` + swap of `Toolchain-ID` and `Config-ID`.

**Comment by NeroBurner** [comment]
both ways would enable the usage of `hunter_check_toolchain_definition` in global and local hunter config files

- The swap of `Toolchain-ID` and `Config-ID` would be a major change to hunter
- my hack would not change the structure. On the other hand as you stated it is pretty hacky by having `HUNTER_TOOLCHAIN_ID_PATH` pointing to different locations at different times (first to local, then to global)

I leave it to your judgment what the best way is. I'm happy to help and get this feature

**Comment by ruslo** [comment]
> both ways would enable the usage of hunter_check_toolchain_definition in global and local hunter config files

Why? If Toolchain-ID calculated first then `HUNTER_TOOLCHAIN_ID_PATH` will be defined once and never change.

**Comment by NeroBurner** [comment]
I meant those bullet poits in my lasst message as different approaches we could take. all having different impact on hunter. I wanted to provide some Ideas you could chose from or have a better idea :)
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ruslo** [comment]
> The swap of Toolchain-ID and Config-ID would be a major change to hunter

I vote for this one. Seems like a clean solution to the problem.
