### ISSUE TITLE
GIT_SUBMODULE related feature whish/proposal: Dynamic switching between 'package-mode' and 'developer-mode'

### ISSUE THREAD

**Issue by Knitschi** [ruslo/hunter#932]
I just discovered the `GIT_SUBMODULE` feature of hunter and i am excited. I think this will ease the development of hunter packages.

I have been dreaming of a related feature for some time now.
When writing code that uses external packages, I sometimes encounter bugs from which I am not sure if they are caused by false usage of the external library or by a bug in the external library. In these cases I may have to debug into the external libraries to find out what happens. But sometimes I also want to apply a quick change to the external code to get more debug output or to try out a fix for a bug. In this case I would like to be able to open the external library in an IDE and allow incremental builds so I can get changes quickly into my project.

`GIT_SUBMODULE` is a step towards getting this kind of functionality. I can now add the external package as submodule, adjust my `config.cmake` file, edit the package, commit and get the changes into my project. But these steps need to be made manually. Without having tried 'GIT_SUBMODULE' I guess that It will execute the normal hunter process, meaning that it does a full rebuild which can be quiete long (think Qt package).

 What if the `hunter_config()` command pointed to the repository like in this issue (elucideye/drishti/issues/414) at the bottom, and than the user could choose by an option if the package is kept in HUNTER_ROOT, or checked out and build locally in a user defined directory outside the HUNTER_ROOT.

This feature could also be used to split-up and improve scaling of larger code-bases. Developers could easily switch between "developer-mode" for packages they work on often, and "package-mode" for packages that they usually do not change.

For example, in the last job I worked, the department worked on various separated projects. Some were under active development while others where only in maintenance mode. There also were some libraries that were shared between the projects. In this scenario, the active project could include the shared packages in "developer mode" so the could work efficiently on them and always get the latest version when the developer makes a pull. The less active projects could include the packages as 'normal' hunter-packages, fixed to certain version so they do not need to be adjusted to the changes that the active projects make. 

Ideally a package in developer-mode would also be added to project so It could be worked on in the same IDE instance.

So what do you think?

**Comment by headupinclouds** [comment]
@Knitschi : `GIT_SUBMODULE` was a huge improvement for day-to-day development with early stage packages (i.e., there are two "under construction" libraries, where one depends on another), but I still have a need for debugging a hunter managed package from source from the top level project from time to time.  I'm interested in the discussion.

For convenience (and easy debugging), I still revert to local alias targets for submodules that are managed by the `GIT_SUBMODULE` feature.  This doesn't always work in practice, since the installed package can be quite different from the source tree (most significantly the header layout can change). 

Here is the usual clean syntax for a nice upstream CMakeLists.txt files.
```
   # Note: GIT_SUBMODULE in local config file
   #  hunter_config(ogles_gpgpu GIT_SUBMODULE 
   #      "src/3rdparty/ogles_gpgpu" 
   #      
   hunter_add_package(ogles_gpgpu)
   find_package(ogles_gpgpu CONFIG REQUIRED)
```

For debugging, I usually just temporarily insert the following code with a `FOO_USE_LOCAL_BAR=ON` option to enable the local build.
```
  # Support local submodule use or external package:
  option(DRISHTI_USE_LOCAL_OGLES_GPGPU "Use local ogles_gpgpu" ON)

  if(DRISHTI_USE_LOCAL_OGLES_GPGPU)
    option(OGLES_GPGPU_INSTALL "Avoid installation of submodule libraries" ON)
    option(OGLES_GPGPU_BUILD_EXAMPLES "Don't build examples" OFF)
    option(OGLES_GPGPU_VERBOSE "Don't be verbose" OFF)
    add_subdirectory( "${DRISHTI_3RD_PARTY_DIR}/ogles_gpgpu" )
    set(OGLES_GPGPU_LIB ogles_gpgpu)
    add_library(ogles_gpgpu::ogles_gpgpu ALIAS ogles_gpgpu)
  else()

   # Note: GIT_SUBMODULE in local config file
   #  hunter_config(ogles_gpgpu GIT_SUBMODULE 
   #      "src/3rdparty/ogles_gpgpu" 
   #       CMAKE_ARGS ${OGLES_GPGPU_CMAKE_ARGS})

    hunter_add_package(ogles_gpgpu)
    find_package(ogles_gpgpu CONFIG REQUIRED)
  endif()
  set(OGLES_GPGPU_LIB ogles_gpgpu::ogles_gpgpu)
endif()
```

I think some combination of the current `GIT_SUBMODULE` feature + `HUNTER_KEEP_PACKAGE_SOURCES` (specific to the managed package) might be close to what you are looking for.   I actually haven't tried `HUNTER_KEEP_PACKAGE_SOURCES` yet, and am not 100% clear on how that will work with various IDE's, but will try to experiment with this feature next time I have a need for it.

**Comment by Knitschi** [comment]
I had something like this in mind, only that that code would be in hunter and maybe hunter could even add and delete the git submodule depending on the state of the DEVELOPER_MODE / PACKAGE_MODE switch.
But I have to play around with the GIT_SUBMODULE stuff and packages in general before I get a clearer idea about what needed to be done to implement it.

**Comment by ruslo** [comment]
> In this case I would like to be able to open the external library in an IDE and allow incremental builds so I can get changes quickly into my project.

> Ideally a package in developer-mode would also be added to project so It could be worked on in the same IDE instance

Most convenient way is when 3rd party code is a part of main user's project. It means the feature will use `add_subdirectory`.

> think Qt package

I don't think it will be possible to introduce anything for non-CMake projects.

> This doesn't always work in practice, since the installed package can be quite different from the source tree

Yes, that's the main problem. Not all the projects are `add_subdirectory`-friendly.

> I actually haven't tried HUNTER_KEEP_PACKAGE_SOURCES yet, and am not 100% clear on how that will work with various IDE's

It doesn't affect IDE. Sources kept so debugger can find symbols. The rest is the same.

---

I guess Hunter can turn `hunter_add_package(foo)` into `add_subdirectory(3rdparty/foo)` and manage `CMAKE_ARGS`. Package should be `add_subdirectory`-friendly. E.g. not pollute cache - all cache variables should start with [PACKAGE_*](http://cgold.readthedocs.io/en/latest/tutorials/variables/cache.html#recommendation). Plus package should define alias to the targets, like `add_library(ogles_gpgpu::ogles_gpgpu ALIAS ogles_gpgpu)`.

The trickiest part is about adding project from the middle of dependency graph. Say we use `A` and `B`. And both `A` and `B` use `Z`. If we want to load `Z` we have to pull `A` and `B` too! Hunter should load it in correct order. Also both `A` and `B` should have code like this:
```cmake
if(NOT TARGET foo::foo)
  find_package(foo CONFIG REQUIRED)
endif()
```

There are a lot of peculiarities here. It will be hard but I think it's doable.

**Comment by Knitschi** [comment]
Yes, packages will probably need to be written with this in mind to support it. I am currently overhauling my projects cmake code and I want to organize it into multiple small "generic" packages. When this is done I think I will spend some time experimenting with this idea and see if I can design it in a way that one can easily switch between external-packages and project-integrated source code.

**Comment by headupinclouds** [comment]
@Knitschi : Any progress?

As a starting point, I'm thinking about a simple feature that combines [GIT_SUBMODULE](https://docs.hunter.sh/en/stable/user-guides/hunter-user/git-submodule.html) + [HUNTER_KEEP_PACKAGE_SOURCES](https://docs.hunter.sh/en/latest/reference/user-variables.html#hunter-keep-package-sources).

Something like this:
```
hunter_config(foo GIT_SUBMODULE "src/3rdparty/foo" KEEP_PACKAGE_SOURCES)
```

This would seem to provide a developer friendly option for repository/package modularity that retains support for local debugging.  It would be nice not to rebuild an entire project via the global `HUNTER_KEEP_PACKAGE_SOURCES`

@ruslo : Does the above approach and syntax look reasonable?  Any pitfalls with the local variant of KEEP_PACKAGE_SOURCES?

**Comment by ruslo** [comment]
> Any pitfalls with the local variant of KEEP_PACKAGE_SOURCES?

I don't see any **new**. Though same **old** problems as with global `HUNTER_KEEP_PACKAGE_SOURCES` remain. E.g. if you have `hunter_config(foo GIT_SUBMODULE "src/3rdparty/foo)` already and it's build/cached then changing it to `hunter_config(foo GIT_SUBMODULE "src/3rdparty/foo KEEP_PACKAGE_SOURCES)` will not have any effects.

**Comment by Knitschi** [comment]
@headupinclouds : No, I have not yet worked on this although it has been some time since my last post. But I will definately not forget this. But if you want to give it a shot, don't let me stop you ;-). I don't think I will find time to work on this before the year is over.

**Comment by headupinclouds** [comment]
Here is a PR for a simple `KEEP_PACKAGE_SOURCES` option to `hunter_config()` https://github.com/ruslo/hunter/pull/1216

```
hunter_config(GTest GIT_SUBMODULE src/3rdparty/gtest KEEP_PACKAGE_SOURCES)
```

OR

```
hunter_config(GTest VERSION ${HUNTER_GTest_VERSION} KEEP_PACKAGE_SOURCES)
```

> if you have hunter_config(foo GIT_SUBMODULE "src/3rdparty/foo) already and it's build/cached then changing it to hunter_config(foo GIT_SUBMODULE "src/3rdparty/foo KEEP_PACKAGE_SOURCES) will not have any effects.

What is a minimal cache surgery that will allow the `KEEP_PACKAGE_SOURCES` parameter to take effect in such cases.  If we have `PKG_NAME=GTest`:

```
rm $(dirname $(cat _builds/default/_3rdParty/Hunter/install-root-dir))/Build/${PKG_NAME}/cache.sha1
...
```

**Comment by ruslo** [comment]
> rm $(dirname $(cat _builds/default/_3rdParty/Hunter/install-root-dir))/Build/${PKG_NAME}/cache.sha1

The only effect it will have is a broken cache state :)

Option `HUNTER_KEEP_PACKAGE_SOURCES` is a workaround and since it's a workaround I don't see the point of making it better. Masking a problems in such cases will only lead to more confusion when user hit non-trivial cases.

**Comment by headupinclouds** [comment]
Ok.  I guess that is a workaround for lack of support for debugging symbols as described here:

https://github.com/ruslo/CGold/issues/17 : Working with debug symbols
  + lib
  + gdb
  + pdb

**Comment by headupinclouds** [comment]
@Knitschi :  PR https://github.com/ruslo/hunter/pull/1216 was merged (with help from @ruslo) with per package support for `hunter_config( FOO  ... KEEP_PACKAGE_SOURCES)`, which might be of some use to you.

**Comment by ruslo** [comment]
> Can this be done without modifying each package's install() section?

It's really hard to say because there are different approaches on different platforms/compilers. And it may vary even for the one platform+compiler pair (see [Visual Studio "/Z*"](https://github.com/ruslo/CGold/issues/8#issuecomment-339458755)). Need to make a research and figure out some conclusion. Terra incognita for me at this moment.

**Comment by Knitschi** [comment]
@headupinclouds  I will take a look at it when the time has come.

**Comment by ruslo** [comment]
Closing inactive discussion.
