### ISSUE TITLE
error installing ethereum on Mac via homebrew

### ISSUE THREAD

**Issue by yeti-detective** [ruslo/hunter#947]
==> cmake -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -D
Last 15 lines from /Users/cb_yeti/Library/Logs/Homebrew/cpp-ethereum/01.cmake:
    https://github.com/ruslo/hunter/wiki/error.internal
-------------------------------------------------------------------

CMake Error at .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_internal_error.cmake:13 (hunter_wiki)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_calculate_toolchain_sha1.cmake:103 (hunter_internal_error)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_apply_gate_settings.cmake:106 (hunter_calculate_toolchain_sha1)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_finalize.cmake:66 (hunter_apply_gate_settings)
  .brew_home/.hunter/_Base/Download/Hunter/0.19.57/f83ea76/Unpacked/cmake/modules/hunter_add_package.cmake:24 (hunter_finalize)
  CMakeLists.txt:96 (hunter_add_package)

-- Configuring incomplete, errors occurred!
See also "/tmp/cpp-ethereum-20170808-19287-16jjy9w/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/ethereum/homebrew-ethereum/issues

These open issues may also help:
brew install cpp-ethereum error https://github.com/ethereum/homebrew-ethereum/issues/121

**Comment by ruslo** [comment]
Can you build with `HUNTER_STATUS_DEBUG=ON` and attach all logs. even here we should see `"Generate failed: exit with code ...` message, but there is no such.

**Comment by ruslo** [comment]
I've managed to start the install on my local machine. See: https://github.com/ethereum/homebrew-ethereum/issues/121#issuecomment-321241829
