### ISSUE TITLE
custom installation step

### ISSUE THREAD

**Issue by dvirtz** [ruslo/hunter#966]
I'm trying to convert some library to use CMake + Hunter. The library depends on Clang tooling but uses some headers not installed by Clang by copying them manually from the source folder to the installation dir.
Is this possible to achieve within Hunter? Maybe through some custom installation step?

**Comment by ruslo** [comment]
> uses some headers not installed by Clang

Where they came from? They should be linked to some package, if there is no such package you can create new one.

**Comment by dvirtz** [comment]
> Where they came from? 
They are part of Clang's sources.

**Comment by ruslo** [comment]
> They are part of Clang's sources

You can patch Clang to install them. We already have fork anyway. Aside: if they not installed on purpose then they may be the part of private API that can be removed/changed later, it they not installed mistakenly then it should be fixed upstream.

**Comment by dvirtz** [comment]
I agree it's a bad practice, but wouldn't it be useful to enable some custom post package build logic?
I don't want to patch Clang just for this library's use.

**Comment by ruslo** [comment]
> wouldn't it be useful to enable some custom post package build logic?

There is plain and simple functionality in CMake to manage installation. I don't see the point of introducing custom steps and spread the logic.

**Comment by dvirtz** [comment]
OK, I've decided to try to get the library fixed to use only installed headers.
