### ISSUE TITLE
Add protobuf (google protocol buffers)

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#97]
* [Official](https://github.com/google/protobuf) non-cmake

For package: https://github.com/ruslo/hunter/issues/79

**Comment by KerstinKeller** [comment]
In the meantime, protobuf seems to support cmake for Version 3. It is still in beta stage, but it might be worth to have another look at the package.
I would be very interested in hunter supporting protobuf.

**Comment by ruslo** [comment]
> protobuf seems to support cmake for Version 3

I've just noticed that there is a `cmake` directory :) Probably we just need to add a top `CMakeLists.txt` with one command `add_subdirectory(cmake)` and everything will just work.

@KerstinKeller Can you test this solution? Hints: https://github.com/ruslo/hunter/wiki/usr.adding.new.package

**Comment by KerstinKeller** [comment]
Yes, I will have a look. It seems not quite as easy though (at least for
VS2012):
To compile protobuf, you're required to manually check out goolemock/gmock
into the main directory. There is however a realease tar.gz which contains
this folder already, but I cannot compile because of the
"_VARIADIC_TEMPLATE_MAX" default 5 in VS2012 .

I also tried with VS2015 Community (which seems not to be supported by
Hunter yet - probably cmake\modules\hunter_setup_msvc_vcvarsall.cmake will
have to be adapted).

I will  investigate further and update the issue accordingly.

2015-09-30 12:02 GMT+02:00 Ruslan Baratov <notifications@github.com>:

**Comment by ruslo** [comment]
VS2015 should work fine with Hunter. From what I've remember while fixing this bug: https://github.com/forexample/hunter-simple/issues/2

**Comment by ruslo** [comment]
> To compile protobuf, you're required to manually check out goolemock/gmock into the main directory

@KerstinKeller I think `BUILD_TESTING=OFF` might be helpful here?

**Comment by KerstinKeller** [comment]
Ok, I was able to successfully install with hunter and `BUILD_TESTING=OFF`. I changed this in the protobuf cmake. Is there also an option to pass this from protobuf/hunter.cmake file?

And what is the general procedure to make this available then? Need to fork the protobuf project to integrate the changes (mainly additional CmakeLists.txt with `add_subdirectory(cmake)`  in the main directory)?

**Comment by ruslo** [comment]
> Ok, I was able to successfully install with hunter and BUILD_TESTING=OFF. I changed this in the protobuf cmake. Is there also an option to pass this from protobuf/hunter.cmake file?

Yes, you can use `hunter_cmake_args` see example: https://github.com/ruslo/hunter/wiki/usr.adding.new.package#cmake-options

> And what is the general procedure to make this available then? Need to fork the protobuf project to integrate the changes (mainly additional CmakeLists.txt with add_subdirectory(cmake) in the main directory)?

Yes, you can use this repository: https://github.com/hunter-packages/protobuf Use branch `hunter` and keep other branches equal to upstream. Though it make sense to try to apply this patch to the official repository.

**Comment by KerstinKeller** [comment]
Ok, thanks already. So I would probably create the `hunter` branch from the beta-release tag commit, because that's the version to be made available, make my changes and tag it with `3.0.0-beta-1-hunter`.

**Comment by ruslo** [comment]
Cool, thank you

**Comment by tatraian** [comment]
What is the progress of this hunterization? As I see the the mentioned modifications is not in hunter-packages/protobuf repository (disabling test, and root CMakeLists.txt).
I plan to use this library (on the top of ZeroMQ) and if you give me rights to the repository I help to integrate it.
@ruslo When I tried some weeks ago to compile this project I cannot set the path of cmake/CMakeLists.txt. (In this case we can avoid the separated repository). Can I add this as parameter to ExternalParoject_Add command? As I remember I tried -Hcmake/ but it had no effect.

**Comment by ruslo** [comment]
> and root CMakeLists.txt

Should be a trivial task

> disabling test

This can be done by setting default cmake arguments for package in `hunter.cmake`, no need to patch `protobuf` (see [this wiki page](https://github.com/ruslo/hunter/wiki/usr.adding.new.package#cmake-options)).

>  if you give me rights to the repository I help to integrate it

Done. @tatraian You have permissions to push to branches directly but I think it make sense to make a pull request for review/discussion purpose.

> Can I add this as parameter to ExternalParoject_Add command? As I remember I tried -Hcmake/ but it had no effect

As far as I know there is no way to specify this with simple option. The easiest way to do fixes is to add root CMakeLists.txt.

**Comment by tatraian** [comment]
Can I update the forked repository to the current state of original? They released beta-2 in December.
After that I plan to create a branch from the release tag. After I'm going to clone the repository and send pull requests. Is this OK?

**Comment by ruslo** [comment]
>  Is this OK?

@tatraian Sure, it sounds great.

**Comment by ruslo** [comment]
Fixed by https://github.com/ruslo/hunter/pull/340
