### ISSUE TITLE
Update Hunterized glog package

### ISSUE THREAD

**Issue by v1bri** [ruslo/hunter#978]
I'd like to pull the latest glog changes into the Hunterized fork (at least up to [baf6c8b](https://github.com/google/glog/commit/baf6c8b2c5712f70e20a3fc4734267b7c7cbf8b0) and [e1cae33](https://github.com/google/glog/commit/e1cae334a198010b7c4642dfb578552d2bf15adc)). My [pull request](https://github.com/hunter-packages/glog/pull/4) seems to have stalled so I'm opening this issue to keep it on the radar.

**Comment by ruslo** [comment]
> My pull request seems to have stalled

It's closed as far as I can see, not stalled.

> I'm opening this issue to keep it on the radar

Maybe it make sense to open issue here https://github.com/hunter-packages/glog/issues?

**Comment by ruslo** [comment]
Closing for https://github.com/hunter-packages/glog/issues/5
