### ISSUE TITLE
Build Boost with fPIC

### ISSUE THREAD

**Issue by NeroBurner** [ruslo/hunter#979]
I want to use hunter Boost to create a shared library. But when linking Boost to my library I get the error to rebuild Boost with "-fPIC". How do I do that?

**Comment by NeroBurner** [comment]
thanks

**Comment by chfast** [comment]
I noticed that in a CMake toolchain file you can specify
```cmake
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```
This is much simpler and does not break MSVC builds than forcing `-fPIC` flag. But it does not work with Boost packages. Is it possible to support for `CMAKE_POSITION_INDEPENDENT_CODE` in boost build config?

**Comment by ruslo** [comment]
Boost build scheme is using `hunter_dump_cmake_flags`:
* https://github.com/ruslo/hunter/blob/52c85a21a469bf43bf5aec731a7dfcbe9797889e/cmake/projects/Boost/schemes/url_sha1_boost_library.cmake.in#L88-L90

And `CMAKE_POSITION_INDEPENDENT_CODE` seems to be used there already:
* https://github.com/ruslo/hunter/blob/52c85a21a469bf43bf5aec731a7dfcbe9797889e/cmake/modules/hunter_dump_cmake_flags.cmake#L154-L168

So in theory `set(CMAKE_POSITION_INDEPENDENT_CODE ON)` in toolchain aready should work.

**Comment by chfast** [comment]
Ok, I will test it then.

**Comment by Algomorph** [comment]
Example syntax for config.cmake for reference:

hunter_config(Boost VERSION 1.68.0-p1 CMAKE_ARGS CMAKE_POSITION_INDEPENDENT_CODE=ON )

**Comment by ruslo** [comment]
You will need it in another dependent packages as well, so it's better to do it in toolchain:
* https://docs.hunter.sh/en/latest/overview/customization/toolchain-id.html#simple-toolchains

**Comment by Algomorph** [comment]
@ruslo Ah, thanks!
