### ISSUE TITLE
How to use hunter

### ISSUE THREAD

**Issue by nowox** [ruslo/hunter#980]
Yeah this is a very dumb question, but I've read the documentation and tried the demo examples. Now I would like to make my own example. 

I have two GitHub repositories: 

- my-foolib
- my-main

On the main repository I have one main file: 

```
#include <stdio.h>
#include "foo.h"

int main() {
    printf("Foo says %d", foo());
    return 0;
}
```

And of course a `CMakeLists.txt`

```
cmake_minimum_required(VERSION 3.0)

include("cmake/HunterGate.cmake")

include(ExternalProject)

HunterGate(
    URL "https://github.com/ruslo/hunter/archive/v0.10.9.tar.gz"
    SHA1 "53b198e364dc7bc8360fc545f798563229bd7e20"
)

# This one doesn't work 
#HunterGate(
#    URL "https://github.mycompany.com/user/my-foolib.git"
#    SHA1 "b9f5026a3dcba667dd685669bd815e53d8709472"
#)

# This one doesn't work either
#ExternalProject_Add(
#   FooLib
#   URL "https://github.mycompany.com/user/my-foolib.git"
#   URL_HASH SHA1=b9f5026a3dcba667dd685669bd815e53d8709472
#)    

project(Demo)
add_executable(demo main.c)
```

So ... I haven't figured out how I can simply create simple dependencies

Is there anything in the Hunter documentation?

**Comment by ruslo** [comment]
```
# This one doesn't work 
#HunterGate(
#    URL "https://github.mycompany.com/user/my-foolib.git"
#    SHA1 "b9f5026a3dcba667dd685669bd815e53d8709472"
#)

# This one doesn't work either
#ExternalProject_Add(
#   FooLib
#   URL "https://github.mycompany.com/user/my-foolib.git"
#   URL_HASH SHA1=b9f5026a3dcba667dd685669bd815e53d8709472
#)
```

Why do you think this should work? Make no sense at all. Read documentation again.

> So ... I haven't figured out how I can simply create simple dependencies

Creating new package:
* https://docs.hunter.sh/en/latest/creating-new.html

If you are planning to change your dependency often it make sense to use Git submodule integration:
* https://docs.hunter.sh/en/latest/user-guides/hunter-user/git-submodule.html

**Comment by nowox** [comment]
I am deeply sorry, but I don't understand it. Yes I did the tutorial for new package, but I rather want to retrieve my package from y Git repository. I don't want to have it as a submodule because if I have 10 projects that use the exact same version of that heavy library I will multiply the history of this library 10 times. I prefer to let my package manager store the library on my `HUNTER_ROOT` path. 

So yes I hoped it worked that way because:  I would like to link my main application to a sub project which can be called "ExternalProject". Form the tutorial, if I need to ZLib I just have to write `use hunter_add_package(ZLIB)`, but I have no idea how hunter finds out where to fetch zlib from. What is if I want to do `hunter_add_package(myownpackage)` ? How can I tell hunter where to find it?

I am very sorry. I am completely new to package managers. I've tried conan.io, cpm and now hunter. I've read the documentation of all of them and I still don't understand what are their philosophy. Hunter seems to be the simplest one though. 

My requirement is the following: 

- My team and I are developing firmware for embedded devices we have to deal with: 
  - Different compilers
  - Different architectures
- We want to have reusable modules (SPI accelerometer, heart-rate library, ...)
  - Each module is stored on our GitHub Enterprise instance
  - Each project have dependencies on these modules

My goal is to find a package manager that can: 

- Take care of the dependencies
- Store the used modules at one location only
- Avoid to use submodules or subtree as people usually make a lot of mistakes with these adv. features

So I naively thought that `hunter` can fulfill my needs. 

Am I wrong?

**Comment by ruslo** [comment]
> Yes I did the tutorial for new package, but I rather want to retrieve my package from y Git repository

There is no such feature.

> I don't want to have it as a submodule because if I have 10 projects that use the exact same version of that heavy library I will multiply the history of this library 10 times.

Submodules are handy for active development of external projects. If external project is stable then you should create archive with release and add it to Hunter.

> but I have no idea how hunter finds out where to fetch zlib from

First page of documentation will answer that question:
* https://docs.hunter.sh/en/latest/overview/what-is-it.html

> So I naively thought that hunter can fulfill my needs

From my undestanding Hunter can handle this, see no problems.

**Comment by xsacha** [comment]
You can make a custom version of Hunter (fork it) and then add projects in cmake/projects/<libname> that use your git repositories.
Make sure it is also in the cmake/configs/default.cmake
Then when you hunter_add_package(<libname>) you will receive the one you created, from your git repository.

**Comment by ruslo** [comment]
Closing inactive discussion.
