### ISSUE TITLE
build OpenSSL 1.1.0f  on msvc

### ISSUE THREAD

**Issue by katmatus** [ruslo/hunter#985]
Is it possible to build  OpenSSL 1.1.0f  on msvc  with hunter? I've installed Perl and configure hunter to install OpenSSL 1.1.0f, cause in default.cmake it is 1.0.2l.  I configured perl with option no-asm
and after I have build step error.
 -- OpenSSL configure command succeeded.

  Performing build step for 'OpenSSL'

  makefile:55: *** missing separator. Stop.

**Comment by ruslo** [comment]
It's broken, somebody have to fix it:
https://github.com/ruslo/hunter/blob/bc16efecbcba48612899ee36b0b4d065069ab0a2/cmake/configs/default.cmake#L102-L107

**Comment by ruslo** [comment]
Fixed: https://github.com/ruslo/hunter/releases/tag/v0.19.134
