### ISSUE TITLE
Add hdf5

### ISSUE THREAD

**Issue by ruslo** [ruslo/hunter#99]
* Official?
* CMake port? https://github.com/mmarat/hdf5-v16-cmake

Used by: https://github.com/ruslo/hunter/issues/79

**Comment by oliverdaniell** [comment]
@ruslo I have made an initial attempt at porting hdf5 to hunter, it would be great to get some feedback before I create a pull request.

I have started from the official svn repos at 
https://svn.hdfgroup.uiuc.edu/hdf5/tags/hdf5-1_8_15
https://svn.hdfgroup.uiuc.edu/szip/tags/szip-hdf5-1.8.15
I've patched the cmakes to use a hunter version of zlib and szip and then uploaded a tarball of the source code to https://github.com/oliverdaniell/hunter-projects

I've create a branch with the projects here

https://github.com/oliverdaniell/hunter/tree/v0.11.6-develop/

It can be tested from this release https://github.com/oliverdaniell/hunter/releases/tag/v0.11.6-seebyte-p5 using the examples/hdf5 folder

**Comment by ruslo** [comment]
> I've patched the cmakes to use a hunter version of zlib and szip and then uploaded a tarball of the source code to

Let's do it in more centralized fashion. I've created two projects:
* https://github.com/hunter-packages/hdf5
* https://github.com/hunter-packages/szip

and added you to the team so you have full access to this repositories.

hdf5 release uploaded as a binary: https://github.com/hunter-packages/hdf5/releases/download/v1.8.15/hdf5-1.8.15-hunter.tar.gz
same for szip: https://github.com/hunter-packages/szip/releases/download/v2.1.0/szip-2.1.0-hunter.tar.gz

Also I guess the best alternative is to have some automatic svn -> git converter so we have smooth update procedure and native github released with tags and merges.

**Comment by ruslo** [comment]
> It can be tested from this release https://github.com/oliverdaniell/hunter/releases/tag/v0.11.6-seebyte-p5 using the examples/hdf5 folder

This looks good from the first view. Please send me one pull request per package.

**Comment by oliverdaniell** [comment]
I've set-up https://github.com/hunter-packages/szip as a remote for my local branch but I'm getting a permission denied error. Are the permissions set up properly or am I missing a step?

**Comment by ruslo** [comment]
> but I'm getting a permission denied error

Are you trying to make a pull or push? Pull should work fine. If you want to push you have to accept invitation first so you'll be added to team. Currently your invitation has status "Pending".

**Comment by oliverdaniell** [comment]
> If you want to push you have to accept invitation first
Got it, Thanks!

**Comment by oliverdaniell** [comment]
Pull request for szip https://github.com/ruslo/hunter/pull/206

**Comment by ruslo** [comment]
> Please could you create a pre-release for use in the hdf5 package

Done: https://github.com/ruslo/hunter/releases/tag/v0.12.1

**Comment by oliverdaniell** [comment]
hdf5 pull request https://github.com/ruslo/hunter/pull/208

**Comment by oliverdaniell** [comment]
Once https://github.com/ruslo/hunter/pull/208 is merged we can close this bug

**Comment by ruslo** [comment]
> Once #208 is merged we can close this bug

@oliverdaniell Merged, thanks again
