### ISSUE TITLE
toolchain.info SHA1 affected by CACHE variable

### ISSUE THREAD

**Issue by Osse** [ruslo/hunter#992]
Hi,

I am using a Yocto/Poky toolchain. I don't have a toolchain file for it so I am trying to write my own. I observe a difference in `toolchain.info` based on whether `CMAKE_CXX_FLAGS` is marked `CACHE` or not (see the diff at the end). It makes no difference whether `CMAKE_C_FLAGS` is `CACHE` or not. The value I am using for both is `"-march=armv7-a -mthumb-interwork -mfloat-abi=softfp -mfpu=neon"`.

`CMakeFiles/3.9.1/CompilerIdCXX/CMakeCXXCompilerId.cpp` and `_3rdParty/Hunter/toolchain/_builds/CMakeFiles/3.9.1/CompilerIdCXX/CMakeCXXCompilerId.cpp` are identical to eachother and indentical whether or not I use `CACHE`. The same goes for the equivalent C files. Only the toolchain.info file is different.

Is it correct to use `CACHE` in a toolchain file? Tthis was the advice from `#cmake` on Freenode. Regardless, are the toolchain files supposed to be different?

`0c3ae6b` is when using `CACHE`:
```
--- 4858d34/toolchain.info	2017-08-30 09:03:53.009301666 +0200
+++ 0c3ae6b/toolchain.info	2017-08-30 09:45:53.872436666 +0200
@@ -22,7 +22,9 @@
 #define __ARM_FEATURE_CLZ 1
 #define __ARM_FEATURE_UNALIGNED 1
 #define __ARM_FP 12
+#define __ARM_NEON 1
 #define __ARM_NEON_FP 4
+#define __ARM_NEON__ 1
 #define __ARM_SIZEOF_MINIMAL_ENUM 4
 #define __ARM_SIZEOF_WCHAR_T 32
 #define __ATOMIC_ACQUIRE 2
@@ -110,8 +112,8 @@
 #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2 1
 #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4 1
 #define __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8 1
-#define __GCC_IEC_559 0
-#define __GCC_IEC_559_COMPLEX 0
+#define __GCC_IEC_559 2
+#define __GCC_IEC_559_COMPLEX 2
 #define __GLIBCXX__ 20140716
 #define __GLIBC__ 2
 #define __GNUC_GNU_INLINE__ 1
@@ -199,6 +201,8 @@
 #define __SIZE_MAX__ 4294967295U
 #define __SIZE_TYPE__ unsigned int
 #define __STDC_HOSTED__ 1
+#define __STDC_IEC_559_COMPLEX__ 1
+#define __STDC_IEC_559__ 1
 #define __STDC_ISO_10646__ 201103L
 #define __STDC_NO_THREADS__ 1
 #define __STDC__ 1
```

**Comment by ruslo** [comment]
> I observe a difference in toolchain.info based on whether CMAKE_CXX_FLAGS is marked CACHE or not (see the diff at the end)

Flags should be forced:
* https://github.com/ruslo/polly/blob/master/utilities/polly_add_cache_flag.cmake

Build with CMAKE_VERSION_MAKEFILE=ON. I guess flags not passed to compiler in fact if you're not using CACHE + FORCE.

**Comment by ruslo** [comment]
Closing inactive discussion.
